### ISSUE TITLE
"获取应用" 接口缺少 allow_tags 属性。

### ISSUE THREAD

**Issue by kkistudio** [JeffreySu/WeiXinMPSDK#1000]
"获取应用" 的官方接口是有 allow_tags 属性的，而且老的 QY 库也是有这个属性的，但为何新版本的 Work 库要把该属性注释呢？

///// <summary>
///// 企业应用可见范围（标签）
///// </summary>
//public GetAppInfo_AllowTags allow_tags { get; set; }

**Comment by JeffreySu** [comment]
已修正，感谢！
