### ISSUE TITLE
使用 HangFire 后台任务发送模板消息，微信端收到的{{.data}}内容为空

### ISSUE THREAD

**Issue by dusdong** [JeffreySu/WeiXinMPSDK#1001]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
背景：开发框架是 Abp + Hangfire，Hangfire通过数据库保存任务。

技术实现：
1、通过后台任务 TemplateSendJob.Execute(input) 触发模板发送语句 _messageService.Send(input) 时，微信端收到的{{.data}}消息内容为空；

2、直接调用  _messageService.Send(input) 发送模板消息，一切正常

怀疑是 TemplateSendInput.Data 经过序列化/反序列化之后，SDK就不识别了？

截图：
![tim 20171230095930](https://user-images.githubusercontent.com/3461709/34450599-3d6bc040-ed48-11e7-83f1-2015f7e53ea8.png)

```

 public class TemplateSendInput
    {
        public string AppId { get; set; }

        public string OpenId { get; set; }

        public string TemplateId { get; set; }

        public string Url { get; set; }

        public object Data { get; set; }
    }

public class TemplateSendJob : BackgroundJob<TemplateSendInput>, ITransientDependency
    {
        #region Ctor

        private readonly ITemplateMessageService _messageService;

        public TemplateSendJob(ITemplateMessageService messageService)
        {
            _messageService = messageService;
        }

        #endregion

        public override void Execute(TemplateSendInput input)
        {
            _messageService.Send(input);
        }
    }
```

##### 发现问题的模块

- [x] Senparc.Weixin 版本：当前最新版
- [x] Senparc.Weixin.MP 版本：当前最新版

##### 模块对应的.net版本

- [x] .net 4.6.1

##### 开发环境

- [x] Visual Studio 2017

##### 缓存环境

- [X] 服务器内存缓存（默认）

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by dusdong** [comment]
问题找到了：我在本地跟踪了下，果然是序列号的问题，因为data是匿名类型，无法反序列化。

请问有什么方法可以解决吗？

或者，TemplateApi.SendTemplateMessageAsync() 可以提供一个重载，传入 string 类型的 json 串？

**Comment by JeffreySu** [comment]
按照我们建议的做法，这个data虽然是object类型，最好也是一个确定的类，例如你可以看一下我们的例子：https://github.com/JeffreySu/WeiXinMPSDK/blob/e92261276f79286879fe3cafd53c3ea37c1f1b7d/src/Senparc.Weixin.MP.Sample/Senparc.Weixin.MP.Sample.CommonService/EventService.cs#L162

这样反序列化也不成问题了。

如若不然，你也可以用dynamic试一下。

**Comment by JeffreySu** [comment]
总的来说我们也不建议用匿名的方法，可维护性太差。

**Comment by dusdong** [comment]
是的，我的在业务系统调用时，传递的也是确定的类。

我是想把『发送模板消息』做成一个通用的后台任务 TemplateSendJob.Execute(input) ，只需要传递需要发送的参数 TemplateSendInput 就好了。这时，由于每个模板的data参数不同，只能使用object类来传递，序列化时就丢失了类信息。

因此，目前的条件下，只能把不同的模板都分别做成不同的后台任务，太繁琐了。

**Comment by dusdong** [comment]
另：dynamic 类型也不行

**Comment by JeffreySu** [comment]
关键是data参数下面是一个对象，直接传字符串的话，最后post之前的序列化也会产生问题，如此的话，就需要整个post信息拼接成一个统一的string传入，这样做实在不太好。

**Comment by JeffreySu** [comment]
谢谢讨论，欢迎继续交流，先关闭了。

**Comment by cuibty** [comment]
@dusdong 如何解决的？

**Comment by JeffreySu** [comment]
@cuibty 建议还是创建一个类

**Comment by Vict0r-Chen** [comment]
经测试，把JSON字符串反序列化为`Dictionary<string, TemplateDataItem>`传入即可
