### ISSUE TITLE
SDK卡劵创建最终json错误

### ISSUE THREAD

**Issue by 183328251** [JeffreySu/WeiXinMPSDK#101]
脚本：
Senparc.Weixin.MP.AdvancedAPIs.Card.Card_BaseInfoBase cardInfo = new Senparc.Weixin.MP.AdvancedAPIs.Card.Card_BaseInfoBase();
            cardInfo.brand_name = "巴黎欧莱雅沙龙专属";
            cardInfo.code_type = Senparc.Weixin.MP.Card_CodeType.CODE_TYPE_TEXT;
            cardInfo.color = "Color070";
            Senparc.Weixin.MP.AdvancedAPIs.Card.Card_BaseInfo_DateInfo dateInfo = new Senparc.Weixin.MP.AdvancedAPIs.Card.Card_BaseInfo_DateInfo();
            dateInfo.type = 1;
            dateInfo.begin_timestamp = DateTimeToUnixTimestamp(Convert.ToDateTime("2015-06-15"));
            dateInfo.end_timestamp = DateTimeToUnixTimestamp(Convert.ToDateTime("2015-08-31"));
            cardInfo.date_info = dateInfo;
            cardInfo.description = "-持优惠券在指定沙龙进行小V脸无氨剪染造型服务（使用伊诺雅染膏），可抵扣150元 \n-有效期：2015.06.15-2015.08.31";
            cardInfo.get_limit = 1;
            cardInfo.logo_url = "http://mmbiz.qpic.cn/mmbiz/TjPv4UDp2qWZckqV9hQTicbbTyXX1eGOnT80KiaicxgFwibQpuEVkvSwjz6km8dDoQMznt35V6PicIia1icfLBDk2iadiaA/0";
            cardInfo.notice = "请在结账时出示此页";
            Senparc.Weixin.MP.AdvancedAPIs.Card.Card_BaseInfo_Sku sku = new Senparc.Weixin.MP.AdvancedAPIs.Card.Card_BaseInfo_Sku();
            sku.quantity = 10000;
            cardInfo.sku = sku;
            cardInfo.sub_title = "无氨剪染造型服务（使用伊诺雅染膏）";
            cardInfo.title = "小V脸造型服务减150";
            cardInfo.url_name_type = Senparc.Weixin.MP.Card_UrlNameType.URL_NAME_TYPE_USE_IMMEDIATELY;
            cardInfo.custom_url = "http://testvlook.tsv3.com/m/pincard.html";
            cardInfo.use_limit = 1;
            Senparc.Weixin.MP.AdvancedAPIs.Card.Card_GeneralCouponData card = new Senparc.Weixin.MP.AdvancedAPIs.Card.Card_GeneralCouponData();
            card.default_detail = "";
            card.base_info = cardInfo;
            card.CardType = Senparc.Weixin.MP.CardType.GENERAL_COUPON;
            Response.Write(DateTimeToUnixTimestamp(Convert.ToDateTime("2015-06-11")));
            //Response.Write( Json.ToStringEx(card));
            Senparc.Weixin.MP.AdvancedAPIs.Card.CardCreateResultJson result = Senparc.Weixin.MP.AdvancedAPIs.Card.CardApi.CreateCard(Access_Token, card);

运行后得到的json字符串为
{
    \"card\": {
        \"general_coupon\": {
            \"default_detail\": \"\",
            \"base_info\": {
                \"logo_url\": \"http: 

//mmbiz.qpic.cn/mmbiz/TjPv4UDp2qWZckqV9hQTicbbTyXX1eGOnT80KiaicxgFwibQpuEVkvSwjz6km8dDoQMznt35V6PicIia1icfLBDk2iadiaA/0\",
                \"code_type\": 0,
                \"brand_name\": \"巴黎欧莱雅沙龙专属\",
                \"title\": \"小V脸造型服务减150\",
                \"sub_title\": \"无氨剪染造型服务（使用伊诺雅染膏）\",
                \"color\": \"Color070\",
                \"notice\": \"请在结账时出示此页\",
                \"service_phone\": null,
                \"source\": null,
                \"description\": \"-持优惠券在指定沙龙进行小V脸无氨剪染造型服务（使用伊诺雅染膏），可抵扣150元\\n-有效期：2015.06.15-2015.08.31\",
                \"use_limit\": 1,
                \"get_limit\": 1,
                \"use_custom_code\": false,
                \"bind_openid\": false,
                \"can_share\": false,
                \"can_give_friend\": false,
                \"location_id_list\": null,
                \"date_info\": {
                    \"type\": 1,
                    \"begin_timestamp\": 1434326400,
                    \"end_timestamp\": 1440979200,
                    \"fixed_term\": 0,
                    \"fixed_begin_term\": 0
                },
                \"sku\": {
                    \"quantity\": 10000
                },
                \"url_name_type\": 2,
                \"custom_url\": \"http: //testvlook.tsv3.com/m/pincard.html\"
            },
            \"CardType\": 0
        },
        \"card_type\": 0
    }
}

检测发现该字符串部分字段数据错误正确json为：
var jsonString = "{\"card\":{";
            jsonString += "\"card_type\":\"GENERAL_COUPON\",";
            jsonString += "\"general_coupon\":{";
            jsonString += "\"default_detail\":\"-持优惠券在指定沙龙进行小V脸无氨剪染造型服务（使用伊诺雅染膏），可抵扣200元 -有效期：2015.06.15-2015.08.31\",";
            jsonString += "\"base_info\": {";
            jsonString += "\"code_type\": \"CODE_TYPE_TEXT\",";
            jsonString += "\"logo_url\": \"http://mmbiz.qpic.cn/mmbiz/TjPv4UDp2qWZckqV9hQTicbbTyXX1eGOnT80KiaicxgFwibQpuEVkvSwjz6km8dDoQMznt35V6PicIia1icfLBDk2iadiaA/0\",";
            jsonString += "\"brand_name\": \"巴黎欧莱雅沙龙专属\",";
            jsonString += "\"title\": \"小V脸造型服务减200\",";
            jsonString += "\"sub_title\": \"无氨剪染造型服务（使用伊诺雅染膏）\",";
            jsonString += "\"color\": \"Color070\",";
            jsonString += "\"notice\": \"请在结账时出示此页\",";
            jsonString += "\"service_phone\": \"\",";
            jsonString += "\"description\": \"请在结账时出示此页，由沙龙专业人员进行操作\",";
            jsonString += "\"date_info\": {";
            jsonString += "\"type\": 1,";
            jsonString += "\"begin_timestamp\": 1433980800,";
            jsonString += "\"end_timestamp\": 1440979200";
            jsonString += " },";
            jsonString += "\"sku\": {";
            jsonString += "\"quantity\": 10000";
            jsonString += "},";
            jsonString += "\"use_limit\": 1,";
            jsonString += "\"get_limit\": 1,";
            jsonString += "\"use_custom_code\": false,";
            jsonString += "\"bind_openid\": false,";
            jsonString += "\"can_share\": true,";
            jsonString += "\"can_give_friend\": true,";
            jsonString += "\"location_id_list\": null,";
            jsonString += "\"url_name_type\": \"URL_NAME_TYPE_USE_IMMEDIATELY\",";
            jsonString += "\"custom_url\": \"http: //testvlook.tsv3.com/m/pincard.html\",";
            jsonString += "\"source\": \"\"";
            jsonString += "},";
            jsonString += "\"deal_detail\": \"\"";
            jsonString += "}";
            jsonString += "}";
            jsonString += "}";

是否是我使用SDK创建属性的时候有写错的地方？

**Comment by TYSZCC** [comment]
\"code_type\": 0,  这里的code_type使用枚举值时一定要转成string，不能传入int值。以前可以传int，现在接口改变了

**Comment by JeffreySu** [comment]
@TYSZCC 此问题Close了吗？
