### ISSUE TITLE
导入自定义code(仅对自定义code商户)中的（get_custom_code_mode）缺少

### ISSUE THREAD

**Issue by lisensoft** [JeffreySu/WeiXinMPSDK#1028]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [x] .net 4.5
- [x] .net 4.6.1
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
@lisensoft 能提供一下你说的问题的文档地址吗？

**Comment by lisensoft** [comment]
Senparc.Weixin.MP.AdvancedAPIs.CardApi 中的CreateCardAsync方法中的 BaseCardInfo类型的参数中没有该字段

**Comment by JeffreySu** [comment]
@lisensoft  BaseCardInfo会对很多返回结果生效，不只是 CreateCard 一个，请问文档地址在哪里？我们需要进一步核实一下。谢谢！

**Comment by lisensoft** [comment]
Senparc.Weixin.MP.AdvancedAPIs.Card  Card_BaseInfoBase  中缺少 get_custom_code_mode 属性

**Comment by JeffreySu** [comment]
直接引用或者继承 Card_BaseInfoBase  的类有3个：
* Card_BaseInfoBase （这个是我们需要解决问题的）
* BaseInfoResult（最终是给BaseCardInfoResult用，有11个引用）；
* BaseCardInfo （有11个引用）

如果其他的引用里面不需要用到 get_custom_code_mode  的话，就需要单独为 Card_BaseInfoBase  创建一个类了，而不是使用 Card_BaseInfoBase 了，现在具体是什么样情况？

**Comment by zhongyi112134** [comment]
创建优惠券时调用的该方法，但是单对应的传入对象中 没有   get_custom_code_mode  该字段    @@无法创建自定义code的微信优惠券
 public static class CardApi
    {
        #region 同步方法
        /// <summary>
        /// 创建卡券
        /// </summary>
        /// <param name="accessTokenOrAppId">AccessToken或AppId（推荐使用AppId，需要先注册）</param>
        /// <param name="cardInfo">创建卡券需要的数据，格式可以看CardCreateData.cs</param>
        /// <param name="timeOut">代理请求超时时间（毫秒）</param>
        /// <returns></returns>
        [ApiBind(NeuChar.PlatformType.WeChat_OfficialAccount, "CardApi.CreateCard", true)]
        public static CardCreateResultJson CreateCard(string accessTokenOrAppId, BaseCardInfo cardInfo, int timeOut = Config.TIME_OUT)

**Comment by JeffreySu** [comment]
已在 MP v16.6.15 中发布，感谢两位！
#1672
