### ISSUE TITLE
这行代码计算结果是0

### ISSUE THREAD

**Issue by yangpengfei** [JeffreySu/WeiXinMPSDK#1029]
https://github.com/JeffreySu/WeiXinMPSDK/blob/389728d2f137ccb9f32e2a6225f9df05875d0b0c/Samples/Senparc.Weixin.MP.Sample/Senparc.Weixin.MP.Sample/Controllers/TenPayV3Controller.cs#L162

如果价格是小于1的数字，你这里计算就错了。都是零值。强制转换将小数转成0.

**Comment by JeffreySu** [comment]
最小单位是分。

**Comment by JeffreySu** [comment]
这个demo里面我们预设的最小是1元，实际
