### ISSUE TITLE
经过长时间线上运营发现，获取图文统计数据已发生变更，但是微信官方没有给出文档，导致盛派接口缺少一个重要参数。

### ISSUE THREAD

**Issue by ailongfei** [JeffreySu/WeiXinMPSDK#1033]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
经过长时间线上运营发现，获取图文统计数据已发生变更，但是微信官方没有给出文档，导致盛派接口缺少一个重要参数。

目前发现影响接口
1>Senparc.Weixin.MP.AdvancedAPIs.AnalysisApi.GetUserRead
2>Senparc.Weixin.MP.AdvancedAPIs.AnalysisApi.GetUserReadHour

缺少重要参数  user_source 用户渠道来源，客户很看重这一点。

目前已经采用临时解决方案（通过自行post）解决。

##### 微信官方文档 URL
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421141084

##### 微信官方文档快照（直接复制关键内容到下方）
![tim 20180116092846](https://user-images.githubusercontent.com/7904076/34967735-d93789b4-fa9f-11e7-9c87-383872cdf19c.png)

##### 发现问题的模块

- [v] Senparc.Weixin.MP 版本：v14.8.12.0

##### 模块对应的.net版本

- [v] .net 4.0（已于2017年7月暂时停止更新）
- [v] .net 4.5

##### 开发环境

- [v] Visual Studio 2017

##### 联系方式
Email：longfei.ai@connext.com.cn

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
已经添加，非常感谢！这类小问题也可以直接修改代码后 Pull Request 到 Developer 分支，成为 GitHub 的 Contributor，谢谢！
