### ISSUE TITLE
企业号缺少接口 向员工付款

### ISSUE THREAD

**Issue by 513835749** [JeffreySu/WeiXinMPSDK#1038]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
企业号缺少接口 向员工付款

##### 微信官方文档 URL
https://work.weixin.qq.com/api/doc#11545

##### 微信官方文档快照（直接复制关键内容到下方）
接口调用规则：

给同一个实名用户付款，单笔单日限额2W/2W
不支持给非实名用户打款
一个商户同一日付款总额限额100W
单笔最小金额默认为1元
每个用户每天最多可付款10次，可以在商户平台—API安全进行设置
给同一个用户付款时间间隔不得低于15秒

##### 发现问题的模块
- [ ] Senparc.Weixin.QY 版本：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [x] .net 4.5
- [x] .net 4.6.1
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
@513835749 此前已添加：
https://github.com/JeffreySu/WeiXinMPSDK/blob/1493f7b6636aa4890d08451bbc74ee228fa6649c/src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPay/V3/Universal/TenPayV3.cs#L906

您的贡献我们会记录到本年度，非常感谢！
