### ISSUE TITLE
在webapi下面 ResponseHandler处 一直报缺少根元素

### ISSUE THREAD

**Issue by sun96013** [JeffreySu/WeiXinMPSDK#1039]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
在webapi下面 回调支付结果
出错在ResponseHandler处
            Senparc.Weixin.MP.TenPayLibV3.ResponseHandler payNotifyRepHandler = new Senparc.Weixin.MP.TenPayLibV3.ResponseHandler(null);
            payNotifyRepHandler.SetKey("qYtzS0BH7Wjr1EMXVXTqA4Q66aOaXtei");//配置文件里面的Key

            string return_code = payNotifyRepHandler.GetParameter("return_code");
            string return_msg = payNotifyRepHandler.GetParameter("return_msg");
            string xml = string.Format(@"<xml><return_code><![CDATA[{0}]]></return_code><return_msg><![CDATA[{1}]]></return_msg></xml>", return_code, return_msg);

            if (return_code.ToUpper() != "SUCCESS")
            {
                return xml;
            }

            string out_trade_no = payNotifyRepHandler.GetParameter("out_trade_no");
            //微信服务器可能会多次推送到本接口，这里需要根据out_trade_no去查询订单是否处理，如果处理直接返回：return Content(xml, "text/xml"); 不跑下面代码
            ChangeBillStatus(out_trade_no);
            //验证请求是否从微信发过来（安全）
            if (payNotifyRepHandler.IsTenpaySign())
            {

            }
            else
            {

            }

再用post 模拟post
<xml>
  <appid><![CDATA[wx2421b1c4370ec43b]]></appid>
  <attach><![CDATA[支付测试]]></attach>
  <bank_type><![CDATA[CFT]]></bank_type>
  <fee_type><![CDATA[CNY]]></fee_type>
  <is_subscribe><![CDATA[Y]]></is_subscribe>
  <mch_id><![CDATA[10000100]]></mch_id>
  <nonce_str><![CDATA[5d2b6c2a8db53831f7eda20af46e531c]]></nonce_str>
  <openid><![CDATA[oUpF8uMEb4qRXf22hE3X68TekukE]]></openid>
  <out_trade_no><![CDATA[1409811653]]></out_trade_no>
  <result_code><![CDATA[SUCCESS]]></result_code>
  <return_code><![CDATA[SUCCESS]]></return_code>
  <sign><![CDATA[B552ED6B279343CB493C5DD0D78AB241]]></sign>
  <sub_mch_id><![CDATA[10000100]]></sub_mch_id>
  <time_end><![CDATA[20140903131540]]></time_end>
  <total_fee>1</total_fee>
  <trade_type><![CDATA[JSAPI]]></trade_type>
  <transaction_id><![CDATA[1004400740201409030005092168]]></transaction_id>
</xml>
一直报缺少根元素

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [x] .net 4.5
- [x] .net 4.6.1
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：jerry@ivantech.cn

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
这个方法不是这样用的，直接用ResponseHandler.ParseXML()方法就能生成XML了。

**Comment by sun96013** [comment]
是我没有表达清楚吗

**Comment by sun96013** [comment]
Senparc.Weixin.MP.TenPayLibV3.ResponseHandler payNotifyRepHandler = new Senparc.Weixin.MP.TenPayLibV3.ResponseHandler(null); 这句就过不去了。直接在内部方法里面就报错了

**Comment by JeffreySu** [comment]
@sun96013 我没理解你说的：
```
再用post 模拟post



<bank_type></bank_type>
<fee_type></fee_type>
<is_subscribe></is_subscribe>
<mch_id></mch_id>
<nonce_str></nonce_str>

<out_trade_no></out_trade_no>
<result_code></result_code>
<return_code></return_code>

<sub_mch_id></sub_mch_id>
<time_end></time_end>
<total_fee>1</total_fee>
<trade_type></trade_type>
<transaction_id></transaction_id>

一直报缺少根元素
```
上面的xml是你模拟post的吗？这段XML本来就是缺了根元素，抛错也是很正常呀。
或者你的意思是上面的xml是监控日志里面实际输出的（不是你期望的）》

**Comment by JeffreySu** [comment]
@sun96013  使用WebApi对接MessageHandler方法和Controller几乎是一样的，先关闭啦
