### ISSUE TITLE
MediaApi.UploadForeverMedia 总是返回 media data missing

### ISSUE THREAD

**Issue by jasonwzw** [JeffreySu/WeiXinMPSDK#104]
不知道这个问题为何会产生。
不管我是使用WebClient.UploadFile()这个方法上传
还是你SDK中的MediaApi.UploadForeverMedia()---其中用的是HttpRequest
都会报同样的错误。

**Comment by JeffreySu** [comment]
这个错误应该就是你的文件没有上传，比如看一下流是不是空的，以及流的指针是不是已经在尾部了，导致没有内容上传。

**Comment by jasonwzw** [comment]
开始我也是这么判断的,但是我用同样的代码,只是把URL替换为上传临时素材,就可以成功,这让我很费解.还有其他可能导致这个错误吗?

**Comment by jasonwzw** [comment]
我重新引用了你的完整的SDK,发现的确是可以成功获取media_id的,╮(╯▽╰)╭应该还是我这边的问题,但是同样的代码,只能上传临时素材,不能上永久素材...挺奇怪
