### ISSUE TITLE
扫描二维关注/进入公众号，出现推送提示语接着又出现 “二维码异常，请重新生成!”

### ISSUE THREAD

**Issue by xiezhushu** [JeffreySu/WeiXinMPSDK#1050]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
扫描二维之后，能进入公众号，出现推送提示语接着又出现 **“二维码异常，请重新生成!”**。
 
我试着将整个事件代码注释，还是出现**“二维码异常，请重新生成!”**。
 
事件代码如下：
public override IResponseMessageBase OnEvent_ScanRequest(RequestMessageEvent_Scan requestMessage)
{
	//通过扫描关注
	var responseMessage = CreateResponseMessage<ResponseMessageText>();

	responseMessage.Content = "欢迎关注！";

	return responseMessage;
}

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：4.18.9.17705
- [ ] Senparc.Weixin.MP 版本：14.8.12.17706

##### 模块对应的.net版本

- [x] .net 4.5

##### 开发环境

- [ ] Visual Studio 2015

##### 联系方式
Email：xiezhushu@139.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by xiezhushu** [comment]
扫描关注之后，触发的事件 OnEvent_SubscribeRequest，提示之后，还会出现该提示：**“二维码异常，请重新生成!”**。

如果是通过搜索关注，就不会有该提示。

二维码也重新生成过了，还是存在该问题，能否帮忙查一下，到底是什么引起的问题吗？非常感谢！！！

**Comment by JeffreySu** [comment]
请检查是不是授权给了第三方开放平台。
