### ISSUE TITLE
2.4 将评论标记精选（新增接口）

### ISSUE THREAD

**Issue by sipo1209** [JeffreySu/WeiXinMPSDK#1052]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述

老大，这个接口啥时候能实现
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1494572718_WzHIY

##### 微信官方文档 URL

https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1494572718_WzHIY

##### 微信官方文档快照（直接复制关键内容到下方）

2.4 将评论标记精选（新增接口）

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [x] .net 4.5
- [x] .net 4.6.1
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
@sipo1209 其中 https://api.weixin.qq.com/cgi-bin/comment/list?access_token=ACCESS_TOKEN 接口文档上的返回消息格式有错乱，你那边有 example 吗？

**Comment by JeffreySu** [comment]
已经完成 https://github.com/JeffreySu/WeiXinMPSDK/commit/5921113f4222a8a11843a5e9af78ef7dcd85fc5f

**Comment by sipo1209** [comment]
评论接口: 查看文章评论数据接口 comment/list
请求地址：
https://api.weixin.qq.com/cgi-bin/comment/list?access_token=7_2juXPOMBFLQ-ohcQAqHZSLI6B_6TuPbbKou_B1LL-0uWYIKWIIN3aMzLvLkjMTPMoftYVSHuNw-o3l9yVBmrWVjisZWVrR9LICCMOmOErVtgr3BtcgrnIcm8ut0XJZHf1BUKiTxZbq2rGT-fDQNdABAPCZ
返回结果:
200	OK
Connection: keep-alive
Date: Sat, 17 Mar 2018 03:19:37 GMT
Content-Length: 244
{
    "errcode": 0, 
    "errmsg": "ok", 
    "comment": [
        {
            "user_comment_id": 9, 
            "create_time": 1521255525, 
            "content": "如果有什么大考验的话可能会发现自己啥都没改都白扯了吧", 
            "comment_type": 0, 
            "openid": "oufSm0Xw0nhuha_nWD6AfiZ3rgvA"
        }
    ], 
    "total": 1
}

**Comment by sipo1209** [comment]
comment/list 接口 官网上返回数据格式是正确的，但是我程序里返回的数据能取到OK，但是没有comment的array，显示null

**Comment by sipo1209** [comment]
public class CommentItem
    {
        /// <summary>
        /// 
        /// </summary>
        public int user_comment_id { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public int create_time { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public string content { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public int comment_type { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public string openid { get; set; }

    }


    public class RootWeiXinComment : WxJsonResult
    {
     
        /// <summary>
        /// 
        /// </summary>
        public List<CommentItem> comment { get; set; }

    }

**Comment by JeffreySu** [comment]
已修改
