### ISSUE TITLE
微信获取网页授权Ticket时 报错问题

### ISSUE THREAD

**Issue by zx2200** [JeffreySu/WeiXinMPSDK#1054]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
Core 2.0下Senparc.Weixin.MP.CommonAPIs.GetTicket获取授权时不时会提示
An error occurred while sending the request. 提供给函数的缓冲区太小。
An error occurred while sending the request. 发生了安全错误
经检查发现HTTPWebRequest的问题。自己改写改用HttpClient后解决问题

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [x] Senparc.Weixin.MP 版本：14.8.12
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [x] .net 4.5
- [x] .net 4.6.1
- [ ] .net core

##### 开发环境

- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
@zx2200 有没有在多个环境下测试过？

**Comment by JeffreySu** [comment]
@zx2200 请问具体改写的是什么地方？

**Comment by zhouxin93** [comment]
@JeffreySu 我目前是升级到最新版的SDK没有出现这种问题了。

**Comment by JeffreySu** [comment]
@zhouxin93  OK，THX！
