### ISSUE TITLE
使用EncryptHelper.DecodeUserInfoBySessionId报CryptographicException

### ISSUE THREAD

**Issue by fanyinghao** [JeffreySu/WeiXinMPSDK#1055]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
System.Security.Cryptography.CryptographicException: 填充无效，无法被移除。
   在 System.Security.Cryptography.RijndaelManagedTransform.DecryptData(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount, Byte[]& outputBuffer, Int32 outputOffset, PaddingMode paddingMode, Boolean fLast)
   在 System.Security.Cryptography.RijndaelManagedTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   在 System.Security.Cryptography.CryptoStream.FlushFinalBlock()
   在 System.Security.Cryptography.CryptoStream.Dispose(Boolean disposing)
   在 System.IO.Stream.Close()
   在 Senparc.Weixin.WxOpen.Helpers.EncryptHelper.AES_Decrypt(String Input, Byte[] Iv, Byte[] Key)
   在 Senparc.Weixin.WxOpen.Helpers.EncryptHelper.DecodeEncryptedData(String sessionKey, String encryptedData, String iv)
   在 Senparc.Weixin.WxOpen.Helpers.EncryptHelper.DecodeUserInfoBySessionId(String sessionId, String encryptedData, String iv)

##### 发现问题的模块

- [x] Senparc.Weixin 版本：4.18.12
- [x] Senparc.Weixin.MP 版本：14.8.12
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [x] Senparc.Weixin.WxOpen 版本：1.8.2
- [x] Senparc.Weixin.Cache.Redis 版本：1.3.0
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [ ] .net 4.5
- [x] .net 4.6.1
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [ ] 服务器内存缓存（默认）
- [x] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
测试是正常的，你输入的数据方便给一下吗？或者邮件也可以：www.jeffrey.su@gmail.com。

**Comment by fanyinghao** [comment]
@JeffreySu 已发送数据到你的邮箱

**Comment by JeffreySu** [comment]
@fanyinghao 今天整理issue重新查了一下邮箱，一直没有收到。

**Comment by fanyinghao** [comment]
我重新发了一遍到 www.jeffrey.su@gmail.com ，可以查收下

**Comment by zxz19** [comment]
我猜是不是每次登录都重新生成的SessionId，导致使用DecodeUserxxx方法时,里面得到了失效的SessionKey

**Comment by fanyinghao** [comment]
`SessionId`是交由框架来作缓存管理的

**Comment by zxz19** [comment]
> `SessionId`是交由框架来作缓存管理的 @zxz19

我知道，所以我的意思就是是不是没有处理好session_key的缓存问题，导致微信那边有效的session_key与你服务器传过去的session_key不一致，所以最后就Decode加密数据失败了。我们之前就是犯过这类错误

**Comment by fanyinghao** [comment]
好的，我先检查下逻辑
