### ISSUE TITLE
MemcachedObjectCacheStrategy中Memcached缓存初始化报错

### ISSUE THREAD

**Issue by yuchen1030** [JeffreySu/WeiXinMPSDK#1067]
##### 问题描述
    MemcachedObjectCacheStrategy.RegisterServerList(memcachedConfig) 调用时报"emcachedStrategy静态构造函数异常：未将对象引用设置到对象的实例。"的错误。查看源码发现，先执行私有构造函数进行初始化（用到了_serverlist），但此时给用到了_serverlist 赋值的RegisterServerList尚未执行，因此产生该错误。

##### 发现问题的模块
- [ ] Senparc.Weixin 版本：4.18.14
- [ ] Senparc.Weixin.MP 版本：14.8.12
- [ ] Senparc.Weixin.MP.MVC 版本：5.1.1
- [ ] Senparc.Weixin.Cache.Memcached 版本：1.1.0

##### 模块对应的.net版本
- [x] .net 4.5  

##### 开发环境
- [x] Visual Studio 2013
- [x] Visual Studio 2015
- [ ] Visual Studio 2017
- [x] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认） ok
- [ ] Redis 版本：ok
- [ ] Memcached 版本：出错

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
那段代码是测试用的，其实没有必要运行，已经注释掉，发布v1.2.0，非常感谢！
