### ISSUE TITLE
new MemcachedClientConfiguration(null, null) 报错

### ISSUE THREAD

**Issue by wuball** [JeffreySu/WeiXinMPSDK#1069]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述

分布式缓存报错
var config = new MemcachedClientConfiguration(null, null);

##### 发现问题的模块

- [x] Senparc.Weixin.Cache.Memcached 版本：1.1.0

##### 模块对应的.net版本
- [x] .net core 2.0

##### 开发环境
- [x] Visual Studio 2017

##### 缓存环境

- [x] Memcached 版本：EnyimMemcachedCore 2.0.2

##### 联系方式
Email：JeffreySu@wubo.pro

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
Sample.vs2017编译是通过的，能不能确认一下你那边使用的Maemcached组件版本？

**Comment by wuball** [comment]
[MemcachedClientConfiguration.cs](https://github.com/cnblogs/EnyimMemcachedCore/blob/565ead3fa8737aac31c1d767dfea5a250b5f94ae/Enyim.Caching/Configuration/MemcachedClientConfiguration.cs)

EnyimMemcachedCore 2.0.2, 与 Senparc.Weixin.Cache.Memcached 1.1.0 使用相同版本

**Comment by wuball** [comment]
再次反复测试过
`var config = new MemcachedClientConfiguration(null, null);`
这一行过不了
有没有 netcore2.0 Memcached 的使用例子

**Comment by JeffreySu** [comment]
好的，明白了，那就是还是要多加两个注入的参数

**Comment by JeffreySu** [comment]
@wuball 已经使用.net core 2.0 的注入方式进行了改造，你可以测试一下有问题欢迎继续反馈。

**Comment by JeffreySu** [comment]
如果有任何维恩替请ReOpen此问题，谢谢！
