### ISSUE TITLE
Senparc.Weixin.QY\AdvancedAPIs\OAuth2\OAuth2Api.GetUserId方法参数存在问题

### ISSUE THREAD

**Issue by jonathanpeng** [JeffreySu/WeiXinMPSDK#107]
微信企业号的Oauth验证接口的根据code获取成员信息接口没有agentId参数
请参见：http://qydev.weixin.qq.com/wiki/index.php?title=OAuth%E9%AA%8C%E8%AF%81%E6%8E%A5%E5%8F%A3

**Comment by TYSZCC** [comment]
此问题已经在最新的SDK中处理，感谢您的反馈！
