### ISSUE TITLE
WxAppApi.GetWxaCodeUnlimit方法缺少传递line_color参数

### ISSUE THREAD

**Issue by fanyinghao** [JeffreySu/WeiXinMPSDK#1070]
##### 问题描述
WxAppApi.GetWxaCodeUnlimit方法缺少传递line_color参数

不加入这参数是有什么考虑呢，我可以添加进来

##### 微信官方文档 URL
https://mp.weixin.qq.com/debug/wxadoc/dev/api/qrcode.html

##### 微信官方文档快照（直接复制关键内容到下方）

line_color | Object | {"r":"0","g":"0","b":"0"} | auto_color 为 false 时生效，使用 rgb 设置颜色 例如 {"r":"xxx","g":"xxx","b":"xxx"}
-- | -- | -- | --

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [x] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

**Comment by JeffreySu** [comment]
欢迎提交代码，成为我们的Contributor！

**Comment by JeffreySu** [comment]
已经添加，请检查。
