### ISSUE TITLE
MessageHandler没有处理文件类型的消息

### ISSUE THREAD

**Issue by vejuhust** [JeffreySu/WeiXinMPSDK#1071]
##### 问题描述

将一个非视频、图片类型文件发送给公众号，`MessageHandler`中没有对应的处理逻辑或`RequestMessage*`类型，而是直接调用了`OnUnknownTypeRequest`方法。

截获的微信服务器请求如下——
```xml
<xml>
    <ToUserName>
        <![CDATA[gh_ffffeeeedddd]]>
    </ToUserName>
    <FromUserName>
        <![CDATA[o5lE40xwHOqG8riO_EOZQV3JYCV8]]>
    </FromUserName>
    <CreateTime>1518080539</CreateTime>
    <MsgType>
        <![CDATA[file]]>
    </MsgType>
    <Title>
        <![CDATA[小冰 piano.wav]]>
    </Title>
    <Description>
        <![CDATA[]]>
    </Description>
    <FileKey>
        <![CDATA[AwAAAAAAAABF4n55]]>
    </FileKey>
    <FileMd5>
        <![CDATA[07bee1c012c5ef718514701d42fae10c]]>
    </FileMd5>
    <FileTotalLen>10203788</FileTotalLen>
    <MsgId>6520106268131360945</MsgId>
    <Encrypt>
        <![CDATA[LDlJIR3WMDZ3b3zg7UqmLMJ1fTH/rj7Hr55nfmzfamX4BgSOTScY/5ZoDYzb2esTHFuHNVpqyyFwGjlxVmIAPrh+bTK80APcklA9dCiV4TWAppittpITkktJ1e5KPjJ6GEEPdmq2Fqipd0tfzgLH7Q0F68+PSc3XSbbEvV1fSeccJ2FIZxoikIRO/UZX101BK7cHY/Zn+H3DeDcCDA/0SFg5JrIlWONOY72SEiUkl9Edo4GwrQqN5y6u0zh/apKbi3B6S4xk3Z/66rnFjPS+zN7bT/URCpEDZShUHJqVPa//7BnTm51IvTchTlm01MdM5UCh6pHTuoNrTGmwAy/4ekCGjmD6bcbJbQ7c3D2uH8ej9cKc+xMfEuZkxbHC5I9t6xhPBoZ0L4cvSZGTTu+1Pd/sF4I3lkdBOn2U4dcO7NzacJM3vmSY7hVMOw3eRJhI0nlaiM1mrfO3A8EJouS9nkYAnQyYbV14rscdARVO5f4ipS8336soC00ZbRgmVgKfIpE4phxJMDmiux7ym7s40dwD9WNtxXK4Zk4ePQGrvjLvrx2PbZIUpV//Aing1oS9Lh6OdVhJgFlBd7bs0HlccbhADiYR07k+eG8TdaUNoDKdkXNgYgxGwUpB07e0vfuD2EtIpI0P/b7QrJU1nAw2R/s3imfLmStVlq3CRpTo5ahnhNrSZ8db/hEM3XJsIotVRUQKT4ONFvnI7RLLGWjkNQ==]]>
    </Encrypt>
</xml>
```

##### 微信官方文档 URL

订阅号/服务号无相关文档，但企业号有相关文档：http://qydev.weixin.qq.com/wiki/index.php?title=%E6%B6%88%E6%81%AF%E7%B1%BB%E5%9E%8B%E5%8F%8A%E6%95%B0%E6%8D%AE%E6%A0%BC%E5%BC%8F#file.E6.B6.88.E6.81.AF

##### 微信官方文档快照（直接复制关键内容到下方）

msgtype | 是 | 消息类型，此时固定为：file （不支持主页型应用）

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [x] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [x] .net 4.5
- [x] .net 4.6.1
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email： wei.ye@microsoft.com

**Comment by JeffreySu** [comment]
收到，已列入计划，同时也欢迎推送代码！

**Comment by vejuhust** [comment]
@JeffreySu 谢谢 👍

**Comment by JeffreySu** [comment]
@vejuhust 有两个问题需要进一步确认：
1、普通公众号也有相同的回复吗？
2、你给的接口是“企业号”的，目前已经全部升级到“企业微信”，接口也是一致的吗？

**Comment by JeffreySu** [comment]
@vejuhust 是否方便私信一下Encrypt生成需要的几个关键参数，方便我们做单元测试，谢谢！
Email：zsu@senparc.com

**Comment by vejuhust** [comment]
@JeffreySu 
问题是在普通公众号上遇到的，发现公众号文档上没有说明，但是企业号文档上说明了。我看了一下你的PR，只处理了企业号，实际上公众号部分也需要添加此逻辑。

另外，你需要的东西是以下哪些？
* [ ] AppID
* [ ]  AppSecret
* [ ] Token
* [ ] EncodingAESKey
* [ ] 微信请求原始报文
* [ ] 发送给公众号的二进制文件

**Comment by JeffreySu** [comment]
需要：AppID、Token、EncodingAESKey即可，还有当时的URL参数（Signature等参数）

我测试了企业号，发送文件并没有收到XML，很奇怪。

**Comment by vejuhust** [comment]
@JeffreySu 已经邮件发给你了，标题是“WeiXinMPSDK Issue #1071 Request Details”。

**Comment by JeffreySu** [comment]
@vejuhust OK，这两天我会处理。

**Comment by JeffreySu** [comment]
已创建临时分支：https://github.com/JeffreySu/WeiXinMPSDK/tree/Developer_MessageHandler_file

**Comment by JeffreySu** [comment]
@vejuhust 已经合并到master分支。非常感谢！

PS：单元测试使用了你给的的数据（不提供URL应该是安全的，出于绝对的安全考虑，最好修改一下AESKey）。

**Comment by JeffreySu** [comment]
如果有任何问题请ReOpen此Issue。

**Comment by vejuhust** [comment]
好的，谢谢！辛苦了！
