### ISSUE TITLE
TenPayV3RefundQueryRequestData 能否加入对 每笔退款单详情的解析

### ISSUE THREAD

**Issue by dusdong** [JeffreySu/WeiXinMPSDK#1075]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
TenPayV3RefundQueryRequestData 能否加入对 每笔退款单详情的解析。
从目前已经解析出的信息中，并不能得到本退款总共的退款金额，需要合计退款明细才能够算出来。

##### 微信官方文档 URL
[https://pay.weixin.qq.com/wiki/doc/api/native_sl.php?chapter=9_5](https://pay.weixin.qq.com/wiki/doc/api/native_sl.php?chapter=9_5)

##### 微信官方文档快照（直接复制关键内容到下方）
![image](https://user-images.githubusercontent.com/3461709/36071257-8d0f80f8-0f46-11e8-82b5-995492234247.png)

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [x] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [x] .net 4.5
- [x] .net 4.6.1
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
你说的是这个微信没有提供的接口，需要额外进行获取和计算，是吧？

**Comment by dusdong** [comment]
微信的接口已经提供了截图的那部分信息，但是 TenPayV3RefundQueryRequestData 对象没有对截图的信息进行解析

**Comment by JeffreySu** [comment]
好的，我会跟进。

**Comment by JeffreySu** [comment]
@dusdong 仔细看了一下，你截图的是返回的xml信息，不是请求的，而TenPayV3RefundQueryRequestData 是请求的信息，本身就不包含这些数据，接口TenPayLibV3.RefundQuery()所返回的RefundResult类型，对上述信息已经进行了处理的，请核实。

此外针对TenPayV3RefundQueryRequestData其他缺少的参数已经进行了补足：https://github.com/JeffreySu/WeiXinMPSDK/commit/e3cb2ea48cb3fdc72c16625b66b2a57d12aaecdb
