### ISSUE TITLE
获取图文群发总数据接口 缺少字段

### ISSUE THREAD

**Issue by lojurn** [JeffreySu/WeiXinMPSDK#1077]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
ArticleTotal_Detail 类缺少统计字段

##### 微信官方文档 URL
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421141084

##### 微信官方文档快照（直接复制关键内容到下方）
{ 
   "list": [ 
       { 
           "ref_date": "2014-12-14", 
           "msgid": "202457380_1", 
           "title": "马航丢画记", 
           "details": [ 
               { 
                   "stat_date": "2014-12-14", 
                   "target_user": 261917, 
                   "int_page_read_user": 23676, 
                   "int_page_read_count": 25615, 
                   "ori_page_read_user": 29, 
                   "ori_page_read_count": 34, 
                   "share_user": 122, 
                   "share_count": 994, 
                   "add_to_fav_user": 1, 
                   "add_to_fav_count": 3,
                    "int_page_from_session_read_user": 657283, 
                    "int_page_from_session_read_count": 753486, 
                    "int_page_from_hist_msg_read_user": 1669, 
                    "int_page_from_hist_msg_read_count": 1920, 
                    "int_page_from_feed_read_user": 367308, 
                    "int_page_from_feed_read_count": 433422, 
                    "int_page_from_friends_read_user": 15428, 
                    "int_page_from_friends_read_count": 19645, 
                    "int_page_from_other_read_user": 477, 
                    "int_page_from_other_read_count": 703, 
                    "feed_share_from_session_user": 63925, 
                    "feed_share_from_session_cnt": 66489, 
                    "feed_share_from_feed_user": 18249, 
                    "feed_share_from_feed_cnt": 19319, 
                    "feed_share_from_other_user": 731, 
                    "feed_share_from_other_cnt": 775
               }, //后续还会列出所有stat_date符合“ref_date（群发的日期）到接口调用日期”（但最多只统计7天）的数据
           ]
       },//后续还有ref_date（群发的日期）在begin_date和end_date之间的群发文章的数据
   ]
}

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [X] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [x] .net 4.5
- [x] .net 4.6.1
- [ ] .net core

##### 开发环境

- [X] Visual Studio 2010
- [X] Visual Studio 2010 (SP1)
- [X] Visual Studio 2012
- [X] Visual Studio 2013
- [X] Visual Studio 2015
- [X] Visual Studio 2017
- [] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：lojurn@126.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
收到，已列入计划，也欢迎您直接提交代码，成为我们的Contributor！

**Comment by JeffreySu** [comment]
已经更新，请检查：https://github.com/JeffreySu/WeiXinMPSDK/commit/bb3643fd7b8bba246c3e95d320662f734d872d69

感谢！
