### ISSUE TITLE
关于网页授权的问题

### ISSUE THREAD

**Issue by jackzhum** [JeffreySu/WeiXinMPSDK#1078]
这个也不能算是问题，只是个建议。
我们目前遇到的情况是这样：公司里有多个项目(不同域名)同时使用了网页授权（同一公众号），因为不同的项目里都需要获取微信用户的信息，但是大家都知道目前微信公众号后台网页授权只能填写一个授权域名。
为了解决这个问题我专门写一个授权平台，比如 auth.xxx.com ，然后不同的项目需要授权的时候请求这个地址，由这个授权平台去负责获取code，再跳转回原请求网页。
如果没有用到盛派的接口只需要手工修改下授权的地址就行了，但是因为盛派的接口是封装好了，授权都是统一封装的，无法修改授权地址（除非改源码）。
不知道有没有什么好的解决方案能解决此类问题？

**Comment by JeffreySu** [comment]
可以换换一个思路，不是所有的平台去你的auth.xxx.com获取code，而是你的所有授权都回调到auth.xxx.com，然后由auth.xxx.com授权并跳转到不同的网站。

**Comment by jackzhum** [comment]
@JeffreySu 我竟然没有想到。。。感谢
