### ISSUE TITLE
.net core 微信支付证书问题

### ISSUE THREAD

**Issue by abc52406** [JeffreySu/WeiXinMPSDK#1079]
##### 问题描述
公司项目使用.net core版本，部署在centos下，用到证书发红包时，总是提示“参数错误:订单号字段必填,最长为28个字符”。
.net版本使用下来是没有问题的，所有.net core版本基本照抄.net版本写法。报错后怀疑是.net core写法与.net不一致，但是官网找不到.net core的demo，请问您有测试过.net core在非windows系统下的发红包功能吗？有demo可供借鉴吗？
##### 微信官方文档快照（直接复制关键内容到下方）
https://github.com/JeffreySu/WeiXinMPSDK/blob/master/Samples/Senparc.Weixin.MP.Sample/Senparc.Weixin.MP.Sample/Controllers/TenPayV3Controller.cs
##### 发现问题的模块
- [x ] Senparc.Weixin.MP 版本：
##### 模块对应的.net版本
- [ x] .net core
##### 开发环境
- [x ] Visual Studio 2017
##### 缓存环境
- [x] 服务器内存缓存（默认）
##### 问题代码
            string mchbillno = DateTime.Now.ToString("HHmmss") +Senparc.Weixin.MP.TenPayLibV3.TenPayV3Util.BuildRandomStr(28);
            //本地或者服务器的证书位置（证书在微信支付申请成功发来的通知邮件中）
            string cert = account.CertPhysicalPath;
            //私钥（在安装证书时设置）
            string password = account.CertPassword;

            string nonceStr;//随机字符串
            string paySign;//签名
            var redpackageresult = RedPackApi.SendNormalRedPack(
                account.AppId,
                account.MchID,
                account.WxPayAppSecret,
                cert,
                openid,
                sendername,
                _webUrlService.WebSiteRootIPFormat,
                rptotal,
                sendmsg,
                activityname,
                remark,
                out nonceStr,
                out paySign,
                mchbillno);

            return Json(new
            {
                errorcode = redpackageresult.result_code == "1" ? "200" : "204",
                errormsg = redpackageresult.return_msg,
            });

##### 返回错误
参数错误:订单号字段必填,最长为28个字符.

##### 联系方式
Email：mail@pengbo.info

**Comment by abc52406** [comment]
刚刚测试完，不论是在centos7，还是windows server2012+iis8下，都会报该错误

**Comment by JeffreySu** [comment]
订单号字段应该就是你里面的mchbillno吧？能不能跟踪一下是不是确实发出去了，另外编号的问题也需要关注一下。
这个问题我会一起关注。

**Comment by abc52406** [comment]
请求确实是发送出去了，所以才得到了微信的回应

**Comment by JeffreySu** [comment]
@abc52406 你试过windows下面同样的程序执行情况吗？

**Comment by abc52406** [comment]
我前面的补充评论里面说过了，同样这套代码，.net core版本，运行在windows系统，centos系统，都是同样的报错。
但是在同一台windows系统下，这个代码片段放入.net版本，就能正常使用。

**Comment by JeffreySu** [comment]
@abc52406 OK，那么就是基本可以确定是.net core版本的问题了
