### ISSUE TITLE
MediaApi.GetForeverNews一直失败。

### ISSUE THREAD

**Issue by serveryang** [JeffreySu/WeiXinMPSDK#109]

**Comment by JeffreySu** [comment]
请给一下代码和具体结果，谢谢。

**Comment by zmrbak** [comment]
这个，我最近再用，没出现什么问题。

**Comment by zmrbak** [comment]
var accessToken = Senparc.Weixin.MP.CommonAPIs.AccessTokenContainer.TryGetAccessToken(appId, appSecret);
            //获取模板数据
            String TemplateMediaID = "A53u65xYfun_mujtZ9ZRJaY7ppk9Ky3sMtLdORoOI5s";
            GetNewsResultJson NewsResultJson = MediaApi.GetForeverNews(accessToken, TemplateMediaID);

没问题，@serveryang，看你是不是这样写的。
确保 TemplateMediaID，在微信中能找到的。
