### ISSUE TITLE
消息模拟工具SimulateTool创建的请求无法正常的被NetCore版本项目读取?

### ISSUE THREAD

**Issue by yyjdelete** [JeffreySu/WeiXinMPSDK#1090]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
消息模拟工具http://sdk.weixin.senparc.com/SimulateTool 创建的请求无法正常的被NetCore版本项目读取?(Request.Body为空)

是不是这里处理的有问题(试过手动改了ContentType为`text/xml`之后是能用的). 暂时没有去确认微信发的ContentType是啥.
https://github.com/JeffreySu/WeiXinMPSDK/blob/v14.10.0/src/Senparc.Weixin/Senparc.Weixin/Utilities/HttpUtility/RequestUtility.Post.cs#L273
https://github.com/JeffreySu/WeiXinMPSDK/blob/v14.10.0/src/Senparc.Weixin/Senparc.Weixin/Utilities/HttpUtility/RequestUtility.Post.cs#L166

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [x] Senparc.Weixin.MP 版本：`4.20.0`
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [ ] .net 4.5
- [x] .net 4.6.1
- [x] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
@yyjdelete 这个类型本身不重要，应该是.net core在解析数据的过程中，需要使用到这个ContentType，推测和微信无关。我们会进一步进行确认。
另外给Post犯法加上ContentType可选的参数确实也是一个可以优化的地方，谢谢提醒！

**Comment by JeffreySu** [comment]
@lishewen 这里说的问题已经在你提供的最新更新中解决了，是吧？
