### ISSUE TITLE
memcached缓存中的小问题

### ISSUE THREAD

**Issue by yuchen1030** [JeffreySu/WeiXinMPSDK#1093]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
1、nuget中的  Senparc.Weixin 中好像没有Senparc.Weixin.RegisterServices; 
![image](https://user-images.githubusercontent.com/25839813/36777678-65553906-1ca5-11e8-9d85-dccb57f7d2ee.png)

2、 memcache中未实现GetAll方法；
![11111111111111](https://user-images.githubusercontent.com/25839813/36777672-5e593efe-1ca5-11e8-98a6-f5c0c936f65d.png)

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：4.20.0.0
- [ ] Senparc.Weixin.MP 版本：14.10.0.0
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本
- [x] .net 4.5 

##### 开发环境
- [ ] Visual Studio 2013

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：1.5.0.0
- [ ] Memcached 版本：1.4.0.0
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
对的，Sample里面提供的方法正在做最后的测试和优化，nuget还没有发布，今天我先发布一个。

**Comment by JeffreySu** [comment]
已发布：https://www.nuget.org/packages/Senparc.Weixin/4.20.2

**Comment by yuchen1030** [comment]
苏神，问题2好像没有更新的呢。

**Comment by yuchen1030** [comment]
苏神，问题2好像没有更新的呢。使用最新的4.20.2版本注册memcache缓存时，提示  Nested的类型初始值设定项引发异常。

**Comment by JeffreySu** [comment]
@yuchen1030 不好意思，没有看到，我已经Reopen

**Comment by JeffreySu** [comment]
@yuchen1030 请升级到最新版本，按照Demo的方式注册和使用既可。
