### ISSUE TITLE
WeixinUserInfoResult 缺少 tagid_list 返回

### ISSUE THREAD

**Issue by zhouxin93** [JeffreySu/WeiXinMPSDK#1098]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
微信文档上 获取用户基本信息(UnionID机制) 写明返回了
tagid_list | 用户被打上的标签ID列表
字段。WeixinUserInfoResult 并没有该属性

##### 微信官方文档 URL
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421140839

##### 微信官方文档快照（直接复制关键内容到下方）

headimgurl | 用户头像，最后一个数值代表正方形头像大小（有0、46、64、96、132数值可选，0代表640*640正方形头像），用户没有头像时该项为空。若用户更换头像，原有头像URL将失效。
-- | --
subscribe_time | 用户关注时间，为时间戳。如果用户曾多次关注，则取最后关注时间
unionid | 只有在用户将公众号绑定到微信开放平台帐号后，才会出现该字段。
remark | 公众号运营者对粉丝的备注，公众号运营者可在微信公众平台用户管理界面对粉丝添加备注
groupid | 用户所在的分组ID（兼容旧的用户分组接口）
tagid_list | 用户被打上的标签ID列表

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：程序集 Senparc.Weixin.MP, Version=14.10.0.0
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [x] .net 4.5
- [x] .net 4.6.1
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [1 ] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：215194818@qq.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
已添加，感谢！
也欢迎直接提交代码，Pull Request给我们，成为我们的Contributor，谢谢
