### ISSUE TITLE
ChatApi有问题

### ISSUE THREAD

**Issue by qands** [JeffreySu/WeiXinMPSDK#110]
reciver 的type 应该是string类型
msgtype 应该是string类型
sendchatmessage里 连接是clearnotify的，应该是send

另 chat的回调没有实现啊。 
跪求楼主添加

**Comment by JeffreySu** [comment]
@TYSZCC 这个问题有处理吗？

**Comment by AnnXu** [comment]
Hi,
@qands 1.最新的代码receiver中的type是string类型，msgtype是string类型。
 public class Receiver
    {
        /// <summary>
        /// 接收人类型：single|group，分别表示：群聊|单聊
        /// </summary>
        public string type { get; set; }
        /// <summary>
        /// 接收人的值，为userid|chatid，分别表示：成员id|会话id
        /// </summary>
        public string id { get; set; }
    }

/// <summary>
        /// 消息类型
        /// </summary>
        public string msgtype { get; set; }

2.sendchatmessage链接已改，
var url = string.Format("https://qyapi.weixin.qq.com/cgi-bin/chat/send?access_token={0}", accessToken.AsUrlData());

3. chat的回调已在计划中。

**Comment by JeffreySu** [comment]
“chat的回调”找不到文档对应内容，说的是普通Message推送吗？
