### ISSUE TITLE
建议TenPayV3Result类将xml public 出来。

### ISSUE THREAD

**Issue by jiehanlin** [JeffreySu/WeiXinMPSDK#1101]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述

将xml公布处理，数据库可以只记录部分数据，然后将xml保存到一个字段中，已备分析。
另外，公布xml后，也可以在接口变更后获得更全的数据。

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [x] .net 4.5
- [x] .net 4.6.1
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
已经列入改进计划。

**Comment by jiehanlin** [comment]
从TenPayResult独立来看，是没有意义。但输入的xml实际上都封闭在每一个接口中，并没有开放出来，外部访问不到。如查询接口：
        /// <summary>
        /// 订单查询接口
        /// </summary>
        /// <param name="dataInfo"></param>
        /// <returns></returns>
        public static OrderQueryResult OrderQuery(TenPayV3OrderQueryRequestData dataInfo)
        {
            var urlFormat = ReurnPayApiUrl("https://api.mch.weixin.qq.com/{0}pay/orderquery");
            var data = dataInfo.PackageRequestHandler.ParseXML();//获取XML
            var formDataBytes = data == null ? new byte[0] : Encoding.UTF8.GetBytes(data);
            MemoryStream ms = new MemoryStream();
            ms.Write(formDataBytes, 0, formDataBytes.Length);
            ms.Seek(0, SeekOrigin.Begin);//设置指针读取位置
            var resultXml = RequestUtility.HttpPost(urlFormat, null, ms);
            return new OrderQueryResult(resultXml);
        }

请求数据类有ParseXML()，结果类就没有。我认为开放出来还是有意义的。

**Comment by JeffreySu** [comment]
弄出个OrderQuery来关系就有点乱了，简单地说您到底是希望获取resultXML还是requestXML呢？
