### ISSUE TITLE
comment/list 接口 官网上返回数据格式是正确的，但是我程序里返回的数据能取到OK，但是没有comment的array，显示null

### ISSUE THREAD

**Issue by sipo1209** [JeffreySu/WeiXinMPSDK#1108]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
comment/list 接口 官网上返回数据格式是正确的，但是我程序里返回的数据能取到OK，但是没有comment的array，显示null

##### 重现问题步骤（如果可以）
200	OK
Connection: keep-alive
Date: Sat, 17 Mar 2018 03:19:37 GMT
Content-Length: 244
{
    "errcode": 0, 
    "errmsg": "ok", 
    "comment": [
        {
            "user_comment_id": 9, 
            "create_time": 1521255525, 
            "content": "如果有什么大考验的话可能会发现自己啥都没改都白扯了吧", 
            "comment_type": 0, 
            "openid": "oufSm0Xw0nhuha_nWD6AfiZ3rgvA"
        }
    ], 
    "total": 1
}

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [x] .net 4.5
- [x] .net 4.6.1
- [ ] .net core 1.x
- [ ] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by sipo1209** [comment]
应该加上这个

public class CommentItem
    {
        /// <summary>
        /// 
        /// </summary>
        public int user_comment_id { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public int create_time { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public string content { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public int comment_type { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public string openid { get; set; }

    }


    public class RootWeiXinComment : WxJsonResult
    {
     
        /// <summary>
        /// 
        /// </summary>
        public List<CommentItem> comment { get; set; }

    }

**Comment by sipo1209** [comment]
msg_data_id | 是 | Uint32 | 群发返回的msg_data_id
-- | -- | -- | --
index | 否 | Uint32 | 多图文时，用来指定第几篇图文，从0开始，不带默认返回该msg_data_id的第一篇图文
begin | 是 | Uint32 | 起始位置
count | 是 | Uint32 | 获取数目（>=50会被拒绝）
type | 是 | Uint32 | type=0 普通评论&精选评论 type=1 普通评论 type=2 精选评论

**Comment by sipo1209** [comment]
5个参数，后台只实现了前两个！？？？？？？

**Comment by JeffreySu** [comment]
非常感谢！官方文档给的JSON很乱，所以没有实施，源代码里面有注释的，现在应该可以补全了 👍

**Comment by JeffreySu** [comment]
你上面提供的参数说明的表格，好像不是用于这个接口的？

**Comment by JeffreySu** [comment]
已修改 https://github.com/JeffreySu/WeiXinMPSDK/blob/2cd6ab92d78e28e2ef4474ca2f8f93f62ec8cca6/src/Senparc.Weixin.MP/Senparc.Weixin.MP/AdvancedAPIs/Comment/CommentJson/ListResultJson.cs#L48
