### ISSUE TITLE
接口中删除了图片素材，为何微信后台还是能看到，而且没办法删除

### ISSUE THREAD

**Issue by a444739916** [JeffreySu/WeiXinMPSDK#111]
接口中删除了图片素材，为何微信后台还是能看到，而且没办法删除。

**Comment by a444739916** [comment]
大家都没遇到过这个问题吗？

**Comment by TYSZCC** [comment]
你确定一下是删除的永久素材吗？我测试过，是可以删除的。也可能你上传了同样图片到后台，把一张删了，但是留下来的一样的误以为是没有删除。

**Comment by a444739916** [comment]
我删除以后，看微信后台的素材的总数就没有变化。在我自己的后台，删除的图片是会消失的
