### ISSUE TITLE
微信h5支付，微信外浏览器支付实现 实体类接口未更新

### ISSUE THREAD

**Issue by yaols** [JeffreySu/WeiXinMPSDK#1111]
问题描述
微信h5支付，微信外浏览器支付实体类接口未更新.
贵公司实体类TenPayV3UnifiedorderRequestData中SceneInfo 封装字段与最新接口文档有很大差异
贵公司实体类接口文档Url
https://pay.weixin.qq.com/wiki/doc/api/H5.php?chapter=9_1
微信接口最新文档
https://pay.weixin.qq.com/wiki/doc/api/H5.php?chapter=9_20&index=1

开发环境如下
Senparc.Weixin.MP 版本
Visual Studio 2017

我有发邮件给贵公司。很遗憾的事，贵公司直接无视了我。

##### 联系方式
Email：2912166657@qq.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
非常感谢！已经列入计划中。

PS：不好意思，确实没收到邮件，可能被归到垃圾邮箱了 😈

**Comment by JeffreySu** [comment]
已经修改，请查看。

**Comment by yaols** [comment]
我已经成功接收。谢谢您的帮助！
