### ISSUE TITLE
求教：AccessTokenContainer.TryGetAccessToken

### ISSUE THREAD

**Issue by sipo1209** [JeffreySu/WeiXinMPSDK#1113]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
AccessTokenContainer.TryGetAccessToken
只能判断如果没有token才获取token
可是有没有一个函数能自动判断token过期了，重新获取token
也就是说，当返回40001错误的时候自动判断错误代码，然后自动刷新token？

是说再次获取token的刷新方法需要我自己实现?

能不能给个内置的一劳永逸的方法~

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [x] .net 4.5
- [x] .net 4.6.1
- [ ] .net core 1.x
- [ ] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
我们几乎所有的高级接口，你只需要输入AppId，会自动判断是否过期，过期会重新获取，不需要你手动调用TryGetAccessToken()方法来使用AccessToken操作。此方法只在你确实需要看一下目前AccessToken，或者强制刷新的时候用到。
