### ISSUE TITLE
IMessageHandlerDocument.FinalResponseDocument comment issue

### ISSUE THREAD

**Issue by vabc3** [JeffreySu/WeiXinMPSDK#112]
https://github.com/JeffreySu/WeiXinMPSDK/blob/5d502fee1bb2cbb57c55dff301ac302c3b2aa3da/Senparc.Weixin/Senparc.Weixin/MessageHandlers/IMessageHandlerDocument.cs#L41

 /// 如果是Senparc.Weixin.QY，则应当和ResponseDocument一致；如果是Senparc.Weixin.QY，则应当在ResponseDocument基础上进行加密

两句话的条件重复？

**Comment by JeffreySu** [comment]
对的，非常感谢提醒！正确的表达应该是： 如果是Senparc.Weixin.MP引用，并且未设置未加密，则应当和ResponseDocument一致；除此以外（Senparc.Weixin.QY或已加密），则应当在ResponseDocument基础上进行加密
