### ISSUE TITLE
.net core 2.0 调用WeixinResult报错

### ISSUE THREAD

**Issue by xiaoxin01** [JeffreySu/WeiXinMPSDK#1120]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
按照教程搭了框架，实现了基本的Controller，处理 Text Message，在 Controller的ActionResult方法调用
 WeixinResult("参数错误！");//v0.8+ 或者 FixWeixinBugWeixinResult(messageHandler);//v0.8+
报错：
System.MissingMethodException: Method not found: 'Void Senparc.Weixin.Exceptions
.WeixinException..ctor(System.String, System.Exception)'.

##### 重现问题步骤（如果可以）

1. dotnet new mvc
2. 新建 WechatController
3. 在Controller添加代码：
```
[HttpPost]
    [ActionName("Index")]
    public ActionResult MiniPost(PostModel postModel)
    {
return new WeixinResult("参数错误！");//v0.8+
}
```
4. 添加引用：

```
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.3"/>
    <PackageReference Include="Senparc.Weixin.MP" Version="14.10.3"/>
    <PackageReference Include="Senparc.Weixin.MP.MvcExtension" Version="4.1.1"/>
```
5. 运行 dotnet run，然后用 postman 模拟 post xml：
```
<xml>
<ToUserName><![CDATA[公众号]]></ToUserName>
 <FromUserName><![CDATA[粉丝号]]></FromUserName>
 <CreateTime>1460537339</CreateTime>
 <MsgType><![CDATA[text]]></MsgType>
 <Content><![CDATA[欢迎开启公众号开发者模式]]></Content>
 <MsgId>6272960105994287618</MsgId>
 </xml>
```

备注：如果把 Senparc.Weixin.MP.MvcExtension的 WeixinResult 直接 copy 到project里面引用，则不会报错，可能是package引用问题？

##### 发现问题的模块

- [ ] Senparc.Weixin.MP 版本：14.10.3
- [ ] Senparc.Weixin.MP.MVC 版本：4.1.1

##### 模块对应的.net版本
- [ ] .net core 2.x

##### 开发环境
- [x] Visual Studio 2017

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by lishewen** [comment]
用最新版 https://www.nuget.org/packages/Senparc.Weixin.MP.MVC

**Comment by xiaoxin01** [comment]
@lishewen 感谢，用这个可以了。
搜索package的时候勿用了这个：
Senparc.Weixin.MP.MvcExtension
