### ISSUE TITLE
GetAuthorizerInfoResult获得的信息不全

### ISSUE THREAD

**Issue by Atm563** [JeffreySu/WeiXinMPSDK#1127]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
在调用
var getAuthorizerInfoResult = AuthorizerContainer.GetAuthorizerInfoResult(component_AppId, authorizerId);
返回的信息authorization_info中func_info、authorizer_appid为null

##### 重现问题步骤（如果可以）

1. 通过demo进入开放平台
2. 进行授权
3. 授权成功后过一会访问授权详情是getAuthorizerInfoResult，返回的json里面authorization_info中func_info、authorizer_appid为null

##### 发现问题的模块

- [4.20.2 ] Senparc.Weixin 版本：
- [14.10.10 ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ 2.9.1] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ 1.9.1] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [x] .net 4.5
- [x] .net 4.6.1
- [ ] .net core 1.x
- [ ] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：54046711@qq.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
感谢反馈！有跟踪到原因吗？

**Comment by JeffreySu** [comment]
@Atm563 做了一次升级，您可以看下是否也解决了这个问题？ #1148

欢迎反馈。
