### ISSUE TITLE
HttpUtility.Get.Download 方法可能有一个bug

### ISSUE THREAD

**Issue by percyboy** [JeffreySu/WeiXinMPSDK#1136]
HttpUtility.Get.Download 方法中有一段代码如下：

```
string responseFileName = null;
//ContentDisposition可能会为Null
if (responseMessage.Content.Headers.ContentDisposition != null &&
      responseMessage.Content.Headers.ContentDisposition.FileName != null)
{
      responseFileName = Path.Combine(dir, responseMessage.Content.Headers.ContentDisposition.FileName.Trim('"'));
}

var fullName = responseFileName ?? Path.Combine(dir, GetRandomFileName());
using (var fs = File.Open(fullName, FileMode.Create))
{
      // ....
}

```

当 responseMessage.Content.Headers.ContentDisposition.FileName = "" 时，fullName = responseFileName 其值是一个文件夹的完整路径，则 File.Open 处会遇到“System.UnauthorizedAccessException: 对路径“C:\Windows\TEMP”的访问被拒绝。” 的异常。

我是在调试企业微信时发现这个问题的：我从苹果相册里选了一副照片，发给企业微信的app，后台调用了 MediaApi.Get 希望从微信服务器下载该照片，结果碰到 UnauthorizedAccessException。经反复排查相关权限设置，高度怀疑是这里的bug。

Fiddler跟踪得到的HTTP Response Header 如下：

> HTTP/1.1 200 OK
> Connection: keep-alive
> Content-Type: application/octet-stream
> Content-disposition: attachment; filename=""
> Content-Length: 29039

**Comment by JeffreySu** [comment]
就是说需要增加一个对responseMessage.Content.Headers.ContentDisposition.FileName = "" （而不光是null）的判断，是吧？

**Comment by percyboy** [comment]
实际测试了一下，这种情况下 responseMessage.Content.Headers.ContentDisposition.FileName 并不是空白字符串，而是两个引号。因此建议修改为：

```
if (responseMessage.Content.Headers.ContentDisposition != null 
      && !string.IsNullOrEmpty(responseMessage.Content.Headers.ContentDisposition.FileName)
      && responseMessage.Content.Headers.ContentDisposition.FileName != "\"\"")
{
      responseFileName = Path.Combine(dir, responseMessage.Content.Headers.ContentDisposition.FileName.Trim('"'));
}
```

**Comment by JeffreySu** [comment]
非常感谢！已经提交！
此类小改动也欢迎直接Pull Request，成为我们的Contributor，感谢 😄
