### ISSUE TITLE
UserApi.BatchGetUserInfo这方法，传的是中文，取出来的是中文，不知道啥情况

### ISSUE THREAD

**Issue by andysjt** [JeffreySu/WeiXinMPSDK#114]
UserApi.BatchGetUserInfo这方法，传的是中文，取出来的是中文，不知道啥情况

**Comment by JeffreySu** [comment]
你想说取出来的是英文是吧？特别是area的信息是吗？这个我们也碰到这个问题了。

**Comment by andysjt** [comment]
是的，我字打错了，取出来的area是英文的

**Comment by JeffreySu** [comment]
这个确实很奇怪，API里面提供的是中文。应该是一个bug，我们都继续关注一下吧，有新进展了在这里发一下。

**Comment by JeffreySu** [comment]
很久之前已经处理。
