### ISSUE TITLE
.net core 在centos 使用docker发布 微信退款出错

### ISSUE THREAD

**Issue by CarsonFjz** [JeffreySu/WeiXinMPSDK#1144]
报这个错误, 在本地没有错的
error:23076071:PKCS12 routines:PKCS12_parse:mac verify failure
好像是证书验证出错

            var cert = AppContext.BaseDirectory + "apiclient_cert.p12";//把证书放在根目录
            _logger.Information(File.Exists(cert).ToString());//true
            var password = xxx;
            var result = TenPayV3.Refund(dataInfo, cert, password);

因为是捕抓到错误
`X509Certificate2 cer = new X509Certificate2(cert, certPassword, X509KeyStorageFlags.PersistKeySet | X509KeyStorageFlags.MachineKeySet);`
应该是这里出错

**Comment by JeffreySu** [comment]
@CarsonFjz 有更加进一步的错误信息吗？例如是路径问题或者其他的？有一系列问题需要先排除一下。

**Comment by JeffreySu** [comment]
@CarsonFjz  看一下是不是这个问题：https://github.com/dotnet/corefx/issues/11046

**Comment by CarsonFjz** [comment]
@JeffreySu 恕在下愚钝, 看不懂问题在哪

**Comment by JeffreySu** [comment]
@CarsonFjz  看一下我上面发的链接，里面的描述和你的似乎有点像，看看能否按照里面的方法解决问题，可以试一下。

**Comment by CarsonFjz** [comment]
@JeffreySu  就是没看懂链接里面的解决方案

**Comment by JeffreySu** [comment]
你叫我说设么好呢 🤣
