### ISSUE TITLE
redis 缓存的 authorization_info为空的问题

### ISSUE THREAD

**Issue by 149392914** [JeffreySu/WeiXinMPSDK#1148]
AuthorizerContainer.TryGetAuthorizerAccessToken 的时候总是出现 未将对象引用到实例
经过排查发现在redis里缓存的 "authorizationInfo": null  （用json输出的）
查看GetAuthorizationInfo--》TryUpdateAuthorizationInfo
```
 var authorizerBag = TryGetItem(authorizerAppid);

                var refreshTokenChanged = authorizerBag.AuthorizationInfo.authorizer_access_token !=
                                         authorizationInfo.authorizer_access_token
                                           || authorizerBag.AuthorizationInfo.authorizer_refresh_token !=
                                              authorizationInfo.authorizer_refresh_token;
```
authorizerBag.AuthorizationInfo 这里每次都会抛异常。

请教：
这是Bug？还是在哪里需要对authorizerBag.AuthorizationInfo进行初始化？（没有通读代码，所以并不知道问题点）

**Comment by JeffreySu** [comment]
@149392914 发布了一个2.9.2，你可以测试一下是否问题还存在：https://www.nuget.org/packages/Senparc.Weixin.Open/2.9.2
