### ISSUE TITLE
关于企业付款到个人的问题

### ISSUE THREAD

**Issue by ys9168274** [JeffreySu/WeiXinMPSDK#1149]
企业付款到个人提示和CA证书不存在或者错误   原因是SDK中的方法没有携带证书信息
/// <summary>
        /// 用于企业向微信用户个人付款 
        /// 目前支持向指定微信用户的openid付款
        /// </summary>
        /// <param name="dataInfo">微信支付需要post的xml数据</param>
        /// <param name="timeOut"></param>
        /// <returns></returns>
        public static TransfersResult Transfers(TenPayV3TransfersRequestData dataInfo, string cert, string certPassword, int timeOut = Config.TIME_OUT)
        {
            var url = ReurnPayApiUrl("https://api.mch.weixin.qq.com/{0}mmpaymkttransfers/promotion/transfers");
            var data = dataInfo.PackageRequestHandler.ParseXML();
            string responseContent = CertPost(cert, certPassword, data, url);
            return new TransfersResult(responseContent);
        }

**Comment by JeffreySu** [comment]
@ys9168274 不是已经提供了cert和certPassword了吗？

**Comment by ys9168274** [comment]
代码贴错了 sorry
