### ISSUE TITLE
关于企业付款到个人的查询问题

### ISSUE THREAD

**Issue by ys9168274** [JeffreySu/WeiXinMPSDK#1151]
官方文档提示需要双向证书 SDK中的方法没有带上证书信息
/// <summary>
        /// 用于商户的企业付款操作进行结果查询，返回付款操作详细结果。
        /// </summary>
        /// <param name="dataInfo"></param>
        /// <param name="timeOut"></param>
        /// <returns></returns>
        public static GetTransferInfoResult GetTransferInfo(TenPayV3GetTransferInfoRequestData dataInfo, int timeOut = Config.TIME_OUT)
        {
            var urlFormat = ReurnPayApiUrl("https://api.mch.weixin.qq.com/{0}mmpaymkttransfers/gettransferinfo");

            var data = dataInfo.PackageRequestHandler.ParseXML();
            var formDataBytes = data == null ? new byte[0] : Encoding.UTF8.GetBytes(data);
            MemoryStream ms = new MemoryStream();
            ms.Write(formDataBytes, 0, formDataBytes.Length);
            ms.Seek(0, SeekOrigin.Begin);//设置指针读取位置
            var result = RequestUtility.HttpPost(urlFormat, null, ms, timeOut: timeOut);
            return new GetTransferInfoResult(result);
        }

**Comment by JeffreySu** [comment]
谢谢提醒，以后麻烦按照格式填写issue，并且提供一下文档地址，谢谢！
