### ISSUE TITLE
Senparc.Weixin.MP 做微信多客服会话控制出现问题

### ISSUE THREAD

**Issue by mrerhuo** [JeffreySu/WeiXinMPSDK#1152]
##### 问题描述
ResponseMessageTransfer_Customer_Service
我指定了coustomer2.TransInfo.Add(new CustomerServiceAccount { KfAccount = "zytxx@yxx" });
然后其他在线的客服在待接入人这里都能看见，请问是哪里的问题？

##### 发现问题的模块
- [ ] Senparc.Weixin.MP 版本：最新版本
##### 模块对应的.net版本
- [x] .net 4.6.1

##### 开发环境
- [x] Visual Studio 2017
##### 联系方式
Email：silence_ailong@qq.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by mrerhuo** [comment]
修改问题内容

**Comment by JeffreySu** [comment]
这个问题最好问一下腾讯的客服。 @mrerhuo

**Comment by JosonJiang** [comment]
这个问题 我也遇见了 不知道是不是有问题？ 官方是  KfAccount 这里是个 list<KfAccount >
