### ISSUE TITLE
获取小程序码，传递页面参数名称有误，望修正！

### ISSUE THREAD

**Issue by yzmx** [JeffreySu/WeiXinMPSDK#1154]
获取小程序码接口B方法（适用于需要的码数量极多的业务场景），传递页面参数名实为page，SDK上为path。

**Comment by JeffreySu** [comment]
@yzmx 请尽量按照issue默认格式填写，包括提供详细的接口名称（代码），以及微信官方文档，谢谢。

**Comment by JeffreySu** [comment]
@yzmx 麻烦去看一下官方文档，有2个接口，一个是限制，一个是不限制，代码应该是正确的。您再确认一下，同样很感谢提交意见！

如果还有问题可以ReOpen这个Issue。
