### ISSUE TITLE
第三方平台授权接口无法选择授权类型（仅公众号或者仅小程序）

### ISSUE THREAD

**Issue by liloin** [JeffreySu/WeiXinMPSDK#1158]
##### 问题描述
1、第三方平台授权接口没有账号类型参数，无法选择仅展示公众号还是仅展示小程序。
接口：ComponentApi.GetComponentLoginPageUrl
2、获取授权方的帐号基本信息接口没有返回小程序字段：
signature, MiniProgramInfo, network
最重要的是MiniProgramInfo，微信官方文档上描述“可根据这个字段判断是否为小程序类型授权”。
接口：AuthorizerContainer.GetAuthorizerInfoResult

##### 微信官方文档 URL
[第三方平台授权流程技术说明](https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1453779503&token=&lang=zh_CN)

##### 微信官方文档快照（直接复制关键内容到下方）
步骤2：引入用户进入授权页
第三方平台方可以在自己的网站中放置“微信公众号授权”或者“小程序授权”的入口，引导公众号和小程序管理员进入授权页。
授权页网址为：
https://mp.weixin.qq.com/cgi-bin/componentloginpage?component_appid=xxxx&pre_auth_code=xxxxx&redirect_uri=xxxx&auth_type=xxx。

参数 | 是否必填 | 参数说明
-- | -- | --
component_appid | 是 | 第三方平台方appid
pre_auth_code | 是 | 预授权码
redirect_uri | 是 | 回调URI
auth_type | 否 | 要授权的帐号类型， 1则商户扫码后，手机端仅展示公众号、2表示仅展示小程序，3表示公众号和小程序都展示。如果为未制定，则默认小程序和公众号都展示。第三方平台开发者可以使用本字段来控制授权的帐号类型。

6、获取授权方的帐号基本信息
（2）小程序获取方法如下
接口调用请求说明
http请求方式: POST（请使用https协议）
https://api.weixin.qq.com/cgi-bin/component/api_get_authorizer_info?component_access_token=xxxx

参数 | 说明
-- | --
signature | 帐号介绍
miniprograminfo | 可根据这个字段判断是否为小程序类型授权
network | 小程序已设置的各个服务器域名

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [x] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [ ] .net 4.5
- [ ] .net 4.6.1
- [ ] .net core 1.x
- [x] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

**Comment by JeffreySu** [comment]
@fanyinghao 谢谢！
