### ISSUE TITLE
一键激活还没在nuget更新

### ISSUE THREAD

**Issue by Kakaeex** [JeffreySu/WeiXinMPSDK#116]
我看到代码有一键激活功能了，在nuget上还是找不到更新，麻烦看看什么问题，谢谢

**Comment by JeffreySu** [comment]
你看到的代码发给我一下。

**Comment by JeffreySu** [comment]
你看到的代码麻烦发给我一下，具体是那一段，我们看一下是不是因为这个版本不在nuget上。

**Comment by plumgrand** [comment]
您好，您是说“企业号中 GetUserId 中没有 OPENID”的代码吗？其实在企业号中是没有OPenID的，如果企业号员工正常登录，返回的是UserID如果是非企业号员工登录，返回的是OpenID。
我原来的场景是做一个员工扫码登录的解决方案，即员工扫二维码，然后登陆对应的业务系统等等，主要是为了单点登录，后来我自己做了别的解决方案，绕了个圈，但还是解决了，现在效果还可以。
在企业号中是不会提供OpenID的。
plumgrand 


     On Thursday, September 17, 2015 3:08 PM, Jeffrey Su <notifications@github.com> wrote:
   

 你看到的代码麻烦发给我一下，具体是那一段，我们看一下是不是因为这个版本不在nuget上。—

**Comment by JeffreySu** [comment]
@plumgrand 请问你说的是哪个问题？

**Comment by Kakaeex** [comment]
@JeffreySu 麻烦把修复47001的版本推送到nuget，谢谢

**Comment by JeffreySu** [comment]
@Kakaeex nuget马上会发布一个最新的版本，不知道你说的修复的版本，现在已经merge了，还是仍然没有解决的

**Comment by Kakaeex** [comment]
@JeffreySu 我在nuget上更新完之后就出先47001的错误，我也不知道什么原因，我看到pull request上面有朋友推送解决47001的错误，看看怎么解决一下

**Comment by JeffreySu** [comment]
@Kakaeex 有没有可供测试的代码？目前的pull过来的解决方案是用newtonsoft.json，这个我们一直在避免使用，也正在尝试使用其他的方法。

**Comment by Kakaeex** [comment]
Card_BaseInfoBase _BaseInfo = new Card_BaseInfoBase()
            {
                logo_url = "https://mmbiz.qlogo.cn/mmbiz/GafMTen3Ue0oSEoCCjPbEZRfuJnFB5UsictIjXM2KH5S5owfCrWvjcIwCaib792mDp1KkjDWuMOicfxjfQeQXmf3g/0?wx_fmt=jpeg",
                brand_name = "花玄木里",
                code_type = Card_CodeType.CODE_TYPE_TEXT,
                title = card.title,//"132 元双人火锅套餐",
                sub_title = card.sub_title,// "周末狂欢必备",
                color = "Color010",
                notice = card.notice,// "使用时向服务员出示此券",
                service_phone = card.service_phone,// "020-88888888",
                description = card.description,
                // @"不可与其他优惠同享\n 如需团购券发票，请在消费时向商户提出\n 店内均可
                //使用，仅限堂食\n 餐前不可打包，餐后未吃完，可打包\n 本团购券不限人数，建议2 人使用，超过建议人
                //数须另收酱料费5 元/位\n 本单谢绝自带酒水饮料",
                date_info = new Card_BaseInfo_DateInfo()
                {
                    type = Card_DateInfo_Type.DATE_TYPE_FIX_TIME_RANGE.ToString(),
                    begin_timestamp = DateTimeHelper.GetWeixinDateTime(card.card_effect),
                    end_timestamp = DateTimeHelper.GetWeixinDateTime(card.card_disabled),
                },
                sku = new Card_BaseInfo_Sku()
                {
                    quantity = card.quantity
                },
                use_limit = card.use_limit,
                get_limit = card.get_limit,
                use_custom_code = false,
                bind_openid = false,
                can_share = true,
                can_give_friend = true,
                url_name_type = Card_UrlNameType.URL_NAME_TYPE_RESERVATION,
                custom_url = card.custom_url,//"http://www.weiweihi.com",
                source = card.source,//"大众点评",
                custom_url_name = card.custom_url_name,// "立即使用",
                custom_url_sub_title = card.custom_url_sub_title,// "6个汉字tips",
                promotion_url_name = card.promotion_url_name,//"更多优惠",
                promotion_url = card.promotion_url,//"http://www.qq.com",
                promotion_url_sub_title = card.promotion_url_sub_title
            };

                    var cash = new Card_CashData()
                    {
                        base_info = _BaseInfo,
                        least_cost = card.least_cost * 100,
                        reduce_cost = card.reduce_cost * 100
                    };
                    cardResult = CardApi.CreateCard(GetToken(), cash);

**Comment by JeffreySu** [comment]
@Kakaeex 能不能跟踪一下最后提交的json给我？

**Comment by Kakaeex** [comment]
{  "least_cost": 10000.00,  "reduce_cost": 3800.00,  "base_info": {    "logo_url": "https://mmbiz.qlogo.cn/mmbiz/GafMTen3Ue0oSEoCCjPbEZRfuJnFB5UsictIjXM2KH5S5owfCrWvjcIwCaib792mDp1KkjDWuMOicfxjfQeQXmf3g/0?wx_fmt=jpeg",    "code_type": 0,    "brand_name": "花玄木里",    "title": "会员卡",    "sub_title": "至尊贵宾卡",    "color": "Color010",    "notice": "淘宝、官网使用",    "service_phone": "020-88888888",    "source": "花玄木里",    "description": "88折",    "use_limit": 1000,    "get_limit": 1,    "use_custom_code": false,    "bind_openid": false,    "can_share": true,    "can_give_friend": true,    "location_id_list": null,    "date_info": {      "type": "DATE_TYPE_FIX_TIME_RANGE",      "begin_timestamp": 1443196800,      "end_timestamp": 1451491200,      "fixed_term": 0,      "fixed_begin_term": 0    },    "sku": {      "quantity": 10000    },    "url_name_type": 1,    "custom_url": "www.fervimori.com/help",    "custom_url_name": "使用规则",    "custom_url_sub_title": "出示客服使用",    "promotion_url_name": "折扣说明",    "promotion_url": "www.fervimori.com/discount",    "promotion_url_sub_title": "折扣入口",    "modify_msg_operation": null  }}

**Comment by JeffreySu** [comment]
@Kakaeex 用现在最新的代码试试看，是否可以？

**Comment by Kakaeex** [comment]
@JeffreySu 能不能推送到nuget上面啊？

**Comment by JeffreySu** [comment]
@Kakaeex 新版本正改到一半，我推一个隐藏版本给你吧。

**Comment by Kakaeex** [comment]
好的~~

**Comment by Kakaeex** [comment]
@JeffreySu smile.kaka@outlook.com thank you so much~

**Comment by JeffreySu** [comment]
@Kakaeex 邮件已发。

**Comment by Kakaeex** [comment]
还是报错：

微信Post请求发生错误！错误代码：47001，说明：data format error hint: [nRzESA0461ent2] Error before ":{"card_cell":{"end_time":0,"card_id":null},"url_cell":{"end_time":0,"text":null,"url":null}}}},

**Comment by JeffreySu** [comment]
@Kakaeex 你上面提供的一段代码里面的card这个对象能不能给我一个你的定义？我做一个单元测试。

**Comment by Kakaeex** [comment]
Card_BaseInfoBase _BaseInfo = new Card_BaseInfoBase()
            {
                logo_url = "https://mmbiz.qlogo.cn/mmbiz/GafMTen3Ue0oSEoCCjPbEZRfuJnFB5UsictIjXM2KH5S5owfCrWvjcIwCaib792mDp1KkjDWuMOicfxjfQeQXmf3g/0?wx_fmt=jpeg",
                brand_name = "花玄木里",
                code_type = Card_CodeType.CODE_TYPE_TEXT,
                title =  "满减优惠券",
                sub_title = "八折优惠券",
                color = "Color010",
                notice = "淘宝、官网使用",
                service_phone =  "020-88888888",
                description = "满50享8折",
                date_info = new Card_BaseInfo_DateInfo()
                {
                    type = Card_DateInfo_Type.DATE_TYPE_FIX_TIME_RANGE.ToString(),
                    begin_timestamp = DateTimeHelper.GetWeixinDateTime("20151001"),//这个我用字符串代替datetime
                    end_timestamp = DateTimeHelper.GetWeixinDateTime("20151201"),//这个我用字符串代替datetime
                },
                sku = new Card_BaseInfo_Sku()
                {
                    quantity = 10000
                },
                use_limit = 1,
                get_limit = 1,
                use_custom_code = false,
                bind_openid = false,
                can_share = true,
                can_give_friend = true,
                url_name_type = Card_UrlNameType.URL_NAME_TYPE_RESERVATION,
                custom_url ="www.fervimori.com/help",
                source = "花玄木里",
                custom_url_name = "www.fervimori.com/help",
                custom_url_sub_title =  "出示客服使用",
                promotion_url_name = "折扣说明",
                promotion_url = "www.fervimori.com/discount",
                promotion_url_sub_title = "折扣入口",
            };
            var discount = new Card_DisCountData()
                    {
                        base_info = _BaseInfo,
                        discount = 0.88
                    };

这个是我们的数据

**Comment by JeffreySu** [comment]
@Kakaeex 4.5的版本这个地方应该已经解决了，如果其他地方还有类似的问题可以重新提交上来。
目前默认的是不使用排除null，个别我们发现有问题的方法加上去。
