### ISSUE TITLE
微信支付退款

### ISSUE THREAD

**Issue by AjuPrince** [JeffreySu/WeiXinMPSDK#1166]
微信官方文档：https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=9_4
问题描述：
 1、根据官方文档（微信退款可支持单笔多次退款），但是实际通过 TenPayV3.Refund 接口 退款，首次退款是合适，当发起第二次退款时，会提示“订单不存在”
2、第二次的结果如图：
![ca5c5dbaf992c636caaf08920109775a](https://user-images.githubusercontent.com/16829343/39340093-b81c58be-49fe-11e8-961d-66cd2877badc.png)
3、通过微信支付后台（pay.weixin.qq.com）登录后找到的这笔单子 如图：

![4991fc945e93abd8e00b8d57f69e44d9](https://user-images.githubusercontent.com/16829343/39340118-e4dd74a0-49fe-11e8-965e-16295245cb10.png)
这个问题该如何解决？

**Comment by JeffreySu** [comment]
退过一次款之后，订单的状态是什么？

**Comment by AjuPrince** [comment]
调用订单查询接口，提示“订单不存在”，没有返回订单状态等信息，从微信支付商户后台看 交易状态是“部分退款完成”。

**Comment by JeffreySu** [comment]
看一下这一行提示，是不是这个原因：

> 2、微信支付退款支持单笔交易分多次退款，多次退款需要提交原支付订单的商户订单号和设置不同的退款单号。申请退款总金额不能超过订单金额。 一笔退款失败后重新提交，请不要更换退款单号，请使用原商户退款单号

**Comment by AjuPrince** [comment]
不存在这个问题，我刚开始也认为是这个原因，经过我再三排查后后确定不是这个原因。
原因如下：同一个退款流程（先通过订单查询后再调用退款接口），首次是合适的，第二次退款的时候，查询时就会提示“订单不存在”，而商户订单号和首次退款时的一样。

**Comment by JeffreySu** [comment]
那么如果第二次你不查询，直接调用订单号，同时提供一个不同的out_refund_no（款款单号），能不能成功？
