### ISSUE TITLE
UrlUtility.GenerateOAuthCallbackUrl(……)得到错误的值 

### ISSUE THREAD

**Issue by 717009629** [JeffreySu/WeiXinMPSDK#1172]
##### 问题描述
网站用的80端口，绑定的域名， 返回的结果中在域名后面多了一个冒号

##### 重现问题步骤（如果可以）

服务器版本server2012R2

` if ((schemeUpper == "HTTP" && port == 80) ||(schemeUpper == "HTTPS" && port == 443))`
此处获取的port 为null

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：

##### 模块对应的.net版本

- [ ] .net core 2.x

**Comment by JeffreySu** [comment]
已经更新，非常感谢！
同时为项目PR代码，成为我们的Contributor :)

**Comment by 717009629** [comment]
不客气，应该感谢您
