### ISSUE TITLE
企业微信缺少”接收通讯录变更事件“

### ISSUE THREAD

**Issue by cakey90** [JeffreySu/WeiXinMPSDK#1174]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
缺少通讯录变更事件

##### 重现问题步骤（如果可以）

1. 在Event枚举里没发现”change_contact“，只有第三方平台的变更事件

##### 微信官方文档 URL
https://work.weixin.qq.com/api/doc#13523
https://work.weixin.qq.com/api/doc#12974/%E6%96%B0%E5%A2%9E%E6%88%90%E5%91%98%E4%BA%8B%E4%BB%B6

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [x] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [x] .net 4.5
- [x] .net 4.6.1
- [ ] .net core 1.x
- [ ] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
谢谢！已经排入计划，因为排队的事务比较多，也欢迎PR代码过来，成为项目的Contributor :)

**Comment by JeffreySu** [comment]
@pekrr1e  👍

**Comment by cakey90** [comment]
👍

**Comment by JeffreySu** [comment]
已经发布到master，如果还有问题可以Reopen。感谢各位！
