### ISSUE TITLE
公众号第三方平台中的公众号消息与事件接收URL 参数$APPID$

### ISSUE THREAD

**Issue by zhujinhu21** [JeffreySu/WeiXinMPSDK#118]
公众号第三方平台中的公众号消息与事件接收URL中$APPID$ 写的是授权公众号的appid，

![qq 20150922153900](https://cloud.githubusercontent.com/assets/4327149/10013083/b8667844-6140-11e5-9f39-5970a68d7659.png)

图中的postmodel.appid我可以换成授权的$APPID$ 吗？

**Comment by JeffreySu** [comment]
对的，这个appId微信会根据你的格式发给你的。
