### ISSUE TITLE
Senparc.Weixin.Open.ComponentAPIs.ComponentApi 中方法ApiAuthorizerToken 中的刷新token的描述信息存在问题

### ISSUE THREAD

**Issue by coderdp** [JeffreySu/WeiXinMPSDK#1181]
[类文件](https://github.com/JeffreySu/WeiXinMPSDK/blob/master/src/Senparc.Weixin.Open/Senparc.Weixin.Open/ComponentAPIs/ComponentApi.cs) 中ApiAuthorizerToken的描述信息存在问题。开放平台 refresh_token 没有有效期，但是在这个参数描述为 
> 由于access_token拥有较短的有效期，当access_token超时后，可以使用refresh_token进行刷新，refresh_token拥有较长的有效期（30天），当refresh_token失效的后，需要用户重新授权。

上面所说30天的是[用户授权token](https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419318590&token=&lang=zh_CN)
如果可以的话，希望更新下文档，如果产生误解。

**Comment by JeffreySu** [comment]
就是这一行注释多余了，是吧？

**Comment by JeffreySu** [comment]
已经提交了，如果有问题的话请 Reopen 这个 issue，另外欢迎职介PR代码过来:)
