### ISSUE TITLE
删除群发接口缺少article_idx参数

### ISSUE THREAD

**Issue by liloin** [JeffreySu/WeiXinMPSDK#1184]
##### 问题描述
GroupMessageApi.DeleteSendMessageAsync 缺少 article_idx参数，无法删除指定位置文章。

##### 微信官方文档 URL
[删除群发【订阅号与服务号认证后均可用】](https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1481187827_i0l21)

##### 微信官方文档快照（直接复制关键内容到下方）

参数 | 是否必须 | 说明
-- | -- | --
msg_id | 是 | 发送出去的消息ID
article_idx | 否 | 要删除的文章在图文消息中的位置，第一篇编号为1，该字段不填或填0会删除全部文章

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [x ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [ ] .net 4.5
- [ ] .net 4.6.1
- [ ] .net core 1.x
- [x] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

**Comment by JeffreySu** [comment]
已经推送，感谢！这种比较清楚的也欢迎直接PR代码过来 ：）
