### ISSUE TITLE
推送模板消息(外链小程序)，报错

### ISSUE THREAD

**Issue by mustcarrayout** [JeffreySu/WeiXinMPSDK#1185]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述

1. 入参名称pagePath 报错
2. 入参名称paget则不报错
3. 官网demo错误

##### 重现问题步骤（如果可以）

1. MP.AdvancedAPIs.TemplateApi.SendTemplateMessage
2. 推送消息链接需跳转至小程序，new TempleteModel_MiniProgram{pagePath="path"}

##### 微信官方文档 URL
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1433751277

##### 微信官方文档快照（直接复制关键内容到下方）

```
{
           "touser":"OPENID",
           "template_id":"ngqIpbwh8bUfcSsECmogfXcV14J0tQlEpBO27izEYtY",
           "url":"http://weixin.qq.com/download",  
           "miniprogram":{
             "appid":"xiaochengxuappid12345",
             "pagepath":"index?foo=bar"
           },
}
```

## 由于官方把参数名pagepath修改为path，导致报错
```
{
    "errcode": 40165, 
    "errmsg": "invalid weapp pagepath hint: [7GyI8a0145ge21]"
}
```

## 解决方案 字段重命名pagepath => page
```
    public class TempleteModel_MiniProgram
    {
        /// <summary>
        /// 小程序AppId
        /// </summary>
        public string appid { get; set; }
        /// <summary>
        /// 路径，如：index?foo=bar
        /// </summary>
        public string path { get; set; }
    }
```

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [x] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [] .net 4.5
- [] .net 4.6.1
- [ ] .net core 1.x
- [x] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：
lihelikepurple@gmail.com
（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
@mustcarrayout 2中 `paget` 是否有写错？

**Comment by mustcarrayout** [comment]
不好意思，确实写错了，是page！

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Jeffrey Su <notifications@github.com>
发送时间: Monday, May 7, 2018 7:17:12 PM
收件人: JeffreySu/WeiXinMPSDK
抄送: lihe; Mention
主题: Re: [JeffreySu/WeiXinMPSDK] 推送模板消息(外链小程序)，报错 (#1185)


@mustcarrayout<https://github.com/mustcarrayout> 2中 paget 是否有写错？

―

**Comment by JeffreySu** [comment]
你确定path是有效的吗（不只是不出错）？我之前试过Demo（也是官方文档写的）中的这个pagepath参数名称是正确的，但是值是错误的，正确的应该是这样：
` pagepath = "pages/index/index"`

**Comment by mustcarrayout** [comment]
兄弟，现在执行单元测试都是好的。不论是用pagepath还是page都不报错了，但是用path跳转之后的页面不是预期，用pagepath是对的，因此这个问题被解决了。


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Jeffrey Su <notifications@github.com>
发送时间: Tuesday, May 8, 2018 7:53:40 PM
收件人: JeffreySu/WeiXinMPSDK
抄送: lihe; Mention
主题: Re: [JeffreySu/WeiXinMPSDK] 推送模板消息(外链小程序)，报错 (#1185)


你确定path是有效的吗（不只是不出错）？我之前试过Demo（也是官方文档写的）中的这个pagepath参数名称是正确的，但是值是错误的，正确的应该是这样：
pagepath = "pages/index/index"

―

**Comment by JeffreySu** [comment]
OK
