### ISSUE TITLE
关于OAuthAccessTokenContainer有个疑问

### ISSUE THREAD

**Issue by JadynWong** [JeffreySu/WeiXinMPSDK#1187]
https://github.com/JeffreySu/WeiXinMPSDK/blob/86831dd5cedd3add90bc23356e93620cf5b6143b/src/Senparc.Weixin.MP/Senparc.Weixin.MP/Containers/OAuthAccessTokenContainer.cs#L205

为什么是以appId为缓存key?
微信文档
代码注释

> code作为换取access_token的票据，每次用户授权带上的code将不一样，code只能使用一次，5分钟未被使用自动过期。

这里的每个人的code 得到的access_token 对**其他粉丝**也有效？ 
若为无效 没什么 缓存的key 不是 appId+code

因为我要实现的功能需要 取得 OAuthAccessTokenResult 中的openid 结果发现都一样 所以有这个疑问

**Comment by JadynWong** [comment]
@JeffreySu 明白了，感谢解答，其实主要是用到了加锁，防止同一code重复请求

**Comment by JeffreySu** [comment]
不过这个类这样留着确实比较容易让人误解，谢谢提醒！
