### ISSUE TITLE
.net core 下 WeixinResult 好像无法正常返回

### ISSUE THREAD

**Issue by ccccccmd** [JeffreySu/WeiXinMPSDK#1194]
asp.net core 下，messagehandler处理好后  ，返回xml时用 `WeixinResult` 不生效

`return new WeixinResult(messageHandler);//v0.8+`

直接返回Content()是有效的

` return Content(messageHandler.ResponseDocument?.ToString());`

**Comment by JeffreySu** [comment]
用过 `FixWeixinBugWeixinResult` 了吗？

``` 
return new FixWeixinBugWeixinResult(messageHandler);
```

**Comment by ccccccmd** [comment]
刚才试了下，`FixWeixinBugWeixinResult`的正常的

**Comment by JeffreySu** [comment]
OK，我们自己也是一直都用这个类，基本上不需要用WeixinResult了。
