### ISSUE TITLE
多次上传同一个图片时报错，应该是没有正确关闭流

### ISSUE THREAD

**Issue by tickwudi** [JeffreySu/WeiXinMPSDK#1196]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
我多次调用代码：var fileResult = Senparc.Weixin.Work.AdvancedAPIs.MediaApi.Upload(appKey,Senparc.Weixin.Work.UploadMediaFileType.image, "d:/201703170510.jpg");出现了The process cannot access the file  because it is being used by another process

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.Work 版本：

##### 模块对应的.net版本

- [ ] .net core 2.x

##### 开发环境

- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [ ] 无

##### 联系方式
Email：tickwudi@qq.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by qwork** [comment]
我遇到了同样的问题

**Comment by JeffreySu** [comment]
@tickwudi @qwork 最新的版本已经进行了改进，你们看一下是否已经解决问题。

**Comment by tickwudi** [comment]
@JeffreySu 我感觉问题出在Senparc.Weixin.HttpUtility.RequestUtility.HttpPost_Common_NetCore方法中,修改如下，您看看如何：
`
var fileName = file.Value;
                        //准备文件流
                        using (var fileStream = FileHelper.GetFileStream(fileName))
                        {
                            if (fileStream != null)
                            {
                                //存在文件


                                //multipartFormDataContent.Add(new StreamContent(fileStream), file.Key, Path.GetFileName(fileName)); //报流已关闭的异常
								//tk:上面打开文件流后，下面这句话没有使用，另外又要打开此文件，所以会报错X.X,应该修改下
                                //注释掉multipartFormDataContent.Add(CreateFileContent(File.Open(fileName, FileMode.Open), Path.GetFileName(fileName)), file.Key, Path.GetFileName(fileName));
								multipartFormDataContent.Add(CreateFileContent(fileStream, Path.GetFileName(fileName)), file.Key, Path.GetFileName(fileName));
                                //fileStream.Dispose();//tk:这里不用显示的调用了，因为using已经包裹了
                            }
                            else
                            {
                                //不存在文件或只是注释
                                multipartFormDataContent.Add(new StringContent(string.Empty), file.Key, file.Value);
                            }
                        }
`

**Comment by lishewen** [comment]
https://github.com/JeffreySu/WeiXinMPSDK/blob/12f5553bb77a8cbdd29ad9a93fa043440b2566fd/src/Senparc.Weixin/Senparc.Weixin/Utilities/HttpUtility/RequestUtility.Post.cs#L258

这里的
`File.Open(fileName, FileMode.Open)`
的确关闭是有问题
但采用上一行的代码的话，以前是会报一个 流已关闭的异常，也通过注释备注了
所以才用了这行的写法，起码能保证上传成功，考虑到我们的业务场景中不会有上传重复图片的情况，就算有前端也会提示请不要上传重复，毕竟微信那边的素材存储是有限的
因此，我们也一直保留这个没有改，但如果新版runtime不存在这个异常的话可以恢复 上一行的写法

**Comment by lishewen** [comment]
另外，CreateFileContent 当时是为了解决 #710 #708 #698 #688 等问题而创建的
用 fileStream 的话也应该过一下，不易重新绕过，导致这些问题重现

**Comment by tickwudi** [comment]
@lishewen 如果是流已关闭，可否读取数据后换成MemeryStream？

**Comment by tickwudi** [comment]
@lishewen 流已关闭就是因为multipartFormDataContent.Add(new StreamContent(fileStream), file.Key, Path.GetFileName(fileName));用了fileStream关闭后续上传才读流的，你在这读取文件内容转成MemeryStream传递进去应该不会报流关闭异常的

**Comment by lishewen** [comment]
@tickwudi 我看 @JeffreySu 这次的修改也是你这个思路改的，可能没改完

**Comment by tickwudi** [comment]
@lishewen 好的，等改完后我再测吧

**Comment by lishewen** [comment]
@tickwudi 你的思路没问题，StreamContent的流在内容Post完成前都是不能关闭的，不然还是会报关闭异常

**Comment by JeffreySu** [comment]
@tickwudi 改进了一下代码，你可以试一下这样是否解决问题了：https://github.com/JeffreySu/WeiXinMPSDK/commit/b442b5979665ba8386d1bb7cbcbc429a9937ef7a

如果还不行的话就要另外的方案了。

**Comment by JeffreySu** [comment]
@tickwudi  @lishewen 我修改了一下，https://github.com/JeffreySu/WeiXinMPSDK/commit/7b3a8de3b8587fc0166a42f968bf746252a6416d

关闭异常的问题没有了（至少第一次发送是这样），但是似乎流并没有被合理序列化并且发送出去，报这个异常：

> {"errcode":44001,"errmsg":"empty media data, hint: [1526540969_6_2e2c92b3380016c92d827c69b6f8d746], more info at https://open.work.weixin.qq.com/devtool/query?e=44001"}



单元测试可以看这里（文件课对应你们自己的路径修改）

https://github.com/JeffreySu/WeiXinMPSDK/blob/7b3a8de3b8587fc0166a42f968bf746252a6416d/src/Senparc.Weixin.Work/Senparc.Weixin.Work.Test/AdvancedAPIs/Media/MediaTest.cs#L63

**Comment by tickwudi** [comment]
我clone不下来代码，总是网络异常，等nuget更新了我才能测试

**Comment by JeffreySu** [comment]
@lishewen 我看了CreateFileContent 的方法，里面已经强制约定了media，这样是不是会不太通用？

**Comment by lishewen** [comment]
@JeffreySu 这个改动好久了，我项目也没发现因为这个强制约定触发的异常反馈，倒是不加的话就会有 #688 和 "errcode":44001,"errmsg":"empty media data 的问题，如果需要考虑通用可以作为一个参数传入

**Comment by lishewen** [comment]
@JeffreySu 
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1444738729
文档中也是规定了，media必填的
media | 是 | form-data中媒体文件标识，有filename、filelength、content-type等信息

**Comment by JeffreySu** [comment]
@lishewen 对这一个接口来说是没问题的，但是如果还有其它接口需要上传文件的话就不对了。传入的参数的name目前是很灵活的，可以自己定义：

https://github.com/JeffreySu/WeiXinMPSDK/blob/7b3a8de3b8587fc0166a42f968bf746252a6416d/src/Senparc.Weixin.Work/Senparc.Weixin.Work/AdvancedAPIs/Media/MediaApi.cs#L65

**Comment by lishewen** [comment]
我并没有反对在方法加参数呀

**Comment by lishewen** [comment]
我只是强调必须要处理下formdata的信息，而不要直接传stream

**Comment by JeffreySu** [comment]
@lishewen @tickwudi  @qwork 这个更新已经解决了上述的问题：https://github.com/JeffreySu/WeiXinMPSDK/commit/63c96a5cb2cb794cb44e62bbe24559572093c8fc，可以重复上传，单元测试也已经通过，如果有任何问题欢迎继续反馈并Reopen这个issue。

![image](https://user-images.githubusercontent.com/2281927/40177694-e192cc32-5a11-11e8-9eb7-033530f92c70.png)

**Comment by JeffreySu** [comment]
测试稳定之后我会发布到nuget。
如果还有问题请Reopen此issue，感谢各位！

**Comment by JeffreySu** [comment]
BTW，重复上传文件我专门写了一个单元测试：
https://github.com/JeffreySu/WeiXinMPSDK/blob/1b0ec2decf2a6897e1e2832c08283a7b37f3e3e9/src/Senparc.Weixin.Work/Senparc.Weixin.Work.Test/AdvancedAPIs/Media/MediaTest.cs#L68
