### ISSUE TITLE
企业微信无法上传图文消息图片 MediaApi.UploadimgMedia

### ISSUE THREAD

**Issue by kevincwq** [JeffreySu/WeiXinMPSDK#1197]
想要调用 Senparc.Weixin.Work.AdvancedAPIs.MediaApi.UploadimgMedia 方法上传图片以获得图片的url

>  [[[接口调用]]]
> [5/16/2018 2:58:25 PM]
> [线程：9]
>     URL：https://qyapi.weixin.qq.com/cgi-bin/media/uploadimg?access_token=...
>     Post Data：
> {"media":"C:\\pic_002.png"}
> 
> [[[接口调用]]]
> [5/16/2018 2:58:26 PM]
> [线程：9]
>     URL：https://qyapi.weixin.qq.com/cgi-bin/media/uploadimg?access_token=...
>     Result：
> {"errcode":44001,"errmsg":"empty media data, hint: [1526453906_3_5c4495f3fc9a30ab525c00f034fd4b3f], more info at https://open.work.weixin.qq.com/devtool/query?e=44001"}
> 
> [[[ErrorJsonResultException]]]
> [5/16/2018 2:58:26 PM]
> [线程：9]
>     ErrorJsonResultException
>     AccessTokenOrAppId：null
>     URL：
>     errcode：多媒体文件为空
>     errmsg：empty media data, hint: [1526453906_3_5c4495f3fc9a30ab525c00f034fd4b3f], more info at https://open.work.weixin.qq.com/devtool/query?e=44001

> [[[ErrorJsonResultException]]]
> [5/16/2018 2:58:26 PM]
> [线程：9]
>     ErrorJsonResultException
>     AccessTokenOrAppId：null
>     URL：
>     errcode：多媒体文件为空
>     errmsg：empty media data, hint: [1526453906_3_5c4495f3fc9a30ab525c00f034fd4b3f], more info at https://open.work.weixin.qq.com/devtool/query?e=44001

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
~- [ ] Senparc.Weixin.Work 版本：~
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [x] .net 4.5
- [ ] .net 4.6.1
- [ ] .net core 1.x
- [ ] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [x] Visual Studio 2015
- [ ] Visual Studio 2017
- [ ] 其他：

**Comment by JeffreySu** [comment]
感谢！我们会进行一些测试，如果有问题会进行修复。

**Comment by JeffreySu** [comment]
@kevincwq 今天已经发布了一个新版本，解决了.net core下文件上传的问题，你可以试一下目前是否正常。
相关问题：https://github.com/JeffreySu/WeiXinMPSDK/issues/1196

**Comment by kevincwq** [comment]
@JeffreySu 我用的 .net4.5, 升级到1.3.1的新版本，还是一样的错误。仔细看了一下发现[Senparc.Weixin.Work.AdvancedAPIs.MediaApi.UploadimgMedia](https://github.com/JeffreySu/WeiXinMPSDK/blob/e783e58f7de0c2d4b2d4f288f505115828787260/src/Senparc.Weixin.Work/Senparc.Weixin.Work/AdvancedAPIs/Media/MediaApi.cs#L315) 这个函数只是把media打包到了post的content中，并没有做File的upload操作。

**Comment by JeffreySu** [comment]
@kevincwq  你运行一下这个单元测试，看一下是否能成功：https://github.com/JeffreySu/WeiXinMPSDK/issues/1196#issuecomment-389855036

**Comment by JeffreySu** [comment]
@kevincwq  嗯，这个接口确实有问题

**Comment by JeffreySu** [comment]
@kevincwq  已经发布了新版本，试一下这个：https://www.nuget.org/packages/Senparc.Weixin.Work/1.6.0-rc1

**Comment by JeffreySu** [comment]
好嘞，非常感谢反馈！
