### ISSUE TITLE
Senparc.Weixin.Work.vs2017 解决方案打不开

### ISSUE THREAD

**Issue by 17768810** [JeffreySu/WeiXinMPSDK#1212]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述

装了netcore 2.1后的，打不开Senparc.Weixin.Work.vs2017，不能手动选择netcore 2.0的框架，看了下项目文件，应该是支持太多版本，写的太复杂了。。

**Comment by lishewen** [comment]
你装的是2.1的哪个版本？rc1还是rtm，rc1打开的话应该没问题，rtm应该还没做适配，毕竟rtm 2.1，30号才会正式上线

**Comment by JeffreySu** [comment]
不要用Senparc.Weixin.Work.vs2017，用 https://github.com/JeffreySu/WeiXinMPSDK/blob/master/Samples/Senparc.Weixin.MP.Sample.vs2017/Senparc.Weixin.MP.Sample.vs2017.sln
