### ISSUE TITLE
字符串json序列化时出现了：字符串的长度超过了为 maxJsonLength 属性设置的值 错误

### ISSUE THREAD

**Issue by hello2008zj** [JeffreySu/WeiXinMPSDK#1213]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
代码位置：Senparc.Weixin.HttpUtility.Post
错误原因：以下代码在对象过大时会报错：进行序列化或反序列化时出错。字符串的长度超过了为 maxJsonLength 属性设置的值。
public static T GetResult<T>(string returnText)
        {
#if NET35 || NET40 || NET45
            JavaScriptSerializer js = new JavaScriptSerializer();
 #endif

            if (returnText.Contains("errcode"))
            {
                //可能发生错误
#if NET35 || NET40 || NET45
               **//发生问题位置**
                WxJsonResult errorResult = **js.Deserialize<WxJsonResult>(returnText);**
#else

处理方式：
public static T GetResult<T>(string returnText)
        {
#if NET35 || NET40 || NET45
            JavaScriptSerializer js = new JavaScriptSerializer();
           ## **//在此处增加一行代码**
            ## **js.MaxJsonLength = int.MaxValue;** 
#endif

            if (returnText.Contains("errcode"))
            {
                //可能发生错误
#if NET35 || NET40 || NET45
                WxJsonResult errorResult = js.Deserialize<WxJsonResult>(returnText);
#else

##### 重现问题步骤（如果可以）

比如获取图文信息，一次量获取大点：比如50篇
MediaApi.GetNewsMediaList(token, 1, 50);

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：v4.20.3
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [x] .net 4.5
- [x] .net 4.6.1
- [ ] .net core 1.x
- [ ] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：chenqihezj@qq.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
@hello2008zj 试一下在web.config里面设置一下允许序列化JSON字符串的最大长度：

<system.web.extensions> 
  <scripting> 
    <webServices> 
       
      <jsonSerialization maxJsonLength="1024000" /> 
    </webServices> 
  </scripting> 
</system.web.extensions>

**Comment by hello2008zj** [comment]
还是报同样的错误。设置如下：

<system.web.extensions>
    <scripting>
      <webServices>
        <jsonSerialization maxJsonLength="2147483647"></jsonSerialization>
      </webServices>
    </scripting>
  </system.web.extensions>

**Comment by hello2008zj** [comment]
可以增加一个熟悉来控制：

        public static int MaxJsonLength { get; set; }

        /// <summary>
        /// 获取Post结果
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="returnText"></param>
        /// <returns></returns>
        public static T GetResult<T>(string returnText)
        {
#if NET35 || NET40 || NET45
            JavaScriptSerializer js = new JavaScriptSerializer();

            if(MaxJsonLength>0)
                js.MaxJsonLength = MaxJsonLength;
#endif

**Comment by hello2008zj** [comment]
可以考虑增加一个属性来控制：

private static int maxJsonLength = int.MaxValue;
        /// <summary>
        /// 最大Json序列化长度，默认为int.MaxValue
        /// </summary>
        public static int MaxJsonLength
        {
            get { return maxJsonLength; }
            set { maxJsonLength = value; }
        }

        /// <summary>
        /// 获取Post结果
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="returnText"></param>
        /// <returns></returns>
        public static T GetResult<T>(string returnText)
        {
#if NET35 || NET40 || NET45
            JavaScriptSerializer js = new JavaScriptSerializer();
           
           js.MaxJsonLength = MaxJsonLength;

**Comment by JeffreySu** [comment]
@hello2008zj 在 Config 下面是有设置的，我们会考虑升级到 CO2NET 里面。目前还没找到 Newtonsoft.Json 内部设置这个参数的地方，你知道吗？
