### ISSUE TITLE
对于微信API返回结果可能出现两种不同格式的json的时候你们是怎么处理的？

### ISSUE THREAD

**Issue by lishewen** [JeffreySu/WeiXinMPSDK#1224]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
根据code获取成员信息 API

a) 当用户为企业成员时返回示例如下：
```json
{
   "errcode": 0,
   "errmsg": "ok",
   "UserId":"USERID",
   "DeviceId":"DEVICEID",
   "user_ticket": "USER_TICKET"，
   "expires_in":7200
}
```

b) 非企业成员授权时返回示例如下：
```json
{
   "errcode": 0,
   "errmsg": "ok",
   "OpenId":"OPENID",
   "DeviceId":"DEVICEID"
}
```

当前SDK只实现了前者

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 微信官方文档 URL
https://work.weixin.qq.com/api/doc#10028

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [x] Senparc.Weixin.Work 版本：1.6.0-rc1
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [x] .net 4.5
- [x] .net 4.6.1
- [ ] .net core 1.x
- [x] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by lishewen** [comment]
企业微信准备打通微信，所以后面的情况需要考虑，日后可能需要用到

**Comment by lishewen** [comment]
我目前是把那块改了 dynamic 或者 JObject

**Comment by JeffreySu** [comment]
除了dynamic之外，Newtonsoft.Json有提供强类型的识别，可以根据一些条件去判断具体的实体是什么，其实这个自己封装一下也可以。这种情况在自定义菜单里面也已经发生了，目前的方法是用比较粗暴的方式做判断的（效率高、代码易懂），如果这种情况很多的话可以做封装的，不过“粗暴”是少不了的。

还有一种情况是做一个实体A，包含所有的属性（可以对应用不同接口，IC，ID），取出来之后再去做判断，然后给到C或D

**Comment by JeffreySu** [comment]
@lishewen 有用过 [MessagePack](https://github.com/neuecc/MessagePack-CSharp) 吗？

**Comment by lishewen** [comment]
@JeffreySu 没用过
