### ISSUE TITLE
一个小小的建议

### ISSUE THREAD

**Issue by JHeLiu** [JeffreySu/WeiXinMPSDK#1229]
还有有个小建议，比如在这里面的通信协议工具包，是否设计成 独立包访问权限，因为我可能只想使用对应的微信接口，而不会使用里面的通信API，当然我只是建议，可能楼主设计是必须这样的，我是说，如果可能， 比如里面不需要外界访问的API是否考虑不暴露给使用者。

**Comment by JeffreySu** [comment]
作为一个通用的SDK组件，这样设计过于复杂了，我提供两个思路：
1、如果您只希望开放一部分（您可能是第三方的开发商），可以直接使用源代码，将不需要暴露的接口去掉（或改写成别的访问级别）
2、在整个管道模块中加一层，屏蔽掉某些接口网址的访问，或做一个白名单只允许某一些。当然这样的话程序里面仍然可以看到，只是无法实现通讯。
