### ISSUE TITLE
.netcore Senparc扩展，名称错误

### ISSUE THREAD

**Issue by gainorloss** [JeffreySu/WeiXinMPSDK#1232]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述

.netcore 注入扩展，名称错误，Senparc误写Sernparc
##### 重现问题步骤（如果可以）

正常调用

##### 微信官方文档快照（直接复制关键内容到下方）
       services.AddMvc();
            services.Configure<SenparcWeixinSetting>(Configuration.GetSection("SenparcWeixinSetting"))
                .AddSernparcWeixinGlobalServices();

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：

##### 模块对应的.net版本

- [ ] .net core 2.x

##### 开发环境
- [x] Visual Studio 2017

##### 缓存环境

- [ ] Redis 版本：

##### 联系方式
Email：519564415@qq.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
已经更新，非常感谢，以后也欢迎直接PR代码过来 👍
