### ISSUE TITLE
.net core post 永久视频素材失败

### ISSUE THREAD

**Issue by JadynWong** [JeffreySu/WeiXinMPSDK#1236]
https://github.com/JeffreySu/WeiXinMPSDK/blob/abdc0f697e96e5a65e70b60dec57467fb47715bf/src/Senparc.Weixin/Senparc.Weixin/Utilities/HttpUtility/RequestUtility.Post.cs#L267

异常 
System.ArgumentException: The format of value '{"title":"2222", "introduction":"3333"}' is invalid.

`//var dataContent = new ByteArrayContent(Encoding.UTF8.GetBytes(file.Value));
                                //dataContent.Headers.ContentDisposition = new ContentDispositionHeaderValue("form-data")
                                //{
                                //    Name = file.Key
                                //};
                                //var dataContent = new StringContent(file.Value)
                                //{
                                //    Headers =
                                //    {
                                //        ContentDisposition = new ContentDispositionHeaderValue("form-data")
                                //        {
                                //            Name = file.Key
                                //        }
                                //    }
                                //};
                                //multipartFormDataContent.Add(dataContent, file.Key);`

上面的代码也不行总是提示缺少
错误代码：41005，说明：media data missing

还没找到解决办法

.net core v2.1 
Senparc.Weixin 4.22.1

**Comment by lishewen** [comment]
https://github.com/JeffreySu/WeiXinMPSDK/blob/abdc0f697e96e5a65e70b60dec57467fb47715bf/src/Senparc.Weixin/Senparc.Weixin/Utilities/HttpUtility/RequestUtility.Post.cs#L261

文件上传没走这个条件？文件流为空？

**Comment by JadynWong** [comment]
@lishewen 文件添加没问题  图片 音频 都不会进入这里
 上传视频素材时要附带的title和introduction

**Comment by lishewen** [comment]
以前是会走的，应该是最近动了那块

**Comment by lishewen** [comment]
@JadynWong 是从哪个方法进去的？我跟踪一下

**Comment by JadynWong** [comment]
@lishewen  嗯占用的问题已经没有了
 MediaApi.UploadForeverVideo(accessToken, path, title, introduction,timeout);

**Comment by JadynWong** [comment]
multipartFormDataContent.Add(content, name, fileName); 
这里fileName只能是标准的文件名称不能包含特殊字符`"`的
ContentDispositionHeaderValue内部
private string EncodeAndQuoteMime(string input)
    {
      string input1 = input;
      bool flag = false;
      if (this.IsQuoted(input1))
      {
        input1 = input1.Substring(1, input1.Length - 2);
        flag = true;
      }
      if (input1.IndexOf("\"", 0, StringComparison.Ordinal) >= 0)
        throw new ArgumentException(string.Format((IFormatProvider) CultureInfo.InvariantCulture, SR.net_http_headers_invalid_value, (object) input));
      if (this.RequiresEncoding(input1))
      {
        flag = true;
        input1 = this.EncodeMime(input1);
      }
      else if (!flag && HttpRuleParser.GetTokenLength(input1, 0) != input1.Length)
        flag = true;
      if (flag)
        input1 = "\"" + input1 + "\"";
      return input1;
    }
处理报的异常
不能这么添加内容

测试
1
var dataContent = new ByteArrayContent(Encoding.UTF8.GetBytes(file.Value)); dataContent.Headers.ContentDisposition = new ContentDispositionHeaderValue("form-data"){  Name = file.Key }; 
multipartFormDataContent.Add(dataContent, file.Key);
2 
dataContent.Headers.ContentDisposition = new ContentDispositionHeaderValue("form-data"){ Name = file.Key }; 
multipartFormDataContent.Add(dataContent, file.Key);
3
 multipartFormDataContent.Add(new StringContent(file.Value),  file.Key);
错误代码：41005，说明：media data missing
搞不明白怎么添加

**Comment by lishewen** [comment]
微信那边返回的那个错误代码不完全可信的

**Comment by lishewen** [comment]
@JadynWong 提交了一个PR，是 description 附加信息时，description 要加双引号，微信那边才识别。。。

**Comment by JadynWong** [comment]
@lishewen 我晕，非常感谢，一直在调发送方式，没想到拼的参数键就有问题😂

**Comment by JeffreySu** [comment]
已经合并，谢谢！

**Comment by JeffreySu** [comment]
#1238
