### ISSUE TITLE
Redis有很大的性能问题

### ISSUE THREAD

**Issue by kistliu** [JeffreySu/WeiXinMPSDK#1240]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 重现问题步骤（如果可以）

1.按照文档注册redis缓存，只写一个根据key获取redis Value的接口，而且只操作一次redis.
单次请求最低需要33ms。
2. 下面是压测结果
图片一直上传不了，并发100，请求数100的情况下吞吐量只有42

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [x] .net 4.5
- [x] .net 4.6.1
- [ ] .net core 1.x
- [x] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [ ] 服务器内存缓存（默认）
- [x] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
好的，我来测试一下，你也可以关注我们新的CO2NET的进展，到时候这部分代码会进行分离，也非常感谢在这个关键时候提出这个问题，我会仔细测试的，欢迎继续在这里沟通跟进。

**Comment by JeffreySu** [comment]
@kistliu 整个过程测试了一下，应该最大的问题可能是在实例的序列化和反序列化上面：

https://github.com/Senparc/Senparc.CO2NET/blob/3614fc7af2fbb8127d846a8058de79bf68fd56aa/src/Senparc.CO2NET.Cache.Redis/StackExchange.Redis/StackExchangeRedisExtensions.cs#L67

https://github.com/Senparc/Senparc.CO2NET/blob/3614fc7af2fbb8127d846a8058de79bf68fd56aa/src/Senparc.CO2NET.Cache.Redis/StackExchange.Redis/StackExchangeRedisExtensions.cs#L117

这两处使用的都是官方推荐的方式，如果要优化的话需要找第三方的库来跟进。欢迎一起测试和讨论方案。

**Comment by JeffreySu** [comment]
@kistliu 还有另外一种可能性，因为 RegisterObjectCacheStrategy()方法注册之后，第一次通过GetObjectCacheStrategyInstance() 获取耗时是比较长的，是否存在你的程序里面每个Request都有RegisterObjectCacheStrategy() 的问题？

**Comment by kistliu** [comment]
RegisterObjectCacheStrategy在我的程序中只是在应用启动时做了一次注册，应该不会存在多次注册问题。
另：是否可以不进行序列化直接存字符串，或者有更优化的方法呢

**Comment by JeffreySu** [comment]
@kistliu 直接存json应该是最简单的方法，不过里面也可能会涉及到一些信息的丢失，如果只是SDK的应用范围问题还不大，如果储存复杂类型的话（比如里面设置了私有变量、事件就是比较复杂的情况了），那么就可能造成一些数据的丢失，很多内容通常是不会被序列化到json里面的。

另外一个原因是现在SDK中的ContainerBag使用了INotifyPropertyChanged接口，用于实现属性变动后的自动缓存，如果做json序列化可能也会有一些问题，不过确实值得一试。

**Comment by JeffreySu** [comment]
@kistliu 支持 CO2NET 的预览版已经发布，改用了JSON作为储存格式，应该不会有效率上的问题了。原先二进制的方法，经过了好几天的测试，发现基本上没有办法再压缩了，已经是可能情况下的比较优的方案了。

目前暂时在 Developer-CO2NET 分支下：https://github.com/JeffreySu/WeiXinMPSDK/tree/Developer-CO2NET

**Comment by kistliu** [comment]
额 Senparc.Weixin.Work 版本没发布程序通不了....

**Comment by JeffreySu** [comment]
多谢提醒，已经发布！
https://www.nuget.org/packages/Senparc.Weixin.Work/2.0.0-preview1

**Comment by kistliu** [comment]
额~ Senparc.CO2NET.Exceptions.BaseException:“当前扩展缓存策略没有进行注册，CacheStrategyDomain：Senparc.Weixin.Cache.ContainerCacheStrategyDomain，IBaseObjectCacheStrategy：Senparc.CO2NET.Cache.Redis.RedisObjectCacheStrategy”  这个是还需要在哪注册什么呢？

**Comment by kistliu** [comment]
IRegisterService register = RegisterService.Start(env, false);
            register.ChangeDefaultCacheNamespace("PSAWeixinCache");
            RegisterWeixinCache(app);       //注册分布式缓存（按需，如果需要，必须放在第一个）
            RegisterWeixinAccessToken();

var RedisServer = Configuration.GetSection("RedisServer").Value;

            //如果留空，默认为localhost（默认端口）

            #region  Redis配置
            var redisConfiguration = RedisServer;
            RedisManager.ConfigurationOption = redisConfiguration;
            
            //如果不执行下面的注册过程，则默认使用本地缓存

            if (!string.IsNullOrEmpty(redisConfiguration))
            {
                CacheStrategyFactory.RegisterObjectCacheStrategy(() => RedisObjectCacheStrategy.Instance);//Redis
            }
            //微信的 Redis 缓存，如果不使用则注释掉（开启前必须保证配置有效，否则会抛错）
            app.UseSenparcWeixinCacheRedis();
            #endregion

.............................................................
是这样配置有问题么？感觉没有快哦
