### ISSUE TITLE
AccessToken过期问和冲突问题

### ISSUE THREAD

**Issue by yaols** [JeffreySu/WeiXinMPSDK#1241]
如果两个项目  一个在服务器上跑  一个是本地  用同一个微信服务号，底层都是Senparc。拉取用户数据 会不会互相冲掉对方的令牌呀
微信官网文档
需要自己做一个令牌中央调控管理
Senparc
我朋友说 已经一起做了统一生命周期管理，规则是根据项目名称。如果两个项目名称(key一样)，那么两个项目的AccessToken是统一的  不会冲刷掉(我觉得可能性很低)
那么盛派是否统一管理周期了
GetAccessTokenResult(appid,true)  两个项目都是这么写的，只是单独管理自己项目的令牌，还是统一管理   那么单独管理  用该方法  进程1--令牌过期然后刷新  进程2--令牌过期然后刷新  会不会互相影响提示令牌过期的错误出来

**Comment by JeffreySu** [comment]
是的，AccessToken的生命周期已经完全自动管理，在多个系统（或分布式）共享的情况下，Senparc.Weixin SDK 中我们已经提供了分布式缓存的接口，并且默认提供了Redis（推荐）以及Memcached两个常用分布式缓存的实现。只要缓存命名空间一致（https://github.com/JeffreySu/WeiXinMPSDK/blob/master/src/Senparc.Weixin/Senparc.Weixin/Config.cs#L95），就可以实现AccessToken的共享，不需要编写任何代码。

Redis：https://www.nuget.org/packages/Senparc.Weixin.Cache.Redis
Memcached：https://www.nuget.org/packages/Senparc.Weixin.Cache.Memcached
