### ISSUE TITLE
未关注的情况下发送模板消息会抛出异常

### ISSUE THREAD

**Issue by zhujinhu21** [JeffreySu/WeiXinMPSDK#1244]
##### 问题描述
TemplateApi.SendTemplateMessage（） 发送模板消息，没有关注的情况下发送消息会直接抛出异常，而不是返回的SendTemplateMessageResult的errcode=43004

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [x] .net 4.5
- [x] .net 4.6.1
- [ ] .net core 1.x
- [ ] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
@zhujinhu21 具体的异常信息是什么？如果不是返回成功代码，本身就也是会抛出异常的，并且带上官方的错误信息。

**Comment by JeffreySu** [comment]
@zhujinhu21 这个是对的，所有错误都会抛出异常，你需要try一下，不要怕麻烦，如果不try，你也需要做别的if判断 😄
