### ISSUE TITLE
运行失败 Exception from HRESULT: 0x80131040 無法載入檔案或組件 或其相依性的其中之一。 找到的組件資訊清單定義與組件參考不符。 (發生例外狀況於 HRESULT: 0x80131040)

### ISSUE THREAD

**Issue by claregao** [JeffreySu/WeiXinMPSDK#1251]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
用Visual Studio 2017 打开Senparc.Weixin.MP.Sample.sln，Restore NuGet， Set Senparc.Weixin.MP.Sample as startup project，运行就报错
![](https://ws1.sinaimg.cn/large/48332c8egy1fspnqrga4xj20z20jigmz.jpg)
![](https://ws1.sinaimg.cn/large/48332c8egy1fspnr6owu3j20zg0jjjsw.jpg)
##### 重现问题步骤（如果可以）

1. 用Visual Studio 2017 打开Senparc.Weixin.MP.Sample.sln
2. Restore NuGet
3. Set Senparc.Weixin.MP.Sample as startup project
4. 运行就报错

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [x] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [x] .net 4.5
- [ ] .net 4.6.1
- [ ] .net core 1.x
- [ ] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：yanjun.gao3@gmail.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
一般是依赖的dll版本不正确导致的。
请看一下Web项目中上运行的所有Senparc.xx.dll是否都是最新的版本，或者依赖正确的版本。如果是从旧版本升级的，可以试一下“清理解决方案”以及“重新生成解决方案”。

**Comment by claregao** [comment]
谢谢你的回复！
还想请教一个问题：如果用沙箱测试微信公众号支付，是否需要设置正确的支付授权目录？我们的域名目前没有备案

谢谢

2018-07-02 21:43 GMT+08:00 Jeffrey Su <notifications@github.com>:

**Comment by JeffreySu** [comment]
1、沙箱对于路径应该是没有特殊要求的（如果有变化以微信官方文档为准）
2、域名最好进行一下备案，没有备案的我们还没试过。

**Comment by claregao** [comment]
好的 谢谢！

2018-07-11 16:48 GMT+08:00 Jeffrey Su <notifications@github.com>:
