### ISSUE TITLE
你们不打算推webFrom，为什么还要提供不能使用的webFrom代码，你们有没有运行过webFrom程序 

### ISSUE THREAD

**Issue by jihaipeng** [JeffreySu/WeiXinMPSDK#1259]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [x] .net 4.5
- [x] .net 4.6.1
- [ ] .net core 1.x
- [ ] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
从来没说过不打算推WebFroms，之前不能运行是因为一个引用路径问题，已经修复，不要着急 😄

**Comment by jihaipeng** [comment]
。。。。。运行webforms程序试下。   里面的连接与样式都是错的。

**Comment by JeffreySu** [comment]
WebForms不是让你看UI的，UI已经集中在MVC里面了，主要是看和MVC处理方式不同的地方。
不过有要求呢，我们是尽量会满足的，稍等我改一下。

**Comment by JeffreySu** [comment]
主要是看MessageHandler：https://github.com/JeffreySu/WeiXinMPSDK/blob/master/Samples/Senparc.Weixin.MP.Sample.WebForms/Senparc.Weixin.MP.Sample.WebForms/readme.txt
