### ISSUE TITLE
第三方平台代公众号网页授权appId参数传递

### ISSUE THREAD

**Issue by zhujinhu21** [JeffreySu/WeiXinMPSDK#126]
![12](https://cloud.githubusercontent.com/assets/4327149/10541924/0e030254-7447-11e5-9f42-ad1d9c7e0c64.png)

第三方平台在代公众号网页授权中，需要参数授权公众号的appId，

图中的appId怎么获取，这个页面被多个公众号公用

**Comment by JeffreySu** [comment]
在用户（公众号）成功授权给你的时候，你可以拿到他的appId（wxbe855a981c34aa3f）。
你可以从这个页面进去测试：http://weixin.senparc.com/OpenOAuth/JumpToMpOAuth
成功授权之后，页面最下方有这个Action的入口。

**Comment by zhujinhu21** [comment]
开发了第三方平台，问题是我有2个授权公众号给第三方平台，2个公众号设置了同一个功能菜单（需要登录）比如评估XXX，是网页跳转，公众号粉丝用户在点击这2个公众号的菜单时候，需要网页授权获取用户信息，怎么识别是哪一个公众号？
![421812a0f2587f921c51413a84ac527b png](https://cloud.githubusercontent.com/assets/4327149/10568301/b6432d06-7648-11e5-8cf8-105215227aac.jpg)
![Uploading 421812a0f2587f921c51413a84ac527b.png.jpg…]()



上面的图中，不同公众号是不是显示该网页有XXX不同的授权公众号开发。
