### ISSUE TITLE
微信3V的支付参数

### ISSUE THREAD

**Issue by JHeLiu** [JeffreySu/WeiXinMPSDK#1261]
TenPayV3UnifiedorderRequestData,
发生在 TenPayV3.Unifiedorder()
1、提个建议，当时这不是错的，用构造函数强制约束 必须，没错
2、但是这样真的很不友好，必须需要太多的字段，而 如果真的别人用微信支付接口，都会自己注意需要填写的参数, 我很想使用参数类来做参数，但是脱离不了 构造函数的参数注入

**Comment by JeffreySu** [comment]
并不是所有的参数都是必填的，TenPayV3UnifiedorderRequestData 中选填的参数都做成了 `xx=null` 的定义，你可以根据需要传入，不需要全部输入的。其余的必填字段基本上时必须提供的，你总得有个地方传入呀。

另外我没理解“参数类来做参数”的意思？

**Comment by JHeLiu** [comment]
我的意思是说， TenPayV3UnifiedorderRequestData这个参数类，已经需要一个无参构造函数，可能我想这样的， new TenPayV3UnifiedorderRequestData(){ }; 这样的赋值。而目前这个 是需要强制构造函数注入参数。当然，这个并没有错，只是，代码不够优雅了。

**Comment by JeffreySu** [comment]
很显然这样做的一个缺点是一系列必须输入的参数可能会被遗漏，带参数的构造函数就是用来强制提供参数的。对于可选的参数都是用了 xx = null 的默认值，可以选填。
如果你非要“优雅”，构造函数也是允许例如这样的：

new TenPayV3UnifiedorderRequestData(appId: appId, secret: secret,...) 

参数之间也可以换行。

**Comment by JeffreySu** [comment]
@JHeLiu 先关闭啦，感谢交流！
