### ISSUE TITLE
AutoReplyJson.cs  KeywordListInfoItem 文件注释错误

### ISSUE THREAD

**Issue by hnsongbiao** [JeffreySu/WeiXinMPSDK#1263]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
“\src\Senparc.Weixin.MP\Senparc.Weixin.MP\AdvancedAPIs\AutoReply\AutoReplyJson.cs”
文件注释错误，请调整为如下：
    public class KeywordListInfoItem
    {
        /// <summary>
        /// 关键词的类型，仅支持文本（text）、图片（img）、语音（voice）、视频（video），关键词自动回复则还多了图文消息（news）
        /// </summary>
        public AutoReplyType type { get; set; }
        /// <summary>
        /// 关键词匹配模式，contain = 0 消息中含有该关键词即可， equal = 1 消息内容必须和关键词严格相同
        /// </summary>
        public AutoReplyMatchMode match_mode { get; set; }
        /// <summary>
        /// 对于文本类型，content是文本内容，对于图文、图片、语音、视频类型，content是mediaID
        /// </summary>
        public string content { get; set; }
    }
 
##### 联系方式
Email：340114173@qq.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
@hnsongbiao 是否方便直接PR过来？

**Comment by hnsongbiao** [comment]
还没PR过

**Comment by JeffreySu** [comment]
@hnsongbiao 先Fork到你自己账户下面，然后修改代码、提交，然后点一下“Pull Request”即可。

**Comment by JeffreySu** [comment]
已处理，谢谢！
