### ISSUE TITLE
关键词回复一次不能发送多条回复信息

### ISSUE THREAD

**Issue by hnsongbiao** [JeffreySu/WeiXinMPSDK#1267]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
“\MessageHandlers\CustomMessageHandler\CustomMessageHandler.cs”
按照这里的写法
public override IResponseMessageBase OnTextRequest(RequestMessageText requestMessage)

没办法实现一个关键词同时回复多条信息，请问有解决办法吗
  

##### 联系方式
Email：340114173@qq.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
https://weixin.senparc.com/QA/QAPost/Item/355
