### ISSUE TITLE
XXE安全漏洞何时修复？

### ISSUE THREAD

**Issue by youbl** [JeffreySu/WeiXinMPSDK#1268]
国外爆出的XXE安全漏洞，以及 微信支付团队的说明如下：
https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=23_5

看了一下，当前SDK也有XmlDocument使用，没有修复，建议修复，修复方法：
var xmlDoc = new XmlDocument();
xmlDoc.XmlResolver = null;  // 添加这一行代码

**Comment by TomLiu-GitHub** [comment]
你能让问题重现吗?

**Comment by youbl** [comment]
这个，百度或Google一下 XXE攻击，你就明白是啥问题了

**Comment by TomLiu-GitHub** [comment]
Prior to .NET Framework version 4.5.2, System.Xml.XmlDocument is unsafe by default. The XmlDocument object has an XmlResolver object within it that needs to be set to null in versions prior to 4.5.2. In versions 4.5.2 and up, this XmlResolver is set to null by default.

**Comment by JeffreySu** [comment]
已经发布，感谢 @youbl  @TomLiu-GitHub
