### ISSUE TITLE
授权公众号的微信网页登陆获取用户信息的提示内容都是一样的吗

### ISSUE THREAD

**Issue by zhujinhu21** [JeffreySu/WeiXinMPSDK#127]
![ssss](https://cloud.githubusercontent.com/assets/4327149/10571488/31eac058-7672-11e5-8b5b-e21932f363d8.png)
菜单的连接地址都是一样的
上图中2个公众号都授权给了第三方开放平台，最后在授权公众号的微信网页登陆获取用户信息的提示页面中，提示信息（该网页有XXX开发）都是一样的吗，
XXX指的是授权公众号的名称吗？
如果不一样，怎么在网页中知道是哪一个授权的微信公众号？

**Comment by JeffreySu** [comment]
应该是一样的，你是要让看的人知道，还是开发者知道？

**Comment by zhujinhu21** [comment]
我想让粉丝用户知道，不是开发者。

**Comment by JeffreySu** [comment]
如果用Open授权了，显示的应该是被授权（Authorizer）的公众号信息。
