### ISSUE TITLE
启动redis 报错

### ISSUE THREAD

**Issue by pbzyy** [JeffreySu/WeiXinMPSDK#1272]
![image](https://user-images.githubusercontent.com/4442711/42320533-4170c13a-8088-11e8-9d65-754751229604.png)

**Comment by pbzyy** [comment]
最新版本使用的是Sample列子

**Comment by JeffreySu** [comment]
我这边未发现这个问题，看错误应该是redis的服务挂了，或者各种原因连不上。还有可能是配置不正确。

**Comment by pbzyy** [comment]
![image](https://user-images.githubusercontent.com/4442711/42355874-f36bb11e-8101-11e8-858a-f72e4d6b848e.png)

**Comment by pbzyy** [comment]
跟这个错误一样的

**Comment by pbzyy** [comment]
Redis 部署在Centos 确实有问题，估计要把Senparc.CO2NET这个源码下载下来调试了

**Comment by JeffreySu** [comment]
是SE.Redis的问题吗？CO2NET有比较完整的单元测试，应该很快可以知道结果，你可以试试看，欢迎反馈结果。

**Comment by pbzyy** [comment]
![image](https://user-images.githubusercontent.com/4442711/42416250-0cb46882-829c-11e8-9f1c-be43b0fc457d.png)

测试代码没有问题

**Comment by pbzyy** [comment]
找到问题点，Redis连接串丢失了。
修改代码如下：
![image](https://user-images.githubusercontent.com/4442711/42416352-c3777ed6-829e-11e8-99dd-3c90b765d753.png)


![image](https://user-images.githubusercontent.com/4442711/42416356-cf6777aa-829e-11e8-9ebb-63f8c5c7b91c.png)

**Comment by lb0726** [comment]
private IList<IDomainExtensionCacheStrategy> GetExCacheStrategies(SenparcSetting senparcSetting)
        {
            var exContainerCacheStrategies = new List<IDomainExtensionCacheStrategy>();
            senparcSetting = senparcSetting ?? new SenparcSetting();

           **//注意：以下两个 if 判断仅作为演示，
            //      只要进行了 register.UseSenparcWeixin() 操作，Redis 和 Memcached 系统已经默认自动注册，无需操作！**

            #region 演示扩展缓存注册方法

            //判断Redis是否可用
            //var redisConfiguration = senparcSetting.Cache_Redis_Configuration;// ConfigurationManager.AppSettings["Cache_Redis_Configuration"];
            //if ((!string.IsNullOrEmpty(redisConfiguration) && redisConfiguration != "Redis配置"))
            //{
            //    exContainerCacheStrategies.Add(RedisContainerCacheStrategy.Instance);
            //}

**Comment by JeffreySu** [comment]
@pbzyy 如果确实是这个问题的话那就是和CentOS没关系了吧？
可以参考这里一步到位的Demo：

https://github.com/JeffreySu/WeiXinMPSDK/blob/d03425fe243989ffb7f66e0cf4d1fa36a9e48079/Samples/Senparc.Weixin.MP.Sample.vs2017/Senparc.Weixin.MP.CoreSample/Startup.cs#L120

**Comment by pbzyy** [comment]
对。就按你的方式就可以了
