### ISSUE TITLE
CardApi.CreateQR 还是遇到47001那个null相关的异常，请修复

### ISSUE THREAD

**Issue by lishewen** [JeffreySu/WeiXinMPSDK#128]
CardApi.CreateQR 还是遇到47001那个null相关的异常，请修复

**Comment by lishewen** [comment]
版本为nuget上的最新版本：13.4.4

**Comment by JeffreySu** [comment]
这个版本应该是已经助理掉了，Senparc.Weixin这个库，v4.2.1以上应该都有有最新的解决方案了。我们再测试一下，谢谢！

**Comment by JeffreySu** [comment]
应该不存在这个问题了，如果还有问题请 Reopen 这个 issue。
