### ISSUE TITLE
SessionBag Redis缓存记录中有一些记录中的unionid为null

### ISSUE THREAD

**Issue by lb0726** [JeffreySu/WeiXinMPSDK#1280]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
SessionBag Redis缓存记录中有些unionid为null

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [x] Senparc.Weixin.WxOpen 版本：
- [x] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [x] .net 4.5
- [x] .net 4.6.1
- [ ] .net core 1.x
- [ ] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [] 服务器内存缓存（默认）
- [x] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：58690327@qq.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
有没有跟踪的一些记录？我们这边看了自己的项目，没有出现这样的情况，是不是某次请求本身就没有拿到unionid？

**Comment by lb0726** [comment]
我也是无意看Redis缓存中SessionBag记录看到的，如何去跟踪？
难道还有openid获取到了unionid没有获取到的情况？

**Comment by JeffreySu** [comment]
如果IsDebug状态打开的话，所有的接口log都会被记录在App_Data下面的，你看一下。
