### ISSUE TITLE
object reference not set to an insance

### ISSUE THREAD

**Issue by myccy8** [JeffreySu/WeiXinMPSDK#1281]
`Senparc.CO2NET.Helpers.ReflectionHelper`      /// <summary>
        /// 获取静态类属性
        /// </summary>
        /// <param name="assemblyName">类型所在程序集名称</param>
        /// <param name="nameSpace">类型所在命名空间</param>
        /// <param name="className">类型名</param>
        /// <param name="memberName">属性名称（忽略大小写）</param>
        /// <returns></returns>
        public static object GetStaticMember(string assemblyName, string nameSpace, string className,string memberName)
        {
            try
            {
                string fullName = nameSpace + "." + className;//命名空间.类型名
                string path = fullName + "," + assemblyName;//命名空间.类型名,程序集
                var type = Type.GetType(path);
                PropertyInfo[] props = type.GetProperties();
                var prop = props.FirstOrDefault(z => z.Name.Equals(memberName, StringComparison.OrdinalIgnoreCase));
                return prop.GetValue(null,null);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return null;
            }
        }`当不引用
Senparc.Weixin.Cache.Memcached 时报object reference not set to an insance错误

**Comment by myccy8** [comment]
var type = Type.GetType(path);
PropertyInfo[] props = type.GetProperties(); 这段代码报错

**Comment by JeffreySu** [comment]
这个不是代码里面的问题，是这个Memcached对象确实为空了，比较常见的原因是没有配置memcached，但是试图初始化。

**Comment by JeffreySu** [comment]
您看一下有没有这样的情况

**Comment by myccy8** [comment]
`   //Memcached
            var memcachedConfiguration = senparcSetting.Cache_Memcached_Configuration;
            //if ((!string.IsNullOrEmpty(memcachedConfiguration) && memcachedConfiguration != "Memcached配置"))
            {
                try
                {
                    var memcachedInstance = ReflectionHelper.GetStaticMember("Senparc.Weixin.Cache.Memcached", "Senparc.Weixin.Cache.Memcached", "MemcachedContainerCacheStrategy", "Instance");
                    if (memcachedInstance != null)
                    {
                        //officialTypes.Add(memcachedInstance.GetType());
                        cacheTypes += "\r\n" + memcachedInstance.GetType();
                    }
                }
                catch (Exception ex)
                {
                    WeixinTrace.WeixinExceptionLog(new Exceptions.WeixinException(ex.Message, ex));
                }
            }`我看您源码里是注释掉判断的，不知道是为何

**Comment by JeffreySu** [comment]
@myccy8 memcached如果需要启用，一定要把memcached服务配置好。为了方便大家demo顺利跑起来，所以注释掉了。
