### ISSUE TITLE
小程序版的客户消息未实现图文接口

### ISSUE THREAD

**Issue by lb0726** [JeffreySu/WeiXinMPSDK#1282]
小程序版的客户消息未实现图文接口
官方文档说明：
https://developers.weixin.qq.com/miniprogram/dev/api/custommsg/conversation.html

发送图文链接
每次可以发送一个图文链接

{

    "touser": "OPENID",
    "msgtype": "link",
    "link": {
          "title": "Happy Day",
          "description": "Is Really A Happy Day",
          "url": "URL",
          "thumb_url": "THUMB_URL"
    }
}
发送小程序卡片
{
    "touser":"OPENID",
    "msgtype":"miniprogrampage",
    "miniprogrampage":{
        "title":"title",
        "pagepath":"pagepath",
        "thumb_media_id":"thumb_media_id"
    }
}

**Comment by fanyinghao** [comment]
小程序的客服接口是和公众号的接口兼容的，可以用`Senparc.Weixin.MP.AdvancedAPIs.CustomApi`下的方法。

**Comment by lb0726** [comment]
@fanyinghao @JeffreySu 
Senparc.Weixin.MP.AdvancedAPIs.CustomApi 有上面所说的对应的方法？

**Comment by JeffreySu** [comment]
@fanyinghao 查了一下，文字和图片都在上面的类里面，除了“图文链接”有一些不同，以及“发送小程序卡片”接口没有。可以计划加上去，谢谢！

**Comment by JeffreySu** [comment]
@lb0726  最新版本已经发布，这两个功能，谢谢！
