### ISSUE TITLE
部分类需要增加Serializable

### ISSUE THREAD

**Issue by hnsongbiao** [JeffreySu/WeiXinMPSDK#1284]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
1、Senparc.Weixin.Open.OAuthAPIs.OAuthUserInfo.cs
2、Senparc.Weixin.MP.AdvancedAPIs.User.UserInfoJson.cs

需要增加[Serializable] 标签：
namespace Senparc.Weixin.Open.OAuthAPIs
{
    /// <summary>
    /// 通过OAuth的获取到的用户信息（snsapi_userinfo=scope）
    /// </summary>
    [Serializable]
    public class OAuthUserInfo
....
}

namespace Senparc.Weixin.MP.AdvancedAPIs.User
{
    /// <summary>
    /// 高级接口获取的用户信息
    /// </summary>
    [Serializable]
    public class UserInfoJson : WxJsonResult
。。。

}
 
##### 联系方式
Email：340114173@qq.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
WxJsonResult 本身已经有序列化标签，子类已经不需要了吧？
