### ISSUE TITLE
UseSenparcWeixin方法不存在的错误

### ISSUE THREAD

**Issue by yushiro** [JeffreySu/WeiXinMPSDK#1285]
##### 问题描述
在vs2013环境下，如下的初始化代码出错，错误信息是“UseSenparcWeixin”这个方法不存在
```
            string appId = "xxx";
            string appSecret = "xxxxxx";
            var senparcSetting = SenparcSetting.BuildFromWebConfig(false);
            var wxSetting = SenparcWeixinSetting.BuildFromWebConfig(false);
            IRegisterService register = RegisterService.Start(senparcSetting).UseSenparcGlobal().UseSenparcWeixin(wxSetting,senparcSetting);
            AccessTokenContainer.Register(appId, appSecret, "");
            var result = AccessTokenContainer.TryGetAccessToken(appId, appSecret);
```

经过查看源码， 猜测应该是vs2013不支持UseSenparcWeixin这个方法的新特性， 需要用如下代码改写
```
WeixinRegister.UseSenparcWeixin(register,senparcWeixinSetting, senparcSetting);
```
暂时只遇到了这个问题，不知道整个框架中是否还有其他类似这个错误的地方。

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [x] .net 4.5
- [] .net 4.6.1
- [ ] .net core 1.x
- [ ] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [x] Visual Studio 2013
- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

**Comment by JeffreySu** [comment]
1、升级到最新的版本
2、需要引用 Senparc.Weixin 命名空间

详情：https://www.cnblogs.com/szw/p/9265828.html

**Comment by JeffreySu** [comment]
VS2013，以及.net 3.5 sp1以上，应该都支持扩展方法的。
