### ISSUE TITLE
获取小程序码的接口缺少 is_hyaline 参数

### ISSUE THREAD

**Issue by zxz19** [JeffreySu/WeiXinMPSDK#1286]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
Senparc.Weixin.WxOpen.AdvancedAPIs.WxApp.GetWxaCodeUnlimit 和
Senparc.Weixin.WxOpen.AdvancedAPIs.WxApp.GetWxaCodeUnlimitAsync 接口没有 is_hyaline 参数，用以指定生成的小程序是否背景透明

##### 微信官方文档 URL
https://developers.weixin.qq.com/miniprogram/dev/api/qrcode.html

##### 微信官方文档快照（直接复制关键内容到下方）

参数 | 类型 | 默认值 | 说明
-- | -- | -- | --
scene | String |   | 最大32个可见字符，只支持数字，大小写英文以及部分特殊字符：!#$&'()*+,/:;=?@-._~，其它字符请自行编码为合法字符（因不支持%，中文无法使用 urlencode 处理，请使用其他编码方式）
page | String |   | 必须是已经发布的小程序存在的页面（否则报错），例如 "pages/index/index" ,根路径前不要填加'/',不能携带参数（参数请放在scene字段里），如果不填写这个字段，默认跳主页面
width | Int | 430 | 二维码的宽度
auto_color | Bool | false | 自动配置线条颜色，如果颜色依然是黑色，则说明不建议配置主色调
line_color | Object | {"r":"0","g":"0","b":"0"} | auto_color 为 false 时生效，使用 rgb 设置颜色 例如 {"r":"xxx","g":"xxx","b":"xxx"} 十进制表示
is_hyaline | Bool | false | 是否需要透明底色， is_hyaline 为true时，生成透明底色的小程序码

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [x] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [x] .net 4.5
- [x] .net 4.6.1
- [ ] .net core 1.x
- [ ] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：zxz19@qq.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
已经添加，感谢！
