### ISSUE TITLE
组合模板并添加至帐号下的个人模板库

### ISSUE THREAD

**Issue by davidmaster** [JeffreySu/WeiXinMPSDK#1288]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述

public static LibraryGetJsonResult Add(....) 这个方法的返回类型错误，应该为AddJsonResult

**Comment by JeffreySu** [comment]
已经修复，感谢！

**Comment by JeffreySu** [comment]
已经修复，感谢！
