### ISSUE TITLE
当我尝试注册Redis缓存的时候 会导致一个错误

### ISSUE THREAD

**Issue by JHeLiu** [JeffreySu/WeiXinMPSDK#1289]
```
/微信
       //注册缓存
            
            CacheStrategyFactory.RegisterObjectCacheStrategy(() => RedisObjectCacheStrategy.Instance);
            var isGLobalDebug = false;//设置全局 Debug 状态
            var senparcSetting = SenparcSetting.BuildFromWebConfig(isGLobalDebug);
            var register = RegisterService.Start(senparcSetting).UseSenparcGlobal();//CO2NET全局注册，必须！

            var isWeixinDebug = false;//设置微信 Debug 状态
            var senparcWeixinSetting = SenparcWeixinSetting.BuildFromWebConfig(isWeixinDebug);
            register.UseSenparcWeixin(senparcWeixinSetting, senparcSetting);////微信全局注册，必须！
```

     

It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. AuthenticationFailure on PING

**Comment by JeffreySu** [comment]
这个错误一般就是因为访问不到redis服务，包括服务没有启动、网络访问有问题（也包括了连接字符串本身的问题）。先看一下这些问题是否存在。

另外： CacheStrategyFactory.RegisterObjectCacheStrategy(() => RedisObjectCacheStrategy.Instance); 这一句不建议写在最上面，因为此时Redis的连接字符串还没有通过CO2NET的全局注册写入到全局的变量中。

**Comment by JHeLiu** [comment]
目前无法证实，我已经移除默认的缓存机制了，当我使用我自己的redis连接缓存，可以正常跑。

**Comment by JeffreySu** [comment]
我觉得非常有可能的是这一句你放在了第一行：
CacheStrategyFactory.RegisterObjectCacheStrategy(() => RedisObjectCacheStrategy.Instance);
此时初始化Redis连接信息还没有完成，应该放在UseSenparcGlobal()寿面，参考Sample中的顺序。

**Comment by JHeLiu** [comment]
没有，项目里面是 注册在第一行，会报错，在本地没有问题，在服务器上会抛错，还有，我重写了未知类型，返回 null 为什么还是会自动返回 一条 未知类型的消息呢？ 当是未知类型，我不希望SDK给我返回任何信息，就当 忽略，

**Comment by JeffreySu** [comment]
1、按理说第一行就是会出问题的，不出问题应该是其他因素，其实这么做是不太好的，建议这个顺序：

``` C#
 var register = RegisterService.Start(senparcSetting).UseSenparcGlobal();
CacheStrategyFactory.RegisterObjectCacheStrategy(() => RedisObjectCacheStrategy.Instance);
```

我这边测试了多个环境都是正常的。

2、那说明这一条未知类型应该就是没有被接收到。外你希望忽略的话可以在 MessageHandler 外面 try 一下，然后返回空字符串即可。这边的异常作为 SDK 内部来说是应该要抛出的。其他的问题可以另外开一个issue。

**Comment by JeffreySu** [comment]
@JHeLiu  补充一下，关于自动处理未知类型的可以参考这里：https://www.cnblogs.com/szw/p/7742896.html

**Comment by JHeLiu** [comment]
@JeffreySu 是的，我看过你的写博客，我重写了这个方法，包括默认回复，当我发送未知类型它还是会回复一条信息，我想让它不返回任何信息，我返回了null,但是好像不能生效。我是这样做的
`/// <summary>
        /// 未知类型
        /// </summary>
        /// <param name="requestMessage"></param>
        /// <returns></returns>
        public override IResponseMessageBase OnUnknownTypeRequest(RequestMessageUnknownType requestMessage)
        {
            return null;
        }`
不知道这样处理是不是正确的？

**Comment by JeffreySu** [comment]
@JHeLiu 如果return null不生效，试一下：

``` C#
return new ResponseMessageNoResponse();
```

然后在Action中返回：
``` C#
return new FixWeixinBugWeixinResult(messageHandler);
```
