### ISSUE TITLE
System.net问题，未能链接到远程服务器 status code  302

### ISSUE THREAD

**Issue by Lipeiheng** [JeffreySu/WeiXinMPSDK#1292]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 重现问题步骤（如果可以）

1. 调用AccessTokenContainer.TryGetAccessToken时出现异常
2. 返回错误代码为302  重定向问题

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：

##### 模块对应的.net版本

- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [x] .net 4.5
- [x] .net 4.6.1
- [ ] .net core 1.x
- [ ] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2015

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
请问重定向到什么地方了？

测试地址访问是正常的。

**Comment by Lipeiheng** [comment]
status 状态 302  在本地测试代码 重定向显示404
