### ISSUE TITLE
CodeApi.GetCategoryAsync 空引用异常

### ISSUE THREAD

**Issue by 1015450578** [JeffreySu/WeiXinMPSDK#1293]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
当未显式设置Senparc.Weixin.Config.SenparcWeixinSetting属性的值时，几乎所有接口都会抛出空引用异常，因为Senparc.Weixin.Config.IsDebug未对Senparc.Weixin.Config.SenparcWeixinSetting属性做空的判断

##### 重现问题步骤（如果可以）

已重现的API CodeApi类型下的大部分接口

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [x] .net 4.0（已于2017年7月暂时停止更新）
- [] .net 4.5
- [] .net 4.6.1
- [ ] .net core 1.x
- [x] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：wuyafeng909099000@qq.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
@1015450578 这个问题应该是发生在已经升级到CO2NET的项目上，请参考我们新的Demo对SenparcWeixinSetting进行注册（必须）：

https://github.com/JeffreySu/WeiXinMPSDK/blob/f0fb5c1adc0608344ed9b5f011021fc3d9044339/Samples/Senparc.Weixin.MP.Sample.vs2017/Senparc.Weixin.MP.CoreSample/Startup.cs#L188

关于为null的问题确实需要增加一些容错的功能，以防大家没有按照demo做，感谢反馈！
