### ISSUE TITLE
sample能否升级到mvc5，vs2017打开即用最好

### ISSUE THREAD

**Issue by qzyuanmu** [JeffreySu/WeiXinMPSDK#1306]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述

我用vs2017打开，并自行升级到mvc5，修复一些报错以后，调试运行，发现redis都会自动注册，
其实在全局启动类中我已经注释掉redis了。

希望sample能vs2017打开即用，并可以正常运行起来

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [x] .net 4.5
- [x] .net 4.6.1
- [ ] .net core 1.x
- [ ] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
@qzyuanmu Redis的注册是有一个过程的，在startup中注册是非常安全的做法，你直接可以用说明我们的一套保障机制生效的，但是在一些情况下（比如你再startup中进行了一些缓存操作），就可能会碰到异常。

MVC5的问题我们会进行一些调研之后确定是否升级Demo。

谢谢！

**Comment by JeffreySu** [comment]
@qzyuanmu 已经完成升级，非常感谢！

顺便分享一下调研结果：

选项 |   | 回复情况 |  
-- | -- | -- | --
未使用 |   | 15.29% |  
MVC 3 |   | 1.18% |  
MVC 4 |   | 9.41% |  
MVC 5 |   | 58.82% |  
MVC 6 |   | 15.29%
