### ISSUE TITLE
.NET Core 2.1 SenparcOAuthAttribute 重复UrlEncode问题

### ISSUE THREAD

**Issue by LuohuaRain** [JeffreySu/WeiXinMPSDK#1308]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
`[CustomOAuth(appId,  "/Home/OAuthCallback", OAuthScope.snsapi_base)]`
被该特性标记的方法，在微信公众号的OAuth2.0授权时，会报redirect_uri参数错误
经查明，在微信返回的URL里，出现了returnUrl的2次html编码，目测是这个问题导致redirect_uri参数错误

在SenparcOAuthAttribute抽象类中，使用了Senparc.Weixin.HttpUtility.UrlUtility.GenerateOAuthCallbackUrl这个生成OAuthCallbackUrl的方法中，授权回调的字符串拼接中使用了 returnUrl.UrlEncode(); 目测这导致了重复UrlEncode的问题。

##### 重现问题步骤（如果可以）

1. 新建.NET Core 2.1的项目，（其他步骤略过）标记一个Action，然后用微信web开发工具去请求这个带有[CustomOAuth]特性的Action
2. 发现微信web开发工具会报redirect_uri参数错误，观察resquest请求可以发现，在returnUrl参数里的地址被URL编码了2次

（目测原因是，ASP.NET Core 2.1本身就对安全性做了很大的提高，所以在返回url时会自动编码一次？）
##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [x] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [ ] .net 4.5
- [ ] .net 4.6.1
- [ ] .net core 1.x
- [x] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [ ] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
本地测试了，我这边看到的编码没有问题，你再看看是不是其他配置的原因。

GenerateOAuthCallbackUrl() 方法中的 returnUrl.UrlEncode() 是必须的，因为这个参数是嵌入在即将生成的url里面作为一个参数的。
