### ISSUE TITLE
MailListApi中方法未封装2018/3/9号最新添加的属性to_invite

### ISSUE THREAD

**Issue by sherlockleo** [JeffreySu/WeiXinMPSDK#1316]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
在批量更新通讯录时，由于MailListApi中方法未封装2018/3/9号最新添加的属性to_invite，腾讯会自动发送通知到用户提示推荐用户下载企业微信app。
to_invite属性默认值为true，希望可以封装该属性，以便能够设置为false。
谢谢。

##### 重现问题步骤（如果可以）
1. 调用CreateMember方法，to_invite在发送包中默认值为true
2. 未加入企业微信用户会收到通知

##### 微信官方文档 URL
http://work.weixin.qq.com/api/doc#10018
http://work.weixin.qq.com/api/doc#11303

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [x ] Senparc.Weixin.QY 版本：~
- [x] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [x] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [x] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：frey.xu@outlook.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
已经修改，方法中有太多参数，已经整合到实体中。谢谢！
另外欢迎直接PR代码过来 😄
