### ISSUE TITLE
SDK中没有这两个接口

### ISSUE THREAD

**Issue by SummerTK** [JeffreySu/WeiXinMPSDK#1317]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
SDK中没有这两个接口
获取用户开卡时提交的信息（跳转型开卡组件）
获取用户开卡时提交的信息（非跳转型开卡组件）

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 微信官方文档 URL
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1499332673_Unm7V

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [x] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [x] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：tang14455@163.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
@SummerTK 欢迎PR

**Comment by JeffreySu** [comment]
此前已经添加：

https://github.com/JeffreySu/WeiXinMPSDK/blob/3b5713e245951c6d7c4eb6223bab2c88e8eee397/src/Senparc.Weixin.MP/Senparc.Weixin.MP/AdvancedAPIs/Card/CardAPI.cs#L1921

https://github.com/JeffreySu/WeiXinMPSDK/blob/3b5713e245951c6d7c4eb6223bab2c88e8eee397/src/Senparc.Weixin.MP/Senparc.Weixin.MP/AdvancedAPIs/Card/CardAPI.cs#L814

感谢！
