### ISSUE TITLE
appsettings.json配置多个公众号items时无法通过itemkey取值

### ISSUE THREAD

**Issue by TomLiu-GitHub** [JeffreySu/WeiXinMPSDK#1318]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
> appsettings.json配置多个公众号items时
 在Startup.Configure中注册公众号senparcWeixinSetting.Value.Items["itemkey"].WeixinAppId,值为null,而itemkey换成0可以取到

##### 重现问题步骤（如果可以）

1. 在appsettings.json中设置items配置
2. 在Startup.Configure中注册注册公众号senparcWeixinSetting.Value.Items["itemkey"].WeixinAppId,值为null,而itemkey换成0可以取到.

##### 发现问题的模块

- [x] Senparc.Weixin 版本：`Senparc.Weixin (>= 5.1.2)`
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [x] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by TomLiu-GitHub** [comment]
{
  "SenparcWeixinSetting": {
        "WeixinAppId": "xxx",
        "WeixinAppSecret": "xxx",
        "Token": "xxx",
        "EncodingAESKey": "xxx"
    "items": [
      {
        "ItemKey": "services",
        "WeixinAppId": "xxx",
        "WeixinAppSecret": "xxx",
        "Token": "xxx",
        "EncodingAESKey": "xxx"
      }
    ]
  }
}

**Comment by JeffreySu** [comment]
这样子是智能有序号的Key，你试试看数组里面分别给一下Key和Value。
