### ISSUE TITLE
无限制生成二维码问题

### ISSUE THREAD

**Issue by lb0726** [JeffreySu/WeiXinMPSDK#1320]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
调用无限制生成二维码的接口，如果scene为空字符串传入，则生成二维码失败
返回：{"errcode":40169,"errmsg":"invalid length for scene, or the data is not json string hint: [wPbCbA05029041]"}
官方似乎没有对scene必须要有值传入

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [x] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [x] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [ ] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
@lb0726 具体是哪一个接口？

**Comment by lb0726** [comment]
Senparc.Weixin.WxOpen.AdvancedAPIs.WxApp.WxAppApi.
                GetWxaCodeUnlimit(AppId, ms, scene, wxPath, width,auto_color,lineColor);

**Comment by JeffreySu** [comment]
@lb0726 测试了一下，这个接口似乎必须要求提供scene，代码中当参数为null已经自动忽略（和""空值不一样），我做了一个单元测试，不管是null还是空值都是不允许的，有值就可以：

https://github.com/JeffreySu/WeiXinMPSDK/blob/ab2485b5fbc86cb5c13c5e57c763f15f988f1109/src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen.Tests/AdvancedAPIs/WxApp/WxAppApiTests.cs#L135
