### ISSUE TITLE
素材下载提示接口提示40007错误。跟踪源码发现mediaapi中没有传递参数

### ISSUE THREAD

**Issue by buyixiaohan** [JeffreySu/WeiXinMPSDK#1326]
##### 问题描述
通过微信公众号的下载素材接口下载图片时，一直出现40007错误，提示media_id无效

##### 重现问题步骤
代码调用：
`var result = MediaApi.GetForeverMedia(accessToken, media_id, ms);`

代码调用（Senparc.Weixin.MP.AdvancedAPIs.MediaApi源码）:
`public static WxJsonResult GetForeverMedia(string accessTokenOrAppId, string mediaId, Stream stream, int timeOut = Config.TIME_OUT)`
`        {`
`            return ApiHandlerWapper.TryCommonApi(accessToken =>`
`            {`
`                string urlFormat = string.Format(Config.ApiMpHost + "/cgi-bin/material/get_material?access_token={0}", (object)accessToken.AsUrlData());`
`                var data = new`
`                {`
`                    media_id = mediaId`
`                };`

`                if (stream != null)`
`                {`
`                    stream.Seek(0, SeekOrigin.Begin);`
`                    Post.Download(urlFormat,null, stream);`
`                }`
`                return new WxJsonResult() { errcode = ReturnCode.请求成功, errmsg = "ok" };//无实际意义`
`            }, accessTokenOrAppId);`
`        }`

在代码`Post.Download(urlFormat,null, stream); `中，第二个参数始终为null，在微信接口调用时，没有media_id参数，导致一直返回编码40007（40007 | 不合法的媒体文件 id）

##### 微信官方文档 URL
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1444738730

##### 微信官方文档快照（直接复制关键内容到下方）

参数 | 是否必须 | 说明
-- | -- | --
access_token | 是 | 调用接口凭证
media_id | 是 | 要获取的素材的media_id

##### 发现问题的模块

- [x] Senparc.Weixin 版本：5.1.4
- [x] Senparc.Weixin.MP 版本：15.1.3
- [x] Senparc.Weixin.MP.MVC 版本：6.0.10

##### 模块对应的 .net 版本
- [x] .net 4.5

##### 开发环境
- [x] Visual Studio 2017

##### 缓存环境
无

##### 联系方式
Email：wang97322@foxmail.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
核对一下，你使用下载的接口，和你上传素材的接口，在永久和临时素材上是否匹配？

**Comment by JeffreySu** [comment]
确实可能有这个问题

**Comment by JeffreySu** [comment]
@JadynWong 是不是上次分离的时候启用了原来注释掉的代码？

https://github.com/JeffreySu/WeiXinMPSDK/commit/948ec751

**Comment by JeffreySu** [comment]
查了一下确实应该是没有传入

**Comment by JeffreySu** [comment]
已经发布：https://www.nuget.org/packages/Senparc.Weixin.MP/15.1.4

**Comment by JadynWong** [comment]
@JeffreySu 恩，是取消原来的注释，很久没调用这个接口，没发现这个问题，抱歉

**Comment by JadynWong** [comment]
@JeffreySu MP csproj 版本号没有变更

**Comment by JeffreySu** [comment]
@JadynWong 非常感谢PR，也是因为我这边没有测试好。

等下有新的稳定版本发布，会统一分配版本号。
