### ISSUE TITLE
微信小店中的查询商品列表出错，string to int32 出错

### ISSUE THREAD

**Issue by hybiz** [JeffreySu/WeiXinMPSDK#134]
public class PropertyItem
    {
        /// <summary>
        /// 属性id
        /// </summary>
        public int id { get; set; }
        /// <summary>
        /// 属性名称
        /// </summary>
        public string name { get; set; }
        /// <summary>
        /// 属性值
        /// </summary>
        public List<PropertyValue> property_value { get; set; }
    }
id应该是string类型，原技术文档是：
"property": [
				{
					"id": "品牌",
					"vid": "Fujifilm/富士"
				},
				{
					"id": "屏幕尺寸",
					"vid": "1.8英寸"
				},

**Comment by nsoff** [comment]
是我也发现此问题了。只能自己把类型修改了。最好是官方修改。

**Comment by JeffreySu** [comment]
官方的PropertyItem已经是string了，你们说的是不是PropertyValue？

**Comment by JeffreySu** [comment]
已经修改了PropertyValue，v13.8.6
