### ISSUE TITLE
会员卡中的拉取会员信息（积分查询）接口缺少

### ISSUE THREAD

**Issue by hybiz** [JeffreySu/WeiXinMPSDK#135]
1、会员卡中的拉取会员信息（积分查询）接口缺少
2、类型Card_MemberCardUpdateData中不存在custom_field1等其它字段

**Comment by TYSZCC** [comment]
第二个问题出在哪里，能否把文档的链接发来看一下？

**Comment by hybiz** [comment]
在会员卡专区的更改卡券信息接口中 会员卡专属字段修改：
特别注意，以下支持更新的字段不在基本信息base_info的结构中。

**Comment by AnnXu** [comment]
@hybiz对于第一个问题，拉取会员信息接口已有， 
 /// <summary>
        /// 拉取会员信息接口
        /// </summary>
        /// <param name="accessTokenOrAppId"></param>
        /// <param name="cardId">CardID</param>
        /// <param name="code">Code</param>
        /// <param name="timeOut"></param>
        /// <returns></returns>
        public static UserinfoGetResult UserinfoGet(string accessTokenOrAppId, string cardId, string code, int timeOut = Config.TIME_OUT)
        {
            return ApiHandlerWapper.TryCommonApi(accessToken =>
            {
                var urlFormat = string.Format("https://api.weixin.qq.com/card/membercard/userinfo/get?access_token={0}", accessToken);

                return CommonJsonSend.Send<UserinfoGetResult>(null, urlFormat, new { card_id = cardId, code = code }, timeOut: timeOut);
            }, accessTokenOrAppId);
        }

**Comment by AnnXu** [comment]
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1466494654_K9rNz&token=&lang=zh_CN

**Comment by JeffreySu** [comment]
> 2、类型Card_MemberCardUpdateData中不存在custom_field1等其它字段

经检查是有这几个字段的：https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1466494654_K9rNz
