### ISSUE TITLE
SDK事件推送中缺少接收礼品卡相关事件推送

### ISSUE THREAD

**Issue by 183328251** [JeffreySu/WeiXinMPSDK#1350]
##### 问题描述
礼品卡相关事件推送缺少
giftcard_pay_done
giftcard_send_to_friend
giftcard_user_accept 

##### 微信官方文档 URL
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=215143440770UT7Y
10.礼品卡相关事件

##### 微信官方文档快照（直接复制关键内容到下方）
`
<xml>
<ToUserName><![CDATA[gh_3fcea188bf78]]></ToUserName>
<FromUserName><![CDATA[obLatjgoYejavUtHsWwrX-2GtFJE]]></FromUserName>
<CreateTime>1472631550</CreateTime>
<MsgType><![CDATA[event]]></MsgType>
<Event><![CDATA[giftcard_pay_done]]></Event>
<PageId><![CDATA[OQK0R3MaFnCm74Phw5hwFJlz5sn+jy1zzM2amDidDbU=]]></PageId>
<OrderId><![CDATA[Z2y2rY74ksZX1ceuGA]]></OrderId>
</xml>
`

参数 | 说明
-- | --
ToUserName | 接收该事件的公众号原始id
FromUserName | 事件发起人，该事件中标识下单购买人的openid
CreateTime | 事件创建时间
MsgType | 消息类型
Event | 事件类型，此处为giftcard_pay_done标识订单完成事件
PageId | 货架的id
OrderId | 订单号

##### 发现问题的模块
- [ ] Senparc.Weixin.MP 版本：v15.2.2

##### 联系方式
Email：183328251@qq.com

**Comment by JeffreySu** [comment]
已经添加，感谢提醒！也欢迎直接PR代码过来 😄
