### ISSUE TITLE
WxOpen小程序DEMO配置错误

### ISSUE THREAD

**Issue by lingkejia** [JeffreySu/WeiXinMPSDK#1352]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
public static readonly string EncodingAESKey = Config.SenparcWeixinSetting.EncodingAESKey;
该配置数据为微信公众号的EncodingAESKey，导致排查了很长时间，请及时修改
修改为Config.SenparcWeixinSetting.WxOpenEncodingAESKey

##### 发现问题的模块
- [ ] Senparc.Weixin.WxOpen 版本：

##### 模块对应的 .net 版本
- [x] .net 4.5

##### 开发环境
- [x] Visual Studio 2017

##### 联系方式
Email：2151975@qq.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
感谢！已经修改。欢迎PR ：）
