### ISSUE TITLE
微信支付中的参数配置，只能用于WEB端，用于WinForm客户端出错。

### ISSUE THREAD

**Issue by hybiz** [JeffreySu/WeiXinMPSDK#136]
RequestHandler packageReqHandler = new RequestHandler(null);
微信支付中的参数配置，只能用于WEB端，用于WinForm客户端出错。希望改进下，搞个通用的。

**Comment by JeffreySu** [comment]
你说的问题是不是HttpContext.Current获取不到的问题？自己new一个就行了。这个API发生的环境就是Web端的，需要jsApi。
