### ISSUE TITLE
开放平台的添加类目方法实体写的不对

### ISSUE THREAD

**Issue by hao123hl** [JeffreySu/WeiXinMPSDK#1370]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
如题

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 微信官方文档 URL
https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=21528465979XX32V&token=&lang=zh_CN

##### 微信官方文档快照（直接复制关键内容到下方）
{
    “categories”: [
        {
            “first”: 8,
            “second”: 39,
            “certicates”: [
                {
                    “key”: ”《因私出入境中介机构经营许可证》”,
                    “value”: ”xxx”
                }
            ]
        }
    ]
}

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [√ ] Senparc.Weixin.Open 版本：2018年8月3号拿的代码，不知道版本
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [√ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [x] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ √] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ √] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
已上线：https://www.nuget.org/packages/Senparc.Weixin.Open/4.1.2

感谢！欢迎PR代码 😄
