### ISSUE TITLE
最新得sdk还需要注册这个方法么RegisterWeixinThreads（）

### ISSUE THREAD

**Issue by ccccccmd** [JeffreySu/WeiXinMPSDK#1378]
/// <summary>
        /// 激活微信缓存
        /// </summary>
        private void RegisterWeixinThreads()
        {
            ThreadUtility.Register();//如果不注册此线程，则AccessToken、JsTicket等都无法使用SDK自动储存和管理。
        }

**Comment by JeffreySu** [comment]
什么问题？

**Comment by ccccccmd** [comment]
我看到  [Global.asax.cs](https://github.com/JeffreySu/WeiXinMPSDK/blob/master/Samples/Senparc.Weixin.MP.Sample/Senparc.Weixin.MP.Sample/Global.asax.cs#L29) 里 原始方式 有这段 方法，使用RegisterServices方式注册是不需要得是吧

**Comment by JeffreySu** [comment]
@ccccccmd 对的，现在已经不需要单独执行了，只要用RegisterServices方式注册就会自动开启。
