### ISSUE TITLE
Global 中 Redis 启用时报错

### ISSUE THREAD

**Issue by AjuPrince** [JeffreySu/WeiXinMPSDK#1385]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)
##### 问题描述

按照 Github Demo 中Global 中的配置，启用Redis时会报错,错误信息如下：
![image](https://user-images.githubusercontent.com/16829343/45140849-b6119480-b1e6-11e8-98a0-3d4228631e9c.png)
并按照 https://www.cnblogs.com/szw/p/9265828.html 是解决不掉这个问题的
如果注释掉 就不会出现这个错误，注释代码如下：
 //配置全局使用Redis缓存（按需，独立）
            var redisConfigurationStr = senparcSetting.Cache_Redis_Configuration;
            var useRedis = !string.IsNullOrEmpty(redisConfigurationStr) && redisConfigurationStr != "Redis配置";
            if (useRedis)
            {
                //Senparc.CO2NET.Cache.Redis.Register.SetConfigurationOption(redisConfigurationStr);
                //Senparc.CO2NET.Cache.Redis.Register.UseKeyValueRedisNow();
                //CacheStrategyFactory.RegisterObjectCacheStrategy(() => Senparc.CO2NET.Cache.Redis.RedisObjectCacheStrategy.Instance);
            }
##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [√ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ √] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [x] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ √] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：1022560838@qq.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
对应Demo的这一行代码你是怎么写的：

`var register = RegisterService.Start(senparcSetting).UseSenparcGlobal();//CO2NET全局注册，必须！`

如果不涉及到Redis自动扫描的话，是不会执行到那里去的，应该是哪边还是有扫描或调用才会这样。

**Comment by AjuPrince** [comment]
我是完全按照 Demo 写的  
var register = RegisterService.Start(senparcSetting).UseSenparcGlobal();//CO2NET全局注册，必须！
这里的写法已经 下面 Redis 配置的写法都是 和 Demo 一样的 
可以说 是从 Demo 中复制过来的

**Comment by JeffreySu** [comment]
那你说的还是有错误是不是执行了：GetExCacheStrategies 这个方法了？

**Comment by AjuPrince** [comment]
没有执行这个方法，这个方法在最新的Demo里没有了，我也就删除了。

**Comment by AjuPrince** [comment]
我在自己的电脑上 运行的Redis，调试的时候就报错了，Global里的代码 全部是从最新的Demo里复制过来的。当我把 redis 注释掉后，再次运行时一切正常。

**Comment by JeffreySu** [comment]
另外你看一下Demo代码的顺序，和你程序里面有没有差别，如果完全不涉及到缓存的话，默认会自动注册本地缓存的。

**Comment by AjuPrince** [comment]
![image](https://user-images.githubusercontent.com/16829343/45195734-9e401c00-b28b-11e8-9897-39a1d0ff3cb5.png)
这是 本地日志
代码我反复看了，一点问题都没有。

**Comment by JeffreySu** [comment]
这个应该还是哪里触发到Redis了，SDK本身不会去强制调用Redis的。
另外如果你不用Redis的话，不需要安装Redis的库，或者把app.settings中的Redis连接字符串设置成我们Demo默认的内容，会跳过的。

**Comment by 491134648** [comment]
同样问题，按照demo文档写的
当前扩展缓存策略没有进行注册：Senparc.Weixin.Cache.ContainerCacheStrategyDomain，Senparc.CO2NET.Cache.Redis.RedisObjectCacheStrategy，解决方案请参考：https://weixin.senparc.com/QA-551

**Comment by JeffreySu** [comment]
@AjuPrince @491134648  这个问题我这边一直没法重现，后来也重构了一次，现在你们那边还有这个异常吗？
