### ISSUE TITLE
希望能在 CreateResponseMessage中增加一个“能按照media_id”发送信息的功能

### ISSUE THREAD

**Issue by zmrbak** [JeffreySu/WeiXinMPSDK#139]
var strongResponseMessage = CreateResponseMessage《ResponseMessageNews》();
                        reponseMessage = strongResponseMessage;
                        strongResponseMessage.Articles.Add(new Article()
                        {
                            Title = "家用清洁系列1",
                            Description = "",
                            PicUrl =“http://asda/com?wx_fmt=jpeg",
                            Url = "http://mp.weixin.qq.com/s?#rd"
                        });
                      strongResponseMessage.Articles.Add(new Article()
                        {
                            Title = "家用清洁系列2",
                            Description = "",
                            PicUrl =“http://asda/com?wx_fmt=jpeg",
                            Url = "http://mp.weixin.qq.com/s?#rd"
                        });

在一些应用中，我想直接发送这个News的media_id，或者直接发送者几个News列表的media_id。
如果能够这样，编程中会轻松很多：
var strongResponseMessage = CreateResponseMessage《ResponseMessageNews》();
                        reponseMessage = strongResponseMessage;
                        strongResponseMessage.Media_ID="12313213245645";

希望能得到帮助。

**Comment by zmrbak** [comment]
这个功能涉及到底层的改动。

**Comment by JeffreySu** [comment]
你说的Media_ID是素材的ID吗？已经有发送素材的接口了，据我所知素材的具体内容好像是获取不到的，这样就没有办法在服务器实现内容的填充的。
如果你发现有这样的接口的话麻烦给一下文档地址，谢谢！

**Comment by zmrbak** [comment]
http://mp.weixin.qq.com/wiki/11/c88c270ae8935291626538f9c64bd123.html#.E5.AE.A2.E6.9C.8D.E6.8E.A5.E5.8F.A3-.E5.8F.91.E6.B6.88.E6.81.AF

【好像是微信新添加不久的功能】
http请求方式: POST
https://api.weixin.qq.com/cgi-bin/message/custom/send?access_token=ACCESS_TOKEN
**发送图文消息**（点击跳转到图文消息页面） 图文消息条数限制在8条以内，注意，如果图文数超过8，则将会无响应。

{
    "touser":"OPENID",
    "msgtype":"mpnews",
    "mpnews":
    {
         "media_id":"MEDIA_ID"
    }
}

**Comment by zmrbak** [comment]
图文素材ID，我是通过遍历微信图文信息，然后保存在本地数据库中。随时检索。

**Comment by zmrbak** [comment]
微信给的图文消息，只有图文组的Media_ID，图文组中的单独图文消息没有Media_ID.

**Comment by TYSZCC** [comment]
感谢您的反馈，接口已经添加
