### ISSUE TITLE
MessageHandler.ExecuteAsync()触发System.NullReferenceException异常

### ISSUE THREAD

**Issue by OrchesAdam** [JeffreySu/WeiXinMPSDK#1396]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
&emsp;调用MessageHandler.ExecuteAsync()时，MessageHandlerNode.ExecuteAsync()会触发触发System.NullReferenceException异常。导致不会执行OnTextRequestAsync()或者OnTextOrEventRequestAsync()方法

##### 重现问题步骤（如果可以）

1. ...

2. ...

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [x] Senparc.Weixin.MP 版本：16.2.2
- [ ] Senparc.Weixin.MP.MVC 版本：
- [x] Senparc.Weixin.Open 版本：4.1.5
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [x] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
有更加详细一点的日志吗？例如收到的xml等，以便我们可以做测试。

**Comment by OrchesAdam** [comment]
```
signature=bf36233bf090a19ce8ea73ebe79abd4284f9254f&timestamp=1536634755&nonce=2006184340&openid=oh2P-0xIBTv__HXb5qOGX6qp06Y4&encrypt_type=aes&msg_signature=2f1ccca4ac96f941a973233878da11cba9d7b348
```
> 消息 xml
```
<xml>
    <ToUserName><![CDATA[gh_ab57940bad8a]]></ToUserName>
    <Encrypt><![CDATA[ffV0/TZH1bAhKW5/Jh+nIKIVILMmRR6D25caNM6ZkmuKozXlE9m9KledzddSpDMhYuudTlpsJZXRKF78dluRK0mFQFdxdebX9mi1IBW75RyVoxcp6oi92p8t7efJBLCbrITXBWgRXpq7s83m0/yZop0KjhgyihaP1+gy1kqESweLsF+C80OsTafCiRulVM7Mpkjpo0Ym+/WInV4iHyCWWObuziiP0BBpiBwIQaYs6KD9ErS3WHpNvhBbkE6NObBYOpkbTV9dfSGWT97YfsxmIzCxWW0X2yHZ9gC9jO2T1ihjZAj1KYwNTfIQx9qISbDFT+DKFSr+z4q93QkhrELG+9jK0smxk9CTqgU2Be9snO3djadF+FoCWTLv/rZfrPCtQvOCFwe6cEeCrXczYmQPz0RWZfXwnStT+LQuZRlbXFk=]]></Encrypt>
</xml>
```

**Comment by JeffreySu** [comment]
@OrchesAdam 没有Token无法解密，你应该日志也可以拿到明文的记录的。

**Comment by OrchesAdam** [comment]
不好意思没有注意到这个。

> 解密后的消息

```
{
  "MsgType": 0,
  "Content": "测试",
  "MsgId": 6599796019053650714,
  "Encrypt": "ffV0/TZH1bAhKW5/Jh+nIKIVILMmRR6D25caNM6ZkmuKozXlE9m9KledzddSpDMhYuudTlpsJZXRKF78dluRK0mFQFdxdebX9mi1IBW75RyVoxcp6oi92p8t7efJBLCbrITXBWgRXpq7s83m0/yZop0KjhgyihaP1+gy1kqESweLsF+C80OsTafCiRulVM7Mpkjpo0Ym+/WInV4iHyCWWObuziiP0BBpiBwIQaYs6KD9ErS3WHpNvhBbkE6NObBYOpkbTV9dfSGWT97YfsxmIzCxWW0X2yHZ9gC9jO2T1ihjZAj1KYwNTfIQx9qISbDFT+DKFSr+z4q93QkhrELG+9jK0smxk9CTqgU2Be9snO3djadF+FoCWTLv/rZfrPCtQvOCFwe6cEeCrXczYmQPz0RWZfXwnStT+LQuZRlbXFk=",
  "ToUserName": "gh_ab57940bad8a",
  "FromUserName": "oh2P-0xIBTv__HXb5qOGX6qp06Y4",
  "CreateTime": "2018-09-11T10:59:15+08:00"
} 
```


![image](https://user-images.githubusercontent.com/10153835/45466457-903b4100-b74c-11e8-948a-5a8de0465ea6.png)


![image](https://user-images.githubusercontent.com/10153835/45466460-99c4a900-b74c-11e8-9faa-0f27fd7f9b91.png)

**Comment by JeffreySu** [comment]
好的，明天我详细查一下。顺便问一下你是按照Demo里面的方法注册AppId的吗？

**Comment by OrchesAdam** [comment]
是的，
只是将
```
private string appId = "appId";
```
字段更改成了一个属性
```
public string ComponentAppId { get; set; }
```

**Comment by JeffreySu** [comment]
没太明白，是改在了哪里？

**Comment by OrchesAdam** [comment]
`CustomMessageHandler`这个类

**Comment by JeffreySu** [comment]
要不我远程看一下吧，加我QQ：498977166

**Comment by JeffreySu** [comment]
@shujian163  上面的问题我和 @OrchesAdam 已经解决了，你确定用的是最新版本的SDK吗？

**Comment by shujian163** [comment]
是的,我今天使用 nuget 更新的.
`
        public override async Task<IResponseMessageBase> OnTextRequestAsync(RequestMessageText requestMessage)
        {
            if (requestMessage.Content == "TESTCOMPONENT_MSG_TYPE_TEXT")
            {


                var responseMessage = requestMessage.CreateResponseMessage<ResponseMessageText>(this.MessageEntityEnlightener);
                responseMessage.Content = requestMessage.Content + "_callback";//固定为TESTCOMPONENT_MSG_TYPE_TEXT_callback


                return responseMessage;
            }

            if (requestMessage.Content.StartsWith("QUERY_AUTH_CODE:"))
            {
                string openTicket = GetOpenTicket(componentAppId);
                var query_auth_code = requestMessage.Content.Replace("QUERY_AUTH_CODE:", "");
                try
                {
                    var component_access_token = ComponentApi.GetComponentAccessToken(componentAppId, componentSecret, openTicket).component_access_token;
                    var oauthResult = ComponentApi.QueryAuth(component_access_token, componentAppId, query_auth_code);

                    //调用客服接口
                    var content = query_auth_code + "_from_api";
                    var sendResult = Senparc.Weixin.MP.AdvancedAPIs.CustomApi.SendText(oauthResult.authorization_info.authorizer_access_token,
                          requestMessage.FromUserName, content);
                }
                catch (Exception ex)
                {
                    throw;
                }

            }


            return null;
        }`

**Comment by JeffreySu** [comment]
@shujian163 最新版本的可用了吧？

**Comment by shujian163** [comment]
可以了
