### ISSUE TITLE
RegisterMpAccount好像会强制创建一个accesstoken为null的缓存？

### ISSUE THREAD

**Issue by yushiro** [JeffreySu/WeiXinMPSDK#1399]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
使用redis作为缓存， 创建一个新的console项目，初始化后，redis中可以看到accesstoken的记录，
但是再次运行此console项目，程序会重新获取一个新的accesstoken，并替换redis中的数据，而不是从redis中获取。

经过研究， 发现问题在RegisterMpAccount这个方法中， 如果不运行RegisterMpAccount，则可以从redis中取出已缓存的accesstoken。
但如果初始化的时候执行了RegisterMpAccount方法，则会强制生成一个accesstoken为null的记录，并覆盖到redis中， 导致调用api的时候， 会重新去获取token。

所有的dll版本都是2018-9-10从nuget上下载的。

##### 重现问题步骤（如果可以）
console项目的代码如下
···
static void Main(string[] args)
        {

            var isGLobalDebug = true;
            var senparcSetting = SenparcSetting.BuildFromWebConfig(isGLobalDebug);

            //CO2NET 全局注册，必须！！
            IRegisterService register = RegisterService.Start(senparcSetting)
                                          .UseSenparcGlobal(false, null);

            //配置全局使用Redis缓存（按需，独立）
            var redisConfigurationStr = senparcSetting.Cache_Redis_Configuration;
            var useRedis = !string.IsNullOrEmpty(redisConfigurationStr) && redisConfigurationStr != "Redis配置";
            if (useRedis)//这里为了方便不同环境的开发者进行配置，做成了判断的方式，实际开发环境一般是确定的，这里的if条件可以忽略
            {
                /* 说明：
                 * 1、Redis 的连接字符串信息会从 Config.SenparcSetting.Cache_Redis_Configuration 自动获取并注册，如不需要修改，下方方法可以忽略
                /* 2、如需手动修改，可以通过下方 SetConfigurationOption 方法手动设置 Redis 链接信息（仅修改配置，不立即启用）
                 */
                Senparc.CO2NET.Cache.Redis.Register.SetConfigurationOption(redisConfigurationStr);

                //以下会立即将全局缓存设置为 Redis
                Senparc.CO2NET.Cache.Redis.Register.UseKeyValueRedisNow();//键值对缓存策略（推荐）
                //Senparc.CO2NET.Cache.Redis.Register.UseHashRedisNow();//HashSet储存格式的缓存策略

                //也可以通过以下方式自定义当前需要启用的缓存策略
                //CacheStrategyFactory.RegisterObjectCacheStrategy(() => RedisObjectCacheStrategy.Instance);//键值对
                //CacheStrategyFactory.RegisterObjectCacheStrategy(() => RedisHashSetObjectCacheStrategy.Instance);//HashSet
            }
            //如果这里不进行Redis缓存启用，则目前还是默认使用内存缓存 

            /* 微信配置开始
             * 建议按照以下顺序进行注册
             */

            //设置微信 Debug 状态
            var isWeixinDebug = true;
            var senparcWeixinSetting = SenparcWeixinSetting.BuildFromWebConfig(isWeixinDebug);

            //微信全局注册，必须！！
            register.UseSenparcWeixin(senparcWeixinSetting, senparcSetting);
            //.RegisterMpAccount(senparcWeixinSetting, "公众号");

            //Console.WriteLine("ok1");
            //Console.ReadKey();
            var tokenResult = AccessTokenContainer.GetAccessTokenResult(senparcWeixinSetting.WeixinAppId);
            
            Console.WriteLine(tokenResult.access_token);

            Console.WriteLine("ok");
            Console.ReadKey();
        }
···
1. ...
2. ...

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [x] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [ ] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [x] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
感谢建议和细心的解读！针对这个问题我做一下解释：

因为分布式缓存相对是无状态（非内部资源）的，为保险起见，我们在设计上把注册过程做成了强制覆盖，并建议所有的服务器（负载均衡等集群中）都进行一次注册，null没有关系，在执行AccessTokenContainer.GetAccessTokenResult()等方法时会自动判断过期状态并重新获取，或者在第一次接口调用失败之后会自动获取（少数情况）。

之所以可以这么设计，也是因为常规的重启是用不完接口每日限制的。当然如果你的业务非常特殊的话，也可以用专门的一个服务（或其中一个网站、一个exe）开在后台进行注册，其他web站点（或exe）都不注册。

如果为了少一次获取accesstoken而进行一系列的判断，事实上也需要服务器进行缓存有效性判断和accesstoken有效性判断等一系列繁琐的过程，反而把流程弄复杂了。

**Comment by yushiro** [comment]
感谢您的回复，在用redis作为缓存的过程中， 发现相关资料好少啊，最开始以为是初始化代码有问题， 除了Sample项目中大批量的初始化代码之外， 其他相关资料网上几乎都找不到，不知能否在wiki中增加一些这方面的简介或者说明？

**Comment by JeffreySu** [comment]
整个我们架构的设计就是希望可以无差别化地进行开发，因此你看到了很多抽象和工厂模式，只需要做一个缓存切换，在逻辑代码上不需要做任何的修改。开发的时候和使用本地缓存没有差别。

如果要知道里面的原理，可以参考[《微信开发深度解析》](https://item.jd.com/12220004.html)一书，虽然后来还有一些升级，不过总体思想、核心是一致的。
