### ISSUE TITLE
Senparc.Weixin.Open的README.md文件内容错误使用了企业号的

### ISSUE THREAD

**Issue by 554393109** [JeffreySu/WeiXinMPSDK#1404]
##### 问题描述
Senparc.Weixin.Open的README.md文件内容错误使用了企业号的

##### 重现问题步骤（如果可以）
1. https://github.com/JeffreySu/WeiXinMPSDK/blob/master/src/Senparc.Weixin.Open/readme.md

##### 发现问题的模块
- [x] Senparc.Weixin.Open 版本：

##### 联系方式
Email：554393109@qq.com

**Comment by JeffreySu** [comment]
已修正，非常感谢！
