### ISSUE TITLE
分布式缓存token不一致的问题

### ISSUE THREAD

**Issue by 491134648** [JeffreySu/WeiXinMPSDK#1405]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [x ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [x] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [] 服务器内存缓存（默认）
- [ x] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：491134648@163.com
 现有两个应用，一个基于.net framework,依赖环境如下
` <package id="Senparc.Weixin" version="4.20.3" targetFramework="net461" />
  <package id="Senparc.Weixin.Cache.Redis" version="1.5.1" targetFramework="net461" />
  <package id="Senparc.Weixin.Cache.Redis.RedLock" version="1.1.0" targetFramework="net461" />
  <package id="Senparc.Weixin.MP" version="14.12.3" targetFramework="net461" />`
集成代码如下
`public static class RegisterServiceUtil
    {
        /// <summary>
        /// 开始 Senparc.Weixin SDK 初始化参数流程
        /// </summary>
        /// <returns></returns>
        public static void Start()
        {
            var register = new RegisterService();
           
            //如果不注册此线程，则AccessToken、JsTicket等都无法使用SDK自动储存和管理。
            register
            #region 注册分自定义（分布式）缓存策略（按需，如果需要，必须放在第一个）

                // 当同一个分布式缓存同时服务于多个网站（应用程序池）时，可以使用命名空间将其隔离（非必须）
                .ChangeDefaultCacheNamespace("DefaultWeixinCache")

                //配置Redis缓存
                .RegisterCacheRedis(
                    ConfigurationManager.AppSettings["Cache_Redis_Configuration"],
                    redisConfiguration => (!string.IsNullOrEmpty(redisConfiguration))
                                         ? RedisObjectCacheStrategy.Instance
                                         : null)

            #endregion
                                         .RegisterThreads()

                .Init();//默认把线程注册好

            
        }
        public static IRegisterService Init(this IRegisterService service)
        {
            #region 注册日志（按需）

            #region 注册公众号或小程序（按需）
            //注册公众号
            return service
              
                .RegisterMpAccount(
                    ConfigurationManager.AppSettings["WeixinAppId"],
                    ConfigurationManager.AppSettings["WeixinAppSecret"],
                    ConfigurationManager.AppSettings["InstanceName"])
                //注册最新微信支付版本（V3）
                .RegisterTenpayV3(() =>
                {
                    //提供微信支付信息
                    var tenPayV3_MchId = ConfigurationManager.AppSettings["TenPayV3_MchId"];
                    var tenPayV3_Key = ConfigurationManager.AppSettings["TenPayV3_Key"];
                    var tenPayV3_AppId = ConfigurationManager.AppSettings["TenPayV3_AppId"];
                    var tenPayV3_AppSecret = ConfigurationManager.AppSettings["TenPayV3_AppSecret"];
                    var tenPayV3_TenpayNotify = ConfigurationManager.AppSettings["TenPayV3_TenpayNotify"];
                    var tenPayV3Info = new TenPayV3Info(tenPayV3_AppId, tenPayV3_AppSecret,
                        tenPayV3_MchId, tenPayV3_Key, tenPayV3_TenpayNotify);
                    WechatConfig.Instance.Init(tenPayV3_AppId, tenPayV3_AppSecret
                        , tenPayV3_MchId, tenPayV3_Key, ConfigurationManager.AppSettings["PkPath"]);
                    return tenPayV3Info;
                });

            #endregion//配置TraceLog

            #endregion
        }

    }`
另一应用基于asp.net core 2.0
依赖如下
`<PackageReference Include="Senparc.Weixin" Version="6.1.1" />
    <PackageReference Include="Senparc.Weixin.Cache.Redis" Version="2.2.1" />
    <PackageReference Include="Senparc.Weixin.mp" Version="16.3.3" />
    <PackageReference Include="Senparc.Weixin.TenPay" Version="0.2.1" />`
集成代码如下
`
            //添加Senparc.Weixin配置文件（内容可以根据需要对应修改）
            services.Configure<SenparcWeixinSetting>(Configuration.GetSection("SenparcWeixinSetting"))
                    .AddSenparcGlobalServices(Configuration)//Senparc.CO2NET 全局注册
                    .AddSenparcWeixinServices(Configuration);//Senparc.Weixin 注册;`
`     app.UseStaticFiles()
                .UseSession()
                .UseMvcWithAreaRoute()
                .UseWeChat(env,senparcSetting,senparcWeixinSetting);`
`public static IApplicationBuilder UseWeChat(this IApplicationBuilder app, IHostingEnvironment env,IOptions<SenparcSetting> senparcSetting, IOptions<SenparcWeixinSetting> senparcWeixinSetting, bool isDebug=false)
        {
            var exContainerCacheStrategies = new List<IDomainExtensionCacheStrategy>();
            exContainerCacheStrategies.Add(RedisContainerCacheStrategy.Instance);
            IRegisterService register = RegisterService.Start(env, senparcSetting.Value)
                                                         //关于 UseSenparcGlobal() 的更多用法见 CO2NET Demo：https://github.com/Senparc/Senparc.CO2NET/blob/master/Sample/Senparc.CO2NET.Sample.netcore/Startup.cs
                                                         .UseSenparcGlobal();
            #region 缓存配置

            // 当同一个分布式缓存同时服务于多个网站（应用程序池）时，可以使用命名空间将其隔离（非必须）
            register.ChangeDefaultCacheNamespace("DefaultWeixinCache");
            Senparc.CO2NET.Cache.Redis.Register.SetConfigurationOption(senparcSetting.Value.Cache_Redis_Configuration);
            #endregion
            Senparc.CO2NET.Cache.Redis.Register.UseKeyValueRedisNow();
            #region 注册日志（按需，建议）
            app.UseSenparcWeixinCacheRedis();
            register.UseSenparcWeixin(senparcWeixinSetting.Value, senparcSetting.Value);
            register.RegisterMpAccount(senparcWeixinSetting.Value, "Farm.Wechat");
            register.RegisterTenpayV3(senparcWeixinSetting.Value, "Farm.Wechat");
            #region 注册公众号或小程序（按需）

            //注册公众号（可注册多个）

            //注册最新微信支付版本（V3）（可注册多个）
            //记录到同一个 SenparcWeixinSettingItem 对象中

            //除此以外，仍然可以在程序任意地方注册公众号或小程序：
            //AccessTokenContainer.Register(appId, appSecret, name);//命名空间：Senparc.Weixin.MP.Containers
            #endregion
            #endregion
           
            return app;`
调用两个项目获取的token分别如下
`13_bfhl5kNI3ey0L7cUfB5ltTsDu-D3dHdBIND6V_8mtVMU14mGKN8BRKdzAokWj8xQmYcLHRzBDP_rMytuBBaR3fkHztSnOPfPuCind8RMuaCzCDPP0ovE-Ywjh7CyAONuM6MXVqdQePks4XnRMASiADAWKC`
`13_N6_fE5k3ru3Lk3tKfB5ltTsDu-D3dHdBIND6V_8mtVMU14mGKN8BRKdzAomiH915339Cc1LqUTzgcBfoKI0duAMjY7v33ejJ43Zxe7eMYNTFv999F6fqHjxFjg44zR_T3p92cUjPjL31yQVRCTViADATKM`

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by 491134648** [comment]
`public static void Start()
        {
            //设置全局 Debug 状态
            var isGLobalDebug = false;
            var a= Senparc.NeuChar.NeuCharActionType.GetConfig;
            //全局设置参数，将被储存到 Senparc.CO2NET.Config.SenparcSetting
            var senparcSetting = SenparcSetting.BuildFromWebConfig(isGLobalDebug);
            //CO2NET 全局注册，必须！！
            IRegisterService register = RegisterService.Start(senparcSetting).UseSenparcGlobal();
            #region 配置和使用 Redis

            //配置全局使用Redis缓存（按需，独立）
            var redisConfigurationStr = senparcSetting.Cache_Redis_Configuration;
            var useRedis = !string.IsNullOrEmpty(redisConfigurationStr) && redisConfigurationStr != "Redis配置";
            if (useRedis)//这里为了方便不同环境的开发者进行配置，做成了判断的方式，实际开发环境一般是确定的，这里的if条件可以忽略
            {
                /* 说明：
                 * 1、Redis 的连接字符串信息会从 Config.SenparcSetting.Cache_Redis_Configuration 自动获取并注册，如不需要修改，下方方法可以忽略
                /* 2、如需手动修改，可以通过下方 SetConfigurationOption 方法手动设置 Redis 链接信息（仅修改配置，不立即启用）
                 */
                Senparc.CO2NET.Cache.Redis.Register.SetConfigurationOption(redisConfigurationStr);
                
                //以下会立即将全局缓存设置为 Redis
                Senparc.CO2NET.Cache.Redis.Register.UseKeyValueRedisNow();//键值对缓存策略（推荐）
                //Senparc.CO2NET.Cache.Redis.Register.UseHashRedisNow();//HashSet储存格式的缓存策略

                //也可以通过以下方式自定义当前需要启用的缓存策略
                //CacheStrategyFactory.RegisterObjectCacheStrategy(() => RedisObjectCacheStrategy.Instance);//键值对
                //CacheStrategyFactory.RegisterObjectCacheStrategy(() => RedisHashSetObjectCacheStrategy.Instance);//HashSet
            }
            //如果这里不进行Redis缓存启用，则目前还是默认使用内存缓存 

            #endregion
            #region 注册微信
            //设置微信 Debug 状态
            var isWeixinDebug = true;
            //全局设置参数，将被储存到 Senparc.Weixin.Config.SenparcWeixinSetting
            var senparcWeixinSetting = SenparcWeixinSetting.BuildFromWebConfig(isWeixinDebug);
            //也可以通过这种方法在程序任意位置设置微信的 Debug 状态：
            //Senparc.Weixin.Config.IsDebug = isWeixinDebug;

            //微信全局注册，必须！！
            register.UseSenparcWeixin(senparcWeixinSetting, senparcSetting)

            #endregion
            #region 注册公众号或小程序（按需）

                //注册公众号（可注册多个）
                .RegisterMpAccount(senparcWeixinSetting, "【盛派网络小助手】公众号")

                //除此以外，仍然可以在程序任意地方注册公众号或小程序：
                //AccessTokenContainer.Register(appId, appSecret, name);//命名空间：Senparc.Weixin.MP.Containers
            #endregion
            #region 注册微信支付（按需）

                //注册最新微信支付版本（V3）（可注册多个）
                .RegisterTenpayV3(senparcWeixinSetting, "【盛派网络小助手】公众号");

            #endregion
        }`

**Comment by 491134648** [comment]
升级之后，按照demo文档写的
当前扩展缓存策略没有进行注册：Senparc.Weixin.Cache.ContainerCacheStrategyDomain，Senparc.CO2NET.Cache.Redis.RedisObjectCacheStrategy，解决方案请参考：https://weixin.senparc.com/QA-551

**Comment by 491134648** [comment]
必须把注册方法放在包含globax启动文件的库里，而放在业务层找不到缓存策略；

**Comment by 491134648** [comment]
同样的方法，都是再global中调用，不过一个现在service层，一个写在webapp中，webapp中没有问题

**Comment by JeffreySu** [comment]
通常service层应该晚于global的初始化代码被执行到吧？

**Comment by 491134648** [comment]
在start中执行业务层的依赖注入容器、以及其他初始化的操作
