### ISSUE TITLE
.net core 2.1 下 MessageHandler 构造函数报错

### ISSUE THREAD

**Issue by zhongzepeng** [JeffreySu/WeiXinMPSDK#1420]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述

The type initializer for 'Senparc.NeuChar.MessageHandlers.MessageHandler`3' threw an exception.   at Senparc.NeuChar.MessageHandlers.MessageHandler`3..ctor(Stream inputStream, I
nt32 maxRecordCount, Object postData)
         at Senparc.Weixin.MP.MessageHandlers.MessageHandler`1..ctor(Stream inputStream, PostModel postModel, Int32 maxRecordCount, DeveloperInfo developerInfo)
         at VipCloud.Web.Api.App_Code.TestHandler..ctor(Stream inputStream, PostModel postModel, Int32 maxRecordCount, DeveloperInfo developerInfo)

##### 重现问题步骤（如果可以）

1.             var memoryStream = new MemoryStream();
                Request.Body.CopyTo(memoryStream);
                var testHandler = new TestHandler(memoryStream);
                testHandler.Execute();

##### 发现问题的模块

- [ ] Senparc.Weixin.MP 版本：16.3.5.0

##### 模块对应的 .net 版本
- [x] .net core 2.x
##### 开发环境
- [x] Visual Studio 2017
##### 缓存环境
- [x] 服务器内存缓存（默认）
##### 联系方式
Email：244239581@qq.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
你的 TestHandler 的基类是什么？

**Comment by zhongzepeng** [comment]
@JeffreySu 
基类是：Senparc.Weixin.MP.MessageHandlers.MessageHandler<TC>


代码如下：
`public class TestHandler : MessageHandler<MessageContext<IRequestMessageBase, IResponseMessageBase>>
    {
        public TestHandler(Stream inputStream, PostModel postModel = null, int maxRecordCount = 0)
            : base(inputStream, postModel, maxRecordCount)
        {
        }

        public override IResponseMessageBase DefaultResponseMessage(IRequestMessageBase requestMessage)
        {
            throw new System.NotImplementedException();
        }
    }`

**Comment by John0King** [comment]
@zhongzepeng @JeffreySu  感觉这个问题是 `Request.Body.CopyTo(memoryStream)` ,  默认 asp.net core 的Request.Body 是只读的流， 不能 seek ， 如果要 seek 需要调用 Request.EnableReWind() ,  看这个
https://github.com/JeffreySu/WeiXinMPSDK/blob/master/src/Senparc.Weixin.MP.MvcExtension/Senparc.Weixin.MP.MvcExtension/Utilities/HttpUtility/EnableRequestRewind.cs

**Comment by JeffreySu** [comment]
有没有试过我们推荐的方法 `Request.GetRequestMemoryStream()`
https://github.com/JeffreySu/WeiXinMPSDK/blob/0ba94a73673341d83e53db7d369ac7cf5a654b01/Samples/Senparc.Weixin.MP.Sample.vs2017/Senparc.Weixin.MP.CoreSample/Controllers/WeixinController.cs#L86

**Comment by zhongzepeng** [comment]
@John0King  
        ```
   app.Use(async (ctx, next) =>
            {
                ctx.Request.EnableRewind();
                await next.Invoke();
            });
```

已经加了这个还是不行，Request.Body 是可以读出xml请求内容的，有没有好的调试办法

**Comment by JeffreySu** [comment]
我们自己的项目一直在用，从来没遇到你说的情况啊 ，EnableRewind()也是有在用的。不过不用应该也是可以的，这个更多解决的是反复读取的问题。

**Comment by zhongzepeng** [comment]
@JeffreySu 有没有好的办法定位下问题呢，这个项目是我们从.net framework 整体迁移到netcore 下面的，主要是报错信息太少，无从下手解决

**Comment by zhongzepeng** [comment]
@ @JeffreySu @John0King 麻烦你们了，看了下demo，还有
IRegisterService register = RegisterService.Start(env, senparcSetting.Value)
                                                        .UseSenparcGlobal(); 
这个配置没加上，加上已经不报这个错误了
