### ISSUE TITLE
异常找不到方法:“System.String Senparc.CO2NET.HttpUtility.RequestUtility.HttpPost

### ISSUE THREAD

**Issue by bluesky001** [JeffreySu/WeiXinMPSDK#1428]
微信支付时返回
异常找不到方法:“System.String Senparc.CO2NET.HttpUtility.RequestUtility.HttpPost(System.String, System.Net.CookieContainer, System.IO.Stream, System.Collections.Generic.Dictionary`2<System.String,System.String>, System.String, System.Text.Encoding, System.Security.Cryptography.X509Certificates.X509Certificate2, Boolean, Int32, Boolean)”

使用Senparc.Weixin.TenPay
使用Senparc.CO2NET
在方法TenPayV3.Unifiedorder(datainfo)时报错

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 发现问题的模块
- [x ] Senparc.CO2NET
- [x ] Senparc.Weixin.TenPay
- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [x] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [ ] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
查看一下你部署在服务器上的Senparc.Weixin.TenPay.dll和Senparc.CO2NET.dll的版本分别是多少（在属性里面看）

**Comment by bluesky001** [comment]
Senparc.Weixin.TenPay.dll：0.2.1.0
Senparc.CO2NET.dll：0.2.14.0

**Comment by JeffreySu** [comment]
应该是依赖的版本不正确，全部更新到最新的看一下。

**Comment by canknow** [comment]
我也是这个问题 全部更新到最新版本 就出现了。折磨了一个月还没好

**Comment by canknow** [comment]
ERROR 2018-10-07 12:50:30,751 [35   ] Mvc.ExceptionHandling.AbpExceptionFilter - Method not found: 'System.String Senparc.CO2NET.HttpUtility.RequestUtility.HttpPost(System.String, System.Net.CookieContainer, System.IO.Stream, System.Collections.Generic.Dictionary`2<System.String,System.String>, System.String, System.Text.Encoding, System.Security.Cryptography.X509Certificates.X509Certificate2, Boolean, Int32, Boolean)'.
System.MissingMethodException: Method not found: 'System.String Senparc.CO2NET.HttpUtility.RequestUtility.HttpPost(System.String, System.Net.CookieContainer, System.IO.Stream, System.Collections.Generic.Dictionary`2<System.String,System.String>, System.String, System.Text.Encoding, System.Security.Cryptography.X509Certificates.X509Certificate2, Boolean, Int32, Boolean)'.
   at Senparc.Weixin.TenPay.V3.TenPayV3.Unifiedorder(TenPayV3UnifiedorderRequestData dataInfo, Int32 timeOut)

**Comment by canknow** [comment]
![image](https://user-images.githubusercontent.com/14821704/46578335-3159a680-ca30-11e8-93e2-ba5cf9321300.png)

**Comment by JeffreySu** [comment]
@canknow @bluesky001  几分钟前Nuget又发布了一个新的版本，你们可以再试一下。
这类问题一般是依赖库的版本太低所致。比如MP是最新的，依赖Senparc.Weixin.dll是v2，但是实际运行的是v1。

**Comment by canknow** [comment]
全部都是最新的版本，发布出来的dll看了都是对的。还是报这个错误

**Comment by canknow** [comment]
应该是senparc.weixin.tenpay这个包发布的有问题。0.2.1这个版本。和senparac源码里面的类方法不完全一样

**Comment by JeffreySu** [comment]
@canknow  @bluesky001 抱歉，之前已经发布了nuget v1.0的版本，但是没注意到设置了Unlist了，外部不可见，已经开放出来，可以安装最新的试一下。
