### ISSUE TITLE
消息处理引入NeuChar后提示“CustomMessageContext”未包含“StorageData”的定义

### ISSUE THREAD

**Issue by lei467** [JeffreySu/WeiXinMPSDK#1440]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
最近升级senparc,发现消息处理移植到了NeuChar，调整引入文件后原程序报错：
“CustomMessageContext”未包含“StorageData”的定义，并且找不到可接受第一个“CustomMessageContext”类型参数的扩展方法“StorageData”(是否缺少 using 指令或程序集引用?)

##### 重现问题步骤（如果可以）

1. 最新下载的WeiXinMPSDK-master\Samples\Senparc.Weixin.MP.Sample.WebForms中仍有引用StorageData

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：v6.1.6.1
- [ ] Senparc.Weixin.MP 版本：v16.4.3.1
- [ ] Senparc.Weixin.Open 版本：v4.1.12.1

- [ ] 其他模块：
Senparc.NeuChar 版本v0.2.7.3

##### 模块对应的 .net 版本

- [ ] .net 4.5

##### 开发环境

- [x] Visual Studio 2017

##### 缓存环境

- [x] 服务器内存缓存（默认）

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
WebForms的还没有对应升级，谢谢提醒。

**Comment by JeffreySu** [comment]
已经更新，您看一下，之前Demo的问题是没有引用最新的库，您这个问题应该是dll没有全部更新到最新版本（或没有对应匹配）才会造成的。

**Comment by lei467** [comment]
非常感谢！
