### ISSUE TITLE
无法获取JsApiTicket

### ISSUE THREAD

**Issue by xuSs1994** [JeffreySu/WeiXinMPSDK#1447]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
使用JsApiTicketContainer.TryGetJsApiTicket(appID, appSecret);无法获取jsapi_tiket
看了下微信文档里面使用access_token去获取jsapi_tiket

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [x]Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [x] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
没错，JsApiTicketContainer.TryGetJsApiTicket 最终实现是用 AccessToken 的，封装起来是为了方便调用，并且自动使用缓存和自动重新获取的一整套机制。

接口本身是没问题的，无法获取你看一下详细的错误信息是什么？

**Comment by xuSs1994** [comment]
var result1 = JsApiTicketContainer.TryGetJsApiTicket(appID, appSecret); 返回的是null
var result2 = JsApiTicketContainer.GetJsApiTicket(appID); 返回的是null
var result3 = JsApiTicketContainer.GetJsApiTicketResult(appID);报错信息：{WxJsonResult：{errcode:'41001',errcode_name:'缺少access_token参数',errmsg:'access_token missing hint: [S3OOTA0739vr63!]'}}

**Comment by xuSs1994** [comment]
麻烦苏总了，没有设置白名单，好长时间没有做微信公众号，不好意思！感谢
