### ISSUE TITLE
电子发票报销方发票信息功能性严重错误

### ISSUE THREAD

**Issue by fdstar** [JeffreySu/WeiXinMPSDK#1449]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
目前报销方获取到的发票信息与微信官方平台不一致，目前报销方实际获取的是**发票供应商的发票参数信息**，报销方获取发票的途径是pdf_url，**目前导致发票无法获取对应pdf**，这个问题希望能尽快解决

##### 微信官方文档 URL
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=21517918939oae3U

##### 微信官方文档快照（直接复制关键内容到下方）
参数 | 类型 | 是否必填 | 描述
-- | -- | -- | --
fee | Int | 是 | 发票加税合计金额，以分为单位
title | String | 是 | 发票的抬头
billing_time | Int | 是 | 开票时间，为十位时间戳（utc+8）
billing_no | String | 是 | 发票代码
billing_code | String | 是 | 发票号码
info | List | 否 | 商品信息结构，见下方说明
fee_without_tax | Int | 是 | 不含税金额，以分为单位
tax | Int | 是 | 税额,以分为单位
pdf_url | String | 是 | 这张发票对应的PDF_URL
trip_pdf_url | String | 否 | 其它消费凭证附件对应的URL，如行程单、水单等
reimburse_status | String | 是 | 发票报销状态，见 备注7.4
check_code | String | 是 | 校验码（必填）
buyer_number | String | 否 | 购买方纳税人识别号（选填）
buyer_address_and_phone | String | 否 | 购买方地址、电话（选填）
buyer_bank_account | String | 否 | 购买方开户行及账号（选填）
seller_number | String | 否 | 销售方纳税人识别号（选填）
seller_address_and_phone | String | 否 | 销售方地址、电话（选填）
seller_bank_account | String | 否 | 销售方开户行及账号（选填）
remarks | String | 否 | 备注
cashier | String | 否 | 收款人，发票左下角处（选填）
maker | String | 否 | 开票人，发票有下角处（选填）

##### 发现问题的模块

- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：16.4.6.1

**Comment by JeffreySu** [comment]
@niktac
