### ISSUE TITLE
版本差异过大，跟进难度非常之高，有同感的给此bug火起来！！

### ISSUE THREAD

**Issue by dodu2014** [JeffreySu/WeiXinMPSDK#1457]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述

命名空间总是变来变去，每个版本差异太大。跟进太过费劲，我觉得这是最大的bug。

##### 重现问题步骤（如果可以）

1. 升级nuget包
2. 问题就出来了。

##### 发现问题的模块

- [x] Senparc.Weixin 版本：
- [x] Senparc.Weixin.MP 版本：
- [x] Senparc.Weixin.MP.MVC 版本：
- [x] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [x] Senparc.Weixin.Work 版本：
- [x] Senparc.Weixin.WxOpen 版本：
- [x] Senparc.Weixin.Cache.Redis 版本：
- [x] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [x] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by jerrytang67** [comment]
啥时候不变了我们做开发的也就没饭吃了

**Comment by JeffreySu** [comment]
@dodu2014  首先感谢您的支持和反馈，这说明我们的更新说明还做的不够好。

不过我并不认为每次新的版本差都异“过大”，除非是隔的版本太多，时间太长，我们所有的升级已经以向下兼容为重要指标，但版本一多，做出一些改动必然会发生的事情，所有软件都这样。另外每次命名空间的修改都是因为业务需要，都会反复推敲，更不会存在“变来变去”的情况，每次变更目的都是非常明确的。

自动找到适用的命名空间，把光标移到对应代码上，有一个快捷键：Alt+回车。希望可以回答你的疑惑。

目前这个 SDK 已经超过 80% 的 .NET 微信系统在用了。欢迎多提意见，我们希望有 hug，没 bug 🤗
