### ISSUE TITLE
ApiHandlerWapper 中的accessToken失效重试逻辑没起作用

### ISSUE THREAD

**Issue by cantain** [JeffreySu/WeiXinMPSDK#1461]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
Senparc.Weixin.CommonAPIs.ApiHandlerWapper.ApiHandlerWapper 中的accessToken失效重试逻辑没起作用

##### 重现问题步骤（如果可以）
原代码及修正意见如下
```
try
{
    if (accessToken == null)
    {
        var accessTokenResult = accessTokenContainer_GetAccessTokenResultFunc(appId, false); //AccessTokenContainer.GetAccessTokenResult(appId, false);
        accessToken = accessTokenResult.access_token;
    }
    result = fun(accessToken);
}
catch (ErrorJsonResultException ex)
{
    if (retryIfFaild
        && appId != null
        //&& ex.JsonResult.errcode == ReturnCode.获取access_token时AppSecret错误或者access_token无效)
        && (int)ex.JsonResult.errcode == invalidCredentialValue)
    {
        //尝试重新验证
        var accessTokenResult = accessTokenContainer_GetAccessTokenResultFunc(appId, true);//AccessTokenContainer.GetAccessTokenResult(appId, true);
        //强制获取并刷新最新的AccessToken
        accessToken = accessTokenResult.access_token;
        result = TryCommonApiBase(platformType,
                    accessTokenContainer_GetFirstOrDefaultAppIdFunc,
                    accessTokenContainer_CheckRegisteredFunc,
                    accessTokenContainer_GetAccessTokenResultFunc,
                    invalidCredentialValue,
                    fun, appId, false); // <--错误行，此处的appId应该改为accessToken
    }
    else
    {
        ex.AccessTokenOrAppId = accessTokenOrAppId;
        throw;
    }
}
catch (WeixinException ex)
{
    ex.AccessTokenOrAppId = accessTokenOrAppId;
    throw;
}
```

##### 发现问题的模块

- [x] Senparc.Weixin 版本：6.1.9
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [x] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

**Comment by JeffreySu** [comment]
这个是一直working的哇，你是具体改了哪里？

**Comment by cantain** [comment]
就是catch里的
``
        result = TryCommonApiBase(platformType,
                    accessTokenContainer_GetFirstOrDefaultAppIdFunc,
                    accessTokenContainer_CheckRegisteredFunc,
                    accessTokenContainer_GetAccessTokenResultFunc,
                    invalidCredentialValue,
                    fun, appId, false);`
```
改为
```
        result = TryCommonApiBase(platformType,
                    accessTokenContainer_GetFirstOrDefaultAppIdFunc,
                    accessTokenContainer_CheckRegisteredFunc,
                    accessTokenContainer_GetAccessTokenResultFunc,
                    invalidCredentialValue,
                    fun, accessToken, false);
```
要不重试都没使用新获取到的token

**Comment by JeffreySu** [comment]
这里输入appId是没问题的，因为重新注册调用的是 AccessTokenContainer.GetAccessTokenResult() 方法，返回结果之前缓存已经更新，通过AppId可以得到最新的AccessToken（除非你做了延迟的缓存更新），当然直接用 accessToken也是没问题的。
