### ISSUE TITLE
RegisterApiBind() 自动扫描程序集异常

### ISSUE THREAD

**Issue by archeraya** [JeffreySu/WeiXinMPSDK#1463]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
更新到最新版本sdk，发布到iis后，debug状态下发现SenparcTraceLog里有错误提示：
扩展缓存：Senparc.Weixin.Cache.LocalContainerCacheStrategy 

[[[RegisterApiBind() 自动扫描程序集异常：Senparc.Weixin.Cache.Memcached, Version=0.0.1.0, Culture=neutral, PublicKeyToken=null]]] 
[2018/10/24 16:04:37] 
[线程：51] 
   System.Reflection.ReflectionTypeLoadException: 无法加载一个或多个请求的类型。有关更多信息，请检索 LoaderExceptions 属性。 
  在 System.Reflection.RuntimeModule.GetTypes(RuntimeModule module) 
  在 System.Reflection.RuntimeModule.GetTypes() 
  在 System.Reflection.Assembly.GetTypes() 
  在 Senparc.NeuChar.Register.RegisterApiBind() 

[[[RegisterApiBind() 自动扫描程序集异常：Senparc.Weixin.MP, Version=16.4.9.0, Culture=neutral, PublicKeyToken=null]]] 
[2018/10/24 16:04:37] 
[线程：51] 
   System.ArgumentException: 已添加了具有相同键的项。 
  在 System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add) 
  在 Senparc.NeuChar.ApiBind.ApiBindInfoCollection.Add(MethodInfo method, ApiBindAttribute apiBindAttr) 
  在 Senparc.NeuChar.Register.RegisterApiBind()

1）nuget只安装了redis，但还没在global里配置，也没安装Memcached包；
2）weixincontroller和global已和当前demo同步；
3）更新以下版本之前只有第一个异常，更新到最新的后出现了第二个异常：
"Senparc.CO2NET" version="0.2.10"
"Senparc.NeuChar" version="0.1.4.1"
"Senparc.Weixin" version="6.1.2"
"Senparc.Weixin.MP" version="16.3.4"
"Senparc.Weixin.MP.MVC" version="7.1.5"
"Senparc.Weixin.Open" version="4.1.8"
"Senparc.Weixin.TenPay" version="0.2.1"

##### 重现问题步骤（如果可以）

编译期间没有错误，每次发布后查看日志就有。

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [x] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [x] .net 4.5.1
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [ ] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：
archeraya@163.com
（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
没关系的，可以忽略，这个异常只是做一个有重复键的提示，不会影响使用。

**Comment by archeraya** [comment]
1）那第一个异常呢？
2）这个重复键是我这项目里哪儿设置的问题吗？

**Comment by archeraya** [comment]
如果不影响正常功能就优先处理其他问题吧，这边知道无碍就行，感谢回复

**Comment by JeffreySu** [comment]
“无法加载一个或多个请求的类型”这个是不正常的，一直都有吗？
第二个重复键可以不用管。

**Comment by archeraya** [comment]
<package id="Senparc.CO2NET" version="0.2.8.2" targetFramework="net45" />
  <package id="Senparc.Weixin" version="5.1.8" targetFramework="net45" />
  <package id="Senparc.Weixin.MP" version="15.3.0" targetFramework="net45" />
  <package id="Senparc.Weixin.MP.MVC" version="6.0.10" targetFramework="net45" />
这个版本之前没这样，从这个版本开始关闭debug了，直到更新到最新的sdk后开启debug才发现这个问题，再就是也没引入Memcached这个包，没有有关这个的配置啊

**Comment by archeraya** [comment]
找到问题了：
以前可能是安过Memcached的包，在服务器上残留着dll，删掉就没这个错误了。
这个dll应该存在很久了，NeuChar.Register的RegisterApiBind里自动扫描程序集的部分可能还有改进的余地，或者是否有什么建议能避免类似的问题。
sdk用了有两年了，着实减少了不少负担，在此表示衷心的感谢

**Comment by JeffreySu** [comment]
这个提示在后面的版本会消除掉，我们会尽快推进，目前只会在启动的时候自检过程中提示（是比较健康的提示，并且不会影响效率）。

谢谢支持！也欢迎各类意见或建议！

**Comment by archeraya** [comment]
好 多谢！
