### ISSUE TITLE
上传素材文件提示 media data missing

### ISSUE THREAD

**Issue by JeffreySu** [JeffreySu/WeiXinMPSDK#1464]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
https://weixin.senparc.com/QA-571

##### 重现问题步骤（如果可以）

resultJson = MediaApi.UploadTemporaryMedia(accessToken, type, absolutePath, timeOut); 

入上面的代码所示，在.net 下面是正常上传的 ， .net core 下上传不了

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [x] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

**Comment by JeffreySu** [comment]
.net core 已经可用。最新版本测试。

**Comment by svinoce** [comment]
net6 samples.mp下调试 UploadTemporaryMedia errcode:'40005' 错误，永久素材上传也有同样问题
