### ISSUE TITLE
微信JSON的忽略null值测试

### ISSUE THREAD

**Issue by dxzcc** [JeffreySu/WeiXinMPSDK#148]
SerializerHelper这个测试有问题，最外层的是可以忽略掉null属性，内层就不行了，目前为了能够使用我替换成了json.net开源类库

**Comment by JeffreySu** [comment]
如果是嵌套多层的，可以让内层的类继承JsonIgnoreNull或者实现IJsonIgnoreNull即可。这些类也会被自动处理。谢谢！

**Comment by dxzcc** [comment]
如果是匿名类呢
