### ISSUE TITLE
Nuget Senparc.Weixin.TenPay1.0.2报错

### ISSUE THREAD

**Issue by itmpanda** [JeffreySu/WeiXinMPSDK#1484]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 
##### Senparc.Weixin.MP.Entities.Request.PostModel --- does not have an implementation 主要是这个问题吧 要怎么实现？

nuget Senparc.Weixin.TenPay 1.0.2后 运行就报如下错误：
##### 在Configure中已使用如下注册语句

`//开始注册微信信息，必须！
            register.UseSenparcWeixin(senparcWeixinSetting.Value, senparcSetting.Value)
                //注册最新微信支付版本（V3）（可注册多个）
                .RegisterTenpayV3(senparcWeixinSetting.Value, "senparc");`

[[[自动注册扩展缓存完成]]]
[2018/11/23 22:32:17.7090]
[线程：1]
注册总用时：0.001ms
自动扫描程序集：0个
扩展缓存：

[[[微信扩展缓存注册完成]]]
[2018/11/23 22:32:17.7428]
[线程：1]
微信扩展缓存注册总用时：0.0014ms
扩展缓存：Senparc.Weixin.Cache.LocalContainerCacheStrategy

[[[RegisterApiBind() 自动扫描程序集异常：Senparc.Weixin.MP, Version=16.4.12.1, Culture=neutral, PublicKeyToken=null]]]
[2018/11/23 22:32:18.4353]
[线程：1]
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Declaration referenced in a method implementation cannot be a final method.  Type: 'Senparc.Weixin.MP.MessageHandlers.MessageHandler`1'.  Assembly: 'Senparc.Weixin.MP, Version=16.4.12.1, Culture=neutral, PublicKeyToken=null'.
Method 'get_DomainId' in type 'Senparc.Weixin.MP.Entities.Request.PostModel' from assembly 'Senparc.Weixin.MP, Version=16.4.12.1, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Senparc.NeuChar.Register.RegisterApiBind()
System.TypeLoadException: Declaration referenced in a method implementation cannot be a final method.  Type: 'Senparc.Weixin.MP.MessageHandlers.MessageHandler`1'.  Assembly: 'Senparc.Weixin.MP, Version=16.4.12.1, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Method 'get_DomainId' in type '**Senparc.Weixin.MP.Entities.Request.PostModel**' from assembly 'Senparc.Weixin.MP, Version=16.4.12.1, Culture=neutral, PublicKeyToken=null' does not have an implementation.

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [x] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：wu1280@qq.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
1、如果你只升级了一个包，建议所有的包都升级一下。does not have an implementation 按理说都是dll不正确导致的。
2、对于日志里面的异常，忽略即可，这个只是常规的自动检查，一个提示而已，不会影响你的程序使用。

**Comment by itmpanda** [comment]
> 1、如果你只升级了一个包，建议所有的包都升级一下。does not have an implementation 按理说都是dll不正确导致的。
> 2、对于日志里面的异常，忽略即可，这个只是常规的自动检查，一个提示而已，不会影响你的程序使用。

谢谢，解决了，是需要升级所有包。谢谢
