### ISSUE TITLE
Senparc.Weixin.MP  版本 16.5.0

### ISSUE THREAD

**Issue by JHeLiu** [JeffreySu/WeiXinMPSDK#1486]
Senparc.Weixin.MP  版本 16.5.0

--Value cannot be null.

webapi中解析出错，之前的版本正常。升级后会报错 
--Value cannot be null.

` var inputStream = HttpContext.Current.Request.InputStream;
            var handler = new CustomMessageHandler(inputStream)
            {
                OmitRepeatedMessage = true
            };
            handler.Execute();`

**Comment by JHeLiu** [comment]
@JeffreySu  是的，我测试了一下，看了一下源代码，需要自己实例化。如果需要实例化应该是比传的参数。不知道这是不是一个小的BUG

**Comment by JeffreySu** [comment]
我们新的Demo已经都要求大家传入了，你有够跟踪到具体是哪一行抛出的异常吗？我们在基类里面应该也有对null的自动初始化判断。

**Comment by JHeLiu** [comment]
@JeffreySu 因为我用的是DLL 不是源代码，所以目前没办法跟踪到具体位置，就如我所说的 ，在我构造函数中 报 Value cannot be null. 错误。 而这个问题 就是你所说的 PostModel参数导致的，只要我手动实例化它，就能正常使用。

**Comment by JeffreySu** [comment]
我的意思是我们的基类里面应该已经有判断postModel是否为null，如果是null的话会自动加以处理，不知道为啥你那边还是会有错误。你构造函数里面有执行什么自定义的代码吗（Demo以外的）？

**Comment by JHeLiu** [comment]
构造函数中没有任何 自定义代码。 是直接继承过来的 
`
 public CustomMessageHandler(Stream inputStream, PostModel postModel = null)
            : base(inputStream, postModel)
        {

        }
`

**Comment by JeffreySu** [comment]
最新基类的构造函数里面是有判断的：
![image](https://user-images.githubusercontent.com/2281927/49122692-798a9c00-f2f0-11e8-9dc0-0a3ccffa367e.png)

**Comment by JHeLiu** [comment]
嗯，是的，。我也看了，是有判断。但是会报错。我只要手动实例化就可以正常使用。目前还具体不知道是什么问题

**Comment by JeffreySu** [comment]
是不是你的构造函数里运行了什么了？或者覆盖了什么？或者有dll不是最新的？
