### ISSUE TITLE
企业微信 中 MailListApi  UpdateDepartment  parentId不能为null，导致无法修改根组织机构

### ISSUE THREAD

**Issue by luoyunchong** [JeffreySu/WeiXinMPSDK#1489]
#### 问题1.
企业微信开发 中 MailListApi  UpdateDepartment  parentId不能为null，导致无法修改根组织机构

 MailListApi  UpdateDepartment方法parentId应该为 long? 
我用企业微信接口调试工具测试：

` {"name":"111","parentid":0,"order":2147483646,"id":1} `

此时报

` {"errcode":60124,"errmsg":"invalid parent party id, hint: [1543402950_5_eae015f6b1020084995459ed925233ae], more info at https://open.work.weixin.qq.com/devtool/query?e=60124"}`

```
错误说明:
无效的父部门id
排查方法:
父部门不存在通讯录中
```

当我用 此json数据时
` {"name":"111","parentid":null,"order":2147483646,"id":1} `

返回正常：
` {"errcode":0,"errmsg":"updated"}`

#### 问题2
通讯录管理->成员管理->创建成员的参数中新增了

参数|	必须|	说明
---|---|---|
alias | 否 | 成员别名。长度1~32个utf8

可查看此链接
### https://work.weixin.qq.com/api/doc#90000/90135/90195
 MailListApi.CreateMember方法的参数类MemberCreateRequest没有这个属性

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [x] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [x] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [ ] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：luoyunchong@foxmail.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by luoyunchong** [comment]
你好，在企业微信通讯录开发，通讯录回调->成员变更通知中的

IsLeader | 上级字段，标识是否为上级。0表示普通成员，1表示上级
-- | --

其中IsLeader 字段，L是大写。

RequestMessageEvent_Change_Contact_User_Update
#### 
https://github.com/JeffreySu/WeiXinMPSDK/blob/cc0e3cf404cc333c550f27e2010faa46341f3709/src/Senparc.Weixin.Work/Senparc.Weixin.Work/Entities/Request/Event/RequestMessageEvent_Change_Contact.cs

```
    /// <summary>
     /// 上级字段，标识是否为上级。第三方暂不支持
     /// </summary>
     public int Isleader { get; set; }

```
会导致OnEvent_ChangeContactUpdateUserRequest事件回调中，RequestMessageEvent_Change_Contact_User_Update参数据Isleader一直是0，无法得到1.我在本地修改代码，引用dll，可得到IsLeader的值。
@JeffreySu

**Comment by luoyunchong** [comment]
确实是大小写问题，我改成小写的Isleader后，无法获取到。

这是request过来的xml数据
```
<?xml version="1.0" encoding="utf-8"?>
<xml>
  <ToUserName><![CDATA[ww6b019c09102869b2]]></ToUserName>
  <FromUserName><![CDATA[sys]]></FromUserName>
  <CreateTime>1543484104</CreateTime>
  <MsgType><![CDATA[event]]></MsgType>
  <Event><![CDATA[change_contact]]></Event>
  <ChangeType><![CDATA[update_user]]></ChangeType>
  <UserID><![CDATA[admin1]]></UserID>
  <IsLeader>1</IsLeader>
</xml>
```
不清楚代码 是哪个部分将这个xml解析成类的，也许 你可以试一下。转成 RequestMessageEvent_Change_Contact_User_Update 类时，看Isleader字段的值。

**Comment by JeffreySu** [comment]
好的，已经放入修改计划，谢谢反馈！

**Comment by JeffreySu** [comment]
@luoyunchong  第一个parentId 需要为null的问题，文档里面是有说明：根部门的id为1，是不是这里输入1就能解决你的问题？

**Comment by luoyunchong** [comment]
@JeffreySu  {"name":"111","parentid":null,"order":2147483646,"id":1}  ,id是传1，但parentid要传null，你的那个参数不能为null，parentid改成long?，为null即可。如果 parentid传1，我记得之前会报一个错，类似id与parentid不能相同的提示。

**Comment by JeffreySu** [comment]
问题2 已修复，等待发布新版本 Work v3.3.7

**Comment by JeffreySu** [comment]
问题1 已修复。

**Comment by JeffreySu** [comment]
IsLeader 大小写问题已修复。
非常感谢！
