### ISSUE TITLE
改善建议

### ISSUE THREAD

**Issue by shuxinqin** [JeffreySu/WeiXinMPSDK#1496]
我们使用了贵公司提供的这个类库用于开发企业微信。项目在运行过程会报有关Task相关的错误。
我查看了HttpRequest相关的源码，https://github.com/Senparc/Senparc.CO2NET/blob/master/src/Senparc.CO2NET/Utilities/HttpUtility/RequestUtility.Get.cs#L144
发现这里同步方法调用了异步方法，最后使用了Task.Result这样的方式等待获取结果，这个使用方式是会不定时出现问题的（网上可以搜到），并且不止这一处，其他很多同步方法内部实现是这样。
我们项目里使用的是WeiXinMPSDK提供的同步方法（如OAuth2Api.GetUserId(accessToken, code)），所以会时不时报有关task的异常（One or more errors occurred. (A task was canceled.)
），目前我们的解决方案改调用WeiXinMPSDK提供的异步方法（await OAuth2Api.GetUserIdAsync(accessToken, code)）。
问题已经能够解决，但我们还是建议大神能对WeiXinMPSDK提供的同步方法进行一些优化，避免后面的开发者踩坑。

**Comment by JeffreySu** [comment]
感谢你的反馈，这边使用 .Result 是因为 httpClient 在 .net core 中只提供了.GetStringAsync() 这个异步方法，已经没有同步方法。
我会寻找另外的替代方案，也欢迎继续探讨你的想法。
另外我们也是建议大家在.net core里面尽量使用异步方法（尤其是这一类涉及到通讯、IO的）。

**Comment by JeffreySu** [comment]
@shuxinqin 相关异步方法最近一段时间已经做了一系列改进，非常感谢反馈，如果有任何问题可以随时交流。
