### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by tiger2014** [JeffreySu/WeiXinMPSDK#1498]
最新版的Senparc.Weixin.MP.Sample编译报错，master分支

1、解决方案右键-->重新生成解决方案
2、报错
![image](https://user-images.githubusercontent.com/6703612/49663263-0ff55500-fa89-11e8-9785-14d54d392f97.png)
![image](https://user-images.githubusercontent.com/6703612/49663288-24395200-fa89-11e8-976f-27a262b23ab4.png)

**Comment by JeffreySu** [comment]
.net 4.5的Sample先前没有更新最新的CO2NET，不知道你碰到的是不是这个问题造成的，现在已经把更新后的版本发布到了master，您可以再试一下。
目前我本地测试是正确的。如果有问题欢迎继续反馈。

**Comment by tiger2014** [comment]
更新后，.net 4.5的Sample 重新生成解决方案 还是报错：
![image](https://user-images.githubusercontent.com/6703612/49684410-8b4d1a00-fb0e-11e8-8216-75bd6e6e9a1a.png)
都是Senparc.Weixin.MP引起的：
![image](https://user-images.githubusercontent.com/6703612/49684435-e4b54900-fb0e-11e8-92b1-b550e670b980.png)

![image](https://user-images.githubusercontent.com/6703612/49684456-27772100-fb0f-11e8-8276-c585913879a8.png)

Senparc.Weixin.MP.Sample.vs2017就编译、调试正常
![image](https://user-images.githubusercontent.com/6703612/49684496-a2d8d280-fb0f-11e8-94ee-26a32b84ac61.png)

**Comment by chenjuanjane** [comment]
请问怎么解决的？我也遇到这个问题

**Comment by JeffreySu** [comment]
如果是VS2017以下，不支持部分新的语法，比如上面的PostModel：

``` C#
public override string DomainId { get => AppId; set => AppId = value; }
```

应该改写为：
``` C#
public override string DomainId { get => {return AppId;}; set {AppId = value;} }
```
