### ISSUE TITLE
Senparc.Weixin.Open.ComponentAPIs注册的bug

### ISSUE THREAD

**Issue by pcstx** [JeffreySu/WeiXinMPSDK#152]
公众平台开发在Global.asax中已经注册了  ComponentContainer.Register()方法。但是获取AuthorizerContainer.GetAllItems();发现access_token和refresh_token是空。其他信息倒是有的

**Comment by JeffreySu** [comment]
Authorizer必须要触发一次（没有命中），才会从远程或者数据库（需要你有对应的委托操作）获取参数，您看一下是不是这个问题？
