### ISSUE TITLE
群发消息的每行行末，都有一个回车符\r

### ISSUE THREAD

**Issue by wtujvk** [JeffreySu/WeiXinMPSDK#1548]
##### 问题描述
群发的文本换行是正常的，查看消息，文本有 \r
![image](https://user-images.githubusercontent.com/17868266/50578518-24552380-0e76-11e9-9d73-2cf3c0595832.png)

![image](https://user-images.githubusercontent.com/17868266/50578509-156e7100-0e76-11e9-9b6c-2c9d3296974c.png)

##### 重现问题步骤（如果可以）
1. 群发文本  (调用接口：  GroupMessageApi.SendGroupMessageByGroupId(accessToken, weixinFanGroupId, value, groupMessageType, toAll))
2. 查看公众号的全部消息
复制添加了 FixWeixinBugWeixinResult.cs
##### 微信官方文档 URL
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1481187827_i0l21
##### 微信官方文档快照（直接复制关键内容到下方）
![image](https://user-images.githubusercontent.com/17868266/50578587-e1478000-0e76-11e9-95f9-677ec15533ba.png)

##### 发现问题的模块

- [x] Senparc.Weixin 版本：4.20.2
- [x] Senparc.Weixin.MP 版本：14.10.3
##### 模块对应的 .net 版本
- [x] .net 4.5 (4.6)
##### 开发环境
- [x] Visual Studio 2017
- [x] 其他：win10
##### 缓存环境
- [x] 服务器内存缓存（默认）
##### 联系方式
Email：1170971516@qq.com

**Comment by JeffreySu** [comment]
高级接口和 FixWeixinBugWeixinResult 无关，看一下你文章内容设置的代码是怎么样的？

**Comment by wtujvk** [comment]
发送时手动替换消息内容： \r\n 为 \r
