### ISSUE TITLE
公众号获取模板id的方法

### ISSUE THREAD

**Issue by zariczhu** [JeffreySu/WeiXinMPSDK#155]
我们第三方平台想代替公众号发模板消息，不同的公众号相同的模板内容，但是模板id不一样，所以能不能提供这样的方法获取模板id，谢谢

**Comment by JeffreySu** [comment]
每个公众号，即使相同的模板，获取的模板ID都是不一样的。
如果接口里面没有提供，这个是获取不到的，你只能申请下来之后，记录到你的第三方平台数据库里面。
如果已经有这样的API了，欢迎给我们看一下文档（目前我还没发现有）。
谢谢！

**Comment by zariczhu** [comment]
谢谢回复
