### ISSUE TITLE
暂定BUG 特性 标签获取Openid,都租户的时候APPID只可以赋值一次

### ISSUE THREAD

**Issue by aitongsm** [JeffreySu/WeiXinMPSDK#1550]
##### 问题描述
多租户使用特性标签获取Openid,特性标签Appid第一次赋值后，其他租户再次使用无法再次赋值

##### 重现问题步骤（如果可以）

1. 在特性标签内内打印日志查询当前会话的租户APPID
2. 结果跳转的时候仍然为错误的Appid

##### 发现问题的模块

- [ ] Senparc.Weixin.MP 版本：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [x] .net core 2.x

##### 开发环境

- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）

##### 联系方式
Email：32599135@qq.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
@aitongsm 请查看上面最后三个提交的演示，不是SDK的问题，你可以在 CustomOAuthAttribute 中做任意的处理。

.NET 4.5：

https://github.com/JeffreySu/WeiXinMPSDK/blob/896c92c0defea698c058987bc948b6e9734b44d0/Samples/Senparc.Weixin.MP.Sample/Senparc.Weixin.MP.Sample/Filters/CustomOAuthAttribute.cs#L21

.NET Core：

https://github.com/JeffreySu/WeiXinMPSDK/blob/0fb86e505ddeabf4964ee4f087a8bf9b3575191a/Samples/Senparc.Weixin.MP.Sample.vs2017/Senparc.Weixin.MP.CoreSample/Filters/CustomOAuthAttribute.cs#L25

**Comment by aitongsm** [comment]
好的感谢老大问题解决
