### ISSUE TITLE
创建会员卡时CodeType属性序列化错误

### ISSUE THREAD

**Issue by LGinC** [JeffreySu/WeiXinMPSDK#1556]
##### 问题描述
创建会员卡 显示码类型字段base_info中code_type枚举应该序列化为字符串而不是数字类型

##### 重现问题步骤（如果可以）
日志如下：
[[[接口调用]]]
[2019/01/03 17:11:39.1131]
[线程：70]
	URL：https://api.weixin.qq.com/card/create?access_token=17_4hsDxGr0qIWuPbjkgUtobWiR5eApcv2zGGzdB6AkHV_Q9w3N1Qqkj6LeDiZP3CV8EyMQpLmJbE59IwVsG0e3fSPIMhzJu8Qa0y6nMoO1k10oW-vU02Ar33kCdrn4xfRyJNVggtAnZkZYM73fFPZeAEATDN
	Post Data：
{"card":{"member_card":{"auto_activate":true,"balance_rules":"","prerogative":"123","bonus_rule":{},"base_info":{"logo_url":"",**"code_type":1**,"brand_name":"baiyun","title":"VIP","color":"Color040","notice":"123","description":"123","use_limit":0,"get_limit":0,"use_custom_code":false,"bind_openid":false,"can_share":false,"can_give_friend":false,"date_info":{"type":"1","begin_timestamp":0,"end_timestamp":0,"fixed_term":0,"fixed_begin_term":0},"sku":{"quantity":100000000,"total_quantity":0},"url_name_type":0,"use_all_locations":false,"need_push_on_view":false}},"card_type":"MEMBER_CARD"}}

其中code_type:1
##### 微信官方文档 URL
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1451025283

##### 微信官方文档快照（直接复制关键内容到下方）

![image](https://user-images.githubusercontent.com/15363011/50630314-543a1f00-0f7b-11e9-86e4-63781fffe243.png)

code_type | 是 | string(16) | Code展示类型， "CODE_TYPE_TEXT" 文本 "CODE_TYPE_BARCODE" 一维码 "CODE_TYPE_QRCODE" 二维码 "CODE_TYPE_ONLY_QRCODE" 仅显示二维码 "CODE_TYPE_ONLY_BARCODE" 仅显示一维码 "CODE_TYPE_NONE" 不显示任何码型
-- | -- | -- | --

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [x] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [x] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [ ] 服务器内存缓存（默认）
- [x] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：
liguo1976@outlook.com

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
已修复并发布：https://www.nuget.org/packages/Senparc.Weixin.MP/16.6.4，感谢 😄
