### ISSUE TITLE
升级到preview2版本后生成二维码问题

### ISSUE THREAD

**Issue by lb0726** [JeffreySu/WeiXinMPSDK#1557]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
12.29号升级到preview2的版本后生成小程序码出现问题，报如下错误：
Could not convert string to DateTimeOffset: 0001-01-01T00:00:00. Path 'AccessTokenExpireTime', line 1, position 122.

调用SDK代码：
 result = Senparc.Weixin.WxOpen.AdvancedAPIs.WxApp.WxAppApi.
                                GetWxaCodeUnlimit(AppId, ms, scene, wxPath, width, auto_color, lineColor);

我用的缓存为redis，经过苏总指导在群指导后，清除redis缓存，问题还是依旧。
今天2019.1.3发现又有新的preview2的版本号。也更新到最新版本。问题还是依旧

但是有个现象。这个问题是站点运行一段时间之后发生，具体时间也无法确定，发生问题之后一直会持续。所以也无法去跟踪，但是从报错的说明来看，应该是转换日期的时候发生了错误。具体不得而知。

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [x] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [x] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [ ] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [] 服务器内存缓存（默认）
- [x] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：58690327@qq.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
SDK每次请求的格式都是固定的，如果是一段时间之后才出现问题，最好检查一下你系统里面有没有其他的干扰因素，比如多个系统同时在使用缓存，导致数据格式不一致等问题。

**Comment by JeffreySu** [comment]
另外除了这个接口以外，你同事测试一下其他小程序的接口，是否也同时有问题？

**Comment by lb0726** [comment]
> SDK每次请求的格式都是固定的，如果是一段时间之后才出现问题，最好检查一下你系统里面有没有其他的干扰因素，比如多个系统同时在使用缓存，导致数据格式不一致等问题。

我们两个站点用了SDK，都用的Redis缓存，是同一个Redis数据库，但是缓存通过命名空间分开的。我在数据库里面也确认过。

**Comment by JeffreySu** [comment]
那两个站点都是同样最新的dll吗？

**Comment by lb0726** [comment]
> 另外除了这个接口以外，你同事测试一下其他小程序的接口，是否也同时有问题？

暂时还没有发现其它接口有问题，上一次也是客服消息哪里有问题。这个preview2版本更新后就正常了。
支付也正常。

**Comment by lb0726** [comment]
> 那两个站点都是同样最新的dll吗？

确认了几遍是一样的版本，刚才确定一遍有一个站点下面没有 Senparc.Weixin.Cache.Redis.RedLock.dll，以前也没有。会不会有影响？我现在把它给不上了。

**Comment by JeffreySu** [comment]
Senparc.Weixin.Cache.Redis.RedLock.dll 按理说应该都有的

**Comment by lb0726** [comment]
> Senparc.Weixin.Cache.Redis.RedLock.dll 按理说应该都有的

加入之后还是出现问题。具体还找不到原因，暂时还原版本试试。

**Comment by JeffreySu** [comment]
这个应该是有问题的，如果你确实在用Redis的话，Senparc.Weixin.Cache.Redis.RedLock.dll应该是必须的。

**Comment by JeffreySu** [comment]
@lb0726 你说的这个问题新版本还存在吗？

**Comment by lb0726** [comment]
@JeffreySu 最近有调整这里的代码吗？最近要放假了。没敢去更新框架，怕影响稳定性。准备节后过来更新。
