### ISSUE TITLE
下载微信菜单返回null，抛异常

### ISSUE THREAD

**Issue by wtujvk** [JeffreySu/WeiXinMPSDK#1567]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
公众号没有设置菜单的时候，下载菜单报错。
调用接口： CommonApi.GetMenu
获取当前菜单，如果菜单不存在，将返回null。
没有菜单， 为什么会抛异常呢？查询返回null不太好，无法区分到底是没有菜单还是 查询出错

##### 重现问题步骤（如果可以）
1. 接入新的公众号 （没有设置菜单）
2. 调用接口 CommonApi.GetMenu
##### 微信官方文档 URL
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1434698695
##### 微信官方文档快照（直接复制关键内容到下方）
![image](https://user-images.githubusercontent.com/17868266/50761040-55818980-12a4-11e9-9479-7812ae376544.png)
##### 发现问题的模块
- [x] Senparc.Weixin 版本：4.20.2.0
- [x] Senparc.Weixin.MP 版本：14.10.3.0
##### 模块对应的 .net 版本
- [x] .net 4.5 (.net 4.6)
##### 开发环境
- [x] Visual Studio 2017
- [x] 其他：win10
##### 缓存环境
- [x] 服务器内存缓存（默认）
##### 联系方式
Email：1170971516@qq.com
（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
没有菜单(no menu)是官方制定的异常，所有的异常，高级接口都会抛出，这个是合理的做法，不然出错了你都不知道，或者仍然要写if语句判断，不如你直接在try里面做掉。

**Comment by wtujvk** [comment]
直接判断根据返回 信息 判断message： menu no exist 然后做相应的处理。

**Comment by JeffreySu** [comment]
对，这个统一都是异常，直接判断枚举即可。
