### ISSUE TITLE
用nuget安装到.NET 4.0项目中报错

### ISSUE THREAD

**Issue by hezhiqiang** [JeffreySu/WeiXinMPSDK#1570]
Install-Package : “Newtonsoft.Json”已拥有为“Microsoft.CSharp”定义的依赖项。

**Comment by JeffreySu** [comment]
出现这样的问题，检查几个地方：
1、用的VS版本是不是比较旧（或者没有装补丁），推荐 VS2017，最好 VS2015 以上
2、是不是有其他的库强制依赖了 Newtonsoft.Json 或 Microsoft.CSharp 的版本

处理的方式通常为：
1、升级 VS
2、卸载依赖了以上两项的库，然后安装 SDK，再把原来卸载的安装上去（如果还缺少的话）
