### ISSUE TITLE
CreateQR方法忽略ignore属性失败

### ISSUE THREAD

**Issue by codekgithub** [JeffreySu/WeiXinMPSDK#158]
CardApi.cs文件中的CreateQR方法在忽略null的属性时失效  
              var data = new
                {
                    action_name = "QR_CARD",
                    action_info = new
                    {
                        card = new
                        {
                            card_id = cardId,
                            code = code,
                            openid = openId,
                            expire_seconds = expireSeconds,
                            is_unique_code = false,
                            balance = balance
                        }
                    }
                };

**Comment by JeffreySu** [comment]
“失效”具体是指什么？
