### ISSUE TITLE
RequestMessageEvent_User_RequestM缺少UnionId字段

### ISSUE THREAD

**Issue by LGinC** [JeffreySu/WeiXinMPSDK#1580]
##### 问题描述
RequestMessageEvent_User_RequestM缺少UnionId字段
##### 微信官方文档 URL
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1451025274

##### 微信官方文档快照（直接复制关键内容到下方）
用户在领取卡券时，微信会把这个事件推送到开发者填写的URL。 推送XML数据包示例：

```
<xml>
   <ToUserName> <![CDATA[gh_fc0a06a20993]]> </ToUserName>
    <FromUserName> <![CDATA[oZI8Fj040-be6rlDohc6gkoPOQTQ]]> </FromUserName>
    <CreateTime>1472551036</CreateTime>
    <MsgType> <![CDATA[event]]> </MsgType>
    <Event> <![CDATA[user_get_card]]> </Event>
    <CardId> <![CDATA[pZI8Fjwsy5fVPRBeD78J4RmqVvBc]]> </CardId>
    <IsGiveByFriend>0</IsGiveByFriend>
    <UserCardCode> <![CDATA[226009850808]]> </UserCardCode>
    <FriendUserName> <![CDATA[]]> </FriendUserName>
    <OuterId>0</OuterId>
    <OldUserCardCode> <![CDATA[]]> </OldUserCardCode>
    <OuterStr> <![CDATA[12b]]> </OuterStr>
    <IsRestoreMemberCard>0</IsRestoreMemberCard>
    <IsRecommendByFriend>0</IsRecommendByFriend>
    <UnionId>o6_bmasdasdsad6_2sgVt7hMZOPfL</UnionId>
</xml>
```

参数 | 说明
-- | --
ToUserName | 开发者微信号。
FromUserName | 领券方帐号（一个OpenID）。
CreateTime | 消息创建时间 （整型）。
MsgType | 消息类型，event
Event | 事件类型，user_get_card(用户领取卡券)。
CardId | 卡券ID。
IsGiveByFriend | 是否为转赠领取，1代表是，0代表否。
FriendUserName | 当IsGiveByFriend为1时填入的字段，表示发起转赠用户的openid
UserCardCode | code序列号。
OldUserCardCode | 为保证安全，微信会在转赠发生后变更该卡券的code号，该字段表示转赠前的code。
OuterStr | 领取场景值，用于领取渠道数据统计。可在生成二维码接口及添加Addcard接口中自定义该字段的字符串值。
IsRestoreMemberCard | 用户删除会员卡后可重新找回，当用户本次操作为找回时，该值为1，否则为0
UnionId | 领券用户的UnionId

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [x] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [x] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：
liguo1976@outlook.com

**Comment by JeffreySu** [comment]
是这个类吗？

https://github.com/JeffreySu/WeiXinMPSDK/blob/bbdaa416dd67e2fa371a88783660cef2432235d4/src/Senparc.Weixin.MP/Senparc.Weixin.MP/Entities/Request/Event/RequestMessageEvent_User_Get_Card.cs#L42

**Comment by JeffreySu** [comment]
nuget已发布。
