### ISSUE TITLE
TemplateApi.SendTemplateMessage 在 accesstoken过期时后并不能自动重新获取新的 accesstoken

### ISSUE THREAD

**Issue by coolincy** [JeffreySu/WeiXinMPSDK#1595]
TemplateApi.SendTemplateMessage 在 accesstoken过期时后并不能自动重新获取新的 accesstoken

1. 程序启动，TemplateApi.SendTemplateMessage 发送模板消息，在Redis缓存中保存了刚刚获取的accesstoken
2. 直接修改Redis中的缓存数据，使得accesstoken无效
3. 再发送模板消息，报告 “获取access_token时AppSecret错误或者access_token无效”，按ApiHandlerWapper.TryCommonApi设计逻辑，这时候应该去重新获取accesstoken并重新执行发送操作，然而并没有。
![senparc](https://user-images.githubusercontent.com/354674/51679528-24ca7f80-201a-11e9-8913-874c9a3a70ab.png)

经查看源码：TryCommonApiBase使用异常捕捉来监视 “获取access_token时AppSecret错误或者access_token无效”错误，但发送模板消息并不引发异常，导致 catch (ErrorJsonResultException ex) 里的代码无用，因此并不会去重新获取accesstoken并重新执行发送操作。

**Comment by JeffreySu** [comment]
测试了，确实可以重现，但是即使给了错误的 AccessToken 似乎并没有在日志里得到结果，说明是中间有其他错误发生了，比如查看一下您是否像 Sample 中一样，在异常日志中也包含了发送模板消息的代码（虽然目前尚不确定是否是其中引起）？先排除一些可能性。

https://github.com/JeffreySu/WeiXinMPSDK/blob/23f9199d27963c963f63103a4ba30e781ebd258b/Samples/Senparc.Weixin.MP.Sample/Senparc.Weixin.MP.Sample.CommonService/EventService.cs#L105

**Comment by JeffreySu** [comment]
非常感谢反馈！查看了一下原因，是因为抽象到 CO2NET 之后，Get.GetJson<T> 方法已经不再抛出异常（因为需要兼容其他的可能性）。

以下是有效的代码：

https://github.com/JeffreySu/WeiXinMPSDK/blob/BookVersion1/src/Senparc.Weixin/Senparc.Weixin/Utilities/HttpUtility/Get.cs#L72

此代码目前已经被抽象到 CO2NET 并不再抛出异常。

此问题我们会尽快修复，谢谢！

**Comment by JeffreySu** [comment]
最新进展：同步方法已经完成自动重新获取AccessToken功能，异步方法还有问题，正在处理。

**Comment by JeffreySu** [comment]
已发布最新稳定版，感谢！
