### ISSUE TITLE
DeleteSendMessage 的接口是错误的

### ISSUE THREAD

**Issue by zhulj** [JeffreySu/WeiXinMPSDK#160]
WeiXinMPSDK/Senparc.Weixin.MP/Senparc.Weixin.MP/AdvancedAPIs/GroupMessage/GroupMessageAPI.cs

DeleteSendMessage 的接口是错误的：

var data = new
                {
                    msgid = msgId
                };

应该用:
var data = new
                {
                    msg_id = msgId
                };

**Comment by TYSZCC** [comment]
感谢您的反馈，已经修改！
