### ISSUE TITLE
使用SnsApi.JsCode2JsonAsync 方法获取OpenId时候偶尔会很慢

### ISSUE THREAD

**Issue by DekeYan** [JeffreySu/WeiXinMPSDK#1601]
使用SnsApi.JsCode2JsonAsync 方法获取OpenId时候偶尔会很慢

使用SnsApi.JsCode2JsonAsync 方法获取OpenId时候偶尔会很慢 正常的时候一般是几百毫秒，偶尔会两三万毫秒，这个产生的可能原因是什么？或者我能通过什么方法来排查问题吗？
计时器是在调用这个方法前后来计时的，应该跟原来程序没关系，不知道是不是配置问题。

- [ ] Senparc.Weixin.WxOpen 版本：3.2.2.1
- [ ] Senparc.Weixin.Cache.Redis 版本：2.3.1.1

- [x] .net core 2.x

##### 开发环境
- [x] Visual Studio 2017

##### 缓存环境
- [ ] Redis 版本：4.0.1

##### 联系方式
Email：rstar@idea-reach.com

**Comment by JeffreySu** [comment]
目前我们这边demo的测试还没发现这个问题，只有这一个接口是这样吗？其他接口呢？另外你的测试条件和环境是怎么样的？

**Comment by DekeYan** [comment]
> 目前我们这边demo的测试还没发现这个问题，只有这一个接口是这样吗？其他接口呢？另外你的测试条件和环境是怎么样的？

测试环境是放在docker中的 ，这两天我把你们的包升级到最新了，好像就没出现问题了 。我在继续观察下把，另外你们包的log在调用微信的接口的时候能记录执行的时间吗？

**Comment by JeffreySu** [comment]
可以的，都有时间，还有线程Id（为了方便跟踪是否在同一个请求内发生）。
