### ISSUE TITLE
ShakeAroundApi中有些错误和缺少接口

### ISSUE THREAD

**Issue by coolboy0821** [JeffreySu/WeiXinMPSDK#161]
错误：SearchPagesByPageId，SearchPagesByRange接口的返回值类型应为SearchPagesResultJson。

缺少：ShakeAroundApi中缺少查询设备与页面的关联关系的接口。接口文档如下 http://mp.weixin.qq.com/wiki/6/0eb3f80f152d2edb95287141e7a6ab5e.html。
微信接口地址：
https://api.weixin.qq.com/shakearound/relation/search?access_token=ACCESS_TOKEN

**Comment by TYSZCC** [comment]
感谢您的反馈，已经处理完毕！
