### ISSUE TITLE
Senparc.Weixin.MP 从 16.6.9 升级到 16.6.11后，发送模板消息不返回错误码，直接throw ex

### ISSUE THREAD

**Issue by coolincy** [JeffreySu/WeiXinMPSDK#1611]
Senparc.Weixin.MP 从 16.6.9 升级到 16.6.11

TemplateApi.SendTemplateMessage 发送模板消息给未关注的用户，直接报Exception
   微信 POST 请求发生错误！错误代码：43004，说明：require subscribe hint: [x.oNUa06394121]

以前是返回错误码：需要接收者关注

这个是否哪里处理逻辑调整时候遗漏了？

**Comment by JeffreySu** [comment]
未关注的用户本来就是瘦不到模板消息的，是会有这个错误。

**Comment by JeffreySu** [comment]
之前有一小段时间不抛出异常（其实是存在不成功的代码回复的），反而是不正确的，现在抛出异常是正确的，你可以在外层通过try捕获到。

**Comment by coolincy** [comment]
以前是返回错误码枚举值："ReturnCode.需要接收者关注"，程序只要判断这个返回码就可以知道是用户没有关注公众号，现在抛个异常出来，还要去解析Exception.Message里面的文本？？

**Comment by JeffreySu** [comment]
不需要，你只需要catch住这个异常（ [ErrorJsonResultException](https://github.com/JeffreySu/WeiXinMPSDK/blob/9b73e4cf8407a36f63b594a50ea237b971d257c5/src/Senparc.Weixin/Senparc.Weixin/Exceptions/ErrorJsonResultException.cs#L47)），参数里面有 JsonResult 详细信息。
