### ISSUE TITLE
Senparc.Weixin.Open中的小程序类目设置，获取账号可以设置的所有类目出现报错

### ISSUE THREAD

**Issue by CharlinQiu** [JeffreySu/WeiXinMPSDK#1612]
Senparc.Weixin.Open中实现下面的微信开放平台文档接口时报错：

> 8 类目相关接口
> 注：该章节接口需要使用1.3环节获取到的新创建小程序appid及authorization_code换取authorizer_refresh_token进而得到authorizer_access_token。
> 
> 8.1 获取账号可以设置的所有类目
> 请求方式：
> 
> GET数据
> URL：https://api.weixin.qq.com/cgi-bin/wxopen/getallcategories?access_token=TOKEN

经过调试，原因是CategoryListJsonResult跟微信返回的JSON数据格式对不上，报如下错误：

{"messages":"Cannot deserialize the current JSON object (e.g. {\"name\":\"value\"}) into type 'System.Collections.Generic.IList`1[Senparc.Weixin.Open.WxOpenAPIs.CategoryListJson.Category]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.\r\nTo fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.\r\nPath 'categories_list.categories', line 1, position 59.\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 501\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 1032\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 2386\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 485\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 167\r\n   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) in /_/Src/Newtonsoft.Json/JsonSerializer.cs:line 907\r\n   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings) in /_/Src/Newtonsoft.Json/JsonConvert.cs:line 828\r\n   at Senparc.CO2NET.Helpers.SerializerHelper.GetObject[T](String jsonString)\r\n   at Senparc.CO2NET.HttpUtility.Get.GetJsonAsync[T](String url, Encoding encoding, Action`2 afterReturnText)\r\n   at Senparc.Weixin.CommonAPIs.CommonJsonSend.SendAsync[T](String accessToken, String urlFormat, Object data, CommonJsonSendType sendType, Int32 timeOut, Boolean checkValidationResult, JsonSetting jsonSetting) in C:\\Users\\Able\\Documents\\Projects\\Open\\src\\Senparc.Weixin\\Senparc.Weixin\\CommonAPIs\\CommonJsonSend.cs:line 215\r\n   at Senparc.Weixin.Open.WxOpenAPIs.WxOpenApi.GetAllCategoriesAsync(String accessToken) in C:\\Users\\Able\\Documents\\Projects\\Open\\src\\Senparc.Weixin.Open\\Senparc.Weixin.Open\\WxOpenAPIs\\WxOpenApi.cs:line 152\r\n   at API.Services.WxaService.GetAllCategories(Int32 authorizerId) in C:\\Users\\Able\\Documents\\Projects\\Open\\maxshineopen.api\\API\\Services\\WxaService.cs:line 697\r\n   at API.Controllers.WxaController.GetAllCategoriesFromWeixin(Int32 authorizerId) in C:\\Users\\Able\\Documents\\Projects\\Open\\maxshineopen.api\\API\\Controllers\\WxaController.cs:line 423\r\n   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at System.Threading.Tasks.ValueTask`1.get_Result()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()\r\n   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)\r\n   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)\r\n   at BaseApi.Middlewares.ErrorHandleMiddleware.Invoke(HttpContext context)"}

**Comment by JeffreySu** [comment]
已发布 https://www.nuget.org/packages/Senparc.Weixin.Open/4.4.3.2

感谢！
