### ISSUE TITLE
Senparc.Weixin.Open中的获取小程序基本信息，返回报错

### ISSUE THREAD

**Issue by CharlinQiu** [JeffreySu/WeiXinMPSDK#1613]
Senparc.Weixin.Open中的获取小程序基本信息，实现下面的微信开放平台接口：

> 1 获取帐号基本信息
> 请求方式：
> 
> GET
> URL：https://api.weixin.qq.com/cgi-bin/account/getaccountbasicinfo?access_token=TOKEN

报错了。

原因是下面这三个微信返回的数据已经从int变成了bool：
 /// <summary>
        /// 是否资质认证 （1：是，0：否）若是，拥有微信认证相关的权限。
        /// </summary>
        public **bool** qualification_verify { get; set; }
        /// <summary>
        /// 是否名称认证 （1：是，0：否） 对于公众号（订阅号、服务号），是名称认证，微信客户端才会有微信认证打勾的标识
        /// </summary>
        public **bool** naming_verify { get; set; }
        /// <summary>
        /// 是否需要年审 （1：是，0：否）（qualification_verify = true时才有该字段）
        /// </summary>
        public **bool** annual_review { get; set; }

**Comment by JeffreySu** [comment]
已发布 https://www.nuget.org/packages/Senparc.Weixin.Open/4.4.3.2
