### ISSUE TITLE
开发OrchardCore的微信模块，整合WeiXinMPSDK如何写Startup.cs

### ISSUE THREAD

**Issue by chinasqzl** [JeffreySu/WeiXinMPSDK#1626]
OrchardCore的模块模类如下：
namespace OrchardCore.Modules {
	public abstract class StartupBase : IStartup {
		protected StartupBase();

		public virtual int Order { get; }

		public virtual void Configure(IApplicationBuilder app, IRouteBuilder routes, IServiceProvider serviceProvider);
		public virtual void ConfigureServices(IServiceCollection services);
	}
}

而WeiXinMPSDK需要一通操作，如何实现？（配置不写appsetting.json而是存表）：
public void ConfigureServices(IServiceCollection services)
        {
            //...
            services.AddSenparcGlobalServices(Configuration)//Senparc.CO2NET 全局注册
                    .AddSenparcWeixinServices(Configuration);//Senparc.Weixin 注册
        }

public void Configure(IApplicationBuilder app, IHostingEnvironment env, IOptions<SenparcSetting> senparcSetting, IOptions<SenparcWeixinSetting> senparcWeixinSetting)
        {
            //app.UseMvc()等设置...

            // 启动 CO2NET 全局注册，必须！
            IRegisterService register = RegisterService.Start(env, senparcSetting.Value)
                                                        .UseSenparcGlobal(false, null);

            //开始注册微信信息，必须！
            register.UseSenparcWeixin(senparcWeixinSetting.Value, senparcSetting.Value)
        }

**Comment by JeffreySu** [comment]
存表的话，你可以直接初始化对象：

``` C#
var senparcSetting = new SenparcSetting(){ ... };
var senparcWeixinSetting = new SenparcWeixinSetting(){ ... };
```

其他的 Configure 和 ConfigureServices 里面的过程是一致的，env 参数如果没有可以不提供，有对应的重写方法。

**Comment by chinasqzl** [comment]
https://github.com/JeffreySu/WeiXinMPSDK/issues/1420
.net core 2.1 下 MessageHandler 构造函数报错 #1420
我是遇到与他同样的问题，必须要加如下代码，现在MessageHandler构造报错。

>>
@ @JeffreySu @John0King 麻烦你们了，看了下demo，还有
IRegisterService register = RegisterService.Start(env, senparcSetting.Value)
.UseSenparcGlobal();
这个配置没加上，加上已经不报这个错误了

**Comment by JeffreySu** [comment]
上述两行代码是必须要加的，是加上去了还有问题吗？

**Comment by chinasqzl** [comment]
是没有地方加，
IRegisterService register = RegisterService.Start(env, senparcSetting.Value)
.UseSenparcGlobal(); 要加在Configure中，但OC的模块Configure带不出senparcSetting，

var senparcSetting = new SenparcSetting(){ ... };
var senparcWeixinSetting = new SenparcWeixinSetting(){ ... };

这样的形式在Configure中使用怪怪的，我正在系统的看NetCore的Startup.cs，再研究研究吧，谢谢。

**Comment by JeffreySu** [comment]
因为总得有个地方需要初始化new个对象出来，我不知道你是通过什么方式储存的，复杂一点的做法的话，这两个类你可以做成数据库对应的Entity，直接从表里面读出来。无非就是直接操作或者写一个Helper或者Extension扩展或注入。

**Comment by chinasqzl** [comment]
已解决，让后来人少走弯路，附核心代码：



		public override void Configure(IApplicationBuilder app, IRouteBuilder routes, IServiceProvider serviceProvider) {
			async Task<WechatSigninSettings> GetServerSettingsAsync() {
				var service = serviceProvider.GetService<ISiteService>().GetSiteSettingsAsync();
				var configuration = (await service).As<WechatSigninSettings>();
				return configuration;
			}

			var settings = GetServerSettingsAsync().GetAwaiter().GetResult();

			// 启动 CO2NET 全局注册，必须！
			SenparcSetting senparcSetting = new SenparcSetting {
				IsDebug = true,
				DefaultCacheNamespace = "DefaultCache"
			};
			IRegisterService register = RegisterService.Start(null, senparcSetting)
														.UseSenparcGlobal(false, null);

			////开始注册微信信息，不必须，至少通过微信发消息，没有使用也可以了！
			//SenparcWeixinSetting senparcWeixinSetting = new SenparcWeixinSetting {
			//	Token = settings.Token,
			//	EncodingAESKey = settings.EncodingAESKey,
			//	WeixinAppId = settings.AppId,
			//	WeixinAppSecret = settings.Secret
			//};
			//register.UseSenparcWeixin(senparcWeixinSetting, senparcSetting);

		}
