### ISSUE TITLE
二次验证成员成功加入企业的接口没有支持

### ISSUE THREAD

**Issue by ringls** [JeffreySu/WeiXinMPSDK#1631]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
二次验证成员成功加入企业的接口没有支持

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 微信官方文档 URL
[二次验证](https://work.weixin.qq.com/api/doc#90000/90135/90203)

##### 微信官方文档快照（直接复制关键内容到下方）

企业在开启二次验证时，必须在管理端填写企业二次验证页面的url。
当成员登录企业微信或关注微工作台（原企业号）加入企业时，会自动跳转到企业的验证页面。在跳转到企业的验证页面时，会带上如下参数：code=CODE。
企业收到code后，使用“通讯录同步助手”调用接口“根据code获取成员信息”获取成员的userid。然后在验证成员信息成功后，调用如下接口即可让成员成功加入企业。

##### 发现问题的模块

- [x] Senparc.Weixin.Work 版本：

##### 模块对应的 .net 版本

- [x] .net 3.5
- [x] .net 4.0
- [x] .net 4.5
- [x] .net standard 2.0
- [x] .net core 1.x
- [x] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [x] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

试着封装了一下

`

        public static WorkJsonResult AuthSucc(string accessTokenOrAppKey, string userId)
        {
            return ApiHandlerWapper.TryCommonApi(accessToken =>
            {
                var url = string.Format(Config.ApiWorkHost + "/cgi-bin/user/authsucc?access_token={0}&userid={1}", accessToken.AsUrlData(), userId);

                return CommonJsonSend.Send<WorkJsonResult>(null, url, null, CommonJsonSendType.GET);
            }, accessTokenOrAppKey);

           
        }
`

**Comment by JeffreySu** [comment]
已经支持了，可以看这里：

https://github.com/JeffreySu/WeiXinMPSDK/blob/6a4b0f12f831aed7cfa3f9248ed22c6caec4deb2/src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPay/V3/Universal/Entities/Request/TenPayV3PayToWorkerRequestData.cs#L203

**Comment by ringls** [comment]
你确定你这个和我说的是同一个接口吗？

**Comment by JeffreySu** [comment]
@ringls  不好意思，是回复另外一个issue的  😄

**Comment by JeffreySu** [comment]
已经发布了，感谢贡献代码 👍
