### ISSUE TITLE
企业微信支付接口生成签名错误

### ISSUE THREAD

**Issue by tony26050369** [JeffreySu/WeiXinMPSDK#1633]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
对于企业微信的企业支付功能，不管是：PayToWorker（向员工付款），还是SendWorkRedPack（向员工发红包接口），调用后都会返回错误：WORKWX_SIGN_ERROR（企业微信签名错误）

我仔细看了一下源码，CreateMd5Sign这个function有点问题。对于企业微信的签名，有一项要求：在stringA最后拼接上企业微信支付应用secret（参见企业微信管理端支付应用页面的secret），得到stringSignTemp字符串，并对stringSignTemp进行MD5运算，再将得到的字符串所有字符转换为大写，得到sign值signValue。

也就是说，把参数拼接完成之后，在最后加上企业微信支付应用的secret，然后再做MD5。示例：stringSignTemp=”stringA&secret=192006250b4c09247ec02edce69f6a2d”

对于PayToWorker这个接口，入参中有Secret(企业微信支付应用的Secret)这个入参，只要改一个CreateMd5Sign就Ok了

对于SendWorkRedPack这个接口，入参中就没有Secret，需要增加个入参，才能生成正确的企业微信签名。

谢谢！

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 微信官方文档 URL
https://work.weixin.qq.com/api/doc#90000/90135/90281   

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [X] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
你可以先看一下这里的做法，是分两次调用 CreateMd5Sign，主要是想把这个过程暴露出来，并且可以不用把secret单独作为一个参数传进去（如果这样做的话，就最好写个重写方法）。

https://github.com/JeffreySu/WeiXinMPSDK/blob/6a4b0f12f831aed7cfa3f9248ed22c6caec4deb2/src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPay/V3/Universal/Entities/Request/TenPayV3PayToWorkerRequestData.cs#L203

你可以看一下上面的代码你那边执行是否可用。

**Comment by JeffreySu** [comment]
@tony26050369  如果没问题我先关闭了。
