### ISSUE TITLE
Senparc.Weixin.MP.Sample.sln 运用了c#7.0 语法

### ISSUE THREAD

**Issue by RickyZhou1** [JeffreySu/WeiXinMPSDK#1636]
##### 问题描述
使用 VS2015 打开 Senparc.Weixin.MP.Sample.sln 会出现许多的编译报错， 主要是Domain ID 这个property 使用的C#7.0 的语法(需要使用VS2017的编译器)，在VS2015中无法编译

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [x] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [ ] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [x] Visual Studio 2015
- [ ] Visual Studio 2017
- [ ] 其他：

**Comment by JeffreySu** [comment]
对的，可以参考这里进行修改：https://weixin.senparc.com/QA-655

我们会在后续版本中权衡新老版本的代码，也欢迎直接修改成你那边VS2015支持的代码PR过来。

**Comment by lishewen** [comment]
准备2019了，.net core 3.0了，C#8.0了，语法改进放着不用也是可惜

**Comment by JeffreySu** [comment]
@lishewen 确实一直很克制 🤣
