### ISSUE TITLE
MediaList_NewsResult中缺少微信的“thumb_url”的返回值

### ISSUE THREAD

**Issue by zmrbak** [JeffreySu/WeiXinMPSDK#164]
MediaList_NewsResult NewsResult = MediaApi.GetNewsMediaList(accessToken, NewsOffset, 20);

微信服务器中返回的news_item:
"news_item": [
                    {
                        "title": "单图文消息", 
                        "author": "", 
                        "digest": "", 
                        "content": "", 
                        "content_source_url": "", 
                        "thumb_media_id": "xUTU_rTn29HQvXtHCwom5rl5_3IIH_HiRXWOx2NIdR8", 
                        "show_cover_pic": 0, 
                        "url": "http://mp.weixin.qq.com/s?__biz=MzAwMjcwMDU3Nw==&mid=403983719&idx=1&sn=4a4420b18f1b6c0ee829c1d67296c07a#rd", 
                        "thumb_url": "http://mmbiz.qpic.cn/mmbiz/f0zib7yrM8nyhV0hndicY97JD70dOhj0yP9Vtm3s1tOLd6l91lO4T9Jkiblcfa9tb7vicRrf1icW6MOlYFMqBQ1931w/0?wx_fmt=jpeg"
                    }, 
使用SDK后，没有取得thumb_url项。

**Comment by TYSZCC** [comment]
感谢您的反馈，已经修改！
