### ISSUE TITLE
找不到方法:“System.DateTime Senparc.NeuChar.Entities.IMessageBase.get_CreateTime()”

### ISSUE THREAD

**Issue by foxaaa** [JeffreySu/WeiXinMPSDK#1643]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
 
升级到最新版本之后 ，事件无法触发 系统日志里面显示  
找不到方法:“System.DateTime Senparc.NeuChar.Entities.IMessageBase.get_CreateTime()”
 

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：6.3.9.0
- [ ] Senparc.Weixin.MP 版本：16.6.1.0
- [ ] Senparc.Weixin.MP.MVC 版本：7.2.1.0
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

 
-[x] ] .net 4.5
 

##### 开发环境

 
- [x] Visual Studio 2017
 

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email： 29938389@qq.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
你确定全部都升级到最新的版本了吗？之前有开发者反映过类似的问题，最后发现是生产环境有一个dll是旧版本的。

**Comment by foxaaa** [comment]
> 你确定全部都升级到最新的版本了吗？之前有开发者反映过类似的问题，最后发现是生产环境有一个dll是旧版本的。

  <package id="Senparc.CO2NET" version="0.5.2" targetFramework="net452" />
  <package id="Senparc.CO2NET.APM" version="0.2.5" targetFramework="net452" />
  <package id="Senparc.NeuChar" version="0.6.2.1" targetFramework="net452" />
  <package id="Senparc.Weixin" version="6.3.9" targetFramework="net452" />
  <package id="Senparc.Weixin.MP" version="16.6.1" targetFramework="net452" />
  <package id="Senparc.Weixin.MP.MVC" version="7.2.1" targetFramework="net452" />
  <package id="Senparc.Weixin.TenPay" version="1.1.3" targetFramework="net452" />
  <package id="Senparc.Weixin.Work" version="3.3.3.1" targetFramework="net452" /> 
 
我重新对比了 是最新版本~

**Comment by JeffreySu** [comment]
现在我们线上Demo运行的就是自动部署的全部最新dll版本的：https://sdk.weixin.senparc.com/

是否能告知一下你的生产环境软件配置（虽然我感觉关系应该不大）？

我们线上的是  IIS 7.5+ .NET Core 2.2 + Redis

**Comment by JeffreySu** [comment]
我看到差别了，你发的错误：System.DateTime Senparc.NeuChar.Entities.IMessageBase.get_CreateTime，确实是不存在的，最新版本已经是DateTimeOffset类型了，不再是DateTime，所以可能要看一下你调用的dll是不是旧的（或者说引用新版本之后没有重新编译）？

**Comment by foxaaa** [comment]
> 现在我们线上Demo运行的就是自动部署的全部最新dll版本的：https://sdk.weixin.senparc.com/
> 
> 是否能告知一下你的生产环境软件配置（虽然我感觉关系应该不大）？
> 
> 我们线上的是 IIS 7.5+ .NET Core 2.2 + Redis

我们的是 IIS 16 + .Net 4.5

**Comment by foxaaa** [comment]
> 我看到差别了，你发的错误：System.DateTime Senparc.NeuChar.Entities.IMessageBase.get_CreateTime，确实是不存在的，最新版本已经是DateTimeOffset类型了，不再是DateTime，所以可能要看一下你调用的dll是不是旧的（或者说引用新版本之后没有重新编译）？

嗯 非常感谢 我清除掉重新拉下新版本 麻烦你了~

**Comment by JeffreySu** [comment]
嗯，补充一下，我上面说的“你调用的dll”是你自己项目的（或其他第三方）的dll。
