### ISSUE TITLE
客服消息发送菜单消息找不到对应的API

### ISSUE THREAD

**Issue by crashsol** [JeffreySu/WeiXinMPSDK#1644]
{
  "touser": "OPENID"
  "msgtype": "msgmenu",
  "msgmenu": {
    "head_content": "您对本次服务是否满意呢? "
    "list": [
      {
        "id": "101",
        "content": "满意"
      },
      {
        "id": "102",
        "content": "不满意"
      }
    ],
    "tail_content": "欢迎再次光临"
  }
}
按照上述例子，用户会看到这样的菜单消息：
“您对本次服务是否满意呢？
满意
不满意”
其中，“满意”和“不满意”是可点击的，当用户点击后，微信会发送一条XML消息到开发者服务器，格式如下：
请问使用这个功能发送API接口、接受点击回传的消息对应的Handler 处理的消息类型是什么呢

**Comment by JeffreySu** [comment]
@crashsol  你说的“格式如下：”具体是什么格式？另外msgmenu这个类型我暂时还没看到文档，能提供一下吗？

**Comment by JeffreySu** [comment]
非常感谢！已经连夜更新版本 MP v16.6.13

可在【盛派网络小助手】公众号进行测试：

![image](https://user-images.githubusercontent.com/2281927/53901594-476ca100-407a-11e9-8bb9-64735236b2ce.png)

**Comment by crashsol** [comment]
谢谢老师，老师这么晚了，都还在处理issues，向老师学习！
