### ISSUE TITLE
通过第三方平台群发消息后，怎么知道群发完成的状态？

### ISSUE THREAD

**Issue by zhujinhu21** [JeffreySu/WeiXinMPSDK#165]
我看到有OnEvent_MassSendJobFinishRequest 方法，群发完成后就会触发此事件吗？
public override IResponseMessageBase OnEvent_MassSendJobFinishRequest(RequestMessageEvent_MassSendJobFinish requestMessage)
        {
            var responseMessage = CreateResponseMessage<ResponseMessageText>();
            responseMessage.Content = "接收到了群发完成的信息";
           return responseMessage;
        }

return responseMessage 是发送给谁了？

**Comment by JeffreySu** [comment]
返回给微信服务器，随便返回什么，没有人会收到这条消息。
