### ISSUE TITLE
升級Senparc.Weixin.MP 16.6.14.2后PostModel，扫描带参数二维码事件没有响应

### ISSUE THREAD

**Issue by AlexGeller** [JeffreySu/WeiXinMPSDK#1658]
升级了最新的版本16.6.14.2的，然后使用PostModel执行带参数二维码的扫描响应。

            var postModel = new PostModel()
            {
                Msg_Signature = "845997ceb6e4fd73edd9a377be227848ce20d34f",
                Timestamp = "1412587525",
                Nonce = "1501543730",

                Token = "fzBsmSaI8XE1OwBh",
                EncodingAESKey = "9J8CQ7iF9mLtQDZrUM1loOVQ6oNDxVtBi1DBU2oaewl",
                CorpId = "wx7618c0a6d9358622"
            };
            var messageHandler = new CustomMessageHandlers(XDocument.Parse(testXml), postModel, 10);
            Assert.IsNotNull(messageHandler.RequestDocument);
            Assert.IsNotNull(messageHandler.RequestMessage);
            Assert.IsNotNull(messageHandler.EncryptPostData);
            Assert.IsTrue(messageHandler.AgentId == 2);

            messageHandler.Execute();

            Assert.IsNotNull(messageHandler.ResponseDocument);
            Assert.IsNotNull(messageHandler.ResponseMessage);

            Console.WriteLine(messageHandler.RequestDocument);

进过调试，因为使用的是测试公众号，所PostModel里除了EncodingAESKey外其它的参数都有值，当执行Execute方法后，messageHandler.RequestDocument为空，而且扫描带参数二维码的响应事件OnEvent_ScanRequest也没有进行响应。

**Comment by AlexGeller** [comment]
带参数的二维码的扫描事件中，新关注的微信号，subscribe类型的通知无法接收到，OnEvent_ScanRequest无法响应，当执行Execute方法后，messageHandler.RequestDocument为null。但是已关注的微信号，scan类型的通知可以接收到。

**Comment by JeffreySu** [comment]
检查一下你的具体执行事件里面有没有代码影响到，你可以试一下这个页面的二维码登陆，目前就是最新版本的：https://weixin.senparc.com/Home/Login

**Comment by AlexGeller** [comment]
查看源代码，原来扫描二维码首次订阅的事件不是在OnEvent_ScanRequest，面是OnEvent_SubscribeRequest。
