### ISSUE TITLE
JSSDKHelper.GetJsSdkUiPackage 报错，token过期

### ISSUE THREAD

**Issue by archeraya** [JeffreySu/WeiXinMPSDK#1663]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
在和示例代码同样写法的WeixinJSSDKController中，调用JSSDKHelper.GetJsSdkUiPackage(appId, secret, Request.Url.AbsoluteUri);时报错：微信 GET 请求发生错误！错误代码：40001，说明：invalid credential, access_token is invalid or not latest，这块代码一直和demo一样没动过，记得以前在过期后可以自动重新获取吧。

在 Senparc.Weixin.CommonAPIs.CommonJsonSend.<>c.<.cctor>b__6_0(String apiUrl, String returnText) 在 Senparc.CO2NET.HttpUtility.Get.GetJson[T](String url, Encoding encoding, Action`2 afterReturnText) 在 Senparc.Weixin.CommonAPIs.CommonJsonSend.Send[T](String accessToken, String urlFormat, Object data, CommonJsonSendType sendType, Int32 timeOut, Boolean checkValidationResult, JsonSetting jsonSetting) 在 Senparc.Weixin.MP.CommonAPIs.CommonApi.<>c__DisplayClass3_0.b__0(String accessToken) 在 Senparc.Weixin.CommonAPIs.ApiHandlerWapper.ApiHandlerWapperBase.TryCommonApiBase[T](PlatformType platformType, Func`1 accessTokenContainer_GetFirstOrDefaultAppIdFunc, Func`2 accessTokenContainer_CheckRegisteredFunc, Func`3 accessTokenContainer_GetAccessTokenResultFunc, Int32 invalidCredentialValue, Func`2 fun, String accessTokenOrAppId, Boolean retryIfFaild) 在 Senparc.Weixin.MP.ApiHandlerWapper.TryCommonApi[T](Func`2 fun, String accessTokenOrAppId, Boolean retryIfFaild) 在 Senparc.Weixin.MP.Containers.JsApiTicketContainer.GetJsApiTicketResult(String appId, Boolean getNewTicket) 在 Senparc.Weixin.MP.Containers.JsApiTicketContainer.GetJsApiTicket(String appId, Boolean getNewTicket) 在 Senparc.Weixin.MP.Sample.Controllers.WeixinJSSDKController.JSSDKLocation()

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 发现问题的模块
目前都是最新版
- [ ] Senparc.Weixin 版本：
- [x] Senparc.Weixin.MP 版本：16.6.14.2
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：3.4.2
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [x] .net 4.5.1
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [ ] 服务器内存缓存（默认）
- [x] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：archeraya@163.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
https://weixin.senparc.com/QA-474

**Comment by JeffreySu** [comment]
https://weixin.senparc.com/QA-515
