### ISSUE TITLE
大家好，有java版本的微信开发教程么

### ISSUE THREAD

**Issue by java-aodeng** [JeffreySu/WeiXinMPSDK#1664]
大家好，有java版本的微信开发教程么

**Comment by John0King** [comment]
你是来捣蛋的么？😂

**Comment by JeffreySu** [comment]
这里没有，这个项目是 .NET 的，简单易学，开发高效，自带日志跟踪、上下文等辅助功能，几乎支持微信所有模块接口：
https://item.jd.com/12220004.html
https://study.163.com/course/introduction/1004873017.htm
https://sdk.weixin.senparc.com/
