### ISSUE TITLE
我这边是asp.net core 2.1 的webapi，请问我应该如何选择版本？

### ISSUE THREAD

**Issue by lousaibiao** [JeffreySu/WeiXinMPSDK#1669]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 重现问题步骤（如果可以）

1. 选了版本16.6.0，
2. restore的时候提示
error NU1107: Version conflict detected for Microsoft.AspNetCore.Hosting. Install/reference Microsoft.AspNetCore.Hosting 2.2.0 directly to project 【project】 to resolve this issue. 
error NU1107:  【project】 -> Senparc.Weixin.MP 16.6.0 -> Senparc.NeuChar 0.5.0 -> Senparc.CO2NET 0.4.1 -> Microsoft.AspNetCore.Hosting (>= 2.2.0) 
error NU1107:  【project】 -> Microsoft.AspNetCore.App 2.1.1 -> Microsoft.AspNetCore.Hosting (>= 2.1.1 && < 2.2.0)
3. 是只能升级2.1为2.2吗？

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [x] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [x] .net core 2.1

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [x] 其他：vscode

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
你可以直接使用Nuget安装，如果需要使用源代码进行编译的话，需要装一下.net core 2.2。
