### ISSUE TITLE
在CardApi中找不到对“拉取会员信息”接口的封装

### ISSUE THREAD

**Issue by donghaiting** [JeffreySu/WeiXinMPSDK#167]
我想获取用户会员卡上的会员信息，微信官方文档说是要调用https://api.weixin.qq.com/card/membercard/userinfo 这个接口，我在senparc.weixin.mp的源代码里没搜到这个接口。
是不是遗漏了？

**Comment by JeffreySu** [comment]
目前确实没有，我们会尽快添加，谢谢反馈！
如果您已经有补充好的代码，也欢迎pull request过来：）

**Comment by JeffreySu** [comment]
已经加上去了，v13.6.6中，如果有任何问题或者遗漏的API欢迎继续反馈，非常感谢！！
