### ISSUE TITLE
加密模式导致自动回复消失失效

### ISSUE THREAD

**Issue by z65877424** [JeffreySu/WeiXinMPSDK#1670]
##### 问题描述
公众号设置加密模式后，导致自动回复消息失效，通过日志看到返回空，在Debug环境检测没有进入到OnTextRequest方法

##### 模块对应的 .net 版本

- [x] .net 4.5

##### 开发环境
- [x] Visual Studio 2017

##### 缓存环境

- [x] Redis 版本：

##### 联系方式
Email：brandon.zhao@homsom.com

**Comment by JeffreySu** [comment]
1、确认一下所有dll或者nuget包是否是最新的，
2、需要看一下具体停在什么地方，并且给出信息才好判断，【盛派网络小助手】官方的号就是加密的，一直很正常，你可以测试一下。使用的是Sample .net core 2.2的代码（之前.net 4.5的也没问题）。
