### ISSUE TITLE
获取菜单接口，返回的个性化菜单无法获取menuid

### ISSUE THREAD

**Issue by janywhere** [JeffreySu/WeiXinMPSDK#169]
bug:16030701
fix:
namespace Senparc.Weixin.MP.CommonAPIs
    public partial class CommonApi
public static GetMenuResult GetMenuFromJsonResult( GetMenuResultFull resultFull, ButtonGroupBase buttonGroupBase)

//设置个性化菜单列表
                if (resultFull.conditionalmenu!=null )
                {
                    var conditionalMenuList = new List< ConditionalButtonGroup>();
                    foreach (var conditionalMenu in resultFull.conditionalmenu)
                    {
                        var conditionalButtonGroup = new ConditionalButtonGroup();
                        //fix bug 16030701
                        conditionalButtonGroup.matchrule = conditionalMenu.matchrule;
                        conditionalButtonGroup.menuid = conditionalMenu.menuid;
                        //fix bug 16030701 end
                        GetButtonGroup(conditionalMenu.button, conditionalButtonGroup); //设置默认菜单
                        conditionalMenuList.Add(conditionalButtonGroup);
                    }
                    result.conditionalmenu = conditionalMenuList;
                }
以上是我的fix，可以获取到menuid请验证正确性。

下面可能是微信公众平台自己的bug：
获取menuid后，我用删除个性化菜单接口却无法删除这个个性化菜单，提示错误：微信Post请求发生错误！错误代码：65301，说明：this menu is not conditionalmenu hint: [kDVWLA0380vr19]

这个难道是微信自己的bug？

**Comment by JeffreySu** [comment]
已经添加代码，你测试一下看看。
