### ISSUE TITLE
最新企业微信JsApiTicketContainer.TryGetTicket 提示尚未注册

### ISSUE THREAD

**Issue by carlchou** [JeffreySu/WeiXinMPSDK#1698]
##### 问题描述

企业微信接口JsApiTicketContainer.TryGetTicket 提示appId（）尚未注册，请先使用AccessTokenContainer.Register完成注册（全局执行一次即可）！

未更新前，使用均正常；
退回更新前版本即正常
![image](https://user-images.githubusercontent.com/8382278/56400336-fe695880-6285-11e9-9fee-52d3cd0597e0.png)

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 发现问题的模块

- [x ] Senparc.Weixin 版本：6.3.11（从6.3.5升级）
- [x ] Senparc.Weixin.MP 版本：16.6.15（从16.6.9升级）
- [x ] Senparc.Weixin.MP.MVC 版本：7.2.7.2（从7.2.4升级）
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [x ] Senparc.Weixin.Work 版本：3.3.10.1（从3.3.4升级）
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [x ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：65195039@qq.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
你在global.asax.cs中的注册代码都执行了吗？

**Comment by carlchou** [comment]
global中是这么写的

var isGLobalDebug = true;//设置全局 Debug 状态
            var senparcSetting = SenparcSetting.BuildFromWebConfig(isGLobalDebug);
            var register = RegisterService.Start(senparcSetting).UseSenparcGlobal();//CO2NET全局注册，必须！

            var isWeixinDebug = true;//设置微信 Debug 状态
            var senparcWeixinSetting = SenparcWeixinSetting.BuildFromWebConfig(isWeixinDebug);
            register.UseSenparcWeixin(senparcWeixinSetting, senparcSetting);////微信全局注册，必须！

**Comment by JeffreySu** [comment]
你在使用相关的高级接口之前，有注册对应企业微信的特定app的appid和secret吗？

**Comment by carlchou** [comment]
有多个应用，每个都要注册？
但问题是，没更新前，一直正常在使用的

**Comment by JeffreySu** [comment]
企业微信的应用里面，secret每一个都是不一样的，如果不注册多个，那就意味着一直使用固定给的一个应用。
