### ISSUE TITLE
Newtonsoft.Json对AccessTokenExpireTime反序列化的异常

### ISSUE THREAD

**Issue by xjfxkook** [JeffreySu/WeiXinMPSDK#1702]
##### 问题描述
使用NuGet上的最新版本：
   package id="Senparc.CO2NET" version="0.5.2" targetFramework="net472"
  package id="Senparc.CO2NET.APM" version="0.2.5" targetFramework="net472"
  package id="Senparc.CO2NET.Cache.Redis" version="3.4.2" targetFramework="net472"
  package id="Senparc.CO2NET.Cache.Redis.RedLock" version="2.1.0" targetFramework="net472"
  package id="Senparc.NeuChar" version="0.6.4" targetFramework="net472"
  package id="Senparc.Weixin" version="6.3.11" targetFramework="net472"
  package id="Senparc.Weixin.Cache.Redis" version="2.5.3" targetFramework="net472"
  package id="Senparc.Weixin.MP" version="16.6.15" targetFramework="net472"
  package id="Senparc.Weixin.MP.MVC" version="7.2.7.2" targetFramework="net472" 
现象：
调用获取Token(如：AccessTokenContainer.GetAccessToken(appId))或调用方法(如：UserTagApi.Get(appId))时，发生异常：Could not convert string to DateTimeOffset: 0001-01-01 00:00:00. Path 'AccessTokenExpireTime'

##### 重现问题步骤（如果可以）
0. 项目是一个平台管理多个公众号，运维选择一个公众号操作
1. 使用没有访问过的新的公众号（或者将redis中的缓存全部清除）
2. 调用“AccessTokenContainer.GetAccessToken”方法
3. 调用后一定会报异常“Could not convert string to DateTimeOffset: 0001-01-01 00:00:00. Path 'AccessTokenExpireTime'”
4. 跟踪代码至“Senparc.Weixin.MP\Senparc.Weixin.MP\Containers\AccessTokenContainer.cs”大约在181行“AccessTokenExpireTime = DateTimeOffset.MinValue”，这儿取了DateTimeOffset的最小值（0001-01-01 00：00：00），但在后续代码中，用"Newtonsoft.Json"反序列化了AccessTokenExpireTime，因为时区（GMT+8）的问题，反序列化失败了。
5. 将DateTimeOffset.MinValue改为DateTimeOffset.Now.AddYears(-100)，问题排除（其实只要不取最小值，就不会产生异常）。

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ x ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ x ] .net 4.7.2
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [ ] 服务器内存缓存（默认）
- [ x ] Redis 版本：3.2
- [ ] Memcached 版本：
- [ ] 其他

**Comment by JeffreySu** [comment]
是否有试过将Redis缓存清空？

**Comment by xjfxkook** [comment]
Redis里面有值（旧系统的值）反而不会出错，只要AccessTokenExpireTime不为0001-01-01就不会出这个异常。而如果之前没有值，或者清空值就是会报错。

我参与的另一个项目也遇到过类似的问题。
只要Newtonsoft.Json遇到0001-01-01 00:00:00值的时候，反序列化就会报错。但序列化不会报错。
我们开发人员的几台电脑都有这个问题，后来将日期初始化成1970-01-01，问题就解决了。

不知道是不是和开发环境或是Newtonsoft.Json的版本有关（我们测试了11.0和12.0几个版本，都有问题，更早的版本没有试过）。

**Comment by JeffreySu** [comment]
不排除是Newtonsoft.Json版本的问题。
回到你眼下的问题上，如果Redis清空之后，使用最新版本的SDK dll，是否问题还存在？

**Comment by xjfxkook** [comment]
我就是升级了最新版本的SDK DLL，清空Redis之后，发生上述异常的。

**Comment by JeffreySu** [comment]
你用报错的版本看一下Newtonsoft.Json序列化一个默认的日期时间最终的字符串是什么？

**Comment by JeffreySu** [comment]
一般都是dll版本依赖有问题，可以所有的dll更新到最新版本（包括Senparc系所有库）。
如果已经很久没有更新，并且使用分布式缓存的情况，建议清空缓存。
