### ISSUE TITLE
服务商对账单下载对账单日期格式

### ISSUE THREAD

**Issue by Hsinky** [JeffreySu/WeiXinMPSDK#1706]
单元测试文件WeiXinMPSDK/src/Senparc.Weixin.MP/Senparc.Weixin.MP.Test/TenPayV3/TenPayV3Test.cs中方法DownloadBillTest()140行，var dataInfo = new TenPayV3DownloadBillRequestData(base._appId, base._mchId, nonceStr, "Senparc POS 1",
                SystemTime.Now.ToString("yyyy-MM-dd"), "ALL", sandBoxKey);的时间格式应该是 DateTime.Now.ToString("yyyyMMdd")

**Comment by JeffreySu** [comment]
@Hsinky  已修正，感谢！
