### ISSUE TITLE
AccessTokenContainer.Register失效，运行后提示没有注册

### ISSUE THREAD

**Issue by sccasupercat** [JeffreySu/WeiXinMPSDK#173]
我使用的是mp的13.6.3.31910版本，调用api时提示此appId尚未注册。之前的版本都是正常的，升级后才发生这个问题，暂时只能用回前一版本。

**Comment by sccasupercat** [comment]
AccessTokenContainer.Register(appid, secret); // 注册
AccessTokenContainer.CheckRegistered(appid); // 马上检查，结果是false

**Comment by sccasupercat** [comment]
补充，经测试，AccessTokenContainer.Register放在Application_Start和OWIN的StartUp里面是失效的，但是放在其他地方就能正常工作，老版本是不会这样的。另外，Application_Start和OWIN的StartUp是大部分应用程序的启动组件，如果不放在这里可以放在哪里呢？所以我还是先用会旧版，等作者解决了这个问题再升级。谢谢。

**Comment by JeffreySu** [comment]
是的，正在针对这个问题做补充方案，原理是为了提高分布式缓存的通讯效率，修改的值不会立即存入缓存，有一个等待时间，所以马上check会找不到（1-2秒以后就可以了，你可以测试一下）。我们会再提供一个立即缓存的方法。

注册的代码放在Application_Start和StartUp都支持的，我们只是放在Application_Start里面做个例子。

**Comment by sccasupercat** [comment]
谢谢您的回复。事实上我已经测试过了，因为我在其他地方调用api的时候看到这个错误，然后看了你的代码，我才去写这个立即检测的方法去测试的，我用的时候肯定不止2秒了。所以我估计应该是缓存发生了某种错误。

**Comment by sccasupercat** [comment]
我建议您这样，做两个措施。第一，提供一个立即缓存的方式，缓存失败抛出异常；第二，检查现在的缓存机制是否存在bug并进行改进，我可以配合你用我的环境进行测试。我的邮箱是14593719@qq.com，您可以加我qq。

**Comment by JeffreySu** [comment]
立即生效的功能在上一个版本中已经提供，您可以再测试一下。
另外已发您邮件，感谢！

**Comment by sccasupercat** [comment]
已测试，故障已排除，非常感谢！
