### ISSUE TITLE
AccessTokenContainer好像存在问题

### ISSUE THREAD

**Issue by bxjg1987** [JeffreySu/WeiXinMPSDK#1732]
AccessTokenContainer.RegisterAsync方法中
``` C#
RegisterFunc = async () =>
            {
                //using (FlushCache.CreateInstance())
                //{
                var bag = new AccessTokenBag()
                {
                    //Key = appId,
                    Name = name,
                    AppId = appId,
                    AppSecret = appSecret,
                    AccessTokenExpireTime = DateTimeOffset.MinValue,
                    AccessTokenResult = new AccessTokenResult()
                };
                await UpdateAsync(appId, bag, null);//第一次添加，此处已经立即更新
                return bag;
                //}
            };
```
问题是这个委托RegisterFunc是全局静态，当我注册多个公众号时后注册的会覆盖之前注册的吧？

另外在其父类的CheckRegisteredAsync方法中调用TryReRegister();没有使用await，后面的return可能还是会返回false，失去重新注册的意义了吧？

另外所有非ui层的 使用了async定义的方法内部的 await语句没有使用ConfigureAwait(false)，调用方若使用返回的Task.Result()可能造成死锁

另外想问问Bag的属性变更通知不是已经取消的，扩展缓存策略目前只有定义，几乎没有再本使用到了？我看Conainer里基本都直接使用的基础缓存策略IBaseObjectCacheStrategy

**Comment by JeffreySu** [comment]
很好的问题，我睡一觉答复你，早睡早起，晚安 😄

**Comment by JeffreySu** [comment]
@bxjg1987 非常感谢反馈！4个问题如下：

1、RegisterFunc 确实会有这个问题，尤其在 TryReRegister() 的时候，我会在下一个版本中修复 👍 

2、TryReRegister() 是上一个版本升级异步方法时候疏漏的，不是故意这样设计的。

3、目前 SDK 的主要场景是在服务器端，所以之前没有考虑 UI 渲染的问题，因为 SDK 依赖于 CO2NET，所以光升级 SDK 并不能完全达到效果，我们已经有计划继续升级 CO2NET 的异步方法，届时 NeuChar、SDK 将一并升级。为了尽快处理您提的问题，已经把这个计划提前。

4、对的，扩展缓存（ContainerCacheStrategy）当时取消属性变更通知会后暂时没用了，是因为考虑.NET 3.5/4.0兼容的问题，上一个版本开始已经通停止对这两个按本的更新，暂时会把这个模块保留，后面会再规划一下。

非常感谢！

**Comment by bxjg1987** [comment]
@JeffreySu 因为我最近一直在学习sdk源码包括co2net，看到扩展缓存有定义，但是实际上在container中只用了一点点扩展缓存，跟书上的不一致，视频中这块讲得不是很详细，担心是自己没看懂所以跟您确认下哈。
扩展缓存的设计稍微有点复杂，并且扩展缓存的作用跟Container的作用感觉有点重合，是否有必要保留扩展缓存呢，Container里直接使用IBaseObjectCacheStrategy更直接吧

**Comment by JeffreySu** [comment]
@bxjg1987 非常感谢发现问题并提出解决方案！您查看的非常仔细，很到位！

关于在CO2NET里面的缓存，我做了一个叫做“领域缓存（Domain Cache）”的概念，是对具体领域内的缓存策略的一种抽象（同时又能支持 Factory 模式适应不同的缓存框架），以后我会专门写文章或者视频介绍其中的设计思路和用意。ContainerCacheStrategy就属于其中之一，这个概念在未来 [SCF](https://gitee.com/SenparcCoreFramework/SCF) 的构建中也会涉及到，目前看上去复杂，但是一方面在特定的环境和领域（Domain）下能够提供更好的编写支持、更清晰的粒度、更好的测试的便利性，另外一方面在长期维护上也是有利的（类似目前的 [SenparcWeixinSetting](https://github.com/JeffreySu/WeiXinMPSDK/blob/7f7d95f666d5949372b315d813a25ded0eda93f3/src/Senparc.Weixin/Senparc.Weixin/Entities/SenparcWeixinSettings/SenparcWeixinSetting.cs#L33)，看上去有点复杂，但是用起来就会很爽，并且效率也能保证）。

**Comment by JeffreySu** [comment]
多账号注册已添加 Demo：

https://github.com/JeffreySu/WeiXinMPSDK/blob/78267ef4f026d07985bf425b2dff575e49f9c2d2/Samples/Senparc.Weixin.MP.Sample.vs2017/Senparc.Weixin.MP.CoreSample/Controllers/WeixinController.cs#L211

在线Demo（有访问频次限制）：https://sdk.weixin.senparc.com/Weixin/MultiAccountTest

**Comment by bxjg1987** [comment]
非常感谢哈！
