### ISSUE TITLE
第三方平台获取公众号的VerifyType

### ISSUE THREAD

**Issue by zariczhu** [JeffreySu/WeiXinMPSDK#174]
通过
 public static GetAuthorizerInfoResult GetAuthorizerInfoResult(string componentAppId, string authorizerAppid, bool getNewTicket = false)
这个api使第三方平台获取公众号的信息，得到的 Verify_type_info 是-1 (未认证),但是改该公众号确实已经认证了，而且也有腾讯的发票，所以会是api的问题吗？获取的内容不准确？

**Comment by JeffreySu** [comment]
这个既然已经得到消息，应该是官方接口传递过来的数据。目前没有发现什么异常，我们会持续关注一段时间，也欢迎提交更多的测试结果，谢谢！
