### ISSUE TITLE
微信开发深度解析：公众号、小程序高效开发秘籍  完整的随书源代码哪里可以获取

### ISSUE THREAD

**Issue by andurils** [JeffreySu/WeiXinMPSDK#1740]
##### 问题描述
微信开发深度解析：公众号、小程序高效开发秘籍  完整的随书源代码哪里可以获取

**Comment by JeffreySu** [comment]
书中有一个 BookHelper 系统，所有代码片段都可以直接复制使用：http://book.weixin.senparc.com

第五章的代码不需要跑通，理解用意即可，框架可以参考SCF（还在不断完善中）：https://github.com/SenparcCoreFramework/SCF
