### ISSUE TITLE
微信点击菜单跳转小程序的事件推送的事件支持

### ISSUE THREAD

**Issue by dupeng0811** [JeffreySu/WeiXinMPSDK#1746]
##### 问题描述
微信点击菜单跳转小程序的事件推送的事件支持，谢谢
微信文档地址：https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1418702138

##### 微信官方文档 URL
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1418702138

##### 微信官方文档快照（直接复制关键内容到下方）
```
<xml>
<ToUserName><![CDATA[toUser]]></ToUserName>
<FromUserName><![CDATA[FromUser]]></FromUserName>
<CreateTime>123456789</CreateTime>
<MsgType><![CDATA[event]]></MsgType>
<Event><![CDATA[view_miniprogram]]></Event>
<EventKey><![CDATA[pages/index/index]]></EventKey>
<MenuId>MENUID</MenuId>
</xml>
```

##### 联系方式
Email：dupeng0811@gmail.com

**Comment by JeffreySu** [comment]
已发布到新版本中，非常感谢！
