### ISSUE TITLE
程序集“Senparc.Weixin.Open, Version=1.6.4.21474, Culture=neutral, PublicKeyToken=null”中的类型“Senparc.Weixin.Open.ComponentAPIs.AuthorizerInfo”未标记为可序列化

### ISSUE THREAD

**Issue by pcstx** [JeffreySu/WeiXinMPSDK#175]
使用RedisContainerCacheStrategy的时候，用Senparc.Weixin.Open搭建第三方平台，绑定微信号在成功回调的地方提示错误，程序集“Senparc.Weixin.Open, Version=1.6.4.21474, Culture=neutral, PublicKeyToken=null”中的类型“Senparc.Weixin.Open.ComponentAPIs.AuthorizerInfo”未标记为可序列化。
是在 queryAuthResult = ComponentContainer.GetQueryAuthResult(component_AppId, auth_code);这句话的地方报的错。
用本地缓存的时候是正常的。

顺便提一句，在微信号绑定到第三方平台的时候，预授权码是不能重复使用的，每次的链接都需要是新的预授权码才行，所以我看demo里面是没有刷新缓存的，第二次使用的时候会提示预授权过期。

**Comment by JeffreySu** [comment]
序列化的标记已经加上，Open v1.6.5

预授权码这一块目前已经在OpenController中加上了强制刷新的参数，不知道你是不是这个意思？
        /// <summary>
        /// 发起授权页的体验URL
        /// </summary>
        /// <returns></returns>
        public ActionResult OAuth()
        {
            //获取预授权码
            var preAuthCode = ComponentContainer.TryGetPreAuthCode(component_AppId, component_Secret, **true**);

            var callbackUrl = "http://weixin.senparc.com/OpenOAuth/OpenOAuthCallback";//成功回调地址
            var url = ComponentApi.GetComponentLoginPageUrl(component_AppId, preAuthCode, callbackUrl);
            return Redirect(url);
        }
