### ISSUE TITLE
小程序未实现转发客服消息的问题

### ISSUE THREAD

**Issue by Nighthawks006** [JeffreySu/WeiXinMPSDK#1751]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
当返回 return new SuccessResponseMessage();
输出到微信服务器的内容 messageHandler.TextResponseMessage===》 :success

当返回 return this.CreateResponseMessage<ResponseMessageTransfer_Customer_Service>();  
输出到微信服务器的内容 messageHandler.TextResponseMessage===》 :（此处为空）

临时解决办法：

IResponseMessageBase responseMessage = messageHandler.ResponseMessage;
                if (responseMessage.MsgType == ResponseMsgType.Transfer_Customer_Service)
                {
                    messageHandler.TextResponseMessage = EntityHelper.ConvertEntityToXml(messageHandler.ResponseMessage).ToString();
                }
                return new FixWeixinBugWeixinResult(messageHandler);

##### 微信官方文档 URL
https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/customer-message/trans.html

##### 联系方式
Email：569455496@qq .com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
最新版本已发布，无需修改任何代码，感谢！
