### ISSUE TITLE
这个文件NeuCharRoot.config导致消息接收失败

### ISSUE THREAD

**Issue by cicna** [JeffreySu/WeiXinMPSDK#1753]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
netcore版，在服务器上删除了这个NeuCharRoot.config文件才可以接收消息

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：6.4.2-preview3
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [x] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [x] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by cicna** [comment]
贡献点代码：
Senparc.Weixin.MP.Sample.CommonService.CustomMessageHandler


//获取Senparc.Weixin.MP.dll版本信息
#if NET45
            var filePath = ServerUtility.ContentRootMapPath("~/bin/Senparc.Weixin.MP.dll");//发布路径
#else
            //var filePath = ServerUtility.ContentRootMapPath("~/bin/Debug/netcoreapp2.2/Senparc.Weixin.MP.dll");//本地测试路径

            #region 更改
            var filePath = string.Empty;    //发布路径

            //  System.IO.Directory.GetCurrentDirectory()
            //  D:\dev2\House\HuaZhou.ZhongHui\4.6.0\aspnet-core\src\HuaZhou.ZhongHui.Web.Mvc
            if (System.IO.File.Exists(System.IO.Directory.GetCurrentDirectory() + @"\Senparc.Weixin.MP.dll"))
            {
                filePath = ServerUtility.ContentRootMapPath("~/Senparc.Weixin.MP.dll");//发布路径
            }
            //  AppContext.BaseDirectory
            //  D:\dev2\House\HuaZhou.ZhongHui\4.6.0\aspnet-core\src\HuaZhou.ZhongHui.Web.Mvc\bin\Debug\netcoreapp2.2\
            else if (System.IO.File.Exists(AppContext.BaseDirectory + @"\bin\Debug\netcoreapp2.2\Senparc.Weixin.MP.dll"))
            {
                filePath = ServerUtility.ContentRootMapPath("~/bin/Debug/netcoreapp2.2/Senparc.Weixin.MP.dll");//本地测试路径
            }
            else
            {
                filePath = ServerUtility.ContentRootMapPath("~/bin/Debug/netcoreapp2.2/publish/Senparc.Weixin.MP.dll");//本地默认发布测试路径
            }
            #endregion

            //var filePath = ServerUtility.ContentRootMapPath("~/Senparc.Weixin.MP.dll");//发布路径     --官方，在服务器上可以，但本地测试的，要开启第44行
#endif

**Comment by JeffreySu** [comment]
1、是否是从比较早的版本升级过来？
2、看一下NeuCharRoot.config是不是又自动生成了一个（并且现在是正常的）？
3、提交代码请 PR 到 Developer 分支。

非常感谢！
