### ISSUE TITLE
执行ComponentContainer.TryGetPreAuthCode(Component_AppID, Component_AppSecret, true)卡死

### ISSUE THREAD

**Issue by 554393109** [JeffreySu/WeiXinMPSDK#1756]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
执行ComponentContainer.TryGetPreAuthCode(Component_AppID, Component_AppSecret, true)卡死，修改getNewToken参数为false就能过

##### 正常使用版本
Senparc.CO2NET v0.5.2
Senparc.CO2NET.APM v0.2.5
Senparc.CO2NET.Cache.Redis v3.4.2
Senparc.CO2NET.Cache.Redis.RedLock v2.1.0
Senparc.NeuChar v0.6.4
Senparc.Weixin v6.3.11
Senparc.Weixin.Cache.Redis v2.5.3
Senparc.Weixin.MP v16.6.15
Senparc.Weixin.Open v4.4.5.2

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [x] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [x] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [x] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：554393109@qq.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
1、执行 ComponentContainer.TryGetPreAuthCode() 之前是否使用独立的Register方法注册过？
2、如果改用异步方法 ComponentContainer.TryGetPreAuthCodeAsync() 还有同样的情况发生吗？

**Comment by 554393109** [comment]
> 1、执行 ComponentContainer.TryGetPreAuthCode() 之前是否使用独立的Register方法注册过？
> 2、如果改用异步方法 ComponentContainer.TryGetPreAuthCodeAsync() 还有同样的情况发生吗？

> 1、在Global中使用register.RegisterOpenComponent(AppID, AppSecret, aFunc, bFunc, cFunc)进行注册的，其中aFunc, bFunc, cFunc在控制层中是静态方法；
> 2、为尝试过，晚点试试

**Comment by JeffreySu** [comment]
1、注册的时候没有异常，再重新强制注册的时候出错了，是吧？顺便问一下用的是什么缓存？

**Comment by 554393109** [comment]
> 1、注册的时候没有异常，再重新强制注册的时候出错了，是吧？顺便问一下用的是什么缓存？

对的，初次注册无异常【不知和我把aFunc, bFunc, cFunc写在控制层有没关系】；用Redis

**Comment by JeffreySu** [comment]
@554393109 我这边暂时不能重现这个问题，不知道你是否能先直接部署一下原版的Demo，缩小一下问题的范围。
另外异步方法也可以换一下试一下。

**Comment by JeffreySu** [comment]
@554393109 最新预览版本已经发布，请试一下，欢迎反馈结果。
