### ISSUE TITLE
微信Post请求发生错误！错误代码：61006，说明：component ticket is invalid hint

### ISSUE THREAD

**Issue by imicer** [JeffreySu/WeiXinMPSDK#176]
![error](https://cloud.githubusercontent.com/assets/17045801/13982813/1980d892-f127-11e5-9e6c-3c3a197d9baa.png)

Senparc.Weixin.Open，微信开放平台，一切配置正常，授权也没问题，但是偶尔会出现上图错误，无法找到原因！
在微信官方的文档中也找不到错误代码：61006的相关描述。
求解决。

**Comment by pcstx** [comment]
官网的错误代码不是很全面的，自己看说明的英文。应该是微信每10分钟推送给你的令牌在你使用的时候过期了，你没有更新最新的令牌

**Comment by JeffreySu** [comment]
@imicer 确认一下你每10分钟接收到的微信服务器的推送都是可以正常保存起来的。很有可能是没有得到最新的推送。

**Comment by imicer** [comment]
@JeffreySu 谢谢，已经解决！
