### ISSUE TITLE
微信企业付款到零钱疑似无法带上证书

### ISSUE THREAD

**Issue by xcaptain** [JeffreySu/WeiXinMPSDK#1762]
使用 https://github.com/JeffreySu/WeiXinMPSDK/blob/16672377bad9c61a4aa454f0b64a72d926ab0456/src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPay/V3/Universal/TenPayV3.cs#L1129
这个api进行企业付款，但是一直提示证书错误，请重新下载证书，检查了多次配置都是对的，后来我把发请求部分代码替换之后测试成功了

```csharp
public static async Task<TransfersResult> TransfersAsync(TenPayV3TransfersRequestData dataInfo, string cert, string certPassword, int timeOut = 1000000)
{
    var url = ReurnPayApiUrl("https://api.mch.weixin.qq.com/{0}mmpaymkttransfers/promotion/transfers");
    var data = dataInfo.PackageRequestHandler.ParseXML();
    string responseContent = await CertPostAsync(cert, certPassword, data, url);
    return new TransfersResult(responseContent);
}

private static string ReurnPayApiUrl(string urlFormat)
{
    return string.Format(urlFormat, Senparc.Weixin.Config.UseSandBoxPay ? "sandboxnew/" : "");
}

private static async Task<string> CertPostAsync(string cert, string certPassword, string data, string url, int timeOut = 1000000)
{
    var cer = new X509Certificate2(cert, certPassword, X509KeyStorageFlags.PersistKeySet | X509KeyStorageFlags.MachineKeySet);
    var handler = new HttpClientHandler();
    handler.ClientCertificates.Add(cer);
    HttpClient client = new HttpClient(handler);
    var content = new StringContent(data, Encoding.UTF8);
    var response = await client.PostAsync(url, content);
    return await response.Content.ReadAsStringAsync();
}
```

怀疑是 `HttpUtility.HttpPost` 这个方法出问题了，但是我还没来得及调试，先把问题反馈在这

**Comment by JeffreySu** [comment]
@xcaptain 这个问题是.NET Core 2.1之后，HttpClientFactory的一个问题，似乎没有办法对动态的证书实现比较好的加载（看似只能全局配置唯一的cert），这个问题我们正在解决，目前官方也没有给出明确的解决方案和思路。

您使用的这个方法就是旧版本的方法，虽然支持证书，但会出现线程无法回收的问题，已经不再是推荐的写法。

**Comment by JeffreySu** [comment]
写到这一行，上面的 HttpClientHandler 就没有办法被使用了：

https://github.com/Senparc/Senparc.CO2NET/blob/6e797b397625de9b296230a7d894670ea800f4a3/src/Senparc.CO2NET/Utilities/HttpUtility/HttpPost/RequestUtility.Post.cs#L249

**Comment by lishewen** [comment]
https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/HttpClient.cs

**Comment by lishewen** [comment]
https://github.com/aspnet/Extensions/blob/master/src/HttpClientFactory/Http/src/DefaultHttpClientFactory.cs#L124

翻了一下 HttpClientFactory 的源码，HttpClient CreateClient可以按name区分的，应该可以提前注册多个不同name的HttpClient（这样不同name的HttpClient就可以读入不同证书了）可否仿照SenparcSetting多租户配置DI，用appId区分，调用时根据当前appId来Get出对应name的HttpClient来使用

**Comment by JeffreySu** [comment]
@lishewen 是的，一共提供了3种方法，目前用的是强类型的，也是最推荐的一个做法，name可以尝试一下，不过这里面有个问题，是不是所有的证书仍然只能在启动的时候确定下来，没有办法在运行过程中动态加入了？

**Comment by JeffreySu** [comment]
@lishewen 随之而来的另外一个问题是，这些请求以后每个必须要带一个appId之类的参数了，不然区分起来有苦难，用物理路径有很奇怪，如果碰到加载在内存里的byte就没办法了

**Comment by lishewen** [comment]
> @lishewen 随之而来的另外一个问题是，这些请求以后每个必须要带一个appId之类的参数了，不然区分起来有苦难，用物理路径有很奇怪，如果碰到加载在内存里的byte就没办法了

不需要的，url传进来不是都带有accessToken这个参数吗？用正则解析出来作为匹配用即可，这样就可以不用带参数，这个在GetappIdOrAccessToken()方法中不是也理解成唯一吗

**Comment by JeffreySu** [comment]
1、accesstoken不一定是通过缓存拿到的，如果直接GetToken，甚至有的人存在数据库里面，系统没有办法定位的。
2、即使用了GetappIdOrAccessToken()，但是Post方法里面是不知道的，还是需要有参数传进去。

**Comment by xcaptain** [comment]
看了一下`IHttpClientFactory`，你们谈的方案是：
1. 在Startup.cs里面注入named http client
2. 给企业支付对应的http client通过`AddHttpMessageHandler`方法在请求时自动添加证书
3. 在sdk中自动解析出注入的http client从而发请求

你们是在说这个吗？我感觉我可以试试这个方法

**Comment by JeffreySu** [comment]
@xcaptain  .AddHttpMessageHandler() 中要求的返回类型是 DelegatingHandler，不是 HttpClientHandler，你确定这样写可以吗？是不是应该是ConfigurePrimaryHttpMessageHandler() ？

**Comment by xcaptain** [comment]
@JeffreySu 你说对了，我刚一直在调试，换成你的`ConfigurePrimaryHttpMessageHandler`就OK了，按这个写法也能发送支付请求成功

**Comment by JeffreySu** [comment]
@xcaptain 我修改一个版本稍后发上来

**Comment by JeffreySu** [comment]
@xcaptain 按照上述的思路做了，出现下面的错误：

``` C#
	Message：An error occurred while sending the request.
	StackTrace：
	InnerException：An error occurred while sending the request.
	InnerException.StackTrace：   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Senparc.CO2NET.HttpUtility.RequestUtility.HttpResponsePost(String url, CookieContainer cookieContainer, Stream postStream, Dictionary`2 fileDictionary, String refererUrl, Encoding encoding, String certName, Boolean useAjax, Dictionary`2 headerAddition, Int32 timeOut, Boolean checkValidationResult, String contentType)
   at Senparc.CO2NET.HttpUtility.RequestUtility.HttpPost(String url, CookieContainer cookieContainer, Stream postStream, Dictionary`2 fileDictionary, String refererUrl, Encoding encoding, String certName, Boolean useAjax, Dictionary`2 headerAddition, Int32 timeOut, Boolean checkValidationResult, String contentType)
   at Senparc.Weixin.TenPay.V3.TenPayV3.CertPost_NetCore(String mchId, String subMchId, String data, String url, Int32 timeOut)
   at Senparc.Weixin.TenPay.V3.TenPayV3.Refund(TenPayV3RefundRequestData dataInfo, Int32 timeOut)
   at Senparc.Weixin.MP.CoreSample.Controllers.TenPayV3Controller.Refund()
```

当前Developer分支测试的结果（CO2NET新的preview2已经发布到nuget，并且已经引用），当前SDK还没有发布nuget，所以测试的话需要用源代码。注意一下 appsettings.json 里面在TenPayV3下面新增的几个字段，只需要设置这几个字段即可，不需要修改代码，都已经封装好了：

https://github.com/JeffreySu/WeiXinMPSDK/blob/527dc846fe3d3895df8d1eb3095eb059aa953bd6/src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPay/V3/TenPayV3InfoCollection.cs#L124

**Comment by xcaptain** [comment]
@JeffreySu 感谢，很速度，看了下你的提交，https://github.com/Senparc/Senparc.CO2NET/blame/1b0f0f604522f355ed7fa898e1c2f4e33ba6177f/src/Senparc.CO2NET/Utilities/HttpUtility/HttpPost/RequestUtility.Post.cs#L254 我把 https://www.nuget.org/packages/Senparc.Weixin.TenPay/1.4.0-preview 拉下来测试就行对吧

**Comment by lishewen** [comment]
更新后出现：
An unhandled exception occurred while processing the request.
ArgumentNullException: Value cannot be null.
Parameter name: name
Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateClient(string name)

Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateClient(string name)
Senparc.CO2NET.HttpUtility.SenparcHttpClient.GetInstanceByName(string httpClientName)
Senparc.CO2NET.HttpUtility.RequestUtility.HttpPost_Common_NetCore(string url, out HttpContent hc, CookieContainer cookieContainer, Stream postStream, Dictionary<string, string> fileDictionary, string refererUrl, Encoding encoding, string certName, bool useAjax, Dictionary<string, string> headerAddition, int timeOut, bool checkValidationResult, string contentType)
Senparc.CO2NET.HttpUtility.RequestUtility.HttpResponsePostAsync(string url, CookieContainer cookieContainer, Stream postStream, Dictionary<string, string> fileDictionary, string refererUrl, Encoding encoding, string certName, bool useAjax, Dictionary<string, string> headerAddition, int timeOut, bool checkValidationResult, string contentType)
Senparc.CO2NET.HttpUtility.RequestUtility.HttpPostAsync(string url, CookieContainer cookieContainer, Stream postStream, Dictionary<string, string> fileDictionary, string refererUrl, Encoding encoding, string certName, bool useAjax, Dictionary<string, string> headerAddition, int timeOut, bool checkValidationResult, string contentType)
Senparc.CO2NET.HttpUtility.Post.PostGetJsonAsync<T>(string url, CookieContainer cookieContainer, Stream fileStream, Encoding encoding, string certName, bool useAjax, bool checkValidationResult, Action<string, string> afterReturnText, int timeOut)
Senparc.Weixin.CommonAPIs.CommonJsonSend.SendAsync<T>(string accessToken, string urlFormat, object data, CommonJsonSendType sendType, int timeOut, bool checkValidationResult, JsonSetting jsonSetting)
Senparc.Weixin.Work.CommonAPIs.CommonApi.GetTokenAsync(string corpId, string corpSecret)
Senparc.Weixin.Work.Containers.AccessTokenContainer.GetTokenResultAsync(string appKey, bool getNewToken)
Senparc.Weixin.Work.Containers.AccessTokenContainer.GetTokenResultAsync(string corpId, string corpSecret, bool getNewToken)
Senparc.Weixin.Work.Containers.AccessTokenContainer.GetTokenAsync(string corpId, string corpSecret, bool getNewToken)
Senparc.Weixin.Work.Containers.AccessTokenContainer.TryGetTokenAsync(string corpId, string corpSecret, bool getNewToken)
WeChat.Controllers.OverSpeedController.Index() in OverSpeedController.cs
+
            _options.DriverAccessToken = await AccessTokenContainer.TryGetTokenAsync(_options.CorpId, _options.DriverSecret);
Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by lishewen** [comment]
是目前nuget的最新版本

**Comment by lishewen** [comment]
我看了下代码也是做了空处理的，是不是没更新nuget

**Comment by lishewen** [comment]
另外 Senparc WeiXin SDK 各个依赖组件之间的版本号差距太大，经常搞乱，建议全部统一成一个版本号。
就像.net core各个组件的版本号那样

**Comment by lishewen** [comment]
https://www.nuget.org/packages/Senparc.Weixin.MP/16.7.4.3
作为一个发行版引用的却是
https://www.nuget.org/packages/Senparc.Weixin/6.4.4-preview1
这个preview版，而这个版本再依赖于有问题的
https://www.nuget.org/packages/Senparc.CO2NET/0.7.3.1-preview1
上述的问题在Senparc.CO2NET/0.7.3.1-preview2中修正了的
但需要单独安装Senparc.CO2NET/0.7.3.1-preview2才能解决
好多用家（例如我的小弟）在使用的时候都是直接引用 Senparc.Weixin.MP/16.7.4.3 这种发行版的包的，不会单独安装依赖包

**Comment by JeffreySu** [comment]
@xcaptain  不只是这一个文件，如果你要复制代码到自己的项目，最好看一下相关版本的提交代码。

@lishewen 是的，这次因为我们几个人测试用，估计大家需要源代码的，或者直接更新对应的版本号。所以我只是在上面说明了一下，没有特意发布全面的新版本，不然这次测试下来各种历史版本会非常多。

**Comment by JeffreySu** [comment]
@lishewen @xcaptain 现在这个代码中间的注册部分已经用了上述 @xcaptain  相关的方案，根据实际情况做了适当的修改，目前仍然是会有错误，不知道你们测试结果怎么样？

**Comment by lishewen** [comment]
我们的核心项目一直是用我们私有的魔改库的，用发行版的是给小弟练手的小项目，流量也小，目前试 preview2 生产跑了一天暂时没什么大问题

这次的httpclient修改，我觉得也可以顺便把 polly 策略 需求加上 （https://github.com/JeffreySu/WeiXinMPSDK/issues/1688#issue-430725840）

或者进一步提炼个ISenparcHttpClient接口，让用家可以在使用时加入更多自定义的配置和HttpClient扩展

一些相关的博文
https://www.nuget.org/packages/Microsoft.Extensions.Http.Polly/2.2.0
https://github.com/App-vNext/Polly/wiki/Polly-and-HttpClientFactory

**Comment by JeffreySu** [comment]
@lishewen 发布了新的预览版，已经是完整的依赖关系。

https://www.nuget.org/packages/Senparc.Weixin/6.4.5-preview1

**Comment by JeffreySu** [comment]
@lishewen 正在发布新的预览版，polly我会在下个正式版考虑加进去。

另外ISenparcHttpClient是个好主意！

**Comment by JeffreySu** [comment]
线上Demo已经发布，可以体验退款（需要用到证书）：

https://sdk.weixin.senparc.com/TenPayV3/ProductList

PS：微信内、微信外浏览器、PC浏览器，分别打开可以体验3种不同的支付过程。别忘了点退款 🤣

**Comment by lishewen** [comment]
> 线上Demo已经发布，可以体验退款（需要用到证书）：
> https://sdk.weixin.senparc.com/TenPayV3/ProductList
> PS：微信内、微信外浏览器、PC浏览器，分别打开可以体验3种不同的支付过程。别忘了点退款 🤣

PC Win10 Edge浏览器，点击第一个1分钱的选项，报502.3错误
对应url：https://sdk.weixin.senparc.com/TenPayV3/ProductItem?productId=1&hc=54647399

**Comment by JeffreySu** [comment]
@lishewen 这里测试正常，你重新从https://sdk.weixin.senparc.com/TenPayV3进去一下看看，后面的hc是为了控制生命周期的，会过期。

![image](https://user-images.githubusercontent.com/2281927/58302565-69c2bf00-7e1e-11e9-86fb-b843e7687976.png)

**Comment by lishewen** [comment]
现在是可以了

**Comment by JeffreySu** [comment]
最新稳定版已发布，谢谢各位的讨论和建议！

**Comment by anhuisunfei** [comment]
@JeffreySu 如果系统下有数百家租户、统一在Startup 注入的话、或者有更新这将是灾难

**Comment by JeffreySu** [comment]
@anhuisunfei 不明白你说的灾难是什么意思？如果你有数百个账号，理论上应该存在于数据库里面，for循环一下就行了，如果你担心效率，可以写一个线程单独执行，只要在调用前注册完毕即可。哪怕有几百个，并且用分布式缓存的话，也应该也可以在小几秒钟内注册完。

**Comment by Varorbc** [comment]
> @xcaptain 按照上述的思路做了，出现下面的错误：
> 
> ```cs
> 	Message：An error occurred while sending the request.
> 	StackTrace：
> 	InnerException：An error occurred while sending the request.
> 	InnerException.StackTrace：   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
>    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>    at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>    at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
>    at Senparc.CO2NET.HttpUtility.RequestUtility.HttpResponsePost(String url, CookieContainer cookieContainer, Stream postStream, Dictionary`2 fileDictionary, String refererUrl, Encoding encoding, String certName, Boolean useAjax, Dictionary`2 headerAddition, Int32 timeOut, Boolean checkValidationResult, String contentType)
>    at Senparc.CO2NET.HttpUtility.RequestUtility.HttpPost(String url, CookieContainer cookieContainer, Stream postStream, Dictionary`2 fileDictionary, String refererUrl, Encoding encoding, String certName, Boolean useAjax, Dictionary`2 headerAddition, Int32 timeOut, Boolean checkValidationResult, String contentType)
>    at Senparc.Weixin.TenPay.V3.TenPayV3.CertPost_NetCore(String mchId, String subMchId, String data, String url, Int32 timeOut)
>    at Senparc.Weixin.TenPay.V3.TenPayV3.Refund(TenPayV3RefundRequestData dataInfo, Int32 timeOut)
>    at Senparc.Weixin.MP.CoreSample.Controllers.TenPayV3Controller.Refund()
> ```
> 
> 这是当前Developer分支测试的结果（CO2NET新的preview2已经发布到nuget，并且已经引用），当前SDK还没有发布nuget，所以测试的话需要用源代码。注意一下 appsettings.json 里面在TenPayV3下面新增的几个字段，只需要设置这几个字段即可，不需要修改代码，都已经封装好了：
> 
> https://github.com/JeffreySu/WeiXinMPSDK/blob/527dc846fe3d3895df8d1eb3095eb059aa953bd6/src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPay/V3/TenPayV3InfoCollection.cs#L122

请问这个异常你们后面是怎么解决的，我也遇到相同的问题了
