### ISSUE TITLE
access_token 缓存总是在1分钟左右就消失了

### ISSUE THREAD

**Issue by vicenteyu** [JeffreySu/WeiXinMPSDK#1778]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
access_token 缓存总是在1分钟左右就消失了，没有使用Redis ，也没有使用Memcached ，原本设计就是这样吗？

##### 重现问题步骤（如果可以）

1. ...GetAccessToken
2. ...GetAccessTokenBags  持续刷新，观察accessTokenExpireTime 和 accessTokenResult ，一分钟左右消失。

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [x] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [x] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [ ] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
不太可能这么短时间内消失，使用内存缓存的话，取决于你的内存缓存的生命周期，比如重启了自然就没有了。

**Comment by vicenteyu** [comment]
那我重建一个项目，提供完整demo，这样可以定位到问题吗？

**Comment by JeffreySu** [comment]
可以，你可以直接用我们原始的纯净Demo试一下。

**Comment by vicenteyu** [comment]
我计划今天晚些时候用新项目的方式创建一次看看能否重现，之后会将所有代码附上。
感谢您的付出。

**Comment by vicenteyu** [comment]
已经确认是发布服务器的回收设定异常，在本地测试是正常的，问题就此关闭啦，抱歉。
