### ISSUE TITLE
公众号查询匹配菜单及删除菜单失败

### ISSUE THREAD

**Issue by limowithzx** [JeffreySu/WeiXinMPSDK#178]
查询匹配菜单调用接口url用的是删除菜单的url：
`var url = string.Format("https://api.weixin.qq.com/cgi-bin/menu/trymatch?access_token={0}", accessToken.AsUrlData());`
微信返回的数据是以menu为起始的数据：
```
public class MenuTryMatchResult : WxJsonResult
    {
        public MenuFull_ButtonGroup menu { get; set; }
    }
```
删除菜单的menuid中I应当小写：
```
var data = new
                {
                    menuid = menuId
                };
```
#169 好像遇到过

**Comment by JeffreySu** [comment]
URL及大小写错误已经修复
MP v13.7.1 fix bug：自定义菜单TryMatch方法中的url错误。
MP v13.7.2 fixbug：删除个性化菜单参数大小写问题。

非常感谢！
