### ISSUE TITLE
设置附近的小程序接口参数与官方文档不符

### ISSUE THREAD

**Issue by WangChuo** [JeffreySu/WeiXinMPSDK#1783]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
设置附近的小程序方法
Senparc.Weixin.WxOpen.AdvancedAPIs.WxApp.AddNearbyPoi(string accessTokenOrAppId, string relatedName, string relatedCredential, string relatedAddress, string relatedProofMaterial, int timeOut = 10000);
参数与官方文档不符，调用该方法返回异常：
错误代码：40097，说明：invalid args hint: [_DEcpa06403064]
是我找错方法了吗？

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 微信官方文档 URL
https://developers.weixin.qq.com/miniprogram/dev/api-backend/nearbyPoi.add.html

##### 微信官方文档快照（直接复制关键内容到下方）

access_token | string |   | 是 | 接口调用凭证
-- | -- | -- | -- | --
is_comm_nearby | string |   | 是 | 必填,写死为"1"
pic_list | string |   | 是 | 门店图片，最多9张，最少1张，上传门店图片如门店外景、环境设施、商品服务等，图片将展示在微信客户端的门店页。图片链接通过文档https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1444738729中的《上传图文消息内的图片获取URL》接口获取。必填，文件格式为bmp、png、jpeg、jpg或gif，大小不超过5M  pic_list是字符串，内容是一个json！
service_infos | string |   | 是 | 必服务标签列表 选填，需要填写服务标签ID、APPID、对应服务落地页的path路径，详细字段格式见下方示例
store_name | string |   | 是 | 门店名字 必填，门店名称需按照所选地理位置自动拉取腾讯地图门店名称，不可修改，如需修改请重现选择地图地点或重新创建地点
hour | string |   | 是 | 营业时间，格式11:11-12:12 必填
credential | string |   | 是 | 资质号 必填, 15位营业执照注册号或9位组织机构代码
address | string |   | 是 | 地址 必填
company_name | string |   | 是 | 主体名字 必填
qualification_list | string |   | 是 | 证明材料 必填  如果company_name和该小程序主体不一致，需要填qualification_list，详细规则见附近的小程序使用指南-如何证明门店的经营主体跟公众号或小程序帐号主体相关http://kf.qq.com/faq/170401MbUnim17040122m2qY.html
kf_info | string |   | 是 | 客服信息 选填，可自定义服务头像与昵称，具体填写字段见下方示例kf_info pic_list是字符串，内容是一个json！
poi_id | string |   | 是 | 如果创建新的门店，poi_id字段为空 如果更新门店，poi_id参数则填对应门店的poi_id 选填

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [x] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [x] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [ ] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [x] Visual Studio 2015
- [ ] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [ ] 服务器内存缓存（默认）
- [x] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/nearby-poi/nearbyPoi.add.html

**Comment by JeffreySu** [comment]
@WangChuo ： 已由 @mc7246  修复 #1824，您看一下。

**Comment by JeffreySu** [comment]
@WangChuo ： 已由 @CdLian 修复 #1824，您看一下。

**Comment by WangChuo** [comment]
好的，麻烦了

**Comment by JeffreySu** [comment]
@WangChuo 如果有问题可以继续反馈，没问题的话可以关闭这个issue，谢谢！
