### ISSUE TITLE
升级到最新版本，第三方平台ComponentContainer.GetComponentAccessToken调用异常

### ISSUE THREAD

**Issue by ccccccmd** [JeffreySu/WeiXinMPSDK#1786]
##### 问题描述
升级到最新版本 Senparc.Weixin.MP （由16.7.4.1 到 16.7.4.3）调用 `var componentAccessToken = ComponentContainer.GetComponentAccessToken(_componentAppid);`

发成异常，见最下方。回退到16.7.4.1 恢复正常

##### 发现问题的模块

- [ x] Senparc.Weixin.MP 版本：16.7.4.3
- [x ] Senparc.Weixin.Open 版本：4.5.2
- [x ] Senparc.Weixin.WxOpen 版本：3.4.2.3
- [x ] Senparc.Weixin.Cache.Redis 版本：2.5.5

##### 模块对应的 .net 版本
- [x] .net core 2.x

##### 开发环境
- [x] Visual Studio 2019

System.ArgumentNullException: Value cannot be null.\r\nParameter name: name\r\n   at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateClient(String name)\r\n   at Senparc.CO2NET.HttpUtility.SenparcHttpClient.GetInstanceByName(String httpClientName)\r\n   at Senparc.CO2NET.HttpUtility.RequestUtility.HttpPost_Common_NetCore(String url, HttpContent& hc, CookieContainer cookieContainer, Stream postStream, Dictionary`2 fileDictionary, String refererUrl, Encoding encoding, String certName, Boolean useAjax, Dictionary`2 headerAddition, Int32 timeOut, Boolean checkValidationResult, String contentType)\r\n   at Senparc.CO2NET.HttpUtility.RequestUtility.HttpResponsePost(String url, CookieContainer cookieContainer, Stream postStream, Dictionary`2 fileDictionary, String refererUrl, Encoding encoding, String certName, Boolean useAjax, Dictionary`2 headerAddition, Int32 timeOut, Boolean checkValidationResult, String contentType)\r\n   at Senparc.CO2NET.HttpUtility.RequestUtility.HttpPost(String url, CookieContainer cookieContainer, Stream postStream, Dictionary`2 fileDictionary, String refererUrl, Encoding encoding, String certName, Boolean useAjax, Dictionary`2 headerAddition, Int32 timeOut, Boolean checkValidationResult, String contentType)\r\n   at Senparc.CO2NET.HttpUtility.Post.PostGetJson[T](String url, CookieContainer cookieContainer, Stream fileStream, Encoding encoding, String certName, Boolean useAjax, Boolean checkValidationResult, Action`2 afterReturnText, Int32 timeOut)\r\n   at Senparc.Weixin.CommonAPIs.CommonJsonSend.Send[T](String accessToken, String urlFormat, Object data, CommonJsonSendType sendType, Int32 timeOut, Boolean checkValidationResult, JsonSetting jsonSetting)\r\n   at Senparc.Weixin.Open.ComponentAPIs.ComponentApi.GetComponentAccessToken(String componentAppId, String componentAppSecret, String componentVerifyTicket, Int32 timeOut)\r\n   at Senparc.Weixin.Open.Containers.ComponentContainer.GetComponentAccessTokenResult(String componentAppId, String componentVerifyTicket, Boolean getNewToken)\r\n

**Comment by JeffreySu** [comment]
这是因为您只升级了MP，没有升级CO2NET造成的，请同时升级到穷其依赖的CO2NET版本（包括CO2NET.APM）即可：https://www.nuget.org/packages/Senparc.CO2NET.APM/

另外新的preview版本已经提供了更好的性能，你可以试一下，很快会发布正式版。

**Comment by ccccccmd** [comment]
nuget升级的时候是连带着所有依赖一起升级的 。
![image](https://user-images.githubusercontent.com/10289019/58444964-148ff180-812d-11e9-9b60-9e0ab904024f.png)
这里并没有你说的CO2NET，我要手动找到这个升级？

**Comment by JeffreySu** [comment]
一般是会自动依赖的，但是如果不全部使用最新的，可能会导致依赖错误。

你应该是没有选中“包括预发行版”的选项。

![image](https://user-images.githubusercontent.com/2281927/58487020-800fa880-8199-11e9-92df-9e8e6ee6485e.png)

**Comment by ccccccmd** [comment]
好的，明白了，谢谢

**Comment by JeffreySu** [comment]
@ccccccmd 这个问题可能要看一下生产环境配置差异了，如果有可以沟通的内容可以这里继续跟进交流。
