### ISSUE TITLE
企业付款到零钱提示需要商户号，可是数据里已经有这个参数了

### ISSUE THREAD

**Issue by yueliuhun** [JeffreySu/WeiXinMPSDK#1816]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
企业付款到零钱提示需要商户号，可是数据里已经有这个参数了

##### 重现问题步骤（如果可以）

TenPayV3TransfersRequestData data 以下是data输出xml内容：

```
<xml>
<amount><![CDATA[100]]></amount>
<spbill_create_ip><![CDATA[xxx.xxx.xxx.xxx]]></spbill_create_ip>
<nonce_str><![CDATA[AB6DFC9AD151BED3C72AE67F6B542498]]></nonce_str>
<desc><![CDATA[测试]]></desc>
<partner_trade_no><![CDATA[149109511220190609022920234218]]></partner_trade_no>
<mch_id><![CDATA[1111111111]]></mch_id>
<re_user_name><![CDATA[]]></re_user_name>
<device_info><![CDATA[]]></device_info>
<check_name><![CDATA[NO_CHECK]]></check_name>
<sign><![CDATA[1E7E88FC5D6E43BB8C7237081E9652E0]]></sign>
<openid><![CDATA[oaW1wwzk9lfnHecN9Bj65zdGiOAI]]></openid>
<appid><![CDATA[wx04dd144444469244]]></appid>
</xml>
```

TransfersResult result = TenPayV3.Transfers(data, cert, certpassword, 10000);
请求后返回信息：

```
<xml>
<return_code><![CDATA[SUCCESS]]></return_code>
<return_msg><![CDATA[参数错误：必须填入商户号]]></return_msg>
<result_code><![CDATA[FAIL]]></result_code>
<err_code><![CDATA[PARAM_ERROR]]></err_code>
<err_code_des><![CDATA[参数错误：必须填入商户号]]></err_code_des>
</xml>
```

##### 微信官方文档 URL
https://pay.weixin.qq.com/wiki/doc/api/tools/mch_pay.php?chapter=14_2

##### 微信官方文档快照（直接复制关键内容到下方）

```
<xml> 

<mch_appid>wxe062425f740c30d8</mch_appid> 

<mchid>10000098</mchid> 

<nonce_str>3PG2J4ILTKCH16CQ2502SI8ZNMTM67VS</nonce_str> 

<partner_trade_no>100000982014120919616</partner_trade_no> 

<openid>ohO4Gt7wVPxIT1A9GjFaMYMiZY1s</openid> 

<check_name>FORCE_CHECK</check_name> 

<re_user_name>张三</re_user_name> 

<amount>100</amount> 

<desc>节日快乐!</desc> 

<spbill_create_ip>10.2.3.10</spbill_create_ip> 

<sign>C97BDBACF37622775366F38B629F45E3</sign> 

</xml>
```

##### 发现问题的模块

支付模块 V3 1.4.1

官方是mchid 和 传入的参数是mch_id  
这个问题吗？

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [x] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [ ] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：liuhun@qq.com

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by yueliuhun** [comment]
修改TenPayV3TransfersRequestData.cs 的内容如下即可，请更新下
```
     PackageRequestHandler.SetParameter("mch_appid", this.AppId); //公众账号ID
     PackageRequestHandler.SetParameter("mchid", this.MchId); //商户号
```

**Comment by yueliuhun** [comment]
需要修改的是两个地方：
appid也是错的

 ```
 PackageRequestHandler.SetParameter("mch_appid", this.AppId); //公众账号ID
     PackageRequestHandler.SetParameter("mchid", this.MchId); //商户号
```

**Comment by JeffreySu** [comment]
@yueliuhun 已经修改，请查看。

**Comment by yueliuhun** [comment]
已更新，测试正常

**Comment by JeffreySu** [comment]
感谢！
