### ISSUE TITLE
企业号获取不到成员的部门字段department

### ISSUE THREAD

**Issue by DemacL** [JeffreySu/WeiXinMPSDK#182]
请问企业号的部门字段怎么获取,直接从 Senparc.Weixin.QY.AdvancedAPIs.MailList.GetMemberResult userInfo = Senparc.Weixin.QY.AdvancedAPIs.MailListApi.GetMember(accessToken, result.UserId);获取到的userinfo中的部门字段是个int数组 不知道怎么取  先谢谢了

**Comment by JeffreySu** [comment]
> 获取到的userinfo中的部门字段是个int数组 不知道怎么取

您是已经获取到了int数组，不知道如何处理，还是不知道怎么获取到这个数组？

**Comment by DemacL** [comment]
恩  你好  现在已经获取到了 之前不知道怎么将数组转换成部门名称 现在 已经可以了 谢谢您和您的SDK

**Comment by JeffreySu** [comment]
欢迎随时提意见和建议，感谢您的支持：）
