### ISSUE TITLE
.net core公众号GetAccessToken

### ISSUE THREAD

**Issue by yueliuhun** [JeffreySu/WeiXinMPSDK#1821]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
.net core 2.2

`OAuthAccessTokenResult GetAccessToken(string appId, string secret, string code, string grantType = "authorization_code");`

这个方法在.net core一直提示错误：
Value cannot be null.Parameter name: services

1.已经获取到code
2.获取AccessToken时一直提示  Value cannot be null.Parameter name: services

==================
在webform asp.net mvc 都正常
只在.net core2.2  出现

如果我自己拼接请求 

`https://api.weixin.qq.com/sns/oauth2/access_token?appid={appid}&secret={secret}&code={CODE}&grant_type=authorization_code`

一点问题没有。。。
这是什么情况

我是从mvc 移植过来的。.net core 有不同的吗？

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [x] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

无

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
是因为没有按照要求进行启动注册，顺序严格参考Demo：

https://github.com/JeffreySu/WeiXinMPSDK/blob/master/Samples/Senparc.Weixin.MP.Sample.vs2017/Senparc.Weixin.MP.CoreSample/Startup.cs

上面是全的，里面不一定所有代码你都需要，看注释即可。
