### ISSUE TITLE
request:fail socket time out timeout

### ISSUE THREAD

**Issue by yorick520** [JeffreySu/WeiXinMPSDK#1829]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述

在真机上 会出现request:fail socket time out timeout ：100000 错误提示

![image](https://user-images.githubusercontent.com/26832111/59650009-2c501800-91b7-11e9-91ab-e8ee74eed6b0.png)

但是有时又正常。

![image](https://user-images.githubusercontent.com/26832111/59649998-24907380-91b7-11e9-8d7a-8517d5df3ea8.png)

我们在服务器nginx下 还接收到请求日志

![image](https://user-images.githubusercontent.com/26832111/59649985-1c383880-91b7-11e9-91f7-bdc16f9f680e.png)

并且会记录到此日志
[[[自动注册扩展缓存完成]]]
[2019/6/18 4:13:29]
[线程：3]
    注册总用时：0ms
自动扫描程序集：0个
扩展缓存：

[[[微信扩展缓存注册完成]]]
[2019/6/18 4:13:29]
[线程：3]
    微信扩展缓存注册总用时：5.8596ms
扩展缓存：Senparc.Weixin.Cache.LocalContainerCacheStrategy
Senparc.Weixin.Cache.Redis.RedisContainerCacheStrategy

[[[自动注册扩展缓存完成]]]
[2019/6/18 5:12:00]
[线程：3]
    注册总用时：0ms
自动扫描程序集：0个
扩展缓存：

[[[微信扩展缓存注册完成]]]
[2019/6/18 5:12:00]
[线程：3]
    微信扩展缓存注册总用时：4.883ms
扩展缓存：Senparc.Weixin.Cache.LocalContainerCacheStrategy
Senparc.Weixin.Cache.Redis.RedisContainerCacheStrategy

[[[自动注册扩展缓存完成]]]
[2019/6/18 6:21:30]
[线程：3]
    注册总用时：0ms
自动扫描程序集：0个
扩展缓存：

请问我一加缓存就报 request:fail socket time out timeout。 是什么原因。我确定我的redis是链接好的。

![image](https://user-images.githubusercontent.com/26832111/59651329-024d2480-91bc-11e9-919d-50e50e644d1e.png)

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [x] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
这个你要查自己的服务器连接的稳定问题了，比如防火墙等。
