### ISSUE TITLE
HTTP代理问题，

### ISSUE THREAD

**Issue by kingreatwill** [JeffreySu/WeiXinMPSDK#183]
你好，能否增加代理功能？公司使用代理才能访问外网，作为最强大weixinSDK建议加上此功能

**Comment by kingreatwill** [comment]
不好意思，里面有代理~~

**Comment by kingreatwill** [comment]
/// <summary>
        /// 从Url下载
        /// </summary>
        /// <param name="url"></param>
        /// <param name="stream"></param>
        public static void Download(string url, Stream stream)
        {
            //ServicePointManager.SecurityProtocol = SecurityProtocolType.Ssl3
            //ServicePointManager.ServerCertificateValidationCallback = new RemoteCertificateValidationCallback(CheckValidationResult);  

            WebClient wc = new WebClient();
            var data = wc.DownloadData(url);
            foreach (var b in data)
            {
                stream.WriteByte(b);
            }
        }
这个没有

**Comment by JeffreySu** [comment]
代理已经有了，可能有部分地方没有覆盖到，欢迎继续反馈，感谢！
