### ISSUE TITLE
有所有情况的返回值，还抛异常是否合理？

### ISSUE THREAD

**Issue by ChiakiYu** [JeffreySu/WeiXinMPSDK#1832]
##### 问题描述
TemplateApi.SendTemplateMessageAsync 只要不是成功就抛异常，那返回WxJsonResult的意义何在（玩了一下午的result，真没想过返回WxJsonResult的情况下还抛异常，WxJsonResult里明明有所有情况的code了）

##### 重现问题步骤（如果可以）

1. TemplateApi.SendTemplateMessageAsync 只要不是成功就抛异常，那返回WxJsonResult的意义何在

##### 发现问题的模块

- [x] Senparc.Weixin.WxOpen 版本：3.4.2.3

##### 模块对应的 .net 版本

- [x] .net core 2.x

##### 开发环境

- [x] Visual Studio 2017

##### 缓存环境

- [x] 服务器内存缓存（默认）

**Comment by ChiakiYu** [comment]
v6.4.8 加了配置了。。。
```
v6.4.8 添加 Config.ThrownWhenJsonResultFaild 属性，用于设置当 JsonResult 不为“成功”状态时，是否抛出异常，默认为 true
```

请问怎么用。。。

**Comment by JeffreySu** [comment]
只要设置 `Senparc.Weixin.Config.ThrownWhenJsonResultFaild = true`，如果返回结果不成功，会返回包含错误信息的 WxJsonResult 数据，而不是抛出异常。

默认抛出异常我认为是非常重要的，否则一些错误信息很容易被忽视，并且理论上你仍然需要对很多结果使用 if 判断其是否成功。并且，所抛出的异常会被 Senparc.CO2NET 的日志系统自动捕获并记录。

**Comment by ChiakiYu** [comment]
好的，可配置就方便多了。
感谢sdk。

**Comment by md-frank** [comment]
> 只要设置 `Senparc.Weixin.Config.ThrownWhenJsonResultFaild = true`，如果返回结果不成功，会返回包含错误信息的 WxJsonResult 数据，而不是抛出异常。
> 
> 默认抛出异常我认为是非常重要的，否则一些错误信息很容易被忽视，并且理论上你仍然需要对很多结果使用 if 判断其是否成功。并且，所抛出的异常会被 Senparc.CO2NET 的日志系统自动捕获并记录。

重要的是，抛出异常后异常信息里没有result信息，导致无法从异常里获取到具体失败原因。
