### ISSUE TITLE
微信 POST 请求发生错误！错误代码：40001

### ISSUE THREAD

**Issue by DekeYan** [JeffreySu/WeiXinMPSDK#1844]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
调用Senparc.Weixin.WxOpen.AdvancedAPIs.Template.TemplateApi.SendTemplateMessageAsync接口发送模板消息的时候偶尔会出现错误代码40001的错误

##### 发现问题的模块

- [x] Senparc.Weixin.MP 版本：2.5.1
- [x] Senparc.Weixin.WxOpen 版本：16.6.10
- [x] Senparc.Weixin.Cache.Redis 版本：3.3.6
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [x] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [4.0.11] 服务器内存缓存（默认）
- [x] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by DekeYan** [comment]
补充下
缓存在放在redis中的，大概第一次获取20分钟之后，就会出现错误
`        ErrorJsonResultException
        AccessTokenOrAppId：null
        URL：https://api.weixin.qq.com/cgi-bin/message/wxopen/template/send?access_token=23_0cBIzo5IQiCr0W0CWIIMHGLKlgmn23PUyx3Dk6M3aNBz1BTmS4Rg_qaH-MBAH3rBn3aY7nOaPnW__XWSjGkV9kZrcan8mTRGUHu4-kInz3_IYJVTBDSX0lr7raJ3wPCPndDSFQrGgrOvvKZ-MQLhACAQUP
        errcode：获取access_token时AppSecret错误或者access_token无效
        errmsg：invalid credential, access_token is invalid or not latest hint: [jDUuoa0771z211!]
`
就会一直报这个错误 无法发送出去模板消息，除非把缓存删除了重新获取

**Comment by JeffreySu** [comment]
@DekeYan 能否发一下你调用 SendTemplateMessageAsync 方法的代码？

**Comment by DekeYan** [comment]
` var wxOpenAppId = Senparc.Weixin.Config.SenparcWeixinSetting.WxOpenAppId;
                    var result = await TemplateApi.SendTemplateMessageAsync(wxOpenAppId, weappKey, data.TemplateId,data.Data, formId, data.Page);
                    if (result.errcode != Senparc.Weixin.ReturnCode.请求成功)
                        Logger.Error("发送小程序模板消息:"+result.ToString());
`

> @DekeYan 能否发一下你调用 SendTemplateMessageAsync 方法的代码？

**Comment by JeffreySu** [comment]
@DekeYan 我这边测试目前是稳定的，您可以关注“盛派网络小助手”小程序，主页上有一个【测试模板消息】可以体验，您也可以自己部署是一下。

**Comment by DekeYan** [comment]
我发现不是SendTemplateMessageAsync 这个接口的问题，是access_token的问题，没过10几分钟这个access_token就会过期了，但是redis中还是老的access_token，一直没找到原因

**Comment by JeffreySu** [comment]
@DekeYan 感觉应该是有多个地方在重复刷新AccessToken，正常情况下不会发生这样提前过期的情况。此问题还存在吗？
