### ISSUE TITLE
SnsApi.JsCode2Json code 无效时报异常

### ISSUE THREAD

**Issue by dodu2014** [JeffreySu/WeiXinMPSDK#1847]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
调用 Senparc.Weixin.WxOpen.AdvancedAPIs.Sns.SnsApi.JsCode2Json 获取openid和sessionkey时, code 无效时竟报异常, 不能正常返回带有错误码的对象, 还需自行容错

##### 重现问题步骤（如果可以）

1. 使用测试code(任意code)调用该接口
2. 程序异常. 需要自行 try... 才能正常给与反馈

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [x] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [x] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [x] Visual Studio 2019
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：dodu@live.cn

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
如果错误的话这里就是应该抛出异常的，如果你一定要沉默掉的话可以这样设置：

``` C#
Senparc.Weixin.Config.ThrownWhenJsonResultFaild = false;
```

然后自己对结果用 if 进行判断。

我们推荐的是保持原状，用 try/catch 处理。
