### ISSUE TITLE
微信请求发生错误！错误代码：42001，说明：access_token expired

### ISSUE THREAD

**Issue by zariczhu** [JeffreySu/WeiXinMPSDK#185]
请问我通过第三方平台接口Senparc.Weixin.Open.OAuthAPIs.GetAccessToken(string appId, string componentAppid, string componentAccessToken, string code, string grantType = "authorization_code")
去获取用户授权信息的时候，偶尔会发生上面的42001错误，请问是为什么呢，我的平台componentAccessToken会10分钟自动刷新一次，所以access_token expired 怎么会过期呢？

**Comment by JeffreySu** [comment]
如果你能确保代理请求的token是最新的，应该不会存在这个问题。你说的“偶尔”是个什么情况？

**Comment by JeffreySu** [comment]
如果你能确保代理请求的token是最新的，应该不会存在这个问题。你说的“偶尔”是个什么情况？

**Comment by zariczhu** [comment]
偶尔就是不是天天发生，但是可能过2天就发生一次，我网站刷新机制没有变化，每隔10分钟平台的componentAccessToken 和 授权的公众号的accesstoken都呼会自动刷新

**Comment by JeffreySu** [comment]
那应该是会自动刷新并且获取到最新的可用的token的，我这边也会持续关注一下，目前为止没有收到其他开发者这方面相同状况下的反馈。
如果您那边有截图或者其他详细信息，也欢迎提交上来，谢谢！

**Comment by jiehanlin** [comment]
![filehelper_1464536250599_4](https://cloud.githubusercontent.com/assets/15990729/15634445/58d6efb4-25f6-11e6-8d35-e8e50ab8595a.png)
最新版本，使用AccessTokenContainer.TryGetAccessToken(AppID, AppSecret)，会出现上面的情况。

**Comment by JeffreySu** [comment]
@jiehanlin 现在最新的版本还有这个情况吗？
