### ISSUE TITLE
企业微信获取token问题报错

### ISSUE THREAD

**Issue by zl2fxy** [JeffreySu/WeiXinMPSDK#1852]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
Senparc.Weixin.Work 版本：3.5.8
使用底层的getToken(CropId,Secret)方法出错

##### 重现问题步骤（如果可以）

1. ...代码CommonApi.GetToken
异常截图如下：[![ZRPvRJ.png](https://s2.ax1x.com/2019/07/11/ZRPvRJ.png)](https://imgchr.com/i/ZRPvRJ)
[![ZRide0.png](https://s2.ax1x.com/2019/07/11/ZRide0.png)](https://imgchr.com/i/ZRide0)
2. ...
版本信息如下图
[![ZRiULq.png](https://s2.ax1x.com/2019/07/11/ZRiULq.png)](https://imgchr.com/i/ZRiULq)
##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：3.5.8
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [x] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by zl2fxy** [comment]
[![ZR0Gh6.png](https://s2.ax1x.com/2019/07/11/ZR0Gh6.png)](https://imgchr.com/i/ZR0Gh6)

**Comment by JeffreySu** [comment]
上面这个错误因为没有按照Demo里面的启动代码进行注册，即使单元测试也需要注册的。

**Comment by zl2fxy** [comment]
直接使用最底层的代码去获取Token也需要注册么，我没有使用盛派提供的容器去管理token。另外我在使用3.3.8.1版本是可以正常的去获取Token

**Comment by JeffreySu** [comment]
如果你使用.net core，starup里面依赖注入的一些准备工作是必须的，其中包括了必要的注册。

**Comment by zl2fxy** [comment]
谢谢
