### ISSUE TITLE
[BUG] OAuthAccessTokenContainer.GetOAuthAccessTokenResult

### ISSUE THREAD

**Issue by hanabi1224** [JeffreySu/WeiXinMPSDK#1857]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
getNewToken默认值不应该为false, 不同的用户过来需要拿到自己对应的openId, 这里用appId做缓存不同的用户到同一个服务器上取到的是第一个被缓存的用户信息，全都乱了，至少应该把code做成cache key的一部分 appId + code 这样

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [x] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
是的，这个类目前还不建议使用，所以做了说明：

https://github.com/JeffreySu/WeiXinMPSDK/blob/0143c63fcc1a4347dd2a76476b457ae0d654617e/src/Senparc.Weixin.MP/Senparc.Weixin.MP/Containers/OAuthAccessTokenContainer.cs#L135

![image](https://user-images.githubusercontent.com/2281927/61304706-2ed87880-a81c-11e9-8cf7-df3d8a59cd54.png)

**Comment by JeffreySu** [comment]
新版本已经发布，感谢！
