### ISSUE TITLE
企业号和服务号JSSDKHelper 是不是不能通用? 

### ISSUE THREAD

**Issue by DemacL** [JeffreySu/WeiXinMPSDK#186]
您好 请问企业号和服务号JSSDKHelper 这个类是不是分开的, 不能通用了?   我用企业号调用之前服务号的js分享接口  提示错误代码：40125，说明：invalid appsecret,  先谢谢您了

**Comment by JeffreySu** [comment]
一直都是不通用的，使用的APPID和SECRET也都没啥关系。
