### ISSUE TITLE
关于缓存的一个问题

### ISSUE THREAD

**Issue by DekeYan** [JeffreySu/WeiXinMPSDK#1868]
##### 问题描述
```
[[[自动注册扩展缓存完成]]]
[2019/07/22 14:35:02.5714]
[线程：1]
注册总用时：0.0021ms
自动扫描程序集：0个
扩展缓存：

[[[系统日志]]]
[2019/07/22 14:35:02.5844]
[线程：1]
系统启动

[[[微信扩展缓存注册完成]]]
[2019/07/22 14:35:02.5933]
[线程：1]
微信扩展缓存注册总用时：0.5459ms
扩展缓存：Senparc.Weixin.Cache.LocalContainerCacheStrategy
Senparc.Weixin.Cache.Redis.RedisContainerCacheStrategy

```

如上面的日志。扩展缓存有Senparc.Weixin.Cache.LocalContainerCacheStrategy，而我现在是用Redis缓存，这样会有影响吗？

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [x] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
不会有影响。
