### ISSUE TITLE
引用Senparc.Weixin.MP报错

### ISSUE THREAD

**Issue by wtujvk** [JeffreySu/WeiXinMPSDK#1877]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 重现问题步骤（如果可以）

1. 使用nuget包引用Senparc.Weixin.MP 16.7.10
2. package.config
 <package id="Senparc.CO2NET" version="0.8.3" targetFramework="net46" />
  <package id="Senparc.CO2NET.APM" version="0.4.1.1" targetFramework="net46" />
  <package id="Senparc.NeuChar" version="0.7.4" targetFramework="net46" />
  <package id="Senparc.NeuChar.App" version="0.5.4" targetFramework="net46" />
  <package id="Senparc.Weixin" version="6.4.11" targetFramework="net46" />
  <package id="Senparc.Weixin.MP" version="16.7.10" targetFramework="net461" />
![image](https://user-images.githubusercontent.com/17868266/62529441-3a461f00-b871-11e9-8fa7-e12a570ae50e.png)

但是引用的Senparc.NeuChar 是0.7.4.0版本，已经包含在引用中还是提示错误。

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [x ] Senparc.Weixin.MP 版本：16.7.10
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5 ()
- [x] .net 4.6.1
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [ ] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [x] Visual Studio 2019
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
1、看一下所有dll有没有统一升级到最新版本。
2、看一下有没有引用了非盛派官方的dll（尤其是这个：https://www.nuget.org/packages/Senparc.Weixin.MP.Mvc）。
3、看一下你代码引用的命名空间是否正确。
