### ISSUE TITLE
Senparc.Weixin.MP升级后很卡（16.7.12）

### ISSUE THREAD

**Issue by wtujvk** [JeffreySu/WeiXinMPSDK#1878]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
Senparc.Weixin.MP从14.10.3升级到16.7.12后很卡。

##### 重现问题步骤（如果可以）

1. 旧包 ：

  package id="Senparc.Weixin" version="4.20.2" targetFramework="net46" 
  package id="Senparc.Weixin.MP" version="14.10.3" targetFramework="net46" 

2. 新的引用：
 package id="Senparc.CO2NET" version="0.8.3" targetFramework="net46" 
  package id="Senparc.CO2NET.APM" version="0.4.1.1" targetFramework="net46" 
  package id="Senparc.NeuChar" version="0.7.4" targetFramework="net46" 
  package id="Senparc.NeuChar.App" version="0.5.4" targetFramework="net46" 
  package id="Senparc.Weixin" version="6.4.11" targetFramework="net46" 
  package id="Senparc.Weixin.MP" version="16.7.12" targetFramework="net46" 
3. 注册
 var senparcSetting = new SenparcSetting(false);
  var senparcWeixinSetting = new SenparcWeixinSetting();
  var register = RegisterService.Start(senparcSetting).UseSenparcGlobal(false).UseSenparcWeixin(senparcWeixinSetting, senparcSetting);
4. 在接入公众号或者修改公众号的时候调用方法
AccessTokenContainer.TryGetAccessToken(appId, appSecret, true)
这个时候使用更新的包很卡（使用旧版的很流畅）。
 这里主要用来判断appId,和appSecret是否正确，并且重新注册 appId,和appSecret。
##### 发现问题的模块

- [x] Senparc.Weixin 版本：6.4.11
- [x] Senparc.Weixin.MP 版本：16.7.12
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [x] .net 4.6.1
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [ ] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [x] Visual Studio 2019
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：
1170971516@qq.com
（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by wtujvk** [comment]
AccessTokenContainer.Register 改为了RegisterAsync ，使用了异步。
但是使用异步外部捕获不了里面的异常。可能会导致线程死掉。

**Comment by JeffreySu** [comment]
你的意思是同步的方法卡，异步的不卡吗？

**Comment by wtujvk** [comment]
AccessTokenContainer.TryGetAccessToken(appId, appSecret, getNewToken)
我这边使用的是同步的方法，没有调用异步的方法。
改用低版本 就好了。

**Comment by JeffreySu** [comment]
你用一下异步方法 TryGetAccessTokenAsync 试试看是否有一样的表现？

**Comment by wtujvk** [comment]
已改用 Senparc.Weixin.MP 16.6.15

**Comment by wtujvk** [comment]
在.netcore2.2 中使用16.7.12版本调用 （接入公众号，新加入时调用）
 AccessTokenContainer.TryGetAccessToken(appId, appSecret, getNewToken);

 抛出了异常，The type initializer for 'Nested' threw an exception
at Senparc.CO2NET.Cache.CacheStrategyFactory.GetObjectCacheStrategyInstance()
   at Senparc.Weixin.Containers.BaseContainer`1.get_Cache()
   at Senparc.Weixin.Containers.BaseContainer`1.CheckRegistered(String shortKey)
   at Senparc.Weixin.MP.Containers.AccessTokenContainer.TryGetAccessToken(String appId, String appSecret, Boolean getNewToken)
   at 

![image](https://user-images.githubusercontent.com/17868266/63394496-83aa7880-c3f2-11e9-9d7d-7b1a0142b156.png)

**Comment by JeffreySu** [comment]
@wtujvk 这个错误有两种可能：
1、dll基础库版本不匹配（从nuget自动升级的话不会有这个问题）；
2、startup.cs中的启动代码没有按照Demo中的要求设置（包括顺序也不要随意颠倒）。

**Comment by wtujvk** [comment]
使用官方demo （Senparc.Weixin.MP.Sample）能够重现问题。
组件 版本：
 package id="Senparc.CO2NET" version="0.8.9" targetFramework="net45" 
  package id="Senparc.CO2NET.APM" version="0.4.2" targetFramework="net45" 
  package id="Senparc.CO2NET.Cache.Memcached" version="3.3.3" targetFramework="net45" 
  package id="Senparc.CO2NET.Cache.Redis" version="3.5.3" targetFramework="net45" 
  package id="Senparc.CO2NET.Cache.Redis.RedLock" version="2.2.3" targetFramework="net45" 
  package id="Senparc.NeuChar" version="0.7.5" targetFramework="net45" 
  package id="Senparc.NeuChar.App" version="0.5.5" targetFramework="net45" 
  package id="StackExchange.Redis" version="1.2.6" targetFramework="net45" 
其他： appid和appSecret 不是使用的web.config里面的。此appid未注册。
 Controller中的代码 (首次调用传true, 以后传false)：
      public ActionResult Test()
        {
            Stopwatch sp = new Stopwatch();
            var appId = "非config里的appid";
            var appSecret = "不是config里面的appSecret";
            sp.Start();
            string message = string.Empty;
            try
            {
                AccessTokenContainer.TryGetAccessToken(appId, appSecret, true);
            }
            catch (Exception e)
            {
                message = e.Message;
            }
            sp.Stop();
            return Content($"消息：{message}。耗时 {sp.ElapsedMilliseconds}");
        }
网站一直未响应，在转圈。。。

**Comment by JeffreySu** [comment]
@wtujvk 好的，稍后我会测试一下，感谢反馈。

**Comment by JeffreySu** [comment]
@wtujvk 我发现之前我已经做过一个测试了，就在 HomeController 里面，当时就是能够测试通过的：

https://github.com/JeffreySu/WeiXinMPSDK/blob/76fc03ab3d99a954b441fa673a56fa051edbdd88/Samples/Senparc.Weixin.MP.Sample/Senparc.Weixin.MP.Sample/Controllers/HomeController.cs#L138

如果从未注册过确实重现了问题，调试状态下是可以的，但是单独运行就会卡主，所以估计是线程Wait() 锁死的问题，我来检查一下。

**Comment by JeffreySu** [comment]
@wtujvk 已经发布了新版本，将可能会造成死锁的地方修改了一下，您可以试一下最新的版本：

https://github.com/JeffreySu/WeiXinMPSDK/blob/cc18a1e77b24ce14b99e813193a51322f7b8beb9/Samples/Senparc.Weixin.MP.Sample/Senparc.Weixin.MP.Sample/Controllers/HomeController.cs#L138

**Comment by wtujvk** [comment]
异常详细信息
此appId（wx4a3135586bxxx）尚未注册，请先使用AccessTokenContainer.Register完成注册（全局执行一次即可）！
TryGetAccessToken不是会自动注册吗 ？ (如果不存在将自动注册 )
日志信息 此appId尚未注册，请先使用JsApiTicketContainer.Register完成注册（全局执行一次即可），为什么又是要使用JsApiTicketContainer 注册 ？？

**Comment by wtujvk** [comment]
首次调用报这个错。第二次调用 就能成功。
TryGetAccessToken不是会自动注册么 ？

**Comment by wtujvk** [comment]
TryGetAccessToken， 调用这个方法相关的业务需求：
1. 没有注册的appid,  需要进行注册。 getNewToken =true
2. 有注册，但是appsecret可能有修改， 需要更新accessToken。 getNewToken =true
3. 获取accessToken 。 getNewToken =false

**Comment by JeffreySu** [comment]
@wtujvk 如果用TryGetAccessToken，提供了appId和appSecret，应该是不会出现这个异常的，只有从未注册过，或者TryGet过，然后直接使用appId调用高级接口，才会这样。

最新代码的Demo您测试了吗？

https://github.com/JeffreySu/WeiXinMPSDK/blob/76fc03ab3d99a954b441fa673a56fa051edbdd88/Samples/Senparc.Weixin.MP.Sample/Senparc.Weixin.MP.Sample/Controllers/HomeController.cs#L138

**Comment by wtujvk** [comment]
有时候还是会卡住。

**Comment by JeffreySu** [comment]
> 异常详细信息
> 此appId（wx4a3135586bxxx）尚未注册，请先使用AccessTokenContainer.Register完成注册（全局执行一次即可）！
> TryGetAccessToken不是会自动注册吗 ？ (如果不存在将自动注册 )
> 日志信息 此appId尚未注册，请先使用JsApiTicketContainer.Register完成注册（全局执行一次即可），为什么又是要使用JsApiTicketContainer 注册 ？？

AccessTokenContainer里面自动包含了为JsApiTicketContainer 的注册。

**Comment by JeffreySu** [comment]
> 有时候还是会卡住。

有什么规律吗？

**Comment by wtujvk** [comment]
使用redis缓存，当清除（Flush）缓存后，访问http://localhost:65395/home/TryGetAccessTokenTest
就卡住了。当redis缓存重建好了后，页面还是在转圈，没有响应。

**Comment by JeffreySu** [comment]
> 当redis缓存重建好了后，页面还是在转圈，没有响应。

这个重建过程和状态的详细情况可以说一下吗？

**Comment by wtujvk** [comment]
启动后：
1. 在redis客户端 清除缓存 （Flush DataBase）。
2. 访问页面 /Home/TryGetAccessTokenTest (调用方法TryGetAccessToken)
3. 查看redis 已生成Senparc.Weixin.MP.Containers.AccessTokenBag缓存。
其他的缓存（Senparc.Weixin.MP.Containers.JsApiTicketBag:*，Senparc.Weixin.MP.Containers.OAuthAccessTokenBag）没生成缓存。
  页面一直在响应中。
打开新的tab访问这个页面也是在 正在等待存入缓存
页面显示耗时200ms左右，但是页面刷新的时间需要几秒，有时甚至一直在响应中。

**Comment by JeffreySu** [comment]
@wtujvk 已经找到了原因，之前统一升级异步方法的时候，唯独在 AccessTokenContainer.RegisterAsync() 方法中，用于防止线程死锁的代码 `.ConfigureAwait(false)` 没有加，所以导致了上述奇怪的情况，非常感谢坚持反馈问题和排错！

已经发布版本 Senparc.Weixin.MP v16.7.14，如有问题欢迎继续反馈 🤝

**Comment by JeffreySu** [comment]
@wtujvk 继续发布了 v16.7.15，解决了另外一个注册问题（在 TryGetAccessToken() 方法中提示 appId 未注册）。关于卡住的问题，如果有使用新版本欢迎给一个反馈 😄

**Comment by wtujvk** [comment]
.net46
不知道升级后 MessageHandler 里面有没有更改。
Senparc.Weixin.MP 16.7.13.0 编译正常。Senparc.Weixin.MP 16.7.14(含)以上的版本编译报错。
升级到 Senparc.Weixin.MP version=16.7.16，编译 报错：
CS0012	类型MessageHandler<,,>在未引用的程序集中定义。必须添加对程序集Senparc.NeuChar, Version=0.7.5.0, Culture=neutral, PublicKeyToken=null”的引用

**Comment by JeffreySu** [comment]
@wtujvk 这一块没有改过，你可以重新用nuget安装一下，会自动依赖最新的库。

**Comment by wtujvk** [comment]
项目是mvc分层架构， 使用 WebActivatorEx 来初始化微信的。是否跟这个有关 ？
[assembly: PreApplicationStartMethod(typeof(ModuleStartup), nameof(ModuleStartup.PreApplicationStart))]

**Comment by JeffreySu** [comment]
@wtujvk 我不清楚你里面的原理，总之项目代码的执行顺序需要按照Demo来，如果这里影响了，可能有部分代码你需要提前。
