### ISSUE TITLE
错别勘误

### ISSUE THREAD

**Issue by iXinwei** [JeffreySu/WeiXinMPSDK#1881]
#### “此库用途.2....Scoket”处Scoket应为Socket。

**Comment by JeffreySu** [comment]
感谢提醒！

**Comment by JeffreySu** [comment]
@iXinwei 请问你发现的错别字是在是在第几章第几节？

**Comment by iXinwei** [comment]
不好意思，让你多虑了。其实只是一个无伤大雅的错别，在WxOpen的readme里##此库用途中的WebSocket拼写错误。

https://github.com/JeffreySu/WxOpen

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Jeffrey Su <notifications@github.com>
发送时间: Sunday, August 18, 2019 12:04:25 AM
收件人: JeffreySu/WeiXinMPSDK <WeiXinMPSDK@noreply.github.com>
抄送: Xinwei Zhang <zhang010917@outlook.com>; Mention <mention@noreply.github.com>
主题: Re: [JeffreySu/WeiXinMPSDK] 错别勘误 (#1881)


@iXinwei<https://github.com/iXinwei> 请问你发现的错别字是在是在第几章第几节？

―

**Comment by JeffreySu** [comment]
@iXinwei 我还以为是图书里面的，所以找了半天没找到 😄 
当前项目对应的注释已经修正，今天将会同步到 https://github.com/JeffreySu/WxOpen，感谢提醒！
