### ISSUE TITLE
尝试引入redis缓存，报错未能加载文件或程序集“Senparc.CO2NET, Version=xx

### ISSUE THREAD

**Issue by wtujvk** [JeffreySu/WeiXinMPSDK#1886]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
引入senparc的redis相关组件
Senparc.Weixin.Cache.Redis 后报错。未能加载文件或程序集Senparc.CO2NET，但实际上是有对应版本引用的。
##### 重现问题步骤（如果可以）

1. 未引入redis相关组件前是正常的。
2. 引用Senparc.Weixin.Cache.Redis组件2.5.2.0 后启用报错，未能加载文件或程序集0.5.2.0。
packages部分文件： 
  <package id="Senparc.CO2NET" version="0.5.2" targetFramework="net46" />
  <package id="Senparc.CO2NET.APM" version="0.2.5" targetFramework="net46" />
  <package id="Senparc.CO2NET.Cache.Redis" version="3.4.2" targetFramework="net46" />
  <package id="Senparc.CO2NET.Cache.Redis.RedLock" version="2.1.0" targetFramework="net46" />
  <package id="Senparc.NeuChar" version="0.6.4" targetFramework="net46" />
  <package id="Senparc.Weixin" version="6.3.10.2" targetFramework="net46" />
  <package id="Senparc.Weixin.Cache.Redis" version="2.5.2" targetFramework="net46" />
  <package id="Senparc.Weixin.MP" version="16.6.15" targetFramework="net46" />
  <package id="StackExchange.Redis" version="1.2.6" targetFramework="net46" />

##### 发现问题的模块

- [ x] Senparc.Weixin 版本：6.3.10.2
- [ x] Senparc.Weixin.MP 版本：16.6.15.0
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [x] Senparc.Weixin.Cache.Redis 版本：  2.5.1.0
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：
  Senparc.CO2NET 0.5.2.0
  Senparc.CO2NET.APM 0.2.5.0
  Senparc.CO2NET.Cache.Redis  3.4.2.0
  Senparc.CO2NET.Cache.Redis.RedLock  2.1.0.0
  Senparc.NeuChar 0.6.4.0
 StackExchange.Redis  1.2.6.0

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [x] .net 4.6
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [ ] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [x] Visual Studio 2019

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [x] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by wtujvk** [comment]
<package id="Senparc.CO2NET" version="0.5.2" targetFramework="net46" />
  <package id="Senparc.CO2NET.APM" version="0.2.5" targetFramework="net46" />
  <package id="Senparc.CO2NET.Cache.Redis" version="3.4.2" targetFramework="net46" />
  <package id="Senparc.CO2NET.Cache.Redis.RedLock" version="2.1.0" targetFramework="net46" />
  <package id="Senparc.NeuChar" version="0.6.4" targetFramework="net46" />
  <package id="Senparc.Weixin" version="6.3.10.2" targetFramework="net46" />
  <package id="Senparc.Weixin.Cache.Redis" version="2.5.2" targetFramework="net46" />
  <package id="Senparc.Weixin.MP" version="16.6.15" targetFramework="net46" />
  <package id="StackExchange.Redis" version="1.2.6" targetFramework="net46" />

**Comment by wtujvk** [comment]
package id="Senparc.CO2NET" version="0.5.2" targetFramework="net46" 
  package id="Senparc.CO2NET.APM" version="0.2.5" targetFramework="net46" 
  package id="Senparc.CO2NET.Cache.Redis" version="3.4.2" targetFramework="net46" 
  package id="Senparc.CO2NET.Cache.Redis.RedLock" version="2.1.0" targetFramework="net46" 
  package id="Senparc.NeuChar" version="0.6.4" targetFramework="net46" 
  package id="Senparc.Weixin" version="6.3.10.2" targetFramework="net46" />
  package id="Senparc.Weixin.Cache.Redis" version="2.5.2" targetFramework="net46" 
  package id="Senparc.Weixin.MP" version="16.6.15" targetFramework="net46" 
  package id="StackExchange.Redis" version="1.2.6" targetFramework="net46"

**Comment by wtujvk** [comment]
未能加载文件或程序集“Senparc.CO2NET, Version=0.5.2.0, Culture=neutral, PublicKeyToken=631468bce49458f1”或它的某一个依赖项。系统找不到指定的文件

**Comment by JeffreySu** [comment]
看一下是不是 Senparc.CO2NET 引用的其他库没有还原成功。

**Comment by JeffreySu** [comment]
另外看这按本个比较旧了，建议更新到最新的比较好测试。

**Comment by wtujvk** [comment]
使用更新的版本ok。
  package id="Senparc.CO2NET" version="0.8.9" targetFramework="net46" 
  package id="Senparc.CO2NET.APM" version="0.4.2" targetFramework="net46" 
  package id="Senparc.CO2NET.Cache.Redis" version="3.5.3" targetFramework="net46" 
  package id="Senparc.CO2NET.Cache.Redis.RedLock" version="2.2.3" targetFramework="net46" 
  package id="Senparc.NeuChar" version="0.7.5" targetFramework="net46" 
  package id="Senparc.NeuChar.App" version="0.5.5" targetFramework="net46" 
  package id="Senparc.Weixin" version="6.4.13" targetFramework="net46" 
  package id="Senparc.Weixin.Cache.Redis" version="2.5.10" targetFramework="net46" 
  package id="Senparc.Weixin.MP" version="16.7.14" targetFramework="net46" 
  package id="StackExchange.Redis" version="1.2.6" targetFramework="net46"
