### ISSUE TITLE
使用redis缓存Senparc.Weixin.Cache2.5.10里面的引用版本不对

### ISSUE THREAD

**Issue by wtujvk** [JeffreySu/WeiXinMPSDK#1889]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
启用调试web程序报错，提示未能找到Senparc.CO2NET.Cache.Redis.RedLock, Version=2.2.1.1。但其实引用的是2.2.3
未能加载文件或程序集“Senparc.CO2NET.Cache.Redis.RedLock, Version=2.2.1.1, Culture=neutral, PublicKeyToken=631468bce49458f1”或它的某一个依赖项。系统找不到指定的文件。

##### 重现问题步骤（如果可以）

1.  Senparc.CO2NET.Cache.Redis等升级到最新版本。
2.  启动IIS Express直接崩溃。启用调试web程序报错，提示未能找到Senparc.CO2NET.Cache.Redis.RedLock, Version=2.2.1.1。但其实引用的是2.2.3
未能加载文件或程序集“Senparc.CO2NET.Cache.Redis.RedLock, Version=2.2.1.1, Culture=neutral, PublicKeyToken=631468bce49458f1”或它的某一个依赖项。系统找不到指定的文件。

  package id="Senparc.CO2NET" version="0.8.9" targetFramework="net46" 
  package id="Senparc.CO2NET.APM" version="0.4.2" targetFramework="net46" 
  package id="Senparc.CO2NET.Cache.Redis" version="3.5.3" targetFramework="net46" 
  package id="Senparc.CO2NET.Cache.Redis.RedLock" version="2.2.3" targetFramework="net46" 
  package id="Senparc.NeuChar" version="0.7.5" targetFramework="net46" 
  package id="Senparc.NeuChar.App" version="0.5.5" targetFramework="net46" 
  package id="Senparc.Weixin" version="6.4.13" targetFramework="net46" 
  package id="Senparc.Weixin.Cache.Redis" version="2.5.10" targetFramework="net46" 
  package id="Senparc.Weixin.MP" version="16.7.13" targetFramework="net46" 
  package id="StackExchange.Redis" version="1.2.6" targetFramework="net46"

![image](https://user-images.githubusercontent.com/17868266/63643767-e6f61c80-c70a-11e9-854a-70150d5fd392.png)
通过反编译发现  Senparc.Weixin.Cache.Redis2.5.10.0 里面的Senparc.CO2NET.Cache.Redis.RedLock, Version=2.2.1.1
![image](https://user-images.githubusercontent.com/17868266/63643770-fbd2b000-c70a-11e9-8c42-fa9a7c364531.png)
nuget包的相关依赖。
Senparc.Weixin.Cache2.5.10
Senparc.CO2NET.Cache.Redis (>= 3.5.3)

Senparc.CO2NET.Cache.Redis3.5.3
Senparc.CO2NET.Cache.Redis.RedLock (>= 2.2.3)

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [x ] Senparc.Weixin.MP 版本：16.7.13
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [x] .net 4.6
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [x] Visual Studio 2019
- [ ] 其他：

##### 缓存环境

- [ ] 服务器内存缓存（默认）
- [x ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
Senparc.CO2NET.Cache.Redis v3.5.3：https://www.nuget.org/packages/Senparc.CO2NET.Cache.Redis/3.5.3

引用的确实是 Senparc.CO2NET.Cache.Redis.RedLock v2.2.3：
![image](https://user-images.githubusercontent.com/2281927/63651720-8a3a4680-c78a-11e9-85df-367f7ad472f2.png)

程序里面也是对的：
![image](https://user-images.githubusercontent.com/2281927/63651738-b786f480-c78a-11e9-86d2-7db48275b914.png)

可能出现 RedLock v2.2.1.1 的地方是 .net 4.5 的 Sample 项目里面目前引用的还是旧版本的（现在更新基本上都集中在 vs2017 这个新的 Sample 里面了），我更新一下您看一下是不是这个 Sample 的 Web 项目的引用问题，nuget 上面的依赖显示是正常的，不太可能出问题。

感谢反馈！

**Comment by wtujvk** [comment]
更新dll后，在mvc demo使用如下版本，引用版本正常。可运行。
 <package id="Senparc.CO2NET" version="0.8.9" targetFramework="net46" 
  <package id="Senparc.CO2NET.APM" version="0.4.2" targetFramework="net46" 
  <package id="Senparc.CO2NET.Cache.Memcached" version="3.3.3" targetFramework="net46" 
  <package id="Senparc.CO2NET.Cache.Redis" version="3.5.3" targetFramework="net46" 
  <package id="Senparc.CO2NET.Cache.Redis.RedLock" version="2.2.3" targetFramework="net46" 
  <package id="Senparc.NeuChar" version="0.7.5" targetFramework="net46" 
  <package id="Senparc.NeuChar.App" version="0.5.5" targetFramework="net46" 
  package id="Senparc.Weixin" version="6.4.13" targetFramework="net46" 
  package id="Senparc.Weixin.Cache.Redis" version="2.5.10" targetFramework="net46" 
  package id="Senparc.Weixin.MP" version="16.7.13" targetFramework="net46" 
  package id="StackExchange.Redis" version="1.2.6" targetFramework="net46"
