### ISSUE TITLE
关于生成卡券二维码的问题

### ISSUE THREAD

**Issue by hello2008zj** [JeffreySu/WeiXinMPSDK#189]
生成卡券二维码函数原型与最新微信内容不匹配，主要增加以下内容：

1、增加参数：string outer_id=null //自定义应用场景ID，int型
2、修改代码：
      A、outer_id = outer_id //增加场景ID，int型

      B、 //***********原来内容 begin*******************
                //var jsonSettingne = new JsonSetting(true);
                //***********原来内容 end*******************

               //***********增加内容 begin*******************
                var jsonSetting = new JsonSetting(true, null,
                   new List<Type>()
                   {
                        //typeof (Modify_Msg_Operation),
                        //typeof (CardCreateInfo),
                        data.action_info.card.GetType()//过滤Modify_Msg_Operation主要起作用的是这个
                   });
               //***********增加内容 end*******************

修改后函数如下：

/// <summary>
        /// 生成卡券二维码
        /// 获取二维码ticket 后，开发者可用ticket 换取二维码图片。换取指引参考：http://mp.weixin.qq.com/wiki/index.php?title=生成带参数的二维码
        /// </summary>
        /// <param name="accessTokenOrAppId"></param>
        /// <param name="cardId">卡券ID</param>
        /// <param name="code">指定卡券code 码，只能被领一次。use_custom_code 字段为true 的卡券必须填写，非自定义code 不必填写。</param>
        /// <param name="openId">指定领取者的openid，只有该用户能领取。bind_openid 字段为true 的卡券必须填写，非自定义openid 不必填写。</param>
        /// <param name="expireSeconds">指定二维码的有效时间，范围是60 ~ 1800 秒。不填默认为永久有效。</param>
        /// <param name="isUniqueCode">指定下发二维码，生成的二维码随机分配一个code，领取后不可再次扫描。填写true 或false。默认false。</param>
        /// <param name="balance">红包余额，以分为单位。红包类型必填（LUCKY_MONEY），其他卡券类型不填。</param>
        /// <param name="timeOut">代理请求超时时间（毫秒）</param>
        /// <returns></returns>
        public static CreateQRResultJson CreateQR(string accessTokenOrAppId, string cardId, string code = null,
                                                  string openId = null, string expireSeconds = null,
                                                  bool isUniqueCode = false, string balance = null,string outer_id=null,
                                                  int timeOut = Config.TIME_OUT)
        {
            return ApiHandlerWapper.TryCommonApi(accessToken =>
            {
                var urlFormat = string.Format("https://api.weixin.qq.com/card/qrcode/create?access_token={0}", accessToken.AsUrlData());

                var data = new
                {
                    action_name = "QR_CARD",
                    action_info = new
                    {
                        card = new
                        {
                            card_id = cardId,
                            code = code,
                            openid = openId,
                            expire_seconds = expireSeconds,
                            is_unique_code = false,
                            balance = balance,
                           outer_id = outer_id //增加场景ID，int型
                        }
                    }
                };

                //***********原来内容 begin*******************
                //var jsonSettingne = new JsonSetting(true);
                //***********原来内容 end*******************

               //***********增加内容 begin*******************
                var jsonSetting = new JsonSetting(true, null,
                   new List<Type>()
                   {
                        //typeof (Modify_Msg_Operation),
                        //typeof (CardCreateInfo),
                        data.action_info.card.GetType()//过滤Modify_Msg_Operation主要起作用的是这个
                   });
               //***********增加内容 end*******************

                return CommonJsonSend.Send<CreateQRResultJson>(null, urlFormat, data, timeOut: timeOut, jsonSetting: jsonSetting);

            }, accessTokenOrAppId);
        }

**Comment by JeffreySu** [comment]
感谢！上面的代码已经测试通过了吗？

**Comment by JeffreySu** [comment]
已经升级到v13.7.3中，您可以看一下。谢谢！

**Comment by JeffreySu** [comment]
对了，此方法还没有做测试，目前已经正式发布，如果测试通过欢迎反馈一下，非常感谢:)
