### ISSUE TITLE
调用TryGetAccessToken，报错 当前扩展缓存策略没有进行注册

### ISSUE THREAD

**Issue by wtujvk** [JeffreySu/WeiXinMPSDK#1892]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
Senparc.Weixin.MP version=16.7.14此版本有此问题，16.6.15 无此问题TryGetAccessToken能使用（redis缓存未验证）。
使用Redis缓存，调用TryGetAccessToken方法报错，当前扩展缓存策略没有进行注册：Senparc.Weixin.Cache.ContainerCacheStrategyDomain，Senparc.CO2NET.Cache.Redis.RedisObjectCacheStrategy，解决方案请参考：https://weixin.senparc.com/QA-551

##### 重现问题步骤（如果可以）
1.  使用内存缓存，调用TryGetAccessToken， 此appId（wx4axxx）尚未注册，请先使用AccessTokenContainer.Register完成注册（全局执行一次即可）。
改用方法 AccessTokenContainer.RegisterAsync(appId, appSecret)和 AccessTokenContainer.GetAccessToken(appId, getNewToken) 后正常。
2. 使用Redis缓存，报错： 当前扩展缓存策略没有进行注册：Senparc.Weixin.Cache.ContainerCacheStrategyDomain，Senparc.CO2NET.Cache.Redis.RedisObjectCacheStrategy，解决方案请参考：https://weixin.senparc.com/QA-551

改用方法 AccessTokenContainer.RegisterAsync(appId, appSecret)和 AccessTokenContainer.GetAccessToken(appId, getNewToken)  
##### 微信官方文档 URL

关键代码
       /// <summary>
        /// 微信初始化。
        /// </summary>
        public static void RegisterWeixin()
        {
            try
            {
                SenparcSetting senparcSetting = CreateSenparcSetting();

                //设置微信 Debug 状态
                var senparcWeixinSetting = new SenparcWeixinSetting(IsDebug);

                //CO2NET全局注册，必须！
                var register = RegisterService.Start(senparcSetting).UseSenparcGlobal();

                if (WeixinPublicAccountConfig.Instance.WeixinCacheType == WeixinCacheType.Redis)
                {
                    UseRedisContainerCache();
                }

                //微信全局注册，必须！
                register.UseSenparcWeixin(senparcWeixinSetting, senparcSetting);
            }
            catch (System.Exception ex)
            {
                Logger.AddFileLog(ex);
            }
        }

        private static SenparcSetting CreateSenparcSetting()
        {
            var settingConfig = WeixinPublicAccountConfig.Instance;
            return new SenparcSetting
            {
                Cache_Memcached_Configuration = string.Empty,
                Cache_Redis_Configuration = settingConfig.CacheRedisConfiguration,
                DefaultCacheNamespace = settingConfig.DefaultCacheNamespace,
                IsDebug = IsDebug
            };
        }

        private static void UseRedisContainerCache()
        {
Register.SetConfigurationOption(WeixinPublicAccountConfig.Instance.CacheRedisConfiguration);

            // 以下会立即将全局缓存设置为 Redis
            Senparc.CO2NET.Cache.Redis.Register.UseKeyValueRedisNow(); // 键值对缓存策略（推荐）
        }

日志：

[[[UseSenparcGlobal() 自动扫描程序集异常：Senparc.Weixin.Cache.Redis, Version=2.5.2.0, Culture=neutral, PublicKeyToken=null]]]

[[[RegisterApiBind() 自动扫描程序集报告（非程序异常）：Senparc.Weixin.Cache.Redis, Version=2.5.2.0, Culture=neutral, PublicKeyToken=null]]]
[2019/08/26 15:24:56.3222]
[线程：81]
System.Reflection.ReflectionTypeLoadException: 无法加载一个或多个请求的类型。有关更多信息，请检索 LoaderExceptions 属性。
   在 System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   在 System.Reflection.RuntimeModule.GetTypes()
   在 System.Reflection.Assembly.GetTypes()
   在 Senparc.NeuChar.Register.RegisterApiBind(Boolean forceBindAgain)
dll版本：
  package id="Senparc.CO2NET" version="0.8.9" targetFramework="net46" 
  package id="Senparc.CO2NET.APM" version="0.4.2" targetFramework="net46" 
  package id="Senparc.CO2NET.Cache.Redis" version="3.5.3" targetFramework="net46" 
  package id="Senparc.CO2NET.Cache.Redis.RedLock" version="2.2.3" targetFramework="net46" 
  package id="Senparc.NeuChar" version="0.7.5" targetFramework="net46" 
  package id="Senparc.NeuChar.App" version="0.5.5" targetFramework="net46" 
  package id="Senparc.Weixin" version="6.4.13" targetFramework="net46" 
  package id="Senparc.Weixin.Cache.Redis" version="2.5.10" targetFramework="net46" 
  package id="Senparc.Weixin.MP" version="16.7.14" targetFramework="net46" 
  package id="StackExchange.Redis" version="1.2.6" targetFramework="net46" 

包括Senparc.Weixin.Cache.Redis在内引用的dll版本和package里面的版本一致。
##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net 4.6
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [ ] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [x] Visual Studio 2019
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [x] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
可能是同步方法中的一个问题，我正在处理并发布新版本

**Comment by JeffreySu** [comment]
什么.net版本？

**Comment by wtujvk** [comment]
net46

**Comment by JeffreySu** [comment]
上面代码和表述有点乱，意思不太明确，你是已经按照Demo的注册了，还是有这个问题吗？

**Comment by wtujvk** [comment]
是的。 
使用内存缓存正常。 
但是使用redis缓存看，调用register 就不行，报这个错：  当前扩展缓存策略没有进行注册。

**Comment by JeffreySu** [comment]
这个错误的发生是因为没有按照要求注册，缺少代码或者把注册过程顺序弄错了，您对应我们官方的Demo看一下，用Demo连一次试试看，然后逐步改成你现在的代码。

**Comment by wtujvk** [comment]
redis缓存里面是不是用到了反射？
单独的项目是可以使用redis缓存的。 
但是 在服务层使用微信模块，内存缓存可用，使用redis缓存注册不了缓存。怀疑是扫描程序集的问题。即：在类库中使用微信的代码，在mvc的ui层 引用这个类库（调用注册方法等），然后redis缓存就注册不了。

**Comment by wtujvk** [comment]
就是说，微信的这些东西不作为ui层，而是作为服务层（类库）， 在ui层的 Global.asax.cs 中调用 初始化方法。 微信redis缓存不可用。
如果直接在ui层使用同杨的代码 ，就可用使用redis缓存

**Comment by JeffreySu** [comment]
@wtujvk 反射是有的，为了尽量避免影响效率，我们采用了注册的方式，使用委托的额外开销接近于0，所以 redis 等缓存策略其实是基于注册的基础来展开工作的，如果在注册之前，有任何的代码运行到了缓存的读写，就有可能出问题，这里只要注意一下确保在系统启动的第一时间完成注册过程即可。

**Comment by wtujvk** [comment]
去掉了cache和redis相关的dll引用，使用默认缓存，TryGetAccessToken功能可用，但是日志里面还是会出现：
[[[RegisterApiBind() 自动扫描程序集报告（非程序异常）：Senparc.Weixin.Cache.Redis, Version=2.5.2.0, Culture=neutral, PublicKeyToken=null]]]
[2019/09/04 10:12:35.2907]
[线程：90]
System.Reflection.ReflectionTypeLoadException: 无法加载一个或多个请求的类型。有关更多信息，请检索 LoaderExceptions 属性。

packages：
  package id="Senparc.CO2NET" version="0.8.9" targetFramework="net46" 
  package id="Senparc.CO2NET.APM" version="0.4.2" targetFramework="net46" 
  package id="Senparc.NeuChar" version="0.7.5" targetFramework="net46" 
  package id="Senparc.NeuChar.App" version="0.5.5" targetFramework="net46" 
  package id="Senparc.Weixin" version="6.4.13" targetFramework="net46" 
  package id="Senparc.Weixin.MP" version="16.7.16" targetFramework="net46" 
注：相关程序集都有强签名 (strongName)

**Comment by JeffreySu** [comment]
1、上面的一场不是问题，主义已经写明了 `（非程序异常）`
2、如果使用默认缓存可以的话要就要看一下 redis 缓存注册顺序以及是否有代码遗漏的问题了。
