### ISSUE TITLE
缺少“获取WiFi门店列表”接口

### ISSUE THREAD

**Issue by bit-4** [JeffreySu/WeiXinMPSDK#190]
微信WIFI 缺少API
请求URL：https://api.weixin.qq.com/bizwifi/shop/list?access_token=ACCESS_TOKEN

**Comment by JeffreySu** [comment]
已经放到下一个版本计划，谢谢！

**Comment by JeffreySu** [comment]
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1444894115&token=&lang=zh_CN
