### ISSUE TITLE
统一发送消息的参数类型有误 UniformSendData

### ISSUE THREAD

**Issue by Dysheng** [JeffreySu/WeiXinMPSDK#1901]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
统一发送消息的参数类型有误，不应该写死参数类型，
weapp_template_msg .data 应该为Object类型。
否则有很多模板无法使用
 
![image](https://user-images.githubusercontent.com/6174604/64141984-c03b9280-ce3c-11e9-9b1d-7dc31c209870.png)

![image](https://user-images.githubusercontent.com/6174604/64142124-40fa8e80-ce3d-11e9-845a-7d86648806d1.png)

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 微信官方文档 URL
https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/uniform-message/uniformMessage.send.html

##### 发现问题的模块
 
- [ ] Senparc.Weixin.WxOpen 版本：
 

##### 模块对应的 .net 版本

4.6.1

##### 开发环境
 
- [ ] Visual Studio 2017
- [x] Visual Studio 2019
 
- [ ] 其他：

 
##### 联系方式
Email：
deng0981@sina.com

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
@Dysheng  已经修正并发布新版本，板鞋！也欢迎继续反馈或 PR 代码成为项目 Contributor 一员🎖

**Comment by JHeLiu** [comment]
@JeffreySu  层主 关于这个问题，其实我建议 可以把  data 扩展一个方法出来，它可以是 
 Dictionary<string, object> data = new Dictionary<string, object>(); 这样它可以在 稍微标准的情况下又给予了调用者更灵活的组装

**Comment by JeffreySu** [comment]
@JHeLiu 是的，这样更好，序列化和反序列化可能需要有一套特殊的规则，这个格式应该 JSON.NET 不能自动转吧？

**Comment by JHeLiu** [comment]
@JeffreySu  可以自动转化， 微信的 其实标准的也是   key1:{ value:"",color:"" } 这样的格式， 你甚至可以定义为 Dictionary<string, class> ，在使用者的时候 更为标准行为

**Comment by JeffreySu** [comment]
@JHeLiu 好，我会试一下
