### ISSUE TITLE
商户的企业付款查询结果实体（GetTransferInfoResult）缺少payment_time字段

### ISSUE THREAD

**Issue by JianChengSun** [JeffreySu/WeiXinMPSDK#1902]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
微信支付官方文档的返回参数中有 **payment_time**字段用来表示企业付款成功时间，但是在实体**Senparc.Weixin.TenPay.V3.GetTransferInfoResult** 中没有这个字段

##### 微信官方文档 URL
https://pay.weixin.qq.com/wiki/doc/api/tools/mch_pay.php?chapter=14_3

##### 微信官方文档快照（直接复制关键内容到下方）
![image](https://user-images.githubusercontent.com/6623304/64234936-e8ed8600-cf29-11e9-8217-c70a1629949a.png)

##### 发现问题的模块

- [x] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [x] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] Visual Studio 2019
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：sunjiancheng2013@163.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JianChengSun** [comment]
暂时使用了以下方法获到了payment_time的值
`GetTransferInfoResult infoResult= TenPayV3.GetTransferInfo(reviewData);
string paymentTime = infoResult.GetXmlValue("payment_time");`

**Comment by JeffreySu** [comment]
@JianChengSun  已经发布新版本，非常感谢！欢迎继续反馈或 PR，成为项目 Contributor 😄

**Comment by JianChengSun** [comment]
非常感谢，已经使用新版本了
