### ISSUE TITLE
缺少“获取公众号连网URL"API

### ISSUE THREAD

**Issue by bit-4** [JeffreySu/WeiXinMPSDK#191]
请求URL：https://api.weixin.qq.com/bizwifi/account/get_connecturl?access_token=ACCESS_TOKEN

**Comment by JeffreySu** [comment]
已经加入开发计划，谢谢！
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1457445326&token=&lang=zh_CN

如果您有已经做好的代码，也欢迎pull request上来！

**Comment by AnnXu** [comment]
已经更新到 Senparc.Weixin.MP v13.7.11 添加“获取公众号连网URL”接口（GetConnectUrl）
谢谢！
