### ISSUE TITLE
配置文件debug模式下会导致整站挂掉

### ISSUE THREAD

**Issue by 97686773** [JeffreySu/WeiXinMPSDK#1916]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
.net core 2.2 webapi 
在使用OAuth2的时候，发现的问题，
如果在appsetting.json 中关于IsDebug 全部设置为true的时候，
在任意请求中调用HttpContext.Session.GetString("test");//获取session的请求
都可以触发 整站503 ，导致网站挂掉
ps：本地debug运行没有问题，部署到服务器上可以稳定复现，服务器是阿里云的服务器。

操作系统： Windows Server 2016 数据中心版...
##### 重现问题步骤（如果可以）

1. 我这里只启用了微信公众号功能，缓存和其他的所有功能都没有启动
2. 定义一个请求设置session，HttpContext.Session.SetString("test","test123");，然后定义一个请求获取session并返回string a = HttpContext.Session.GetString("test");
                return Content(a);
3.实际上页面不会出现获取的session，而是一个空白，代表没有拿到session，然后整站所有请求都会变成503

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [x] Senparc.Weixin.WxOpen 版本：

##### 模块对应的 .net 版本

- [x] .net core 2.x

##### 开发环境

- [x] Visual Studio 2017

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
您是在自己的项目里面装SDK，还是在Demo基础上运行的？SDK内部没有用到Session。
