### ISSUE TITLE
JSSDKHelper 版本太旧，需要更新

### ISSUE THREAD

**Issue by bit-4** [JeffreySu/WeiXinMPSDK#192]
api_ticket 相较 appsecret 安全性更高，同时兼容老版本文档中使用的 appsecret 作为签名凭证
虽然是能兼容旧版本，但是否考虑更新一下SDK？

**Comment by JeffreySu** [comment]
JSSDK有好几个，api_ticket也不是都通用的，您说的是哪一个？
安全性上面来说，目前的jssdk也没有把seceret暴露给客户端哇，这里面您觉得有什么问题？
