### ISSUE TITLE
OnTextOrEventRequest的参数类型RequestMessageText没有事件类型，导致无法在这里处理48小时内活动用户

### ISSUE THREAD

**Issue by willtoto** [JeffreySu/WeiXinMPSDK#1920]
##### 问题描述
想在 OnTextOrEventRequest 函数中标记用户为48消失内有过互动得用户
但是 ConvertToRequestMessageText()这个函数里面没有吧对应的事件传递过来，导致无法判断用户是执行了什么操作

**Comment by JeffreySu** [comment]
根据消息类型做判断，应该在 OnExecuting() 方法里面写。
