### ISSUE TITLE
DefaultMpMessageContext GetRequestEntityMappingResult xdoc is null

### ISSUE THREAD

**Issue by gendou** [JeffreySu/WeiXinMPSDK#1930]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述

使用CoreSample专案 直接测试
使用微信公众平台接口调试工具发送事件消息(兼容模式)

**GetRequestEntityMappingResult doc 会是null**

WeixinController 中 PostModel 与 Response.GetRequestMemoryStream() 皆有信息

使用 XmlUtility.Convert(Request.GetRequestMemoryStream()); 也能取得Xdocment

是我调试步骤哪里有误吗?
或是我使用微信公众平台接口调试工具的信息有误?

System.NullReferenceException: Object reference not set to an instance of an object.
   at Senparc.Weixin.MP.MessageContexts.DefaultMpMessageContext.GetRequestEntityMappingResult(RequestMsgType requestMsgType, XDocument doc) in Z:\Project\WeiXinMPSDK\src\Senparc.Weixin.MP\Senparc.Weixin.MP\MessageContexts\DefaultMpMessageContext.cs:line 84
   at Senparc.Weixin.MP.RequestMessageFactory.GetRequestEntity[TMC](TMC messageContext, XDocument doc, PostModel postModel) in Z:\Project\WeiXinMPSDK\src\Senparc.Weixin.MP\Senparc.Weixin.MP\RequestMessageFactory.cs:line 90

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [x] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [x] .net core 2.x

##### 开发环境

- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [x] Visual Studio 2019
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：gendou915@foxmail.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by 280780363** [comment]
同样的问题+1,希望尽快修复,目前只能用源码自行修复此bug

**Comment by JeffreySu** [comment]
@280780363 已经上传新版本源码，正在等待和 .NET Core 3.0 版本一起进入发布管道。

**Comment by JeffreySu** [comment]
@280780363  @gendou 已经发布新版本，请使用最近版本测试。感谢反馈！
