### ISSUE TITLE
企业付款最新版本的接口不能带证书参数

### ISSUE THREAD

**Issue by ClementeGao** [JeffreySu/WeiXinMPSDK#1931]
![image](https://user-images.githubusercontent.com/16145998/65505557-12cc1400-defc-11e9-9e7e-63bb408e2cae.png)
请问证书怎么配置

**Comment by JeffreySu** [comment]
@ClementeGao 麻烦按照 issue 提供一下您的开发环境。

**Comment by ClementeGao** [comment]
开发环境

**Comment by ClementeGao** [comment]
![image](https://user-images.githubusercontent.com/16145998/65561942-eb665d00-df76-11e9-9a86-64a5efade36d.png)
证书那个 我配置了 但是现在报了这个问题 是开发环境 本地调试出的问题

**Comment by JeffreySu** [comment]
@ClementeGao 抱歉，没有看到开发环境的参数。比如 VS 版本，.NET 版本。
