### ISSUE TITLE
在win服务下可以用吗？

### ISSUE THREAD

**Issue by JHeLiu** [JeffreySu/WeiXinMPSDK#1946]
我知道在 .NET .NETCORE下需要 首次 注册下
1、我可以不注册，开箱直接用吗？
2、我可以在WIN服务下使用它吗？

**Comment by JeffreySu** [comment]
1、通常需要进行简单的注册，只需要简单的几行代码，参考 Console，当然如果你只是使用一些 Helper 之类类，不需要使用到缓存、文件位置等信息，可以不用注册。
2、可以在服务下使用。

**Comment by JHeLiu** [comment]
@JeffreySu  谢谢，
我在想它有没有更为绿色的使用方法。比如它是一个工具栏。默认情况下 我不需要做任何多余操作，
只需要 引用后 直接调用 api即可， 因为很多时候 它就是一个通用的公共库。不是这样会不会好点?

**Comment by JeffreySu** [comment]
如果按照“约定胜于配置”，理论上是可以的，不过实际上还是会有很多特殊情况，所以还是需要给开发者提供多种选择。另外从可维护性上来说，显性的调试入口也是很重要的，让开发者知道正在发生什么。

**Comment by JHeLiu** [comment]
@JeffreySu 在未来的版本 有没有可能 有2个选择？
1、**不启动配置** 默认就直接用，它可能更像我说的它就是一个 工具类库，使用者只需关心我该如何使用使用库。什么命名空间下的类 的方法如何使用
2、**启动配置就走配置**

**Comment by JeffreySu** [comment]
@JHeLiu 可能性当然是存在地，CO2NET目前的定位是一个功能性的基础库，如果按照第一种方式，可能就是分离成一个.Helper或者.Utility的包，可以“静态”地调用。

另外一个题外话，目前CONET里面对Web（Host）有一些依赖，某种程度上来说，如果用户只是需要支持命令行或者桌面地时候不是特别好，有些多余，我们真该考虑分离一个 CO2NET.Host出来，只是目前来看没有这么迫切。
