### ISSUE TITLE
最新版（Senparc.Weixin.MP 16.9.101）自定义菜单中的扫码事件触发失败

### ISSUE THREAD

**Issue by GitOffice** [JeffreySu/WeiXinMPSDK#1978]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
自定义菜单中的事件类型（scancode_waitmsg）触发OnEvent_ScancodeWaitmsgRequest(RequestMessageEvent_Scancode_Waitmsg requestMessage)失败，如果用微信自带的扫一扫，可以成功！
升级到NeuChar之前的旧版中，不存在该问题。
##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 发现问题的模块

- [x] Senparc.Weixin.MP 版本：
 .net 4.5.1
vs2013

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
确定是退回一个版本问题就不存在了吗？

**Comment by GitOffice** [comment]
> 确定是退回一个版本问题就不存在了吗？

确定，在升级到MP16.9之前一直是正常使用的。目前用到的相关库和版本依次是：
Senparc.Weixin  6.6.101
Senparc.CO2NET  1.0.101
Senparc.Weixin.MP  16.9.101

**Comment by JeffreySu** [comment]
好的，这一块这个版本应该没有动过，我会再核实一下，谢谢！

**Comment by JeffreySu** [comment]
微信官方已经确认是微信自身的 bug，目前尚未发布补丁。
