### ISSUE TITLE
卡券中的 code_type 定义不完整

### ISSUE THREAD

**Issue by jiehanlin** [JeffreySu/WeiXinMPSDK#199]
定义不完整，导致部分code type的卡券CardDetailGet后转换失败。
    /// <summary>
    /// 卡券code码展示类型
    /// </summary>
    public enum Card_CodeType
    {
        /// <summary>
        /// 文本
        /// </summary>
        CODE_TYPE_TEXT = 0,
        /// <summary>
        /// 一维码
        /// </summary>
        CODE_TYPE_BARCODE = 1,
        /// <summary>
        /// 二维码
        /// </summary>
        CODE_TYPE_QRCODE = 2,
        	//以下为增加的
        /// <summary>
        /// 二维码无code显示
        /// </summary>
        CODE_TYPE_ONLY_QRCODE = 3,
        /// <summary>
        /// 一维码无code显示
        /// </summary>
        CODE_TYPE_ONLY_BARCODE = 4,
        /// <summary>
        /// 不显示code和条形码类型
        /// </summary>
        CODE_TYPE_NONE = 5

    }

**Comment by JeffreySu** [comment]
谢谢！
你可以直接pull request过来吗？这样你就可以自动进入到“贡献者”名单了：）

**Comment by AnnXu** [comment]
@	jiehanlin非常感谢你的发现和意见，已经修改了public enum Card_CodeType
    {
        /// <summary>
        /// 文本
        /// </summary>
        CODE_TYPE_TEXT = 0,
        /// <summary>
        /// 一维码
        /// </summary>
        CODE_TYPE_BARCODE = 1,
        /// <summary>
        /// 二维码
        /// </summary>
        CODE_TYPE_QRCODE = 2,
        ///
        /// 二维码无code显示
        ///
        CODE_TYPE_ONLY_QRCODE = 3,
        ///
        /// 一维码无code显示
        ///
        CODE_TYPE_ONLY_BARCODE = 4,
        ///
        /// 不显示code和条形码类型
        ///
        CODE_TYPE_NONE = 5
    }
已上传。版本为AssemblyVersion("14.2.3.*")]
