### ISSUE TITLE
WxAppApi.ImgSecCheckAsync 提示 缺少多媒体文件数据 41005

### ISSUE THREAD

**Issue by ChiakiYu** [JeffreySu/WeiXinMPSDK#1990]
### 问题描述

使用WxAppApi.ImgSecCheckAsync进行图片审核时，无论用啥图片都是返回“缺少多媒体文件数据”

##### 重现问题步骤（如果可以）

图片路径：http://portal.jielong.csproj.com/image/20191009/6370620880544107641465.png
这是微信小程序官方审核时使用的图片，被我放在七牛上方便测试了，无防盗链等

##### 发现问题的模块

- [x] Senparc.Weixin.WxOpen 版本：3.4.9.0

##### 模块对应的 .net 版本

- [x] .net core 2.2

##### 开发环境

- [x] Visual Studio 2019

##### 缓存环境

- [x] 服务器内存缓存（默认）

**Comment by JeffreySu** [comment]
不能直接使用外部资源，需要用本地磁盘中的文件路径进行上传，微信不支持这样的转发，必须要传实体文件。

**Comment by ChiakiYu** [comment]
那像我这种  从用户手机或微信聊天记录中上传图片到服务器，服务器转存到七牛的情况，能用这个方法审核图片吗？

**Comment by JeffreySu** [comment]
不管你存在哪里，最后提交给微信服务器必须是文件，不是一个url。

**Comment by ChiakiYu** [comment]
但是sdk的这个方法要的是一个url。。。是sdk不支持外部资源吗？

**Comment by ChiakiYu** [comment]
我也尝试过  绕过sdk，拿小程序端提交过来的Request.File组装成form表单直接提交给微信，依旧是这个错误

**Comment by JeffreySu** [comment]
SDK 要求的是 filePath，没有说要 Url：http://doc.weixin.senparc.com/html/M_Senparc_Weixin_WxOpen_AdvancedAPIs_WxApp_WxAppApi_ImgSecCheckAsync.htm

下载图片在底层有方法的， CO2NET 下面：https://github.com/Senparc/Senparc.CO2NET/blob/0b1cb2264b80ad1008624fb87879bea3049bf9bc/src/Senparc.CO2NET/Utilities/HttpUtility/HttpGet/Get.cs#L286

结合起来用就行了。

**Comment by ChiakiYu** [comment]
明白了  多谢
