### ISSUE TITLE
模板信息 公众号+小程序

### ISSUE THREAD

**Issue by JHeLiu** [JeffreySu/WeiXinMPSDK#2002]
希望在 公众号 以及小程序 发送 模板消息的时候，直接开一个 完整的 json 字符串接口，
比如 。 token + json 就完事了，
1、遇到在上游程序已经格式化好了 完整的 json， 考虑到动态设置管理系统 模板。

虽然自己用源代码可以修改， 但是还是希望官方能公开这个方法。或者拓展出来一个
比如

`TemplateApi.SendTemplateMessage("access_token","json")` 

这样 的

**Comment by JeffreySu** [comment]
@JHeLiu  这样即可：

``` c#
TemplateApi.SendTemplateMessage("access_token","json".GetObject<object>())
```

**Comment by JHeLiu** [comment]
@JeffreySu  
![image](https://user-images.githubusercontent.com/15246138/66990421-baea8c80-f0f8-11e9-9858-0a6750a629e5.png) 
我在最新版本 没看到有这个扩展放， 它在那个目录下呢、

![image](https://user-images.githubusercontent.com/15246138/66990511-ecfbee80-f0f8-11e9-9e5f-267ff26a48a6.png)

好像绕不开 openid， 我想绕过openid，
就access_token 跟 完整d  json  接可以了

**Comment by JeffreySu** [comment]
@JHeLiu  `.GetObject<object>()` 是一个扩展方法，按 `Alt+回车` 应该可以直接看到命名空间提示。这个方法可以把你的 json 转成 object 类型（逆向就是 .ToJson() 扩展方法，可以转成字符串），因为模板消息数据不会很多，这个转换过程的损失通常可以忽略不计。

另外我的概念是接口应该`尽量`避免直接传送字符串，不可控因素太多。经过对象转换也是一个校验结构正确性的过程。

**Comment by JeffreySu** [comment]
你的字符串里面是怎么样的？还有openid？

**Comment by JHeLiu** [comment]
@JeffreySu  就是一个完整的JSON字符串

**Comment by JeffreySu** [comment]
但是这个 json 如果你对应的是 data 的话，应该 openid 是另外的吧？
