### ISSUE TITLE
Senparc.Weixin.MP 多客服指定客服 无效 所有客服都可以看见

### ISSUE THREAD

**Issue by JosonJiang** [JeffreySu/WeiXinMPSDK#2003]
//接入操作客服
                        //ResponseMessageTransfer_Customer_Service responseMessageTransfer_Customer_ = new ResponseMessageTransfer_Customer_Service();
                        //responseMessageTransfer_Customer_.TransInfo.Add(new CustomerServiceAccount { KfAccount = "zytxx@yxx" });
                        //responseMessageTransfer_Customer_.TransInfo.Add(new CustomerServiceAccount { KfAccount = "zytxx@yxssssx" });

CreateResponseMessage<ResponseMessageTransfer_Customer_Service>();

这样有问题？

**Comment by JeffreySu** [comment]
@JosonJiang 能不能给一下你真实的在线上运行的代码？一模一样的代码。
