### ISSUE TITLE
扫描商品条形码的后，会有一个画面，里面有一个查看公众号，这个特殊的事件未处理

### ISSUE THREAD

**Issue by ihugang** [JeffreySu/WeiXinMPSDK#202]
微信扫描条形码之后，会弹出一个商品介绍画面，在画面下方有一个查看公众号链接，会直接进入公众号，这个时候，公众号会收到一个事件，目前，这个事件未处理，那位能够升级一下代码？

<?xml version="1.0" encoding="utf-8"?>
<xml>
  <ToUserName><![CDATA[gh_a8e920aabe60]]></ToUserName>
<FromUserName><![CDATA[oBh-Tv20THT4Pkq7j1CvJ4V7RTeE]]></FromUserName>
<CreateTime>1463471444</CreateTime>
<MsgType><![CDATA[event]]></MsgType>
<Event><![CDATA[user_scan_product]]></Event>
<KeyStandard><![CDATA[ean13]]></KeyStandard>
<KeyStr><![CDATA[6970388836017]]></KeyStr>
<Country><![CDATA[中国]]></Country>
<Province><![CDATA[浙江]]></Province>
<City><![CDATA[杭州]]></City>
<Sex>1</Sex>
<Scene>1</Scene>
<ExtInfo><![CDATA[]]></ExtInfo>
</xml>

**Comment by JeffreySu** [comment]
对应文档地址？
