### ISSUE TITLE
希望能提供搭建微信测试环境的项目

### ISSUE THREAD

**Issue by wtujvk** [JeffreySu/WeiXinMPSDK#2021]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
能否搭建一套微信测试环境呢？
由于微信接口次数限制 以及测试环境和正式环境的区别，无法做相应的测试（例如压力测试等）。
而且公众号不一定有所有的权限（除非申请多个公众号？）。
在实际开发或者演示中 经常出现接口超过次数的问题。
搭建一个类似于微信公众号平台的环境（目前只需要考虑本地调用微信公众号平台的接口即可）：
（1）  目前 Config.ApiMpHost是可以修改的（这个已有了吧）。
（2） 调用接口，请求提交到部署的测试站，返回和微信类似的响应的结果。
（3） 最好可以自己控制设置接口频次。

##### 发现问题的模块

- [x] Senparc.Weixin 版本：
- [x] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [x] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [ ] .net core 2.x
- [ ] .net core 3.x

##### 开发环境

- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [x] Visual Studio 2019
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
可以直接使用微信测试号：https://mp.weixin.qq.com/debug/cgi-bin/sandbox?t=sandbox/login
涉及到微信支付可以直接用沙箱。

**Comment by wtujvk** [comment]
测试号次数不够，很多接口不到100次，而且很多接口测试号是不支持的。

**Comment by JeffreySu** [comment]
那你要获得和公众号一样的结果本身也很困难吧？如果这样我倒是建议你专门申请一个号做测试。
