### ISSUE TITLE
OnEvent_EnterRequest 参数为null

### ISSUE THREAD

**Issue by yang524433** [JeffreySu/WeiXinMPSDK#2026]
Senparc.Weixin.MP：14.10.13.0
由于项目较老依赖项多，无法升级此库，我有其他方式处理此事件吗？
请求参数如下：
``` xml
<xml>
    <ToUserName>
        <![CDATA[gh_e1175f9e7683]]>
    </ToUserName>
    <FromUserName>
        <![CDATA[oDUQw5YxSpbGUvfzlbICkVAV_ox8]]>
    </FromUserName>
    <CreateTime>1573454260</CreateTime>
    <MsgType>
        <![CDATA[event]]>
    </MsgType>
    <Event>
        <![CDATA[user_enter_tempsession]]>
    </Event>
    <SessionFrom>
        <![CDATA[wxapp]]>
    </SessionFrom>
    <Encrypt>
        <![CDATA[cvkpAhqf9IpaKMdD0NKs8Di+dpzS5pYdNxlJLeZPhhEbSSwZk+/BkmCQOXsqkQ49y7ivTKE7AmbqkqRhYnCcrN19EHFXt5tgmQEYBA7Ys2cEtRPp975V5j3TUfCL+mSfpNYUa/KtbE18IyERmPElcGo49k3cFkjdSW/XbBVCLVjoIIbydAKvRKBaT9qeqf6r54/u+kqUROZO0BcHL1gwC5Rx4bvj4M92rz4wpejIVCpFGw0VQxRKxyd5ZjoQlMNKO+QKJ7dTg3cNTN3cgM5S0hp5NVT25R1zC5Q7Bp1woe5bXFxCN6XjXSmyZ9RSA8WvIF+C4nYfMw9wugO/ZxzCQstc4DWSf2GOq775Ve5Dd6dHomdK1KgIR5As4jMdGCHO0p7gGGp/CCKYtl4u3P6gcdxQ+BmpAwPMtvOTKnGX6oBnKQVDqhUzxa9rfe5NA6NDYKHM9XtzEMLufypMGmIasQ==]]>
    </Encrypt>
</xml>
```

**Comment by yang524433** [comment]
<xml>
    <ToUserName>
        <![CDATA[gh_e1175f9e7683]]>
    </ToUserName>
    <FromUserName>
        <![CDATA[oDUQw5YxSpbGUvfzlbICkVAV_ox8]]>
    </FromUserName>
    <CreateTime>1573454260</CreateTime>
    <MsgType>
        <![CDATA[event]]>
    </MsgType>
    <Event>
        <![CDATA[user_enter_tempsession]]>
    </Event>
    <SessionFrom>
        <![CDATA[wxapp]]>
    </SessionFrom>
    <Encrypt>
        <![CDATA[cvkpAhqf9IpaKMdD0NKs8Di+dpzS5pYdNxlJLeZPhhEbSSwZk+/BkmCQOXsqkQ49y7ivTKE7AmbqkqRhYnCcrN19EHFXt5tgmQEYBA7Ys2cEtRPp975V5j3TUfCL+mSfpNYUa/KtbE18IyERmPElcGo49k3cFkjdSW/XbBVCLVjoIIbydAKvRKBaT9qeqf6r54/u+kqUROZO0BcHL1gwC5Rx4bvj4M92rz4wpejIVCpFGw0VQxRKxyd5ZjoQlMNKO+QKJ7dTg3cNTN3cgM5S0hp5NVT25R1zC5Q7Bp1woe5bXFxCN6XjXSmyZ9RSA8WvIF+C4nYfMw9wugO/ZxzCQstc4DWSf2GOq775Ve5Dd6dHomdK1KgIR5As4jMdGCHO0p7gGGp/CCKYtl4u3P6gcdxQ+BmpAwPMtvOTKnGX6oBnKQVDqhUzxa9rfe5NA6NDYKHM9XtzEMLufypMGmIasQ==]]>
    </Encrypt>
</xml>

**Comment by yang524433** [comment]
![image](https://user-images.githubusercontent.com/13463179/68578935-000e9e00-04ae-11ea-99b7-5ef594c60308.png)

**Comment by JeffreySu** [comment]
如果旧版本没有包含这个事件，要么直接修改原代码编译，要么自己重写。
最好的方法还是升级。

**Comment by yang524433** [comment]
Senparc.Weixin.MP：14.10.13.0 版本中是包含这个事件的，但是执行行传进来的RequestMessageEvent_Enter参数为null。

**Comment by yang524433** [comment]
Senparc.Weixin 中是否有通用的解析方法可以直接使用呢

**Comment by JeffreySu** [comment]
1、是否是这里这个方法和类？

https://github.com/JeffreySu/WeiXinMPSDK/blob/86c0d64f42166b4bcaf0c2929343c93aa2b4b3b0/src/Senparc.Weixin.MP/Senparc.Weixin.MP/MessageContexts/DefaultMpMessageContext.cs#L87

https://github.com/JeffreySu/WeiXinMPSDK/blob/86c0d64f42166b4bcaf0c2929343c93aa2b4b3b0/src/Senparc.Weixin.MP/Senparc.Weixin.MP/MessageHandlers/Async/MessageHandlerAsync.Event.cs#L60

2、是否能提供一下解密后的xml信息？

**Comment by yang524433** [comment]
1.我使用的是这个方法https://github.com/JeffreySu/WeiXinMPSDK/blob/86c0d64f42166b4bcaf0c2929343c93aa2b4b3b0/src/Senparc.Weixin.MP/Senparc.Weixin.MP/MessageHandlers/MessageHandler.Event.cs#L60
![1573555578(1)](https://user-images.githubusercontent.com/13463179/68666306-a5914280-057e-11ea-9de6-9e0529a2b950.png)
2.
<xml>
  <ToUserName><![CDATA[gh_e1175f9e7683]]></ToUserName>
  <FromUserName><![CDATA[oDUQw5YxSpbGUvfzlbICkVAV_ox8]]></FromUserName>
  <CreateTime>1573454260</CreateTime>
  <MsgType><![CDATA[event]]></MsgType>
  <Event><![CDATA[user_enter_tempsession]]></Event>
  <SessionFrom><![CDATA[wxapp]]></SessionFrom>
</xml>

**Comment by yang524433** [comment]
`<xml>
  <ToUserName><![CDATA[gh_e1175f9e7683]]></ToUserName>
  <FromUserName><![CDATA[oDUQw5YxSpbGUvfzlbICkVAV_ox8]]></FromUserName>
  <CreateTime>1573454260</CreateTime>
  <MsgType><![CDATA[event]]></MsgType>
  <Event><![CDATA[user_enter_tempsession]]></Event>
  <SessionFrom><![CDATA[wxapp]]></SessionFrom>
</xml>`

**Comment by yang524433** [comment]
另外我还发现14.10.13.0的另一个问题，当请求send方法发送失败时，会直接导致应用程序崩溃
`- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="ASP.NET 4.0.30319.0" /> 
  <EventID Qualifiers="49152">1325</EventID> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2019-11-12T03:00:32.880579900Z" /> 
  <EventRecordID>198143</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>Nestle-LGO2.nestlegcr.com.cn</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>An unhandled exception occurred and the process was terminated. Application ID: /LM/W3SVC/7/ROOT Process ID: 23424 Exception: Senparc.Weixin.Exceptions.ErrorJsonResultException Message: 微信Post请求发生错误！错误代码：45015，说明：response out of time limit or subscription is canceled hint: [Vn4fja06323951] StackTrace: at Senparc.Weixin.HttpUtility.Post.GetResult[T](String returnText) at Senparc.Weixin.CommonAPIs.CommonJsonSend.Send[T](String accessToken, String urlFormat, Object data, CommonJsonSendType sendType, Int32 timeOut, Boolean checkValidationResult, JsonSetting jsonSetting) at Senparc.Weixin.MP.CommonAPIs.CommonJsonSend.Send(String accessToken, String urlFormat, Object data, CommonJsonSendType sendType, Int32 timeOut, Boolean checkValidationResult, JsonSetting jsonSetting) at Senparc.Weixin.MP.AdvancedAPIs.CustomApi.<>c__DisplayClass1_0.<SendText>b__0(String accessToken) at Senparc.Weixin.CommonAPIs.ApiHandlerWapper.ApiHandlerWapperBase.TryCommonApiBase[T](PlatformType platformType, Func`1 accessTokenContainer_GetFirstOrDefaultAppIdFunc, Func`2 accessTokenContainer_CheckRegisteredFunc, Func`3 accessTokenContainer_GetAccessTokenResultFunc, Int32 invalidCredentialValue, Func`2 fun, String accessTokenOrAppId, Boolean retryIfFaild) at Senparc.Weixin.MP.ApiHandlerWapper.TryCommonApi[T](Func`2 fun, String accessTokenOrAppId, Boolean retryIfFaild) at CSR.IM.Services.TaskSchedulingService.workQueue_UserWork(Object sender, EnqueueEventArgs e) at CSR.IM.Infrastructure.WorkQueue`1.DoUserWork(Object o) at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() at System.Threading.ThreadPoolWorkQueue.Dispatch()</Data> 
  </EventData>
  </Event>`

**Comment by yang524433** [comment]
另外我还发现14.10.13.0的另一个问题，当请求send方法发送失败时，会直接导致应用程序崩溃
`-

An unhandled exception occurred and the process was terminated. Application ID: /LM/W3SVC/7/ROOT Process ID: 23424 Exception: Senparc.Weixin.Exceptions.ErrorJsonResultException Message: 微信Post请求发生错误！错误代码：45015，说明：response out of time limit or subscription is canceled hint: [Vn4fja06323951] StackTrace: at Senparc.Weixin.HttpUtility.Post.GetResult[T](String returnText) at Senparc.Weixin.CommonAPIs.CommonJsonSend.Send[T](String accessToken, String urlFormat, Object data, CommonJsonSendType sendType, Int32 timeOut, Boolean checkValidationResult, JsonSetting jsonSetting) at Senparc.Weixin.MP.CommonAPIs.CommonJsonSend.Send(String accessToken, String urlFormat, Object data, CommonJsonSendType sendType, Int32 timeOut, Boolean checkValidationResult, JsonSetting jsonSetting) at Senparc.Weixin.MP.AdvancedAPIs.CustomApi.<>c__DisplayClass1_0.b__0(String accessToken) at Senparc.Weixin.CommonAPIs.ApiHandlerWapper.ApiHandlerWapperBase.TryCommonApiBase[T](PlatformType platformType, Func`1 accessTokenContainer_GetFirstOrDefaultAppIdFunc, Func`2 accessTokenContainer_CheckRegisteredFunc, Func`3 accessTokenContainer_GetAccessTokenResultFunc, Int32 invalidCredentialValue, Func`2 fun, String accessTokenOrAppId, Boolean retryIfFaild) at Senparc.Weixin.MP.ApiHandlerWapper.TryCommonApi[T](Func`2 fun, String accessTokenOrAppId, Boolean retryIfFaild) at CSR.IM.Services.TaskSchedulingService.workQueue_UserWork(Object sender, EnqueueEventArgs e) at CSR.IM.Infrastructure.WorkQueue`1.DoUserWork(Object o) at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() at System.Threading.ThreadPoolWorkQueue.Dispatch() `

**Comment by JeffreySu** [comment]
> 另外我还发现14.10.13.0的另一个问题，当请求send方法发送失败时，会直接导致应用程序崩溃
> `-
> 
> An unhandled exception occurred and the process was terminated. Application ID: /LM/W3SVC/7/ROOT Process ID: 23424 Exception: Senparc.Weixin.Exceptions.ErrorJsonResultException Message: 微信Post请求发生错误！错误代码：45015，说明：response out of time limit or subscription is canceled hint: [Vn4fja06323951] StackTrace: at Senparc.Weixin.HttpUtility.Post.GetResult[T](String returnText) at Senparc.Weixin.CommonAPIs.CommonJsonSend.Send[T](String accessToken, String urlFormat, Object data, CommonJsonSendType sendType, Int32 timeOut, Boolean checkValidationResult, JsonSetting jsonSetting) at Senparc.Weixin.MP.CommonAPIs.CommonJsonSend.Send(String accessToken, String urlFormat, Object data, CommonJsonSendType sendType, Int32 timeOut, Boolean checkValidationResult, JsonSetting jsonSetting) at Senparc.Weixin.MP.AdvancedAPIs.CustomApi.<>c__DisplayClass1_0.b__0(String accessToken) at Senparc.Weixin.CommonAPIs.ApiHandlerWapper.ApiHandlerWapperBase.TryCommonApiBase[T](PlatformType platformType, Func`1 accessTokenContainer_GetFirstOrDefaultAppIdFunc, Func`2 accessTokenContainer_CheckRegisteredFunc, Func`3 accessTokenContainer_GetAccessTokenResultFunc, Int32 invalidCredentialValue, Func`2 fun, String accessTokenOrAppId, Boolean retryIfFaild) at Senparc.Weixin.MP.ApiHandlerWapper.TryCommonApi[T](Func`2 fun, String accessTokenOrAppId, Boolean retryIfFaild) at CSR.IM.Services.TaskSchedulingService.workQueue_UserWork(Object sender, EnqueueEventArgs e) at CSR.IM.Infrastructure.WorkQueue`1.DoUserWork(Object o) at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() at System.Threading.ThreadPoolWorkQueue.Dispatch() `

抱歉，这个问题因为是旧版本上的，已经没法跟进了，因为已经有新版本了，如果新版本不能重现，你应该升级到新版本，不然就出来两个分支了。

下面的回复仍然会针对最顶部的问题。

**Comment by yang524433** [comment]
我使用OnEventRequest事件解决了问题
感谢解答

**Comment by JeffreySu** [comment]
> `<xml> <ToUserName><![CDATA[gh_e1175f9e7683]]></ToUserName> <FromUserName><![CDATA[oDUQw5YxSpbGUvfzlbICkVAV_ox8]]></FromUserName> <CreateTime>1573454260</CreateTime> <MsgType><![CDATA[event]]></MsgType> <Event><![CDATA[user_enter_tempsession]]></Event> <SessionFrom><![CDATA[wxapp]]></SessionFrom> </xml>`

user_enter_tempsession 和 enter 不是同一个事件，你确定这个 xml 最后跑到这个方法里面了吗：

https://github.com/JeffreySu/WeiXinMPSDK/blob/86c0d64f42166b4bcaf0c2929343c93aa2b4b3b0/src/Senparc.Weixin.MP/Senparc.Weixin.MP/MessageHandlers/MessageHandler.Event.cs#L60

**Comment by yang524433** [comment]
`if(requestMessage.MsgType== RequestMsgType.Event&&requestMessage.Event== Event.ENTER)
            {
               todo...
            }
            return base.OnEventRequest(requestMessage);`
会进入到OnEventRequest事件，我通过判断MsgType和Event来执行相关操作

**Comment by JeffreySu** [comment]
> `if(requestMessage.MsgType== RequestMsgType.Event&&requestMessage.Event== Event.ENTER) { todo... } return base.OnEventRequest(requestMessage);`
> 会进入到OnEventRequest事件，我通过判断MsgType和Event来执行相关操作


这个也是可以的，不过不是最好的方法，我很奇怪为什么你会进入到这个方法里面？你是不是用了 MP（公众号） 的 dll 去处理 WxOpen（小程序） 的事件了？user_enter_tempsession 好像只有小程序才有？

**Comment by yang524433** [comment]
> > `if(requestMessage.MsgType== RequestMsgType.Event&&requestMessage.Event== Event.ENTER) { todo... } return base.OnEventRequest(requestMessage);`
> > 会进入到OnEventRequest事件，我通过判断MsgType和Event来执行相关操作
> 
> 这个也是可以的，不过不是最好的方法，我很奇怪为什么你会进入到这个方法里面？你是不是用了 MP（公众号） 的 dll 去处理 WxOpen（小程序） 的事件了？user_enter_tempsession 好像只有小程序才有？
对的  目前这块只处理小程序推送过来的消息

**Comment by JeffreySu** [comment]
那你不应该用MP的MessageHandler，这个是处理公众号请求的，小程序应该用WxOpen的MessageHandler基类。
