### ISSUE TITLE
.net core 3.0项目发布部署后出现HttpClient.SenparcHttpClient访问特别慢的问题

### ISSUE THREAD

**Issue by zhangchunyu129** [JeffreySu/WeiXinMPSDK#2027]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
.net core 3.0项目发布部署后，10分钟不访问，再次访问会出现HttpClient.SenparcHttpClient访问特别慢的问题，

##### 重现问题步骤（如果可以）

1.示例代码Senparc.Weixin.Sample.NetCore3，发布到文件夹
2. 发布后的代码放置windows server 2019服务器上，双击Senparc.Weixin.Sample.NetCore3.exe运行控制台
3,等待10分钟运行任意需要发送http请求的接口，第一次http请求最少10秒以上

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [ ] .net core 2.x
- [x] .net core 3.x

##### 开发环境

- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [x] Visual Studio 2019
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [x] Windows，版本：
- [ ] Linux，版本：
- [ ] Mac，版本：
- [ ] 其他：

##### 联系方式
Email：54531043@qq.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
您是怎么注册配置和调用的？

**Comment by lishewen** [comment]
可以自行配置HttpClient的生命周期的
默认是两分钟
参考：https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#httpclient-lifetimes

另外将程序配置成Server GC行为，有助于服务器环境的GC优化
参考：https://docs.microsoft.com/en-us/aspnet/core/performance/memory?view=aspnetcore-3.0#workstation-gc-vs-server-gc

**Comment by zhangchunyu129** [comment]
感谢两位大佬的回复，我这边把项目放到了windows server 2008和2012上都没有出现访问慢的问题了，看来问题是在WindowsServer2019上了
