### ISSUE TITLE
Json序列化错误：用户画像接口DataCubeApi.GetWeAnalysisAppidUserPortrait

### ISSUE THREAD

**Issue by GitOffice** [JeffreySu/WeiXinMPSDK#2029]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
调用DataCubeApi.GetWeAnalysisAppidUserPortrait时错误如下：

"ExceptionMessage": "Cannot deserialize the current JSON object (e.g. {\"name\":\"value\"}) into type 'System.Collections.Generic.List`1[Senparc.Weixin.WxOpen.AdvancedAPIs.DataCube.GetWeAnalysisAppidUserPortraitResultJson_visit_uv]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.\r\nTo fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.\r\nPath 'visit_uv_new.province', line 1, position 50.",

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 微信官方文档 URL
https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/data-analysis/analysis.getUserPortrait.html

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：6.6.101.0
- [ ] Senparc.Weixin.MP 版本：16.9.101.0
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：3.7.101.0
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [对勾 ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [ ] .net core 2.x
- [x] .net core 3.x

##### 开发环境

- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [x] Visual Studio 2019
- [ ] Visual Studio Code
- [ ] 其他：Visual Studio 2013

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [x] Windows，版本：
- [ ] Linux，版本：
- [ ] Mac，版本：
- [ ] 其他：

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by GitOffice** [comment]
按照 https://stackoverflow.com/a/22557770/591587的方法是： 因为province的键值中含[ ] SDK反序列化时候没考虑到。

**Comment by JeffreySu** [comment]
是有问题，List 应该是在第二层，之前放置着在第一层了。已经发布新版本，非常感谢！
