### ISSUE TITLE
关于目前盛派中没有封装小程序红包

### ISSUE THREAD

**Issue by lishouxiangjs** [JeffreySu/WeiXinMPSDK#2031]
微信官方接口地址：https://pay.weixin.qq.com/wiki/doc/api/tools/cash_coupon.php?chapter=18_2&index=3

**Comment by JeffreySu** [comment]
已经列入计划，可能要2周以后更新，欢迎踊跃PR 😄

**Comment by lishouxiangjs** [comment]
非常感谢，加油~

**Comment by JeffreySu** [comment]
已经发布，谢谢！
