### ISSUE TITLE
是否有微信支付  分账相关的api

### ISSUE THREAD

**Issue by YZBGitHub** [JeffreySu/WeiXinMPSDK#2032]
微信官方文档https://pay.weixin.qq.com/wiki/doc/api/allocation.php?chapter=1_24

**Comment by JeffreySu** [comment]
目前还没有列入计划，您那边方便PR吗？

**Comment by JeffreySu** [comment]
可以的，其实基础的做法在 Senparc.Weixin.Tenpay.dll 中已经有了，按照已经有的模式进行扩展就行了。
您扩展完的话，基本上也可以 PR 了 😄

**Comment by YZBGitHub** [comment]
不是都在 Senparc.Weixin.MP这个里面吗

**Comment by JeffreySu** [comment]
这个应该属于支付里面的。

**Comment by YZBGitHub** [comment]
哦，那可能是我用的版本比较老了，我升级看看

**Comment by JeffreySu** [comment]
正在发布 .103 结尾的版本，建议使用最新的版本，上一个版本有缺陷，大概半小时后应该可以看到。
