### ISSUE TITLE
升级到下述版本后，CustomMessageHandler_Events中的是否必须override 异步的方法

### ISSUE THREAD

**Issue by ChiakiYu** [JeffreySu/WeiXinMPSDK#2039]
##### 问题描述
CustomMessageHandler_Events 中，
原本是override OnEvent_SubscribeRequest方法，在上个版本是管用的
升级sdk后，override OnEvent_SubscribeRequest不再执行，尝试着override OnEvent_SubscribeRequestAsync后有效。

请问是我配置不对还是sdk全面废弃同步方法？

##### 重现问题步骤（如果可以）
代码同WeiXinMPSDK\Samples\netcore3.0-mvc
其中 使用了Linux centos的配置`services.Configure<KestrelServerOptions>(options => options.AllowSynchronousIO = true);`

且注释了` //services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();`

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：6.6.102
- [ ] Senparc.Weixin.MP 版本：16.9.103.1
- [ ] Senparc.Weixin.Open 版本：4.7.103
- [ ] Senparc.Weixin.WxOpen 版本：3.7.103

##### 模块对应的 .net 版本

- [x] .net core 3.x

##### 开发环境
- [x] Visual Studio 2019

##### 缓存环境

- [x] 服务器内存缓存（默认）

##### 系统环境

- [x ] Linux，版本：centos 7.7

**Comment by JeffreySu** [comment]
MessageHandler 提供了在异步调用中，共享同步方法的设置，请参考：
https://github.com/JeffreySu/WeiXinMPSDK/blob/master/Samples/netcore3.0-mvc/Senparc.Weixin.Sample.NetCore3/Controllers/WeixinAsyncController.cs#L112

**Comment by ChiakiYu** [comment]
好的。
还有个题外的问题，
当使用第三方带公众号业务后，是不是这里的Post（或者中间件的那种/WeixinAsync）就不再调用了，而变成调用第三方配置里的 /Open/CallBack？
小程序还是依旧调用WxOpen里的Post？

**Comment by JeffreySu** [comment]
@ChiakiYu 第三方代公众号调用接口，大部分还是需要用到 Senparc.Weixin.MP.dll 的（或对应其他模块），只不过使用的是第三方平台获取到的 AccessToken。少部分接口在 Senparc.Weixin.Open 下面，具体看接口的类型（或者说 API 路径的规则）。这些区别参考官方文档就行了。

**Comment by ChiakiYu** [comment]
好的 谢谢
