### ISSUE TITLE
更新6.6.103后扫描带参二维码出错

### ISSUE THREAD

**Issue by archeraya** [JeffreySu/WeiXinMPSDK#2040]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
全部更新当前最新sdk后扫描带参二维码，会话窗口提示服务出现故障。对这部分不是很了解，看代码解决需要时间所以先发下issue。

##### 重现问题步骤（如果可以）

 扫描带参二维码出现

##### 发现问题的模块

- [x ] Senparc.Weixin 版本：6.6.103
- [x] Senparc.Weixin.MP 版本：16.9.103.1
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [x ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [ ] .net core 2.x
- [] .net core 3.x

##### 开发环境

- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [x] Visual Studio 2019
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [x] Windows，版本：
- [ ] Linux，版本：
- [ ] Mac，版本：
- [ ] 其他：

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
先排除一下是不是这个设置的问题：

https://github.com/JeffreySu/WeiXinMPSDK/issues/2039#issuecomment-556091941

**Comment by harvey-chennnnn** [comment]
我也能复现，扫码后能正常处理扫码业务并返回正常message，但是在返回后会提示"该公众号提供的服务出现故障，请稍后再试"。 设置完全按照 #2039 (comment) 里controller里写的。

**Comment by JeffreySu** [comment]
@harvey-chennnnn  关键是这个参数有没有设置：

messageHandler.DefaultMessageHandlerAsyncEvent = DefaultMessageHandlerAsyncEvent.SelfSynicMethod;

**Comment by JeffreySu** [comment]
@harvey-chennnnn 确实能重现这个问题，我正在排查。

**Comment by JeffreySu** [comment]
@harvey-chennnnn 最新104版本已经解决这个问题，请使用最新版本测试。谢谢反馈！

**Comment by harvey-chennnnn** [comment]
@JeffreySu 非常感谢！找到问题了，是公众号授权了第三方有问题，取消掉授权就正常了，sdk没问题。
