### ISSUE TITLE
netframework4.5的程序怎么注册多个公众号

### ISSUE THREAD

**Issue by zhujinhu21** [JeffreySu/WeiXinMPSDK#2043]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述

  //注册公众号（可注册多个）                                                -- DPBMARK MP
                .RegisterMpAccount(senparcWeixinSetting, "【盛派网络小助手】公众号")
在web.config中怎么设置多个公众号，在netcore中有Items配置，在netframework怎么设置？
##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [x] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [ ] .net core 2.x
- [ ] .net core 3.x

##### 开发环境

- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] Visual Studio 2019
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [x] Windows，版本：
- [ ] Linux，版本：
- [ ] Mac，版本：
- [ ] 其他：

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
web.config 中暂时没有提供多级Item的配置，您可以自己使用其他方式配置（如独立的xml、数据、json文件等），然后遍历对应的项目，使用类似下面的方式手动注册：

为每一个公众号创建一个新的 SenparcWeixinSetting 对象，如：

``` C#
foreach(var item in items){
    var newSenparcWeixinSetting  = new SenparcWeixinSetting();
    newSenparcWeixinSetting  .AppId = item.AppId;
    newSenparcWeixinSetting  .AppSecret = item.AppSecret ;
    //...
    
    register.RegisterMpAccount(newSenparcWeixinSetting  , item.Name);
}
```
