### ISSUE TITLE
Senparc.Weixin.MP 16.9.103.1 MessageHandler不能处理同步事件

### ISSUE THREAD

**Issue by zhaoyu1999** [JeffreySu/WeiXinMPSDK#2044]
##### 问题描述
微信服务器发送Click事件后，OnEvent_ClickRequest没有触发。试验了一下似乎是因为BuildResponseMessage被删除了。OnEvent_ClickRequestAsync可以触发。

##### 重现问题步骤（如果可以）

实现Senparc.Weixin.MP.MessageHandlers.MessageHandler，重写OnEvent_ClickRequest。
在Controller中使用MessageHandler.Execute()。
点击公众号菜单中任意一个有Click事件的按钮，可以发现OnEvent_ClickRequest没有触发。

##### 发现问题的模块

- [x] Senparc.Weixin 版本：6.6.103
- [ ] Senparc.Weixin.MP 版本：16.9.103.1
- [ ] Senparc.Weixin.MP.MVC 版本：7.4.103
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本
- [ ] .net 4.5

##### 开发环境

- [x] Visual Studio 2019

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [x] Windows，版本：
- [ ] Linux，版本：
- [ ] Mac，版本：
- [ ] 其他：

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
请检查一下，是不是没有进行这个同步兼容性设置：

https://github.com/JeffreySu/WeiXinMPSDK/blob/master/Samples/netcore3.0-mvc/Senparc.Weixin.Sample.NetCore3/Controllers/WeixinAsyncController.cs#L112

**Comment by zhaoyu1999** [comment]
啊 原来还有这个东西

**Comment by JeffreySu** [comment]
机关很多，可以灵活搭积木 😄
