### ISSUE TITLE
Unexpected character encountered while parsing value: �. Path '', line 0, position 0.

### ISSUE THREAD

**Issue by 1378955720** [JeffreySu/WeiXinMPSDK#2057]
##### 问题描述
在微信成功授权，解密手机号的时候偶尔：Unexpected character encountered while parsing value: �. Path '', line 0, position 0.此问题不是每次都会出现，本人在用源码调试的时候，会发现是因为解密后得到的字符串是乱码的。我试着换了几个Encoding还是不行，返回乱码的是在EncryptHelper.DecodeEncryptedData这个方法中。

##### 发现问题的模块

- [ ] Senparc.Weixin.WxOpen 版本：3.7.104
- [ ] Senparc.Weixin.Cache.Redis 版本：2.7.104

##### 模块对应的 .net 版本

- [ ] .net core 2.0

##### 开发环境

- [ ] Visual Studio 2017

##### 缓存环境

- [ ] Redis 版本：Caching.CSRedis 3.0.51

##### 系统环境

- [ ] Linux，版本：

**Comment by JeffreySu** [comment]
能把你出现乱码时候的所有相关数据发过来看一下吗？包括原始密文，以及解密需要的所有参数。如果涉及到密钥，可以发送到 zsu@senparc.com。

**Comment by JeffreySu** [comment]
是 **wolf@qq.com 这个邮箱发来的吗？

**Comment by JeffreySu** [comment]
@1378955720 可以参考这里：https://github.com/JeffreySu/WeiXinMPSDK/issues/1869#issuecomment-565944975

**Comment by 1378955720** [comment]
> 是 **[wolf@qq.com](mailto:wolf@qq.com) 这个邮箱发来的吗？

不好意思，现在才看到，我还没发过邮箱给你，我稍后可以发给你。

**Comment by JeffreySu** [comment]
@1378955720 后来有发过来吗？

**Comment by yueliuhun** [comment]
这个问题前端做POST前，参数做urlencode处理就行了！

**Comment by fairok** [comment]
这个我在解密profile的时候会有一定概率出现这个问题，前端参数post前也做了encodeURI的
