### ISSUE TITLE
LocalContainerCacheStrategy.Instance 这里的这行代码是做什么用？

### ISSUE THREAD

**Issue by ccccccmd** [JeffreySu/WeiXinMPSDK#2058]
这里有行代码：
https://github.com/JeffreySu/WeiXinMPSDK/blob/b369ffbee848a06e14e8255d8e72943f04ea89b7/src/Senparc.Weixin/Senparc.Weixin/WeixinRegister.cs#L101

上面的代码导致我必须要添加下面的代码 `services.AddMemoryCache();`，即使我用redis缓存。

如果我添加了`AddMemoryCache()`,我的token等是否就会存到local cache中？缓存这块好混乱啊.

https://github.com/Senparc/Senparc.CO2NET/blob/2b5b8703e1357d91eacc230c4248e1e14f43f9f5/Sample/Senparc.CO2NET.Sample.netcore/Startup.cs#L42

从图里看，这个 instance没有什么用，如果有用，应该在外面自行激活好点吧

![image](https://user-images.githubusercontent.com/10289019/70793925-69e4d500-1dd7-11ea-8937-2b76917a22c3.png)

**Comment by JeffreySu** [comment]
这个问题书里面有讲到一些，几方面的原因：
1、大多数的用户并不使用Redis，因此本地缓存是一个默认配置，并且无需任何注册代码即可使用。当然你可以通过注册Redis绕开它，并不会对你的程序有任何不好的影响。
2、本机的消息队列等不需要借助分布式缓存的功能，仍然可能会使用到本地缓存。总之本地缓存在多数系统里面是一个必要的存在。
3、（集成在基础库的中的主要原因）是为了容错降级，当Redis或其他扩展缓存不可用的时候，或者任何故障的时候，方便你热切换到确保可用的本地缓存，可以确保在应激状态下降级运行（当然你也可以阻止这么做）。这个问题即使我们库不提供，也仍然是你在构建一个健壮项目时候必须要考虑到的点（虽然这么做不能解决所有的降级问题）。
--------------------------------------------------
4、关于AddMemoryCache()，这个是官方注册内存缓存的方法，只是启用MemoryCache的一个注册，并不表示你必须使用MemoryCache，只要设置了Redis，仍然会在Redis中。
5、不知何原因看不到您最后的截图，是否能发一个代码的位置？

**Comment by ccccccmd** [comment]
https://github.com/JeffreySu/WeiXinMPSDK/blob/b369ffbee848a06e14e8255d8e72943f04ea89b7/src/Senparc.Weixin/Senparc.Weixin/WeixinRegister.cs#L101

图里的就是这行代码，反编译后的。

所以就是说  即使  services.AddMemoryCache() ，并且也开启了senparc redis的缓存。senparc内部并不会使用local cache存储token是吧。

这次升级为net core 3.1的时候，发现多了这个AddMemoryCache，以前的版本没有这句代码，所有点疑问

**Comment by JeffreySu** [comment]
1、这一条是必须的，因为需要确保本地缓存是激活状态，以做好随时降级的准备。否则让开发者在外部自行处理会更加怪异。对性能也不会有任何影响。
2、对的，AddMemoryCache() 只是一个enable的操作，并不是use的操作，所以对你的存放目标不会有影响（性能上也会不有影响）

**Comment by ccccccmd** [comment]
好的，明白了，谢谢
