### ISSUE TITLE
 AccessTokenContainer.TryGetAccessToken 调用保存 引用版本16.9.104.1

### ISSUE THREAD

**Issue by aehyok** [JeffreySu/WeiXinMPSDK#2059]
System.TypeInitializationException:“The type initializer for 'Nested' threw an exception.”

获取access_token是报错
![image](https://user-images.githubusercontent.com/5900140/70889860-86268300-201e-11ea-9abf-85d5c1f11441.png)

##### 重现问题步骤
var accessToken = AccessTokenContainer.TryGetAccessToken(appId, appSecret); 
见截图，通过注释代码是可以调用到access_token的

##### 模块对应的 .net 版本
- [x] .net core 3.0

##### 开发环境
- [x] Visual Studio 2019

##### 系统环境

- [x] Windows 10版本：

##### 联系方式
Email：455043818@qq.com

**Comment by JeffreySu** [comment]
这个错误是因为没有按照Demo的指导过程进行注册，可以参考一下Demo中startup.cs中的注册过程是否有遗漏代码（包括顺序）。

**Comment by aehyok** [comment]
@JeffreySu  谢谢了，问题解决了。头一次用问了这么个低级的问题，非常感谢回复。
