### ISSUE TITLE
netcore下使用异步oauth功能报错

### ISSUE THREAD

**Issue by mfjiang** [JeffreySu/WeiXinMPSDK#2061]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
netcore下使用异步oauth功能报错

##### 重现问题步骤（如果可以）

1. 在net core 3.0 环境使用oauth相关异步请求异常，比如OAuthApi.GetAccessTokenAsync

##### 发现问题的模块
- [x ] Senparc.Weixin.MP 版本：Senparc.Weixin.MP, Version=16.9.103.2

##### 模块对应的 .net 版本
- [x] .net core 3.x

##### 开发环境
- [x] Visual Studio 2019
##### 缓存环境
- [ x] 其他：

##### 系统环境
- [x] Linux，版本：

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
这个功能一直是好的，请检查一下其他代码，或者提供其他代码。
