### ISSUE TITLE
随机字符串生成重复BUG

### ISSUE THREAD

**Issue by yueliuhun** [JeffreySu/WeiXinMPSDK#2066]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
TenPayV3Util.BuildRandomStr 会有概率生成一样的随机串。实际应用中由于并发高的问题，已经发生了，特地用循环测试了一下。然后把结果导到EXCEL，显示重复。果然会有一些重复

##### 重现问题步骤（如果可以）

for (int i = 0; i < 10000; i++)
            {
                string order_str = string.Format("{0}{1}", DateTime.Now.ToString("yyyyMMddHHmmssfff"), TenPayV3Util.BuildRandomStr(6));//订单号
                context.Response.Write($"{DateTime.Now.ToString("yyyyMMddHHmmssfff")}----{order_str}<br>");
            }

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [ ] .net core 2.x
- [x] .net core 3.x

##### 开发环境

- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [x] Visual Studio 2019
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [x] Windows，版本：
- [ ] Linux，版本：
- [ ] Mac，版本：
- [ ] 其他：

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
对，后面的BuildRandomStr(x)就是用来帮助你避免并发时候的重复的，如果并发量越大，你这个随机字符串就需要越长（当然最大长度应该是有限制的），结合随机数，你肯定在录入订单的时候需要判断当前订单号是否存在，如果存在的话重新获取一次，哪怕你每一位都是随机数，也需要做这一步验证的。
