### ISSUE TITLE
微信退款出错

### ISSUE THREAD

**Issue by ITOL-DNNT** [JeffreySu/WeiXinMPSDK#2075]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
.netcore 3.1下，微信支付的退款报错，排查原因判断为证书的加载出现问题。
查看问题历史，发现企业微信退款出现过相同问题，
附错误详细：
{"StackTrace":"   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)\n   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)\n   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)\n   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\n   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\n   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\n   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)\n   at Senparc.CO2NET.HttpUtility.RequestUtility.HttpResponsePost(String url, CookieContainer cookieContainer, Stream postStream, Dictionary`2 fileDictionary, String refererUrl, Encoding encoding, String certName, Boolean useAjax, Dictionary`2 headerAddition, Int32 timeOut, Boolean checkValidationResult, String contentType)\n   at Senparc.CO2NET.HttpUtility.RequestUtility.HttpPost(String url, CookieContainer cookieContainer, Stream postStream, Dictionary`2 fileDictionary, String refererUrl, Encoding encoding, String certName, Boolean useAjax, Dictionary`2 headerAddition, Int32 timeOut, Boolean checkValidationResult, String contentType)\n   at Senparc.Weixin.TenPay.V3.TenPayV3.CertPost_NetCore(String mchId, String subMchId, String data, String url, Int32 timeOut)\n   at Senparc.Weixin.TenPay.V3.TenPayV3.Refund(TenPayV3RefundRequestData dataInfo, Int32 timeOut)\n   at CloundBox.Store.Consumer.Process.OrderRefundProcess.RefundPayOrderFromWeiXinPay(PlatformOrderReturnNote refundOrder, TenPayV3Info tenpayInfo, PlatformOrder order) in /src/CloundBox.Store.Consumer/Process/OrderRefundProcess.cs:line 106","Message":"An error occurred while sending the request.","Data":{},"InnerException":{"ClassName":"System.IO.IOException","Message":"The response ended prematurely.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at System.Net.Http.HttpConnection.FillAsync()\n   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)\n   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146232800,"Source":"System.Net.Http","WatsonBuckets":null},"HelpLink":null,"Source":"System.Net.Http","HResult":-2146232800}

##### 重现问题步骤（如果可以）

1. TenPayV3.Refund(dataInfo);

##### 发现问题的模块

- [ ] 其他模块：Senparc.Weixin.TenPay.V3

##### 模块对应的 .net 版本

- [x] .net core 3.x

##### 开发环境

- [x] Visual Studio 2019

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：

##### 系统环境

- [x] Windows，版本：
- [x] Linux，版本：

##### 联系方式
Email：450657671@qq.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
请参考一下Demo的做法。在线测试：
1、关注公众号“盛派网络小助手”
2、点击菜单中的【微信支付】
3、任意选择一个产品支付，完成后出现退款提示，点击【确认】
4、可以看到一个退款SUCCESS的状态码
5、刷新网页，看到一个FAIL的状态码（因为已经退款完成，无法重复退款）
6、查看自己的微信对话列表或钱包，是否已经完成退款。

**Comment by ITOL-DNNT** [comment]
.netcore 3.1，你可以试一下这个环境的退款，加载证书会抛出上述异常。
有看到其他网友也指出了相同的问题，低版本是没有问题的。
烦请检查一下。

**Comment by JeffreySu** [comment]
另外您说得挡板是指具体以哪个版本为分界线？

**Comment by ITOL-DNNT** [comment]
> 另外您说得挡板是指具体以哪个版本为分界线？

我们项目上应该是2.0、2.2都使用过，后来升到3.1就不行了。

**Comment by ITOL-DNNT** [comment]
我从其他网友那查阅相关问题时，发现了证书问题，于是我尝试了按这个思路是能够解决问题的。
您说的能在3.1上跑，我这边并不能执行行成功呢。
开发环境vs2019, .netcore3.1, Senparc.Weixin.TenPay 1.5.104。

**Comment by ITOL-DNNT** [comment]
我们项目上应该是2.0、2.2都使用过，后来升到3.1就不行了。
您说的能在3.1上跑，我这边并不能执行行成功呢。
开发环境vs2019, .netcore3.1, Senparc.Weixin.TenPay 1.5.104。

**Comment by ITOL-DNNT** [comment]
问题已解决，切换了N多不同的包，结果是各版本senparc包冲突导致，并非开发环境问题。

**Comment by JeffreySu** [comment]
@ITOL-DNNT 对的，建议使用nuget更新，会自动更新依赖的库。
