### ISSUE TITLE
Senparc.Weixin.MP.Sample 网页授权页面报错

### ISSUE THREAD

**Issue by dongqingfan** [JeffreySu/WeiXinMPSDK#2077]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
给的案例Senparc.Weixin.MP.Sample 运行起来 点击开放平台授权测试 报错，
已经配置的信息
【WeixinToken】【WeixinEncodingAESKey】【WeixinAppId】【WeixinAppSecret】
运行的项目 net45-mvc\Senparc.Weixin.MP.Sample，报错信息为Senparc.Weixin.Exceptions.ErrorJsonResultException:“微信 POST 请求发生错误！错误代码：40013，说明：invalid appid hint: [OM01944809]”，
查到的参数信息 {"component_appid":"Component_Appid","component_appsecret":"Component_Secret","component_verify_ticket":""}
 是因为开放平台的参数没有配吗，但是我不需要开放平台啊，在global中将注册第三方平台的代码去掉，仍然报错，耦合性太强了

联系邮件 dongqinglove@126.com

**Comment by JeffreySu** [comment]
这个错误说的很清楚了，这个就是appId不合法，你要自己检查合法性。另外Component_Appid给第三方平台用的，不是给普通公众号用的，你是不是用错模块了?

第三方平台和公众号平台的模块是完全分离的，顶多是复用，即插即用，相互不影响，不知道你说的耦合性是指啥？
