### ISSUE TITLE
CustomMessageHandler  Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by 97686773** [JeffreySu/WeiXinMPSDK#2078]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 重现问题步骤（如果可以）

1.  .net core 3.0下接受微信公众号推送时会报错
关键代码如下
   var messageHandler = new CustomMessageHandler(Request.GetRequestMemoryStream(), postModel, 10);

     Request.GetRequestMemoryStream(),手动查看此方法是可以获取到xml内容的，但是这里会throw
Object reference not set to an instance of an object.我是用当前最新版本的官方demo部署之后，用官网的消息测试工具是可以复现的。

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [ ] .net core 2.x
- [x] .net core 3.x

##### 开发环境

- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [x] Visual Studio 2019
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [x] Windows，版本：
- [ ] Linux，版本：
- [ ] Mac，版本：
- [ ] 其他：

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
这里有我们线上 .NET Core 的 Demo：https://sdk.weixin.senparc.com/SimulateTool
您可以试一下，这个方法本身应该是没有问题的，需要找程序其他地方的原因。

另外您是所有的请求都有问题吗？

**Comment by lishewen** [comment]
UseEnableRequestRewind ？

**Comment by 97686773** [comment]
> 这里有我们线上 .NET Core 的 Demo：https://sdk.weixin.senparc.com/SimulateTool
> 您可以试一下，这个方法本身应该是没有问题的，需要找程序其他地方的原因。
> 
> 另外您是所有的请求都有问题吗？
并不是，我是下载的demo，然后参考的Senparc.Weixin.Sample.NetCore3的引用，将其他的项目都引入，然后参考startup配置好，用的weixinController就出的这个问题。
是我有什么东西没有引入吗

**Comment by 97686773** [comment]
> UseEnableRequestRewind ？

用不用这个，都有这个问题

**Comment by 97686773** [comment]
> 这里有我们线上 .NET Core 的 Demo：https://sdk.weixin.senparc.com/SimulateTool
> 您可以试一下，这个方法本身应该是没有问题的，需要找程序其他地方的原因。
> 
> 另外您是所有的请求都有问题吗？

做了几次测试发现，在本地debug和release下都能够正常返回结果，发布之后在服务器上，return new FixWeixinBugWeixinResult(messageHandler);//v0.8+ 是返回的空结果的，messageHandler.ResponseDocument其实是等于null的，无论是独立部署还是框架依赖，都不行。
服务器上安装的是dotnet-hosting-3.0.2-win.exe
其他功能都是正常的，唯独messagehandler这块有问题，此项目是有其他依赖吗
