### ISSUE TITLE
源码无法编译通过

### ISSUE THREAD

**Issue by sx5486510** [JeffreySu/WeiXinMPSDK#2087]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
1>------ 已启动全部重新生成: 项目: Senparc.Weixin, 配置: Debug Any CPU ------
1>CSC : error CS2001: 未能找到源文件“D:\work\红星公众号支付\WeiXinMPSDK\src\Senparc.Weixin\Senparc.Weixin\Utilities\BrowserUtility\BrowserUtility.cs”。
2>------ 已启动全部重新生成: 项目: Senparc.Weixin.Work, 配置: Debug Any CPU ------
2>CSC : error CS2001: 未能找到源文件“D:\work\红星公众号支付\WeiXinMPSDK\src\Senparc.Weixin.Work\Senparc.Weixin.Work\MessageHandlers\Middleware\WorkMessageHandlerMiddleware.cs”。

检查发现git中也没有这两个文件

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ x] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [ ] .net core 2.x
- [x] .net core 3.x

##### 开发环境

- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [x] Visual Studio 2019
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [x] Windows，版本：
- [ ] Linux，版本：
- [ ] Mac，版本：
- [ ] 其他：

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by sx5486510** [comment]
还有 Senparc.Weixin.AspNetHttpUtility.UrlUtility.GenerateOAuthCallbackUrl(httpContext, "/TenpayV3/OAuthCallback");

这个GenerateOAuthCallbackUrl在哪里定义的？

**Comment by JeffreySu** [comment]
这个文件应该有的，你确定你打开的是 Senparc.Weixin.Sample.NetCore3.vs2019.sln 这个解决方案吗？

**Comment by cnbabycrazy** [comment]
我也是这个问题。Senparc.Weixin.Work.net45.sln

**Comment by JeffreySu** [comment]
@cnbabycrazy  开错解决方案了，请打开上面写的Senparc.Weixin.Sample.NetCore3.vs2019.sln ，或者查看readme，根据您实际的环境选择不同的解决方案文件。
