### ISSUE TITLE
企业客服回调消息处理好像没有实现，无法转换

### ISSUE THREAD

**Issue by ghost** [JeffreySu/WeiXinMPSDK#209]
http://qydev.weixin.qq.com/wiki/index.php?title=%E4%BC%81%E4%B8%9A%E5%AE%A2%E6%9C%8D%E5%9B%9E%E8%B0%83

**Comment by JeffreySu** [comment]
单元测试：https://github.com/JeffreySu/WeiXinMPSDK/blob/a2c7bdb196b518461a80b5e70fe6f8c84c46933b/src/Senparc.Weixin.Work/Senparc.Weixin.Work.Test/EntityHelperTest.cs#L33
