### ISSUE TITLE
尚无已经注册的AppId，请先使用AccessTokenContainer.Register完成注册（全局执行一次即可）！模块：WeChat_OfficialAccount

### ISSUE THREAD

**Issue by wtujvk** [JeffreySu/WeiXinMPSDK#2094]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
调用方法
AccessTokenContainer.TryGetAccessToken(appId, appSecret, true);
报错：
尚无已经注册的AppId，请先使用AccessTokenContainer.Register完成注册（全局执行一次即可）！模块：WeChat_OfficialAccount
##### 重现问题步骤（如果可以）

1. 测试号可以正常接入公众号。
2. 使用正式公众号接入，报错。使用在线接口调试发现是ip没有加入白名单。
错误信息应该是白名单信息才对而不应该是系统异常？
查看TryGetAccessToken方法，发现是使用异步注册，然后获取的，是否是获取的时候还未注册呢？

相关业务场景:
（1）接入多公众号的情况，并不能在系统初始化的时候注册公众号。
（2）接入公众号包括 ： 接入新的公众号，修改公众号 appSecret, 获取公众号appidOrAccessToken

##### 发现问题的模块

- [x] Senparc.Weixin 版本：6.6.104.1
- [x] Senparc.Weixin.MP 版本：16.9.104.1
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [x] .net 4.5， net4.6.1
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [ ] .net core 2.x
- [ ] .net core 3.x

##### 开发环境

- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [x] Visual Studio 2019
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [x] Windows，版本：
- [ ] Linux，版本：
- [ ] Mac，版本：
- [ ] 其他：

##### 联系方式
Email：1170971516@qq.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
1、正式账号必须要开通白名单，否则确实会 SDK 当做未被注册处理，受到到这个错误。
2、多公众号可以注册，便利所有公众号的AppId和Secret，使用 AccessTokenContainer.RegisterAsync() 方法注册即可（其他类型凭证对应到各自的Container下）。
3、修改公众号secret只需要重新注册就行了。
4、appidOrAccessToken 是出入参数，可以输入 AppId，或者 AccessToken（从AccessTokenContainer获取或者CommonApi获取都可以），这个不是一个特定的全局变量。

**Comment by hanabi1224** [comment]
@JeffreySu 类似的 OAuthAccessTokenContainer.GetAccessToken 也报同样的错不合理吧，code每个页面请求都不一样，不可能只注册一次啊

**Comment by wtujvk** [comment]
1. TryGetAccessToken方法是否可用？注册并返回可用的AccessToken
2. AccessTokenContainer.Register
  2.1 是否可用重复调用（相同AppId,），会更新AccessToken吗？
  2.2 返回的异常是否和接口在线调试工具的一样？例如appSecret错误 或者未加入白名单等

**Comment by JeffreySu** [comment]
@hanabi1224  OAuthAccessTokenContainer 的注册不是一人一次，或者一个账号一次，而是一个请求一次，请看 Key 的生成规则：

https://github.com/JeffreySu/WeiXinMPSDK/blob/75b41e760e8a336450f28ebf6be1a64fb63047ea/src/Senparc.Weixin.MP/Senparc.Weixin.MP/Containers/OAuthAccessTokenContainer.cs#L121

**Comment by JeffreySu** [comment]
> 1. TryGetAccessToken方法是否可用？注册并返回可用的AccessToken
> 2. AccessTokenContainer.Register
>    2.1 是否可用重复调用（相同AppId,），会更新AccessToken吗？
>    2.2 返回的异常是否和接口在线调试工具的一样？例如appSecret错误 或者未加入白名单等

1、这个方法是可以的，但是没有办法确保当前获取的 AccessToken 凭证时可用的，也就是说在发生错误的时候，你需要自己重试；而是用系统推荐的方法，每次调用接口传入 appId（需要提前注册才可以，因为系统需要保留appSecret），这样发生凭证过期时，SDK 会为你自动重试。

2.1 不会。
2.2 如果有异常，本身就会包含详细的错误信息返回的，请看一下这个异常的定义：

https://github.com/JeffreySu/WeiXinMPSDK/blob/75b41e760e8a336450f28ebf6be1a64fb63047ea/src/Senparc.Weixin/Senparc.Weixin/Exceptions/ErrorJsonResultException.cs#L45

其中包含了 WxJsonResult，里面收纳了微信服务器返回的完整的异常信息。

**Comment by wtujvk** [comment]
l类似于 IP白名单的问题 #2116
目前版本<package id="Senparc.Weixin.MP" version="16.10.304" targetFramework="net461" />
当appSecret错误或者白名单问题 统一抛出异常而没有返回 ErrorJsonResultException

**Comment by wtujvk** [comment]
由于调用了CommApi.GetToken方法，接入公众号后调用微信接口也会抛出这个异常（例如ip变更了（接入后不在白名单）等等）：
尚无已经注册的AppId，请先使用AccessTokenContainer.Register完成注册（全局执行一次即可）！模块：WeChat_OfficialAccount

**Comment by wtujvk** [comment]
可以看下这个
https://github.com/JeffreySu/WeiXinMPSDK/pull/2136/commits/808805f79f21f668f6bc3d5d1ce7ab7c1218395c
