### ISSUE TITLE
JavaScriptSerializer序列化dynamic类型对象有问题，建议使用NewtonSoft.Json进行序列化

### ISSUE THREAD

**Issue by wushancool** [JeffreySu/WeiXinMPSDK#210]
Data:{
    first:{value:"尊敬的标致车主，您好。您预约的车辆保养方案已发送。"},
    keyword1:{value:"汽车保养"},
    keyword2:{value:"保养方案查询"},
    keyword3:{value:"2014年8月26日"},
    remark:{value:"请点击查看您爱车的保养方案详情。"}
    
  }，发送模板消息的时候用不固定的json对象传送给MVC自动反序列化成一个   [Required]
        public dynamic Data { get; set; }dynamic对象的时候，发送模板消息前序列化成字符串的时候，使用JavaScriptSerializer进行序列化会变成很多[]，使用Newston.Json可以正常序列化。不知道能不能帮忙更新，或者有别的解决办法。我现在被卡在这个地方了。

**Comment by JeffreySu** [comment]
1、可以自己写一个自定义Converter的方法（SDK已经提供了）
2、不适用第三方的插件有一定的原因，请看：http://weixin.senparc.com/QA/QAPost/Item/87
