### ISSUE TITLE
UseSenparcWeixin缓存判断问题

### ISSUE THREAD

**Issue by mpnet** [JeffreySu/WeiXinMPSDK#2107]
```
.UseSenparcWeixin(senparcWeixinSetting, weixinRegister =>
{
       weixinRegister.UseSenparcWeixinCacheCsRedis();
});

```
缓存使用CsRedis组件，因此不会引用Senparc.Weixin.Cache.Redis，但
在这个方法UseSenparcWeixin里
下面这段代码会被执行，然后报错 Console.WriteLine(ex.Message);
按理如果用CsRedis组件，这段代码应该做判断的，不应该被执行
`   var redisInstance = ReflectionHelper.GetStaticMember("Senparc.Weixin.Cache.Redis", "Senparc.Weixin.Cache.Redis", "RedisContainerCacheStrategy", "Instance");`

报错就报错吧，为嘛要把它输出到控制台，强迫症受不了

**Comment by JeffreySu** [comment]
@mpnet 输出到控制台是因为发生异常了（程序集没有加载），总需要做一个提示告诉程序发生了什么，当然这里也可以想办法检查之后跳过，我这边可以给一个是否打印的选项。

不过感谢提示了这里这样一个情况，其实这里只预加载了Redis，没有加载CsRedis，CsRedis也是需要加载一下的。

**Comment by JeffreySu** [comment]
已经发布新版本，请更新查看，非常感谢！
