### ISSUE TITLE
csRedis 包消息去重缓存时间是-1 永久缓存问题

### ISSUE THREAD

**Issue by WangDrama** [JeffreySu/WeiXinMPSDK#2111]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
你们最近换的csRedis包有问题，消息去重里面是放在redis 里面，但是给了有效期还是是-1 表示永久，图一是你们源码，图二是我提出来的列子。请查收并确定
![image](https://user-images.githubusercontent.com/33739071/75606817-a2b95e00-5b2b-11ea-8953-6feeb1f9536a.png)
![image](https://user-images.githubusercontent.com/33739071/75606821-abaa2f80-5b2b-11ea-82f9-0f24f7192936.png)

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [ ] .net core 2.x
- [x] .net core 3.x

##### 开发环境

- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [x] Visual Studio 2019
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [x] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [x] Windows，版本：
- [ ] Linux，版本：
- [ ] Mac，版本：
- [ ] 其他：

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by WangDrama** [comment]
这是更换老版本redis后的redis 对比

![image](https://user-images.githubusercontent.com/33739071/75606963-5707b400-5b2d-11ea-9b3d-783d0e093b26.png)

**Comment by JeffreySu** [comment]
@WangDrama 这个地方的上下文本身默认就没有设置时间限制，并且有自动排序清楚或者清空的功能。如果过期了，下一条消息进来的时候就会自动删除。

**Comment by JeffreySu** [comment]
已经发布新版本，请查看。
