### ISSUE TITLE
IP白名单的问题

### ISSUE THREAD

**Issue by mpnet** [JeffreySu/WeiXinMPSDK#2116]
`/// <summary>
        /// 获取凭证接口
        /// </summary>
        /// <param name="grant_type">获取access_token填写client_credential</param>
        /// <param name="appid">第三方用户唯一凭证</param>
        /// <param name="secret">第三方用户唯一凭证密钥，既appsecret</param>
        /// <returns></returns>
        [ApiBind(NeuChar.PlatformType.WeChat_OfficialAccount, "CommonApi.GetToken", true)]
        public static AccessTokenResult GetToken(string appid, string secret, string grant_type = "client_credential")
        {
            //注意：此方法不能再使用ApiHandlerWapper.TryCommonApi()，否则会循环
            var url = string.Format(Config.ApiMpHost + "/cgi-bin/token?grant_type={0}&appid={1}&secret={2}",
                                    grant_type.AsUrlData(), appid.AsUrlData(), secret.AsUrlData());

            AccessTokenResult result = Get.GetJson<AccessTokenResult>(CommonDI.CommonSP, url);//此处为最原始接口，不再使用重试获取的封装

            if (Config.ThrownWhenJsonResultFaild && result.errcode != ReturnCode.请求成功)
            {
                var unregisterAppIdEx = new UnRegisterAppIdException(null, $"尚无已经注册的AppId，请先使用AccessTokenContainer.Register完成注册（全局执行一次即可）！模块：{NeuChar.PlatformType.WeChat_OfficialAccount}");
                throw unregisterAppIdEx;//抛出异常
            }

            return result;
        }`

因IP没在白名单内，调试了一下午一直报“尚无已经注册的AppId”，然后就不停的在注册环节找问题，最后才发现不是代码的问题，好大一坑啊，这个ip白名单的报错能不能单独做下判断的，笼统的抛出个“尚无已经注册的AppId”，还以为是代码的问题

**Comment by JeffreySu** [comment]
对的，遇到这个错误首先查看配置，然后查看白名单。

**Comment by dashenxian** [comment]
ip没有加入白名单时，在使用 工具箱-》异步方法测试-》的时候会进入死循环

**Comment by JeffreySu** [comment]
@dashenxian 你用的是最新版本的代码？能够一直重现？

**Comment by dashenxian** [comment]
是的 我下的最新版代码，在这里
![image](https://user-images.githubusercontent.com/18696614/83939763-139aa100-a812-11ea-8ab8-abf612f63f74.png)，我用的我的微信key和消息模板，手动调试跳过验证码直接发消息，会一直死循环，无法返回结果

**Comment by JeffreySu** [comment]
你看一下是不是在异常发生的时候，触发了 Sample 中的异常模板消息（或者客服消息），其中又发生了什么异常，导致死循环了？这个属于 Sample 里面的一个演示，根据你自己的情况排除掉就行了。
