### ISSUE TITLE
企业微信获取通信录Secret与应用Secret无法同时配置

### ISSUE THREAD

**Issue by yang524433** [JeffreySu/WeiXinMPSDK#2128]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
使用应用Secret时无权调用通讯录信息接口时必须使用通讯录Secret获取

##### 微信官方文档 URL
https://work.weixin.qq.com/api/doc/90000/90135/90193

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：6.7.305
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：7.5.304
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：3.7.304
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [x] .net core 3.x

##### 开发环境
- [x] Visual Studio 2019

##### 缓存环境

- [x] 服务器内存缓存（默认）

##### 系统环境

- [x] Windows，版本：win 10

##### 联系方式
Email：54656180@qq.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
每个应用的 secret 都可以单独注册的，企业微信里面，corpId+secret(单应用)是一个key的组合，所以不会冲突，可以多次注册。
