### ISSUE TITLE
卡券开放类目实体定义错误

### ISSUE THREAD

**Issue by leeson0219** [JeffreySu/WeiXinMPSDK#213]
在 GetApplyProtocolJsonResult 实体中：

`public GetApplyProtocol_Category category { get; set;} `
应为：`public List<GetApplyProtocol_Category> category { get; set;}`

`public GetApplyProtocol_Secondary_Category secondary_category { get; set; }`
应为：`public List<GetApplyProtocol_Secondary_Category> secondary_category { get; set; }`

**Comment by AnnXu** [comment]
感谢你发现的这个问题，已经修改了。
