### ISSUE TITLE
接入公众号没有成功也没有异常提示

### ISSUE THREAD

**Issue by wtujvk** [JeffreySu/WeiXinMPSDK#2131]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
公众号未注册成功确没有提示，微信接口调用不了。

##### 重现问题步骤（如果可以）
1. 使用错误的AppSecret 或者 ip不在白名单正式公众号 不会报错 也没有任何提示。
2. 接入后下载微信菜单 报错，系统错误system_error
通过微信在线接口调试， 发现是 ip不在白名单内。重置AppSecret 后依然没有任何提示。
##### 发现问题的模块

- [ ] Senparc.Weixin 版本：6.7.400
- [x] Senparc.Weixin.MP 版本：16.10.400
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [x] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [ ] .net core 2.x
- [] .net core 3.x

##### 开发环境

- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [x] Visual Studio 2019
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [x] Windows，版本：
- [ ] Linux，版本：
- [ ] Mac，版本：
- [ ] 其他：

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by wtujvk** [comment]
异步无法抛出异常，抛出的异常主线程接受不到。但是没有注册成功，主线程并不知道。
AccessToken的管理除了异步外能否支持（原生的）同步呢， 感觉同步更稳定，异步经常出现各种问题 。

**Comment by JeffreySu** [comment]
@wtujvk 你异步的代码是如何执行的？

另外一个问题是异步可以传一个CancellationTokenSource，不过工程量很会比较大，调用也会比较麻烦。

**Comment by wtujvk** [comment]
之前的版本
Mp14.10.3 基本上无太大问题，能正常提示接入公众号的问题。
Mp16.9.104.1 是抛出异常的，只是提示不友好（#2094 ）。
代码调用：
`          AccessTokenContainer.RemoveFromCache(appId);
            JsApiTicketContainer.RemoveFromCache(appId);
            AccessTokenContainer.TryGetAccessTokenAsync(appId, appSecret, true).ConfigureAwait(false).GetAwaiter().GetResult();
`

**Comment by wtujvk** [comment]
需要重写CommonApi.GetToken方法 ， 这个方法在什么时候用到呢 ?
判断容器判断过期的方法 和添加到容器 的方法是什么呢？ 可以直接调用容器更新方法的AccessTokenContainer.UpdateAsync （Update） 吗 ？

**Comment by JeffreySu** [comment]
CommonApi.GetToken 基本上不需要使用，你也不用关心token，只要调用的时候传入appId就行了。相关详细的介绍可以找一个高级接口查源码，或者看教材。
