### ISSUE TITLE
netcore 2.2无法从nuget安装Senparc.Weixin

### ISSUE THREAD

**Issue by yinanrong** [JeffreySu/WeiXinMPSDK#2140]
##### 问题描述
无法正常安装Senparc.Weixin,依赖项Senparc.Weixin.CO2NET在netstandard 2.2环境下依赖的
Microsoft.Extensions.DependencyInjection.Abstractions版本为3.1.2

##### 发现问题的模块

- [X] Senparc.Weixin 版本：6.7.401
- [X] Senparc.Weixin.CO2NET 版本：1.3.104

##### 模块对应的 .net 版本
- [x] .net core 2.2

##### 开发环境
- [X] Visual Studio 2019

**Comment by JeffreySu** [comment]
3.1.2 应该也支持 .net core 2.2 的。
