### ISSUE TITLE
Sample里的一个文件没有指定文件编码导致WeChatSampleBuilder的时候处理完的中文乱码

### ISSUE THREAD

**Issue by coffee0818** [JeffreySu/WeiXinMPSDK#2149]
##### 问题描述
我在win下没有用git pull命令，直接点的download zip下载的文件，发现今天下载的/Samples/netcore3.0-mvc/Senparc.Weixin.Sample.NetCore3/Startup.cs的文件没有指定编码，其它.cs文件都是UTF-8/UTF-8-BOM格式编码，导致WeChatSampleBuilder处理完后该文件被强制转换为了UTF-8编码导致注释和代码中的一些中文出现了乱码。（注释乱码倒无所谓，主要是有一小部分代码里面也有中文）

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [x] 其他模块：Samples

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [ ] .net core 2.x
- [x] .net core 3.x

##### 开发环境

- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [x] Visual Studio 2019
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [x] Windows，版本：
- [ ] Linux，版本：
- [ ] Mac，版本：
- [ ] 其他：

**Comment by JeffreySu** [comment]
已经处理，非常感谢！

另外友情提醒一下：WeChatSampleBuilder 很快会有新的更新发布（会使用全新的方式），当前主版本已经停止更新了。

**Comment by coffee0818** [comment]
好的， 我会密切关注的，也非常感谢您开源的WeiXinMPSDK！
