### ISSUE TITLE
customApi能否加上customservice参数

### ISSUE THREAD

**Issue by andysjt** [JeffreySu/WeiXinMPSDK#215]
发送消息能否加个customservice参数：
{
    "touser":"OPENID",
    "msgtype":"text",
    "text":
    {
         "content":"Hello World"
    },
    "customservice":
    {
         "kf_account": "test1@kftest"
    }
}
文档地址：https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421140547&token=&lang=zh_CN

我们的api里没有这个参数

**Comment by AnnXu** [comment]
Hi，
 那你加了这个参数之后，有对它进行测试过吗？有影响吗？

**Comment by andysjt** [comment]
有影响啊，比如发消息的时候，我需要用某个多客服的头像和昵称去发，加上这个参数就可以了。 把消息从公众号发给关注者，头像和昵称就变成多客服的了，而不是公众号默认的

**Comment by AnnXu** [comment]
您具体说的是哪个接口的方法，能否直接发上来一下。

**Comment by AnnXu** [comment]
非常感谢你的意见，参数已加上去 @andysjt
