### ISSUE TITLE
Senparc.Weixin.Config.SenparcWeixinSetting.Items["key"] 得不到值的bug

### ISSUE THREAD

**Issue by dodu2014** [JeffreySu/WeiXinMPSDK#2156]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
如题在 appsettings.json 中配置的 items 节点信息, 通过 Senparc.Weixin.Config.SenparcWeixinSetting.Items["key"] 得不到值.

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [ ] .net core 2.x
- [x] .net core 3.x

##### 开发环境

- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [x] Visual Studio 2019
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [x] Windows，版本：
- [ ] Linux，版本：
- [ ] Mac，版本：
- [ ] 其他：

##### 联系方式
Email：dodu@live.cn

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
您先跑一下 .NET Core Sample，里面的结果应该是正确的，然后您再对比一下自己代码里面有什么做的不一样的地方。

下面是 Demo 的返回结果：
![image](https://user-images.githubusercontent.com/2281927/79644095-44c6ff80-81d9-11ea-9cf7-edb7644a0449.png)

对应配置：
https://github.com/JeffreySu/WeiXinMPSDK/blob/e78223529be5444563f42c74dfd4459fde8a0799/Samples/netcore3.0-mvc/Senparc.Weixin.Sample.NetCore3/appsettings.json#L105
