### ISSUE TITLE
企业号删除永久素材的函数，拼接url字符串的时候最后多了一个 }

### ISSUE THREAD

**Issue by redshana** [JeffreySu/WeiXinMPSDK#216]
/// <summary>
        /// 删除永久素材
        /// </summary>
        /// <param name="accessToken"></param>
        /// <param name="agentId"></param>
        /// <param name="mediaId"></param>
        /// <returns></returns>
        public static QyJsonResult DeleteForeverMaterial(string accessToken, int agentId, string mediaId)
        {
            var url =
                string.Format(
                    "https://qyapi.weixin.qq.com/cgi-bin/material/del?access_token={0}&agentid={1}&media_id={2}}",
                    accessToken.AsUrlData(), agentId, mediaId.AsUrlData());

            return CommonJsonSend.Send<QyJsonResult>(null, url, null, CommonJsonSendType.GET);
        }

**Comment by AnnXu** [comment]
Thanks,已将括号去掉！
