### ISSUE TITLE
TenPayV3.Refund 退款netcore  运行centos服务器无法退款 报 The 'hr' start tag on line 6 position 2 does not match the end tag of 'body'.

### ISSUE THREAD

**Issue by h0730303779** [JeffreySu/WeiXinMPSDK#2173]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
The 'hr' start tag on line 6 position 2 does not match the end tag of 'body'. Line 7, position 3.
![24_6(A6R%%556N89%G2HN31](https://user-images.githubusercontent.com/16299810/81303966-ff4a7380-90ae-11ea-81c4-61162fa30f16.png)
![NV0R@{0D$L5~2}A5}MIRG@7](https://user-images.githubusercontent.com/16299810/81303970-007ba080-90af-11ea-9c54-fbbf1c5e5e49.png)

##### 重现问题步骤（如果可以）

.发布到 centos 服务器 出问题   本地没问题可以正常退款开发环境是win

##### 微信官方文档 URL
1

##### 微信官方文档快照（直接复制关键内容到下方）
1

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：6.6.104.1
- [ ] Senparc.Weixin.MP 版本：16.9.104.1
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] Senparc.Weixin.TenPay： 1.5.104

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [X ] .net core 2.x
- [] .net core 3.x

##### 开发环境

- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [x] Visual Studio 2019
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [x] Windows，版本：
- [ ] Linux，版本：
- [ ] Mac，版本：
- [ ] 其他：

##### 联系方式
Email：1

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
能跟踪到收到的信息吗？感觉是收到了错误的xml信息？

**Comment by h0730303779** [comment]
> 能跟踪到收到的信息吗？感觉是收到了错误的xml信息？


腾讯返回回来的信息是没问题的  dataInfo数据 能正常序列化

**Comment by JeffreySu** [comment]
看一下这个result的内容，不要ToJson()

**Comment by h0730303779** [comment]
> 看一下这个result的内容，不要ToJson()

![image](https://user-images.githubusercontent.com/16299810/81561978-accac900-93c6-11ea-96c0-db085599409f.png)
原因知道了.  为什么 centos环境 返回回来的 dataInfo 没有xml数据?

**Comment by JeffreySu** [comment]
@h0730303779  你能用断点或者日志跟踪到里面的过程吗？

**Comment by h0730303779** [comment]
> @h0730303779 你能用断点或者日志跟踪到里面的过程吗？

不能 ,因为我本地 没问题(win10)  服务器才不行 centos  现在除了退款 别的都没问题 困惑

**Comment by JeffreySu** [comment]
@h0730303779 查一下证书加载的问题。

**Comment by h0730303779** [comment]
> @h0730303779 查一下证书加载的问题。

我觉得不是        如果证书有问题 那我支付的时候为什么可以呢

**Comment by JeffreySu** [comment]
支付（收款）的时候不需要使用证书，你资金账户现金流出的环节才需要。

**Comment by h0730303779** [comment]
> 支付（收款）的时候不需要使用证书，你资金账户现金流出的环节才需要。

这样啊  那估计就是证书地址问题吧  配置json文件里我直接写Certs/apiclient_cert.p12的
服务器上站目录下也是有的

**Comment by h0730303779** [comment]
> 支付（收款）的时候不需要使用证书，你资金账户现金流出的环节才需要。

App_Data/SenparcTraceLog  也没提示 证书找不到的问题 确定是证书吗? 我吧证书删了 支付的时候日志能看到 提示没证书

**Comment by JeffreySu** [comment]
确定：微信收款是不需要证书的（cert/p12/pfx等），对外支付是需要的（如退款、打款到个人余额/银行卡等）。

**Comment by houta-higuchi** [comment]
这个肯定是证书问题了。你可以按照我的方法排查下  
首先我有另外用日志框架（我用的是NLog，这个不重要，能打到日志即可）,退款失败看到如下日志  
```
2020-05-27 13:55:41.5293|100|INFO|System.Net.Http.HttpClient.1xxxxxxxxx_.LogicalHandler|Start processing HTTP request POST https://api.mch.weixin.qq.com/secapi/pay/refund |url: http://weixin/customerapp/weixin/wxpayV2/refund|action: Refund
2020-05-27 13:55:41.5293|100|INFO|System.Net.Http.HttpClient.1xxxxxxxxx_.ClientHandler|Sending HTTP request POST https://api.mch.weixin.qq.com/secapi/pay/refund |url: http://weixin/customerapp/weixin/wxpayV2/refund|action: Refund
2020-05-27 13:55:41.6101|101|INFO|System.Net.Http.HttpClient.1xxxxxxxxx_.ClientHandler|Received HTTP response after 68.46170000000001ms - BadRequest |url: http://weixin/customerapp/weixin/wxpayV2/refund|action: Refund
2020-05-27 13:55:41.6101|101|INFO|System.Net.Http.HttpClient.1xxxxxxxxx_.LogicalHandler|End processing HTTP request after 91.99730000000001ms - BadRequest |url: http://xxx/wxpayV2/refund|action: Refund
2020-05-27 13:55:41.6660||ERROR|weixin_service.Controllers.WxPayControllerV2|订单号：SHOP_10000002_2020052765314发起退款失败---系统异常 System.Xml.XmlException: The 'hr' start tag on line 6 position 2 does not match the end tag of 'body'. Line 7, position 3.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowTagMismatch(NodeData startTag)
   at System.Xml.XmlTextReaderImpl.ParseEndElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text)
   at Senparc.Weixin.TenPay.V3.TenPayV3Result..ctor(String resultXml)
   at Senparc.Weixin.TenPay.V3.Result..ctor(String resultXml)
   at Senparc.Weixin.TenPay.V3.RefundResult..ctor(String resultXml)
   at Senparc.Weixin.TenPay.V3.TenPayV3.Refund(IServiceProvider serviceProvider, TenPayV3RefundRequestData dataInfo, Int32 timeOut)
```  
*System.Net.Http.HttpClient.1xxxxxxxxx_.ClientHandler*，这里的1xxxxxxxxx就是商户号，看到了BadRequest应该就是证书问题了。然后我每次启动项目都加入证书  
```
services.AddCertHttpClient(item["mch_id"] + "_", item["mch_id"] + "", item["certpath"] + "");
```  
这样就没有问题了

**Comment by houta-higuchi** [comment]
不过有个问题是，我之前使用的这样的注册证书的方式，现在发现不行了  
```
TenPayV3InfoCollection.Register(new TenPayV3Info(item["appid"] + "", item["app_secret"] + "",
                item["mch_id"] + "", item["paykey"] + "",
                item["certpath"] + "", item["mch_id"] + "",
                "", ""), "商家" + item["id"]);
```

**Comment by h0730303779** [comment]
![image](https://user-images.githubusercontent.com/16299810/83259618-f9960880-a1ea-11ea-93de-49d9e387b584.png)
![image](https://user-images.githubusercontent.com/16299810/83259672-0fa3c900-a1eb-11ea-9fb6-3c50e5647b58.png)

确实存在的 请问 有没有存在的方法或者属性来确认 sdk是否正确读到了证书呢

> 确定：微信收款是不需要证书的（cert/p12/pfx等），对外支付是需要的（如退款、打款到个人余额/银行卡等）。

**Comment by h0730303779** [comment]
> 不过有个问题是，我之前使用的这样的注册证书的方式，现在发现不行了
> 
> ```
> TenPayV3InfoCollection.Register(new TenPayV3Info(item["appid"] + "", item["app_secret"] + "",
>                 item["mch_id"] + "", item["paykey"] + "",
>                 item["certpath"] + "", item["mch_id"] + "",
>                 "", ""), "商家" + item["id"]);
> ```

谢谢,  现在没办法用了  
TenPayV3.Refund(dataInfo) 没有给证书的参数了. 直接sdk自己去读了

**Comment by JeffreySu** [comment]
那个.p12路径必须是物理路径（注意看后面注释）。

现在.net core的证书加载方式已经和.net framework不同了，按照我们Demo推荐的做法应该是可以的（如果有更好的方法欢迎讨论）。

**Comment by h0730303779** [comment]
> 那个.p12路径必须是物理路径（注意看后面注释）。
> 
> 现在.net core的证书加载方式已经和.net framework不同了，按照我们Demo推荐的做法应该是可以的（如果有更好的方法欢迎讨论）。

原来如此  感谢
不过对于相对路径 我都是自动区分当前OS环境
win  Directory.GetCurrentDirectory() 读取本地路径
liunx AppContext.BaseDirectory 读取本地路径

**Comment by h0730303779** [comment]
> 那个.p12路径必须是物理路径（注意看后面注释）。
> 
> 现在.net core的证书加载方式已经和.net framework不同了，按照我们Demo推荐的做法应该是可以的（如果有更好的方法欢迎讨论）。

再请问下  我证书改成绝对路径之后 出新提示了

The handler does not support client authentication certificates with this combination of libcurl (7.29.0) and its SSL backend ("NSS/3.36"). An SSL backend based on "OpenSSL/1.0.2l" is required. Consider using System.Net.Http.SocketsHttpHandler.

**Comment by h0730303779** [comment]
> > 那个.p12路径必须是物理路径（注意看后面注释）。
> > 现在.net core的证书加载方式已经和.net framework不同了，按照我们Demo推荐的做法应该是可以的（如果有更好的方法欢迎讨论）。
> 
> 再请问下 我证书改成绝对路径之后 出新提示了
> 
> The handler does not support client authentication certificates with this combination of libcurl (7.29.0) and its SSL backend ("NSS/3.36"). An SSL backend based on "OpenSSL/1.0.2l" is required. Consider using System.Net.Http.SocketsHttpHandler.
> 
> 试过隔壁 issue 提供的代码
> `string data = dataInfo.PackageRequestHandler.ParseXML(); var cer = new X509Certificate2(tenPayV3Info.CertPath, tenPayV3Info.CertSecret, X509KeyStorageFlags.PersistKeySet | X509KeyStorageFlags.MachineKeySet); var handler = new HttpClientHandler(); handler.ClientCertificates.Add(cer); HttpClient client = new HttpClient(handler); var content = new StringContent(data, Encoding.UTF8); var request = client.PostAsync($"https://api.mch.weixin.qq.com/secapi/pay/refund", content).GetAwaiter().GetResult(); var response = request.Content.ReadAsStreamAsync().GetAwaiter().GetResult(); var xmlDoc = new XmlDocument(); xmlDoc.Load(response); RefundResult refundResult = new RefundResult(xmlDoc.InnerXml);`
> 一样 错 请问 别人最后都怎么处理的?

好了解决 感谢各位 最后还是手动安装OpenSSL
Centos curl ssl 替换 NSS 为 OpenSSL

**Comment by dodu2014** [comment]
为什么同样的配置, 之前是正确的, 现在怎么异常了呢?

**Comment by LmuQuan** [comment]
起码要输出微信返回的报文,给我们排查下是什么错误啊... 唉

**Comment by h0730303779** [comment]
> 起码要输出微信返回的报文,给我们排查下是什么错误啊... 唉

你眼神不好吗 挖坟..我最后说解决了  SSL的证书问题

**Comment by JeffreySu** [comment]
我们TenPayV3已经在预览了，下一代就不需要安装证书了。

**Comment by bbhxwl** [comment]
> 这个肯定是证书问题了。你可以按照我的方法排查下 首先我有另外用日志框架（我用的是NLog，这个不重要，能打到日志即可）,退款失败看到如下日志
> 
> ```
> 2020-05-27 13:55:41.5293|100|INFO|System.Net.Http.HttpClient.1xxxxxxxxx_.LogicalHandler|Start processing HTTP request POST https://api.mch.weixin.qq.com/secapi/pay/refund |url: http://weixin/customerapp/weixin/wxpayV2/refund|action: Refund
> 2020-05-27 13:55:41.5293|100|INFO|System.Net.Http.HttpClient.1xxxxxxxxx_.ClientHandler|Sending HTTP request POST https://api.mch.weixin.qq.com/secapi/pay/refund |url: http://weixin/customerapp/weixin/wxpayV2/refund|action: Refund
> 2020-05-27 13:55:41.6101|101|INFO|System.Net.Http.HttpClient.1xxxxxxxxx_.ClientHandler|Received HTTP response after 68.46170000000001ms - BadRequest |url: http://weixin/customerapp/weixin/wxpayV2/refund|action: Refund
> 2020-05-27 13:55:41.6101|101|INFO|System.Net.Http.HttpClient.1xxxxxxxxx_.LogicalHandler|End processing HTTP request after 91.99730000000001ms - BadRequest |url: http://xxx/wxpayV2/refund|action: Refund
> 2020-05-27 13:55:41.6660||ERROR|weixin_service.Controllers.WxPayControllerV2|订单号：SHOP_10000002_2020052765314发起退款失败---系统异常 System.Xml.XmlException: The 'hr' start tag on line 6 position 2 does not match the end tag of 'body'. Line 7, position 3.
>    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
>    at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
>    at System.Xml.XmlTextReaderImpl.ThrowTagMismatch(NodeData startTag)
>    at System.Xml.XmlTextReaderImpl.ParseEndElement()
>    at System.Xml.XmlTextReaderImpl.ParseElementContent()
>    at System.Xml.XmlTextReaderImpl.Read()
>    at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
>    at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
>    at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
>    at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
>    at System.Xml.Linq.XDocument.Parse(String text)
>    at Senparc.Weixin.TenPay.V3.TenPayV3Result..ctor(String resultXml)
>    at Senparc.Weixin.TenPay.V3.Result..ctor(String resultXml)
>    at Senparc.Weixin.TenPay.V3.RefundResult..ctor(String resultXml)
>    at Senparc.Weixin.TenPay.V3.TenPayV3.Refund(IServiceProvider serviceProvider, TenPayV3RefundRequestData dataInfo, Int32 timeOut)
> ```
> 
> _System.Net.Http.HttpClient.1xxxxxxxxx_.ClientHandler_，这里的1xxxxxxxxx就是商户号，看到了BadRequest应该就是证书问题了。然后我每次启动项目都加入证书
> 
> ```
> services.AddCertHttpClient(item["mch_id"] + "_", item["mch_id"] + "", item["certpath"] + "");
> ```
> 
> 这样就没有问题了，注意加下划线

怎么关闭这样的日志。Start processing HTTP request

**Comment by JeffreySu** [comment]
> > 这个肯定是证书问题了。你可以按照我的方法排查下 首先我有另外用日志框架（我用的是NLog，这个不重要，能打到日志即可）,退款失败看到如下日志
> > ```
> > 2020-05-27 13:55:41.5293|100|INFO|System.Net.Http.HttpClient.1xxxxxxxxx_.LogicalHandler|Start processing HTTP request POST https://api.mch.weixin.qq.com/secapi/pay/refund |url: http://weixin/customerapp/weixin/wxpayV2/refund|action: Refund
> > 2020-05-27 13:55:41.5293|100|INFO|System.Net.Http.HttpClient.1xxxxxxxxx_.ClientHandler|Sending HTTP request POST https://api.mch.weixin.qq.com/secapi/pay/refund |url: http://weixin/customerapp/weixin/wxpayV2/refund|action: Refund
> > 2020-05-27 13:55:41.6101|101|INFO|System.Net.Http.HttpClient.1xxxxxxxxx_.ClientHandler|Received HTTP response after 68.46170000000001ms - BadRequest |url: http://weixin/customerapp/weixin/wxpayV2/refund|action: Refund
> > 2020-05-27 13:55:41.6101|101|INFO|System.Net.Http.HttpClient.1xxxxxxxxx_.LogicalHandler|End processing HTTP request after 91.99730000000001ms - BadRequest |url: http://xxx/wxpayV2/refund|action: Refund
> > 2020-05-27 13:55:41.6660||ERROR|weixin_service.Controllers.WxPayControllerV2|订单号：SHOP_10000002_2020052765314发起退款失败---系统异常 System.Xml.XmlException: The 'hr' start tag on line 6 position 2 does not match the end tag of 'body'. Line 7, position 3.
> >    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
> >    at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
> >    at System.Xml.XmlTextReaderImpl.ThrowTagMismatch(NodeData startTag)
> >    at System.Xml.XmlTextReaderImpl.ParseEndElement()
> >    at System.Xml.XmlTextReaderImpl.ParseElementContent()
> >    at System.Xml.XmlTextReaderImpl.Read()
> >    at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
> >    at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
> >    at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
> >    at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
> >    at System.Xml.Linq.XDocument.Parse(String text)
> >    at Senparc.Weixin.TenPay.V3.TenPayV3Result..ctor(String resultXml)
> >    at Senparc.Weixin.TenPay.V3.Result..ctor(String resultXml)
> >    at Senparc.Weixin.TenPay.V3.RefundResult..ctor(String resultXml)
> >    at Senparc.Weixin.TenPay.V3.TenPayV3.Refund(IServiceProvider serviceProvider, TenPayV3RefundRequestData dataInfo, Int32 timeOut)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > _System.Net.Http.HttpClient.1xxxxxxxxx_.ClientHandler_，这里的1xxxxxxxxx就是商户号，看到了BadRequest应该就是证书问题了。然后我每次启动项目都加入证书
> > ```
> > services.AddCertHttpClient(item["mch_id"] + "_", item["mch_id"] + "", item["certpath"] + "");
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这样就没有问题了，注意加下划线
> 
> 怎么关闭这样的日志。Start processing HTTP request

请讨论主题有关的内容，您的困惑已经在相关问题中回复。
https://github.com/JeffreySu/WeiXinMPSDK/issues/2573#issuecomment-1040437314
