### ISSUE TITLE
请移除 Microsoft.AspNet.WebApi.Client 的引用，该库在 Core 3.1 下无法正常工作。

### ISSUE THREAD

**Issue by hetaoos** [JeffreySu/WeiXinMPSDK#2178]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
在 dotnet core 3 中，如果使用 [Microsoft.AspNet.WebApi.Client](https://www.nuget.org/packages/Microsoft.AspNet.WebApi.Client/) 并使用 **HttpClient** 的 **PostAsJsonAsync** 扩展方法，Post 到服务端的数据不正确。

简单示例代码：
```cs
var client = new HttpClient();
var d = new { i = 0, t = 99 };
await client.PostAsJsonAsync("http://127.0.0.1", d);
```
服务端收到的数据是这样的：
```
POST / HTTP/1.1
Host: 127.0.0.1
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8

E
{"i":0,"t":99}
0
```

类似问答
- [HttpClient PostAsJsonAsync behaving different in .NET Core and Classic .NET](https://stackoverflow.com/questions/42073484/httpclient-postasjsonasync-behaving-different-in-net-core-and-classic-net)

- [HttpClient issue when calling older ASP.Net webAPIs from net core #232](https://github.com/aspnet/AspNetWebStack/issues/232)

**该库已经很老了，已经不适用于 dotnet core 3.1，劳烦请移除。**

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 发现问题的模块

- [x] Senparc.Weixin 版本：
- [x] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [ ] .net core 2.x
- [x] .net core 3.x

##### 开发环境

- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [x] Visual Studio 2019
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [x] Windows，版本：
- [x] Linux，版本：
- [ ] Mac，版本：
- [ ] 其他：

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by hetaoos** [comment]
我自己实现了个同名的扩展方法
```cs
public static Task<HttpResponseMessage> PostAsJsonAsync<T>(this HttpClient client, string requestUri, T value, CancellationToken cancellationToken = default)
            => client.PostAsync(requestUri, new StringContent(JsonConvert.SerializeObject(value), encoding, "application/json"), cancellationToken);
```

但，引用了 **Microsoft.AspNet.WebApi.Client** 后，被覆盖了。。。

**Comment by JeffreySu** [comment]
@hetaoos 这个库目前没有实际用到，我发布了一个新版本的CO2NET，您可以先只更新这个库试一下（其他SDK等库应该都没用到）：http://nuget.org/packages/Senparc.CO2NET
