### ISSUE TITLE
必须指定待分账的接收方列表 判断有误

### ISSUE THREAD

**Issue by fanheshe** [JeffreySu/WeiXinMPSDK#2181]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
Senparc.Weixin.TenPay/V3/Universal/Entities/Request/TenpayV3ProfitShareingRequestData.cs
TenpayV3ProtfitSharingRequestData构造函数在判断最后一个参数 receivers 接收方列表时

如下：
` if (Receivers != null || Receivers.Length == 0)
            {
                throw new ArgumentNullException("必须指定待分账的接收方列表");
            }`
因此，无论Receivers传任何值都会被阻止，应该是

` if (Receivers == null || Receivers.Length == 0)
            {
                throw new ArgumentNullException("必须指定待分账的接收方列表");
            }`

服务商TenpayV3ProfitShareingAddReceiverRequestData接口也存在同样的问题

 if (Receiver != null) throw new ArgumentNullException("必须指定待添加的分账接收方");

##### 重现问题步骤（如果可以）

1. new一个TenpayV3ProtfitSharingRequestData对象，并传入构造函数值receivers总是会报错

##### 发现问题的模块

- [ ] Senparc.Weixin.Tenpay 版本：1.5.401

##### 模块对应的 .net 版本

- [x] .net core 3.x

##### 开发环境
- [ ] Visual Studio Code

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [x] Windows，版本：

##### 联系方式
Email：31978@163.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by houta-higuchi** [comment]
老哥稳，我也刚遇到了

**Comment by JeffreySu** [comment]
已发布新版本 Tenpay v1.5.502.2，感谢！
