### ISSUE TITLE
《2019-2020年度盛派开发者社区优秀贡献者获奖名单》出炉！请注意查阅并登记领奖信息（时间截止2020年6月30日10:24 ，逾期视为放弃获奖资格！）

### ISSUE THREAD

**Issue by Jessie-Space** [JeffreySu/WeiXinMPSDK#2197]
**Senparc 能有今天的成绩和发展，离不开所有开发者的持续贡献，以及社区小伙伴们的竭力支持！感谢大家一直以来为 Senparc 开发者社区做出的贡献，这也是为中国开源事业做出的贡献！**

以下我们整理出了在 2019 年2月22日 至 2020 年 3月 31日的社区贡献者名单，“盛派开发者社区贡献者”活动评选组委会从所有 GitHub/Gitee 代码贡献入围者、社区  QQ 群 / 微信群做出重要贡献的开发者中，按照贡献的质量、数量、重要性及完整程度等指标予以评分，最终评选出一系列贡献者奖项。 

本次活动共评出贡献者70名，其中最佳贡献者30个，卓越贡献者35个，社区杰出贡献者5个。为了让获奖的贡献者们能及时领到奖品，即日起，本次贡献者领奖登记信息开始收集，截止时间为2020年6月30日10:24，请各位获奖小伙伴及时登记。

*通过社区QQ群、微信群等其他途径提出重要意见或建议的贡献者，截止2020年6月30日前，仍可通过社区推荐或自荐成为贡献者（内荐请提供社区内QQ群或微信群的有效贡献截图）；如有任何问题，请及时联系盛小嗨（微信号：SenparcWechat）

![盛派社区开发者获奖名单](https://www.neuchar.com/material/images/202006241044375330..png)

**2019-2020年度盛派开发者优秀贡献者名单**

**『最佳贡献者』**

* @mc7246
* @lishewen
* @dupeng0811
* @zhao365845726
* @qideqian
* @hanabi1224
* @jianChengSun
* @LGinC
* @wtujvk
* @CdLian
* @ringls
* @crashsol
* @dong900512
* @wlclass
* @bxjg1987
* @lxings
* @slwangzi 
* @xuefuruanjian
* @janywhere 
* @cqwebwang
* @刘晓伦
* @jiehanlin
* @yueliuhun
* @jerrytang67
* @a673025
* @rongjjieaaa
* @2881099
* @oTcom
* @hesi815
* @Luoyunchong

**『卓越贡献者』**

* @CharlinQiu
* @wlsoftware
* @tiger2014
* @xclyisen
* @leeseett
* @JeffreyHangGe
* @Liu-Ryan
* @tongbenchuan
* @lisensoft
* @zhongyi112134
* @kistliu
* @Hsinky
* @lxyruanjian
* @iXinwei
* @Dysheng 
* @JianCheng
* @tangyangming
* @gendou
* @WangDrama
* @xcaptain
* @jiuzhou2019
* @xuj668
* @pengweiqhca
* @coolincy
* @tony26050369
* @fairangel
* @fengshi19888
* @luoxy123
* @TalkTruly
* @cqinwn
* @Gitoffice
* @hnsongbiao
* @archeraya
* @mpnet
* @ulyanovsk

**『社区杰出贡献者』**

* @leon
* @/kb虎@小子
* @飞机大猪
* @卖白菜的
* @上善若水

如需增补请联系我们：zsu@senparc.com/盛小嗨（微信号：SenparcWechat）

身份确认说明：由于以上名称包含了 GitHub 账户以及从 社区QQ群/微信群 等其他渠道了解的昵称、姓名，请自行核对！

**奖品内容：**

1. 最佳贡献者奖：最佳贡献者奖牌、盛派纪念盘子、盛派纪念版短袖（短袖样式随机发放）
2. 卓越贡献者奖：卓越贡献者奖牌、盛派纪念盘子、盛派纪念版短袖（短袖样式随机发放）
3. 社区杰出贡献者奖：社区杰出贡献者奖牌、盛派纪念盘子、盛派纪念版短袖（短袖样式随机发放）

**如何领取奖品？**

邮寄发放。请获选贡献者登记有效的姓名、联系电话、邮寄地址，以确保收到奖品。

**如果您是上述开发者，请使用微信扫一扫下方的二维码，登记奖励信息：**

![领奖信息登记](https://www.neuchar.com/material/images/202006241044585871..png)

**特别说明**

_由于奖品需要统一制作，领奖信息登记收集截止时间为2020年6月30日10：30！
逾期不再补签、补发，敬请悉知！_

__本次没有获奖的小伙伴也不要觉得遗憾，“盛派优秀贡献者评选活动”每年都会如期举行，机会、奖品…都留给有准备的你哟~__

参与方式）

1/通过 GitHub 官方认可的 PR 方式成功合并有意义的代码，并成为 GitHub 库认可的贡献者；（https://github.com/JeffreySu/WeiXinMPSDK/graphs/contributors）
2/通过正确提交 issue 为项目提供建设性意见和建议，并被官方最终采纳或实现（或主动实现）的贡献者；
通过社区QQ群、微信群等其他途径提出重要意见或建议的贡献者，截止2020年6月30日前，仍可通过社区推荐或内荐成为贡献者（内荐请提供社区内QQ群或微信群的有效贡献截图）；
3/在问答系统中（https://weixin.senparc.com/QA）主动帮助微信开发者解决问题的贡献者；
4/进行资金支持的突出贡献者（只随机取10%）；
5/同一条意见或建议，以第一个发布 issue 的人为准；
6/盛派员工不得参与评选。

_**未来盛派还将继续举办其他活动来为大家送福利，奖品更丰富、收获更多哦！请大家持续关注“盛派网络小助手”微信公众号，不要错过活动哦~**_

![盛派网络小助手微信公众号](https://www.neuchar.com/material/images/202006241045176763..png)

**最后再次感谢所有社区小伙伴的共同努力，感谢大家的支持与配合。**

**Comment by dupeng0811** [comment]
白嫖了这么久，因为工作需要改了几行代码，竟然还能评选优秀贡献者，受宠若惊呀。

谢谢作者的无私开源，工作中帮了很大的忙。

再次感谢。

**Comment by JeffreySu** [comment]
@xuj668
@pengweiqhca
@coolincy
@tony26050369
@fairangel
@fengshi19888
@luoxy123
@TalkTruly
@cqinwn
@Gitoffice
@hnsongbiao
@archeraya
@mpnet
@ulyanovsk

@leon
@/kb虎@小子
@飞机大猪
@卖白菜的
@上善若水

**Comment by archeraya** [comment]
啊 才看到 感谢Senparc团队，给开发带来了很大的便利

**Comment by 2881099** [comment]
感谢苏总和以上的小伙伴对开源的贡献！

**Comment by wlsoftware** [comment]
感谢Senparc团队

**Comment by JeffreySu** [comment]
非常感谢各位！2021年度优秀贡献者正在评选中，敬请期待！
