### ISSUE TITLE
2019-2020年盛派开发者社区优秀贡献者入围名单

### ISSUE THREAD

**Issue by Jessie-Space** [JeffreySu/WeiXinMPSDK#2198]
**感谢大家一直以来为 Senparc 开发者社区做出的贡献，这也是为中国开源事业做出的贡献！**

_以下我们整理出了在 2019 年2月22日 至 2020 年 3月 31日的社区优秀贡献者入围名单，“盛派开发者社区贡献者”活动评选组委会从所有GitHub/Gitee 代码贡献入围者、社区  QQ 群 / 微信群做出重要贡献的开发者中，按照贡献的质量、数量、重要性及完整程度等指标予以评分，最终评选出一系列贡献者奖项。_ 

**入围标准：**

1/通过 GitHub 官方认可的 PR 方式成功合并有意义的代码，并成为 GitHub 库认可的贡献者；（https://github.com/JeffreySu/WeiXinMPSDK/graphs/contributors）
2/通过正确提交 issue 为项目提供建设性意见和建议，并被官方最终采纳或实现（或主动实现）的贡献者；
通过社区QQ群、微信群等其他途径提出重要意见或建议的贡献者，截止2020年6月30日前，仍可通过社区推荐或内荐成为贡献者（内荐请提供社区内QQ群或微信群的有效贡献截图）；
3/在问答系统中（https://weixin.senparc.com/QA）主动帮助微信开发者解决问题的贡献者；
4/进行资金支持的突出贡献者（只随机取10%）；
5/同一条意见或建议，以第一个发布 issue 的人为准；
6/盛派员工不得参与评选。

**入围贡献者名单：**

* @mc7246
* @lishewen
* @dupeng0811
* @zhao365845726
* @qideqian
* @hanabi1224
* @jianChengSun
* @LGinC
* @wtujvk
* @CdLian
* @ringls
* @crashsol
* @dong900512
* @wlclass
* @bxjg1987
* @lxings
* @slwangzi 
* @xuefuruanjian
* @janywhere 
* @cqwebwang
* @刘晓伦
* @jiehanlin
* @yueliuhun
* @jerrytang67
* @a673025
* @rongjjieaaa
* @2881099
* @oTcom
* @hesi815
* @Luoyunchong
* @CharlinQiu
* @wlsoftware
* @tiger2014
* @xclyisen
* @leeseett
* @JeffreyHangGe
* @Liu-Ryan
* @tongbenchuan
* @lisensoft
* @zhongyi112134
* @kistliu
* @Hsinky
* @lxyruanjian
* @iXinwei
* @Dysheng 
* @JianCheng
* @tangyangming
* @gendou
* @WangDrama
* @xcaptain
* @jiuzhou2019
* @xuj668
* @pengweiqhca
* @coolincy
* @tony26050369
* @fairangel
* @fengshi19888
* @luoxy123
* @TalkTruly
* @cqinwn
* @Gitoffice
* @hnsongbiao
* @archeraya
* @mpnet
* @ulyanovsk
* @leon
* @/kb虎@小子
* @飞机大猪
* @卖白菜的
* @上善若水

*通过社区QQ群、微信群等其他途径提出重要意见或建议的贡献者，截止2020年6月30日前，仍可通过社区推荐或自荐成为贡献者（内荐请提供社区内QQ群或微信群的有效贡献截图）；如有任何问题，请及时联系盛小嗨（微信号：SenparcWechat）

_如需增补请联系我们：zsu@senparc.com/盛小嗨（微信号：SenparcWechat）_
身份确认说明：由于以上名称包含了 GitHub 账户以及从 社区QQ群/微信群 等其他渠道了解的昵称、姓名，请自行核对！

最后再次感谢所有社区小伙伴的共同努力，感谢大家的支持与配合。

**Comment by JeffreySu** [comment]
更新; https://github.com/JeffreySu/WeiXinMPSDK/issues/2197

**Comment by Dysheng** [comment]
感谢大家



发自我的小米手机
在 Jessie-Space <notifications@github.com>，2020年6月28日 上午11:22写道：

感谢大家一直以来为 Senparc 开发者社区做出的贡献，这也是为中国开源事业做出的贡献！

以下我们整理出了在 2019 年2月22日 至 2020 年 3月 31日的社区优秀贡献者入围名单，“盛派开发者社区贡献者”活动评选组委会从所有GitHub/Gitee 代码贡献入围者、社区  QQ 群 / 微信群做出重要贡献的开发者中，按照贡献的质量、数量、重要性及完整程度等指标予以评分，最终评选出一系列贡献者奖项。

入围标准：

1/通过 GitHub 官方认可的 PR 方式成功合并有意义的代码，并成为 GitHub 库认可的贡献者；（https://github.com/JeffreySu/WeiXinMPSDK/graphs/contributors）<https://github.com/JeffreySu/WeiXinMPSDK/graphs/contributors%EF%BC%89>
2/通过正确提交 issue 为项目提供建设性意见和建议，并被官方最终采纳或实现（或主动实现）的贡献者；
通过社区QQ群、微信群等其他途径提出重要意见或建议的贡献者，截止2020年6月30日前，仍可通过社区推荐或内荐成为贡献者（内荐请提供社区内QQ群或微信群的有效贡献截图）；
3/在问答系统中（https://weixin.senparc.com/QA）主动帮助微信开发者解决问题的贡献者；<https://weixin.senparc.com/QA%EF%BC%89%E4%B8%BB%E5%8A%A8%E5%B8%AE%E5%8A%A9%E5%BE%AE%E4%BF%A1%E5%BC%80%E5%8F%91%E8%80%85%E8%A7%A3%E5%86%B3%E9%97%AE%E9%A2%98%E7%9A%84%E8%B4%A1%E7%8C%AE%E8%80%85%EF%BC%9B>
4/进行资金支持的突出贡献者（只随机取10%）；
5/同一条意见或建议，以第一个发布 issue 的人为准；
6/盛派员工不得参与评选。

入围贡献者名单：

  *   @mc7246<https://github.com/mc7246>
  *   @lishewen<https://github.com/lishewen>
  *   @dupeng0811<https://github.com/dupeng0811>
  *   @zhao365845726<https://github.com/zhao365845726>
  *   @qideqian<https://github.com/qideqian>
  *   @hanabi1224<https://github.com/hanabi1224>
  *   @JianChengSun<https://github.com/JianChengSun>
  *   @LGinC<https://github.com/LGinC>
  *   @wtujvk<https://github.com/wtujvk>
  *   @CdLian<https://github.com/CdLian>
  *   @ringls<https://github.com/ringls>
  *   @crashsol<https://github.com/crashsol>
  *   @dong900512<https://github.com/dong900512>
  *   @wlclass<https://github.com/wlclass>
  *   @bxjg1987<https://github.com/bxjg1987>
  *   @lxings<https://github.com/lxings>
  *   @slwangzi<https://github.com/slwangzi>
  *   @xuefuruanjian<https://github.com/xuefuruanjian>
  *   @janywhere<https://github.com/janywhere>
  *   @cqwebwang<https://github.com/cqwebwang>
  *   @刘晓伦
  *   @jiehanlin<https://github.com/jiehanlin>
  *   @yueliuhun<https://github.com/yueliuhun>
  *   @jerrytang67<https://github.com/jerrytang67>
  *   @a673025<https://github.com/a673025>
  *   @rongjjieaaa
  *   @2881099<https://github.com/2881099>
  *   @oTcom<https://github.com/oTcom>
  *   @hesi815<https://github.com/hesi815>
  *   @luoyunchong<https://github.com/luoyunchong>
  *   @CharlinQiu<https://github.com/CharlinQiu>
  *   @wlsoftware<https://github.com/wlsoftware>
  *   @tiger2014<https://github.com/tiger2014>
  *   @xclyisen
  *   @leeseett<https://github.com/leeseett>
  *   @JeffreyHangGe<https://github.com/JeffreyHangGe>
  *   @Liu-Ryan
  *   @tongbenchuan<https://github.com/tongbenchuan>
  *   @lisensoft<https://github.com/lisensoft>
  *   @zhongyi112134<https://github.com/zhongyi112134>
  *   @kistliu<https://github.com/kistliu>
  *   @Hsinky<https://github.com/Hsinky>
  *   @lxyruanjian<https://github.com/lxyruanjian>
  *   @iXinwei
  *   @Dysheng<https://github.com/Dysheng>
  *   @JianCheng<https://github.com/JianCheng>
  *   @tangyangming<https://github.com/tangyangming>
  *   @gendou<https://github.com/gendou>
  *   @WangDrama<https://github.com/WangDrama>
  *   @xcaptain<https://github.com/xcaptain>
  *   @jiuzhou2019<https://github.com/jiuzhou2019>
  *   @xuj668
  *   @pengweiqhca
  *   @coolincy
  *   @tony26050369
  *   @fairangel
  *   @fengshi19888
  *   @luoxy123
  *   @TalkTruly
  *   @cqinwn
  *   @Gitoffice
  *   @hnsongbiao
  *   @archeraya
  *   @mpnet
  *   @ulyanovsk
  *   @leon
  *   @/kb虎@小子
  *   @飞机大猪
  *   @卖白菜的
  *   @上善若水

*通过社区QQ群、微信群等其他途径提出重要意见或建议的贡献者，截止2020年6月30日前，仍可通过社区推荐或自荐成为贡献者（内荐请提供社区内QQ群或微信群的有效贡献截图）；如有任何问题，请及时联系盛小嗨（微信号：SenparcWechat）

如需增补请联系我们：zsu@senparc.com<mailto:zsu@senparc.com>/盛小嗨（微信号：SenparcWechat）
身份确认说明：由于以上名称包含了 GitHub 账户以及从 社区QQ群/微信群 等其他渠道了解的昵称、姓名，请自行核对！

最后再次感谢所有社区小伙伴的共同努力，感谢大家的支持与配合。
