### ISSUE TITLE
是否有计划支持.net Core (netStandard) 啊？ 

### ISSUE THREAD

**Issue by John0King** [JeffreySu/WeiXinMPSDK#220]

**Comment by galendai** [comment]
+1

**Comment by John0King** [comment]
怎么都没人回复？

**Comment by JeffreySu** [comment]
文件夹已经创建了，会逐步更新上来，也欢迎大家提供代码！

**Comment by lishewen** [comment]
@JeffreySu 
我这里有一份，基于您框架的ASP.Net Core移植
<https://github.com/lishewen/LSW.Weixin>
因为您一直不愿意使用 Newtonsoft.Json 并且一直没有开Core项目，还有 区分Nuget包 的安装，所以我改了命名空间，待您的项目上架稳定后我会删除此分支
现在您建立项目了，我不懂如何推过来，所以只传了一份到自己的Github上，还请指教

**Comment by John0King** [comment]
@JeffreySu   改为NetStandard 后，好像就变成可移植类库了，如果从netStandard1.0开始 将能够在所有的.net上使用 （4.5之后）.
这里是介绍地址： [netStandards](https://docs.microsoft.com/en-us/dotnet/articles/standard/library)
感觉没必要单独建立一个文件夹，  一个单独的分支可能更合适， 等NetStandard 的库完善后，直接替换到master 分支就行了 （winform / 传统的MVC 的项目除外）

**Comment by lishewen** [comment]
同意 @John0King 的看法，Core的类库项目的确是可以编译出支持.Net Framework 4.5的DLL的。不过我觉得 @JeffreySu 还是会纠结 Newtonsoft.Json 的问题，NetStandard 是没有自带的JSON序列化的，就连微软自己的mvc6也是在用 Newtonsoft.Json 的

**Comment by John0King** [comment]
Newtonsoft.Json 也许不是性能最好的，但绝对在性能比较的好的一类中，而且 功能和易用性都这么好， 干嘛要纠结这个问题啊？

**Comment by lishewen** [comment]
@John0King #210 
我也是蛮喜欢Newtonsoft.Json的，很久以前我就建议过改用它，系统自带的序列化好多不如人意的地方，@JeffreySu 却一直坚持使用，不得已开了新的分支

**Comment by JeffreySu** [comment]
@John0King @lishewen

关于大家关心的几个问题我统一回复一下：

**Comment by JeffreySu** [comment]
@John0King 
关于 netStandards 现在你已经用到生产环境里面了吗？稳定性怎么样？
我是不是可以理解为使用  netStandards 之后我们整个库都不需要使用 System.Web 等对 .NET Framework 耦合度比较高的库了？

**Comment by John0King** [comment]
@JeffreySu   我自己的一个项目在用 netCoreApp 1.0,   未定型怎么样我不能断言，不过 newtonsoft.json 已经使用netStandard 了   稳定性应该不会差
看 @lishewen  有没有更好的看法

**Comment by lishewen** [comment]
@JeffreySu 我提供的移植代码是已经用在我的生产环境了的，并且已经上传到nuget包库，方便我自己项目的安装。稳定性感觉还行，由于 Newtonsoft.JSON 的全局设置，null值的处理比您的 jsonsetting 要好；证书处理方面还有缺失，由于我自己的项目没有使用这方面的功能，所以也没有深究
是的，netStandards 已经取消了 System.Web

**Comment by JeffreySu** [comment]
@lishewen @John0King 
OK，我来研究一下 netStandards  ，尝试试用一下。这个话题保持沟通。

**Comment by John0King** [comment]
@JeffreySu  现在nuget 包 支持 Core 么？ 还是我先用 @lishewen  的那个？

**Comment by JeffreySu** [comment]
@John0King 暂时还没发布，我们下周会有一个新版本上线，然后打算merge @lishewen 的代码，再新建分支，测试之后下下周发布到nuget，这是目前的计划。

**Comment by lishewen** [comment]
@JeffreySu 期待，目前我的代码主要还是存放在我自己的TFS里面，github上只是传了一份副本，两边双线维护麻烦，merge后我就可以不用维护此分支了。另外，对于 #230 的nuget的话题，我还有一份asp.net core 库项目 CI集成并自动发布到nuget的脚本，也是我现在TFS在用的，需要我也可以一并推过来

**Comment by JeffreySu** [comment]
已发布到分支DotNET-Core：https://github.com/JeffreySu/WeiXinMPSDK/tree/DotNET-Core

**Comment by John0King** [comment]
@lishewen  有必要使用 netStandard 1.6 级别么？   我觉得 netStandard 1.3 就差不多了

**Comment by lishewen** [comment]
@John0King 1.6是Core RTM后的模板默认的，与MVC6 RTM兼容也好，1.3的话其他有些关联库都还停留在Core RC时候的状态，会带来兼容性问题，如果需要1.3的在 project.json 中的 frameworks 配置节中修改加入即可
另外，@JeffreySu 
https://github.com/JeffreySu/WeiXinMPSDK/blob/DotNET-Core/src/Senparc.Weixin.MP/Senparc.Weixin.MP/project.json
像这个，我已经在配置节中声明了 net461，这样在build的时候同时也会生成一份基于 .net 4.6.1 的 DLL
是可以直接引用到 .net 4.6的项目中的
同理可以修改为 net45
建议你可以使用测试下，配合条件编译符号，可以在一个项目中，生成不同版本的包的，没必要再重新加入 .csproj 项目了

**Comment by John0King** [comment]
@lishewen   这我到没注意，平常都在用 .netCoreApp1.0 ,有空研究一下。
还有一个问题想请教一下：
> 我之前fork 的这个项目，并没有这个 netCore 分支， 我现在只能删掉我fork的项目，然后再 fork一遍么？ 如果有其它办法，请告诉我怎么操作

**Comment by lishewen** [comment]
我也不是很习惯Git，也是删了再重新fork的，求教 @JeffreySu

**Comment by JeffreySu** [comment]
@John0King @lishewen 如果之前的代码你们不需要保留（当然本地建议任何时候这样的操作都备份一下），那么就删了再fork。如果你们一直是频率比较高地保持同步的，甚至进场pull request过来（并得到merge），直接同步最新的分支，应该不会有太多的冲突，否则的话慢慢就等于两个完全不同的项目了。

除此以外，也可以从这里的master同步到你们的任意一个新分支，不一定要是对应你们的master的，这样就不需要删除了。然后有空的时候把新分支合并到你们自己的master就行了，当然可能会有冲突存在。

比如这次14.3.3的，我准备merge到.net core，发生了惨烈的一幕：
![image](https://cloud.githubusercontent.com/assets/2281927/17553936/02f18072-5f3b-11e6-92c3-dde28b82a32b.png)
