### ISSUE TITLE
CO2NET.Cache.Redis-V3.9.11-加锁失败

### ISSUE THREAD

**Issue by wechatdeveloper** [JeffreySu/WeiXinMPSDK#2203]
##### 问题描述
参考视频的学习项目，CO2NET.Cache.Redis-V3.4.2-LockTest-加锁正常
现在升级所有的Nuget包到最新，CO2NET.Cache.Redis-V3.9.11 重新运行测试LockTest-加锁失败

##### 重现问题步骤（如果可以）
1. 可使用项目重现问题 ：https://github.com/wechatdeveloper/WechatVideoCourse/tree/master/07-Redis%E7%BC%93%E5%AD%98
2. 运行单元测试：Home/LockTest 查看结果
3.或者在Sample项目中添加1个并发LockTest测试

##### 主要运行代码块
以下是缓存加锁代码，参考《第7课  缓存策略及并发场景下的分布式锁》最后10分钟：

` private static int _count;
        public int Count
        {
            get { return _count; }
            set
            {
                //休0.1s , 模拟并发场景，所有线程都会在这里停留0.1秒
                Thread.Sleep(100);
                _count = value;
            }
        }

        public ContentResult LockTest()
        {
            //获取当前缓存实例
            var cacheStrategy = CacheStrategyFactory.GetObjectCacheStrategyInstance();
            using (cacheStrategy.BeginCacheLock("SenparcWechatCourse", "LockTest"))
            {
                Count++;
            }
            return Content(Count.ToString());
        }`

   `private int totalThreadCount = 100;
        private int finishedThreadCount = 0;

        [TestMethod]
        public void LockTest()
        {
            //启动100个thread 
            for (int i = 0; i < totalThreadCount; i++)
            {
                var thread = new Thread(RunSingleLockTest);
                thread.Start();
            }

            //等待100次的线程执行完成，等待输出结果 
            //每次执行完毕 FinishedThreadCount + 1
            while (finishedThreadCount < totalThreadCount)
            {
                ;
            }

            Console.WriteLine("完成测试，线程总数"+finishedThreadCount);
        } 

        /// <summary>
        /// Single Function
        /// </summary>
        public void RunSingleLockTest()
        {
            // Arrange
            HomeController controller = new HomeController();
            // Act
            ContentResult result = controller.LockTest() as ContentResult;
            
            Console.WriteLine("结果：" + result.Content);

            finishedThreadCount++; //完成一次 +1 
        }`

##### 发现问题的模块
- [ ] Senparc.Weixin.Cache.Redis 版本：

##### 模块对应的 .net 版本
- [ ] .net 4.5

##### 开发环境
- [ ] Visual Studio 2017
- [x] Visual Studio 2019

- [ ] 其他：

##### 缓存环境

- [ ] Redis 版本：

##### 系统环境

- [x] Windows，版本：

##### 联系方式
Email： 772173708@qq.com

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
有没有试过 Senparc.CO2NET.Cache.CsRedis ？
