### ISSUE TITLE
The SSL connection could not be established, see inner exception

### ISSUE THREAD

**Issue by imgd** [JeffreySu/WeiXinMPSDK#2207]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
CentOS 7.5 
.Net Core 3.1
Senparc.Weixin.MP version:16.10.502.1
微信授权回调获取用户信息报错：
The SSL connection could not be established, see inner exception

定位到：
`
OAuthApi.GetAccessToken(appId, appSecret, code)
`
报错

##### 重现问题步骤（如果可以）

1. 授权方式：OAuthScope.snsapi_userinfo

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [x] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [ ] .net core 2.x
- [x] .net core 3.x

##### 开发环境

- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [x] Visual Studio 2019
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [ ] Windows，版本：
- [x] Linux，版本：
- [ ] Mac，版本：
- [ ] 其他：

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by imgd** [comment]
尝试：
`System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
                result = OAuthApi.GetAccessToken(appId, appSecret, code);`
无效

**Comment by imgd** [comment]
能不能提供下解决方案，或者采用某个版本？求指导

**Comment by imgd** [comment]
设置centos系统环境变量：
export DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0
也无效。。。

**Comment by JeffreySu** [comment]
看一下这个有没有帮助：https://github.com/JeffreySu/WeiXinMPSDK/issues/1299

**Comment by imgd** [comment]
采用这个方案 解决了http://www.yshizi.cn/178.html
不过建议还是sdk http兼容下centos
谢谢

**Comment by JeffreySu** [comment]
@imgd 我看了一下，基本上都是配置层面的问题？

**Comment by imgd** [comment]
启动配置加上DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0解决
