### ISSUE TITLE
缓存组件的选择，引起的异常；

### ISSUE THREAD

**Issue by fmpfmp** [JeffreySu/WeiXinMPSDK#2209]
当缓存组件仅选择：StackExchange.Redis时；
项目也仅引用依赖：Senparc.Weixin.Cache.Redis时；

当在Startup调用app.UseSenparcWeixin(**********)时，会报异常：
经过引用源码进行调试，发现以下代码抛出异常；（Senparc.Weixin.WeixinRegister.cs）
应该是，ReflectionHelper没有找到Senparc.Weixin.Cache.CsRedis.dll;

//CsRedis
var redisInstance = ReflectionHelper.GetStaticMember("Senparc.Weixin.Cache.CsRedis", "Senparc.Weixin.Cache.CsRedis", "RedisContainerCacheStrategy", "Instance");
if (redisInstance != null)
{
 //officialTypes.Add(redisInstance.GetType());
cacheTypes += "\r\n" + redisInstance.GetType();
}

但项目仅选择了StackExchange.Redis，并不需要引用CsRedis依赖；

这里是否应该根据配置，做一个判断？

盼回复，谢谢；

**Comment by JeffreySu** [comment]
如果引用的是Senparc.Weixin.Cache.Redis.dll，就是对应用StackExchange.Redis，如果用的是Senparc.Weixin.Cache.CsRedis.dll（推荐），那么引用的是CsRedis。

**Comment by fmpfmp** [comment]
> StackExchange

了解；

但现在的情况是，只引用Senparc.Weixin.Cache.Redis.dll ，不引用Senparc.Weixin.Cache.CsRedis.dll  的时候；
上述的代码会抛出异常；


虽然在运行时，并不影响；但在F5调试的时候，会抛出异常；

**Comment by JeffreySu** [comment]
StackExchange 问题不少，建议用CsRedis吧。

**Comment by PccCodesix** [comment]
这个问题好像还存在 。在 Senparc.CO2NET 1.3.110 中。使用csredis.后 不安装Senparc.Weixin.Cache.Redis 会报 dll 找不到错误

**Comment by JeffreySu** [comment]
@PccCodesix 有能够重现问题的代码或者最小化的项目吗？

**Comment by PccCodesix** [comment]
最小化项目没有，项目有点大。但是有报错的图片。这是报错的信息  at Senparc.CO2NET.Helpers.ReflectionHelper.GetStaticMember(String assemblyName, String nameSpace, String className, String memberName, Boolean recordLog)
![image](https://user-images.githubusercontent.com/29922883/90097469-8ff8b580-dd68-11ea-8679-b768ba2b8964.png)

**Comment by fmpfmp** [comment]
@JeffreySu 

就是我在一楼发的那段代码，有问题；

通过反射(ReflectionHelper.GetStaticMember)去取值的时候，会去找两种redis组件的dll，如果项目里只依赖了其中一种，就会报异常；

**Comment by fmpfmp** [comment]
Senparc.Weixin/Senparc.Weixin/WeixinRegister.cs
的199行和128行；

 var redisInstance = ReflectionHelper.GetStaticMember("Senparc.Weixin.Cache.Redis", "Senparc.Weixin.Cache.Redis", "RedisContainerCacheStrategy", "Instance");
var redisInstance = ReflectionHelper.GetStaticMember("Senparc.Weixin.Cache.CsRedis", "Senparc.Weixin.Cache.CsRedis", "RedisContainerCacheStrategy", "Instance");


运行时没啥影响，只是F5调试的时候，总会被异常中断；

**Comment by JeffreySu** [comment]
@fmpfmp  @thinkif  应该是119行和128行是吧？

这两个方法已经被包含在了try里面，并且我这边调试的时候没有异常，没有办法重现，还有其他的错误信息吗？另外你们.NET版本是多少？

**Comment by fmpfmp** [comment]
@JeffreySu   net core 3.1

看看你的项目，是不是两个dll都引用过，bin目录下是不是两个dll都有；

当只存在其中一个dll的时候，才会重现；

运行时没啥影响，只是F5调试的时候，会被异常中断；

**Comment by JeffreySu** [comment]
@fmpfmp  调试中断应该是在try内部，F5之后是可以继续跑的还是整个调试终止了？

**Comment by fmpfmp** [comment]
@JeffreySu   
F5之后可以继续跑，没有什么影响；
只是一方面有洁癖的人受不了，另外不清楚原理的人可能会怀疑人生；；；；；
我最开始就是，一直以为是自己哪里配置的不对，实在查不出问题；最后引用了源码单步调试，才找到原因；

**Comment by kinglionsoft** [comment]
```
 <PackageReference Include="Senparc.Weixin.Cache.CsRedis" Version="0.1.510" />
```
