### ISSUE TITLE
Found a small mistake

### ISSUE THREAD

**Issue by songyandong** [JeffreySu/WeiXinMPSDK#221]
文件:WeiXinMPSDK/Senparc.Weixin.MP/Senparc.Weixin.MP/AdvancedAPIs/Media/MediaAPI.cs
59行:var url = string.Format("http://api.weixin.qq.com/cgi-bin/media/upload?access_token={0}******
应为:var url = string.Format("https://api.weixin.qq.com/cgi-bin/media/upload?access_token={0}******
参考:http://mp.weixin.qq.com/wiki/15/2d353966323806a202cd2deaafe8e557.html

**Comment by JeffreySu** [comment]
v13.8.9 素材管理接口MediaApi修改全部http为https 感谢@songyandong
