### ISSUE TITLE
[企业微信]更新任务卡片消息状态方法异常

### ISSUE THREAD

**Issue by JiangJingxuan** [JeffreySu/WeiXinMPSDK#2222]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
企业微信`MassApi.UpdateTaskCardAsync`方法返回结果异常
官方返回结构中`invaliduser`字段为数组类型,程序中使用string类型接收,调用会产生反序列化异常

##### 重现问题步骤（如果可以）

MassApi.UpdateTaskCardAsync

##### 微信官方文档 URL
https://work.weixin.qq.com/api/doc/90000/90135/91579

##### 微信官方文档快照（直接复制关键内容到下方）
 {
   "errcode" : 0,
   "errmsg" : "ok",
   "invaliduser" : ["userid1","userid2"], // 不区分大小写，返回的列表都统一转为小写
 }

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [x] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [ ] .net core 2.x
- [x] .net core 3.x

##### 开发环境

- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [x] Visual Studio 2019
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [x] Windows，版本：
- [ ] Linux，版本：
- [ ] Mac，版本：
- [ ] 其他：

##### 联系方式
Email：331033205@qq.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
@JiangJingxuan 已更新，感谢！
