### ISSUE TITLE
新增永久素材接口缺少参数type

### ISSUE THREAD

**Issue by zgmqdl** [JeffreySu/WeiXinMPSDK#2224]
![image](https://user-images.githubusercontent.com/35328737/89730461-56c2fb80-da71-11ea-953e-e38542e5f74e.png)
![image](https://user-images.githubusercontent.com/35328737/89730465-5cb8dc80-da71-11ea-9f7e-7c32fada5e3a.png)

方法为UploadForeverMediaAsync

**Comment by JeffreySu** [comment]
https://developers.weixin.qq.com/doc/offiaccount/Asset_Management/Adding_Permanent_Assets.html

**Comment by JeffreySu** [comment]
已经发布，谢谢！

**Comment by wtujvk** [comment]
UploadForeverVideo 方法签名是新增永久视频，那么是不是只适用于上传视频呢？
 type如果只能传video 呢, 在方法内部设置type = “video” 好一些吧
