### ISSUE TITLE
企业号API被动响应消息XCData问题

### ISSUE THREAD

**Issue by BsaGyy** [JeffreySu/WeiXinMPSDK#223]
在使用Senparc.Weixin.QY.AdvancedAPIs.MassApi中的SendText方法时出现一个问题：
发回发消息中带\n换行符时XCData类处理之后Ios系统微信显示行间隔特别大，试验直接以sb拼接![CDATA]元素的xml再回传则不会出现，请问有相关的解决方案吗？

**Comment by JeffreySu** [comment]
比较稳定的一个fix bug的做法，是把最后发送给微信服务器的\r\n替换为\n，原因是windows,unix,linux之间不同的换行标记造成的。
