### ISSUE TITLE
企业支付接口缺少ssl证书参数

### ISSUE THREAD

**Issue by mfjiang** [JeffreySu/WeiXinMPSDK#2239]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
企业号支付接口缺少ssl证书参数

原接口现已经被标记为过期
```C#
Transfers(TenPayV3TransfersRequestData dataInfo, string cert, string certPassword, int timeOut = 10000);
```
请问现在要用哪个接口？

##### 发现问题的模块
- [x] Senparc.Weixin.TenPay.V3

##### 模块对应的 .net 版本
- [x] .net core 3.x

##### 开发环境
- [x] Visual Studio 2019

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
因为需要使用 DI 进行 HTTP 配置的原因，.NET Core 的证书现在是在 appsettings.json 里面配置。

参考：

https://github.com/JeffreySu/WeiXinMPSDK/blob/07836a859454c445549cdddb74f93efd78df5378/Samples/netcore3.0-mvc/Senparc.Weixin.Sample.NetCore3/appsettings.json#L69

**Comment by mfjiang** [comment]
> 因为需要使用 DI 进行 HTTP 配置的原因，.NET Core 的证书现在是在 appsettings.json 里面配置。
> 
> 参考：
> 
> https://github.com/JeffreySu/WeiXinMPSDK/blob/07836a859454c445549cdddb74f93efd78df5378/Samples/netcore3.0-mvc/Senparc.Weixin.Sample.NetCore3/appsettings.json#L69

感谢回复，我看了你们源码，该方法的签名现是：
```C#
Transfers(IServiceProvider serviceProvider, TenPayV3TransfersRequestData dataInfo, int timeOut = 10000);
```
跟踪后面的代码发现，直接从IServiceProvider取的HttpClientFactory等等……，
建议仍然提供这样的重载方法，因为某些场景需要编程式配置参数，经过条件计算后才决定使用的证书和商户号信息。
```C#
Transfers(TenPayV3TransfersRequestData dataInfo, string cert, string certPassword,int timeOut = 10000);
```

**Comment by JeffreySu** [comment]
.NET Core 的机制有变化，因为都是依赖注入的，之前的方式好像是有问题的，我们有尝试过（具体原因记不清了）。当前方法在作用于、对象释放等方面应该是官方推荐的。


BTW：除了在 Startup 里面注册，还可以在外围配置（当然可能不是您要的）：

``` C#

WebHost.CreateDefaultBuilder(args)
            .UseStartup<Startup>()
            .UseKestrel(options =>
            {
                options.Listen(IPAddress.Loopback, 5001, listenOptions =>
                {
                    listenOptions.UseHttps(AppContext.BaseDirectory+@"\my.p12", "IoM@1234");
                });
            })
```

**Comment by mfjiang** [comment]
> .NET Core 的机制有变化，因为都是依赖注入的，之前的方式好像是有问题的，我们有尝试过（具体原因记不清了）。当前方法在作用于、对象释放等方面应该是官方推荐的。
> 
> BTW：除了在 Startup 里面注册，还可以在外围配置（当然可能不是您要的）：
> 
> ```cs
> WebHost.CreateDefaultBuilder(args)
>             .UseStartup<Startup>()
>             .UseKestrel(options =>
>             {
>                 options.Listen(IPAddress.Loopback, 5001, listenOptions =>
>                 {
>                     listenOptions.UseHttps(AppContext.BaseDirectory+@"\MySsl.p12", "MyPassword");
>                 });
>             })
> ```

如果使用你们现在的DI方式，在Startup.cs中配置如下：
```C#
   services.AddSenparcWeixinServices(Configuration);
   services.AddCertHttpClient(wx_ssl_cert_mchid, wx_ssl_cert_pwd, wx_ssl_cert_path);
```
在调用入口处使用如下代码是否有效？
```C#
 IServiceProvider serviceProvider = CommonDI.CommonSP;
 if (serviceProvider == null)
 {
     throw new Exception("请在Startup.cs中添加services.AddSenparcWeixinServices,services.AddCertHttpClient");
 }
result = Senparc.Weixin.TenPay.V3.TenPayV3.Transfers(serviceProvider, data);
```

**Comment by JeffreySu** [comment]
可以的，如果是 .NET Core，建议 IServiceProvider  直接从构造函数里面注入。CommonDI.CommonSP 能不用的话最好不要用，有一些接口为了简化输入，我才缓存了一份，但和系统里面拿的可能会有差异，只能确保基础部分的注入信息是一致的（当然 SSL 证书也包含在内，所以可以用）。

**Comment by mfjiang** [comment]
十分感谢，我先用这个临时方案，本来也打算PR新的扩展上去，发现牵涉甚多，待日后找到优雅的方案再说。
