### ISSUE TITLE
为什么一个SDK写的这么庞大这么复杂

### ISSUE THREAD

**Issue by zb2947244682** [JeffreySu/WeiXinMPSDK#2241]
为什么一个SDK写的这么庞大这么复杂，新手上手各种报错。
API不就是简单的组装参数，发送参数，接受参数吗？

**Comment by JeffreySu** [comment]
您好，先要说明的是微信的 API 目前本身已经很丰富了，SDK 是根据官方 API 来进行同步的，当前 SDK 已经对不同应用场景进行了拆分，可以灵活调用。
其次，您对 SDK 的理解可能停留在一般没有生命周期管理的 API 调用上，事实上微信的验证规则、上下文处理等，官方是没有提供解决方案的，需要 SDK 来提供，本 SDK 已经提供了很好的保障机制，并且并不复杂。包括 API 的调用，您可以看一下源码，已经非常简洁（在全自动维护 AccessToken 的基础上）。
最后，我们最新更新的 Demo 都是通过测试后发布的，不知道您说的报错内容是什么？可以发一下，看可以如何帮到您。
