### ISSUE TITLE
Senparc.Weixin.MP.dll 13.8.4版本 CheckSignature.Check(signature, postModel)方法错误

### ISSUE THREAD

**Issue by tomkluas** [JeffreySu/WeiXinMPSDK#225]
版本dll：
https://github.com/JeffreySu/WeiXinMPSDK/blob/master/Senparc.Weixin.MP.BuildOutPut/.net4.5/Senparc.Weixin.MP.dll
错误点：
/// <summary>
    /// 检查签名是否正确
    /// 
    /// </summary>
    /// <param name="signature"/><param name="postModel">需要提供：Timestamp、Nonce、Token</param>
    /// <returns/>
    public static bool Check(string signature, PostModel postModel)
    {
      return **CheckSignature.Check(postModel.Timestamp, postModel.Nonce, postModel.Token, (string) null);**
    }

    /// <summary>
    /// 检查签名是否正确
    /// 
    /// </summary>
    /// <param name="signature"/><param name="timestamp"/><param name="nonce"/><param name="token"/>
    /// <returns/>
    public static bool Check(string signature, string timestamp, string nonce, string token = null)
    {
      return signature == CheckSignature.GetSignature(timestamp, nonce, token);
    }

**Comment by JeffreySu** [comment]
确实有问题，应该是：

`
        /// <summary>
        /// 检查签名是否正确
        /// </summary>
        /// <param name="signature"></param>
        /// <param name="postModel">需要提供：Timestamp、Nonce、Token</param>
        /// <returns></returns>
        public static bool Check(string signature, PostModel postModel)
        {
            return Check(signature, postModel.Timestamp, postModel.Nonce, postModel.Token);
        }
`

v13.8.7 fixbug：CheckSignature.Check方法调用错误。感谢@tomkluas 

非常感谢！
