### ISSUE TITLE
MASSSENDJOBFINISH事件增加 了ArticleUrlResult 节点

### ISSUE THREAD

**Issue by ccccccmd** [JeffreySu/WeiXinMPSDK#2250]
https://developers.weixin.qq.com/doc/offiaccount/Message_Management/Batch_Sends_and_Originality_Checks.html#7

需要等NeuChar发包
https://github.com/Senparc/NeuChar/pull/111

**Comment by JeffreySu** [comment]
@ccccccmd NeuChar 已经发布，可以继续升级。感谢！

**Comment by ccccccmd** [comment]
谢谢
