### ISSUE TITLE
想问下TemplateMessage 的发送方法在哪

### ISSUE THREAD

**Issue by Hareis** [JeffreySu/WeiXinMPSDK#2258]
![image](https://user-images.githubusercontent.com/11290701/95950281-ce712600-0e26-11eb-8525-1a72f9e12f20.png)

- 刚开始用C#写微信公众号 ，以为找到春天。这文档写的真一言难尽，感觉可以夸到明天！！！

找到``Senparc.Weixin.MP.AdvancedAPIs.TemplateMessage`` 这下面,结果定义一堆请求结果实体类型，未看到有效用的方法
全局搜索模板消息 也没有查找到

qq群申请了半天 也没人通过 所以才来。。。

**Comment by Hareis** [comment]
我找到了 在Senparc.Weixin.MP.AdvancedAPIs.TemplateApi 中

**Comment by JeffreySu** [comment]
@Hareis 建议您先看一下教程，SDK所有的接口命名都是符合官方文档的规律的。

**Comment by Hareis** [comment]
> @Hareis 建议您先看一下教程，SDK所有的接口命名都是符合官方文档的规律的。

哪里有完整且系统的文档，想找个接口 真是上天无门

**Comment by JeffreySu** [comment]
> > @Hareis 建议您先看一下教程，SDK所有的接口命名都是符合官方文档的规律的。
> 
> 哪里有完整且系统的文档，想找个接口 真是上天无门

这个项目的首页已经有足够的学习资源了：https://github.com/JeffreySu/WeiXinMPSDK#%E8%B5%84%E6%BA%90 你还需要什么？
