### ISSUE TITLE
删除分账接收方

### ISSUE THREAD

**Issue by 13433103756** [JeffreySu/WeiXinMPSDK#2277]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述

TenPayV3.ProfitSharingRemoveReceiver接口的TenpayV3ProfitShareingRemoveReceiverRequestData实体作为传入参数，构造函数赋值时多了            PackageRequestHandler.SetParameter("version", Register.TenpayV3ProtfitRequestDataVersion);，导致微信验签失败，删除就可以了.

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 微信官方文档 URL

https://pay.weixin.qq.com/wiki/doc/api/allocation_sl.php?chapter=25_4&index=5

##### 微信官方文档快照（直接复制关键内容到下方）
https://pay.weixin.qq.com/wiki/doc/api/allocation_sl.php?chapter=25_4&index=5

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

Senparc.Weixin.TenPay 版本：1.5.600

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [ ] .net core 2.x
- [x] .net core 3.x

##### 开发环境

- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [x] Visual Studio 2019
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [x] Windows，版本：
- [ ] Linux，版本：
- [ ] Mac，版本：
- [ ] 其他：

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
@13433103756 已发布新版本，非常感谢！

**Comment by 13433103756** [comment]
请问nuget的组件什么时候更新

**Comment by 13433103756** [comment]
> @ 13433103756已发布新版本，非常感谢！

请求nuget什么时候可以获取最新版本

**Comment by JeffreySu** [comment]
@13433103756 上面答复的时候就已经可用了。
