### ISSUE TITLE
[bug] InvoiceApi.InsertCardToBag出现72031异常，order_id is empty

### ISSUE THREAD

**Issue by sundayisblue** [JeffreySu/WeiXinMPSDK#2285]
提交个bug，调用方法Senparc.Weixin.MP.AdvancedAPIs.InvoiceApi.InsertCardToBag出现异常，order_id都正确，如下log：
`
微信 POST 请求发生错误！错误代码：72031，说明：invalid params, order_id is empty hint: [uedqhA00131565] ===>>   在 Senparc.Weixin.CommonAPIs.CommonJsonSend.<>c.<.cctor>b__6_1(String apiUrl, String returnText)
   在 Senparc.CO2NET.HttpUtility.Post.PostGetJson[T](IServiceProvider serviceProvider, String url, CookieContainer cookieContainer, Stream fileStream, Encoding encoding, X509Certificate2 cer, Boolean useAjax, Boolean checkValidationResult, Action`2 afterReturnText, Int32 timeOut)
   在 Senparc.Weixin.CommonAPIs.CommonJsonSend.Send[T](String accessToken, String urlFormat, Object data, CommonJsonSendType sendType, Int32 timeOut, Boolean checkValidationResult, JsonSetting jsonSetting)
   在 Senparc.Weixin.MP.AdvancedAPIs.InvoiceApi.<>c__DisplayClass24_0.<InsertCardToBag>b__0(String accessToken)
   在 Senparc.Weixin.CommonAPIs.ApiHandlerWapper.ApiHandlerWapperBase.TryCommonApiBase[T](PlatformType platformType, Func`1 accessTokenContainer_GetFirstOrDefaultAppIdFunc, Func`2 accessTokenContainer_CheckRegisteredFunc, Func`3 accessTokenContainer_GetAccessTokenResultFunc, Int32 invalidCredentialValue, Func`2 fun, String accessTokenOrAppId, Boolean retryIfFaild)
   在 Senparc.Weixin.MP.ApiHandlerWapper.TryCommonApi[T](Func`2 fun, String accessTokenOrAppId, Boolean retryIfFaild)

`
改成自己的post方法则没有问题((提交实体参数都正确且没变)。望核实解决。

**Comment by sundayisblue** [comment]
gitee 上我也冲突提交了这个bug。https://gitee.com/JeffreySu/WeiXinMPSDK/issues/I29WPD

**Comment by JeffreySu** [comment]
@sundayisblue 是否方便提供一下自己post的测试用的信息？我跑一个单元测试看看。

**Comment by JeffreySu** [comment]
@sundayisblue  是否方便提供一下自己post的测试用的信息？我跑一个单元测试看看。

**Comment by sundayisblue** [comment]
gitee上已经解决此bug。更新版本即可
