### ISSUE TITLE
[BUG] 调用分账 ProfitSharingQuery 返回签名错误

### ISSUE THREAD

**Issue by zgx840925** [JeffreySu/WeiXinMPSDK#2286]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
调用分账 ProfitSharingQuery TenpayV3ProtfitSharingQueryRequestData 返回签名错误

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [ ] .net core 2.x
- [x] .net core 3.x

##### 开发环境

- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [x] Visual Studio 2019
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [x] Windows，版本：
- [ ] Linux，版本：
- [ ] Mac，版本：
- [ ] 其他：

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
@zgx840925 请提供一下你的测试数据。zsu@senparc.com

**Comment by zgx840925** [comment]
我后来根据微信开发文档 发现不需要传 appid&nbsp; 我把appid 参数设置为null就可以了
&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; var tenpayV3ProtfitSharingQueryRequestData = new TenpayV3ProtfitSharingQueryRequestData(null, TenPayV3Info.MchId, null, null, TenPayV3Info.Key, TenPayV3Util.GetNoncestr(), model.TransactionID, model.OutOrderNo.ToString(), null);
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; var profitSharingQuery = TenPayV3.ProfitSharingQuery(tenpayV3ProtfitSharingQueryRequestData);









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JeffreySu/WeiXinMPSDK"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月20日(星期天) 下午3:27
收件人:&nbsp;"JeffreySu/WeiXinMPSDK"<WeiXinMPSDK@noreply.github.com&gt;;
抄送:&nbsp;"原点"<28972015@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [JeffreySu/WeiXinMPSDK] [BUG] 调用分账 ProfitSharingQuery 返回签名错误 (#2286)





 
@zgx840925 请提供一下你的测试数据。zsu@senparc.com

**Comment by JeffreySu** [comment]
OK
