### ISSUE TITLE
net5支持

### ISSUE THREAD

**Issue by LeiYangGH** [JeffreySu/WeiXinMPSDK#2308]
现在不管是源代码还是示例生成工具，最高都只支持到.net core 3.x，希望能增加对.net 5的直接支持！

**Comment by JeffreySu** [comment]
@LeiYangGH 当前的库最高支持是.net standard 2.1，同时是支持 .NET Core 和 .NET 5，如果要支持 .NET 5 的项目，只需要把 web 项目的 <TargetFramework> 从 netcoreapp3.1 改为 .net 5 即可。

我们后期会在 NCF 模板基础上直接发布 .NET 5的一系列 SDK 的应用示例，敬请期待 😄

**Comment by flopgiggle** [comment]
> @LeiYangGH 当前的库最高支持是.net standard 2.1，同时是支持 .NET Core 和 .NET 5，如果要支持 .NET 5 的项目，只需要把 web 项目的 TargetFramework 从 netcoreapp3.1 改为 net5.0 即可。
> 
> 我们后期会在 NCF 模板基础上直接发布 .NET 5的一系列 SDK 的应用示例，敬请期待 😄

强烈支持尽快支持.net5

**Comment by JeffreySu** [comment]
> > @LeiYangGH 当前的库最高支持是.net standard 2.1，同时是支持 .NET Core 和 .NET 5，如果要支持 .NET 5 的项目，只需要把 web 项目的 TargetFramework 从 netcoreapp3.1 改为 net5.0 即可。
> > 我们后期会在 NCF 模板基础上直接发布 .NET 5的一系列 SDK 的应用示例，敬请期待 😄
> 
> 强烈支持尽快支持.net5

@flopgiggle 目前已经是支持的，nuget 包也可以直接安装到 .NET 5 的项目中，后面只是出一个有功能性的 .NET 的 Demo。

顺便调研一下，你们需要直接出一个 .NET 5 的微信 SDK 的 Sample 吗？（其实基本上只有 .csproj 文件里面的 TargetFramework  设置不一样，其他 99.9% 的代码都是一样的）。

**Comment by LeiYangGH** [comment]
现在.net6预览版出来了，感觉跟不上节奏。。

**Comment by JeffreySu** [comment]
> 现在.net6预览版出来了，感觉跟不上节奏。。

暂时可以不用管这么多，直到 .NET6 发布 LTS 版本再考虑更新不迟，不过可以关注新特性。

**Comment by JeffreySu** [comment]
将准备发布 .NET 6 (preview) Sample。

**Comment by JeffreySu** [comment]
@LeiYangGH 已经支持 .NET 6.0，兼容 .NET 5。
