### ISSUE TITLE
微信更新了获取永久素材的接口，多了thumb_url属性，希望作者抽空更新下sdk

### ISSUE THREAD

**Issue by oppoic** [JeffreySu/WeiXinMPSDK#231]
我模拟请求获取永久素材接口（get_material）
![1](https://cloud.githubusercontent.com/assets/3375619/16793330/c5af8540-4902-11e6-819c-e417d8d3f6d9.png)

微信返回的字段：
![2](https://cloud.githubusercontent.com/assets/3375619/16793333/c9342a18-4902-11e6-9ced-bb99e93b5d4c.png)

最后一个属性thumb_url是图文消息的缩略图地址，但是封装的GetNewsResultJson对象里没有这个属性，导致获取不到：
![3](https://cloud.githubusercontent.com/assets/3375619/16793334/cc2cd95e-4902-11e6-9097-14a88d9dee67.png)

希望作者更新下sdk，谢谢！

**Comment by JeffreySu** [comment]
已经添加了，v13.9.1，谢谢！
