### ISSUE TITLE
微信消息推送不能触达

### ISSUE THREAD

**Issue by zxz524** [JeffreySu/WeiXinMPSDK#2330]
https://github.com/JeffreySu/WeiXinMPSDK/blob/ab161b8b814ba7a42a5bf6f82d18e630ef27fd75/src/Senparc.Weixin.Work/Senparc.Weixin.Work/MessageHandlers/Async/WorkMessageHandler.Async.cs#L23

第一次编译的时候可以正常触发，但是以后微信推送过来的内容不能触发。回调事件没有正常响应
public virtual IWorkResponseMessageBase OnEventRequest(IRequestMessageEventBase requestMessage)

**Comment by zxz524** [comment]
https://github.com/Senparc/NeuChar/issues/121   找到问题根源了，尽快修复一下

**Comment by JeffreySu** [comment]
@zxz524 已经发布，非常感谢！

https://github.com/Senparc/NeuChar/commit/419ac198aac75f6d28cdaf2d500ebf1ceddf5c48
