### ISSUE TITLE
小程序Senparc.Weixin.WxOpen库中解密方法重复对加密块调用两次Base64解码

### ISSUE THREAD

**Issue by JimReal** [JeffreySu/WeiXinMPSDK#2344]
##### 问题描述
小程序Senparc.Weixin.WxOpen库中解密方法DecodeEncryptedData重复对加密块调用两次Base64解码

即：
DecodeEncryptedData（）
{
var aesCipher = Convert.FromBase64String(encryptedData);//这步是多余的，AES_Decrypt方法未使用aesCipher参数
}

**Comment by JeffreySu** [comment]
@JimReal 对的，这行代码是多余的，不过不会对下面的代码有影响，所以逻辑上没有重复加密。

**Comment by JimReal** [comment]
是的 对解密结果没有影响
