### ISSUE TITLE
开发平台增加unionid后，OAuthAccessTokenResult其实也有unionid

### ISSUE THREAD

**Issue by capqueen** [JeffreySu/WeiXinMPSDK#235]
如题，
根据接口文档，OAuthAccessTokenResult 也应该加上unionid,不然总是要再去取一次unserinfo的接口，觉得麻烦了。

另外是不是可以考虑把整个returnText放到OAuthAccessTokenResult ，或者是序列化到dictionary，这样微信接口参数变更了的话，SDK用户可以不用等待更新。

**Comment by capqueen** [comment]
http://mp.weixin.qq.com/wiki/17/c0f37d5704f0b64713d5d2c37b468d75.html

**Comment by JeffreySu** [comment]
感谢您的建议，我们看一下。 @AnnXu

**Comment by JeffreySu** [comment]
已经添加，谢谢！ v13.9.1
