### ISSUE TITLE
看了你们的Redis Cache实现，感觉太麻烦了

### ISSUE THREAD

**Issue by capqueen** [JeffreySu/WeiXinMPSDK#236]
我觉得TryGetTicket/TryGetToken里的Cache可以不用自己实现，直接接口注入
然后默认实现MemoryCache，自动过期可以依赖Cache的Expried(.NET自带的MemroryCache和Redis这类都有支持)属性就好了，伪代码：
var token = GetFromCahe()
if(token == null)
{
      token = GetTiket();
      ICache.SetToCache(token, token.expires_in);
}

这样切换Redis就分分钟了。

另外还需要一个锁，本地的时候lock，Redis的时候得有一个分布式锁，Redis也可以实现分布式锁。
我觉得这里可以也实现的类似的
ICache.Lock(Action action)
这样的方法，把Lock的实现放在具体的ICache实现类上去。

我感觉这样的话，比你们现在要我自己实现一个BaseContainer 简单点。并且我看了下你们提供的Redis Cache，并没有考虑到分布式锁？求指教

**Comment by JeffreySu** [comment]
缓存过期的机制这么做主要有两个原因：
1、因为本地缓存我们使用的是Dictionary，所以过期的时间还是需要使用程序来维护。不使用.NET自带的缓存有很多的考虑。
2、因为Container缓存的结构比较深，可能（或者比较肯定地说）在一些缓存模块里面，你缓存的是一整个容器对象，这个expire参数做不到针对某个Item的过期时间设置。

所以目前总体来说还是用程序来维护过期时间更加可靠，当然我们也会不断优化这个结构，效率上面始终是会有保障的。

分布式锁的做法比较多，我们正在找一个更加通用一点的方法，尤其是针对每个缓存都可以有效的，预计下一次Redis模块升级我们会加上去。因为是开源项目，最好还需要做成接口和一个默认实现，所以需要一些时间来验证。如果您有很好的通用方案，也欢迎交流。

非常感谢！

**Comment by capqueen** [comment]
针对第二点，有点疑问。

> 在一些缓存模块里面，你缓存的是一整个容器对象。  

这个我感觉按照目前我对缓存的使用，没有是存放整个容器的吧？如果缓存数据不是以Item为单独key缓存的话，一定是有问题的吧？
在程序层面可以以一个key来做一个大集合： urn:weixin:*(urn:weixin:jstoken/urn:weixin:token...)，这样不是每个key都是单独维护的嘛。我觉得想到存整个container，一定是个不合理的设计，而且不够通用。
Redis虽然有众多数据结构支持，但是作为通用缓存无论是redis/memcached都还是以Key:Value来做的。

当然我还是理解作为开源产品，还是以可扩展性为主比较好。我觉得如果Token缓存模块有更好的接口可以扩展的话，还是会比较方便的，毕竟大部分公司（比如我们这）都有稳定的cache框架了，直接扩展一个接口会更加的方便些。

**Comment by JeffreySu** [comment]
目前我们库里面提供的是一个默认的实现，如果您有自己的实现方式，是可以做另外的实现的。

关于缓存IContainerItemCollection的问题，是历史遗留问题，因为之前的方案是做一个CacheServer代理服务（开源项目里面有这个项目，只是我们现在还没有正式发布），然后所有的缓存都集中在这一台上面，并且直接用C#存对象，而不是字符串，这样的话整个对象引用效率会比序列化高，并且部分的Container逻辑处理都集中在这一台上面，Web服务器只需要关注业务逻辑，当然里面还有很多的问题需要解决。这只是一个扩展方案，即使发布了也不会影响当前的方案。后来扩展到Redis等其他的缓存框架之后，面临序列化的问题确实有独立的需要，这个后期是会处理的，目前来说对大部分维护已知的微信公众号的项目不会有效率上太大的差别。

**Comment by JeffreySu** [comment]
@capqueen 已经重构了Container和Redis的代码。此版本开始稳定支持：https://github.com/JeffreySu/WeiXinMPSDK/releases/tag/v14.3.4

感谢您的建议！
