### ISSUE TITLE
RequestMessageEvent_Change_External_Chat 类找不到？

### ISSUE THREAD

**Issue by EasonXm** [JeffreySu/WeiXinMPSDK#2362]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
.net 4.5 项目编译失败,客户群变更事件推送RequestMessageEvent_Change_External_Chat类找不到？

##### 重现问题步骤（如果可以）

![image](https://user-images.githubusercontent.com/24467790/117943829-1f0a1c80-b33f-11eb-9757-ac00e2a43c4d.png)

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [x] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [ ] .net core 2.x
- [x] .net core 3.x

##### 开发环境

- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [x] Visual Studio 2019
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [x] Windows，版本：
- [ ] Linux，版本：
- [ ] Mac，版本：
- [ ] 其他：

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by EasonXm** [comment]
下载的源码是主干

**Comment by JeffreySu** [comment]
源码位置：

https://github.com/JeffreySu/WeiXinMPSDK/blob/6563197341e1afd0882decff710e27c2d8c7c291/src/Senparc.Weixin.Work/Senparc.Weixin.Work/Entities/Request/Event/RequestMessageEvent_External_Chat.cs#L19

如果使用源码，建议用 .NET Core 的 Sample 版本编译（哪怕你用的是.NET 4.5）,4.5的Sample已经不再更新。
