### ISSUE TITLE
TenPayV3.Transfers CA_ERROR证书出错！！

### ISSUE THREAD

**Issue by imgd** [JeffreySu/WeiXinMPSDK#2376]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
企业付款到零钱：CA_ERROR证书出错，请登录微信支付商户平台下载证书。
我知道是证书相关的问题，但是发送现金红包正常，我就无法理解了。
配置：
![image](https://user-images.githubusercontent.com/5319255/120954076-f714aa00-c780-11eb-9b2f-96c8371e1b00.png)
现金红包使用的默认配置证书路径：
![image](https://user-images.githubusercontent.com/5319255/120954136-101d5b00-c781-11eb-976e-5de12a154e24.png)
付款到零钱：
![image](https://user-images.githubusercontent.com/5319255/120954174-262b1b80-c781-11eb-9145-6687ad15b801.png)
IServiceProvider难道不应该拿的也是默认配置的证书吗？ConfigureServices无其他证书配置

也尝试services.AddCertHttpClient添加证书，一样的错误。
可以肯定的是证书路径正确且是微信下发的。

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [x ] Senparc.Weixin.Tenpay 版本：         Senparc.Weixin.TenPay, Version=1.5.510.0
- [ ] Senparc.WebSocket 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [ ] .net core 2.x
- [x] .net core 3.x
- [ ] .net 5.x / 6.x

##### 开发环境

- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [x] Visual Studio 2019
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [ ] Windows，版本：
- [x ] Linux，版本：
- [ ] Mac，版本：
- [ ] 其他：

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by imgd** [comment]
TenPayV3.Transfers 此方法不能指定证书路径，怎么解决？

**Comment by JeffreySu** [comment]
.NET Core 是需要在启动的时候就注册证书的，参考 Startup.cs 的注释：

https://github.com/JeffreySu/WeiXinMPSDK/blob/1bcdabdb227fd8b3c6d49053cbafa0c971499eed/Samples/net6-mvc/Senparc.Weixin.Sample.Net6/Startup.cs#L81

**Comment by imgd** [comment]
奇了怪了
![image](https://user-images.githubusercontent.com/5319255/121311368-ec9c1100-c936-11eb-8b7c-979c7eccfb1a.png)
我之前也注册了的，只不过证书名字不一样随便弄得，现在改成了 "商户号_" 就可以了。

我也看Startup.cs注释其中一段
![image](https://user-images.githubusercontent.com/5319255/121311549-1c4b1900-c937-11eb-9f5f-c836e14db256.png)
配置参数里面我是加了的，我认为他是注册了的

**Comment by imgd** [comment]
证书名是有啥玄学吗？
