### ISSUE TITLE
小程序推送客服消息问题

### ISSUE THREAD

**Issue by xxvolvo** [JeffreySu/WeiXinMPSDK#2388]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
这个问题之前就发现了 微信小程序的客服消息走的是公众号的逻辑，token维护也走的公众号那一套，
所以想成功推送的话只能将小程序注册为公众号，或者调用公众号的AccessTokenContainer.RegisterAsync，否则将无法通过传递appid来调用方法。
最近开发新项目，又回顾到了这个问题，请问一下这块是设计如此？还是有计划剥离公众号和小程序的底层调用。

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] Senparc.Weixin.Tenpay 版本：
- [ ] Senparc.WebSocket 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [ ] .net core 2.x
- [x] .net core 3.x
- [ ] .net 5.x / 6.x

##### 开发环境

- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [x] Visual Studio 2019
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [x] Windows，版本：
- [ ] Linux，版本：
- [ ] Mac，版本：
- [ ] 其他：

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
您说的问题不存在，小程序我们专门提供了独立的 MessageHandler，可以参考示例：

https://github.com/JeffreySu/WeiXinMPSDK/blob/fa4b15d52af652196d5c988c9990f6bedd78e4c5/Samples/net45-mvc/Senparc.Weixin.MP.Sample.CommonService/MessageHandlers/WxOpenMessageHandler/CustomWxOpenMessageHandler.cs

**Comment by xxvolvo** [comment]
> 您说的问题不存在，小程序我们专门提供了独立的 MessageHandler，可以参考示例：
> 
> https://github.com/JeffreySu/WeiXinMPSDK/blob/fa4b15d52af652196d5c988c9990f6bedd78e4c5/Samples/net45-mvc/Senparc.Weixin.MP.Sample.CommonService/MessageHandlers/WxOpenMessageHandler/CustomWxOpenMessageHandler.cs

我使用的就是WxOpenMessageHandler 您可以验证一下 
而且这个问题和WxOpenMessageHandler无关，经过看源码发现是Senparc.Weixin.WxOpen.AdvancedAPIs.CustomApi.SendTextAsync调用了Senparc.Weixin.MP.AdvancedAPIs.CustomApi.SendTextAsync 当把Appid当第一次参数传入后，token管理走的是MP的AccessTokenContainer而不是WxOpen的AccessTokenContainer

**Comment by JeffreySu** [comment]
> > 您说的问题不存在，小程序我们专门提供了独立的 MessageHandler，可以参考示例：
> > https://github.com/JeffreySu/WeiXinMPSDK/blob/fa4b15d52af652196d5c988c9990f6bedd78e4c5/Samples/net45-mvc/Senparc.Weixin.MP.Sample.CommonService/MessageHandlers/WxOpenMessageHandler/CustomWxOpenMessageHandler.cs
> 
> 我使用的就是WxOpenMessageHandler 您可以验证一下
> 而且这个问题和WxOpenMessageHandler无关，经过看源码发现是Senparc.Weixin.WxOpen.AdvancedAPIs.CustomApi.SendTextAsync调用了Senparc.Weixin.MP.AdvancedAPIs.CustomApi.SendTextAsync 当把Appid当第一次参数传入后，token管理走的是MP的AccessTokenContainer而不是WxOpen的AccessTokenContainer
> 问题发生在CustomApi类中

对的，您说的这个问题是存在的，我们会尽快处理，谢谢！

**Comment by JeffreySu** [comment]
@xxvolvo 已经发布新版本：https://www.nuget.org/packages/Senparc.Weixin.WxOpen/3.12.2-preview1
非常感谢！
