### ISSUE TITLE
work模块gettoken 也没有使用分布式锁

### ISSUE THREAD

**Issue by WangDrama** [JeffreySu/WeiXinMPSDK#2399]
work模块gettoken 也没有使用分布式锁，应该也是有问题的吧
![image](https://user-images.githubusercontent.com/33739071/126142453-52d46d12-7d1b-48d6-8c0d-410d02a2d13b.png)
![image](https://user-images.githubusercontent.com/33739071/126142478-c014cdb7-cbec-4723-9fd1-9edca6186170.png)

**Comment by JeffreySu** [comment]
对，这里应该是没有同步升级，下个版本会处理。
