### ISSUE TITLE
最新版Senparc.Weixin.MP中AdvancedAPIs.CustomApi.SendText无限递归

### ISSUE THREAD

**Issue by zhaoyu1999** [JeffreySu/WeiXinMPSDK#240]
最新版的CustomApi.SendText会无限递归。 测试代码：
   AccessTokenContainer.Register("", "");
   var result = CustomApi.SendText("", "", "test");
   Console.WriteLine(result .errmsg);
   Console.ReadLine();

**Comment by andysjt** [comment]
我也遇到了，搞死我了，第一次碰到这种问题，感觉换人了就不行了啊

**Comment by andysjt** [comment]
被坑了

**Comment by AnnXu** [comment]
真是抱歉给你造成那么大的问题，这次贡献者提供的代码没有做单元测试，以后我们会加强审核，已经在处理中，给您带来麻烦非常抱歉。

**Comment by AnnXu** [comment]
修改的代码已上传，感谢你们的及时提出！ @zhaoyu1999 @andysjt

**Comment by AnnXu** [comment]
@andysjt 对了，这个代码就是您提供的哇。。https://github.com/JeffreySu/WeiXinMPSDK/issues/215

**Comment by andysjt** [comment]
我传的只是参考啊，而且我的代码也没有死循环啊

**Comment by andysjt** [comment]
我新建的类，然后调的CustomApi.SendText， 看你的代码是在 CustomApi.SendText 里调CustomApi.SendText
