### ISSUE TITLE
TemplateApi.SendTemplateMessageAsync()方法里的topcolor参数是干嘛的？

### ISSUE THREAD

**Issue by fengrui358** [JeffreySu/WeiXinMPSDK#241]
TemplateApi.SendTemplateMessageAsync()方法里的topcolor参数是干嘛的？貌似官方接口没发现要这个参数呢？

**Comment by AnnXu** [comment]
@fengrui358 感谢你的疑问。已查看，官方接口没有这个参数，已修改，修改的代码已上传。再次感谢！
