### ISSUE TITLE
采用Senparc.Weixin.Cache.Redis缓存策略时，OAuthAccessTokenResult序列化反序列化报错

### ISSUE THREAD

**Issue by jefth** [JeffreySu/WeiXinMPSDK#242]
采用Senparc.Weixin.Cache.Redis缓存策略时，OAuthAccessTokenResult序列化反序列化报错

程序集“Senparc.Weixin.MP, Version=14.2.3.32547, Culture=neutral, PublicKeyToken=null”中的类型“Senparc.Weixin.MP.AdvancedAPIs.OAuth.OAuthAccessTokenResult”未标记为可序列化.

+    [Serializable]
     public class OAuthAccessTokenResult : WxJsonResult

**Comment by jefth** [comment]
Senparc.Weixin.MP.AdvancedAPIs.OAuth.OAuthAccessTokenResult

**Comment by JeffreySu** [comment]
谢谢！已经上传，除此以外还有其他几个类也加了，目前正在优化Container和缓存的衔接部分，测试结果已经越来越稳定。

**Comment by JeffreySu** [comment]
如果有最新的测试结果欢迎随时沟通！
