### ISSUE TITLE
发消息提示未注册

### ISSUE THREAD

**Issue by andysjt** [JeffreySu/WeiXinMPSDK#243]
我在global里已经注册了
AccessTokenContainer.Register(ConfigHelper.WeixinAppId, ConfigHelper.WeixinAppSecret);

sendtext的时候还提示我要注册，什么情况？？

**Comment by carlchou** [comment]
一样问题，上一个版本无限循环，更新了最新版本后就变这样了，以前几个版本还好的

**Comment by andysjt** [comment]
@carlchou 我跟你的感觉是一样的，我已经两次恢复到以前的版本了。 而且看demo要注册一堆东西，感觉越搞越复杂

**Comment by JeffreySu** [comment]
昨天发布的Senparc.Weixin.dll v4.7.3收到部分开发者的反馈，存在无法注册Container的问题，现已修复，新版本v4.7.4。
除了解决上述问题，新版本同时优化了部分缓存接口。

本次涉及到的更新包括：
Senparc.Weixin.dll
v4.7.3 => v4.7.4

Senparc.Weixin.Cache.Redis.dll
v0.2.0 => v0.2.1

Senparc.Weixin.Cache.Memcached.dll
v0.0.2 => v0.0.3

其他版本均无影响。
Nuget库也已更新，只需根据项目需要更新以上类库即可（Senparc.Weixin.dll必须更新）。

以上版本均可以在github下载源代码：
https://github.com/JeffreySu/WeiXinMPSDK
或Release版本：
https://github.com/JeffreySu/WeiXinMPSDK/releases

类库帮助文档下载：
http://sdk.weixin.senparc.com/Document

感谢您的支持，同时非常感谢反馈问题的朋友们！

**Comment by JeffreySu** [comment]
@andysjt @carlchou 正式发布的版本请看 https://github.com/JeffreySu/WeiXinMPSDK/releases 以及Nuget 上面的正式版，github的实时的代码很可能是我们一个Milestone过程中的代码。

昨天不能注册的问题是我这边测试的时候没有清空Redis缓存导致问题没有被及时发现，抱歉！

另外有关注册的问题，是为了使用过程中更加方便，至于具体要注册多少东西，是腾讯微信的体量和设计的。实在不想注册的话，可以在程序里面用TryGetXX方法，每次提供AppId和Secret即可。
