### ISSUE TITLE
微信公众平台用户信息相关接口调整公告

### ISSUE THREAD

**Issue by Varorbc** [JeffreySu/WeiXinMPSDK#2478]
[微信公众平台用户信息相关接口调整公告](https://mp.weixin.qq.com/cgi-bin/announce?action=getannouncement&announce_id=11632637451RQs8y&version=&lang=zh_CN&token=)

**Comment by JeffreySu** [comment]
@Varorbc 之前已经获取过的用户还是会有这个信息，是否暂时标记为[Obsolete]更合适？

**Comment by JeffreySu** [comment]
已经发布，非常感谢！
