### ISSUE TITLE
是否支持 ASP.NET CORE

### ISSUE THREAD

**Issue by gaoxuesong** [JeffreySu/WeiXinMPSDK#248]
请问是否支持 asp.net core，以及是否有开发文档和sample？

**Comment by JeffreySu** [comment]
请看.NET Core的分支：https://github.com/JeffreySu/WeiXinMPSDK/tree/DotNET-Core

已经可以用了，有部分功能正在完善。包括序列化（分布式缓存需要用到）之类的问题，也正在等下一个版本官方来提供。
