### ISSUE TITLE
v3版本创建签名docker内异常

### ISSUE THREAD

**Issue by XiaoJia12138** [JeffreySu/WeiXinMPSDK#2485]
途中的三个方法，vs中执行是正常的。
但是在docker下，TenPaySignHelper.CreateSign  方法异常。
![微信截图_20211002003320](https://user-images.githubusercontent.com/52380888/135656453-dca8d94a-959d-4f6b-8b9b-5c4deccf9318.png)
下面是异常截图
![微信截图_20211002003704](https://user-images.githubusercontent.com/52380888/135656621-d46096f9-4225-4b9e-af60-7c507a01004e.png)

**Comment by XiaoJia12138** [comment]
![微信截图_20211002005833](https://user-images.githubusercontent.com/52380888/135659058-9b27b218-fe63-4ba3-95b1-03908ff3ac26.png)
应该是这个原因导致的。

**Comment by JeffreySu** [comment]
上述方法是腾讯默认的示例里面提供的，后来已经提供新的兼容方法了，您再看一下。
