### ISSUE TITLE
怎么得到公众号的年审通知

### ISSUE THREAD

**Issue by zhujinhu21** [JeffreySu/WeiXinMPSDK#250]
在那个事件中可以得到年审通知。 OnEvent_Poi_Check_NotifyRequest 这个吗？
http://mp.weixin.qq.com/wiki/10/2adfb2f10828e87aa1e5c3ef83b17906.html  微信认证事件推送 在哪个事件接收？

**Comment by zhujinhu21** [comment]
@JeffreySu  我增加了一个通知类型 可以吗 case Event.annual_renew://年审通知
                    responseMessage = OnEvent_annual_renew(RequestMessage as RequestMessageEvent_annual_renew);
                    break;

**Comment by JeffreySu** [comment]
@zhujinhu21 这个好像最早是没有的，可能是没有加，如果你有修改过的代码，欢迎PullRequest过来。
另外可以看一下我们之前的一些命名规则，希望可以尽量保持一致（如大小写）。

感谢！

**Comment by zhujinhu21** [comment]
@JeffreySu  我提交了代码，你看下有什么问题，谢谢

**Comment by JeffreySu** [comment]
@zhujinhu21 PR里面只有你同步的几个记录，没有收到代码，是不是你本地修改之后没有提交？

**Comment by JeffreySu** [comment]
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1455785130

**Comment by JeffreySu** [comment]
单元测试：https://github.com/JeffreySu/WeiXinMPSDK/blob/a2c7bdb196b518461a80b5e70fe6f8c84c46933b/src/Senparc.Weixin.MP/Senparc.Weixin.MP.Test/MessageHandlers/MessageHandlersTest.Event.cs#L38
