### ISSUE TITLE
企微客户联系变更回调事件丢失

### ISSUE THREAD

**Issue by 656739286** [JeffreySu/WeiXinMPSDK#2508]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
接入了盛派SDK企微事件回调，会出现回调的数据没有接收到的情况

##### 重现问题步骤（如果可以）

1.OnEvent_ChangeExternalContactAddRequest   OnEvent_ChangeExternalContactDelRequest   OnEvent_ChangeExternalContactAddHalfRequest   OnEvent_ChangeExternalContactDelFollowUserRequest  这四个事件会存在部分回调丢失的情况，咨询过企微的客服，确认企微有发出回调事件，但是我的站点在接收事件并保存入库的时候，找不到对应的数据，怀疑是接收企微回调时事件类型判断处理失败，导致没有进入对应的事件处理中

##### 微信官方文档 URL
https://open.work.weixin.qq.com/api/doc/90000/90135/92130

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [x] Senparc.Weixin.Work 版本：3.9.600
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] Senparc.Weixin.Tenpay 版本：
- [ ] Senparc.WebSocket 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5
- [ ] .net standard 2.0
- [ ] .net core 1.x
- [ ] .net core 2.x
- [] .net core 3.x
- [x ] .net 5.x / 6.x

##### 开发环境

- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [x] Visual Studio 2019
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [x] Windows，版本：
- [ ] Linux，版本：
- [ ] Mac，版本：
- [ ] 其他：

##### 联系方式
Email：656739286@qq.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
升级到最新的版本试一下，太老的版本可能有去重不准确的问题。
