### ISSUE TITLE
CardDetailGetResultJson 需要修改

### ISSUE THREAD

**Issue by gwhzh21** [JeffreySu/WeiXinMPSDK#251]
Card_BaseInfoBase.get_limit 类型需要修改为 unsigned int,
因为不填此值,默认是4294967295.

**Comment by JeffreySu** [comment]
C#貌似是没有unsigned int这种定义方式的，你说的是不是unit类型？
另外你说的默认值的问题，应该是在构造函数里面处理，unit默认也是0吧？

**Comment by gwhzh21** [comment]
我是说的微信那边返回的结果,现在都不对了.https://api.weixin.qq.com/card/get来获取卡券基本信息的时候,会出现"值对于 Int32 太大或太小",打开日志看了下,"get_limit":4294967295,返回的是这个值,而微信文档里面的定义是int,而且接口里面也是int,但是现在出错了.

**Comment by JeffreySu** [comment]
那其实应该是使用Int64（long）类型，是吧？

**Comment by JeffreySu** [comment]
已经按照long类型修改：https://github.com/JeffreySu/WeiXinMPSDK/commit/25108fccd8c9152f6427dc9196acc971ffecb34c

谢谢！
