### ISSUE TITLE
net6可以取消startup类，怎么进行微信全局配置

### ISSUE THREAD

**Issue by bocblca** [JeffreySu/WeiXinMPSDK#2518]
net6可以取消startup启动类，那么如何在program类里面配置微信的全局设置？
// 启动 CO2NET 全局注册，必须！
            // 关于 UseSenparcGlobal() 的更多用法见 CO2NET Demo：https://github.com/Senparc/Senparc.CO2NET/blob/master/Sample/Senparc.CO2NET.Sample.netcore3/Startup.cs
            var registerService = app.UseSenparcGlobal(env, senparcSetting.Value, ...
          
这里usesenparcglobal
参数怎么写？

weixinRegister
                            //注册公众号（可注册多个）                                                    -- DPBMARK MP

                            .RegisterMpAccount(senparcWeixinSetting.Value, "【盛派网络小助手】公众号")     // DPBMARK_END

我想知道senparcWeixinSetting.Value这个参数用什么代替，感谢！！！

**Comment by bocblca** [comment]
weixinRegister
                            //注册公众号（可注册多个）                                                    -- DPBMARK MP

                            .RegisterMpAccount(senparcWeixinSetting.Value, "【盛派网络小助手】公众号")     // DPBMARK_END

**Comment by bocblca** [comment]
好像这样就可以了，请大佬指正
app.UseSenparcGlobal(app.Environment, Senparc.CO2NET.Config.SenparcSetting, reg =>
{
})
              .UseSenparcWeixin(Senparc.Weixin.Config.SenparcWeixinSetting, reg =>
              {
                  reg.RegisterMpAccount(Senparc.Weixin.Config.SenparcWeixinSetting, "xxxx公众号");

              });

**Comment by bocblca** [comment]
我把我的NET6 program.cs代码贴到这里，有兴趣的可以参考一下：
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Senparc.CO2NET;
using Senparc.CO2NET.AspNet;
using Senparc.Weixin.RegisterServices;
using weixin.Models;
using Microsoft.AspNetCore.Hosting;

using Senparc.CO2NET.RegisterServices;
using Senparc.Weixin;
using Senparc.Weixin.MP;
using Senparc.Weixin.MP.MessageHandlers.Middleware;
using weixin;

var builder = WebApplication.CreateBuilder(args);
builder.Host.UseServiceProviderFactory(new SenparcServiceProviderFactory());


builder.Services.AddDbContext<Wxusers>(options => options.UseSqlServer(builder.Configuration.GetConnectionString("sqlconn")));
builder.Services.AddSingleton<ITempDataProvider,CookieTempDataProvider> ();
builder.Services.Configure<IISServerOptions>(options => options.AllowSynchronousIO = true);
builder.Services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
builder.Services.AddMemoryCache();
builder.Services.AddSenparcWeixinServices(builder.Configuration);
IRegisterService register = RegisterService.Start(Senparc.CO2NET.Config.SenparcSetting).UseSenparcGlobal();// 启动 CO2NET 全局注册，必须！
register.UseSenparcWeixin(Senparc.Weixin.Config.SenparcWeixinSetting, Senparc.CO2NET.Config.SenparcSetting);//微信全局注册，必须！

var app=builder.Build();


app.UseSession();
app.UseEnableRequestRewind();
if (app.Environment.IsDevelopment())
{
    app.UseDeveloperExceptionPage();
}
else
{
    app.UseExceptionHandler("/Home/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

app.UseHttpsRedirection();


app.UseStaticFiles();

app.UseRouting();

app.UseAuthorization();


app.UseEndpoints(endpoints =>
{
    endpoints.MapControllerRoute(
        name: "default",
        pattern: "{controller}/{action=Index}/{id?}");
});

app.UseSenparcGlobal(app.Environment, Senparc.CO2NET.Config.SenparcSetting, reg =>
{
})
              .UseSenparcWeixin(Senparc.Weixin.Config.SenparcWeixinSetting, reg =>
              {
                  reg.RegisterMpAccount(Senparc.Weixin.Config.SenparcWeixinSetting, "xx (微信公众号)");

              });

app.UseMessageHandlerForMp("/Weixin", (stream, postModel, maxRecordCount, serviceProvider) => new CustomMessageHandler(stream, postModel, maxRecordCount, false), Options =>
{
    Options.AccountSettingFunc = Context => Senparc.Weixin.Config.SenparcWeixinSetting;
    Options.DefaultMessageHandlerAsyncEvent = Senparc.NeuChar.MessageHandlers.DefaultMessageHandlerAsyncEvent.SelfSynicMethod;


});



app.Run("https://localhost:7009");

**Comment by JeffreySu** [comment]
@bocblca 抱歉，在 .NET 6 简洁的写法可以参考这个项目：https://github.com/JeffreySu/MsBuildSample2021

对应的完整视频见：https://live.csdn.net/room/microsoftreactor/M36pgJSo（播放后需要往后拉一下，前面有一段时间没有内容）

其中WorkShop部分单独的见：https://www.bilibili.com/video/BV1Gq4y197mw
