### ISSUE TITLE
40029-invalid code

### ISSUE THREAD

**Issue by andysjt** [JeffreySu/WeiXinMPSDK#252]
OAuthApi.GetAuthorizeUrl  ,加上addConnectRedirect还是会有40029-invalid code的问题，不知道怎么解决

**Comment by JeffreySu** [comment]
你跟踪一下，是不是客户端收到了2次请求（第一次被腾讯服务器终止）

**Comment by JeffreySu** [comment]
刚更新了一篇文章，可以参考一下：《解决OAuth出现40029(invalid code)错误》
https://github.com/JeffreySu/WeixinResource/blob/master/%E9%82%A3%E4%BA%9B%E5%B9%B4%E6%88%91%E4%BB%AC%E8%B8%A9%E8%BF%87%E7%9A%84%E5%9D%91/20160913-OAuth%E5%87%BA%E7%8E%B040029(invalid%20code)%E9%94%99%E8%AF%AF.md

你看看是不是这个问题。

**Comment by andysjt** [comment]
看到了，非常感谢，我试试
