### ISSUE TITLE
sha1签名算法中编码不对，导致算出的签名与微信官网不一致

### ISSUE THREAD

**Issue by zheast** [JeffreySu/WeiXinMPSDK#253]
经验证：
原代码Senparc.Weixin.MP.Helpers.SHA1UtilHelper中采用ASCII编码进行加密，的到签名串与官网
http://mp.weixin.qq.com/debug/cgi-bin/sandbox?t=jsapisign 中结果不一致，修改为UTF8编码后结果一致，请验证！

**Comment by JeffreySu** [comment]
我测试的结果是一样的，你可以再看一下，官方要求的就是ASCII编码。
下面是官网debug截图：
![image](https://cloud.githubusercontent.com/assets/2281927/18657573/26f30960-7f2e-11e6-9777-96f0c888dd06.png)

下面是SDK的单元测试：
![image](https://cloud.githubusercontent.com/assets/2281927/18657594/3d53f4da-7f2e-11e6-89c7-44db46832cdd.png)

**Comment by zheast** [comment]
需填入正确的参数后测试！
根据官网说法“字段名和字段值都采用原始值”，用ASCII编码应该没问题才对，但结果确实不一致。
实际验证用UTF8计算出来的与官网完全一致
参数样例：
 ticket：kgt8ON7yVITDhtdwci0qefK1QvDlwsAPwMnZOO_J0MxaUpuHtIU_IltC7zs3kfNOYTHEqeIEvEXZHbS3xXNx3g
nonce： B7EE6F5F9AA5CD17CA1AEA43CE848496 
timestamp：1474350784
url: https://www.baidu.com

**Comment by JeffreySu** [comment]
"需填入正确的参数后测试！"这个只是提示，包括已过期什么的，不牵扯到算法，换了之后仍然是一样的。
![image](https://cloud.githubusercontent.com/assets/2281927/18672298/35e6d108-7f7a-11e6-9f62-3adc54d19a0c.png)

![image](https://cloud.githubusercontent.com/assets/2281927/18672374/82e6ad34-7f7a-11e6-8852-0c6913214ddb.png)

**Comment by zheast** [comment]
这是我这边的调试信息，参数都是一样的，sh1str是我用UFT8编码的，signatureStrOri是原本的，另外现在客户端目前用UTF8生成后与微信通信已经正常了，之前一直提示signature错误
![20160921155726](https://cloud.githubusercontent.com/assets/1185072/18702471/7e89440a-8014-11e6-85fb-36e17311ab62.jpg)
![0921161128](https://cloud.githubusercontent.com/assets/1185072/18703182/65b1a208-8017-11e6-8102-5716131d8523.png)

**Comment by JeffreySu** [comment]
你有没有发现timestamp和noceStr被你输错位置了？
正确的顺序是：public static string GetSignature(string ticket, string noncestr, string timestamp, string url)

**Comment by JeffreySu** [comment]
参考：https://github.com/JeffreySu/WeiXinMPSDK/blob/master/src/Senparc.Weixin.MP/Senparc.Weixin.MP/Helpers/JSSDK/JSSDKHelper.cs

**Comment by JeffreySu** [comment]
参考：https://github.com/JeffreySu/WeiXinMPSDK/blob/master/src/Senparc.Weixin.MP/Senparc.Weixin.MP/Helpers/JSSDK/JSSDKHelper.cs#L121

**Comment by zheast** [comment]
Ok,确实是我这边参数输入错误了，竟然一直没有发现，(⊙﹏⊙)b囧就一个！
修正后验证果然是一致的，看来编码不影响最终结果。多谢你的耐心回应。
另外我问下TenPay跟TenPayV3有什么区别，也是针对不同的微信版本吗？
官方支付这块的资料要么找不到，要么打不开

**Comment by JeffreySu** [comment]
TenPay是旧的为新版本（只有你在非常早的时候申请了微信支付才可能需要使用到这个接口），TenPayV3是第三版最新的，现在都只用这个就行了。和客户端没关系。
