### ISSUE TITLE
12月27号后微信不再输出头像和昵称信息，请问是否已经更新了相关功能?

### ISSUE THREAD

**Issue by 15319934357** [JeffreySu/WeiXinMPSDK#2531]
https://developers.weixin.qq.com/doc/offiaccount/User_Management/Get_users_basic_information_UnionID.html#UinonId
相关文档介绍

**Comment by JeffreySu** [comment]
已经在计划中。

**Comment by JeffreySu** [comment]
> ● 关于公众号“关注后用户信息获取接口”调整的通知
平台为公众号开发者提供了关注后用户信息获取接口，以方便公众号开发者对粉丝进行管理。
根据相关法律法规，为保障用户合法权益，2021年12月27日之后，该接口不再输出用户昵称、头像信息。
请开发者及时调整相关接口调用，用户昵称、头像信息请通过相关业务用户授权获取。
点击查看相关接口说明，如有问题可点击咨询客服。

**Comment by JeffreySu** [comment]
已经发布 https://www.nuget.org/packages/Senparc.Weixin.MP/16.17.3
