### ISSUE TITLE
迁移到.net6取消startup问题

### ISSUE THREAD

**Issue by bocblca** [JeffreySu/WeiXinMPSDK#2536]
services.AddSenparcWeixinServices(Configuration)//Senparc.Weixin 注册（必须）
            

实现ICOnfiguration接口的对象，这个参数换成builder. COnfiguration可以不？

**Comment by bocblca** [comment]
这么简单的问题问了两次，没人回答，关了

**Comment by JeffreySu** [comment]
@bocblca 抱歉，在 .NET 6 简洁的写法可以参考这个项目：https://github.com/JeffreySu/MsBuildSample2021

对应的完整视频见：https://live.csdn.net/room/microsoftreactor/M36pgJSo（播放后需要往后拉一下，前面有一段时间没有内容）

其中WorkShop部分单独的见：https://www.bilibili.com/video/BV1Gq4y197mw
