### ISSUE TITLE
怎么去掉默认的message handler返回文字

### ISSUE THREAD

**Issue by cool20212021** [JeffreySu/WeiXinMPSDK#2543]
请问代码里怎么去掉默认message handler返回的消息？

比如：

**您刚才发送了文字信息：中国平安

您此前还发送了如下消息（10/36）：
16:12:57 【Text】中国平安
16:12:44 【Text】MUTE
16:10:04 【Text】MUTE
16:09:50 【Text】中国平安
16:07:45 【Text】MUTE
16:07:17 【Text】中国平安
16:05:21 【Text】中国平安
16:01:11 【Text】中国平安
16:00:56 【Text】中国平安

如果您在3分钟内连续发送消息，记录将被自动保留（当前设置：最多记录10条）。过期后记录将会自动清除。

您还可以发送【位置】【图片】【语音】【视频】等类型的信息（注意是这几种类型，不是这几个文字），查看不同格式的回复。
SDK官方地址：https://sdk.weixin.senparc.com**

**Comment by cool20212021** [comment]
> 这个信息是在代码中自定义的，对应 Sample 的位置在这里：
> 
> https://github.com/JeffreySu/WeiXinMPSDK/blob/ebc94808966753d6e9a8c0f70d81a1f1d3588bbd/Samples/Senparc.Weixin.Sample.CommonService/MessageHandlers/CustomMessageHandler/CustomMessageHandler.cs#L429

谢谢老师回复

我其实在代码里也改掉了这里，默认加了自己的逻辑，也返回了mute response，不知道还是返回入上的默认消息

**Comment by cool20212021** [comment]
能帮我再想想，哪里还可以改的吗？谢谢

**Comment by JeffreySu** [comment]
我对你自定义的逻辑代码内部实现不清楚，这部分没法判断，但是从整体上看，这样是可以让微信不产生任何回复的。

最后一个 return也可以写成：
```
return requestHandler.GetResponseMessage();
```

**Comment by cool20212021** [comment]
> 我对你自定义的逻辑代码内部实现不清楚，这部分没法判断，但是从整体上看，这样是可以让微信不产生任何回复的。
> 
> 最后一个 return也可以写成：
> 
> ```
> return requestHandler.GetResponseMessage();
> ```

谢谢回复，默认是按照你提供的代码的，但不知道为何不work，总会返回消息。如果我返回自己的response content, 微信会同样会返回默认的那段文字，不知道哪里改。。。。难道微信有缓存吗？

**Comment by JeffreySu** [comment]
你有公众号可以给测试一下的吗？我可以帮你看一下。或者发我邮箱：zsu@senparc.com

**Comment by cool20212021** [comment]
公众号名叫:量化树


老师自己搜索下吗？
需要我给你源码和服务器访问权限吗？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JeffreySu/WeiXinMPSDK"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月6日(星期四) 晚上10:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JeffreySu/WeiXinMPSDK] 怎么去掉默认的message handler返回文字 (Issue #2543)





 
***@***.***
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JeffreySu** [comment]
测试了确实有，你直接搜一下源码“您刚才发送”几个字，肯定是有出处的。

**Comment by cool20212021** [comment]
好的，谢谢
我看一下
如果有问题我再问你




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JeffreySu/WeiXinMPSDK"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月7日(星期五) 上午10:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JeffreySu/WeiXinMPSDK] 怎么去掉默认的message handler返回文字 (Issue #2543)





 
测试了确实有，你直接搜一下源码“您刚才发送”几个字，肯定是有出处的。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cool20212021** [comment]
老师你好

不好意思又打扰你了
我把代码修改成如下：
public override async Task<IResponseMessageBase> OnTextRequestAsync(RequestMessageText requestMessage)
        {
            WeixinTrace.Log("OnTextRequestAsync {0}----{1}", requestMessage.Content, requestMessage.FromUserName);

            var defaultRequestHandler = await requestMessage.StartHandler().Default(async () =>
            {
                WeixinTrace.Log("Inside default request handler {0}----{1}", requestMessage.Content, requestMessage.FromUserName);
                var defaultMuteResponseMessage = base.CreateResponseMessage<ResponseMessageNoResponse>();
                return defaultMuteResponseMessage;
            });

            return defaultRequestHandler.GetResponseMessage() as IResponseMessageBase;
        }
部署到服务器后，不知道为何似乎原来的逻辑还在，比如我输入OPEN，公众号还是会返回链接
【开放平台微信授权测试】

输入其他的文本，还是会之前提到的文字信息

但是我加的日志能够在日志里找到，说明代码生效了
[[[系统日志]]]
[2022/01/08 15:46:26.1973]
[线程：10]
Inside default request handler open----ojOUf5ztGJKUsMqXNQbEhHjQAHEs

请问是因为有缓存吗还是其他的？我找源代码，似乎也没有其他地方有类似的的逻辑。能帮忙再想想吗？

**Comment by JeffreySu** [comment]
我能想到最有可能的是你微信后台配置的消息接口，和你实际更新的服务不是同一个，因为你程序里都没有这个文字了，不可能会再出来。

当然还有另外一个可能是你授权了其他第三方的平台回复这些消息，这个你可以直接在公众号后台取消授权。

**Comment by cool20212021** [comment]
谢谢回复
但是确实从日志里看，我新添加的逻辑都work了，好奇怪
我自己再研究研究
谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JeffreySu/WeiXinMPSDK"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月8日(星期六) 晚上10:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JeffreySu/WeiXinMPSDK] 怎么去掉默认的message handler返回文字 (Issue #2543)





 
我能想到最有可能的是你微信后台配置的消息接口，和你实际更新的服务不是同一个，因为你程序里都没有这个文字了，不可能会再出来。
 
当然还有另外一个可能是你授权了其他第三方的平台回复这些消息，这个你可以直接在公众号后台取消授权。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JeffreySu** [comment]
如果你确定已经没有任何源码的干预，并且部署是没有问题的，那就本上就只剩下检查一下是否有对外的第三方授权，由其他的服务在帮你回复。

**Comment by cool20212021** [comment]
好的
万分感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JeffreySu/WeiXinMPSDK"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月19日(星期三) 下午3:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JeffreySu/WeiXinMPSDK] 怎么去掉默认的message handler返回文字 (Issue #2543)





 
如果你确定已经没有任何源码的干预，并且部署是没有问题的，那就本上就只剩下检查一下是否有对外的第三方授权，由其他的服务在帮你回复。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
