### ISSUE TITLE
https://api.weixin.qq.com/wxa/generate_urllink 小程序接口未找到

### ISSUE THREAD

**Issue by HandsomeBoy01** [JeffreySu/WeiXinMPSDK#2546]
https://api.weixin.qq.com/wxa/generate_urllink  这个小程序接口 在SDK 中未找到，是没有添加吗？

**Comment by HandsomeBoy01** [comment]
Senparc.Weixin.WxOpen 3.14.2 的版本  未找到！！急用

**Comment by HandsomeBoy01** [comment]
@JeffreySu

**Comment by JeffreySu** [comment]
已经加急处理。
以后麻烦按照issue要求格式，提供官方文档等信息，可以提高处理速度。谢谢！

**Comment by JeffreySu** [comment]
@HandsomeBoy01 已发布新版本：WxOpen v3.14.2，并添加（通过）单元测试（https://github.com/JeffreySu/WeiXinMPSDK/blob/99aa23e3a678790122492f834f8814e1792ea99c/src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen.Tests/AdvancedAPIs/WxApp/UrlLinkApiTests.cs#L12）。

单元测试结果：
```
﻿ GenerateTest
   源: UrlLinkApiTests.cs 行 12
   持续时间: 1.9 秒

  标准输出: 
{
  "url_link": "https://wxaurl.cn/LROTLu5OFxi",
  "errcode": 0,
  "ErrorCodeValue": 0,
  "errmsg": "ok",
  "P2PData": null
}
```

**Comment by HandsomeBoy01** [comment]
@JeffreySu   辛苦了，终于能开发了
