### ISSUE TITLE
开放平台公众号权限集和枚举定义的对不上，缺少了许多

### ISSUE THREAD

**Issue by HandsomeBoy01** [JeffreySu/WeiXinMPSDK#2547]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
https://developers.weixin.qq.com/doc/oplatform/Third-party_Platforms/2.0/product/offical_account_authority.html
以上连接是微信定义的开发平台的权限集，

FuncscopeCategory  这个枚举里面少了好多，导致有些获取的显示不完全。

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 微信官方文档 URL
https://developers.weixin.qq.com/doc/oplatform/Third-party_Platforms/2.0/product/offical_account_authority.html

##### 微信官方文档快照（直接复制关键内容到下方）

![image](https://user-images.githubusercontent.com/40994318/148473874-4dbf2741-520a-46ce-8d2c-1b75808658c6.png)
![image](https://user-images.githubusercontent.com/40994318/148474048-a44d13f1-20cd-4ed3-8beb-5f6e3177180a.png)

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [√ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] Senparc.Weixin.Tenpay 版本：
- [ ] Senparc.WebSocket 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5+
- [ ] .net standard 2.0 / 2.1
- [ ] .net core 1.x
- [ ] .net core 2.x
- [ ] .net core 3.x
- [x] .net 5.x / 6.x

##### 开发环境

- [ ] Visual Studio 2019
- [x] Visual Studio 2022
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [x] Windows，版本：
- [ ] Linux，版本：
- [ ] Mac，版本：
- [ ] 其他：

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by HandsomeBoy01** [comment]
good 正在更新，这效率杠杠滴

**Comment by JeffreySu** [comment]
已经发布 [Open v4.13.4](https://www.nuget.org/packages/Senparc.Weixin.Open/4.13.4) ，非常感谢！也欢迎直接 PR，成为 Contributor ：）
