### ISSUE TITLE
请教一下只注册最基础的，需要注意什么？

### ISSUE THREAD

**Issue by imgd** [JeffreySu/WeiXinMPSDK#2550]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
因为项目会涉及到配置是读取缓存或者数据库的，公众号配置是动态的根据不同的客户读取，不会默认启动根据配置文件注册。
请问下需要注意什么？

##### 重现问题步骤（如果可以）
最基础的注册
![image](https://user-images.githubusercontent.com/5319255/148917086-3a6e252e-b33b-4f27-a2b6-e3730944e4bf.png)

尝试写了一些方法类似于获取accesstoken 、oauth授权 是可以调通
![image](https://user-images.githubusercontent.com/5319255/148917765-e6ed7049-0ff8-4bac-a3ee-0988ec554c4a.png)
![image](https://user-images.githubusercontent.com/5319255/148917845-9622b262-3810-42aa-85c1-19e3c6626682.png)

1. ...
2. ...

##### 发现问题的模块

- [x ] Senparc.Weixin 版本：6.14
- [x ] Senparc.Weixin.MP 版本：16.17.3
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] Senparc.Weixin.Tenpay 版本：
- [ ] Senparc.WebSocket 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5+
- [ ] .net standard 2.0 / 2.1
- [ ] .net core 1.x
- [ ] .net core 2.x
- [ ] .net core 3.x
- [x] .net 5.x / 6.x

##### 开发环境

- [ ] Visual Studio 2019
- [x] Visual Studio 2022
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [x ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [x] Windows，版本：
- [x] Linux，版本：
- [ ] Mac，版本：
- [ ] 其他：

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
@imgd 如果不需要立即注册公众号，虽然在 app.UseSenparcGlobal() 里面不添加代码（因为不需要配置缓存等），后面的 .UseSenparcWeixin() 还是需要写的，委托也是可以留空的。

**Comment by imgd** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by imgd** [comment]
好的，谢谢
