### ISSUE TITLE
统一服务消息无法跳转小程序指定页面

### ISSUE THREAD

**Issue by vsantw** [JeffreySu/WeiXinMPSDK#2554]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
![image](https://user-images.githubusercontent.com/20358243/150244164-ec11e8ae-985e-4312-adcd-663d188ba7b5.png) 
解决方法   字段 page改成 pagepath 即可

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] Senparc.Weixin.Tenpay 版本：
- [ ] Senparc.WebSocket 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5+
- [ ] .net standard 2.0 / 2.1
- [ ] .net core 1.x
- [ ] .net core 2.x
- [ ] .net core 3.x
- [x] .net 5.x / 6.x

##### 开发环境

- [ ] Visual Studio 2019
- [x] Visual Studio 2022
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [x] Windows，版本：
- [ ] Linux，版本：
- [ ] Mac，版本：
- [ ] 其他：

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
@vsantw 您说的是 WxOpen 下面的 TempleteModel.cs 里面的吗？

如果是的话，这个接口微信官方的实现似乎有点问题，不管写 page 或者 pagepath，都会有的账号可用，有的不可用，您可以试一下小程序“盛派网络小助手”，点击【订阅消息】按钮，可以体验能够跳转的效果，这个 Sample 用的就是 page。

**Comment by JeffreySu** [comment]
> @vsantw 您说的是 WxOpen 下面的 TempleteModel.cs 里面的吗？
> 
> 如果是的话，这个接口微信官方的实现似乎有点问题，不管写 page 或者 pagepath，都会有的账号可用，有的不可用，您可以试一下小程序“盛派网络小助手”，点击【订阅消息】按钮，可以体验能够跳转的效果，这个 Sample 用的就是 page。

抱歉，纠正一下，这个接口还没有接入到 Sample，我会尽快升级一下测试，不过确实收到各种反馈，反而用 page 就可以：
https://weixin.senparc.com/QA-17333

**Comment by JeffreySu** [comment]
目前已发布新版本（WxOpen v3.14.5），支持使用不同实现类来决定使用 page 或 pagepath 参数。

使用方法：
需要使用 pagepath 参数：
``` C#
               var miniprogram = new Miniprogram_PagePath(WxOpenAppId, pagePath);

               UniformSendData msgData = new(
                   sessionBag.OpenId,
                   new Mp_Template_Msg(mpAppId,
                                       mpTemplateId,
                                       "https://dev.senparc.com",
                                       miniprogram,
                                       templateData)
```
需要使用 page 参数，只需修改实现类，其他代码不变：
```
               var miniprogram = new ·Miniprogram_Page(WxOpenAppId, pagePath);
```

**Comment by vsantw** [comment]
感谢更新
