### ISSUE TITLE
jssdk扫码后自己会退到公众号聊天窗口

### ISSUE THREAD

**Issue by SevenBoy2012** [JeffreySu/WeiXinMPSDK#256]
@JeffreySu 
用的网页授权
在自定义菜单里填写了网页授权那个url
点击菜单后进到网页  然后点击按钮调用扫一扫  扫码得到结果后 返回了公众号聊天窗口。
手机是坚果手机  发现有下图的情况 （好像菜单点击后就不在微信里面打开了网页了）：
![image](https://cloud.githubusercontent.com/assets/2778925/18866586/345c54bc-84d3-11e6-8185-53a1b9e0ce04.png)

**Comment by JeffreySu** [comment]
没看明白是什么情况？

**Comment by SevenBoy2012** [comment]
前提是用的坚果手机    如上图两个页面   好像微信公众号里点了菜单上的链接后  不是在微信内部打开网页的  而是像上面图片那样的另外开了个小的进程    导致  在第二个页面点击扫码后   页面返回了第一个页面  其他安卓手机和苹果手机都没发现这个情况  所以感觉很奇怪

**Comment by SevenBoy2012** [comment]
这种情况还不好重现  
坚果手机 微信关注顺丰快递的公众号  查询快递的时候 点扫码  就可以重现这个问题了  测了下其他手机没发现这个问题

**Comment by JeffreySu** [comment]
那应该是微信客户端APP的问题了，SDK处理不了。

**Comment by SevenBoy2012** [comment]
嗯嗯 是啊  所以想问问有没有遇到过  想找个处理方法

**Comment by JeffreySu** [comment]
暂时没发现这个问题
