### ISSUE TITLE
为什么一直有输出信息，怎么取消

### ISSUE THREAD

**Issue by bbhxwl** [JeffreySu/WeiXinMPSDK#2573]
小程序，我配置文件的IsDebug设置了false，怎么一直都有输出信息，太多了。怎么取消。我只用了这个方法
SnsApi.JsCode2Json
![image](https://user-images.githubusercontent.com/26525599/153832069-4f634aa7-578b-414e-b898-b436c61f452a.png)

**Comment by bbhxwl** [comment]
> 这明显是你宿主生成的日志，和SDK没有关系，你宿主（比如 dotnet 命令行，或者 Web 项目配置文件）配置成把所有日志输出到文件了。

我知道我这是控制台输出，然后用的进程守护，所有的控制台输出都会输出到文件，我的意思是，为什么会有这个输出。

**Comment by JeffreySu** [comment]
查一下是不是你的程序里面设置了比如log4net或者其他日志模块的输出，或者被别的第三方模块设置成输出了，最简单的辨别方法，你可以运行一下我们Sample，是没有这样的情况的。

**Comment by bbhxwl** [comment]
> 查一下是不是你的程序里面设置了比如log4net或者其他日志模块的输出，或者被别的第三方模块设置成输出了，最简单的辨别方法，你可以运行一下我们Sample，是没有这样的情况的。

我的意思，访问一次，有4个输出，这个输出是你们这个方法内部输出的么？不是说为什么写出到文件了。

**Comment by bbhxwl** [comment]
> > > 这明显是你宿主生成的日志，和SDK没有关系，你宿主（比如 dotnet 命令行，或者 Web 项目配置文件）配置成把所有日志输出到文件了。
> > 
> > 
> > 我知道我这是控制台输出，然后用的进程守护，所有的控制台输出都会输出到文件，我的意思是，为什么会有这个输出。
> 
> 根据你的日志看，这个就是 info 级别的日志，你关掉就行了。PS：当然我不知道你用的什么工具，怎么关需要你自己看了，或者如果有可以重现问题的最小化项目或许可以帮助你分析一下。

ok，稍等。就因为我项目里面也用到了其他httpclient，都没有任何输出，我都可以控制到。就最近添加你们这个sdk想测试下，不知道什么时候出现的这个。

**Comment by JeffreySu** [comment]
当然还有一个可能是你某个地方 Hook 到 CO2NET 里面的 HTTP 发送过程了，但这个还是需要通过你外部关闭的。

**Comment by bbhxwl** [comment]
> 当然还有一个可能是你某个地方 Hook 到 CO2NET 里面的 HTTP 发送过程了，但这个还是需要通过你外部关闭的。

最小项目好了，马上发您，也还是这个问题。

**Comment by bbhxwl** [comment]
[WebApplication6.zip](https://github.com/JeffreySu/WeiXinMPSDK/files/8072701/WebApplication6.zip)

**Comment by bbhxwl** [comment]
> 

新建的项目net core3.1，全部默认的，除了关于Senparc 的东西。没改过任何东西

**Comment by JeffreySu** [comment]
> 

您回复看一下我提的两个问题：
1、只用 Sample，是否会有？（排除第三方和配置干扰）
2、POST 和 GET 方法是否都有？（锁定Trace 某些特征）

**Comment by JeffreySu** [comment]
> > > 
> > 
> > 
> > 您回复看一下我提的两个问题： 1、只用 Sample，是否会有？（排除第三方和配置干扰） 2、POST 和 GET 方法是否都有？（锁定Trace 某些特征）
> 
> 我刚发的zip 项目，就是最小的了。官方的Sample 下载下来很多错误运行不起来。刚才这个项目肯定没第三方干扰，没多少行代码。新建的项目，没用的东西也都删除了。没任何第三方sdk。 2：我目前只用了这一个code获取openid方法，还没深入用其他的呢。这一天测试就有10几M的文件，

所有 Sample 都是可以运行的，这是帮你解决问题最快的路径之一，如果有问题，把问题发上来。

**Comment by bbhxwl** [comment]
![image](https://user-images.githubusercontent.com/26525599/154104370-332b95a3-f023-4ac2-a1b0-523287d5ee27.png)
这应该打开哪个文件能运行不出错呢。

**Comment by bbhxwl** [comment]
想单独打开项目编译，也出错。您刚说给整个最小项目测试下，我刚发了，求帮忙看下呗。
![image](https://user-images.githubusercontent.com/26525599/154104799-545c9098-9f3a-4d4a-b520-e423c2172829.png)

**Comment by bbhxwl** [comment]
JsCode2JsonAsync和JsCode2Json 效果都是这样。
![image](https://user-images.githubusercontent.com/26525599/154105255-314305c8-8f17-4b7f-942a-48324eec52a6.png)

**Comment by JeffreySu** [comment]
> ![image](https://user-images.githubusercontent.com/26525599/154104370-332b95a3-f023-4ac2-a1b0-523287d5ee27.png) 这应该打开哪个文件能运行不出错呢。

碰到这种错误，找到最根源的一个异常，比如Senparc.Weixin下面CSC或者阻碍你编译的，看一下比如是不是某个 .NET 版本没有装（这个是multi-target版本）

**Comment by bbhxwl** [comment]
![C52K() V7ZGB%{X EC _BPE](https://user-images.githubusercontent.com/26525599/154107549-18f77068-ce7c-4675-a801-eccb445f46cb.png)
修复不了，您帮帮忙看下呗，已经删不可删，Configure 再删一个都出错，ConfigureServices 也是没多余的一行代码了。还是有输出。第三方插件也没其他的，只有Senparc.CO2NET.AspNet+Senparc.Weixin.WxOpen    ，研究2天了，其他post请求，再怎么写都没输出，所以觉得可能需要设置Senparc的哪里，或是Senparc 内部忘了去掉输出之类的。
![image](https://user-images.githubusercontent.com/26525599/154107988-0d51f7b1-631f-4024-9477-d4845317c895.png)


![image](https://user-images.githubusercontent.com/26525599/154107773-e369acc0-26b4-489f-8ad8-1f7a2b14ffbe.png)

**Comment by JeffreySu** [comment]
> JsCode2JsonAsync和JsCode2Json 效果都是这样。 ![image](https://user-images.githubusercontent.com/26525599/154105255-314305c8-8f17-4b7f-942a-48324eec52a6.png)

这个日志就清楚了，这个是 HttpClientFactory 的日志，默认就会有跟踪信息，底层 CO2NET 的请求是使用 HttpClientFactory 的。

**Comment by JeffreySu** [comment]
稍等我手写一个解决方案给你，稍等我 10 分钟，HttpClientFactory 是一个很好的东西，顺便推荐一些相关介绍：
https://www.cnblogs.com/deepthought/p/11303015.html
https://www.jianshu.com/p/732aee097c6b
https://www.cnblogs.com/ccaa/p/13047255.html

**Comment by JeffreySu** [comment]
@bbhxwl

创建一个类：
```
    public class OmitInfoLogMessageHandlerFilter : IHttpMessageHandlerBuilderFilter
    {
        public Action<HttpMessageHandlerBuilder> Configure(Action<HttpMessageHandlerBuilder> next)
        {
            _ = next == null ? throw new ArgumentNullException(nameof(next)) : 1;
            return (builder) => next(builder);
        }
    }
```

然后在 startup.cs 的 ConfigureServices() 方法最后加一行代码：

```
services.Replace(ServiceDescriptor.Singleton<IHttpMessageHandlerBuilderFilter, OmitInfoLogMessageHandlerFilter>());
```

搞定。

**Comment by bbhxwl** [comment]
> 稍等我手写一个解决方案给你，稍等我 10 分钟，HttpClientFactory 是一个很好的东西，顺便推荐一些相关介绍：
> https://www.cnblogs.com/deepthought/p/11303015.html
> https://www.jianshu.com/p/732aee097c6b
> https://www.cnblogs.com/ccaa/p/13047255.html

我自己都是new HttpClient用，GetStringAsync啥的，没日志呢，我查查你用的，没用过呢

**Comment by bbhxwl** [comment]
> @bbhxwl
> 
> 创建一个类：
> 
> ```
>     public class OmitInfoLogMessageHandlerFilter : IHttpMessageHandlerBuilderFilter
>     {
>         public Action<HttpMessageHandlerBuilder> Configure(Action<HttpMessageHandlerBuilder> next)
>         {
>             _ = next == null ? throw new ArgumentNullException(nameof(next)) : 1;
>             return (builder) => next(builder);
>         }
>     }
> ```
> 
> 然后在 startup.cs 的 ConfigureServices() 方法最后加一行代码：
> 
> ```
> services.Replace(ServiceDescriptor.Singleton<IHttpMessageHandlerBuilderFilter, OmitInfoLogMessageHandlerFilter>());
> ```
> 
> 搞定。

多谢，所以说别人应该都会有这个是吧

**Comment by JeffreySu** [comment]
> > @bbhxwl
> > 创建一个类：
> > ```
> >     public class OmitInfoLogMessageHandlerFilter : IHttpMessageHandlerBuilderFilter
> >     {
> >         public Action<HttpMessageHandlerBuilder> Configure(Action<HttpMessageHandlerBuilder> next)
> >         {
> >             _ = next == null ? throw new ArgumentNullException(nameof(next)) : 1;
> >             return (builder) => next(builder);
> >         }
> >     }
> > ```
> >   
> > 然后在 startup.cs 的 ConfigureServices() 方法最后加一行代码：
> > ```
> > services.Replace(ServiceDescriptor.Singleton<IHttpMessageHandlerBuilderFilter, OmitInfoLogMessageHandlerFilter>());
> > ```
> >   
> > 搞定。
> 
> 多谢，所以说别人应该都会有这个是吧

不是，别人可能压根没有用 HttpClientFactory，不然如果处理了就不会出来了，因为要注意一下：这个 Replace 是全局的，针对所有的 HttpClientFactory。

这个是 CO2NET 为大家提供的一个应对高并发的增强能力，上述代码的作用是覆盖掉 .NET 默认提供的记录日志的 Filter 的源码。

**Comment by lishewen** [comment]
如果你是用VS默认模板的话，只要在`appsettings.json`加上最后这句就不会有这些提示了
```json
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.Hosting.Lifetime": "Information",
      "System.Net.Http.HttpClient": "Warning"
    }
  }
```

**Comment by lishewen** [comment]
即对`System.Net.Http.HttpClient`只输出警告级别以上的日志，默认是Information
