### ISSUE TITLE
企业微信通讯录回调无法获取用户基本信息

### ISSUE THREAD

**Issue by zl2fxy** [JeffreySu/WeiXinMPSDK#2578]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
企业微信通讯录回调无法获取用户基本信息

##### 重现问题步骤（如果可以）

1. ...继承Senparc.Weixin.Work.MessageHandlers.WorkMessageHandler
2. ...重写方法OnEvent_ChangeContactUpdateUserRequest(RequestMessageEvent_Change_Contact_User_Update wechatUser)
3. ...在方法里无法获取wechatUser相关数据，包含部门信息

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [x] Senparc.Weixin.Work 版本：3.14.5
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] Senparc.Weixin.Tenpay 版本：
- [ ] Senparc.WebSocket 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5+
- [ ] .net standard 2.0 / 2.1
- [ ] .net core 1.x
- [ ] .net core 2.x
- [ ] .net core 3.x
- [x] .net 5.x / 6.x

##### 开发环境

- [ ] Visual Studio 2019
- [x] Visual Studio 2022
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [x] Windows，版本：
- [ ] Linux，版本：
- [ ] Mac，版本：
- [ ] 其他：

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
@zl2fxy 能否把收到的XML发一下？

**Comment by JeffreySu** [comment]
我测试了一下是正常的，注意：回调消息只会告诉你具体修改的值：

```
<xml>
  <ToUserName><![CDATA[ww8533***]]></ToUserName>
  <FromUserName><![CDATA[sys]]></FromUserName>
  <CreateTime>1645108596</CreateTime>
  <MsgType><![CDATA[event]]></MsgType>
  <Event><![CDATA[change_contact]]></Event>
  <ChangeType><![CDATA[update_user]]></ChangeType>
  <UserID><![CDATA[SuZhenWei]]></UserID>
  <EnglishName><![CDATA[Jeffrey]]></EnglishName>
  <Alias><![CDATA[Jeffrey]]></Alias>
  <Address><![CDATA[苏州]]></Address>
</xml>
```

另外，现在最新的版本是 v3.14.9，建议升级到最新，顺便我们的测试信息也可以同步。
