### ISSUE TITLE
OnEvent_SubscribeRequestAsync不能触发，却进入了OnTextOrEventRequestAsync

### ISSUE THREAD

**Issue by CatcherX** [JeffreySu/WeiXinMPSDK#2610]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
用户关注公众号时请求报文：
```
<xml>
  <ToUserName><![CDATA[toUser]]></ToUserName>
  <FromUserName><![CDATA[FromUser]]></FromUserName>
  <CreateTime>{{$timestamp}}</CreateTime>
  <MsgType><![CDATA[event]]></MsgType>
  <Event><![CDATA[subscribe]]></Event>
  <EventKey><![CDATA[qrscene_123123]]></EventKey>
  <Ticket><![CDATA[TICKET]]></Ticket>
</xml>
```

调试发现始终无法进入OnEvent_SubscribeRequestAsync方法，却进入了OnTextOrEventRequestAsync

##### 微信官方文档快照（直接复制关键内容到下方）
关注/取消关注事件 | 微信开放文档
https://developers.weixin.qq.com/doc/offiaccount/Message_Management/Receiving_event_pushes.html

##### 发现问题的模块
Senparc.Weixin.MP.Middleware 0.3.100.1-preview2 

##### 自定义的消息处理器部分代码：
```
public override async Task<IResponseMessageBase> OnEvent_SubscribeRequestAsync(RequestMessageEvent_Subscribe requestMessage)
        {
            var responseMessage = CreateResponseMessage<ResponseMessageNews>();
            responseMessage.Articles.Add(new Article()
            {
                Title = "国思公众号",
                Description = "欢迎关注国思软件公众号，更多内容稳步官网，多谢！",
                PicUrl = "http://www.rdiframework.net/WeiXin.png",
                Url = "http://www.rdiframework.net/"
            });

            return responseMessage;
        }

      public override async Task<IResponseMessageBase> OnTextOrEventRequestAsync(RequestMessageText requestMessage)
        {
            .................
        }
```

**Comment by CatcherX** [comment]
MessageHandler(TMC).OnTextOrEventRequestAsync 方法
http://doc.weixin.senparc.com/html/M_Senparc_Weixin_MP_MessageHandlers_MessageHandler_1_OnTextOrEventRequestAsync.htm

根据文档描述，会先进入OnTextOrEventRequestAsync 方法，进入之后，报文变化，消息类型变成了Text，如何区分是关注事件？
```
<?xml version="1.0" encoding="utf-16"?>
<RequestMessageText xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <ToUserName>toUser</ToUserName>
  <FromUserName>FromUser</FromUserName>
  <CreateTime />
  <MsgId>0</MsgId>
  <MsgType>Text</MsgType>
  <Content>qrscene_123123</Content>
</RequestMessageText>
```

**Comment by CatcherX** [comment]
MessageHandler(TMC).OnTextRequestAsync 方法
http://doc.weixin.senparc.com/html/M_Senparc_Weixin_MP_MessageHandlers_MessageHandler_1_OnTextRequestAsync.htm

查到了，要区分的话，不应该用OnTextOrEventRequestAsync 方法，而是分开写？

**Comment by JeffreySu** [comment]
OnTextOrEventRequestAsync 只是作为统一处理的场所，以及中转，本身不会影响数据（不重写 OnTextOrEventRequestAsync  或者 OnTextOrEventRequest 的话，会继续进入到 Event 对应方法）。
