### ISSUE TITLE
CardApi.CardDetailGet在获取会员卡时报错,请尽快修复.

### ISSUE THREAD

**Issue by gwhzh21** [JeffreySu/WeiXinMPSDK#262]
"custom_field1":{"name_type":"FIELD_NAME_TYPE_UNKNOW" ,无法识别FIELD_NAME_TYPE_UNKNOW

**Comment by JeffreySu** [comment]
你确定是CardApi.CardDetailGet()这个方法吗？这里面好像没有涉及到custom_field1和name_type。
找到问题后我们会尽快核查处理，感谢反馈！

**Comment by gwhzh21** [comment]
这个问题是这样的．创建会员的时候，新版会员，有三个custom_field可以填，但是在创建的时候，一直都是传的name_type:0[enum的值0,1....]本来应该是字符串的．创建的时候，在微信服务器就为未知类型了，结果在获取的时候，因为微信回传的是FIELD_NAME_TYPE_UNKNOW,enum里面没有这个值．导致出现此问题，解决enum序列化的问题，就能解决这创建会员和获取会员卡的问题了．

**Comment by JeffreySu** [comment]
已经看到这个问题了，jsonSetting里面针对EnmuString的配置没有生效，我们会尽快处理，感谢反馈！

**Comment by starpunk** [comment]
大半年过去了

**Comment by gwhzh21** [comment]
此问题的主要原因是缺少此枚举值。补上即可。此枚举值主要是用于关闭custom_field。
