### ISSUE TITLE
无法安装程序包“Senparc.Weixin.TenPayV3 0.5.7”

### ISSUE THREAD

**Issue by wangjiashuy** [JeffreySu/WeiXinMPSDK#2634]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
NuGet无法安装TenPayV3
  CACHE https://api.nuget.org/v3/registration5-gz-semver2/senparc.weixin.tenpayv3/index.json
已解析操作以安装程序包“Senparc.Weixin.TenPayV3.0.5.7”
安装失败。正在回滚...
包“Senparc.Weixin.TenPayV3.0.5.7”不存在于项目“DDMao”中
包“Senparc.Weixin.TenPayV3.0.5.7”不存在于文件夹“C:\Users\ddmao\Downloads\webs\DDMao_v2\packages”中
执行 nuget 操作花费时间 474 ms
无法安装程序包“Senparc.Weixin.TenPayV3 0.5.7”。你正在尝试将此程序包安装到目标为“.NETFramework,Version=v4.7.2”的项目中，但该程序包不包含任何与该框架兼容的程序集引用或内容文件。有关详细信息，请联系程序包作者。
已用时间: 00:00:00.5162881
========== 已完成 ==========

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] Senparc.Weixin.Tenpay 版本：
- [ ] Senparc.WebSocket 版本：
- [x] 其他模块：TenPayV3

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [x ] .net 4.5+
- [ ] .net standard 2.0 / 2.1
- [ ] .net core 1.x
- [ ] .net core 2.x
- [ ] .net core 3.x
- [] .net 5.x / 6.x

##### 开发环境

- [ ] Visual Studio 2019
- [x] Visual Studio 2022
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [x] Windows，版本：
- [ ] Linux，版本：
- [ ] Mac，版本：
- [ ] 其他：

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
您看一下是不是没有成功还原，或者先卸载，再安装一下最新的版本。
