### ISSUE TITLE
一直返回40029，用了同步锁还是不能解决,已经2天了，解决不了，谢谢

### ISSUE THREAD

**Issue by Allen20162151** [JeffreySu/WeiXinMPSDK#264]
一开始GetAuthorizeUrl进入授权页面，没问题，点击授权以后，换取CODE，进行GetAccessToken开始报错，返回40029,  
string openid;
            Senparc.Weixin.MP.AdvancedAPIs.OAuth.OAuthAccessTokenResult model = null;
            try
            {
                var isSecondRequest = false;
                lock (OauthCodeCollectionLock)
                {
                    isSecondRequest = OauthCodeCollection.ContainsKey(code);
                }
                if (!isSecondRequest)
                {
                    //第一次请求
                    lock (OauthCodeCollectionLock)
                    {

```
                    WeixinTrace.Log("第一次微信OAuth到达，code：}"+ code);
                    OauthCodeCollection[code] = null;
                }
            }
            else
            {
                //第二次请求
                lock (OauthCodeCollectionLock)
                {
                    WeixinTrace.Log("第二次微信OAuth到达，code：}" + code);
                    model = OauthCodeCollection[code];
                }
            }

            try
            {
                try
                {

                    model = model ?? OAuthApi.GetAccessToken(WeChatConfig.AppID, WeChatConfig.AppSecret, code);
                }
                catch (Exception ex)
                {
                    return Content("OAuth AccessToken错误：" + ex.Message);
                }
                if (model != null)
                {
                    lock (OauthCodeCollectionLock)
                    {
                        OauthCodeCollection[code] = model;
                    }
                }
            }
            catch (ErrorJsonResultException ex)
            {
                if (ex.JsonResult.errcode == ReturnCode.不合法的oauth_code)
                {
                    //code已经被使用过
                    //code已经被使用过
                    lock (OauthCodeCollectionLock)
                    {
                        model = OauthCodeCollection[code];
                    }
                }
            }
            openid = model != null ? model.openid : null;
        }
        catch (Exception ex)
        {
            return Content("授权过程发生错误：" + ex.Message);
        }
```

**Comment by JeffreySu** [comment]
能不能跟踪一下，发一下某个人的完整的log记录上来？

**Comment by Allen20162151** [comment]
发现问题的时候，
第一次测试：
我用WX开发工具能看到请求CODE的URL的变化，还多了几个参数，最后还是返回了一个URL的链接，里面包含了CODE和SATAE，我用这个CODE拼接获取accesstoken的请求，直接放到URL执行发现还是返回40029，这个时候，回调方法里面，SDK包里面的OAuthApi.GetAccessToken这个方法我还没有注释掉，说明在我手动拼接URL之前，这个CODE就已经给用掉或者过期掉了，用LOG，输出只看到
Time:    2016/10/13 10:42:19
Action:  第一次微信OAuth到达
Message: /OAuth2/Authorize?code=011YIIVx1EDlZ30hnoVx1pXDVx1YIIV9&state=Member
说明这个方法只运行了一次？还是运行了我没监控到？

第二次测试开始：
我把回调方法里面的SDK包里面的OAuthApi.GetAccessToken这个方法注释掉，（这里就算进入回调也不会请求，说明，CODE肯定不会在这里用掉），然后通过请求授权页面，还是能看到WX开发工具URL那里的变化，也是同样多了几个参数，然后返回了一个回调的URL，里面包含CODE和SATAE，这个时候我再次手动用返回来的CODE，拼接请求换取ACCESSTOKEN，然后复制到WX开发工具里面的URL框里面运行，发现成功了。成功返回了JSON数据。

通过这两次测试，我就奇怪了，那在我没注释掉回调方法里面，SDK包里面的OAuthApi.GetAccessToken这个方法之前，这个CODE用去了哪里？
如何处理这个问题呢？

**Comment by JeffreySu** [comment]
不知道你有没有看过这篇文章：https://github.com/JeffreySu/WeixinResource/blob/master/%E9%82%A3%E4%BA%9B%E5%B9%B4%E6%88%91%E4%BB%AC%E8%B8%A9%E8%BF%87%E7%9A%84%E5%9D%91/20160913-OAuth%E5%87%BA%E7%8E%B040029(invalid%20code)%E9%94%99%E8%AF%AF.md

你说的问题可以认为是微信的一个bug，看你的代码应该是从里面来的，建议看一下，你说的现象应征了我们发现的问题。

你第一次测试，就是2次请求已经帮你用掉了，你再去复制code使用，当然是无效的了。

**Comment by feifanyajun** [comment]
现在这个版本的，如果把BaseCallback方法直接放到微信菜单上，点击后还是会存在40029code不可用的错误
https://open.weixin.qq.com/connect/oauth2/authorize?appid=wxedd537864775bb75&redirect_uri=http%3A%2F%2Fmedicalcloud.cn%2Fyiyuntong%2Foauth2%2FUserInfoCallback%3FreturnUrl%3D%252fyiyuntong%252foauth2%252fTestReturnUrl&response_type=code&scope=snsapi_userinfo&state=JeffreySu-786&connect_redirect=1#wechat_redirect

**Comment by feifanyajun** [comment]
而且是，如果出现40029错误后，点击返回按钮就会出现未知链接

![image](https://cloud.githubusercontent.com/assets/19487214/20590171/8202cda2-b25c-11e6-92c8-9fc38dd86193.png)

**Comment by JeffreySu** [comment]
你按照上面我给的方法尝试了吗？
另外看一下我们Sample里面的做法（Sample的没有用我上面解决40029的解决方法，但是页面逻辑都是正确的）。
