### ISSUE TITLE
企业微信通讯录模块创建/更新成员的参数缺少企业邮箱参数“biz_mail”

### ISSUE THREAD

**Issue by zxz19** [JeffreySu/WeiXinMPSDK#2647]
Senparc.Weixin.Work.AdvancedAPIs.MailList.Member.Member中Member相关Model缺少biz_mail属性

============================
企业微信官方文档说明：
biz_mail	否	企业邮箱。仅对开通企业邮箱的企业有效。长度6~64个字节，且为有效的企业邮箱格式。企业内必须唯一。未填写则系统会为用户生成默认企业邮箱（可修改一次，2022年4月25日之后创建的成员需通过企业管理后台-协作-邮件-邮箱管理-成员邮箱修改）

**Comment by JeffreySu** [comment]
@zxz19 麻烦尽量按照Issue模板填写，提供一下明确的文档地址。

**Comment by zxz19** [comment]
企业微信官方文档：https://developer.work.weixin.qq.com/document/path/90195

**Comment by JeffreySu** [comment]
没有新的反馈，关闭了，感谢！
