### ISSUE TITLE
MessageHandler中Execute()过程发生错误：The type initializer for 'NeuralSystemNested' threw an exception.

### ISSUE THREAD

**Issue by imgd** [JeffreySu/WeiXinMPSDK#2648]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
微信开发者接入，微信服务器POST过来，
关注公众号事件报错：
MessageHandler 消息转发执行报错
`Senparc.NeuChar.Exceptions.MessageHandlerException: MessageHandler中Execute()过程发生错误：The type initializer for 'NeuralSystemNested' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'NeuralSystemNested' threw an exception.
 ---> System.UnauthorizedAccessException: Access to the path 'C:\inetpub\wwwroot\PMP_API_WeiXin\App_Data\NeuChar' is denied.
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at Senparc.NeuChar.NeuralSystem.ReloadNode()
   at Senparc.NeuChar.NeuralSystem..ctor()
   at Senparc.NeuChar.NeuralSystem.NeuralSystemNested..cctor()
   --- End of inner exception stack trace ---
   at Senparc.NeuChar.NeuralSystem.get_Instance()
   at Senparc.NeuChar.MessageHandlers.MessageHandler`3.get_CurrentMessageHandlerNode()
   at Senparc.Weixin.MP.MessageHandlers.MessageHandler`1.BuildResponseMessageAsync(CancellationToken cancellationToken)
   at Senparc.NeuChar.MessageHandlers.MessageHandler`3.ExecuteAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Senparc.NeuChar.MessageHandlers.MessageHandler`3.ExecuteAsync(CancellationToken cancellationToken)
   at Senparc.NeuChar.MessageHandlers.MessageHandler`3.ExecuteAsync(CancellationToken cancellationToken)
   at PropertyManagementPlatform.Web.WeiXin.WeixinController.Post(Int64 configId, String signature, String timestamp, String nonce, String openid, String encrypt_type, String msg_signature) in D:\项目\公司\property-management-platform-`

其他问题就是：关键字回复事件返回空数据
![image](https://user-images.githubusercontent.com/5319255/170439072-f2142c7a-c7e0-47e5-8ce0-b6c824332084.png)

##### 重现问题步骤（如果可以）
![image](https://user-images.githubusercontent.com/5319255/170438310-dbd200a7-ae2f-40fd-9e74-9adec0f33636.png)
![image](https://user-images.githubusercontent.com/5319255/170438354-796c4b9b-e05f-464f-a7f0-8a111dd1d3f1.png)

POST代码：
![image](https://user-images.githubusercontent.com/5319255/170438774-80ae4a80-6422-4398-9639-73d8e7a9ff3c.png)

![image](https://user-images.githubusercontent.com/5319255/170438558-2b4e38e9-a55d-499e-8bb8-0b123a5ff63b.png)

##### 发现问题的模块

- [ √] Senparc.Weixin 版本：6.15.1
- [ √] Senparc.Weixin.MP 版本：16.18.2.1
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] Senparc.Weixin.Tenpay 版本：
- [ ] Senparc.WebSocket 版本：
- [ √ ] 其他模块：Senparc.CO2NET 2.1.0

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5+
- [ ] .net standard 2.0 / 2.1
- [ ] .net core 1.x
- [ ] .net core 2.x
- [ ] .net core 3.x
- [x] .net 5.x / 6.x

##### 开发环境

- [ ] Visual Studio 2019
- [x] Visual Studio 2022
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [x] Windows，版本：
- [ ] Linux，版本：
- [ ] Mac，版本：
- [ ] 其他：

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by imgd** [comment]
配置文件没有配置，均采用默认配置，公众号配置实时读取缓存

**Comment by imgd** [comment]
配置文件没有配置，均采用默认配置，公众号配置实时读取缓存

**Comment by imgd** [comment]
accesstoken 我自己做集中管理

**Comment by JeffreySu** [comment]
有几个可能的原因：
1、没有按照 Sample 的完整流程完成注册（如果传入 AppId 调用高级接口，仍然需要进行账号 AppId+Secret 进行注册）
2、C:\inetpub\wwwroot\PMP_API_WeiXin\App_Data\NeuChar 这个目录没有访问权限，但是被用到了，例如开启了 APM。

**Comment by imgd** [comment]
> 有几个可能的原因： 1、没有按照 Sample 的完整流程完成注册（如果传入 AppId 调用高级接口，仍然需要进行账号 AppId+Secret 进行注册） 2、C:\inetpub\wwwroot\PMP_API_WeiXin\App_Data\NeuChar 这个目录没有访问权限，但是被用到了，例如开启了 APM。

1.没办法做到启动注册，我的配置都是动态的，另外不知道调用某些接口，例如发送模板消息需要用到accesstoken或appid，我传入的是accesstoken 不知道有没有隐形缺陷
2.我不知道这个写需要什么权限，iis我给了最高权限依然不行

**Comment by imgd** [comment]
另外我关闭APM,依然一样的错
![image](https://user-images.githubusercontent.com/5319255/170606161-09a449df-9aac-46fe-b0bb-ad7028b78eb3.png)

**Comment by imgd** [comment]
我现在用到的都是一些非高级功能，授权，获取用户信息，菜单管理，事件消息转发，发送模板 订阅消息这些

**Comment by imgd** [comment]
解决了，谢谢

**Comment by imgd** [comment]
1.权限问题为iis系统目录胡问题
2.返回消息之前为统一包装导致最终输出格式不一致
