### ISSUE TITLE
BuildRandomStr的str.Insert(0, "0");

### ISSUE THREAD

**Issue by zjfsdnu** [JeffreySu/WeiXinMPSDK#265]
BuildRandomStr的str.Insert(0, "0");应改为str = str.Insert(0, "0");
http://stackoverflow.com/questions/1381634/string-insert-in-c-sharp-doesnt-overwrite-does-it

**Comment by JeffreySu** [comment]
是的，官方提供的这个方法确实有问题！已经更新到https://github.com/JeffreySu/WeiXinMPSDK/commit/c330c2bf01ea5f19c1eb80b9c6077ebc3fd7db0b

非常感谢！
