### ISSUE TITLE
最新的企业转账到零钱没有接口

### ISSUE THREAD

**Issue by y1024866464** [JeffreySu/WeiXinMPSDK#2652]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
微信接口变更了，取消【企业付款到零钱】，新增【企业转账到零钱】

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 微信官方文档 URL

https://pay.weixin.qq.com/wiki/doc/apiv3/apis/chapter4_3_1.shtml
##### 微信官方文档快照（直接复制关键内容到下方）
https://pay.weixin.qq.com/wiki/doc/apiv3/apis/chapter4_3_1.shtml

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] Senparc.Weixin.Tenpay 版本：
- [ ] Senparc.WebSocket 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5+
- [ ] .net standard 2.0 / 2.1
- [ ] .net core 1.x
- [ ] .net core 2.x
- [ ] .net core 3.x
- [x] .net 5.x / 6.x

##### 开发环境

- [ ] Visual Studio 2019
- [x] Visual Studio 2022
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [x] Windows，版本：
- [ ] Linux，版本：
- [ ] Mac，版本：
- [ ] 其他：

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by zhangliang2008** [comment]
同求 @JeffreySu

**Comment by y1024866464** [comment]
微信6月刚出的接口，【付款到零钱】接口没了，出新接口【企业转账到零钱】，尼玛微信天天搞事情，又不发公告，又没客服。json格式传递数据，而且需要把证书字符串添加到请求头里面，跟以前完全不同。

**Comment by JeffreySu** [comment]
是的，目前 TenPayV3.dll 已经使用了最新的接口方式，此接口已经在加急日程中。

**Comment by JeffreySu** [comment]
@y1024866464 已经发布 TenPayV3 v0.6.3-beta1，欢迎测试并反馈。
beta版本之后，其他接口将会陆续添加。非常感谢！

**Comment by zhangliang2008** [comment]
> @y1024866464 @zhangliang2008 已经发布 TenPayV3 v0.6.3-beta1，欢迎测试并反馈。 beta版本之后，其他接口将会陆续添加。非常感谢！

新版本已测试，无法转账报{"code":"PARAM_ERROR","message":"HTTP header缺少微信支付平台证书序列号(Wechatpay-Serial)"}

**Comment by zhangliang2008** [comment]
我修改源码加上Wechatpay-Serial头后，返回{"code":"PARAM_ERROR","message":"请确认待处理的消息是否为加密后的密文"}
` /// <summary>
        /// 重写 SendAsync 方法
        /// </summary>
        /// <param name="request"></param>
        /// <param name="cancellationToken"></param>
        /// <returns></returns>
        protected async override Task<HttpResponseMessage> SendAsync(
            HttpRequestMessage request,
            CancellationToken cancellationToken)
        {
            var auth = await BuildAuthAsync(request);
            string value = $"WECHATPAY2-SHA256-RSA2048 {auth}";
            request.Headers.Add("Authorization", value);
            request.Headers.Add("Wechatpay-Serial", _tenpayV3Setting.TenPayV3_SerialNumber);
            return await base.SendAsync(request, cancellationToken);
        }`

**Comment by JeffreySu** [comment]
> 我修改源码加上Wechatpay-Serial头后，返回{"code":"PARAM_ERROR","message":"请确认待处理的消息是否为加密后的密文"} ` ` ///
> 
> 
> /// 重写 SendAsync 方法
> ///
> 
> ///
> ///
> ///
> protected async override Task SendAsync(
> HttpRequestMessage request,
> CancellationToken cancellationToken)
> {
> var auth = await BuildAuthAsync(request);
> string value = $"WECHATPAY2-SHA256-RSA2048 {auth}";
> request.Headers.Add("Authorization", value);
> request.Headers.Add("Wechatpay-Serial", _tenpayV3Setting.TenPayV3_SerialNumber);
> return await base.SendAsync(request, cancellationToken);
> }

我们下一个版本会开放这个头的修改，新的这个错误是否是因为没有加密？Serial是需要加密的

**Comment by zhangliang2008** [comment]
> > 我修改源加上微信支付-串口头后，返回{"code":"PARAM_ERROR","message":"请确认待处理的消息是否为加密后的密文"} ` `///
> > /// 对象 SendAsync 方法
> > //
> > /// 
> > /// 
> > /// 
> > protected async override Task SendAsync( 
> > HttpRequestMessage request, 
> > CancellationToken cancelToken) 
> > { 
> > var auth = await BuildAuthAsync(request); 
> > 字符串值 = $"WECHATPAY2-SHA256-RSA2048 {auth}"; 
> > request.Headers.Add("授权", value); 
> > request.Headers.Add("Wechatpay-Serial", _tenpayV3Setting.TenPayV3_SerialNumber); 
> > return await base.SendAsync(request, cancelToken); 
> > }
> 
> 我们下一个版本会打开这个头的修改，新的这个错误是否是因为没有加密？序列号是需要加密的

是的经测试是姓名没加密。
