### ISSUE TITLE
TenPayV3 平台证书获取逻辑错误

### ISSUE THREAD

**Issue by hitsjt** [JeffreySu/WeiXinMPSDK#2663]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
![image](https://user-images.githubusercontent.com/2417781/177495581-10d423ab-838c-4ed3-bb57-3be339626624.png)

这里publicKeys在为空时，会向微信更新，
但当publicKeys不为空时，不会再得到更新。

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [x] Senparc.Weixin.Tenpay 版本：v3
- [ ] Senparc.WebSocket 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5+
- [ ] .net standard 2.0 / 2.1
- [ ] .net core 1.x
- [ ] .net core 2.x
- [ ] .net core 3.x
- [x] .net 5.x / 6.x

##### 开发环境

- [ ] Visual Studio 2019
- [x] Visual Studio 2022
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [x] Windows，版本：
- [ ] Linux，版本：
- [ ] Mac，版本：
- [ ] 其他：

##### 联系方式
Email：hitsjt@gmail.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by hitsjt** [comment]
> 这是一个私有变量，如果获取到了，本次使用过程中获取一次之后，本身就不需要更新吧？
可以看到Data是一个静态变量
![image](https://user-images.githubusercontent.com/2417781/177906627-ea60f6a2-75f3-4ca1-a9d7-0256d3efe87c.png)

![image](https://user-images.githubusercontent.com/2417781/177906555-401b6c84-aeab-44bc-a7b3-28c160541931.png)

这里TenPayV3Info每次都会新建一个对象么？
如果不是每次新建一个，那就会有问题了
![image](https://user-images.githubusercontent.com/2417781/177906782-aaf530cf-7f04-4612-a428-a9b31bd9f4dd.png)

**Comment by JeffreySu** [comment]
这里不会，也不需要，因为是一个字典，里面对每一个账号都有一个独立的 TenPayV3Info。你说的问题，只要publicKeys是private，每个实例里面的都是不同的。

**Comment by JeffreySu** [comment]
> > 这是一个私有变量，如果获取到了，本次使用过程中获取一次之后，本身就不需要更新吧？
> > 可以看到Data是一个静态变量
> > ![image](https://user-images.githubusercontent.com/2417781/177906627-ea60f6a2-75f3-4ca1-a9d7-0256d3efe87c.png)
> 
> ![image](https://user-images.githubusercontent.com/2417781/177906555-401b6c84-aeab-44bc-a7b3-28c160541931.png)
> 
> 这里TenPayV3Info每次都会新建一个对象么？ 如果不是每次新建一个，那就会有问题了 ![image](https://user-images.githubusercontent.com/2417781/177906782-aaf530cf-7f04-4612-a428-a9b31bd9f4dd.png)

这里不会，也不需要，因为是一个字典，里面对每一个账号都有一个独立的 TenPayV3Info。你说的问题，只要publicKeys是private，每个实例里面的都是不同的。

**Comment by hitsjt** [comment]
> > > 这是一个私有变量，如果获取到了，本次使用过程中获取一次之后，本身就不需要更新吧？
> > > 可以看到Data是一个静态变量
> > > ![image](https://user-images.githubusercontent.com/2417781/177906627-ea60f6a2-75f3-4ca1-a9d7-0256d3efe87c.png)
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/2417781/177906555-401b6c84-aeab-44bc-a7b3-28c160541931.png)
> > 这里TenPayV3Info每次都会新建一个对象么？ 如果不是每次新建一个，那就会有问题了 ![image](https://user-images.githubusercontent.com/2417781/177906782-aaf530cf-7f04-4612-a428-a9b31bd9f4dd.png)
> 
> 这里不会，也不需要，因为是一个字典，里面对每一个账号都有一个独立的 TenPayV3Info。你说的问题，只要publicKeys是private，每个实例里面的都是不同的。

会出现这个问题，如果腾讯更新了新的公钥，那就永远不会更新了。

**Comment by JeffreySu** [comment]
腾讯更新公钥，有两种方式，一种是通过重启的机会更新，另外可以直接通过调用 `await basePayApis.GetPublicKeysAsync()` 来手动强制更新。
