### ISSUE TITLE
企业微信成员更新requestMessage.Encrypt需要再次解密吗？

### ISSUE THREAD

**Issue by bocblca** [JeffreySu/WeiXinMPSDK#2666]
企业微信成员更新回调事件：OnEvent_ChangeContactUpdateUserRequest(RequestMessageEvent_Change_Contact_User_Update requestMessage)
requestMessage.Encrypt需要手工解密吗？还是有内置的已经解密好的数据？
感谢各位大佬！！！

**Comment by JeffreySu** [comment]
不需要，自动解密，直接在对应事件中获取 requestMessage 中的值即可。

**Comment by bocblca** [comment]
感谢大佬回复，应该是另一个帖子的问题，缺少ADDRESS字段，此贴关闭。
