### ISSUE TITLE
微信退款能不能支持热更新，别再用配置文件了大哥

### ISSUE THREAD

**Issue by znyet** [JeffreySu/WeiXinMPSDK#2669]
我有N个公众号和，N个商户号
退款的时候能不能让我动态传入指定商户，而不是在配置文件写死
程序启动，并不想配置任何公众号和商户号，而是根据用户我自己去数据库读取

**Comment by bocblca** [comment]
据我的经验，配置文件本来就可以和数据库联动的啊，配置文件可以选择配置文件优先还是数据库存储的配置优先.网上类似的文章也很多。你也完全可以在配置公众号的时候动态读取数据库配置。这个不是WeiXinMPSDK的问题，我觉得是使用方法的问题。

**Comment by znyet** [comment]
所谓的热更新，是指在程序运行过程中，在不停机的状态下，
对所有公众号商户号信息进行，增、删、改、查。

而不是在程序启动的时候只读取一次配置文件，或者只读取一次数据库，下次增加公众号和商户号怎么办？
或者修改了公众号和商户号信息怎么办？
停机重启程序？重新配置吗？这是极其不合理的

配置和依赖注入明显就是乱设计，写死了，限制了发挥空间

**Comment by bocblca** [comment]
配置文件和依赖注入不是什么缺点吧？这个senparc weixinSDK是可以一次注册多个微信公众号的，不同的订单对应不同的公众号，完全可以通过订单标识进行区分，在订单前面加上标识前缀，不就可以区分不同的公众号商户了吗？办法总比困难多嘛:) 
ps：在使用订单之前公众号商户号肯定注册好了吧？不会先有订单后有公众号商户号吧？所以说这不是问题。

**Comment by JeffreySu** [comment]
@[znyet](https://github.com/znyet) 你可以在任何需要使用的地方进行注册，并且TenPavV3（ApiV3）的证书也不像之前一样必须启动的时候注册（.NET Core的设计），现在你说的问题应该是不存在了。

> 据我的经验，配置文件本来就可以和数据库联动的啊，配置文件可以选择配置文件优先还是数据库存储的配置优先.网上类似的文章也很多。你也完全可以在配置公众号的时候动态读取数据库配置。这个不是WeiXinMPSDK的问题，我觉得是使用方法的问题。

这个理解是对的。

**Comment by znyet** [comment]
能不能给一个demo
你们给的那些sample都是在配置文件。
比如我应该调用哪个静态类的方法
传入什么进行注册，修改，删除等等

**Comment by JeffreySu** [comment]
就是全局注册里面执行的代码，比如：

```
TenPayV3InfoCollection.Register(=> new TenPayV3Info(weixinSetting), name);
```

任意地方，只要你在调用接口之前执行都可以。
