### ISSUE TITLE
net core 分之下 , SDK生成失败 ,提示 没有 helper.JsonSetting***** 这个文件

### ISSUE THREAD

**Issue by China-Sunwei** [JeffreySu/WeiXinMPSDK#267]

**Comment by JeffreySu** [comment]
我这边是通过的，刚才整理了几个文件（但不是你说的这个），你再看一下还有没有问题？

**Comment by lishewen** [comment]
.net core没有这个文件才是正确的 这个当时已经被我移除了，因为.Net Core 的 JSON 序列化是用Newtonsoft.Json，而 senparc.weixin.helpers.JsonSetting 这个类是.Net Framework自带的序列化的补充实现，在.net core中没用

移除后并不会影响编译，请你检查下你所下载的项目是否为.net core项目

**Comment by China-Sunwei** [comment]
@lishewen  现在好了. 17号的时候 我pull代码 .  core版本的CustomField 这个类上还有[JsonSetting] .编译无法通过.今天我重新Clone了一下代码 .发现没有那个[Jsonsetting],并且可以编译通过了~ 谢谢~
