### ISSUE TITLE
升级到新版本，老版本写法怎么弃用了。

### ISSUE THREAD

**Issue by bbhxwl** [JeffreySu/WeiXinMPSDK#2670]
不知道现在是什么写法了。
![image](https://user-images.githubusercontent.com/26525599/178641443-f9cf5637-671f-425d-aa70-14d30dc61e21.png)

**Comment by JeffreySu** [comment]
因为不知道您是从什么版本升级到什么版本，如果是比较老的，建议这么做：
1、参考一下最新的Demo，看一下参数有没有区别
2、参考一下最新的Demo，看一下启动文件的using，是否有缺。我们有一个时间点开始，添加了 Senparc.Weixin.AspNet 这个库。
