### ISSUE TITLE
缺少"查询小程序版本信息"接口

### ISSUE THREAD

**Issue by jhzou1** [JeffreySu/WeiXinMPSDK#2671]
缺少"查询小程序版本信息"接口

[https://developers.weixin.qq.com/doc/oplatform/openApi/OpenApiDoc/miniprogram-management/code-management/getVersionInfo.html](https://gitee.com/link?target=https%3A%2F%2Fdevelopers.weixin.qq.com%2Fdoc%2Foplatform%2FopenApi%2FOpenApiDoc%2Fminiprogram-management%2Fcode-management%2FgetVersionInfo.html)

**Comment by JeffreySu** [comment]
@jhzou1 已发布，感谢！
