### ISSUE TITLE
RedPackApi发送红包时报找不到文件

### ISSUE THREAD

**Issue by hiseab** [JeffreySu/WeiXinMPSDK#268]
把:X509Certificate cer = new X509Certificate(cert, password);换成
X509Certificate2 cer = new X509Certificate2(cert, password, X509KeyStorageFlags.PersistKeySet | X509KeyStorageFlags.MachineKeySet);就好了

**Comment by JeffreySu** [comment]
最开始是这样的，后来注释掉了，应该是有原因的，我们看一下。感谢反馈！

**Comment by JeffreySu** [comment]
已经在v14.3.104中更正，谢谢！https://github.com/JeffreySu/WeiXinMPSDK/releases/tag/v14.3.104
