### ISSUE TITLE
Senparc.Weixin.Work.AdvancedAPIs.MediaApi.UploadAsync  上传中文文件名为乱码。

### ISSUE THREAD

**Issue by chinasqzl** [JeffreySu/WeiXinMPSDK#2682]
企业微信上传临时素材，上传的文件名为乱码。

**Comment by JeffreySu** [comment]
最新的版本应该已经解决这个问题了，您更新到最新版本看一下。如果还有问题的话麻烦提供一下所有的执行代码和参数。

**Comment by chinasqzl** [comment]
已更新为最新的3.14.10，问题依旧，字母命名正常。
代码：
await MediaApi.UploadAsync(token.access_token, Senparc.Weixin.Work.UploadMediaFileType.file, value);
value: 考勤.xlxs

上传结果：
![image](https://user-images.githubusercontent.com/16968103/182761772-08860944-902b-4778-bc35-56a95143d727.png)

**Comment by JeffreySu** [comment]
你可以在最新源码里面跑一下这个单元测试：
https://github.com/JeffreySu/WeiXinMPSDK/blob/aedac05c8179baefce4a7329f98ec4cac6bd26c9/src/Senparc.Weixin.Work/Senparc.Weixin.Work.Test/AdvancedAPIs/Media/MediaTest.cs#L114-L114

![image](https://user-images.githubusercontent.com/2281927/182769642-3b8a4fe9-fbdc-4c08-a4b4-dc30ff7bd5b0.png)

**Comment by chinasqzl** [comment]
我升级到预览版3.15.6，可以了，谢谢。
