### ISSUE TITLE
企业付款证书相关问题

### ISSUE THREAD

**Issue by LuceLuo** [JeffreySu/WeiXinMPSDK#269]
在提交企业转账数据的时候是需要证书的，但是没有提供相关参数。
默认的p12证书需要到服务器上安装，还可能涉及到权限问题，是否可以参数别的语言使用其他类型的证书文件，这样只要放到服务器目录上就可以了

**Comment by JeffreySu** [comment]
已经确认类似的问题，正在等待开发者PR

**Comment by JeffreySu** [comment]
@LuceLuo 长时间观察下来似乎没有这个必要，先关闭了。
