### ISSUE TITLE
Deploy to Azure 按钮失效

### ISSUE THREAD

**Issue by Jeff-Tian** [JeffreySu/WeiXinMPSDK#2699]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述

<img width="1290" alt="image" src="https://user-images.githubusercontent.com/3367820/185101855-06d313dc-6938-46b4-bde5-36760d785ea9.png">

##### 重现问题步骤（如果可以）

1. 参考这个文档： https://github.com/JeffreySu/WeiXinMPSDK/wiki/%E5%B0%86%E5%BE%AE%E4%BF%A1%E7%AB%99%E7%82%B9%E9%83%A8%E7%BD%B2%E5%88%B0-Azure-%E4%B8%AD
2. 点击 Deploy to Azure 按钮

**Comment by JeffreySu** [comment]
@Jeff-Tian 是的，已经不适用了，非常感谢提醒！Azure的部署目前已经可以直接用 Visual Studio 的“发布”功能完成。
