### ISSUE TITLE
消息中间件中的messagehandler中能否实现服务类的依赖注入？

### ISSUE THREAD

**Issue by bocblca** [JeffreySu/WeiXinMPSDK#2707]
类似这样的messagehandler中 中能否实现服务类的依赖注入？
public class WorkCustomMessageHandler : WorkMessageHandler<WorkCustomMessageContext>
    {
        /// <summary>
        /// 为中间件提供生成当前类的委托
        /// </summary>
        public static Func<Stream, PostModel, int, IServiceProvider, WorkCustomMessageHandler> GenerateMessageHandler =
            (stream, postModel, maxRecordCount, serviceProvider) => new WorkCustomMessageHandler(stream, postModel, maxRecordCount, serviceProvider);

        readonly ISenparcWeixinSettingForWork _workSetting;
          

        public WorkCustomMessageHandler(Stream inputStream, PostModel postModel, int maxRecordCount = 0, IServiceProvider? serviceProvider = null)
            : base(inputStream, postModel, maxRecordCount, serviceProvider: serviceProvider)
        {
            _workSetting = Config.SenparcWeixinSetting.WorkSetting;
           
        }
..........................

能否实现这样的依赖注入：
readonly  Sqldata sqldata;
 public WorkCustomMessageHandler(Sqldata sqldata)
{
  this.sqldata=slqdata
}

##### 发现问题的模块

- [ ] Senparc.Weixin.Work 版本：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5+
- [ ] .net standard 2.0 / 2.1
- [ ] .net core 1.x
- [ ] .net core 2.x
- [ ] .net core 3.x
- [x] .net 5.x / 6.x

##### 开发环境

- [ ] Visual Studio 2019
- [x] Visual Studio 2022
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [x] Windows，版本：
- [ ] Linux，版本：
- [ ] Mac，版本：
- [ ] 其他：

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
没有问题，都可以。

**Comment by bocblca** [comment]
谢谢，是的，通过IServiceProvider可以注入
