### ISSUE TITLE
企业微信缺少上下游及互联企业相关接口

### ISSUE THREAD

**Issue by tiansfather** [JeffreySu/WeiXinMPSDK#2725]
企业微信缺少上下游及互联企业相关接口

##### 微信官方文档 URL
https://developer.work.weixin.qq.com/document/path/95813

##### 微信官方文档快照（直接复制关键内容到下方）
获取互联企业部门成员详情
最后更新：2022/06/22
请求方式： POST（HTTPS）
请求地址： https://qyapi.weixin.qq.com/cgi-bin/linkedcorp/user/list?access_token=ACCESS_TOKEN

##### 发现问题的模块

- [x ] Senparc.Weixin.Work 版本：

##### 模块对应的 .net 版本
- [x] .net 5.x / 6.x

##### 开发环境

- [x] Visual Studio 2022

**Comment by mojinxun** [comment]
@mojinxun @SenparcHai @tiansfather
