### ISSUE TITLE
HttpUtility/Post.cs中JavaScriptSerializer的MaxJsonLength没有设置 

### ISSUE THREAD

**Issue by ZachShine** [JeffreySu/WeiXinMPSDK#273]
HttpUtility/Post.cs中JavaScriptSerializer的MaxJsonLength没有设置

**Comment by JeffreySu** [comment]
目前还不明确微信那边的的最大Json长度（尤其是很多字段是用户自己设置的），所以这个目前还没有办法设置死，你需要设置这个是出于什么原因？

**Comment by ZachShine** [comment]
谢谢, 回复挺快的。

我看HttpUtility/Get.cs是设置为int.Max(int64.max?)的啊. 这个怎么没设置呢？
批量读取图文的时候(N个图文消息且比较大)就报异常了
JavaScriptSerializer. The length of the string exceeds the value set on the maxJsonLength property..

**Comment by JeffreySu** [comment]
好的，我们目前还没碰到这样的情况，所以没有什么感触，既然已经有这个需求下个版本我们会改进一下。非常感谢！
如果你有已经写好的代码也欢迎Pull Request过来。
