### ISSUE TITLE
解密ShareInfo时AES的KeySize应为256

### ISSUE THREAD

**Issue by kchanlee** [JeffreySu/WeiXinMPSDK#2738]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
解密ShareInfo时AES的KeySize应为256

##### 重现问题步骤（如果可以）

1. 小程序端通过如下方法获得ShareInfo
```
      wx.showShareMenu({
        withShareTicket: true
      })
  
      const options = wx.getLaunchOptionsSync()
  
      if (options.shareTicket) {
        wx.getShareInfo({
          shareTicket: options.shareTicket
          success: (shareInfo) {
            ...
          }
        })
      }
```
2. 将shareInfo发到后端，通过以下方式解密，得到乱码
```
EncryptHelper.DecodeEncryptedData(loginResult.session_key, shareInfo.encryptedData, shareInfo.iv);
```

##### 解决办法
将`Senparc.Weixin.WxOpen.Helpers.EncryptHelper.AES_Decrypt`中`aes.KeySize`设置为256可解决。

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [x] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] Senparc.Weixin.Tenpay 版本：
- [ ] Senparc.WebSocket 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5+
- [ ] .net standard 2.0 / 2.1
- [ ] .net core 1.x
- [ ] .net core 2.x
- [ ] .net core 3.x
- [x] .net 5.x / 6.x

##### 开发环境

- [ ] Visual Studio 2019
- [x] Visual Studio 2022
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [x] Windows，版本：
- [ ] Linux，版本：
- [ ] Mac，版本：
- [ ] 其他：

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
https://github.com/JeffreySu/WeiXinMPSDK/blob/e3c375a0f3d7269982f29e96add1c8b6c3bc90d5/src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/Helpers/EncryptHelper.cs#L133-L133

这里原始的就是256，但是使用256也会有别的问题，使用128暂时没发现问题，是否方便提供一下解密的数据，我这边测试一下？zsu@senparc.com

**Comment by JeffreySu** [comment]
@kchanlee 先发布了一个 beta 版本，您可以试一下。提供了一个 keySize 的可选参数。

**Comment by JeffreySu** [comment]
@kchanlee  没有新的反馈就先关闭了，谢谢。
