### ISSUE TITLE
.net 7 ASP.netMVC Program.cs 这个错误有人遇到吗

### ISSUE THREAD

**Issue by sipo1209** [JeffreySu/WeiXinMPSDK#2750]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
using MAHAKALA.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.FileProviders;
using xweb;
using Senparc.Weixin;
using Senparc.Weixin.Work; 
using Senparc.Weixin.RegisterServices; 
using Senparc.Weixin.AspNet;
using Senparc.Weixin.Cache.Redis;
using MAHAKALA.Helper;
using MAHAKALA;
using WebDemo.Services;
using Microsoft.AspNetCore.Server.Kestrel.Core;
using OpenCCNET;

var builder = WebApplication.CreateBuilder(args);

#if DEBUG
builder.WebHost.UseUrls("http://*:5000");
builder.WebHost.ConfigureKestrel(options => options.ListenAnyIP(5000));
#else
builder.WebHost.UseUrls(args);
#endif

builder.Services.AddControllersWithViews();
builder.Services.AddHttpContextAccessor();
builder.Services.AddTransient<ICaptchaService, ClickableCaptchaService>();
builder.Services.AddEntityFrameworkMySql();
builder.Services.AddEntityFrameworkMySqlJsonNewtonsoft();
builder.Services.AddSingleton<IPathProvider, PathProvider>();
builder.Services.Configure<KestrelServerOptions>(options =>
{
    options.AllowSynchronousIO = true;
    options.Limits.MinRequestBodyDataRate =
            new MinDataRate(bytesPerSecond: 100, gracePeriod: TimeSpan.FromSeconds(10));
});

builder.Services.AddMemoryCache();
builder.Services.AddSenparcWeixinServices(builder.Configuration);  **在这句话抛出错误，object null找不到引用什么的。**

var app = builder.Build();

##### 重现问题步骤（如果可以）

1. 安装.net 7
2.安装nuget最新版6.15.8.1（回退到6.15.7就没事了）
3. 就能看到

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] Senparc.Weixin.Tenpay 版本：
- [ ] Senparc.WebSocket 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5+
- [ ] .net standard 2.0 / 2.1
- [ ] .net core 1.x
- [ ] .net core 2.x
- [ ] .net core 3.x
- [x] .net 5.x / 6.x

##### 开发环境

- [ ] Visual Studio 2019
- [x] Visual Studio 2022
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [x] Windows，版本：
- [ ] Linux，版本：
- [ ] Mac，版本：
- [ ] 其他：

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by hxqz** [comment]
.net6同问题，同回退解决

**Comment by JeffreySu** [comment]
是不是装了 .NET SDK7.0.101？需要退回到 7.0.100

https://github.com/JeffreySu/WeiXinMPSDK/issues/2742

**Comment by adaxiong** [comment]
我也报错了，因为我是用v3,
就直接弄成
 services.AddSenparcWeixinServices(configuration,delegate {});
就可以了，不用证书，不用退回 7.0.100

**Comment by JeffreySu** [comment]
新版本已经发布，排除了 null 的情况（正常情况不应该为 null，可能是 appsettings.json 中没有提供可能会发生）。现在起可以忽略这个问题。
