### ISSUE TITLE
开放平台中，获取授权方的选项设置信息的BUG

### ISSUE THREAD

**Issue by bingohanet** [JeffreySu/WeiXinMPSDK#276]
在ComponentApi.GetAuthorizerOption的方法中，需要传入OptionName的枚举类型参数，在CommonJsonSend.Send方法中，枚举类型参数会被JavaScriptSerializer序列化为int类型，并非API中所需要的字符串。
原代码：
var data = new
{
    component_appid = componentAppId,
    authorizer_appid = authorizerAppId,
    option_name = optionName
};
修改如下后通过：
var data = new
{
    component_appid = componentAppId,
    authorizer_appid = authorizerAppId,
    option_name = optionName.ToString()
};

**Comment by JeffreySu** [comment]
OK，我们会在下个版本中发布，感谢！

**Comment by JeffreySu** [comment]
已经在v2.3.2中更正：https://github.com/JeffreySu/WeiXinMPSDK/commit/feb2d3bb5a7afa2aafbbd055affe2ee85e6592af
