### ISSUE TITLE
新增永久视频素材后通过接口获取视频description字段为空

### ISSUE THREAD

**Issue by wtujvk** [JeffreySu/WeiXinMPSDK#2764]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
上传永久视频素材后，通过media_id获取视频素材（title、description都有值），title、down_url是有值的， 但description为空。
使用的测试号。

##### 重现问题步骤（如果可以）

1. 上传永久视频素材
    var uploadVideoResult = MediaApi.UploadForeverVideo(accessTokenOrAppId, videoFilePath, videoTitle, introduction);
2. 获取视频素材
  var videoResult = MediaApi.GetForeverVideo(accessTokenOrAppId, uploadVideoResult.media_id);

示例参数：
var videoTitle= "用户体验就是用户在使用一个或者多个产品或者服务的整个过程的感受用户体验就是用户在使用一个或者多个产品或者服务的整个过程的感受";
            var introduction = "大家都知道一个好的标题可以有效的吸引读者点击公众号文章，增加文章的点击率和曝光度，下面我们跟随拓途数据一起来了解一下微信公众号标题长度的相关资料吧微信公众号标题长度多少字合适？官方规定的是不能超过64个，但是因为手机显示问题，第一篇文章最好不要超过15个字，不然没办法全部显示。后面的文章无所谓，但是也不要太长。标题嘛，越精炼越好。微信公众号图文消息标题很重要，一个好的标题是成功的一半，标题也有用户体验度，如订阅号在订阅号文件夹中，打开之后能够显示的字数是有限的，因此我们的标题应尽可能让我们在订阅号可见范围内看明白其意思，微信公众号标题字数要尽量控制在约15个字，如果超过就会换行，把文章内容给遮挡住，两行就已经够了，如果是三行，那就酸爽了，你可以感受下。官方规定的是不能超过64个，但是因为手机显示问题，第一篇文章最好不要超过15个字，不然没办法全部显示。后面的文章无所谓，但是也不要太长。标题嘛，越精炼越好。微信公众号图文消息标题很重要，一个好的标题是成功的一半，标题也有用户体验度，如订阅号在订阅号文件夹中，打开之后能够显示的字数是有限的，因此我们的标题应尽可能让我们在订阅号可见范围内看明白其意思，微信公众号标题字数要尽量控制在约15个字，如果超过就会换行，把文章内容给遮挡住，两行就已经够了，如果是三行，那就酸爽了，你可以感受下。官方规定的是不能超过64个，但是因为手机显示问题，第一篇文章最好不要超过15个字，不然没办法全部显示。后面的文章无所谓，但是也不要太长。标题嘛，越精炼越好。微信公众号图文消息标题很重要，一个好的标题是成功的一半，标题也有用户体验度，如订阅号在订阅号文件夹中，打开之后能够显示的字数是有限的，因此我们的标题应尽可能让我们在订阅号可见范围内看明白其意思，微信公众号标题字数要尽量控制在约15个字，如果超过就会换行，把文章内容给遮挡住，两行就已经够了，如果是三行，那就酸爽了，你可以感受下。官方规定的是不能超过64个，但是因为手机显示问题，第一篇文章最好不要超过15个字，不然没办法全部显示。后面的文章无所谓，但是也不要太长。标题嘛，越精炼越好。微信公众号图文消息标题很重要，一个好的标题是成功的一半，标题也有用户体验度，如订阅号在订阅号文件夹中，打开之后能够显示的字数是有限的，因此我们的标题应尽可能让我们在订阅号可见范围内看明白其意思，微信公众号标题字数要。";

##### 微信官方文档快照（直接复制关键内容到下方）
![image](https://user-images.githubusercontent.com/17868266/211763686-4dc0afa7-39ce-4419-ab39-a8ba1d19cc4b.png)

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [x] Senparc.Weixin.MP 版本：16.18.9
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] Senparc.Weixin.Tenpay 版本：
- [ ] Senparc.WebSocket 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5+
- [ ] .net standard 2.0 / 2.1
- [ ] .net core 1.x
- [ ] .net core 2.x
- [ ] .net core 3.x
- [x] .net 5.x / 6.x

##### 开发环境

- [ ] Visual Studio 2019
- [x] Visual Studio 2022
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [x] Windows，版本：
- [ ] Linux，版本：
- [ ] Mac，版本：
- [ ] 其他：

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by mojinxun** [comment]
@wtujvk @mojinxun @Senparc21

**Comment by mojinxun** [comment]
@wtujvk @mojinxun

**Comment by mojinxun** [comment]
新增永久素材这个接口上传的视频素材，微信那边不审核，没法使用，基本上可以认为这个接口无用了。
只能在公众号后台手动上传，然后通过获取素材列表拉取到数据后使用，
MediaApi.GetOthersMediaList
MediaApi.GetForeverVideo

**Comment by mojinxun** [comment]
https://developers.weixin.qq.com/community/minihome/doc/0000acea168dc82664ba9d86d52000

**Comment by SenparcHai** [comment]
测试

**Comment by mojinxun** [comment]
@SenparcHai
