### ISSUE TITLE
开放平台中，获取可用AuthorizerAccessToken的BUG

### ISSUE THREAD

**Issue by bingohanet** [JeffreySu/WeiXinMPSDK#277]
在AuthorizerContainer.TryGetAuthorizerAccessToken方法中，调用了GetAuthorizerInfoResult方法，而GetAuthorizerInfoResult方法所调用的ComponentApi.GetAuthorizerInfo获取到的authorization_info是空值，具体见方法注释：此方法返回的JSON中，authorization_info.authorizer_appid等几个参数通常为空（哪怕公众号有权限）。因此，读取到的authorization_info.authorizer_access_token也为空值。
原代码：
return GetAuthorizerInfoResult(componentAppId, authorizerAppid, getNewTicket).authorization_info.authorizer_access_token;
修改后测试通过：
GetAuthorizerInfoResult authorizerInfoResult = GetAuthorizerInfoResult(componentAppId, authorizerAppid, getNewTicket);
authorizerInfoResult.authorization_info = GetAuthorizationInfo(componentAppId, authorizerAppid, getNewTicket);
return authorizerInfoResult.authorization_info.authorizer_access_token;

**Comment by JeffreySu** [comment]
你的代码简化之后，实际上是：
```
            var authorization_info = GetAuthorizationInfo(componentAppId, authorizerAppid, getNewTicket);
            return authorization_info.authorizer_access_token;
```

是这个意思吧？

**Comment by JeffreySu** [comment]
@bingohanet ?

**Comment by bingohanet** [comment]
是的

**Comment by anley360106** [comment]
@JeffreySu 是的

**Comment by JeffreySu** [comment]
@bingohanet @anley360106  在 Open v2.3.4 版本中已经修正，请查看当前是否正确，谢谢！
