### ISSUE TITLE
对于腾讯api返回值 无数据（Http状态码为204）返回 RequestAsync 签名验证失败：Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by MrSummerFang** [JeffreySu/WeiXinMPSDK#2774]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
对于腾讯api返回值 无数据（Http状态码为204）处理有问题，
返回 RequestAsync 签名验证失败：Object reference not set to an instance of an object.
实际数据操作成功。 比如修改商家券基本信息等

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 微信官方文档 URL
https://pay.weixin.qq.com/wiki/doc/apiv3_partner/apis/chapter9_2_12.shtml

##### 微信官方文档快照（直接复制关键内容到下方）
返回示例
[正常示例](javascript:;)
无数据（Http状态码为204）

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [x] Senparc.Weixin.Tenpay 版本：
- [ ] Senparc.WebSocket 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5+
- [ ] .net standard 2.0 / 2.1
- [ ] .net core 1.x
- [ ] .net core 2.x
- [ ] .net core 3.x
- [x] .net 5.x / 6.x

##### 开发环境

- [ ] Visual Studio 2019
- [x] Visual Studio 2022
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [x] Windows，版本：
- [ ] Linux，版本：
- [ ] Mac，版本：
- [ ] 其他：

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
已经修复 #96539867e70c0e3e33bbaa602b5f0beed5cd52b7 非常感谢！

**Comment by MrSummerFang** [comment]
> 已经修复 [96539867e70c0e3e33bbaa602b5f0beed5cd52b7](https://github.com/JeffreySu/WeiXinMPSDK/pull/2775/commits/96539867e70c0e3e33bbaa602b5f0beed5cd52b7) 非常感谢！
> 
> @MrSummerFang @bbkingZ

"resultCode": {
            "success": false,
            "stateCode": null,
            "errorCode": null,
            "errorMessage": "Object reference not set to an instance of an object.",
            "solution": null,
            "additional": null
        }

还是有问题哦

**Comment by JeffreySu** [comment]
@MrSummerFang 已经再次修复发布新版本，非常感谢反馈！https://www.nuget.org/packages/Senparc.Weixin.TenPayV3/0.6.8.13
