### ISSUE TITLE
企业微信 服务商回调通知 消息类型缺少 重置永久授权码通知

### ISSUE THREAD

**Issue by One0627** [JeffreySu/WeiXinMPSDK#2785]
##### 问题描述
企业微信 服务商回调通知 消息类型缺少 重置永久授权码通知

##### 重现问题步骤（如果可以）

![image](https://user-images.githubusercontent.com/42073125/217472931-42146118-061c-4c95-bafd-c46c98f13369.png)
![image](https://user-images.githubusercontent.com/42073125/217473042-f54aab9e-5377-49b0-b525-9d633ee38ef2.png)

##### 微信官方文档 URL
https://developer.work.weixin.qq.com/document/path/97175

**Comment by JeffreySu** [comment]
@One0627  已发布到 Open v3.15.15，非常感谢！

**Comment by One0627** [comment]
感谢回应，但是并没有解决我的问题 
WorkMessageHandler.cs 中 OnThirdPartyEventAsync方法  siwtch case 中没有添加 RESET_PERMANENT_CODE  该事件虚方法

**Comment by One0627** [comment]
> 感谢回应，但是并没有解决我的问题 WorkMessageHandler.cs 中 OnThirdPartyEventAsync方法 siwtch case 中没有添加 RESET_PERMANENT_CODE 该事件虚方法

@JeffreySu
