### ISSUE TITLE
微信支付V3响应处理类缺少获取所有参数方法

### ISSUE THREAD

**Issue by huyou** [JeffreySu/WeiXinMPSDK#279]
在ResponseHandler.cs类中缺少'GetAllParameters()方法，获取响应的所有参数。还缺少IsWXsign()签名验证方法。

**Comment by JeffreySu** [comment]
哪个库下面？

**Comment by huyou** [comment]
.NET4.5

**Comment by JeffreySu** [comment]
是微信官方的提供的Demo相比少了还是你觉得需要加上去？

**Comment by huyou** [comment]
其实也没多大影响，用获取单个参数方法也可以使用的

**Comment by jianliulin** [comment]
IsWXsign()签名验证非常必要

**Comment by JeffreySu** [comment]
@jianliulin 你们说真的这个IsWXsign()是官方已经有提供代码Sample了，还是建议我们自己加上去的一个方法？目前我们是直接在代码里面验证的。

**Comment by JeffreySu** [comment]
@jianliulin @huyou 重新看了一下，你们说的 IsWxsign() 应该是 TenPayLib 下面已经有的，目前 TenPayLibV3 下面也是会有的，只是名字改了，叫：Senparc.Weixin.MP.TenPayLibV3.ResponseHandler.IsTenpaySign()
