### ISSUE TITLE
需要通过邮箱获取UserId

### ISSUE THREAD

**Issue by bonnlee2016** [JeffreySu/WeiXinMPSDK#2799]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 微信官方文档 URL
https://developer.work.weixin.qq.com/document/path/95892

##### 微信官方文档快照（直接复制关键内容到下方）
邮箱获取userid
最后更新：2022/07/19
通过邮箱获取其所对应的userid。

请求方式：POST（HTTPS）
请求地址：https://qyapi.weixin.qq.com/cgi-bin/user/get_userid_by_email?access_token=ACCESS_TOKEN

##### 发现问题的模块
Senparc.Weixin.Work

##### 模块对应的 .net 版本

- [x] .net standard 2.0 / 2.1
- [x] .net core 2.x
- [x] .net 5.x / 6.x

##### 开发环境

- [x] Visual Studio 2022

##### 缓存环境

- [x] 服务器内存缓存（默认）

##### 系统环境

- [x] Windows，版本：

##### 联系方式
Email：390391254@qq.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JaneConan** [comment]
@bonnlee2016 @SenparcHai  @JaneConan 正在处理

**Comment by JaneConan** [comment]
PR已提交 #2800

**Comment by JeffreySu** [comment]
已发布，非常感谢！
