### ISSUE TITLE
企业微信自建应用回调出现XML格式错误

### ISSUE THREAD

**Issue by bocblca** [JeffreySu/WeiXinMPSDK#2805]
##### 问题描述

在回调中读取不到：requestMessage.ApprovalInfo
  public override IWorkResponseMessageBase OnEvent_Open_Approval_Change_Status_ChangeRequest(RequestMessageEvent_OpenApprovalChange requestMessage)
        {
            try {
                Console.WriteLine("这是自建应用回调...");
                Console.WriteLine(requestMessage.AgentID);
                Console.WriteLine("这是自建应用回调...执行第一次");
                Console.WriteLine(requestMessage.CreateTime);
                Console.WriteLine("这是自建应用回调...执行第二次");
                if (requestMessage.ApprovalInfo != null)
                {
                    Console.WriteLine("approval不为空");
                    Console.WriteLine(requestMessage.ApprovalInfo.ToString());
                }
                else { 
                   Console.WriteLine("approval是空值");
                }
                
                Console.WriteLine("这是自建应用回调...执行第三次");
                Console.WriteLine(requestMessage.ApprovalInfo.OpenSpName);
                Console.WriteLine("这是自建应用回调...执行第四次");
            }catch (Exception ex) { 
                Console.WriteLine(ex.Message); 
            }
           
            return base.OnEvent_Open_Approval_Change_Status_ChangeRequest(requestMessage);
        }

requestMessage.AgentID 这个值是能读取到的但是approvalinfo是空值

经查日志，xml文件是有数据的：如下
##code
```xml
<xml>
  <ToUserName><![CDATA[wwa32481exxx]]></ToUserName>
  <FromUserName><![CDATA[sys]]></FromUserName>
  <CreateTime>1680354268</CreateTime>
  <MsgType><![CDATA[event]]></MsgType>
  <Event><![CDATA[open_approval_change]]></Event>
  <AgentID>1000014</AgentID>
  <ApprovalInfo>
    <ThirdNo><![CDATA[6401271680350012806]]></ThirdNo>
    <OpenSpName><![CDATA[督办通知单审批1]]></OpenSpName>
    <OpenTemplateId><![CDATA[25b9e830ed383c2713c13f5614757c7b_899122340]]></OpenTemplateId>
    <OpenSpStatus>2</OpenSpStatus>
    <ApplyTime>1680350036</ApplyTime>
    <ApplyUserName><![CDATA[赵xx]]></ApplyUserName>
    <ApplyUserId><![CDATA[640127]]></ApplyUserId>
    <ApplyUserParty><![CDATA[xx/xx/xxx]]></ApplyUserParty>
    <ApplyUserImage><![CDATA[https://rescdn.qqmail.com/node/wwmng/wwmng/style/images/independent/DefaultAvatar$73ba92b5.png]]></ApplyUserImage>
    <ApprovalNodes>
      <ApprovalNode>
        <NodeStatus>2</NodeStatus>
        <Items>
          <Item>
            <ItemName><![CDATA[xxx]]></ItemName>
            <ItemImage><![CDATA[https://rescdn.qqmail.com/node/wwmng/wwmng/style/images/independent/DefaultAvatar$73ba92b5.png]]></ItemImage>
            <ItemUserId><![CDATA[642005]]></ItemUserId>
            <ItemStatus>2</ItemStatus>
            <ItemSpeech><![CDATA[这是审批意见]]></ItemSpeech>
            <ItemOpTime>1680354268</ItemOpTime>
          </Item>
        </Items>
        <NodeAttr>1</NodeAttr>
        <NodeType>1</NodeType>
      </ApprovalNode>
     </ApprovalNodes>
     <NotifyNodes></NotifyNodes>
      <ApproverStep>0</ApproverStep>
    </ApprovalInfo>
 </xml>
```
##code

是不是RequestMessageEvent_OpenApprovalChange requestMessage 这个类有问题？

以下是错误信息：

System.InvalidOperationException: There is an error in XML document (5, 4).
 ---> System.FormatException: The input string '25b9e830ed383c2713c13f5614757c7b_899122340' was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, ReadOnlySpan`1 value, TypeCode type)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderOpenApprovalInfo.Read5_OpenApprovalInfo(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderOpenApprovalInfo.Read6_ApprovalInfo()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at Senparc.CO2NET.Utilities.XmlUtility.Deserialize(Type type, String xml, String rootNodeName)

##### 微信官方文档 URL
https://developer.work.weixin.qq.com/document/path/91815

##### 发现问题的模块

- [ ] Senparc.Weixin.Work 版本：

3.15.17

##### 模块对应的 .net 版本 

net7 

##### 开发环境

- [x] Visual Studio 2022 17.5.3

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [ ] Linux，版本：

**Comment by JeffreySu** [comment]
@bocblca  非常感谢！新版本已经发布。
