### ISSUE TITLE
RedPackApi查询红包方法报错！

### ISSUE THREAD

**Issue by hiseab** [JeffreySu/WeiXinMPSDK#281]
1.把:X509Certificate cer = new X509Certificate(cert, password);换成
X509Certificate2 cer = new X509Certificate2(cert, password, X509KeyStorageFlags.PersistKeySet | X509KeyStorageFlags.MachineKeySet);就好了

2.去掉wechatHBInfo.status = hbinfo.SelectSingleNode("status").InnerText;微信返回没有status这个字段

另外建议发送红包时把string mchbillno = GetNewBillNo(mchId);商户订单号提出来让用户自己生成传进来

**Comment by JeffreySu** [comment]
1、不知道你说的是不是SearchRedPack方法中，已经修改：https://github.com/JeffreySu/WeiXinMPSDK/commit/1de6b3388c40bfb585b2e25dad5f13374c376772

2、已修复：https://github.com/JeffreySu/WeiXinMPSDK/commit/59c090f298bfd2b85dd30a2ba5beb61450506160

3、这个billNo的格式是文档中有规定的，不是随意的，TenPayV3Util.BuildRandomStr这个方法也是官方提供的（官方的代码其实有bug，已经修复），如果要自定义的话也就剩下修改这个随机字符串的方法。此问题暂时没有做修改。

非常感谢！
