### ISSUE TITLE
红包发送接口在加入场景参数等，后会引发签名错误

### ISSUE THREAD

**Issue by dyb628** [JeffreySu/WeiXinMPSDK#285]
经过查看源码，发现红包计算签名的位置不对，在加入后续的不是必填参数后，这些参数不能加入到签名算法中，需要将 计算签名的代码位置进行调整，放在所有 不是必填参数后面，在进行签名

**Comment by JeffreySu** [comment]
能举一个具体一点的例子吗？

**Comment by dyb628** [comment]
RedPackApi.SendNormalRedPack(AppID, MchId, TenPayKey, cert, openid, "xxx公司", "127.0.0.1",
              1000, “中奖红包”, "游戏抽奖/兑换", "抽奖/兑换", out nonceStr, out paySign, Senparc.Weixin.MP.RedPack_Scene.PRODUCT_2);

在最后加入  RedPack_Scene.PRODUCT_2  红包场景2，在源码中中，这个 红包场景没有被加入到签名中，只需要移动下签名计算的代码顺序就可以了

**Comment by JeffreySu** [comment]
你的意思是调整后变成这样是吧：
![image](https://cloud.githubusercontent.com/assets/2281927/20645834/72b767fe-b4a5-11e6-8516-0427d675f9b2.png)

**Comment by JeffreySu** [comment]
已经更新一个版本，你看一下是不是这样：https://github.com/JeffreySu/WeiXinMPSDK/commit/4fa827faa1b1bdbe92fb012b89eae3a023d7eb7d

**Comment by dyb628** [comment]
就是这样

**Comment by JeffreySu** [comment]
OK，那已经修复了，如果还有问题欢迎继续反馈，谢谢！
