### ISSUE TITLE
接收微信授权事件推送"快速创建个人小程序"  缺少字段

### ISSUE THREAD

**Issue by fishjimi** [JeffreySu/WeiXinMPSDK#2870]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
`Senparc.Weixin.Open.RequestMessageThirdFasteRegister`这个类只覆盖到了[快速注册企业小程序](https://developers.weixin.qq.com/doc/oplatform/openApi/OpenApiDoc/register-management/fast-registration-ent/registerMiniprogram.html)示例的字段
```xml
<xml>
    <AppId><![CDATA[第三方平台appid]]></AppId>
    <CreateTime>1535442403</CreateTime>
    <InfoType><![CDATA[notify_third_fasteregister]]></InfoType>
    <appid>创建小程序appid</appid>
    <status>0</status>
    <auth_code>xxxxx第三方授权码</auth_code>
    <msg>OK</msg>
    <info>
    <name><![CDATA[企业名称]]></name>
    <code><![CDATA[企业代码]]></code>
    <code_type>1</code_type>
    <legal_persona_wechat><![CDATA[法人微信号]]></legal_persona_wechat>
    <legal_persona_name><![CDATA[法人姓名]]></legal_persona_name>
    <component_phone><![CDATA[第三方联系电话]]></component_phone>
    </info>
</xml>
```
没有覆盖[快速注册个人小程序](https://developers.weixin.qq.com/doc/oplatform/openApi/OpenApiDoc/register-management/fast-registration-ind/fastRegisterPersonalMp.html)示例的字段 （info里面是不同的）
```xml
<xml>
    <AppId><![CDATA[第三方平台appid]]></AppId>
    <CreateTime>1535442403</CreateTime>
    <InfoType><![CDATA[notify_third_fasteregister]]></InfoType>
    <appid>创建小程序appid</appid>
    <status>0</status>
    <auth_code>xxxxx第三方授权码</auth_code>
    <msg>OK</msg>
    <info>
    <wxuser><![CDATA[用户微信号]]></wxuser>
    <idname><![CDATA[用户姓名]]></wxidnnn>
    <component_phone><![CDATA[第三方联系电话]]></component_phone>
    </info>
</xml>
```
##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [x] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] Senparc.Weixin.Tenpay 版本：
- [ ] Senparc.WebSocket 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5+
- [ ] .net standard 2.0 / 2.1
- [ ] .net core 1.x
- [ ] .net core 2.x
- [ ] .net core 3.x
- [ ] .net 5.x / 6.x
- [x] .net 7.0

##### 开发环境

- [ ] Visual Studio 2019
- [x] Visual Studio 2022
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [x] Windows，版本：
- [x] Linux，版本：
- [ ] Mac，版本：
- [ ] 其他：

##### 联系方式
Email：me@jimifish.com

（也可将问题地址及联系方式发送到 zsu@senparc.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by mojinxun** [comment]
@SenparcHai

**Comment by JeffreySu** [comment]
已发布新版本，感谢！
