### ISSUE TITLE
ChatApi.cs 的文件描述好像不对

### ISSUE THREAD

**Issue by pipihu** [JeffreySu/WeiXinMPSDK#288]
https://github.com/JeffreySu/WeiXinMPSDK/blob/master/src/Senparc.Weixin.QY/Senparc.Weixin.QY/AdvancedAPIs/Chat/ChatApi.cs
这个是关于会话的，文件描述却是
/*----------------------------------------------------------------
    Copyright (C) 2016 Senparc
    
    文件名：UploadResultJson.cs
    文件功能描述：上传媒体文件返回结果
    
    
    创建标识：Senparc - 20150728
    修改标识：Senparc - 20160720
    修改描述：增加其接口的异步方法
 
----------------------------------------------------------------*/

**Comment by JeffreySu** [comment]
是的，已经修改，感谢！ 版本：https://github.com/JeffreySu/WeiXinMPSDK/commit/1212b1abd41465154866ea43f16d46d8dc315b37
