### ISSUE TITLE
关于同步锁问题!

### ISSUE THREAD

**Issue by thisXYH** [JeffreySu/WeiXinMPSDK#290]
![image](https://cloud.githubusercontent.com/assets/16305024/20786723/a316f1d6-b7e2-11e6-9927-b2990b965d70.png)
![image](https://cloud.githubusercontent.com/assets/16305024/20786788/f9e1697e-b7e2-11e6-9526-971013d805c9.png)
好多都有这个死锁的问题, 还是我哪里没有配置好?

**Comment by JeffreySu** [comment]
除了这里还有其他什么地方？

**Comment by FrancisFYK** [comment]
已经修复，非常感谢！版本：Open v2.3.3 更新记录：https://github.com/JeffreySu/WeiXinMPSDK/commit/0bc52b32bd53236bce5ac6d084b228d1c050c5ed

**Comment by thisXYH** [comment]
加锁的地方都修复了?    为什么要加这个同步锁哈

**Comment by JeffreySu** [comment]
已经修复了。如果是分布式环境，这种数据读写必须要用同步锁啊

**Comment by thisXYH** [comment]
@JeffreySu  好的, 谢谢啦
