### ISSUE TITLE
.net core 7中 始终找不到 UseSenparcWeixin方法

### ISSUE THREAD

**Issue by yfeng** [JeffreySu/WeiXinMPSDK#2990]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
在Program.cs中

var app = builder.Build();
 
  app.UseSenparcWeixin(app.Environment,
    null ,
    null 
  
   );
 始终找不到 UseSenparcWeixin这个方法啊，并且也引用了
 using Senparc.Weixin;

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 发现问题的模块

- [ x] Senparc.Weixin 版本：6.17.1
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ x] Senparc.Weixin.WxOpen 版本：3.17.6
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] Senparc.Weixin.Tenpay 版本：
- [ ] Senparc.WebSocket 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5+
- [ ] .net standard 2.0 / 2.1
- [ ] .net core 1.x
- [ ] .net core 2.x
- [ ] .net core 3.x
- [ ] .net 5.x / 6.x
- [x] .net  core 7.0

##### 开发环境

- [ ] Visual Studio 2019
- [] Visual Studio 2022
- [ ] Visual Studio Code
- [ x] 其他：rider

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [] Windows，版本：
- [ ] Linux，版本：
- [x] Mac，版本：
- [ ] 其他：

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 zsu@senparc.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
@yfeng 是不是没有引用 Senparc.Weixin.AspNet 包？对比一下我们的 Sample 的引用。

**Comment by JeffreySu** [comment]
另外建议直接上 .NET 8 吧，这个是 LTS 版本。跟 .NET 7 是兼容的。
