### ISSUE TITLE
和serilog在依赖注入的时候有冲突

### ISSUE THREAD

**Issue by kentxxq** [JeffreySu/WeiXinMPSDK#3047]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述

serilog-aspnetcore 的 `CreateBootstrapLogger` 和  `app.UseSenparcWeixin` 冲突. 

报错
```
Unhandled exception. System.TypeInitializationException: The type initializer for 'Nested' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Nested' threw an exception.
 ---> Senparc.CO2NET.Exceptions.CacheException: IMemoryCache 依赖注入未设置！如果您使用的是本地缓存，请确保在 Startup.cs 中执行了 services.AddMemoryCache() 方法！
   at Senparc.CO2NET.Cache.LocalObjectCacheHelper.get_LocalObjectCache()
   at Senparc.CO2NET.Cache.LocalObjectCacheStrategy..ctor()
   at Senparc.CO2NET.Cache.LocalObjectCacheStrategy.Nested..cctor()
```

代码如下

```csharp
Log.Logger = new LoggerConfiguration()
    // .CreateLogger();    这个可以正常工作
    .CreateBootstrapLogger();  // 这种会报错

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddMemoryCache();
builder.Services.AddSenparcWeixinServices(builder.Configuration);
builder.Services.AddSerilog((services, lc) => lc
    .AddCustomLogConfig(builder.Configuration));

var app = builder.Build();

var registerService = app
    .UseSenparcWeixin(app.Environment,
    null /* 不为 null 则覆盖 appsettings  中的 SenpacSetting 配置*/,
    null /* 不为 null 则覆盖 appsettings  中的 SenpacWeixinSetting 配置*/,
    register => { /* CO2NET 全局配置 */ },
    (register, weixinSetting) =>
    {
        //注册公众号信息（可以执行多次，注册多个公众号）
        register.RegisterMpAccount(weixinSetting, "【自己的测试】公众号");
    });

app.UseSerilogRequestLogging();
app.MapControllers();
app.Run();
```

##### 重现问题步骤（如果可以）

1. 安装`Serilog.AspNetCore`和`Senparc.Weixin.All`
2. 使用`Serilog.AspNetCore`的`CreateBootstrapLogger`两步验证

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [x] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] Senparc.Weixin.Tenpay 版本：
- [ ] Senparc.WebSocket 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5+
- [ ] .net standard 2.0 / 2.1
- [ ] .net core 1.x
- [ ] .net core 2.x
- [ ] .net core 3.x
- [ ] .net 5.x / 6.x
- [x] .net 7.0

##### 开发环境

- [ ] Visual Studio 2019
- [x] Visual Studio 2022
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [x] Windows，版本：
- [ ] Linux，版本：
- [ ] Mac，版本：
- [ ] 其他：

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 zsu@senparc.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
@kentxxq  SDK 内部没有对外部缓存做任何处理，您可以尝试一下把这一段代码放到 AddSenparcWeixinServices() 之后试试看。

**Comment by kentxxq** [comment]
> @kentxxq SDK 内部没有对外部缓存做任何处理，您可以尝试一下把这一段代码放到 AddSenparcWeixinServices() 之后试试看。

换了顺序也不行...     我去掉了, 不使用serilog的两步验证就没问题

**Comment by Axlingking** [comment]
确实存在这个问题，使用 CreateLogger 即可
