### ISSUE TITLE
企业微信获取部门信息需求

### ISSUE THREAD

**Issue by c10231** [JeffreySu/WeiXinMPSDK#3056]
> ***此版块专为反馈 bug 及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA***

##### 问题描述
企业微信开发文档中提供了通过部门ID，获取部门详细信息的接口。目前MailListApi中，只能获取部门列表和部门ID列表，无法根据部门ID获取部门信息。

另外public class DepartmentList 类中的字段不全
完整的应该是
{
           "id": 2,
           "name": "广州研发中心",
           "name_en": "RDGZ",
	   "department_leader":["zhangsan","lisi"],
           "parentid": 1,
           "order": 10
       }

##### 重现问题步骤（如果可以）

1. ...
2. ...

##### 微信官方文档快照（直接复制关键内容到下方）
https://developer.work.weixin.qq.com/document/path/95351

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
~- [ ] Senparc.Weixin.QY 版本：~
- [x] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] Senparc.Weixin.Tenpay 版本：
- [ ] Senparc.WebSocket 版本：
- [ ] 其他模块：

##### 模块对应的 .net 版本

- [ ] .net 3.5
- [ ] .net 4.0
- [ ] .net 4.5+
- [ ] .net standard 2.0 / 2.1
- [ ] .net core 1.x
- [ ] .net core 2.x
- [ ] .net core 3.x
- [ ] .net 5.x / 6.x
- [x] .net 7.0

##### 开发环境

- [ ] Visual Studio 2019
- [x] Visual Studio 2022
- [ ] Visual Studio Code
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他：

##### 系统环境

- [x] Windows，版本：
- [ ] Linux，版本：
- [ ] Mac，版本：
- [ ] 其他：

##### 联系方式
Email：c10231@126.com

（也可将问题地址及联系方式发送到 zsu@senparc.com）

> 发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。

**Comment by JeffreySu** [comment]
@c10231 可以看一下接口文档的说明现在通过常规 API 应该已经获取不到部门详情了吧？
