### ISSUE TITLE
发送视频客服消息CustomApi.SendVideo 

### ISSUE THREAD

**Issue by hello2008zj** [JeffreySu/WeiXinMPSDK#306]
发送视频客服消息增加 thumb_media_id  缩略图Id参数

public static WxJsonResult SendVideo(string accessTokenOrAppId, string openId, string mediaId, string title, 
            string description, int timeOut = Config.TIME_OUT, string kfAccount = ""**, string thumb_media_id = ""**)

**Comment by JeffreySu** [comment]
已经更新，感谢！
版本：MP v14.3.112 https://github.com/JeffreySu/WeiXinMPSDK/pull/311/commits/bef931780dfa41814af146fb468c527f47ad2ff4
