### ISSUE TITLE
在代码中，发现很多地方都用了Generic.Dictionary这个类（多线程下会有问题，导致CPU 100%）

### ISSUE THREAD

**Issue by jucheap** [JeffreySu/WeiXinMPSDK#308]
在代码中，发现很多地方都用了Generic.Dictionary这个类（多线程下会有问题，导致CPU 100%，我在线上环境测试出来的）。

**Comment by JeffreySu** [comment]
可以把您测试的代码发上来一下吗？我们目前还没有发现有这样的情况。另外Dictionary这个类正常使用下面是不会导致这么高的CPU的。
