### ISSUE TITLE
调用参数自定义序列化器中失效问题

### ISSUE THREAD

**Issue by benbenzlj** [JeffreySu/WeiXinMPSDK#309]
经过多次调试，问题原因出现在SupportTypes，这里只能传入最终的类型，而不能是接口。
按现有的代码，可以在JsonSetting中增加属性，在调用时传入

**Comment by JeffreySu** [comment]
请问能够说详细一点或者给一个示例代码吗？

**Comment by benbenzlj** [comment]
不好意思，回复晚了
其实在WeixinJsonConventer 这个类的SupportedTypes 方法中已有判断，只不过我感觉名称稍微有点问题
![image](https://cloud.githubusercontent.com/assets/5343522/21492825/cf1dbee4-cc42-11e6-82a4-49a3baef60da.png)
所以只需要在调用时传入支持的类型就可以了
![image](https://cloud.githubusercontent.com/assets/5343522/21492876/191da61c-cc43-11e6-8a1e-cec8e661a8d7.png)

**Comment by JeffreySu** [comment]
先关闭了，如果还有问题请 Reopen 这个 issue，谢谢！
