### ISSUE TITLE
统一下单接口第一次调用的时候非常慢，要10秒。

### ISSUE THREAD

**Issue by nextuntil** [JeffreySu/WeiXinMPSDK#310]
string payResult = Senparc.Weixin.MP.AdvancedAPIs.TenPayV3.Unifiedorder(data, 30000);
APP里做微信支付，由服务端调用统一下单接口，第一次的时候非常慢，每次都是要10秒。
是哪里的问题？

**Comment by JeffreySu** [comment]
如果您用的是阿里云，可以参考一下这里：https://github.com/JeffreySu/WeixinResource/blob/master/%E9%82%A3%E4%BA%9B%E5%B9%B4%E6%88%91%E4%BB%AC%E8%B8%A9%E8%BF%87%E7%9A%84%E5%9D%91/20161224-%E4%BD%BF%E7%94%A8%E9%98%BF%E9%87%8C%E4%BA%91%E5%AF%BC%E8%87%B4%E7%BB%9F%E4%B8%80%E4%B8%8B%E5%8D%95%E6%8E%A5%E5%8F%A3%E8%B0%83%E7%94%A8%E8%B6%85%E6%97%B6.md
