### ISSUE TITLE
在WCF中如何使用ResponseHandler？

### ISSUE THREAD

**Issue by coolboy0821** [JeffreySu/WeiXinMPSDK#339]
在wcf中HttpContext.Request.InputStream会引发异常，不知如何在wcf中new ResponseHandler对象呢？wcf获取inputStream和mvc不太一样.有什么通用的解决办法吗？万分感谢~

**Comment by JeffreySu** [comment]
你的WCF代码是怎么样的？

有两篇文章可以参考一下（里面用的是JSON，微信默认是XML的）：
http://www.cnblogs.com/GeeWu/archive/2011/06/29/wcf_1.html
http://blog.csdn.net/zhuifenging/article/details/8146330

**Comment by coolboy0821** [comment]
是这样的，通过WCF写的接口

**Comment by coolboy0821** [comment]
`
[WebInvoke(UriTemplate = "PayNotify")]
public Stream PayNotify(Stream stream){
    ResponseHandler resHandler = new ResponseHandler(null);
}
`
ResponseHandler 里边是通过HttpContext.Request.InputStream获取请求体的输入流，但是WCF通过HttpContext获取输入流有异常。
我的WCF获取输入流的方法是定义接口参数为Stream，即可获取到post输入流。
但是无法把输入流传入到ResponseHandler 中，我自己修改了下ResponseHandler，增加了一个构造函数，不接收HttpContext而是接收Stream。暂时解决了我在wcf里调用的问题。


`
            try
            {
                if (this.HttpContext.Request.InputStream.Length > 0)
                {
                    XmlDocument xmlDoc = new XmlDocument();
                    xmlDoc.Load(this.HttpContext.Request.InputStream);
                    XmlNode root = xmlDoc.SelectSingleNode("xml");
                    XmlNodeList xnl = root.ChildNodes;

                    foreach (XmlNode xnf in xnl)
                    {
                        XmlMap.Add(xnf.Name, xnf.InnerText);
                        this.SetParameter(xnf.Name, xnf.InnerText);
                    }
                }
            }
            catch { }

            try
            {
                if (stream != null)
                {
                    XmlDocument xmlDoc = new XmlDocument();
                    xmlDoc.Load(stream);
                    XmlNode root = xmlDoc.SelectSingleNode("xml");
                    XmlNodeList xnl = root.ChildNodes;

                    foreach (XmlNode xnf in xnl)
                    {
                        XmlMap.Add(xnf.Name, xnf.InnerText);
                        this.SetParameter(xnf.Name, xnf.InnerText);
                    }
                }
            }
            catch { }
`

**Comment by JeffreySu** [comment]
你看一下上面我给的例子，然后你可以找到直接接收XML格式的，MessageHandler的构造函数可以直接接收XDocument对象。
