### ISSUE TITLE
卡券的创建二维码接口返回值缺少问题

### ISSUE THREAD

**Issue by canyouhn** [JeffreySu/WeiXinMPSDK#347]
官方接口返回值如下：
`
{
 "errcode": 0,
 "errmsg": "ok",
 "ticket":      "gQHB8DoAAAAAAAAAASxodHRwOi8vd2VpeGluLnFxLmNvbS9xL0JIV3lhX3psZmlvSDZmWGVMMTZvAAIEsNnKVQMEIAMAAA==",//获取ticket后需调用换取二维码接口获取二维码图片，详情见字段说明。
 "expire_seconds": 1800,
 "url": "http://weixin.qq.com/q/BHWya_zlfioH6fXeL16o ",
 "show_qrcode_url": " https://mp.weixin.qq.com/cgi-bin/showqrcode?  ticket=gQH98DoAAAAAAAAAASxodHRwOi8vd2VpeGluLnFxLmNvbS9xL0czVzRlSWpsamlyM2plWTNKVktvAAIE6SfgVQMEgDPhAQ%3D%3D"
 }
`
但是外面实际接口接收的类型CreateQRResultJson里面只有一个属性ticket
其中url，和show_qrcode_url无法获取

**Comment by canyouhn** [comment]
http请求方式: POST
https://api.weixin.qq.com/card/qrcode/create?access_token=TOKEN

**Comment by JeffreySu** [comment]
CreateQRResultJson继承了WxJsonResult，所以 `"errcode": 0, "errmsg": "ok"` 这个应该是有的，url和show_qrcode_url目前确实没有，已经添加了：https://github.com/JeffreySu/WeiXinMPSDK/commit/f1e4c29e93a34db79e508c21a6a7841fce001fbd

非常感谢！
