### ISSUE TITLE
批量获取用户基本信息(BatchGetUserInfo)出错

### ISSUE THREAD

**Issue by mengshuaiyang** [JeffreySu/WeiXinMPSDK#353]
在使用批量获取用户基本信息(BatchGetUserInfo)方法时，获取到的city、country、province都是英文状态下的。已设置获取内容为中文（lang = Language.zh_CN）。
后来发现在批量获取的时候代码如下：
```
{
    "user_list": [
        {
            "openid": "otvxTs4dckWG7imySrJd6jSi0CWE", 
            "lang": "zh-CN"
        }, 
        {
            "openid": "otvxTs_JZ6SEiP0imdhpi50fuSZg", 
            "lang": "zh-CN"
        }
    ]
}
```
是不是因为zh_CN和zh-CN不一致导致的在批量获取用户基本信息时无法获取到中文版的内容？还是其他的原因？

**Comment by JeffreySu** [comment]
这个应该是微信接受的类型是int，而JSON默认提供了枚举字符串的原因，我们正在处理这个序列化的问题，争取在下一个版本中修复，谢谢！

**Comment by JeffreySu** [comment]
目前已经暂时将lang改为int类型。
https://github.com/JeffreySu/WeiXinMPSDK/commit/9c134c5f49664c7820589a2ff1bf67567201afaa#diff-4ba3077dc7c15964d961727939d3bf78

（暂时在Developer分支下）

**Comment by mengshuaiyang** [comment]
好的，谢谢解答！

**Comment by JeffreySu** [comment]
感谢反馈！
