### ISSUE TITLE
处理微信信息的时候遇到的问题

### ISSUE THREAD

**Issue by Fengxq2014** [JeffreySu/WeiXinMPSDK#354]
![ux70 t22 1va kk52_d7c30](https://cloud.githubusercontent.com/assets/8519834/21922471/b52cac60-d9a9-11e6-925c-80867280c070.png)
最后返回的结果是：
![image](https://cloud.githubusercontent.com/assets/8519834/21922580/5e91daa0-d9aa-11e6-9f90-709ccd231ad7.png)
用注释掉的Content()方法却是正确的，dll是Nuget下载的，看了demo里也是这样用的，不知道我问题在哪里，望解答，谢谢了~，顺便说下，谢谢开源这么好用的项目~

**Comment by JeffreySu** [comment]
建议使用FixWeixinBugWeixinResult取代WeixinResult，看一下是否还有这个问题？

**Comment by Fengxq2014** [comment]
是一样的情况

**Comment by F2EVarMan** [comment]
我也遇到了童谣的情况，只有返回Content 才是正确的其他的都失败

**Comment by JeffreySu** [comment]
@Fengxq2014 @F2EVarMan 
1. 麻烦看一下你们使用的MP和MP.MvcExtension.dll的版本分别是多少？Nuget上面过年前我们发布过一个新的版本。
2. 如果只部署我们源代码中的Sample项目也存在这样的问题吗？

**Comment by F2EVarMan** [comment]
现在我用 Senparc.Weixin 4.8.0 就可以 但是返回 ResponseMessageNoResponse 微信还会提示 改公众号暂时无法提供服务， 请问如果想返回空应该怎么办呢。我看了只有返回 return content("") 微信才不会有这个提示

**Comment by JeffreySu** [comment]
@F2EVarMan 如果用现在全部最新的Sample的代码，会有这个问题吗？另外你用的是.net 4.0还是4.5的？

**Comment by Fengxq2014** [comment]
@JeffreySu 我用的是4.9.0的dll，运行时是4.5

**Comment by JeffreySu** [comment]
感谢各位的反馈！
请各位更新到最新版本，已经全面测试过，应该不存在上述问题了，如果还发现有问题，请ReOpen这个Issue，谢谢！
