### ISSUE TITLE
微信公众号素材修改之后，在微信中查看还是以前的内容

### ISSUE THREAD

**Issue by zhujinhu21** [JeffreySu/WeiXinMPSDK#361]
素材群发之后，调用MediaApi.UpdateForeverNewsAsync(accessToken, mediaId, 0, new2); 修改图文素材，在公众号显示的内容还是以前的内容，没有修改过来

**Comment by JeffreySu** [comment]
已经群发的消息是不能改的，这个自还能改库里面的素材。

**Comment by zhujinhu21** [comment]
请问下，我群发后，在素材管理中把素材删除后，别人还能看到群发的文章吗

**Comment by JeffreySu** [comment]
可以的，群发之后和素材内容其实没有关系了。

**Comment by zhujinhu21** [comment]
谢谢指导
