### ISSUE TITLE
用NuGet无法安装，总是提示程序包还原失败

### ISSUE THREAD

**Issue by edtim8** [JeffreySu/WeiXinMPSDK#362]
ASP.net Core 1.1.0

可安装包；
Senparc.Weixin
Senparc.Weixin.Mp
Senparc.Weixin.WxOpen

安装还原失败包：
Senparc.Weixin.QY
Senparc.Weixin.Open
Senparc.Weixin.MP.MVC
Senparc.Weixin.WxOpen

**Comment by JeffreySu** [comment]
core目前还没有移植下面4个项目。
