### ISSUE TITLE
WeixinContext能否添加几个函数？

### ISSUE THREAD

**Issue by jianliulin** [JeffreySu/WeiXinMPSDK#363]
```
public T  GetLastRequestMessage<T>(string userName) where T:TRequest
public T  GetLastResponseMessage<T>(string userName) where T:TResponse

public List<T>  GetRequestMessage<T>(string userName) where T:TRequest
public List<T>  GetResponseMessage<T>(string userName) where T:TResponse
```

谢谢

**Comment by JeffreySu** [comment]
```
public List<T>  GetRequestMessage<T>(string userName) where T:TRequest
public List<T>  GetResponseMessage<T>(string userName) where T:TResponse
```

这两个列表已经在WeixinContext.GetMessageContext(username)里面输出了（https://github.com/JeffreySu/WeiXinMPSDK/blob/88bb4e94bb1a7365821707b93975a72a311207a7/src/Senparc.Weixin/Senparc.Weixin/Context/WeixinContext.cs#L126），返回的是IMessageContext（当前官方提供的是MessageContext），里面有RequestMessages和ResponseMessages两个变量，已经完全可以满足要求（https://github.com/JeffreySu/WeiXinMPSDK/blob/88bb4e94bb1a7365821707b93975a72a311207a7/src/Senparc.Weixin/Senparc.Weixin/Context/MessageContext.cs#L82）。

**Comment by jianliulin** [comment]
想好返回强类型，比如我想找上传地址信息的消息，
`var list= GetRequestMessage<RequestMessageEvent_Location>(userName);`

**Comment by JeffreySu** [comment]
那只需要这样就行了：
`list.where(z=>z is RequestMessageEvent_Location)`
