### ISSUE TITLE
公众号认证失效通知中的开发者微信号是什么

### ISSUE THREAD

**Issue by zhujinhu21** [JeffreySu/WeiXinMPSDK#368]
公众号认证失效通知中的开发者微信号是什么，我怎么给这个微信号发送通知

![qq 20170119202733](https://cloud.githubusercontent.com/assets/4327149/22106863/d1d17590-de85-11e6-80b7-61fbb8651a05.png)

http://mp.weixin.qq.com/wiki/10/2adfb2f10828e87aa1e5c3ef83b17906.html

**Comment by JeffreySu** [comment]
这个账号就是你的公众号的id，在后台设置中应该可以看到，例如`gh_eec5c84f1e0b`这样的。

### issue模块专用于反馈Senparc.Weixin SDK项目本身存在的问题（bug）以及您的需求。
如果您需要其他方面的帮助，请移步[问答社区](http://weixin.senparc.com/QA)
