### ISSUE TITLE
ApiHandlerWapper的TryCommonApiAsync方法导致线程Deadlock。

### ISSUE THREAD

**Issue by hentaicreep** [JeffreySu/WeiXinMPSDK#376]
ApiHandlerWapper的TryCommonApiAsync方法导致线程Deadlock。

参考连接：
http://blog.darkthread.net/post-2015-08-06-await-task-block-deadlock.aspx
http://blog.stephencleary.com/2012/07/dont-block-on-async-code.html

`  public static async Task<T> TryCommonApiAsync<T>(Func<string, Task<T>> fun, string accessTokenOrAppId = null, bool retryIfFaild = true) where T : WxJsonResult
{
            string appId = null;
            string accessToken = null;

            if (accessTokenOrAppId == null)
            {
                appId = AccessTokenContainer.GetFirstOrDefaultAppId();
                if (appId == null)
                {
                    throw new UnRegisterAppIdException(null,
                        "尚无已经注册的AppId，请先使用AccessTokenContainer.Register完成注册（全局执行一次即可）！");
                }
            }
            else if (ApiUtility.IsAppId(accessTokenOrAppId))
            {
                if (!AccessTokenContainer.CheckRegistered(accessTokenOrAppId))
                {
                    throw new UnRegisterAppIdException(accessTokenOrAppId,
                        string.Format("此appId（{0}）尚未注册，请先使用AccessTokenContainer.Register完成注册（全局执行一次即可）！",
                            accessTokenOrAppId));
                }

                appId = accessTokenOrAppId;
            }
            else
            {
                accessToken = accessTokenOrAppId; //accessToken
            }

            Task<T> result = null;

            try
            {
                if (accessToken == null)
                {
                    var accessTokenResult = await AccessTokenContainer.GetAccessTokenResultAsync(appId, false);
                    accessToken = accessTokenResult.access_token;
                }
                result = fun(accessToken);
            }
            catch (ErrorJsonResultException ex)
            {
                if (retryIfFaild
                    && appId != null
                    && ex.JsonResult.errcode == ReturnCode.获取access_token时AppSecret错误或者access_token无效)
                {
                    //尝试重新验证
                    var accessTokenResult = AccessTokenContainer.GetAccessTokenResultAsync(appId, true);
                    //强制获取并刷新最新的AccessToken
                    accessToken = accessTokenResult.Result.access_token;
                    result = TryCommonApiAsync(fun, appId, false);
                }
                else
                {
                    throw;
                }
            }

            return result.Result;
        }`

最后的return result.Result需要修改为return await result

**Comment by JeffreySu** [comment]
我们这边单元测试和线上测试都没有发现死锁的情况，您那边有这样的现象？

目前Developer中的代码已经升级到v14.3.121，按照return await result写了，谢谢！

**Comment by hentaicreep** [comment]
@JeffreySu 我这边用的Win10(Version 14393。693 )上的.NET Framework 4.5的WebApi项目，运行在IIS10(Version 10.0.14393.0)里面，在调用任何使用到TryCommonApiAsync方法的地方都会导致await的代码回不来，线程死锁在那里，后来搜索发现了上面的两篇博客，然后按照他们的说法把result.Result改成了await result后就正常了，没出现死锁的情况了。

**Comment by JeffreySu** [comment]
同样的环境我们测试都是通过的，我们会持续关注的，代码已经按照您的建议修改了，非常感谢！

PS：如果您有调用异步方法的代码是否可以发上来看一下，我们再做一个相同代码的测试？

**Comment by hentaicreep** [comment]
我刚才试了下，在Console环境里是正常的，但是在WebApi环境下是可以重现这个问题的，以下是我的测试代码：
public class ValuesController : ApiController
    {
        public async Task<IHttpActionResult> Get()
        {
            AccessTokenContainer.Register("你的APPID", "你的APPSECRET");
            List<BatchGetUserInfoData> userList = new List<BatchGetUserInfoData>()
            {
                new BatchGetUserInfoData() {openid="你的用户的OPENID" }
            };
            var result = await UserApi.BatchGetUserInfoAsync("你的APPID", userList);
            return Json(result);
        }
}
用result.Result线程就死锁了，用await result就是好的。

**Comment by JeffreySu** [comment]
@hentaicreep 是异步线程在ASP.NET下的问题，之前的几个版本中会有问题，目前应该已经解决了，如果还有问题欢迎 Reopen 这个 issue 并继续讨论，谢谢！
