### ISSUE TITLE
BatchGetUserInfoData的lang属性类型应该是string而不是int

### ISSUE THREAD

**Issue by hentaicreep** [JeffreySu/WeiXinMPSDK#398]
BatchGetUserInfoData的lang属性类型应该是string而不是int，不然微信会提示“invalid openid list size”

`public int lang { get; set; }}`

修改为：

`ing _lang = "zh_CN";
        public string lang
        {
            get
            {
                return _lang;
            }
            set
            {
                _lang = value;
            }
        }
    }`

**Comment by JeffreySu** [comment]
已经修改，您看一下这样是否正确：https://github.com/JeffreySu/WeiXinMPSDK/commit/4f2ce1f8782ec398dbf282d777ccdbf70e5adb27

目前在Developer分之下，没问题了我会合并到master。

非常感谢！

**Comment by JeffreySu** [comment]
@hentaicreep 目前这样是否正确？

**Comment by hentaicreep** [comment]
@JeffreySu  正常了，感谢修改

**Comment by JeffreySu** [comment]
感谢反馈问题！
