### ISSUE TITLE
关于UserApi.Info的问题

### ISSUE THREAD

**Issue by hentaicreep** [JeffreySu/WeiXinMPSDK#399]
你好，我现在在调用UserApi.Info的时候发现一个问题，就是在我初始化程序后第一次调用UserApi.Info与后面再次调用UserApi.Info拿到的结果不一样，后来调试了一下发现是微信的服务器返回的结果好像就有点问题。

具体问题的截图如下：
1.
![1](https://cloud.githubusercontent.com/assets/1901634/22617561/4ee9b1da-eb03-11e6-93a7-ed3c5bcc5717.png)
2.
![2](https://cloud.githubusercontent.com/assets/1901634/22617562/513aeee0-eb03-11e6-8e31-f69b9719ee81.png)
3.
![3](https://cloud.githubusercontent.com/assets/1901634/22617565/53cc7318-eb03-11e6-9832-f9fe1b92de2e.png)

重现步骤如下：
1.重启iis
2.第一次调用UserApi.Info，返回access_token信息
3.第二次调用UserApi.Info，返回userInfo信息

**Comment by JeffreySu** [comment]
你仔细看一下，第一次应该是执行了2次接口，第一次调用accesstoken，第二次常规的info，这个是SDK的AccessTokenContainer机制，发现你还没有缓存accesstoken，会自动帮你获取，获取之后下次就自动使用缓存了。

你应该使用的是本机缓存吧？如果是分布式的一般不会受IIS重启影响。

谢谢。

**Comment by hentaicreep** [comment]
@JeffreySu 你看看第二张截图，那是iis重启后第一次执行接口触发了SDK的AccessTokenContainer机制，第一个请求是获取accesstoken的这个我理解，但是获取完accesstoken紧接着会调用user/info接口，但是从图二可以看出user/info接口的返回值明显是accesstoken接口的返回值。

**Comment by hentaicreep** [comment]
@JeffreySu 好吧，突然发现这个现象跟我本机装的一个叫adbyby的屏蔽广告的软件有关，它缓存了accesstoken接口的结果，并在第一次调用user/info接口的时候把缓存的结果直接返回过来了。这个问题是我本机的环境问题，sorry。
