### ISSUE TITLE
LocalCacheLock的并发问题

### ISSUE THREAD

**Issue by justwezzz** [JeffreySu/WeiXinMPSDK#402]
@JeffreySu 你好，我们最近发现LocalCacheLock在高并发的情况下会出现问题，比如以下两种典型情况：
1.字典内有相同键
![2](https://cloud.githubusercontent.com/assets/1901634/22767334/962df6e0-eeb5-11e6-8e5f-ceb5c2900e8e.png)
2. 字典大小超过支持范围
![1](https://cloud.githubusercontent.com/assets/1901634/22767352/b4a8a926-eeb5-11e6-9d76-d9f1e36b5c57.png)

每次出错后WeiXinMPSDK都会去尝试RetryLock，如果错误是第二种情况，那么之后会在重试加锁9999次（每次间隔20ms）后才回到之前的流程上去（此时已经过了200s了）。如果是很多个并发一起来的话，所有的线程都被这里卡住，会导致cpu利用率升到100%，这里的现象有点类似与这个问题#308。

我有几个修改意见，不知道合适不合适，先在这里给你说一下：
1.使用ConcurrentDictionary替换Dictionary，使其支持高并发（但是有人说ConcurrentDictionary有自己的问题）
2.RetryLock里如果尝试获取锁的时候发生异常，不再重试而是直接向外抛出异常。
`catch (Exception ex)
                {
                    WeixinTrace.Log("本地同步锁发生异常：" + ex.Message);
                    //return false;
                    throw ex;
                }`

但是我没想到如何能让LockPool在出错后恢复正常的状态（比如图2的时候字典状态已经是大小超过支持范围，后面再也无法正常访问了），所以还想问问你的意见。

以下附上测试代码：
 `private void test()
        {
            UserApi.Info(Appid, openid);
        }`
`List<Task> TaskList = new List<Task>();
            for (int i=0;i<50;i++)
            {
                var LastTask = new Task(test);
                LastTask.Start();
                TaskList.Add(LastTask);
            }
            Task.WaitAll(TaskList.ToArray());`

**Comment by JeffreySu** [comment]
非常感谢反馈！有几个问题我需要了解一下：
1、这个问题只在LocalCache里面发生，还是Redis中也存在相同的情况？
2、您使用的版本是多少？
3、正好在5天前我们修改过LocalCacheLock.cs，进行了一些重构，并且已经给lock和unlock过程加了本地的lock方法，您看一下最新的方法是否可以避免这样的问题？

**Comment by JeffreySu** [comment]
我根据您上面提供的代码已经加了一个单元测试：https://github.com/JeffreySu/WeiXinMPSDK/blob/Developer/src/Senparc.Weixin.MP/Senparc.Weixin.MP.Test/CacheTests/CacheTests.cs

结果是8秒钟，应该是正常了。您可以试一下。

**Comment by hentaicreep** [comment]
@JeffreySu 你好！
以下是对你的问题的回答：
“1、这个问题只在LocalCache里面发生，还是Redis中也存在相同的情况？”
我们这边没有人用过Redis，所以我暂时还无法给你答复，实在抱歉。

“2、您使用的版本是多少？”
Senparc.Weixin用的4.9.11
Senparc.Weixin.MP用的14.3.120

“3、正好在5天前我们修改过LocalCacheLock.cs，进行了一些重构，并且已经给lock和unlock过程加了本地的lock方法，您看一下最新的方法是否可以避免这样的问题？”
这样修改后发现如果并发数是50的时候完全不会出现问题，但是一旦把并发数改成100又会出现原来的错误了:(

因为最近手头上项目比较紧张，所以我简单的做了下处理，在我自己的应用层做了个队列，把所有并发的请求全排在队列里，一个处理完了以后在处理另外一个，尽量避免了并发的发生。因为现在时间比较紧张，所以我可能会回复不是很及时，等项目松一点的时候我会好好看下这个问题的。

**Comment by JeffreySu** [comment]
我测试了100个线程，用了9秒，测试结果如下：
![image](https://cloud.githubusercontent.com/assets/2281927/22970822/8687a09e-f3ae-11e6-80d7-13e202ce95be.png)

200个线程是18秒，还是比较稳定的：
![image](https://cloud.githubusercontent.com/assets/2281927/22970888/b9530842-f3ae-11e6-8bf7-82ab5140e1d6.png)


测试代码我已经更新到github上（Developer分支）。你可以跑一下200个试试看。最好你那边能有一个测试结果发上来。

**Comment by JeffreySu** [comment]
@hentaicreep 这个问题后来有新的结论吗？

**Comment by JeffreySu** [comment]
@justwezzz 后来问题还有持续吗？我们运行了很长一段时间没有发现死锁的情况。，如果你那边还有，可以深入探讨一下。

**Comment by JeffreySu** [comment]
@justwezzz 长时间没有护肤，先关闭了，如果有新的讨论可以ReOpen，谢谢！

**Comment by KevinPan** [comment]
今天我的服务器也CPU 100%了，也没有高并发，启动的时候会卡死，CPU直接全负荷，服务器就没相应了。
我用的是最新版本的类库
  <package id="Senparc.CO2NET" version="1.3.200" targetFramework="net462" />
  <package id="Senparc.CO2NET.APM" version="0.9.200" targetFramework="net462" />
  <package id="Senparc.CO2NET.AspNet" version="0.3.200" targetFramework="net462" />
  <package id="Senparc.CO2NET.Cache.Memcached" version="3.7.200" targetFramework="net462" />
  <package id="Senparc.NeuChar" version="1.2.200.6" targetFramework="net462" />
  <package id="Senparc.NeuChar.App" version="0.8.200" targetFramework="net462" />
  <package id="Senparc.NeuChar.AspNet" version="0.2.200" targetFramework="net462" />
  <package id="Senparc.Weixin" version="6.7.600" targetFramework="net462" />
  <package id="Senparc.Weixin.AspNet" version="0.1.600" targetFramework="net462" />
  <package id="Senparc.Weixin.Cache.Memcached" version="2.6.600" targetFramework="net462" />
  <package id="Senparc.Weixin.MP" version="16.10.600" targetFramework="net462" />
  <package id="Senparc.Weixin.MP.MVC" version="7.5.600" targetFramework="net462" />

**Comment by JeffreySu** [comment]
@KevinPan 这段时间没有更新缓存相关的代码，看一下有没有什么循环引用之类的？目前Demo和我们其他项目测试是正常的。
