### ISSUE TITLE
HttpGetAsync在特殊情况下有线程Deadlock的现象

### ISSUE THREAD

**Issue by justwezzz** [JeffreySu/WeiXinMPSDK#403]
@JeffreySu 你好，又来骚扰你了！偶然发现HttpGetAsync在特殊情况下会发生await wc.DownloadStringTaskAsync(url)线程Deadlock无法返回。

环境：win10 iis webapi

现象：在循环里调用UserApi.InfoAsync导致线程锁死

操作步骤：
1.重启iis，使程序回到初始状态。

2.在webpai里我们尝试在一个循环里调用UserApi.InfoAsync接口，代码如下：
`for (int i = 0; i < 10; i++)
            {
                Senparc.Weixin.MP.AdvancedAPIs.UserApi.InfoAsync(appid,openid);
            }`

3.程序初始化后第一次调用UserApi.InfoAsync时触发了AccessTokenContainer机制，所以框架会先去调用GetAccessTokenResultAsync，调用GetAccessTokenResultAsync的时候会尝试先去加锁，然后加锁成功以后会去调用CommonApi.GetTokenAsync来获取accessToken，然而问题发生了，CommonApi.GetTokenAsync一直在等待没有返回。如下图：
![1](https://cloud.githubusercontent.com/assets/1901634/22812020/5a34dc1c-ef7d-11e6-9068-11c1a7f6f79e.png)
后来看了下Fiddler的记录，发现其实请求已经有Response了，但是CommonApi.GetTokenAsync还是一直在等待
![2](https://cloud.githubusercontent.com/assets/1901634/22812133/e992a2d6-ef7d-11e6-9ab8-1b92d14ee59b.png)
调试发现其实最底层是卡在HttpGetAsync这里
![3](https://cloud.githubusercontent.com/assets/1901634/22812166/1e7b8080-ef7e-11e6-8e12-d610973f516f.png)
然后锁就一直被这个GetTokenAsync操作给占用着，导致后面的请求都只能不停的去尝试获取锁导致cpu100%
![4](https://cloud.githubusercontent.com/assets/1901634/22812217/70f64b38-ef7e-11e6-8dec-d938ba9cbacc.png)

![5](https://cloud.githubusercontent.com/assets/1901634/22812214/6ae0b09e-ef7e-11e6-9cd5-54a6ce08bdf8.png)

我也尝试去搜索相关的现象，但是没有找到结果，所以只能提交到你这里了:(

**Comment by JeffreySu** [comment]
你的这个也是用的本地缓存吗？

**Comment by JeffreySu** [comment]
同样加了一个单元测试：https://github.com/JeffreySu/WeiXinMPSDK/blob/Developer/src/Senparc.Weixin.MP/Senparc.Weixin.MP.Test/CacheTests/CacheTests.cs#L40

**Comment by hentaicreep** [comment]
@JeffreySu 对，这个也用的本地缓存，在pull你的最新代码后，现象与#402类似，在50个并发的情况下是好的，但是在100个并发的情况下还是有问题。

**Comment by JeffreySu** [comment]
我试了200个线程，结果：
![image](https://cloud.githubusercontent.com/assets/2281927/22970995/21d94df4-f3af-11e6-9396-d29e5312d3b5.png)

**Comment by JeffreySu** [comment]
这个问题后来有新的进展吗？

**Comment by JeffreySu** [comment]
@justwezzz 这个问题后来有新的进展吗？

**Comment by justwezzz** [comment]
@JeffreySu 不好意思，离职一年多了，没关注这块的东西了😓

**Comment by JeffreySu** [comment]
@justwezzz 现在已经有新版本，目前没有发现死锁的问题，先关闭了。
