### ISSUE TITLE
更新最新的dll后，程序无法运行

### ISSUE THREAD

**Issue by xilin123** [JeffreySu/WeiXinMPSDK#413]
问题为：{"未能从程序集“Senparc.Weixin, Version=4.9.13.301, Culture=neutral, PublicKeyToken=null”中加载类型“Senparc.Weixin.Cache.IContainerCacheStragegy”。":"Senparc.Weixin.Cache.IContainerCacheStragegy"}
初步猜想是IContainerCacheStragegy问题，我从源代码中看到的是：IContainerCacheStrategy;这两个接口名称有一个字母的差别.

**Comment by JeffreySu** [comment]
比较有可能的是你其中一个dll不是最新的，Stragegy这个是拼写错误，在几个月前已经全局更正了。如果所有的dll都是最新版本的，应该不会有这个问题。

**Comment by xilin123** [comment]
我已经通过Nutget以及源代码重新编译试了N遍了，始终是同样的错误。哎！

**Comment by xilin123** [comment]
我一共就引用了连个dll,一个Senparc.Weixin，一个Senparc.Weixin.MP
是还需要引用其他的dll么？

**Comment by xilin123** [comment]
已经找到问题，确实有个地方没有更新，感谢你的帮助！
