### ISSUE TITLE
查询门店列表的方法PoiApi.GetPoiList返回的数据和官方相比太少，没有经纬度

### ISSUE THREAD

**Issue by zhou0818** [JeffreySu/WeiXinMPSDK#419]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：http://weixin.senparc.com/QA ***)

##### 问题描述
PoiApi.GetPoiList的返回值有缺失，最常用的经纬度没有，用微信官方的api试过，是有经纬度的

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [x] Senparc.Weixin.MP 版本：最新
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.OpenWx 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：

##### 模块对应的.net版本

- [ ] .net 3.5（已经暂停更新）
- [ ] .net 4.0（将于2017年7月停止更新）
- [x] .net 4.5
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [ ] Visual Studio 2017 RC
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

**Comment by JeffreySu** [comment]
感谢提交！
