### ISSUE TITLE
微信小程序，模板消息调用API的Url错误

### ISSUE THREAD

**Issue by zhoushengchaoerpla** [JeffreySu/WeiXinMPSDK#425]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：http://weixin.senparc.com/QA ***)

##### 问题描述
1.微信小程序，消息模板发送失败
调用的API错误，使用的是公众号的消息模板API
const string urlFormat = "https://api.weixin.qq.com/cgi-bin/message/template/send?access_token={0}";
实际：https://api.weixin.qq.com/cgi-bin/message/wxopen/template/send?access_token={0}

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [x] Senparc.Weixin.OpenWx 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：

##### 模块对应的.net版本

- [ ] .net 3.5（已经暂停更新）
- [ ] .net 4.0（将于2017年7月停止更新）
- [x] .net 4.5
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [x] Visual Studio 2013
- [ ] Visual Studio 2015
- [ ] Visual Studio 2017 RC
- [ ] 其他：

##### 缓存环境

- [ ] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

**Comment by JeffreySu** [comment]
确实有这个问题，非常感谢！已经更新 https://github.com/JeffreySu/WeiXinMPSDK/commit/044128ec365d5fa9e5932c6dbbb675200c43bab9
