### ISSUE TITLE
微信小程序模板消息发送，参数未显示在模板消息中，显示的内容为空

### ISSUE THREAD

**Issue by zhoushengchaoerpla** [JeffreySu/WeiXinMPSDK#432]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：http://weixin.senparc.com/QA ***)

##### 问题描述
微信模板消息，发送时，keywordX对应的字段没有赋值
例如：WxOpenTemplateMessage_PaySuccessNotice 
public string keyword1 { get; set; }
建议改为public TemplateDataItem keyword1 { get; set; }

TemplateDataItem是微信公众号模板消息的测试方法中使用的

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [x] Senparc.Weixin.OpenWx 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：

##### 模块对应的.net版本

- [ ] .net 3.5（已经暂停更新）
- [ ] .net 4.0（将于2017年7月停止更新）
- [x] .net 4.5
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [x] Visual Studio 2013
- [ ] Visual Studio 2015
- [ ] Visual Studio 2017 RC
- [ ] 其他：

##### 缓存环境

- [ ] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

**Comment by JeffreySu** [comment]
你的代码是怎么样的？下图是我们Demo的运行结果（到时候也会写入书里）：

![-mobile3](https://cloud.githubusercontent.com/assets/2281927/23369211/8fd75418-fd4b-11e6-9167-cc1367ffc9f4.png)

**Comment by zhoushengchaoerpla** [comment]
很抱歉，我看的是小程序测试项目（Senparc.Weixin.WxOpen.Tests）下面的模板消息测试发送的案例
![image](https://cloud.githubusercontent.com/assets/8053933/23441664/84208586-fe5e-11e6-9ba0-2c06336d2d7f.png)

**Comment by JeffreySu** [comment]
那就是没问题了，是吧？
