### ISSUE TITLE
未能创建 SSL/TLS 安全通道

### ISSUE THREAD

**Issue by andysjt** [JeffreySu/WeiXinMPSDK#455]
我在用咱们sdk的时候经常会碰到  “请求被中止: 未能创建 SSL/TLS 安全通道。”的错误，
在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
在 System.Net.WebClient.DownloadData(Uri address)
我在网上查了下解决方案：
https://community.jiguang.cn/t/c-ssl-tls/2168/5
不知道别人有没有碰到这个问题，或者咱们的WebClient能不能提取出来接口，我在外面做实现，感谢！

**Comment by JeffreySu** [comment]
具体是在哪个方法里面碰到的？SDK里面比较底层的方法应该已经考虑到这个了。

**Comment by andysjt** [comment]
message:请求被中止: 未能创建 SSL/TLS 安全通道。
fullMessage:System.Net.WebException: 请求被中止: 未能创建 SSL/TLS 安全通道。
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadString(Uri address)
   在 Senparc.Weixin.HttpUtility.Get.GetJson[T](String url, Encoding encoding, Nullable`1 maxJsonLength)
   在 Senparc.Weixin.MP.CommonAPIs.CommonApi.GetToken(String appid, String secret, String grant_type)
   在 Senparc.Weixin.MP.Containers.AccessTokenContainer.GetAccessTokenResult(String appId, Boolean getNewToken)
   在 Senparc.Weixin.MP.Containers.JsApiTicketContainer.GetJsApiTicketResult(String appId, Boolean getNewTicket)
   在 Senparc.Weixin.MP.Containers.JsApiTicketContainer.TryGetJsApiTicket(String appId, String appSecret, Boolean getNewTicket)
   在 DaLv.Web.Helper.Wx.WeiXinJsHelper.get_JsTicket()
   在 DaLv.Web.Helper.Wx.WeiXinJsHelper.get_Signature()

**Comment by andysjt** [comment]
还有个问题 企业支付接口，TenPayV3.Transfers  ，请问证书在哪里设置

**Comment by Messilimeng** [comment]
@andysjt 我也在用TenPayV3.Transfers 方法 可否加个qq 一起交流一下

**Comment by dushuaihua** [comment]
这个问题现在有解决方案吗， @JeffreySu 总？

**Comment by JeffreySu** [comment]
@andysjt @Messilimeng  最新的版本里面微信支付对于证书方面的依赖已经检查过了，应该都可用。

**Comment by JeffreySu** [comment]
@dushuaihua 看上去网络环境问题的可能性比较大，按照这个解决方案：http://www.cnblogs.com/liangss/p/5258605.html

增加的一行
```
System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
```

你可以自己加在外面试一下看看。

**Comment by Messilimeng** [comment]
是的 阿里雲 host 文件加個東西就好了
