### ISSUE TITLE
关于素材管理

### ISSUE THREAD

**Issue by xiaowx2010** [JeffreySu/WeiXinMPSDK#47]
现在微信给出的API中貌似没有素材管理这一块
而单单使用”上传下载多媒体文件“ 这个功能的话，就存在一个有效期的问题
如果每次用户发多媒体消息的话就重新上传一遍素材的话 感觉 这个方法又实在太笨了
不知道你们有没有什么好的办法解决这个问题吗 ?

**Comment by JeffreySu** [comment]
@mc7246 #2643  和这个 issue 有什么关联？
