### ISSUE TITLE
第三方平台component_verify_ticket 没有实时更新的bug？

### ISSUE THREAD

**Issue by pbzyy** [JeffreySu/WeiXinMPSDK#471]
推送component_verify_ticket,	出于安全考虑，在第三方平台创建审核通过后，微信服务器每隔10分钟会向第三方的消息接收地址推送一次component_verify_ticket，用于获取第三方平台接口调用凭据
目前存在这个问题。

**Comment by JeffreySu** [comment]
有的，你可以看一下Demo里面的做法：https://github.com/canknow/WeiXinMPSDK/blob/master/src/Senparc.Weixin.MP.Sample/Senparc.Weixin.MP.Sample/Global.asax.cs#L181

剩下的工作交给Controller和MessageHandler自动对接：https://github.com/JeffreySu/WeiXinMPSDK/blob/18d176edc3b6b93a6a7fb43d52a46a749dd00ae0/src/Senparc.Weixin.MP.Sample/Senparc.Weixin.MP.Sample/Controllers/Open/OpenController.cs#L112

**Comment by pbzyy** [comment]
谢谢提醒，看到代码就懂了。我开始的问题是：部署在一台机器上没有问题，分布式部署问题就出来了。

**Comment by JeffreySu** [comment]
嗯，Sample只是提供了一个简单的思路，如果是分布式，可以储存在共享的数据库（包括Redis），或者共享的文件夹中。
