### ISSUE TITLE
获取微信回复内容接口中，缺失关键字回复内容信息reply_list_info，希望及时更新Nuget

### ISSUE THREAD

**Issue by tail00zhou** [JeffreySu/WeiXinMPSDK#472]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：http://weixin.senparc.com/QA ***)

##### 问题描述
Senparc.Weixin.MP.AdvancedAPIs.AutoReply
获取系统关键字回复内容序列化的时候缺少reply_list_info（回复内容）属性
微信接口：
![qq 20170318204718](https://cloud.githubusercontent.com/assets/26503801/24072119/9502d4c8-0c1c-11e7-8ae6-f22e41dba899.png)

SDK：
![qq 20170318204947](https://cloud.githubusercontent.com/assets/26503801/24072122/a72df20e-0c1c-11e7-91ec-70ac31f69f1a.png)

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [x] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.OpenWx 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：

##### 模块对应的.net版本

- [ ] .net 3.5（已经暂停更新）
- [ ] .net 4.0（将于2017年7月停止更新）
- [x] .net 4.5
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [x] Visual Studio 2013
- [ ] Visual Studio 2015
- [ ] Visual Studio 2017 RC
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

**Comment by tail00zhou** [comment]
谢谢 FrancisFYK

**Comment by JeffreySu** [comment]
@tail00zhou 感谢提交反馈！
