### ISSUE TITLE
如何正确返回空消息？

### ISSUE THREAD

**Issue by wuchao288** [JeffreySu/WeiXinMPSDK#474]
##### 问题描述
public override IResponseMessageBase DefaultResponseMessage(IRequestMessageBase requestMessage)
        {
          //var responseMessage = this.CreateResponseMessage<ResponseMessageText>();
            //responseMessage.Content = null;
            return requestMessage
                .CreateResponseMessage<ResponseMessageNoResponse>(); 
        }
上面两种返回方法都会提示：
**该公众号无法提供服务，请稍候再试。**
只有在Action里直接返回Content("")才不会有提示》。不知是Bug还是我程序有Bug？

所有文件都是最新版本，下载于nuget.
##### 发现问题的模块
- [X] Senparc.Weixin 版本：
- [X] Senparc.Weixin.MP 版本：
- [X] Senparc.Weixin.MP.MVC 版本：
##### 模块对应的.net版本
- [x] .net 4.5
##### 开发环境
- [X ] Visual Studio 2013
- [ ] Visual Studio 2015
##### 缓存环境
- [X] 服务器内存缓存（默认）

**Comment by JeffreySu** [comment]
如果不希望返回任何消息，可以直接 return null

**Comment by wuchao288** [comment]
当我在DefaultResponseMessage里返回null是还是提示“该公众号无法提供服务，请稍候再试。”

**Comment by JeffreySu** [comment]
是不是没有设置TextResponseMessage？
类似这样：
``` C#
base.TextResponseMessage = "success";
return null;
```

或者更新到Developer的最新MvcExtension.dll，然后直接：
``` C#
return new SuccessResponseMessage();
```
