### ISSUE TITLE
AddrSign签名方法可能有错误

### ISSUE THREAD

**Issue by JeffreySu** [JeffreySu/WeiXinMPSDK#475]
##### 问题描述

方法：
https://github.com/JeffreySu/WeiXinMPSDK/blob/2d98e84b6cfaad9c9d8befcb575c67444cd06a56/src/Senparc.Weixin.MP/Senparc.Weixin.MP/Helpers/JSSDK/JSSDKHelper.cs#L147

参考：
![image](https://cloud.githubusercontent.com/assets/2281927/24280232/f574d7ea-1089-11e7-9ed0-a30e797f1316.png)

需要调用网页授权的access_token

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [x] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.OpenWx 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：

##### 模块对应的.net版本

- [ ] .net 3.5（已经暂停更新）
- [x] .net 4.0（将于2017年7月停止更新）
- [x] .net 4.5
- [x] .net core

**Comment by JeffreySu** [comment]
还需要结合OAuth缓存进行处理

**Comment by pbzyy** [comment]
是错误的。有个参数大小写错了。需要JeffreySu修改下。

**Comment by JeffreySu** [comment]
大小写是指appId全部需要小写，是吧？@pbzyy

**Comment by pbzyy** [comment]
是的。还有accessTokens不是AccessTokenContainer.TryGetAccessToken(appId, appSecret)这样获取的。

**Comment by JeffreySu** [comment]
开放平台的授权账号accesstoken应该是：AuthorizerContainer.TryGetAuthorizerAccessToken()方法

**Comment by JeffreySu** [comment]
是的，我们目前已经有针对OAuth的Container，不过还需要优化一下。每个用户的AccessToken好像是不一样的？
