### ISSUE TITLE
CardApi.CardUpdate的问题:data format error hint

### ISSUE THREAD

**Issue by jiehanlin** [JeffreySu/WeiXinMPSDK#479]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：http://weixin.senparc.com/QA ***)

##### 问题描述
CardApi.CardUpdate时发生以下错误：
发生了 Senparc.Weixin.Exceptions.ErrorJsonResultException
  HResult=0x80131600
  Message=微信Post请求发生错误！错误代码：47001，说明：data format error hint: [_U0zEa0644e569] Error before ":0,"balance_url":null,"custom_field1":null,"custom_field2":null,"custom_field3":null,"custom_cell1":null,"backgrou...
  Source=Senparc.Weixin

看起来是"init_increase_bonus": 0,的问题。
是不是updatecard不能更新init_increase_bonus了？官方文档还有这个属性。
针对updateCard 生成的json是否应该忽略null值呢？

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [x] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.OpenWx 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：

##### 模块对应的.net版本

- [ ] .net 3.5（已经暂停更新）
- [ ] .net 4.0（将于2017年7月停止更新）
- [x] .net 4.5
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [x]  Visual Studio 2015
- [ ] Visual Studio 2017 RC
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

**Comment by JeffreySu** [comment]
SDK内部已经提供了忽略的方法，我们会跟踪看一下，感谢反馈！
