### ISSUE TITLE
建议这个类ApiHandlerWapper可以给我们扩展或者重写？因为第三方开放平台获取AccessToken的机制不一样？

### ISSUE THREAD

**Issue by pbzyy** [JeffreySu/WeiXinMPSDK#480]
建议这个类ApiHandlerWapper可以给我们扩展或者重写？因为第三方开放平台获取AccessToken的机制不一样？

**Comment by JeffreySu** [comment]
是的，已经有计划在扩展这个方法，我们到时候会直接提供一个解决方案，避免开发者需要自己写额外的实现代码。

目前的代码而言第三方的平台只要传入Authorizer的access_token就行了，Authorizer的信息已经使用第三方平台的Container管理起来了。

**Comment by pbzyy** [comment]
好的。谢谢！ @JeffreySu

**Comment by JeffreySu** [comment]
目前开放平台的授权账号accesstoken应该是：AuthorizerContainer.TryGetAuthorizerAccessToken()方法

**Comment by JeffreySu** [comment]
@pbzyy 之前提供的ApiHandlerWapperBase应该已经解决了这个问题。

https://github.com/JeffreySu/WeiXinMPSDK/blob/bcfe0ddf2fc12429a7a5e9a1c99f56ca415fb3bd/src/Senparc.Weixin/Senparc.Weixin/CommonAPIs/ApiHandlerWapper/ApiHandlerWapperBase.cs

**Comment by JeffreySu** [comment]
提了这么多很好的建议，欢迎早日成为我们Contributor 😄
