### ISSUE TITLE
JSSDKHelper.GetJsSdkUiPackage报Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by wuchao288** [JeffreySu/WeiXinMPSDK#490]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：http://weixin.senparc.com/QA ***)

##### 问题描述
JSSDKHelper.GetJsSdkUiPackage(TenPayV3Info.AppId, TenPayV3Info.AppSecret, Request.Url.AbsoluteUri);
当商户信息配置有误的时候会报Object reference not set to an instance of an object.希望可以明确抛出是哪种错误>

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：

**Comment by JeffreySu** [comment]
Object reference not set to an instance of an object 这个错误应该是没有办法跟踪到栈上的，一般是因为某一个变量为null，但是试图访问其下面的成员。本身GetJsSdkUiPackage这个方法是没有问题的。

建议：
1、给一下你实际的代码
2、通过调试跟踪一下参数的状态，看一下是哪一个参数为null了。

**Comment by wuchao288** [comment]
当我换另一个公众号的时候这里是没问题的。所以我怀疑是不是因为那个公众号(比如，认证已经过期)的问题导致在请求微信后台时返回了null的数据?

**Comment by JeffreySu** [comment]
不排除这种可能，你跟踪一下应该能找出原因。
