### ISSUE TITLE
群发 send_ignore_reprint字段没有添加，有转载判定的群发无法发送

### ISSUE THREAD

**Issue by wushancool** [JeffreySu/WeiXinMPSDK#492]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：http://weixin.senparc.com/QA ***)

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.OpenWx 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：

##### 模块对应的.net版本

- [ ] .net 3.5（已经暂停更新）
- [ ] .net 4.0（将于2017年7月停止更新）
- [x] .net 4.5
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [ ] Visual Studio 2017 RC
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

**Comment by JeffreySu** [comment]
已更新到14.3.140中，感谢反馈！https://github.com/JeffreySu/WeiXinMPSDK/pull/493/commits/87a23b44bfd235865e6ed9bbd2b98abc3af9e5e3

**Comment by wushancool** [comment]
使用openId进行群发也会有这个问题，为什么只修改了根据groupId群发，根据openId群发的没有添加呢？

**Comment by JeffreySu** [comment]
根据openid就不叫群发了吧？

**Comment by JeffreySu** [comment]
如果还有和官方文档不一致的欢迎Pull Request过来，成为Contributor。
