### ISSUE TITLE
FixWeixinBugWeixinResult 在第三方开放平台报错。

### ISSUE THREAD

**Issue by pbzyy** [JeffreySu/WeiXinMPSDK#503]
Senparc.Weixin.MP.MvcExtension
var textResponseMessag = _messageHandlerDocument.TextResponseMessage;
if (_messageHandlerDocument.TextResponseMessage != null)
{
          return _messageHandlerDocument.TextResponseMessage.Replace("\r\n", "\n");
 }

var textResponseMessag = _messageHandlerDocument.TextResponseMessage; 
这条语句可以去掉。

**Comment by pbzyy** [comment]
首先请注意，开发者在接收消息和事件时，都需要进行消息加解密（某些事件可能需要回复，回复时也需要先进行加密）。但是，通过API主动调用接口（包括调用客服消息接口发消息）时，不需要进行加密。

开放平台全网发布接入检测是，需要对消息体加密。
目前没有加密。需要提交开放平台全网发布接入检测加密代码吗？

**Comment by JeffreySu** [comment]
多余的代码已经去掉，下面的回复说的是和这个有关的事情吗？

**Comment by JeffreySu** [comment]
今天凌晨提交了Senparc.Weixin 的最新版本，对MessageHandler做了一些修改，你看一下是不是上面说的全网发布的加密问题已经解决了。

**Comment by JeffreySu** [comment]
@pbzyy 有测试过吗？

**Comment by pbzyy** [comment]
@JeffreySu  下午测试几个小时，好像没有过。不过我还没有调试是哪里的问题？

**Comment by pbzyy** [comment]
@JeffreySu  我比较了你增加的和删除的ThirdPartyMessageHandler,代码没有变化呀？你看看，你改了那个地方?

**Comment by pbzyy** [comment]
![image](https://cloud.githubusercontent.com/assets/4442711/24892061/7b541c92-1eac-11e7-8c33-a1b414418096.png)

**Comment by pbzyy** [comment]
![image](https://cloud.githubusercontent.com/assets/4442711/24892072/87ca2926-1eac-11e7-9b53-24010447c21e.png)

**Comment by pbzyy** [comment]
@JeffreySu 不知道是腾讯的文档有问题，还是哪里的问题？我改成对整个消息的加密。就通过认证了。！

**Comment by pbzyy** [comment]
![image](https://cloud.githubusercontent.com/assets/4442711/24892109/b3c1444c-1eac-11e7-964b-e88273c3c69a.png)

**Comment by pbzyy** [comment]
@JeffreySu 看我上面的代码。

**Comment by JeffreySu** [comment]
我修改的是Senparc.Weixin.MP里面的 TextResponseMessage ：https://github.com/JeffreySu/WeiXinMPSDK/commit/a1bfbdd1655500fa226696c53059b427bf95743f

我自己测试了一下应该是没有问题的，你看一下。

![image](https://cloud.githubusercontent.com/assets/2281927/24893401/07a88ab2-1eb6-11e7-94a0-f0b7b7c15609.png)

**Comment by pbzyy** [comment]
那我再试试看，是哪里出的问题。谢谢了！

**Comment by JeffreySu** [comment]
之前的TextResponseMessage 确实有一个问题，现在的可以了吗？

**Comment by pbzyy** [comment]
@JeffreySu 可以了
