### ISSUE TITLE
Senparc.Weixin.HttpUtility.Get  的下载方法有问题

### ISSUE THREAD

**Issue by thisXYH** [JeffreySu/WeiXinMPSDK#507]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：http://weixin.senparc.com/QA ***)

##### 问题描述

`
//这个方法的文件流一个个字节写并且没有关闭
  public static void Download(string url, Stream stream)
        {
            WebClient wc = new WebClient();
            var data = wc.DownloadData(url);
            foreach (var b in data)
            {
                stream.WriteByte(b);
            }
        }
//导致我程序中一获取二维码并且马上使用文件的时候文件占用，文件格式不对
//微信  错误代码 ：40113
//我的代码
FileStream fw = new FileStream(filePath, FileMode.Create);
                    QrCodeApi.ShowQrCode(qr.ticket, fw);
                    //上传二维码为永久素材,并且更新到数据库中, 并且返回
                    var media =  MediaApi.UploadForeverMedia(appId, filePath);
//建议代码修改成， 亲测有效成功解决问题
public static void Download(string url, Stream stream)
        {
            WebClient wc = new WebClient();
            var data = wc.DownloadData(url);
            stream.Write(data, 0, data.Length);
            stream.Flush();
            stream.Close();
        }
`
@suifengshiqu 

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：github和4.11.6

##### 模块对应的.net版本

- [x] .net 4.5
##### 开发环境

- [ ] Visual Studio 2015

**Comment by thisXYH** [comment]
```c#
//这个方法的文件流一个个字节写并且没有关闭
 public static void Download(string url, Stream stream) 
{ 
WebClient wc = new WebClient(); 
var data = wc.DownloadData(url); 
foreach (var b in data) {
 stream.WriteByte(b); 
} }
 //导致我程序中一获取二维码并且马上使用文件的时候文件占用，文件格式不对 
//微信 错误代码 ：40113 
//我的代码 
FileStream fw = new FileStream(filePath, FileMode.Create); 
QrCodeApi.ShowQrCode(qr.ticket, fw); 
//上传二维码为永久素材,并且更新到数据库中, 并且返回 
var media = MediaApi.UploadForeverMedia(appId, filePath); 
//建议代码修改成， 亲测有效成功解决问题 
public static void Download(string url, Stream stream) 
{ WebClient wc = new WebClient(); 
var data = wc.DownloadData(url); 
stream.Write(data, 0, data.Length); 
stream.Flush(); 
stream.Close();
 }
```

**Comment by JeffreySu** [comment]
方法本身没有问题，改成在里面关闭的做法是不对的，因为stream是外部传进来的，不应该在Download方法内部关闭。

正确的做法是你在外面关闭就行了：

``` C#
using(FileStream fw = new FileStream(filePath, FileMode.Create))
{
    QrCodeApi.ShowQrCode(qr.ticket, fw); 
    //其他代码
}
```
