### ISSUE TITLE
个性化的菜单的参数问题

### ISSUE THREAD

**Issue by pbzyy** [JeffreySu/WeiXinMPSDK#512]
创建个性化的菜单的参数应该为：MenuFull_ConditionalButtonGroup, 而不是 ConditionalButtonGroup 。

**Comment by JeffreySu** [comment]
有没有错误的测试用例？

**Comment by pbzyy** [comment]
这是个性化菜单的Json文件。
{
  "button": [
    {
      "sub_button": [
        {
          "key": "MillionGuide",
          "type": "click",
          "name": "我要参与"
        } 
        {
          "url": "http://demo.***.com/***",
          "type": "view",
          "name": "喵喵后台"
        }
      ],
      "name": "狂欢派送"
    }
  ],
  "matchrule": {
    "group_id":"12",
    "tag_id": "",
    "sex": "",
    "country": "",
    "province": "",
    "city": "",
    "client_platform_type": "",
    "language": ""
  }
}
个性化的Json文件只能序列化 MenuFull_ConditionalButtonGroup，如果序列化ConditionalButtonGroup ，调用腾讯的接口出错。

**Comment by JeffreySu** [comment]
你是直接写json的吗？我配合这个工具测试之前的方法是可以的：http://sdk.weixin.senparc.com/Menu

你可以看一下逻辑实现。

如果是直接JSON的我需要找时间单独测试一下。

**Comment by pbzyy** [comment]
MenuFull_ConditionalButtonGroup conditionalButtonGroup = JsonConvert.DeserializeObject<MenuFull_ConditionalButtonGroup>(adminMenuJson);
上面的Json只有序列化为MenuFull_ConditionalButtonGroup这个的时候，然后利用API调用才不会出错，
如果序列化为ConditionalButtonGroup，然后调用Api会出错，序列化后的对象子按钮不见了。

**Comment by JeffreySu** [comment]
其实这个MenuFull_ConditionalButtonGroup好像不是这么用的。。
