### ISSUE TITLE
群发接口SendGroupMessageByGroupId返回值缺少msg_data_id字段

### ISSUE THREAD

**Issue by oppoic** [JeffreySu/WeiXinMPSDK#513]
##### 问题描述
微信公众号官方群发消息返回值：
```
{
   "errcode":0,
   "errmsg":"send job submission success",
   "msg_id":34182, 
   "msg_data_id": 206227730
}
```
SDK封装的群发消息方法SendGroupMessageByGroupId返回值对象里只有msg_id：
```
public class SendResult : WxJsonResult
{
     public SendResult();
     public string msg_id { get; set; }
     public UploadMediaFileType type { get; set; }
}
```
没有微信接口后加的msg_data_id字段，这个字段在微信统计接口是必须的，请作者有空的时候更新下，谢谢！

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [x] Senparc.Weixin.MP 版本：14.3.139
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.OpenWx 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：

##### 模块对应的.net版本

- [ ] .net 3.5（已经暂停更新）
- [ ] .net 4.0（将于2017年7月停止更新）
- [x] .net 4.5
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [x] Visual Studio 2013
- [ ] Visual Studio 2015
- [ ] Visual Studio 2017 RC
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

**Comment by JeffreySu** [comment]
非常感谢！你那边方便Pull Request到Developer吗？可以做一个contributor :smile:

**Comment by oppoic** [comment]
@JeffreySu 修改代码并Pull Request到Developer分支，首次操作，请多指教。

**Comment by oppoic** [comment]
#516 已解决
