### ISSUE TITLE
memcached同步锁的问题

### ISSUE THREAD

**Issue by spadark** [JeffreySu/WeiXinMPSDK#517]
##### 问题描述
`
                    if (_cache.Get(key) != null)
                    {
                        return false;//已被别人锁住，没有取得锁
                    }
                    else
                    {
                        _cache.Store(StoreMode.Set, key, new object(), new TimeSpan(0, 0, 10));//创建锁
                        return true;//取得锁
                    }`

经单元测试发现, StoreMode 不应该使用Set, 这样会导致高并发下, 多个线程都重复获取到锁. 应该使用Add模式, 这样memcache会判断key是否存在. 

` if (_cache.Store(StoreMode.Add, key, new object(), new TimeSpan(0, 0, 10)))
                    {
                        return true;//取得锁
                    }
                    else
                    {
                        return false;//已被别人锁住，没有取得锁
                    }`

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.OpenWx 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：

##### 模块对应的.net版本

- [ ] .net 3.5（已经暂停更新）
- [ ] .net 4.0（将于2017年7月停止更新）
- [x] .net 4.5
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [ ] Visual Studio 2017 RC
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

**Comment by JeffreySu** [comment]
方便Pull Request到Developer分支里面吗？加入到Contributor里面来。

**Comment by JeffreySu** [comment]
已经修改，感谢！ https://github.com/JeffreySu/WeiXinMPSDK/pull/529/commits/d927b5e8730fab0608f6b2a2db2d56bedb78adc9
