### ISSUE TITLE
 公众号第三方平台的authorizer_refresh_token没有缓存？

### ISSUE THREAD

**Issue by pbzyy** [JeffreySu/WeiXinMPSDK#519]
authorizer_refresh_token：刷新令牌（在授权的公众号具备API权限时，才有此返回值），刷新令牌主要用于公众号第三方平台获取和刷新已授权用户的access_token，只会在授权时刻提供，请妥善保存。 一旦丢失，只能让用户重新授权，才能再次拿到新的刷新令牌？

目前sdk没有实现？

**Comment by JeffreySu** [comment]
有缓存的，当然如果你用Redis之类分布式缓存的话会更好。

**Comment by pbzyy** [comment]
应该是没有的。这个在授权的时候就必须缓存。应该是demo没写这块代码。

**Comment by JeffreySu** [comment]
Container里面有缓存的。

**Comment by pbzyy** [comment]
authorizer_refresh_token 只有在这个时候才能获取到，而且是唯一的入口。所以authorizer_refresh_token 必须在这个方法 OpenOAuthCallback(string auth_code, int expires_in, string appId) 里做缓存？
