### ISSUE TITLE
Senparc.Weixin.Helpers.EncryptHelper.GetSha1(String encypStr) 异常

### ISSUE THREAD

**Issue by hetaoos** [JeffreySu/WeiXinMPSDK#530]
##### 问题描述
从Nuget上更新到 Senparc.Weixin.dll 4.11.9 后，调用 `signature = JSSDKHelper.GetSignature(ticket, nonceStr, timestamp, url);` 报错，发现是 Senparc.Weixin.Helpers.EncryptHelper.GetSha1(String encypStr) 报出的错误：
![tim 20170420104219](https://cloud.githubusercontent.com/assets/1094462/25211123/2d7b2aa4-25b6-11e7-86c0-5784e8967389.png)

在NuGet包中，发现net461的版本和net45的文件版本，第三位不一致，不清楚是不是打包错误导致的：
net45的版本是：4.11.9.36181
net461的版本是：4.11.6.3
![2](https://cloud.githubusercontent.com/assets/1094462/25211201/9a1976c0-25b6-11e7-9b07-0cec41ef7203.png)

##### 发现问题的模块

- [x] Senparc.Weixin 版本：
- [x] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.OpenWx 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：

##### 模块对应的.net版本

- [ ] .net 3.5（已经暂停更新）
- [ ] .net 4.0（将于2017年7月停止更新）
- [ ] .net 4.5
- [x] .net 4.6.1
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

**Comment by lishewen** [comment]
4.11.6.3是我的netcore版本= =，能截下项目 依赖项的图么？

**Comment by lishewen** [comment]
不对，看源码这个不知道为什么被注释掉了，不是我的操作。。。
<img width="283" alt="_20170420105618" src="https://cloud.githubusercontent.com/assets/837067/25211514/215d4a8e-25b8-11e7-9417-136e57d15d78.png">

**Comment by hetaoos** [comment]
新建一个.net 4.6.1 的控制台程序，添加以下两个包的引用：
```xml
  <package id="Senparc.Weixin" version="4.11.9" targetFramework="net461" />
  <package id="Senparc.Weixin.MP" version="14.3.142" targetFramework="net461" />
```
在Main下增加一句代码：
```cs
    var s = Senparc.Weixin.Helpers.EncryptHelper.GetSha1("122");
```
执行起来就报错了。

**Comment by hetaoos** [comment]
@lishewen 我说为毛这个错误提示那么诡异，言简意赅，网上还找不到。。。

**Comment by lishewen** [comment]
先改用4.5吧，我一会看看再推个netcore版本过来

**Comment by HADB** [comment]
+1

An unhandled exception occurred while processing the request.

ArgumentException: 暂时不可用
Senparc.Weixin.Helpers.EncryptHelper.GetSha1(string encypStr) in EncryptHelper.cs, line 59

**Comment by JeffreySu** [comment]
@HADB 最新版本的呢？

**Comment by HADB** [comment]
@JeffreySu 经测试，nuget上最新版14.4.4已恢复正常。

**Comment by JeffreySu** [comment]
OK
