### ISSUE TITLE
JSSDKHelper.GetJsSdkUiPackage 报错，暂时不可用

### ISSUE THREAD

**Issue by jinghun1999** [JeffreySu/WeiXinMPSDK#532]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：http://weixin.senparc.com/QA ***)

##### 问题描述
暂时不可用

说明: 执行当前 Web 请求期间，出现未经处理的异常。请检查堆栈跟踪信息，以了解有关该错误以及代码中导致错误的出处的详细信息。 

异常详细信息: System.ArgumentException: 暂时不可用

源错误: 

```
行 41:             #endregion
行 42:             
行 43:             var jssdkUiPackage = JSSDKHelper.GetJsSdkUiPackage(appId, secret, Request.Url.AbsoluteUri);
行 44:             //ViewData["JsSdkUiPackage"] = jssdkUiPackage;
行 45:             //ViewData["AppId"] = appId;

```

##### 发现问题的模块

- [x] Senparc.Weixin 版本：4.11.6.3
- [x] Senparc.Weixin.MP 版本：14.3.139.4
- [x] Senparc.Weixin.MP.MVC 版本：4.3.0.36184
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.OpenWx 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：

##### 模块对应的.net版本

- [ ] .net 3.5（已经暂停更新）
- [ ] .net 4.0（将于2017年7月停止更新）
- [x] .net 4.5
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [x] Visual Studio 2013
- [ ] Visual Studio 2015
- [ ] Visual Studio 2017 RC
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

**Comment by JeffreySu** [comment]
你的.net版本是不是4.6.1的？那个版本对这个方法有一个暂时的屏蔽，master中的代码已经修复，nuget很快会发布。

**Comment by jinghun1999** [comment]
是的，
