### ISSUE TITLE
新建 Developer-FullDotNet分支

### ISSUE THREAD

**Issue by JeffreySu** [JeffreySu/WeiXinMPSDK#535]
此分支将合并当前的DotNet-Core分支及Developer，在一个项目中支持.net4.0/4.5/4.6.1/.net core 4个库，方便今后的生成和修改。

**Comment by JeffreySu** [comment]
@lishewen @John0King @FrancisFYK

**Comment by John0King** [comment]
请问在不删除重新fork 的情况下，怎么得到这个分支？

**Comment by JeffreySu** [comment]
直接checkout 到这个分支就行

**Comment by JeffreySu** [comment]
Senparc.Weixin.dll已经移植完成

**Comment by JeffreySu** [comment]
@John0King 
1、checkout 分支：Developer-FullDotNet
2、使用VS2017打开这个目录下的Senparc.Weixin.MP.Sample.vs2017.sln文件即可看到最新的合并进展：
https://github.com/JeffreySu/WeiXinMPSDK/tree/Developer-FullDotNet/src/Senparc.Weixin.MP.Sample.vs2017

**Comment by JeffreySu** [comment]
MP 基本移植过去了，发现一个很奇怪的问题，Senparc.Weixin三个版本都是正常编译，MP对standard1.6好像识别有点问题，只要在.netstandard1.6下面，很多命名空间就找不到，甚至不能引用.netstandard1.6的Senparc.Weixin。大家如果发现问题欢迎反馈，我也会继续跟进。

**Comment by John0King** [comment]
我刚刚从你这边的远程，迁出了 dev-fullDotnet 但是 怎么 没有全局的 sln文件

**Comment by John0King** [comment]
@JeffreySu   Senparc.WenXin 可以支持到 `netstandard1.3 ; net45`
配置如下：
```xml
<ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="10.0.1" />
    <PackageReference Include="System.Xml.XmlSerializer" Version="4.3.0" />
  </ItemGroup>
  
  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard1.3'">
    <PackageReference Include="System.Reflection.TypeExtensions" Version="4.3.0" />
    <PackageReference Include="System.Threading.Thread" Version="4.3.0" />
  </ItemGroup>
<ItemGroup Condition=" '$(TargetFramework)' == 'net45' ">
    <Reference Include="System.Runtime.Serialization" />
    <Reference Include="System.Web" />
    <Reference Include="System.Web.Extensions" />
    <Reference Include="System.Net.Http" />
  </ItemGroup>
```
本想降级到netstandard1.1 但是 System.Threading.Thread 和 System.Security.Cryptography.X509Certificates  这两个包低于 netstandard1.3不支持 

不过netstandard1.3 之后没有什么具体的好处了

另外一个问题， 我们有必要同时支持.net4.5 和.net 4.6.x 么？ 高版本的.net 应该直接能够兼容低版本的，所以我们只需要兼容 netstandard 和 .net 4.5 就够了吧 ， 当然如果能到netstandard1.1 级别，连.net4.5也需要了。（前提是我们把这些兼容的Api 放到另一个库里面（这个库分别编译就免不了）， 不管怎么样 现在里面 包含System.Web 的东西都应该拿出来）


> 只要在.netstandard1.6下面，很多命名空间就找不到
需要引用System.Net.Request 包 ，才能有 HttpWebRequest 并且 netStandard 支持里面的 async API

**Comment by JeffreySu** [comment]
@John0King 不好意思，我上面写错了，解决方案文件应该是：https://github.com/JeffreySu/WeiXinMPSDK/blob/Developer-FullDotNet/src/Senparc.Weixin.MP.Sample.vs2017/Senparc.Weixin.MP.Sample.vs2017.sln

另外你说的两个问题：
1、三个版本的问题在MvcExtension里面是存在的，其他地方确实差别不大。
2、netstandard1.3确实够用了，因为一开始 @lishewen 就用了1.6，所以移植暂时用了1.6，后面会考虑降级的。

这个分支暂时不会合并到主分支，我们先内测一下，目前已经完成移植的代码我全部重新理了一下，应该是稳定可用的（只要Senparc.Weixin.MP.Sample.vs2017.sln里面包含的都审查过了），如果发现什么问题可以及时沟通。

**Comment by lishewen** [comment]
@JeffreySu @John0King 降级1.3主要就是为了单DLL兼容更多库，但由于MVC和CoreMVC依赖的原因，而且现在Senparc.Weixin是多目标框架编译打包，本来这个包就已经可以兼容覆盖低版本的.net，这样降级的意义不大，我还是建议使用新版本，这样netcore分支可以同步asp.net core带来诸如依赖注入等更多新特性。正如目前Senparc.Weixin不会因为兼容.net 2.0而特意从4.5降下来一样

**Comment by JeffreySu** [comment]
@lishewen 根据观察，没错的话nuget应该是向下查找，不会向上吧？比如发布版本号是netstandard1.6，而客户是1.3，这样是匹配不了的，如果发布是1.3，客户用1.6是可以自动找到1.3的dll的。

**Comment by lishewen** [comment]
@JeffreySu 是你观察这样没错，但用1.3的人无非是想兼容net4.5而已，但是你的nupkg中已经打包有了net4.5，这样新建一个net4.5的项目在nuget引用Senparc.Weixin的包，匹配到的也只会是net4.5的dll，而并不会匹配1.3那个，所以1.3没有存在的必要了，除非你把net4.5在nupkg打包时候拿掉。不知道我这样是否能表达清楚

**Comment by lishewen** [comment]
而netcore 1.1底包用的就是1.6，强行向下兼容1.3，而损失原生底包的性能优势，这样也没多大意义。另外据说5月出netcore 2.0了，底包是netstandard 2.0，到时我的项目还是打算升，底包还是继续往上提的

**Comment by John0King** [comment]
@lishewen 1.3是.net 46级别,  netstandard 1.6到1.3降级的意义确实不大，但是根据 2.0标准，级别应该在1.4，  这个.netstandard.library   的版本并不是包的新旧，而是代表了可共享的api范围，json.net 用的1.0+1.3，ImageSharp用的1.1+1.3

然而这并不是重点，我想说的是  现在除了标准库，还有.net 45. .net46.1, 我们应该 只需要.net45  就好

**Comment by lishewen** [comment]
@John0King 你不用Core分支，直接用master分支就直接是4.0/4.5的了。至于你要在Full Framework中使用CoreMVC这种目前是很非主流的用法，由于目前他们主库还是有传统asp.net的依赖的，你的需求很难在4.5中照顾到，毕竟拿掉System.Web命名空间的提案我已经提了有一年多了。你想玩酷炫屌炸天的用法最好还是像我目前那样自己搭个TFS，CI他们的代码

**Comment by JeffreySu** [comment]
@lishewen 我倒是想到另外一个问题，如果代码里面是 `#if NET45`，跑的项目是4.6.1，这个 `#if NET45` 是不是永远不会命中，还是某些情况下会命中？

**Comment by lishewen** [comment]
永不命中，但条件编译符是可以用 && || 这种逻辑运算符的，所以也不用写多次

**Comment by JeffreySu** [comment]
哦，可能是我想错了，其实上面我说的情况可能是不存在的。比如上述的代码：
``` C#
#if NET45
using System.Web.Routing;
using System.Web.WebSockets;
#else
using Microsoft.AspNetCore.Http;
#endif
```
虽然编译的时候是NET45，生成的dll是包含在.net framework 4.5下面，如果客户端使用的是4.6.1，会降级区查找4.5，所以不必担心将来不可预知的版本号了，对吧？

**Comment by lishewen** [comment]
@JeffreySu 嗯，这个是的

**Comment by John0King** [comment]
@JeffreySu @lishewen   现在没问题是因为 .net 4.6.1 未实现 .netstandard 1.6 , 但在 tools 2.0 里面 .net standard 将实现 .netstandard 1.4 - 2.0   , 这会不会就会有问题

.NET Standard | 1.0 | 1.1 | 1.2 | 1.3 | 1.4 | 1.5 | 1.6 |2.0
-----------------|---|----|----|------|-----|-----|----|----
NET Core         |1.0  | 1.0| 1.0  | 1.0 |1.0 | 1.0  |1.0 |2.0
.NET Framework (with tooling 1.0)|4.5|4.5|4.5.1|4.6|4.6.1|4.6.2|vNext|4.6.1
.NET Framework (with tooling 2.0)|4.5|4.5|4.5.1|4.6|4.6.1|4.6.1|4.6.1|4.6.1
Mono             |4.6|4.6|4.6|4.6|4.6|4.6|4.6|vNext
