### ISSUE TITLE
更新之后微信支付签名失败

### ISSUE THREAD

**Issue by myccy8** [JeffreySu/WeiXinMPSDK#541]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：http://weixin.senparc.com/QA ***)

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [x] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.OpenWx 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：

##### 模块对应的.net版本

- [ ] .net 3.5（已经暂停更新）
- [ ] .net 4.0（将于2017年7月停止更新）
- [ ] .net 4.5
- [ ] .net 4.6.1
- [x] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [ ] Visual Studio 2017 RC
- [ ] 其他：

##### 缓存环境

- [ ] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

**Comment by lishewen** [comment]
我知道原因了 稍后推送代码

**Comment by JeffreySu** [comment]
Nuget已经发布14.4.4最新版。

**Comment by lishewen** [comment]
@JeffreySu 这次条件编译的修复在Senparc.Weixin中，并不在Senparc.Weixin.MP项目里面。。。

**Comment by JeffreySu** [comment]
看到了，谢谢提醒，已发布 🌹 
https://www.nuget.org/packages/Senparc.Weixin
