### ISSUE TITLE
目前是否支持创建自定义菜单时指定跳转小程序？

### ISSUE THREAD

**Issue by nextuntil** [JeffreySu/WeiXinMPSDK#544]
RT，之前的自定义菜单只有click/view两种类型。
目前微信后台已经支持配置打开小程序的菜单，Senparc的SDK有支持么？

**Comment by JeffreySu** [comment]
支持。

**Comment by JeffreySu** [comment]
我们的可视化工具里面也已经提供了对应选项。

**Comment by nextuntil** [comment]
3Q，已经看到啦，之前因为微信官方文档也没有及时更新所以未处理。

**Comment by JeffreySu** [comment]
👍

**Comment by JeffreySu** [comment]
据说二级菜单对于小程序的自持还没有添加，待测试。

**Comment by F2EVarMan** [comment]
请问现在二级菜单跳转小程序支持了么

**Comment by F2EVarMan** [comment]
更新失败：微信Post请求发生错误！错误代码：40027，说明：invalid sub button url size hint: [nonvra0198vr18]。使用接口：普通自定义菜单接口。 Type选择的小程序直接跳转，url没有填写。小程序AppId和pagepath都有填写。 如果设置成小程序直接跳转url应该填写成什么

**Comment by F2EVarMan** [comment]
二级菜单添加小程序跳转后提示“ 更新失败：微信Post请求发生错误！错误代码：40166，说明：invalid weapp appid hint: [EmGtPA0862vr19]。使用接口：普通自定义菜单接口。” appid 肯定是对的

**Comment by F2EVarMan** [comment]
![image](https://user-images.githubusercontent.com/10355060/32816690-07d95a80-c9f5-11e7-8df1-43a242777d61.png)
这两个id都是detailsurl

**Comment by JeffreySu** [comment]
@F2EVarMan 已经修正，之前没注意到这条回复，感谢！
