### ISSUE TITLE
ASP.NET CORE中，关于Request.Body的问题

### ISSUE THREAD

**Issue by xcshan** [JeffreySu/WeiXinMPSDK#546]
namespace Intelligear.Web.Controllers
{    
    public class WxController : Controller
    {
        AppConfig _config;        
        public WxController(IOptions<AppConfig> options)
        {
            _config = options.Value;                               
        }
        [HttpGet]
        [ActionName("Index")]
        public ActionResult Get(PostModel postModel, string echostr)
        {
            if (CallbackHandler.CheckSignature(postModel, _config))
            {
                return Content(echostr);
            }
            else
            {
                return Content($"请在微信公众平台 > 开发 > 基本配置 > 服务器配置 > URL（服务器地址）段落内配置此地址：{_config.WxCallbackUrl}");
            }
        }
        [HttpPost]
        [ActionName("Index")]
        public IActionResult Post(PostModel postModel)
        {           
            if (!CallbackHandler.CheckSignature(postModel, _config))
            {
                return new WeixinResult("错误");
            }
            postModel.Token = _config.WxToken;
            postModel.EncodingAESKey = _config.WxEncodingAESKey;
            postModel.AppId = _config.WxAppId;
            LogTool.Info(_config.WxToken + "," + _config.WxEncodingAESKey + "," + _config.WxAppId + "," + _config.WxMaxRecordCount);
           
            try
            {
                var messageHandler = new WxCustomMessageHandler(Request.Body, postModel, 10);
                messageHandler.OmitRepeatedMessage = true;
                messageHandler.Execute();
                return new WeixinResult(messageHandler);
            }
            catch (Exception ex)
            {
                LogTool.Info(ex.Message);
                return Content(ex.Message);
            }
        }
    }   
}
使用Response.Body作为输入流的时候报错，说没有这个方法

**Comment by lishewen** [comment]
```
			string body = new StreamReader(Request.Body).ReadToEnd();           // log body

			byte[] requestData = Encoding.UTF8.GetBytes(body);
			Stream inputstream = new MemoryStream(requestData);

			var messageHandler = new CustomMessageHandler(inputstream, postModel);//接收消息

			messageHandler.Execute();//执行微信处理过程
```
我是这样输入的，直接 Request.Body 的话，由于Controller有其他处理的干扰，流的指针不一定在初始位置上，直接用的话会有问题

**Comment by xcshan** [comment]
谢谢，果然通了，太谢谢了

**Comment by JeffreySu** [comment]
简化方法可以这样：
``` C#
            var inputStream = new MemoryStream();
            Request.Body.CopyTo(inputStream);

            var messageHandler = new CustomMessageHandler(inputStream, postModel, maxRecordCount);
```
这个问题目测可能和Stream的异步读入有关，Request.Body一旦被当做参数传递，可能会造成stream中断传输。还没有测试如果将MessageHandler做成异步是否可以直接解决这个问题。目前只是猜测。
