### ISSUE TITLE
企业付款时无法指定证书的问题

### ISSUE THREAD

**Issue by coolboy0821** [JeffreySu/WeiXinMPSDK#549]
##### 问题描述
在企业付款接口中
Senparc.Weixin.MP.TenPayLibV3.TenPayV3.Transfers(TenPayV3TransfersRequestData dataInfo, int timeOut = Config.TIME_OUT)
并未提供设置证书的参数或方法，导致无法付款，望修复，谢谢

##### 发现问题的模块
- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：

当前时刻Github上NET4.0分支的最新版。

##### 模块对应的.net版本
- [ ] .net 4.0（将于2017年7月停止更新）

##### 开发环境
- [√ ] Visual Studio 2015

**Comment by JeffreySu** [comment]
谢谢！我们会安排到下一个版本计划中。

**Comment by JeffreySu** [comment]
@coolboy0821 Developer的版本已经更新了，.net 4.5的，你是在用4.0的版本？

**Comment by coolboy0821** [comment]
@JeffreySu  对，项目里用的是4.0的版本。。。。

**Comment by coolboy0821** [comment]
不知4.0分支有没有merge这个更新呢？？

**Comment by JeffreySu** [comment]
现在重点在弄.net core的版本，精力有限，4.0我们暂时停止更新了，欢迎大家来推送。只要合并Developer就行了。很长时间不合并可能会有一些冲突要处理。
