### ISSUE TITLE
iBeacon 添加设备到分组 

### ISSUE THREAD

**Issue by Messilimeng** [JeffreySu/WeiXinMPSDK#552]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：http://weixin.senparc.com/QA ***)

##### 问题描述
添加 ibeacon 设备到分组里报错 微信Post请求发生错误！错误代码：9001001，说明：json structure invalid.
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421141115&token=1888060707&lang=zh_CN

##### 发现问题的模块

- [x] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：

##### 模块对应的.net版本

- [ ] .net 3.5（已经暂停更新）
- [ ] .net 4.0（将于2017年7月停止更新）
- [x] .net 4.5
- [x] .net 4.6.1
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2017 RC
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

**Comment by JeffreySu** [comment]
上面的Url是JSSDK的，对应后端的接口具体是哪个？是这个吗： https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421141115&token=1888060707&lang=zh_CN

**Comment by Messilimeng** [comment]
![image](https://cloud.githubusercontent.com/assets/12272166/25843807/1e92a38a-34db-11e7-9619-68cfbbe13149.png)
@JeffreySu

**Comment by JeffreySu** [comment]
看了一下结构应该是对的，返回数据：
{
  "data": {
      "group_id" : 123,
      "group_name" : "test"
  },
  "errcode": 0,
  "errmsg": "success."
}

对应实体：
```
namespace Senparc.Weixin.MP.AdvancedAPIs
{
    /// <summary>
    /// 新增分组的返回结果
    /// </summary>
    public class GroupAddResultJson : WxJsonResult 
    {
        public GroupAdd_Data data { get; set; }

       
    }
    public class GroupAdd_Data
    {
        /// <summary>
        /// 分组唯一标识，全局唯一
        /// </summary>
        public string group_id { get; set; }
        /// <summary>
        /// 分组名 
        /// </summary>
        public string group_name { get; set; }

    }
}
```

**Comment by JeffreySu** [comment]
最新版本已经发布到nuget，可以了吗？

**Comment by Messilimeng** [comment]
@JeffreySu 还是不行

**Comment by JeffreySu** [comment]
跟踪一下实际发送的XML上来看看。
