### ISSUE TITLE
refresh_token 会定时刷新的吗

### ISSUE THREAD

**Issue by smilecoder** [JeffreySu/WeiXinMPSDK#561]
refresh_token 微信上有效期7天，30天，90天，但没有看见哪设置

sdk中refresh_token会定时刷新吗，发现用sdk 第三方平台长时间不访问，token会失效

var accessToken = AuthorizerContainer.GetAuthorizationInfo(AuthorizationWeiXin.Component_AppId, appId);

调用这个方法，返回了token,但去调使用报 “<font color=red>微信请求发生错误！错误代码：42001，说明：access_token expired</font>”

![20170510170150](https://cloud.githubusercontent.com/assets/2402816/25891234/dcf81aea-35a2-11e7-901f-d305d12bbffc.png)

**Comment by JeffreySu** [comment]
我们写了一个AuthorizerTokenRefreshedFunc，是专门用来给刷新用的，触发的位置位于：AuthorizerContainer.TryUpdateAuthorizationInfo()，再往上游走是AuthorizerContainer.GetAuthorizationInfo()

**Comment by smilecoder** [comment]
refresh_token 存在过期，需要维护它吗，定时去刷新一次。

**Comment by smilecoder** [comment]
@JeffreySu refresh_token 存在过期，需要维护它吗，定时去刷新。

**Comment by JeffreySu** [comment]
我空了看一下，你有直接的建议吗？

**Comment by JeffreySu** [comment]
@smilecoder  目前没发现问题，先关闭了，如果有新的发现可以重新开 issue，感谢！
