### ISSUE TITLE
TenPayUtil 下的 BuildRandomStr 方法，连续调用返回随机数一样

### ISSUE THREAD

**Issue by hetaoos** [JeffreySu/WeiXinMPSDK#564]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：http://weixin.senparc.com/QA ***)

##### 问题描述

Random 的用法是错了，你们这样用，将使用系统时间戳作为随机种子，连续调用时，随机种子是一样的，所以产生的随机数也是一样的。

正确的用法是，定义一个class级别的静态 Random，
每次调用的时候 lock 下。
如：
```cs
        public class RandomTest
        {
            private static Random rnd = new Random();

            public string Fun()
            {
                int i;
                lock (rnd)
                    i = rnd.Next(100);
                
                //do something
            }
        }
```

GetNoncestr() 这个方法写得也挺差的，只有1000种情况。
用 Random 的 NextBytes 可以产生指定个随机字节。

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [x] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.OpenWx 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：

##### 模块对应的.net版本

- [ ] .net 3.5（已经暂停更新）
- [ ] .net 4.0（将于2017年7月停止更新）
- [x] .net 4.5
- [x] .net 4.6.1
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

**Comment by JeffreySu** [comment]
对的，这个类是腾讯提供的，还没注意到这个问题，谢谢反馈！

如果您这边已经有修改好的代码欢迎Pull Request，成为我们Contributor。

**Comment by JeffreySu** [comment]
已经发布了。
