### ISSUE TITLE
TemplateApi.SendTemplateMessage中data解析有误

### ISSUE THREAD

**Issue by zmrbak** [JeffreySu/WeiXinMPSDK#566]
String dat = "{﹨"first﹨":{﹨"value﹨":﹨"标题﹨",﹨"color﹨":﹨"#173177﹨"},﹨"orderMoneySum﹨":{﹨"value﹨":﹨"9.9﹨",﹨"color﹨":﹨"#173177﹨"},﹨"orderProductName﹨":{﹨"value﹨":﹨"9.9﹨",﹨"color﹨":﹨"#173177﹨"},﹨"Remark﹨":{﹨"value﹨":﹨"9.9﹨",﹨"color﹨":﹨"#173177﹨"}}";

SendTemplateMessageResult result2 = TemplateApi.SendTemplateMessage(accessToken, openId, templateId, url, dat);

**最后POST的字符串中data一项变成：**
"data":"{﹨"first﹨":{﹨"value﹨":﹨"标题﹨",﹨"color﹨":﹨"#173177﹨"},﹨"orderMoneySum﹨":{﹨"value﹨":﹨"9.9﹨",﹨"color﹨":﹨"#173177﹨"},﹨"orderProductName﹨":{﹨"value﹨":﹨"9.9﹨",﹨"color﹨":﹨"#173177﹨"},﹨"Remark﹨":{﹨"value﹨":﹨"9.9﹨",﹨"color﹨":﹨"#173177﹨"}}"

**腾讯提供的data格式为：**
 "data":{
                   "first": {
                       "value":"恭喜你购买成功！",
                       "color":"#173177"
                   },
                   "keynote1":{
                       "value":"巧克力",
                       "color":"#173177"
                   },
                   "keynote2": {
                       "value":"39.8元",
                       "color":"#173177"
                   },
                   "keynote3": {
                       "value":"2014年9月22日",
                       "color":"#173177"
                   },
                   "remark":{
                       "value":"欢迎再次购买！",
                       "color":"#173177"
                   }
           }

腾讯的页面：
https://mp.weixin.qq.com/wiki?action=doc&id=mp1433751277&t=0.8229012072808293

**_纠正方法：_**
data数据后面不用双引号，里面的引号也不用转义。

位置：
Senparc.Weixin.MP\AdvancedAPIs\TemplateMessage\TemplateApi.cs

2015-5-17早晨8点，下载的最新版本

(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：http://weixin.senparc.com/QA ***)

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [x] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.OpenWx 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：

##### 模块对应的.net版本

- [ ] .net 3.5（已经暂停更新）
- [ ] .net 4.0（将于2017年7月停止更新）
- [x] .net 4.5
- [x] .net 4.6.1
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [X ] Visual Studio 2015
- [ ] Visual Studio 2017 RC
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

**Comment by zmrbak** [comment]
腾讯的页面：
https://mp.weixin.qq.com/wiki?action=doc&id=mp1433751277&t=0.8229012072808293

**Comment by zmrbak** [comment]
2015-5-17早晨8点，下载的最新版本

**Comment by zmrbak** [comment]
"data":"{\"first\":{\"value\":\"标题\",\"color\":\"#173177\"},\"orderMoneySum\":{\"value\":\"9.9\",\"color\":\"#173177\"},\"orderProductName\":{\"value\":\"9.9\",\"color\":\"#173177\"},\"Remark\":{\"value\":\"9.9\",\"color\":\"#173177\"}}"

**Comment by zmrbak** [comment]
"data":"{﹨"first﹨":{﹨"value﹨":﹨"标题﹨",﹨"color﹨":﹨"#173177﹨"},﹨"orderMoneySum﹨":{﹨"value﹨":﹨"9.9﹨",﹨"color﹨":﹨"#173177﹨"},﹨"orderProductName﹨":{﹨"value﹨":﹨"9.9﹨",﹨"color﹨":﹨"#173177﹨"},﹨"Remark﹨":{﹨"value﹨":﹨"9.9﹨",﹨"color﹨":﹨"#173177﹨"}}"

发布这个页面的时候，网站上把我的转义符全删掉了。
使用程序生成的data数据是这个样子的。

**Comment by JeffreySu** [comment]
是不是你用法不对？这个data你穿匿名变量进去会自动序列化成json，不是直接传json字符串进去。

**Comment by zmrbak** [comment]
感谢版主这么及时的回复。终于让我补习了一下匿名变量。
原来不是Bug，是我的写法有错！

var dat = new
            {
                first = new
                {
                    value = "标题",
                    color = "#173177"
                },
                orderMoneySum=new
                {
                    value = "9.9",
                    color = "#173177"
                },
                orderProductName = new
                {
                    value = "orderProductName",
                    color = "#173177"
                },
                Remark = new
                {
                    value = "Remark",
                    color = "#173177"
                }
            };
传入匿名变量，调试通过！

感谢版主！！
