### ISSUE TITLE
微信开放平台，获取授权方的帐号基本信息接口，授权方开通业务功能字段新增一项

### ISSUE THREAD

**Issue by 554393109** [JeffreySu/WeiXinMPSDK#574]
##### 问题描述
微信开放平台
获取授权方的帐号基本信息接口
返回参数business_info添加新项（是否开通微信扫商品功能）business_info：open_scan

```
namespace Senparc.Weixin.Open.ComponentAPIs
{
    public class BusinessInfo
    {
        public BusinessInfo();

        public int open_card { get; set; }
        public int open_pay { get; set; }
        public int open_shake { get; set; }
        public int open_store { get; set; }

        **public int open_scan{ get; set; }**
    }
}
```

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [x] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.OpenWx 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：

##### 模块对应的.net版本

- [ ] .net 3.5（已经暂停更新）
- [ ] .net 4.0（将于2017年7月停止更新）
- [x] .net 4.5
- [x] .net 4.6.1
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [x] Visual Studio 2015
- [ ] Visual Studio 2017 RC
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

**Comment by JeffreySu** [comment]
已经更新到Developer，请看一下是否正确。

**Comment by JeffreySu** [comment]
https://github.com/JeffreySu/WeiXinMPSDK/commit/ad357ba082d9b048242e3c9589cec3eb0f032368

**Comment by 554393109** [comment]
正确

**Comment by JeffreySu** [comment]
谢谢！
