### ISSUE TITLE
卡券获取函数CardBatchGet 缺少参数

### ISSUE THREAD

**Issue by jianliulin** [JeffreySu/WeiXinMPSDK#577]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：http://weixin.senparc.com/QA ***)

##### 问题描述
以下 数据为CardBatchGet 接口官网的例子， 目前缺少了status_list参数
https://mp.weixin.qq.com/wiki
{
  "offset": 0,
  "count": 10, 
  "status_list": ["CARD_STATUS_VERIFY_OK", "CARD_STATUS_DISPATCH"]
}

##### 发现问题的模块

- [x] Senparc.Weixin 版本：4.12.1.0
- [x] Senparc.Weixin.MP 版本：14.4.4.0

##### 模块对应的.net版本

- [x] .net 4.5

##### 开发环境
- [x ] Visual Studio 2017

##### 缓存环境

- [X] 服务器内存缓存（默认）

**Comment by JeffreySu** [comment]
已经在Developer分支中添加，测试后会合并到master正式发布。谢谢！

如果您那边有Fork项目代码，可以修改后直接Pull Request到Developer分支，成为Contributor：https://github.com/JeffreySu/WeiXinMPSDK/graphs/contributors
