### ISSUE TITLE
第三方平台的小程序的接口还未实现

### ISSUE THREAD

**Issue by pbzyy** [JeffreySu/WeiXinMPSDK#584]
现在小程序这么火，希望新版本尽快完成第三方平台的小程序的接口（https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1489144594_DhNoV&token=0e6160153dcb2375e6237a5acb309a1ee45a0eca&lang=zh_CN），不知道是如何规划这块设计的。能否提供一下你的思路，我们可以一起完成这方面的开发，接口不多？

**Comment by JeffreySu** [comment]
已经在Open的下面创建了一个WxaAPIs文件夹，已经做了一个修改域名的接口，其他接口可以如法炮制，欢迎提交代码！

**Comment by JeffreySu** [comment]
@pbzyy 您那边还有计划推送剩下的代码吗？

**Comment by JeffreySu** [comment]
目前尚未实现的第三方功能：
 - [ ] 微信登录 https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1492585163_FtTNA&token=&lang=zh_CN

 - [ ] 小程序模板设置 https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1500465446_j4CgR&token=&lang=zh_CN

**Comment by JeffreySu** [comment]
已全部实现。
