### ISSUE TITLE
Senparc.Weixin.MP.AdvancedAPIs.CustomServiceApi.GetMsgList的方法中，没有对DateTime做类型转换

### ISSUE THREAD

**Issue by Albertzhg** [JeffreySu/WeiXinMPSDK#591]
这个是GetMsgList中data的处理
              var data = new
                {
                    starttime = **startTime**,
                    endtime = **endTime**,
                    msgid = msgId,
                    number = number
                };
这个是GetRecord中data的处理
                //组装发送消息
                var data = new
                {
                    starttime = DateTimeHelper.GetWeixinDateTime(startTime),
                    endtime = DateTimeHelper.GetWeixinDateTime(endTime),
                    pagesize = pageSize,
                    pageindex = pageIndex
                };

因为，我在使用下面代码的时候，总是报"查询参数不合法"错误。
            DateTime d1 = Convert.ToDateTime("2017-06-08 18:00:00");
            DateTime d2 = Convert.ToDateTime("2017-06-08 19:00:00");
            long val = 1;
            var history = CustomServiceApi.GetMsgList(AccessToken, d1, d2, val, 100);

**Comment by JeffreySu** [comment]
应该是GetMsgList的方法错了，谢谢提醒！
