### ISSUE TITLE
CardApi.CardDetailGet 反序列化的处理机制不合适

### ISSUE THREAD

**Issue by gwhzh21** [JeffreySu/WeiXinMPSDK#600]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：http://weixin.senparc.com/QA ***)

##### 问题描述
使用CardApi.CardDetailGet获取会员信息时,返回的结果对于原始返回:
"wx_activate": true,
            "custom_field1": {
                "name_type": "FIELD_NAME_TYPE_COUPON",
                "url": "xxx"            },
            "custom_field2": {},
解析成了
"custom_field1": {
                "name_type": 1,
                "url": "xxx"
            },
            "custom_field2": {
                "name_type": 0,
                "url": null
            },
同时,建议对"name_type"无法解析的情况下.原样输出.因为有可能存在原来的卡中就是存在此"name_type"错误的会员卡,这样会导致在同步卡的时候.报错,无法把正确的卡导入自己的系统.
我还以为是微信那么的问题.直到他们提供了返回的json给我.我才发现......

##### 发现问题的模块

- [ 4.11.9.36951] Senparc.Weixin 版本：
- [14.3.142.36952 ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.OpenWx 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：

##### 模块对应的.net版本

- [ ] .net 3.5（已经暂停更新）
- [ ] .net 4.0（将于2017年7月停止更新）
- [x] .net 4.5
- [x] .net 4.6.1
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [X ] Visual Studio 2015
- [ ] Visual Studio 2017 RC
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

**Comment by JeffreySu** [comment]
已经列入计划，感谢反馈！
