### ISSUE TITLE
SessionContainer 没有自动sessionBag 过期实现

### ISSUE THREAD

**Issue by yongjinc** [JeffreySu/WeiXinMPSDK#612]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：http://weixin.senparc.com/QA ***)

##### 问题描述

微信小程序session未做过期处理：SessionContainer 没有自动sessionBag 过期实现。
建议：在 Senparc.Weixin.WxOpen.Containers 添加 一个后台线程清理过期的sessionBag
以下是我的实现，请参考：

    /// <summary>
    /// 3rdSession容器
    /// </summary>
    public class SessionContainer : BaseContainer<SessionBag>
    {
        /// <summary>
        ///是否开启后台线程
        /// </summary>
        private static int theLock = 0;
        /// <summary>
        /// 挂起10秒
        /// </summary>
        private static int backgroundProcessorDelay = 10;
        /// <summary>
        /// 后台线程运行频率
        /// </summary>
        protected static int processExpiresFrequency = 6;
        /**
        * 后台线程运行迭代次数
        */
        private static int count = 0;
        /// <summary>
        /// session最大时间间隔（分）
        /// </summary>
        private static int maxInactiveInterval = 48 * 60;//两天
        static System.Diagnostics.Stopwatch stopwatch = new System.Diagnostics.Stopwatch();
        public static void backgroundProcess()
        {
            count = (count + 1) % processExpiresFrequency;
            if (count == 0 && Interlocked.CompareExchange(ref theLock, 2, 1) == 1)
            {
                processExpires();
                Interlocked.CompareExchange(ref theLock, 1, 2);
            }
        }

        public static void processExpires()
        {
            try
            {
                stopwatch.Start();
                foreach (var bag in GetAllItems())
                {
                    if (bag.ExpireTime < DateTime.Now)
                    {
                        Cache.RemoveFromCache(bag.Key);
                    }
                }
            }
            finally
            {
                stopwatch.Stop();
                long times = stopwatch.ElapsedTicks;
                stopwatch.Reset();
            }
        }
        /// <summary>
        /// 获取最新的过期时间
        /// </summary>
        /// <returns></returns>
        private static DateTime GetExpireTime()
        {
            return DateTime.Now.AddMinutes(maxInactiveInterval);
        }

        #region 同步方法

        /// <summary>
        /// 获取Session
        /// </summary>
        /// <param name="key"></param>
        /// <returns></returns>
        public static SessionBag GetSession(string key)
        {
            var bag = TryGetItem(key);
            if (bag == null)
            {
                return null;
            }

            if (bag.ExpireTime < DateTime.Now)
            {
                //已经过期
                Cache.RemoveFromCache(key);
                return null;
            }

            using (FlushCache.CreateInstance())
            {
                bag.ExpireTime = GetExpireTime();//滚动过期时间
                Update(key, bag);
            }
            return bag;
        }
   
        /// <summary>
        /// 更新或插入SessionBag
        /// </summary>
        /// <param name="key">如果留空，则新建一条记录</param>
        /// <param name="openId">OpenId</param>
        /// <param name="sessionKey">SessionKey</param>
        /// <returns></returns>
        public static SessionBag UpdateSession(string key, string openId, string sessionKey)
        {
            if (Interlocked.CompareExchange(ref theLock, 1, 0) == 0)
            {
                Thread reporter = new Thread(() =>
                {

                    while (true)
                    {
                        try
                        {
                            // 每秒清理一次
                            Thread.Sleep(backgroundProcessorDelay * 1000);
                            backgroundProcess();
                        }
                        catch (Exception e)
                        {
                            //log。。。。。。
                        }
                    }
                });
                //设置为后台线程  
                reporter.IsBackground = true;

                reporter.Start();
            }

            key = key ?? SessionHelper.GetNewThirdSessionName();

            using (FlushCache.CreateInstance())
            {
                var sessionBag = new SessionBag()
                {
                    Key = key,
                    OpenId = openId,
                    SessionKey = sessionKey,
                    ExpireTime = GetExpireTime()
                };
                Update(key, sessionBag);
                return sessionBag;
            }
        }

        #endregion

    }

##### 发现问题的模块

- [ ] Senparc.Weixin.OpenWx 版本：

**Comment by JeffreySu** [comment]
现在的缓存策略过期其实是没有升级上去，其实这类数据过期处理直接利用缓存的过期时间是不是更妥？

**Comment by yongjinc** [comment]
嗯，我上述代码就是比较缓存的过期时间，只是单独开一个线程跑（感觉 GetAllItems -->foreach-->比较-->remove，这不是一种好的方式），不知道有没有更好的方法。现在源码中Dictionary模拟cache只有惰性删除（取的时候检查是否过期），在微信小程序里面如果用openid当key可能还ok，但是sessionkey是随机生成的，如果数据累积量大的话，内存会溢出吧。。。，我觉得定时删除或者某种时间事件是必要的（redis和memcached）

**Comment by JeffreySu** [comment]
GetAllItems() 的代价其实是很大的，除了分布式缓存通讯开销，序列化也会有比较大的开销，最好不要一直访问。
redis作者答复很明确，不能在HashSet中添加过期时间，所以至少目前在Reids里面做过期会比较麻烦，其他缓存我觉得还是在缓存层面做更轻松。

**Comment by yongjinc** [comment]
今天看了http://www.cnblogs.com/java-zhao/p/5205771.html，Redis采用的过期策略：惰性删除+定期删除（对指定个数个库的每一个库 · 随机· 删除小于等于指定个数个过期key）。这样子会不会好点：
if（原子操作判断是否执行clear操作）｛
  var removeDic = DictionaryCache.Where(t => t.Value.ExpireTime < DateTime.Now).Take(指定个数);
DictionaryCache -删除-removeDic.keys
｝

**Comment by JeffreySu** [comment]
定期删除我觉得是可行的，可以在key里面把时间记录进去，夜深人静的时候，做一次遍历，干掉过期的

**Comment by yongjinc** [comment]
Microsoft 开源的caching 用的是并发字典ConcurrentDictionary，处理清除缓存也是用线程跑的在缓存操作过程中根据某个时间频率触发【https://github.com/aspnet/Caching】 Microsoft.Extensions.Caching.Memory/MemoryCache：
        // Called by multiple actions to see how long it's been since we last checked for expired items.
        // If sufficient time has elapsed then a scan is initiated on a background task.
        private void StartScanForExpiredItems()
        {
            var now = _clock.UtcNow;
            if (_expirationScanFrequency < now - _lastExpirationScan)
            {
                _lastExpirationScan = now;
                Task.Factory.StartNew(state => ScanForExpiredItems((MemoryCache)state), this,
                    CancellationToken.None, TaskCreationOptions.DenyChildAttach, TaskScheduler.Default);
            }
        }

        private static void ScanForExpiredItems(MemoryCache cache)
        {
            var now = cache._clock.UtcNow;
            foreach (var entry in cache._entries.Values)
            {
                if (entry.CheckExpired(now))
                {
                    cache.RemoveEntry(entry);
                }
            }
        }

**Comment by JeffreySu** [comment]
这种内存型的缓存很好处理的，如果是需要序列化的缓存，尤其还在分布式的情况下，这种遍历的成本相比之下是相当大的。

**Comment by JeffreySu** [comment]
现在SessionBag默认已经有过期时间：

https://github.com/JeffreySu/WeiXinMPSDK/blob/3b5713e245951c6d7c4eb6223bab2c88e8eee397/src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/Containers/SessionContainer.cs#L145

感谢讨论。

**Comment by lujiazhu** [comment]
更新缓存时候自定义的过期时间，会被GetSession里的滚动过期时间覆盖成默认的5天。
