### ISSUE TITLE
有没有计划开发个人微信号的接口呢

### ISSUE THREAD

**Issue by yajiya** [JeffreySu/WeiXinMPSDK#618]
有时候需要类似于机器人的程序。是个人微信号。看其他语言有实现的，实现方式是抓web微信的包，分析出来协议。所以请问这个项目有没有支持个人微信号的计划呢？

类似以下这样类库
[wxBot](https://github.com/liuwons/wxBot)
[wechat4u](https://github.com/nodeWechat/wechat4u)

**Comment by JeffreySu** [comment]
暂时没有具体的开发和开源计划，之前我们内部其实已经准备了一套爬行的基础框架了，业务层面的还没开始做。
