### ISSUE TITLE
Senparc.Weixin.MP.TenPayLibV3.GetNoncestr超过了微信的32个字符长度限制

### ISSUE THREAD

**Issue by KevinDai** [JeffreySu/WeiXinMPSDK#621]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：http://weixin.senparc.com/QA ***)

##### 发现问题的模块

- [ ] Senparc.Weixin.MP 版本：

##### 模块对应的.net版本

- [ ] .net 3.5（已经暂停更新）
- [ ] .net 4.0（将于2017年7月停止更新）
- [x] .net 4.5
- [x] .net 4.6.1
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [ ] Visual Studio 2017 RC
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

Senparc.Weixin.MP.TenPayLibV3.GetNoncestr超过了微信的32个字符长度限制

随机字符串	nonceStr	是	String(32)	随机字符串，不长于32位。推荐随机数生成算法

**Comment by KevinDai** [comment]
弄错问题了，是因为TenPayV3UnifiedorderRequestData 属性的set方法没有执行           PackageRequestHandler.SetParameter("nonce_str", this.NonceStr);         ，只能在构造函数里面指定参数，建议是否去掉属性的set，或者补全，否则使用的时候很容易搞错

**Comment by JeffreySu** [comment]
这个建议很好。其实这些属性目前是预留的，实际上做成私有的也没有问题，RequestHandler这个类也是微信官方提供的，一直想找时间优化掉 🙃

**Comment by JeffreySu** [comment]
Thanks
