### ISSUE TITLE
TenPayV3MicroPayRequestData.cs 缺少sub_mch_id 导致服务商的刷卡支付失败

### ISSUE THREAD

**Issue by gzthomasliang** [JeffreySu/WeiXinMPSDK#629]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：http://weixin.senparc.com/QA ***)

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [x] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.OpenWx 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：

##### 模块对应的.net版本

- [ ] .net 3.5（已经暂停更新）
- [ ] .net 4.0（将于2017年7月停止更新）
- [x] .net 4.5
- [x] .net 4.6.1
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [x] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

文件如下
WeiXinMPSDK/src/Senparc.Weixin.MP/Senparc.Weixin.MP/TenPayLibV3/TenPayV3/TenPayV3MicroPayRequestData.cs

因缺省字段sub_mch_id，在使用刷卡支付时候，提示错误如下：

{<xml>
  <return_code><![CDATA[FAIL]]></return_code>
  <return_msg><![CDATA[受理机构必须传入sub_mch_id]]></return_msg>
</xml>}

**Comment by JeffreySu** [comment]
谢谢反馈！服务商的接口是完全包含普通商户接口的吗？

**Comment by gzthomasliang** [comment]
对subappid也少了，但实际项目中这个参数不是必须。建议排查：刷卡支付、公众号H5支付、二维码支付等涉及统一下单接口的模块。

**Comment by JeffreySu** [comment]
整体看了一下，现在微信支付几个版本确实有点乱，正在考虑单独拿出一个模块来

**Comment by pbzyy** [comment]
https://pay.weixin.qq.com/wiki/doc/api/tools/cash_coupon_sl.php?chapter=13_4&index=3
服务商的接口是完全包含普通商户接口的！ @JeffreySu

**Comment by JeffreySu** [comment]
@pbzyy 之前好像有看到不兼容的情况，是官方有这么说的？

**Comment by gzthomasliang** [comment]
@JeffreySu 升级到V16,问题还没解决啊。新版的文件如下

**Comment by JeffreySu** [comment]
@gzthomasliang  收到，因为提了问题没有收到回复，被盖下去了，我会继续跟进。

**Comment by gzthomasliang** [comment]
@JeffreySu 好的，应该可以。什么时候发布？我用实际的项目测试看看

**Comment by JeffreySu** [comment]
@gzthomasliang 这个已经上线有一段时间了，可以从nuget直接安装。

**Comment by gzthomasliang** [comment]
实测使用TenPayV3MicroPayRequestData_ServiceProvider可以正常服务商的支付，谢谢！
