### ISSUE TITLE
上传文件的方法不能用了

### ISSUE THREAD

**Issue by harrisonsu** [JeffreySu/WeiXinMPSDK#63]
我昨天下载的最新版本，目前需要用到下面方法上传文件到微信服务器并获得media_id

UploadMediaFile

我打开源文件，里面上传的路径好像已经不是最新的了，目前的是：

http://api.weixin.qq.com/cgi-bin/media/upload?access_token={0}&type={1}&filename={2}&filelength={3}

在微信测试平台使用发现最新的url已经在最开始的api.weixin.qq.com之前加了file，就是说最新的变成了：
http://file.api.weixin.qq.com/xxxxx 剩下的部分一样。但是好像没有filename和filelength这2个参数了，现在是post的方式。

但是当我修改url之后也无法上传图片，返回错误是：
微信Post请求发生错误！错误代码：41005，说明：media data missing

我上传的代码是：

string accessToken =AccessTokenContainer.TryGetToken(appId, appSecret);

string img = @"d:/logo.jpg";

UploadMediaFileResult result = CommonApi.UploadMediaFile(accessToken, UploadMediaFileType.image, img);

首先access token肯定正确，权限也都有， 图片的路径也正确，就是当执行这个方法的时候报错。

请查证。

谢谢。

**Comment by TYSZCC** [comment]
您好，上传文件的方法请使用AdvancedAPIs.Media.Upload，您使用的UploadMediaFile已经过期了，已处理，感谢您的反馈。
