### ISSUE TITLE
Senparc.Weixin.QY里有没有主动发消息的接口

### ISSUE THREAD

**Issue by zariczhu** [JeffreySu/WeiXinMPSDK#638]
请问Senparc.Weixin.QY里有没有主动发消息的接口？

**Comment by zariczhu** [comment]
看到了，在这里 https://github.com/JeffreySu/WeiXinMPSDK/blob/master/src/Senparc.Weixin.QY/Senparc.Weixin.QY/AdvancedAPIs/Mass/MassApi.cs

**Comment by JeffreySu** [comment]
此接口今天有更新，请注意同步。
