### ISSUE TITLE
群发消息错误 system error

### ISSUE THREAD

**Issue by magicdict** [JeffreySu/WeiXinMPSDK#64]
群发消息错误 system error
SendTextGroupMessageByOpenId 可以正确提交，
SendTextGroupMessageByGroupId一直返回 system error
不知道是微信系统的问题，还是文档的问题

**Comment by TYSZCC** [comment]
您好，请问您在调用SendTextGroupMessageByGroupId接口时传了哪些参数？我测试下来是可以正常发送消息的。

**Comment by dusdong** [comment]
我也遇到了这个问题

**Comment by TYSZCC** [comment]
1、使用is_to_all为true且成功群发，会使得此次群发进入历史消息列表。
2、为防止异常，认证订阅号在一天内，只能使用is_to_all为true进行群发一次，或者在公众平台官网群发（不管本次群发是对全体还是对某个分组）一次。以避免一天内有2条群发进入历史消息列表。
3、类似地，服务号在一个月内，使用is_to_all为true群发的次数，加上公众平台官网群发（不管本次群发是对全体还是对某个分组）的次数，最多只能是4次。
4、设置is_to_all为false时是可以多次群发的，但每个用户只会收到最多4条，且这些群发不会进入历史消息列表。

您在测试群发的时候是不是超过了这些限制？

**Comment by dusdong** [comment]
我又试了下，我在测试号上发送还是返回-1；在正式号上成功了。难道是测试号的问题？我再试试，谢谢啦！
