### ISSUE TITLE
Senparc.Weixin.QY模块发送消息缺少Token

### ISSUE THREAD

**Issue by sharp-summit** [JeffreySu/WeiXinMPSDK#648]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：http://weixin.senparc.com/QA ***)

##### 问题描述
今天刚刚更新Senparc.Weixin.QY模块4.3.5,发送文本消息报Access_Token无效  
这个Token我fiddler测试请求企业微信其他接口都正常获取数据,也可以发送消息  
但通过Senparc.Weixin.QY.AdvancedAPIs调用SendText就报错.
昨天用的4.3.3版本还是正常的.

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [x] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.OpenWx 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：

##### 模块对应的.net版本

- [ ] .net 3.5（已经暂停更新）
- [ ] .net 4.0（将于2017年7月停止更新）
- [x] .net 4.5
- [x] .net 4.6.1
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017 RC
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

**Comment by JeffreySu** [comment]
具体的错误信息是什么？

**Comment by sharp-summit** [comment]
@JeffreySu  
- 异常抛出的信息为  
  - 详细信息  
       -  微信Post请求发生错误！错误代码：40014，说明：invalid access_token   
  - 请求的url为  
    -  https://qyapi.weixin.qq.com/cgi-bin/message/send?access_token={0}  
  - JsonResult信息为  
    - 微信Post请求发生错误！错误代码：40014，说明：invalid access_token

另外这个token我又重测了几次,手动发起请求是可以的正常发送消息的

**Comment by JeffreySu** [comment]
这个接口逻辑应该没有修改过，你再多各种条件综合测试一下看看，是否还有别的原因？

**Comment by sharp-summit** [comment]
@JeffreySu 
我反编译查看了nuget下载的4.3.5的QY模块  
access_token代码里是硬编码为null  
```
return CommonJsonSend.Send<MassResult>(null, "https://qyapi.weixin.qq.com/cgi-bin/message/send?access_token={0}", <>f__AnonymousType, 1, timeOut, false, jsonSetting);
```

**Comment by sharp-summit** [comment]
@JeffreySu  苏先生 QY模块是不再同步更新了吗?    -_-!

**Comment by lishewen** [comment]
这个问题我不是在#642中提交修复了么=.=

**Comment by sharp-summit** [comment]
@lishewen  en ,已经看到,正在着手升级到Work.

**Comment by JeffreySu** [comment]
我看了下源码应该是对的
![image](https://user-images.githubusercontent.com/2281927/28060141-f4c146e2-6658-11e7-9051-54bd4f26abf5.png)

**Comment by sharp-summit** [comment]
我是今天下午更新了所有的模块,我反编译的dll是Nuget更新后的Senparc.Weixin.QY.dll  
版本是4.3.5.0  
所以是不是nuget那边没同步更新的问题  
我现在升级到了Work 已经可以正常发送了 感谢回复.  :)

**Comment by zariczhu** [comment]
我也遇到同样的问题，Senparc.Weixin.QY.dll 4.3.5.
微信Post请求发生错误！错误代码：40014，说明：invalid access_token
4.3.3版本是正常的，请问Senparc.Weixin.QY.dll 还会修改吗？

**Comment by sharp-summit** [comment]
@zariczhu   
github代码是对的,nuget的qy模块没更新  
安全起见还把QY升级到Work吧  
Work是针对企业微信新封装的模块,以后企业微信会注重更新这个模块  
与之前QY模块里代码基本兼容,调整下命名空间就行.

**Comment by JeffreySu** [comment]
@sharp-summit @zariczhu Work是从QY升级过去的，兼容QY，尽量以Work为准。QY会逐步停止更新，官方也已经停止更新了。

**Comment by sharp-summit** [comment]
@JeffreySu  接着反馈一个问题 Work模块 版本0.3   
有部分方法依然发送请求时access_token为null,检查了下github上的同名方法代码也是错误的,如图  
**Senparc.Weixin.Work.AdvancedAPIs.MailListApi**  

![k _ 5t cn29c tgiuxhyzg0](https://user-images.githubusercontent.com/16459753/28237356-db475a70-696f-11e7-963c-9610d7108d08.png)

![image](https://user-images.githubusercontent.com/16459753/28237359-ed5f09ba-696f-11e7-8334-7d09c86da67e.png)

**Comment by JeffreySu** [comment]
是的，QY改了，Work还没改，你那边如果方便的话可以直接修改完了提交到Developer分支

**Comment by sharp-summit** [comment]
@JeffreySu  pull request的时候还没注意到你消息,  
我直接pull到master项目了,可以重新提交吗?   
第一次用这个功能,尴尬了~  :)

**Comment by JeffreySu** [comment]
已经合并了Developer的项目，非常感谢！

**Comment by JeffreySu** [comment]
我们重新过一下并且修改新版本号之后会发布到master。
