### ISSUE TITLE
CardApi.CreateCard Card_MemberCardData 会员卡开卡相关资料不全

### ISSUE THREAD

**Issue by starpunk** [JeffreySu/WeiXinMPSDK#650]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：http://weixin.senparc.com/QA ***)

##### 问题描述
CardApi.CreateCard Card_MemberCardData 会员卡开卡相关资料不全
缺少
wx_activate_after_submit | 否 | bool | 是否支持跳转型一键激活，填true或lse
wx_activate_after_submit_url | 否 | bool | 跳转型一键激活跳转的地址链接，请填写http://或者https://开头的链接

参见微信文档
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1451025283

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：4.13.1.0
- [X ] Senparc.Weixin.MP 版本：14.5.0.0
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：2.3.0.30266
- [ ] Senparc.Weixin.QY 版本：4.1.12.30266
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.OpenWx 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：

##### 模块对应的.net版本

- [ ] .net 3.5（已经暂停更新）
- [ ] .net 4.0（将于2017年7月停止更新）
- [x] .net 4.5
- [x] .net 4.6.1
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ x] Visual Studio 2013
- [ ] Visual Studio 2015
- [ ] Visual Studio 2017 RC
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

**Comment by JeffreySu** [comment]
已经改好了，非常感谢！欢迎直接Pull Request到我们的Developer分支 😄

**Comment by starpunk** [comment]
貌似文档都是错的
wx_activate_after_submit_url  应该是string

**Comment by JeffreySu** [comment]
方便Pull Request吗？

**Comment by ulswww** [comment]
wx_activate_after_submit_url  确实应该是string

**Comment by JeffreySu** [comment]
@ulswww 👌  现在在代码里面的设置都是正确的对吧
