### ISSUE TITLE
关于“生成带参数的二维码”接口的问题

### ISSUE THREAD

**Issue by xuchangsoufang** [JeffreySu/WeiXinMPSDK#656]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：http://weixin.senparc.com/QA ***)

##### 问题描述

“Senparc.Weixin.MP”命名空间下的枚举类型“QrCode_ActionName”缺少一个值“QR_STR_SCENE”，即“临时的字符串参数值”。
微信公众平台开发文档中，关于“生成带参数的二维码”接口中“action_name”参数的说明：
二维码类型，QR_SCENE为临时的整型参数值，QR_STR_SCENE为临时的字符串参数值，QR_LIMIT_SCENE为永久的整型参数值，QR_LIMIT_STR_SCENE为永久的字符串参数值

##### 发现问题的模块

- [X] Senparc.Weixin.MP 版本：14.5.0.0

##### 模块对应的.net版本

- [X] .net 4.5

##### 开发环境

- [X] Visual Studio 2017

##### 缓存环境

- [X] 服务器内存缓存

**Comment by JeffreySu** [comment]
已经修改，请校验。
https://github.com/JeffreySu/WeiXinMPSDK/commit/6434e7e9f174020940143fea1bdb68426d822680
