### ISSUE TITLE
下载微信对账单报错

### ISSUE THREAD

**Issue by qdesk** [JeffreySu/WeiXinMPSDK#657]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：http://weixin.senparc.com/QA ***)

##### 问题描述
调用下载微信对账单时报错，显示“System.NullReferenceException”类型的异常在 Senparc.Weixin.MP.dll 中发生，但未在用户代码中进行处理
其他信息: 未将对象引用设置到对象的实例。
我看了下源码发现PackageRequestHandler为初始化为null， 修改源代码后还是报错
<xml><return_code>FAIL</return_code>
<return_msg>sign error</return_msg>
<error_code>CDATA[20001</error_code>
</xml>

##### 发现问题的模块

- [√ ] Senparc.Weixin 版本：4.13.1.18430
- [√ ] Senparc.Weixin.MP 版本：14.5.1.35427
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.OpenWx 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：

##### 模块对应的.net版本

- [ ] .net 3.5（已经暂停更新）
- [ ] .net 4.0（将于2017年7月停止更新）
- [x] .net 4.5
- [ ] .net 4.6.1
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ √] Visual Studio 2013
- [ ] Visual Studio 2015
- [ ] Visual Studio 2017 RC
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

**Comment by JeffreySu** [comment]
PackageRequestHandler确实缺少初始化，其他应该没有问题，稍微做了些修改，已经添加了Demo，测试结果正常。
代码见：https://github.com/JeffreySu/WeiXinMPSDK/blob/master/src/Senparc.Weixin.MP.Sample/Senparc.Weixin.MP.Sample/Controllers/TenPayV3Controller.cs#L579
