### ISSUE TITLE
企业号升级后, AccessToken的长度有300, 你的代码还是以64来判断的,判断有问题了,  public static bool IsAppId(string accessTokenOrAppId, PlatformType platFormType)

### ISSUE THREAD

**Issue by wenzhili** [JeffreySu/WeiXinMPSDK#668]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
/*
                 * 企业号（企业微信）AppKey：wx7618c00000000222@044ZI5s6-ACxpAuOcm4md410pZ460pQUmxO9hIoMd09kRaJ1iSqhPfmg3-aBFF7q
                 * 企业号（企业微信）AccessToken（length=64）：VJv9BwZtAuuWYWfbTQzefBvRRfBhuM6edMlpxTOm-vXrzyjeWPdgT8ft3vTHMbl2
                 */
                //return accessTokenOrAppId != null && accessTokenOrAppId.Length > 64;

##### 发现问题的模块
 
- [ ] Senparc.Weixin.MP 版本：

**Comment by JeffreySu** [comment]
已解决
