### ISSUE TITLE
公众号被动回复内容报错

### ISSUE THREAD

**Issue by gaofeng-gdpr** [JeffreySu/WeiXinMPSDK#674]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
在OnEvent_Card_Pass_CheckRequest中，公众号服务器有返回操作，但是收不到消息。查公众号运维日志：被动回复内容 
<!DOCTYPE html> <html> <head> <title>找不到方法:“Void Senparc.Weixin.Exceptions.WeixinException..ctor(System.String, System.Exception)”。</title> <meta name="viewport" content="width=device-width" /> <style> body {font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;} p {font-family:"Verdana";font-weight:normal;color:black;margin-top: -5px} b {font-family:"Verdana";font-weight:bold;color:black;margin-top: -5px} H1 { font-family:"Verdana";font-weight:normal;font-size:18pt;color:red } H2 { font-family:"Verdana";font-weight:normal;font-size:14pt;color:maroon } pre {font-family:"Consolas","Lucida Console",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt} .marker {font-weight: bold; color: black;text-decoration: none;} .version {color: gray;} .error {margin-bottom: 10px;} .expandable { text-decoration:underline; font-weight:bold; color:navy;

##### 发现问题的模块

- [ x] Senparc.Weixin 版本：4.12.5.0
- [ x] Senparc.Weixin.MP 版本：14.4.13.0
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经暂停更新）
- [ ] .net 4.0（将于2017年7月停止更新）
- [x] .net 4.5
- [x] .net 4.6.1
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [x ] Visual Studio 2015
- [ ] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

**Comment by JeffreySu** [comment]
应该是Senparc.Weixin.dll版本不是最新的。建议全部更新到最新版本。
