### ISSUE TITLE
JSSDKHelper.GetNoncestr() 不支持 net core1.1

### ISSUE THREAD

**Issue by onestar1** [JeffreySu/WeiXinMPSDK#675]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
net core 开发情况下： 调用 JSSDKHelper.GetNoncestr() 方法会报 936错误，
需要重写获取替换其他方法。
跟core的支持有关系。
我的core版本是1.1

##### 发现问题的模块

 
- [打勾 ] Senparc.Weixin.MP 版本：
 

##### 模块对应的.net版本

 
- [ ] .net core

##### 开发环境
 
- [ ] Visual Studio 2017
 

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

**Comment by lishewen** [comment]
这个bug在月初时候已经修复过了，更新一下版本吧

**Comment by onestar1** [comment]
ok
