### ISSUE TITLE
Senparc.Weixin.Config中的TIME_OUT默认10秒在消息群发时会引发超时

### ISSUE THREAD

**Issue by fsea** [JeffreySu/WeiXinMPSDK#68]
因为要上传图片，10秒超时显示太短了！
希望默认修改大一些，我修改为60秒才正常

**Comment by JeffreySu** [comment]
这个是常量的默认值，是提供给参数用的，不是最终统一的设置，例如：
``` C#
public static string HttpGet(string url, CookieContainer cookieContainer = null, Encoding encoding = null,int timeOut= Config.TIME_OUT)
```
您仍然可以在相关的方法里面去设置您所需要的。

**Comment by DoraemonYu** [comment]
o(∩_∩)o 嗨您们好。

Senparc.Weixin项目，RequestUtility的HttpGet、HttpPost，有看到方法是暴露Timeout参数（即2楼的内容，默认的参数常量，但仍然允许上一层调用时设置具体的数值）。
但是RequestUtility这两个方法的上一层，Senparc.Weixin.MP项目，Senparc.Weixin.MP.AdvancedAPIs相关的类，目前没提供Timeout参数供调用。
因此后续是否会考虑做调整呢？

很期待得到您们的回复。
