### ISSUE TITLE
目前“一次性订阅消息”订阅接口始终返回"errcode":48001,"errmsg":"api unauthorized，看似微信官方的问题

### ISSUE THREAD

**Issue by JeffreySu** [JeffreySu/WeiXinMPSDK#681]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
目前“一次性订阅消息”订阅接口始终返回"errcode":48001,"errmsg":"api unauthorized，看似微信官方的问题

##### 微信官方文档 URL
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1500374289_66bvB

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [x] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经暂停更新）
- [ ] .net 4.0（将于2017年7月停止更新）
- [x] .net 4.5
- [x] .net 4.6.1
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [X] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

**Comment by JeffreySu** [comment]
Sample测试：在微信内打开：https://sdk.weixin.senparc.com/SubscribeMsg

**Comment by lishewen** [comment]
貌似是Result那一步的问题，能弹出确认对话框 GetSubscribeMsgUrl 那一步应该是正常的

**Comment by JeffreySu** [comment]
微信官方的讨论区也在反映这个问题，应该是微信那边的问题，要不就是文档又错了。

**Comment by JeffreySu** [comment]
调用接口返回的是没有api权限

**Comment by lishewen** [comment]
![_20170726143458](https://user-images.githubusercontent.com/837067/28609406-24141a36-7217-11e7-91de-f242dc73108e.png)
我测试用的公众号的确没有那个权限，有权限的号目前方便进行调试，只能先关注下最新的状况

**Comment by JeffreySu** [comment]
只要通过认证即可，订阅号和服务号都能用。

**Comment by JeffreySu** [comment]
已经可以用了，代码需要更新一下，之前有一个另外的bug
