### ISSUE TITLE
微信上传媒体文件报错

### ISSUE THREAD

**Issue by shenlanchenwei** [JeffreySu/WeiXinMPSDK#688]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
上传微信媒体文件时POST基类会报错

具体错误行:  RequestUtility.cs 259行

hc.Headers.ContentType = new MediaTypeHeaderValue(string.Format("multipart/form-data; boundary={0}", boundary));

##### 发现问题的模块

- [x] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经暂停更新）
- [ ] .net 4.0（将于2017年7月停止更新）
- [] .net 4.5
- [] .net 4.6.1
- [x] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

**Comment by JeffreySu** [comment]
@lishewen 你们有碰到过这个问题吗？

**Comment by lishewen** [comment]
@JeffreySu 没有，我自己的项目中也没收到过这个的错误反馈，我晚上回去再具体测下
@shenlanchenwei 具体的错误提示是？

**Comment by shenlanchenwei** [comment]
![error](https://user-images.githubusercontent.com/6754634/28658395-af481154-72dd-11e7-8f68-4e0fe4b11d89.jpg)

**Comment by lishewen** [comment]
@shenlanchenwei 
把那句临时换成
```
            hc.Headers.Remove("Content-Type");
            hc.Headers.TryAddWithoutValidation("Content-Type", "multipart/form-data; boundary=" + boundary);
```
试试

**Comment by lishewen** [comment]
这个地方我还要看看现在是否需要 把 StreamContent 改写成 MultipartFormDataContent，更规范点

**Comment by shenlanchenwei** [comment]
@lishewen 这个我改了以后头没有报错了，但是上传这个还是有问题，我通过抓包发现文件流没有发送在Body里面，应该是代码有点问题

**Comment by lishewen** [comment]
这个方法的netcore移植是在RC版本中，放到现在已经有更好的解法了，不用再在raw流中拼接字符串了。
@shenlanchenwei 我写了个ConsoleApp测试过这个PR的上传文件，没有问题了的，如果你看到此回复时，@JeffreySu 还没来得及merge的话，你可以到我的分支下clone最新的代码试试

附测试代码截图
![_20170728090003](https://user-images.githubusercontent.com/837067/28698064-4e8313aa-7373-11e7-9dbc-814bd9eb4d0b.png)

**Comment by shenlanchenwei** [comment]
MediaApi.UploadForeverMedia(accessToken, locaFilePath);
临时素材上传还是有问题，应该是文件长传的name有问题，导致腾讯报错：
errcode":41005,"errmsg":"media data missing

**Comment by JeffreySu** [comment]
@shenlanchenwei  media data missing 只在name超长的时候发生？

**Comment by lishewen** [comment]
@shenlanchenwei 试试这个PR

**Comment by shenlanchenwei** [comment]
问题以解决，谢谢~~
