### ISSUE TITLE
International Official Account

### ISSUE THREAD

**Issue by leventeolahx** [JeffreySu/WeiXinMPSDK#697]
Hi,

Does the library support International Official Account?

Thank you.
Regards,
Levente

**Comment by JeffreySu** [comment]
Could you show me the Document URL?
I guess they have the same rules.

**Comment by leventeolahx** [comment]
This is what i found:
http://open.wechat.com/cgi-bin/newreadtemplate?t=overseas_open/faq&symbol=faqs-oa-technical

**Comment by JeffreySu** [comment]
Thank you!
I sampled some APIs, they have the same rules, but different domain name. I'll check more later.

For example:
China - https://api.weixin.qq.com/cgi-bin/menu/create?access_token=ACCESS_TOKEN
International - https://api.wechat.com/cgi-bin/menu/create?access_token=ACCESS_TOKEN

**Comment by JeffreySu** [comment]
It seems APIs for International Version is very similar.
Does there many developers need the International Official Account support?

**Comment by JeffreySu** [comment]
@leventeolahx can you leave me an Email address to www.jeffrey.su@gmail.com? We are planning to create the International Official Account SDK project, before that I have to study something about the OA in foreign countrise.

**Comment by leventeolahx** [comment]
@JeffreySu I sent you an email

**Comment by JeffreySu** [comment]
Thanks!

**Comment by JeffreySu** [comment]
@leventeolahx Now we add a property to define API domain name: `Senparc.Weixin.Config.ApiMpHost`, the default value is `https://api.weixin.qq.com`, which is for Chinese version. You can set it to `https://api.wechat.com`  while you want to use in International version.

In addition, the SDK is almost full-version for Chinese API,  International version API is subset in Chinese API. So when you using SDK in International API, you have to check the API whether available in International version.
International Official Documents: http://admin.wechat.com/wiki/index.php?title=Main_Page

**Comment by leventeolahx** [comment]
Thank you!
