### ISSUE TITLE
关于Senparc.Weixin.Config中的TIME_OUT的建议

### ISSUE THREAD

**Issue by DoraemonYu** [JeffreySu/WeiXinMPSDK#70]
o(∩_∩)o 嗨您们好。

Senparc.Weixin/Senparc.Weixin/Config 的 TIME_OUT 属性，
是否会考虑成外部调用时，允许修改？
目前使用SDK的过程中，发现在网络环境一般的场景里，10秒钟的超时时间，确实比较短。（特别是上传视频文件的时候，微信官方允许10MB以下。）

Senparc.Weixin项目，RequestUtility的HttpGet、HttpPost，有看到方法是暴露Timeout参数（Timeout是指定了参数常量，但仍然允许上一层调用时设置具体的数值）。

但是RequestUtility这两个方法的上一层，Senparc.Weixin.MP项目，Senparc.Weixin.MP.AdvancedAPIs相关的类，目前没提供Timeout参数供调用。
因此后续是否会考虑做调整呢？

很期待得到您们的回复。

**Comment by JeffreySu** [comment]
您好，这个TIME_OUT是一个常量，专门提供给系统里面方法的timeOut参数当做默认值使用的，也就是说你在不设置那些方法的timeOut的时候，会默认使用TIME_OUT。换句话说这里的TIME_OUT作为开发者可以忽略。

另外一个问题是比较关键的，就是那些公开方法并没有全部提供timeOut的参数，接下去我们逐步会把“底层”的timeOut开放到公共的方法中的。

非常感谢您的交流！期待更多宝贵建议！
