### ISSUE TITLE
群发上传图片失败！

### ISSUE THREAD

**Issue by lijianwei4444** [JeffreySu/WeiXinMPSDK#708]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
调用MediaApi.UploadImgAsync 上传图片时出错
The format of value 'multipart/form-data; boundary=----8d4d8f52db8b61b' is invalid.

##### 微信官方文档 URL
https://api.weixin.qq.com/cgi-bin/media/uploadimg?access_token=ACCESS_TOKEN

##### 发现问题的模块
MediaApi
- [ ] Senparc.Weixin 版本：
- [x] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经暂停更新）
- [ ] .net 4.0（将于2017年7月停止更新）
- [ ] .net 4.5
- [ ] .net 4.6.1
- [x ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

**Comment by lishewen** [comment]
与#688 是同一个问题，已经提交了PR，不知道更新了Nuget包没，你可以更新下最新版试试

**Comment by lijianwei4444** [comment]
@lishewen  nuget包更新到了14.5.4.2，调用后
 {WxJsonResult：{errcode:'40005',errcode_name:'不合法的文件类型',errmsg:'invalid file type hint: [L9mYWa0852e421]'}}

**Comment by lishewen** [comment]
![_20170801183442](https://user-images.githubusercontent.com/837067/28821488-341d86b2-76e8-11e7-9f7b-12afa67b8a29.png)

测了一下PR的代码，异步方法 MediaApi.UploadImgAsync 也是正常的

你看看是不是你上传的文件格式有问题，或者大小超出了微信的限制

**Comment by lijianwei4444** [comment]
@lishewen 我用的.net core 我看.net core 没有更新啊  是不是测试的是.net 45版本？感谢

**Comment by lijianwei4444** [comment]
@lishewen 通过测试发现，只要带中文名上传就会失败，没有中文 一切正常

**Comment by lishewen** [comment]
好的，晚点我确认下问题再推个PR上来

**Comment by lishewen** [comment]
@lijianwei4444 已提交了Fix Bug PR，等待 @JeffreySu Merge

**Comment by JeffreySu** [comment]
Merged
