### ISSUE TITLE
JsCode2JsonResult缺少unionid属性定义

### ISSUE THREAD

**Issue by kevinleptin** [JeffreySu/WeiXinMPSDK#711]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
根据微信小程序API，wx.login会返回unionid属性。
【期望】JsCode2JsonResult中包含unionid属性定义
【实际】JsCode2JsonResult中没有unionid属性定义

##### 微信官方文档 URL
https://mp.weixin.qq.com/debug/wxadoc/dev/api/api-login.html#wxloginobject

##### 发现问题的模块

- [x] Senparc.Weixin.WxOpen 版本：1.4.0

##### 模块对应的.net版本

- [x] .net 4.5
- [x] .net 4.6.1
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [x] Visual Studio 2015
- [ ] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

**Comment by JeffreySu** [comment]
非常感谢！你那边是否方便直接修改之后Pull Request过来？不方便的话我们来处理。
