### ISSUE TITLE
关于到nuget下载Senparc.Weixin.Work.dll

### ISSUE THREAD

**Issue by pigwing** [JeffreySu/WeiXinMPSDK#712]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
关于到nuget下载Senparc.Weixin.Work.dll 会连同Newtonsoft.Json一并下载下来了.但是我看源码,并无使用到他进行json的序列化.为什么呢.这个json.net到底有什么作用的.

##### 发现问题的模块
- [x] Senparc.Weixin.Work 版本：

##### 模块对应的.net版本
- [x] .net 4.5.2

##### 开发环境
- [x] Visual Studio 2015

**Comment by JeffreySu** [comment]
应该是.net core中用到了，我们会检查一下，谢谢！

**Comment by JeffreySu** [comment]
是Work依赖的Senparc.Weixin基础库用到了：https://www.nuget.org/packages/Senparc.Weixin
实际在.NET 4.5下面是没用到，下一步有计划用。
