### ISSUE TITLE
CommonApi.Menu中，GetMenuFromJsonResult()的几个条件判断

### ISSUE THREAD

**Issue by dusdong** [JeffreySu/WeiXinMPSDK#72]
非常感谢您的开源程序，对我帮助很大。

我使用的技术环境是 Angularjs + Webapi，post到服务器时，数据格式跟mvc的不大一样，导致 GetMenuFromJsonResult() 函数中的判断产生了错误。我进行了具体如下修改：

1、第 199 行，if(rootButton.name == null) 改为 if (string.IsNullOrEmpty(rootButton.name))。

2、第 204 行，var availableSubButton =  rootButton.sub_button.Count(z => !string.IsNullOrEmpty(z.name)) 改为：
var availableSubButton = rootButton.sub_button == null ? 0 : rootButton.sub_button.Count(z => !string.IsNullOrEmpty(z.name))

3、第 308 行，if(subSubButton.name == null) 改为 if (string.IsNullOrEmpty(subSubButton.name))

以上，谢谢！

**Comment by JeffreySu** [comment]
非常感谢！不知道你那边有没有fork？如果有的话可以直接在你的代码里面修改好了pull request过来。（顺便的好处是，这样项目的贡献者里面也能看到你的名字了）

**Comment by TYSZCC** [comment]
已经修改，谢谢！
