### ISSUE TITLE
群发原创校验

### ISSUE THREAD

**Issue by mrrightwangl** [JeffreySu/WeiXinMPSDK#725]
群发如果其中有判断转载的情况，收不到群发内容也无法获取是哪条文章有问题
err(30001) // 原创校验出现系统错误且用户选择了被判为转载就不群发
err(30002) // 原创校验被判定为不能群发
err(30003) // 原创校验被判定为转载文且用户选择了被判为转载就不群发

**Comment by JeffreySu** [comment]
麻烦按照我们给的格式填写issue，不然项目组很难跟进。谢谢。
