### ISSUE TITLE
群发判断转载的情况

### ISSUE THREAD

**Issue by mrrightwangl** [JeffreySu/WeiXinMPSDK#728]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
群发如果其中有判断转载的情况，收不到群发内容也无法获取是哪条文章有问题如：

err(30001) // 原创校验出现系统错误且用户选择了被判为转载就不群发
err(30002) // 原创校验被判定为不能群发
err(30003) // 原创校验被判定为转载文且用户选择了被判为转载就不群发

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [x ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [x] .net 4.5
- [x] .net 4.6.1
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

**Comment by JeffreySu** [comment]
对应微信官方文档 URL 是哪个 ？

**Comment by mrrightwangl** [comment]
https://api.weixin.qq.com/cgi-bin/message/mass/get?access_token=ACCESS_TOKEN
事件推送群发结果,现无法获取CopyrightCheckResult
<xml>
<ToUserName><![CDATA[gh_4d00ed8d6399]]></ToUserName>
<FromUserName><![CDATA[oV5CrjpxgaGXNHIQigzNlgLTnwic]]></FromUserName>
<CreateTime>1481013459</CreateTime>
<MsgType><![CDATA[event]]></MsgType>
<Event><![CDATA[MASSSENDJOBFINISH]]></Event>
<MsgID>1000001625</MsgID>
<Status><![CDATA[err(30003)]]></Status>
<TotalCount>0</TotalCount>
<FilterCount>0</FilterCount>
<SentCount>0</SentCount>
<ErrorCount>0</ErrorCount>
<CopyrightCheckResult>
<Count>2</Count>
<ResultList>
<item>
<ArticleIdx>1</ArticleIdx>
<UserDeclareState>0</UserDeclareState>
<AuditState>2</AuditState>
<OriginalArticleUrl><![CDATA[Url_1]]></OriginalArticleUrl>
<OriginalArticleType>1</OriginalArticleType>
<CanReprint>1</CanReprint>
<NeedReplaceContent>1</NeedReplaceContent>
<NeedShowReprintSource>1</NeedShowReprintSource>
</item>
<item>
<ArticleIdx>2</ArticleIdx>
<UserDeclareState>0</UserDeclareState>
<AuditState>2</AuditState>
<OriginalArticleUrl><![CDATA[Url_2]]></OriginalArticleUrl>
<OriginalArticleType>1</OriginalArticleType>
<CanReprint>1</CanReprint>
<NeedReplaceContent>1</NeedReplaceContent>
<NeedShowReprintSource>1</NeedShowReprintSource>
</item>
</ResultList>
<CheckState>2</CheckState>
</CopyrightCheckResult>
</xml>

**Comment by mrrightwangl** [comment]
https://api.weixin.qq.com/cgi-bin/message/mass/get?access_token=ACCESS_TOKEN
事件推送群发结果，现无法获取CopyrightCheckResult内容

**Comment by JeffreySu** [comment]
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1481187827_i0l21

**Comment by JeffreySu** [comment]
@mrrightwangl 已经更新，请查看。

单元测试地址：https://github.com/JeffreySu/WeiXinMPSDK/blob/23dd2752f23ec1610e2e3c534e2a7a69fd05f9f8/src/Senparc.Weixin.MP/Senparc.Weixin.MP.Test/Helpers/EntityHelperTest.cs#L141
