### ISSUE TITLE
JSSDKHelper.CreateNonekeySha1这个方法进行值排序时与官方的测试工具排序结果有时不一致

### ISSUE THREAD

**Issue by pandaban** [JeffreySu/WeiXinMPSDK#731]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
在开发卡券功能时，在H5页面添加卡卷有时候会出现签名错误的情况，最终发现问题是JSSDKHelper.CreateNonekeySha1和官方测试工具https://mp.weixin.qq.com/debug/cgi-bin/sandbox?t=cardsign 计算出来的签名有时候一致有时候又不一致，发现是值排序的问题，测试数据：
code：1
timestamp：1502361405
api_ticket：IpK_1T69hDhZkLQTlwsAX5obXn0E5uq_TynOijBuCBBI6VJSWxNWD7AlvetXO4OCf_GuMkLBePEArCKFXjZfCw
nonce_str：f2b54bb143ae41b5afe70437506b0555
card_id：p_BzXw2OeMnlDbAcT6i5Mz5WRMmU
官方计算出来是d7498efca6dc0307529ac4c5983d51dc644f1bce
但是JSSDKHelper.GetcardExtSign得到的却不一样，求帮助

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [x] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [x] .net 4.5
- [x] .net 4.6.1
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [x] Visual Studio 2015
- [ ] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

**Comment by JeffreySu** [comment]
是不是你用的版本不是最新的？最新的已经修改了排序规则：
https://github.com/JeffreySu/WeiXinMPSDK/blob/d53eb560f973a6ed94fab874b549602db3aefc76/src/Senparc.Weixin.MP/Senparc.Weixin.MP/Helpers/JSSDK/JSSDKHelper.cs#L146
