### ISSUE TITLE
建议增加获取商品二维码

### ISSUE THREAD

**Issue by zhcnlei** [JeffreySu/WeiXinMPSDK#736]
官方文档地址：https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1455872062

获取商品二维码
调用该接口，商户可获得由微信格式生成的商品二维码，用于印刷在包装上标识商品。

请求示例
HTTP请求方式：POST
https://api.weixin.qq.com/scan/product/getqrcode?access_token=ACCESS_TOKEN
POST数据格式：JSON
POST数据例子：
{
 "keystandard": "ean13",
 "keystr": "6900873042720",
 "extinfo": "test",
 "qrcode_size": 64
}

请求参数说明

参数 | 是否必须 | 说明
-- | -- | --
access_token | 是 | 公众号的全局凭据，用于接口调用。
keystandard | 是 | 商品编码标准。
keystr | 是 | 商品编码内容。
extinfo | 否 | 由商户自定义传入，建议仅使用大小写字母、数字及-_().*这6个常用字符。
qrcode_size | 是 | 二维码的尺寸（整型），数值代表边长像素数，不填写默认值为100。

注意：
商户可通过extinfo为同一款产品生成多个二维码，用于区分或作来源判断。例如一款产品虽然只有一个对应的商品ID，但可以为该款产品下每一个单独的商品分配一个extinfo参数用以标识。当用户打开商品主页，或者点击主页内的推广链接时，微信会将extinfo参数透传给商户，商户就能跟踪每一个商品和用户接触的情况。更多商品二维码能力请见“一物一码专区”。

返回示例
{
 "errcode":0,
 "errmsg":"ok",
 "pic_url":"http://mmbiz.qpic.cn/mmbiz/test/0",
 "qrcode_url":"http://p.url.cn/hA0P71b9MKc/123"
}

返回参数说明

参数 | 说明
-- | --
errcode | 0为调用成功，否则返回相关错误码。
errmsg | ok为调用成功，否则返回错误提示。
pic_url | 商品二维码的图片链接，可直接下载到本地。
qrcode_url | 商品二维码的内容，以http://p.url.cn/为前缀，加上pid和extinfo三部分组成。

**Comment by JeffreySu** [comment]
不一能能赶在下一版Nuget之前加上去，还有其他的一些任务。
如果你的来得及的话是否方便Pull Request过来？
