### ISSUE TITLE
性能问题：AccessTokenContainer.GetAccessTokenResult()资源锁判定问题

### ISSUE THREAD

**Issue by BlueMain** [JeffreySu/WeiXinMPSDK#746]
性能问题：Senparc.Weixin.MP.Containers.AccessTokenContainer.GetAccessTokenResult()资源锁判定问题，应该用双重判定模式，避免高并发时带来性能问题：
![image](https://user-images.githubusercontent.com/23711258/29199555-7e87319a-7e80-11e7-9e61-ba4d572b7fdd.png)
建议修改为：
![image](https://user-images.githubusercontent.com/23711258/29199572-a0a831b6-7e80-11e7-98b9-292754567eb4.png)

**Comment by JeffreySu** [comment]
你的版本是什么时候的？现在这里已经过是这样了：
https://github.com/JeffreySu/WeiXinMPSDK/blob/master/src/Senparc.Weixin.MP/Senparc.Weixin.MP/Containers/AccessTokenContainer.cs#L204

**Comment by BlueMain** [comment]
不好意思，原来我看的是 Release里最新的源码。。。 下个最新的先 -_-!
