### ISSUE TITLE
JSSDKHelper.GetJsSdkUiPackage 方法有死循环？请尽快修改

### ISSUE THREAD

**Issue by pbzyy** [JeffreySu/WeiXinMPSDK#749]
出错点：
 jsApiTicketBag.JsApiTicketResult = await CommonApi.GetTicketAsync(jsApiTicketBag.AppId, jsApiTicketBag.AppSecret);
 CommonApi.GetTicketAsync的方法拿token：
var accessToken = await AccessTokenContainer.TryGetAccessTokenAsync(appId, secret); 这个方法里面有嵌套那token的方法。
嵌套导致死循环

**Comment by JeffreySu** [comment]
下面一个是GetTicketAsync，一个是GetTokenAsync，没有死循环哇？能不能把你说的死循环的一个循环表达一下？

**Comment by JeffreySu** [comment]
新版本代码的问题，需要额外处理才能使用，已在回滚代码，不需要修改任何代码，请使用MP v14.6.3，感谢反馈！
