### ISSUE TITLE
这些未支持功能，以后也不打算开发支持吗，我看这些功能应该有两年了未实现

### ISSUE THREAD

**Issue by ghd258** [JeffreySu/WeiXinMPSDK#760]
企业卡券服务：卡券事件推送
企业客服服务：客服回复消息回调
企业回话服务：企业会话回调
第三方回调协议：授权成功推送auth_code事件、通讯录变更通知
扫一扫事件推送：打开商品主页事件推送、关注公众号事件推送、进入公众号事件推送、地理位置信息异步推送、商品审核结果推送
卡券事件推送：买单事件推送、会员卡内容更新事件推送、库存报警事件推送、券点流水详情事件推送
微信认证事件推送

**Comment by JeffreySu** [comment]
是否能提供一下对应的文档地址？我们来跟踪看一下不做的原因。

**Comment by ghd258** [comment]
https://github.com/JeffreySu/WeiXinMPSDK  下面以实现的功能

**Comment by JeffreySu** [comment]
这个表已经有更新了，我们会重新check一下，谢谢反馈！

**Comment by ghd258** [comment]
我看你们还是没有更新，还有你的发布的版本和你们写的不一样啊，23 releases的版本是Senparc.Weixin.MP v14.4.13，但是你其他得发好像都14.6了

**Comment by JeffreySu** [comment]
Release多数情况下都会比master和nuget晚一点，需要一段时间观察是否达到稳定版要求，另外一般都是有重要更新我们才会做Release。

**Comment by ghd258** [comment]
企业卡券服务：卡券事件推送
企业客服服务：客服回复消息回调
企业回话服务：企业会话回调
第三方回调协议：授权成功推送auth_code事件、通讯录变更通知
扫一扫事件推送：打开商品主页事件推送、关注公众号事件推送、进入公众号事件推送、地理位置信息异步推送、商品审核结果推送
卡券事件推送：买单事件推送、会员卡内容更新事件推送、库存报警事件推送、券点流水详情事件推送
微信认证事件推送  这些好像还是没有变 没有更新 这些功能不开发吗

**Comment by JeffreySu** [comment]
@ghd258 已经计划了，不过目前还有跟多优先级更高的更新，这些优先级相对比较低，我们做了一些调研使用率相对很低。如果你有时间的话可以加上去之后Pull Request过来，成为我们项目的Contributor :)
所有MessageHandler内部机制已经非常成熟了，只要依葫芦画瓢就行了。

**Comment by cocobear** [comment]
没动静了。

**Comment by JeffreySu** [comment]
@cocobear 有一部分已经上了，还有一些计划排的比较后，主要是人手的问题，优先处理必须要我们核心团队处理的紧急的更新，其他的我们欢迎开发者们PR代码上来，成为项目的 Contributor。

**Comment by JeffreySu** [comment]
@cocobear 到现在为止陆续已经添加了一批功能，如果还有缺的欢迎反馈，感谢！
