### ISSUE TITLE
使用TryGetTicket方法返回过期ticket的问题

### ISSUE THREAD

**Issue by superboy724** [JeffreySu/WeiXinMPSDK#761]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [x] Senparc.Weixin.QY 版本：2.6.3.27076
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [x] .net 4.5
- [] .net 4.6.1
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [x ] Visual Studio 2015
- [ ] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [x] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

调用TryGetTicket方法后发现过期的ticket并没有刷新，重启iis后恢复。

**Comment by JeffreySu** [comment]
这边检查逻辑都是正确的，我们会继续观察。
另外建议升级到Work，兼容QY的，只需要修改命名空间

**Comment by JeffreySu** [comment]
对了，Global里面线程启动了吗？

>  ThreadUtility.Register();

**Comment by superboy724** [comment]
好的。话说这个方法理论上会自动调用还是说必须手动调用才可以？

**Comment by JeffreySu** [comment]
功能的设计和目前的代码上看，就是自动更新的。你说的“调用”是指啥？调用当然是在你需要的时候调用。如果你是说刷新的话，是自动的。
