### ISSUE TITLE
最新版的JSSDKHelper.GetJsSdkUiPackage 方法抛异常

### ISSUE THREAD

**Issue by adaxiong** [JeffreySu/WeiXinMPSDK#762]
##### 问题描述
在Controller中调用此方法出现异常，大概说这个方法是个异步的，老版本的不会出现

System.InvalidOperationException: 现在无法开始异步操作。异步操作只能在异步处理程序或模块中开始，或在页生存期中的特定事件过程中开始。如果此异常在执行 Page 时发生，请确保 Page 标记为 <%@ Page Async="true" %>。此异常也可能表明试图调用“异步无效”方法，在 ASP.NET 请求处理内一般不支持这种方法。相反，该异步方法应该返回一个任务，而调用方应该等待该任务。 在 System.Web.AspNetSynchronizationContext.OperationStarted() 在 System.Net.WebClient.DownloadStringAsync(Uri address, Object userToken) 在 System.Net.WebClient.DownloadStringTaskAsync(Uri address) 在 System.Net.WebClient.DownloadStringTaskAsync(String address) 在 Senparc.Weixin.HttpUtility.RequestUtility.d__8.MoveNext() --- 引发异常的上一位置中堆栈跟踪的末尾 --- 在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 在 Senparc.Weixin.HttpUtility.Get.d__3`1.MoveNext() --- 引发异常的上一位置中堆栈跟踪的末尾 --- 在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 在 Senparc.Weixin.MP.CommonAPIs.CommonApi.d__5.MoveNext() --- 引发异常的上一位置中堆栈跟踪的末尾 --- 在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 在 Senparc.Weixin.MP.Containers.AccessTokenContainer.d__7.MoveNext() --- 引发异常的上一位置中堆栈跟踪的末尾 --- 在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 在 Senparc.Weixin.MP.Containers.AccessTokenContainer.d__6.MoveNext() --- 引发异常的上一位置中堆栈跟踪的末尾 --- 在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 在 Senparc.Weixin.MP.Containers.AccessTokenContainer.

##### 发现问题的模块

- [x] Senparc.Weixin 版本：
- [x] Senparc.Weixin.MP 版本：
- [x] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [x] .net 4.5
- [x] .net 4.6.1
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

**Comment by JeffreySu** [comment]
新版本代码的问题，需要额外处理才能使用，已在回滚代码，不需要修改任何代码，请使用MP v14.6.3，感谢反馈！

**Comment by alexinea** [comment]
你是在 ASP.NET MVC 内还是在 ASP.NET Core MVC 内出的问题？

**Comment by JeffreySu** [comment]
@alexinea 他的这个问题是因为在同步方法中直接使用了异步方法，Waiting过程中造成了ASP.NET线程的死锁（在Console里面不会发生，所以单元测试都通过了）。是因为有一位开发者推送过来的代码中这么做了，我们当时没有注意到这个问题，现在已经还原了。
