### ISSUE TITLE
RedPackApi.SendNormalRedPack方法中证书地址只能使用本地地址吗？

### ISSUE THREAD

**Issue by zhougangnj** [JeffreySu/WeiXinMPSDK#769]
是否可以使用流或者http服务器地址？

证书我们保存在阿里云oss中，使用阿里云的oss地址好像这个方法不能使用

**Comment by JeffreySu** [comment]
请提供一下阿里云证书的调用方法示例，我们看一下。

**Comment by JeffreySu** [comment]
@zhougangnj Azure上面是有解决方案的，需要你提供一些信息才能帮到你。

**Comment by JeffreySu** [comment]
@zhougangnj 如果你希望我们继续帮你解决问题，需要你提供你的代码，并 Reopen 这个 issue。
