### ISSUE TITLE
创建和获取自定义菜单不支持media_id和view_limited类型

### ISSUE THREAD

**Issue by zhoujs712** [JeffreySu/WeiXinMPSDK#777]
##### 问题描述
使用如下两种类型来创建自定义菜单或获取自定义菜单时出错
        {
           "type": "media_id", 
           "name": "图片", 
           "media_id": "MEDIA_ID1"
        }, 
        {
           "type": "view_limited", 
           "name": "图文消息", 
           "media_id": "MEDIA_ID2"
        }

##### 微信官方文档 URL
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421141013

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：

##### 模块对应的.net版本

- [x] .net 4.5
- [x] .net 4.6.1

##### 开发环境

- [ ] Visual Studio 2017

##### 缓存环境

- [X] 服务器内存缓存（默认）

**Comment by JeffreySu** [comment]
应该是没有添加对应的类型，我们会马上处理，谢谢！

**Comment by zhoujs712** [comment]
src/Senparc.Weixin.MP/Senparc.Weixin.MP/CommonAPIs/Menu/CommonApi.Menu.Common.cs的修改部分应该是如下，同时应在rootButton中加入相似的判断

                    else if (subSubButton.type.Equals("MEDIA_ID", StringComparison.OrdinalIgnoreCase))
                    {
                        //下发消息（除文本消息）
                        subButton.sub_button.Add(new SingleMediaIdButton()
                        {
                            name = subSubButton.name,
                            key = subSubButton.key,
                            type = subSubButton.type
                        });
                    }
                    else if (subSubButton.type.Equals("VIEW_LIMITED", StringComparison.OrdinalIgnoreCase))
                    {
                        //跳转图文消息URL
                        subButton.sub_button.Add(new SingleViewLimitedButton()
                        {
                            name = subSubButton.name,
                            key = subSubButton.key,
                            type = subSubButton.type
                        });
                    }

**Comment by JeffreySu** [comment]
可以了，master分支，你看一下。Demo也更新了。

**Comment by JeffreySu** [comment]
@zhoujs712 测试结果怎么样？

**Comment by zhoujs712** [comment]
使用Demo测试带有media_id和view_limited的获取菜单和创建菜单功能，全都成功。
