### ISSUE TITLE
删除或者添加tag下面的用户出错

### ISSUE THREAD

**Issue by sinnhe** [JeffreySu/WeiXinMPSDK#784]
我用Senparc.Weixin.Work操作tag时，获取tag和tag下面的用户都能获取到数据，但是删除tag下的用户和添加用户就报这个错
sdk版本均为最新

![qq 20170827141346](https://user-images.githubusercontent.com/6416775/29747599-1c80243e-8b32-11e7-98d8-05cf544b9865.png)

##### 发现问题的模块

- [x] Senparc.Weixin 版本：4.14
- [x] Senparc.Weixin.Work 版本：0.4.1

模块对应的.net版本- [x] .net 4.5
开发环境Visual Studio 2013

**Comment by JeffreySu** [comment]
你的token是怎么来的？多少位（length）告诉我一下

**Comment by sinnhe** [comment]
`AccessTokenContainer.TryGetToken(corpId, secret);`
length=299

**Comment by sinnhe** [comment]
@JeffreySu  
`AccessTokenContainer.TryGetToken(corpId, secret);`
length=299

**Comment by JeffreySu** [comment]
![image](https://user-images.githubusercontent.com/2281927/29872651-0f83d6de-8dc3-11e7-9fb9-579a831c1d65.png)

这个是对于AppKeyh和Token的判断，如果是299的话应该可以识别为Token，而且这个接口并没有要求提供CorpId哇 😨

**Comment by sinnhe** [comment]
@JeffreySu 我把原有的出错的tag删掉了。重新通过接口创建 ，一切就OK啦。我觉得可能是权限的问题

**Comment by JeffreySu** [comment]
@sinnhe 👌
