### ISSUE TITLE
Senparc.Weixin.Work的MemberResult中缺少order这个属性

### ISSUE THREAD

**Issue by lhg0302** [JeffreySu/WeiXinMPSDK#788]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
Senparc.Weixin.Work的MemberResult中缺少order这个属性,
不知道什么时候能更新,谢谢

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [x] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [ ] .net 4.5
- [ ] .net 4.6.1
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [ ] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

**Comment by lhg0302** [comment]
Senparc.Weixin.Work的MemberResult中缺少order这个属性

**Comment by JeffreySu** [comment]
MemberResult.cs里面有好几个接口的返回结果，您说的是具体哪一个？能不能给一下文档，方便我们查找？

**Comment by JeffreySu** [comment]
找了一圈，只看到GetMemberResult.order少了，您确认一下是不是这个。
非常感谢！也欢迎直接将修改的代码Pull Request过来，成为我们的Contributor 😄

**Comment by lhg0302** [comment]
是的,谢谢了
