### ISSUE TITLE
WeiXinMPSDK / Senparc.Weixin / Senparc.Weixin / Enums.cs ReturnCode缺少枚举值“验证失败”

### ISSUE THREAD

**Issue by fsea** [JeffreySu/WeiXinMPSDK#79]
WeiXinMPSDK / Senparc.Weixin / Senparc.Weixin / Enums.cs ReturnCode缺少枚举值“验证失败”

**Comment by TYSZCC** [comment]
您好，返回结果枚举进行了修改，“验证失败”改成了“获取access_token时AppSecret错误或者access_token无效”，您在项目中改一下就行了，其余没有变化，感谢您的反馈，给你带来的不便还请谅解。
