### ISSUE TITLE
SendGroupMessagePreview 一直提示微信Post请求发生错误！错误代码：40007，说明：invalid media_id

### ISSUE THREAD

**Issue by fsea** [JeffreySu/WeiXinMPSDK#80]
SendGroupMessagePreview 一直提示微信Post请求发生错误！错误代码：40007，说明：invalid media_id

**Comment by fsea** [comment]
var newsPicMediaID = Senparc.Weixin.MP.AdvancedAPIs.Media.MediaApi.UploadForeverMedia(wxBaseInfo.AccessToken, Server.MapPath(newsPic)).media_id;

                    var news = new Senparc.Weixin.MP.AdvancedAPIs.GroupMessage.NewsModel()
                    {
                        title = newsTitle,
                        content = Utility.String.ReplaceImageUrl(wxBaseInfo.HeadHtml + newsContent + wxBaseInfo.FootHtml),
                        thumb_media_id = newsPicMediaID,
                        show_cover_pic = "0",

                    };
                    newsList[i] = news;

                var bmsg = Senparc.Weixin.MP.AdvancedAPIs.Media.MediaApi.UploadNews(wxBaseInfo.AccessToken, Senparc.Weixin.Config.TIME_OUT, newsList);

                Senparc.Weixin.MP.AdvancedAPIs.GroupMessage.GroupMessageApi.SendGroupMessagePreview(wxBaseInfo.AccessToken, Senparc.Weixin.MP.GroupMessageType.mpnews, bmsg.media_id, openid);

SendGroupMessagePreview 一直提示微信Post请求发生错误！错误代码：40007，说明：invalid media_id
请问是哪里出现了问题，微信官方文档中上传群发素材依然使用的是https://api.weixin.qq.com/cgi-bin/media/uploadnews?access_token=ACCESS_TOKEN

但WeiXinMPSDK 项目中使用的是http://api.weixin.qq.com/cgi-bin/material/add_material?access_token={0}，并且没有type
旧版本的群发和预览正常，当前版本的用不成，请查查！

**Comment by fsea** [comment]
经测试，要想成功调用SendGroupMessagePreview方法，那么Senparc.Weixin.MP.AdvancedAPIs.Media.MediaApi.UploadNews中的urlFormat必须是https://api.weixin.qq.com/cgi-bin/media/uploadnews?access_token={0}
这估计应该是微信的一个bug，原则上https://api.weixin.qq.com/cgi-bin/material/add_news?access_token={0}代替了原接口，应该是微信预览和群发的api还没有更新

**Comment by TYSZCC** [comment]
您好，感谢您反馈这个问题。微信文档中将原有的上传临时图文素材的接口删除了，但是我这边测试发现以前的那个接口依旧有效，所以在最新版本里面添加了上传临时图文素材的接口，这里的SendGroupMessagePreview方法应该还是用的临时的MediaId，永久的MediaId和临时的MediaId是不能混用的。您这里遇到的问题，只需要将上传图文素材的接口改成上传临时图文的就可以解决了。

**Comment by TYSZCC** [comment]
现在的版本中我把以前的上传接口也放上去了，使用原来的接口试试呢？微信的新接口传的是永久的素材，把以前上传临时素材的接口删除了，但是我测试以前的接口依然能用，我就把以前上传临时素材的接口也放上去了，您换一下上传临时图文素材的接口试试呢。

 

发件人: fsea [mailto:notifications@github.com] 
发送时间: 2015年4月1日 1:35
收件人: JeffreySu/WeiXinMPSDK
主题: Re: [WeiXinMPSDK] SendGroupMessagePreview 一直提示微信Post请求发生错误！错误代码：40007，说明：invalid media_id (#80)

 

                var newsPicMediaID = Senparc.Weixin.MP.AdvancedAPIs.Media.MediaApi.UploadForeverMedia(wxBaseInfo.AccessToken, Server.MapPath(newsPic)).media_id;
 
                var news = new Senparc.Weixin.MP.AdvancedAPIs.GroupMessage.NewsModel()
                {
                    title = newsTitle,
                    content = Utility.String.ReplaceImageUrl(wxBaseInfo.HeadHtml + newsContent + wxBaseInfo.FootHtml),
                    thumb_media_id = newsPicMediaID,
                    show_cover_pic = "0",
 
                };
                newsList[i] = news;
 
            var bmsg = Senparc.Weixin.MP.AdvancedAPIs.Media.MediaApi.UploadNews(wxBaseInfo.AccessToken, Senparc.Weixin.Config.TIME_OUT, newsList);
 
            Senparc.Weixin.MP.AdvancedAPIs.GroupMessage.GroupMessageApi.SendGroupMessagePreview(wxBaseInfo.AccessToken, Senparc.Weixin.MP.GroupMessageType.mpnews, bmsg.media_id, openid);

SendGroupMessagePreview 一直提示微信Post请求发生错误！错误代码：40007，说明：invalid media_id
请问是哪里出现了问题，微信官方文档中上传群发素材依然使用的是https://api.weixin.qq.com/cgi-bin/media/uploadnews?access_token=ACCESS_TOKEN

但WeiXinMPSDK 项目中使用的是http://api.weixin.qq.com/cgi-bin/material/add_material?access_token={0} <http://api.weixin.qq.com/cgi-bin/material/add_material?access_token=%7B0%7D%EF%BC%8C%E5%B9%B6%E4%B8%94%E6%B2%A1%E6%9C%89type> ，并且没有type
旧版本的群发和预览正常，当前版本的用不成，请查查！
