### ISSUE TITLE
Support for .NET Core 2.0 Razor Pages (replacement for MVC)

### ISSUE THREAD

**Issue by ghd258** [JeffreySu/WeiXinMPSDK#802]
Support for .NET Core 2.0 Razor Pages (replacement for MVC)

**Comment by JeffreySu** [comment]
@lishewen 你那边有准备上新的Razor Pages吗？

**Comment by lishewen** [comment]
目前没有，维护期的项目还是主打MVC，新项目还在谈需求，Razor Pages适合做点小项目可以研究下
