### ISSUE TITLE
企业微信GetMember 从腾讯返回wxplugin_status为空值

### ISSUE THREAD

**Issue by lei467** [JeffreySu/WeiXinMPSDK#804]
##### 问题描述
用方法Senparc.Weixin.Work.AdvancedAPIs.MailListApi.GetMember 调用成员信息
返回的GetMemberResult.wxplugin_status为空值

##### 发现问题的模块

- [x] Senparc.Weixin.Work 版本：v0.4.2

##### 模块对应的.net版本

- [x] .net 4.5

##### 开发环境

- [x] Visual Studio 2015

**Comment by lishewen** [comment]
现在文档中没有 wxplugin_status 这项了
https://work.weixin.qq.com/api/doc#10019

好像已经统一在
status
激活状态: 1=已激活，2=已禁用，4=未激活。
已激活代表已激活企业微信或已关注微信插件。未激活代表既未激活企业微信又未关注微信插件。

**Comment by lei467** [comment]
企业微信文档看过，上面的status无法体现：仅关注微信插件的用户状态

**Comment by lishewen** [comment]
文档没有，估计是微信那边不返回数据了，这个也没啥好办法

**Comment by lei467** [comment]
@lishewen 原企业号接口并没有关闭，senparc能否在Senparc.Weixin.Work集成一个对wxplugin_status状态的快速采集方法。毕竟需求一直存在。

**Comment by JeffreySu** [comment]
@lei467 有没有真是的request和response的数据给我们一份，这样才能做单元测试和方便我们验证。

**Comment by JeffreySu** [comment]
@lei467 你有具体的建议吗？如果有的话请留言并 Repoen 这个 issue，谢谢！

**Comment by lei467** [comment]
@JeffreySu   水平有限，你们参考下看这样是否可行：
用方法Senparc.Weixin.Work.AdvancedAPIs.MailListApi.GetMember 调用成员信息
返回的GetMemberResult.wxplugin_status如果为空值，此方法按原来的Senparc.Weixin.QY.AdvancedAPIs.MailListApi.GetMember的路径补取一次Status？  
我目前在项目就是用这样的笨方法处理的。
另外，我个人觉得Senparc现在就停止Senparc.Weixin.QY的更新有点急了。未必腾讯想做什么就一定做得成，我感觉企业号就比企业微信更适合我公司用。

**Comment by lishewen** [comment]
@lei467 Senparc.Weixin.QY是停止更新了，但没有停止下载啊，如果微信那边的API没有停的话，你仍然可以通过Senparc.Weixin.QY去调用的，如果微信那边已经完全停止了企业号的API的话，这边怎么改都是没辙的

**Comment by lei467** [comment]
收到，谢谢。Senparc.Weixin.QY仍在用。
