### ISSUE TITLE
14.6.10版RedPackApi.SendNormalRedPack报错

### ISSUE THREAD

**Issue by zhaoyu1999** [JeffreySu/WeiXinMPSDK#809]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
发送红包后报错 System.ArgumentException: 路径中具有非法字符。
   在 System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   在 System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   在 System.IO.Path.GetFullPath(String path)
   在 System.Xml.XmlResolver.ResolveUri(Uri baseUri, String relativeUri)
   在 System.Xml.XmlTextReaderImpl..ctor(String url, XmlNameTable nt)
   在 System.Xml.XmlDocument.Load(String filename)
   在 Senparc.Weixin.MP.TenPayLibV3.RedPackApi.SendNormalRedPack(String appId, String mchId, String tenPayKey, String tenPayCertPath, String openId, String senderName, String iP, Int32 redPackAmount, String wishingWord, String actionName, String remark, String& nonceStr, String& paySign, String mchBillNo, Nullable`1 scene, String riskInfo, String consumeMchId)

问题应该是出在WeiXinMPSDK/src/Senparc.Weixin.MP/Senparc.Weixin.MP/TenPayLibV3/RedPackApi.cs line #426

##### 发现问题的模块

- [x] Senparc.Weixin 版本：4.14.3
- [x] Senparc.Weixin.MP 版本：14.6.10 

##### 模块对应的.net版本

- [x] .net 4.5

##### 开发环境

- [x] Visual Studio 2015

##### 缓存环境

- [X] 服务器内存缓存（默认）

**Comment by zhaoyu1999** [comment]
通过Nuget添加的包

**Comment by zhaoyu1999** [comment]
从14.4.4版本开始有这个问题

**Comment by zhaoyu1999** [comment]
14.6.11版本没有修复
测试代码
```cs
  AccessTokenContainer.Register(AppConstants.APP_ID, AppConstants.APP_SECRET);
  string nonceStr = "";
  string paySign = "";
  var result = RedPackApi.SendNormalRedPack(AppConstants.APP_ID, AppConstants.PAY_ID, AppConstants.PAY_KEY, @"apiclient_cert.p12", userId,
                "开发", "127.0.0.1", 100, "测试", "测试", "测试", out nonceStr, out paySign, null);
```

**Comment by JeffreySu** [comment]
426行是被注释掉的代码：

![image](https://user-images.githubusercontent.com/2281927/30237812-94e503ba-956c-11e7-8bab-6ef175fce589.png)

是不是你的代码不是最新的？
