### ISSUE TITLE
BUG提交：“企业号>>通讯录管理>>标签管理>>获取标签列表”  接口少了

### ISSUE THREAD

**Issue by bemguin** [JeffreySu/WeiXinMPSDK#81]
BUG提交：接口少了
企业号>>通讯录管理>>标签管理>>获取标签列表
http://qydev.weixin.qq.com/wiki/index.php?title=%E7%AE%A1%E7%90%86%E6%A0%87%E7%AD%BE#.E8.8E.B7.E5.8F.96.E6.A0.87.E7.AD.BE.E5.88.97.E8.A1.A8

**Comment by TYSZCC** [comment]
感谢您的反馈，新版本中已经添加此接口。
