### ISSUE TITLE
第三方平台 AccessToken 使用redis 缓存失败

### ISSUE THREAD

**Issue by TPchene** [JeffreySu/WeiXinMPSDK#811]
本地已注册redis 缓存
public static AuthorizationInfo GetAuthorizationInfo(string componentAppId, string authorizerAppid,bool getNewTicket = false)方法缓存正常，已在两台电脑上测试

ComponentContainer.GetComponentAccessToken 获取token redis缓存失败

**Comment by JeffreySu** [comment]
我们已经安排测试，如果确实有问题会立即修复，谢谢反馈！

**Comment by JeffreySu** [comment]
关了？
