### ISSUE TITLE
企业微信（Work）接口内容跟最新的企业微信api文档有出入

### ISSUE THREAD

**Issue by yyhui00** [JeffreySu/WeiXinMPSDK#812]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
getuserinfo返回的数据类型和企业微信api文档的返回类型有出入
没有getuserdetail 对应的方法

##### 微信官方文档 URL
http://work.weixin.qq.com/api/doc

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：1.0.0
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [x] .net 4.5
- [x] .net 4.6.1
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

**Comment by JeffreySu** [comment]
收到，我们会核对并更新，谢谢！

**Comment by JeffreySu** [comment]
你说的是Work下的OAuth的GetUserInfoResult返回类型里面不正确吗？看了一下里面只有多（按照QY移植），并没有少：http://work.weixin.qq.com/api/doc#10719

**Comment by yyhui00** [comment]
我看的是：http://work.weixin.qq.com/api/doc#10028 ，里面有两个方法：getuserinfo和getuserdetail，其中getuserinfo返回的参数比你们的要多一点，然后getuserdetail这个方法你们是没有实现

**Comment by JeffreySu** [comment]
TODO：完善异步方法和注释

**Comment by JeffreySu** [comment]
已经完成：v1.1.0 添加 OAuth2Api.GetUserDetail()方法，对应已增加异步方法。
以后欢迎将代码Pull Request给我们，成为项目的Contributor 🤝
