### ISSUE TITLE
建议第三方平台 TryRegister 方法设为public

### ISSUE THREAD

**Issue by TPchene** [JeffreySu/WeiXinMPSDK#813]
ComponentContainer.Register 注册时导致token清空
IIS做负载均衡时，token获取有一定概率会出错
所以建议 TryRegister 方法设为Public 这样注册的时候token不需要清空了

**Comment by JeffreySu** [comment]
这里有几个问题：
1、TryRegister 这个private的方法最终调用的是Register，这个方法是public的，所以把TryRegister设为public不能解决任何问题吧？
2、如果是负载均衡，每次注册的时候都会判断componentAppId是否已经被注册，如果没有才会注册，这也正是private TryRegister 中做了一些判断的原因：
```
if (!CheckRegistered(componentAppId) || getNewToken)
{
    Register(componentAppId, componentAppSecret, null, null, null, name);
}
```
3、最可能发生“错误”的原因，是2台服务器同时启动，同时判断CheckRegistered()为false，同时写入一个空的ComponentBag对象，此时缓存本来就没有命中。

欢迎讨论。
