### ISSUE TITLE
SenparcOAuthAttribute在HTTPS协议下遇到错误10003

### ISSUE THREAD

**Issue by kevinleptin** [JeffreySu/WeiXinMPSDK#816]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
当在https协议下，使用该特性，会导致OAuth Url自动加上端口号443。然而根据微信的开发文档，URL中填写端口号是非法的。实际使用中微信服务器会返回10003错误

##### 微信官方文档 URL
N/A

##### 微信官方文档快照（直接复制关键内容到下方）
N/A

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [x] Senparc.Weixin.MP.MVC 版本：目前最新
文件路径/src/Senparc.Weixin.MP.MvcExtension/Senparc.Weixin.MP.MvcExtension/Filters
文件名 SenparcOAuthAttribute.cs
Line# 104
Code:  urlData.Port != 80 ? (":" + urlData.Port) : "",
Workaround: 子类里重写OnAuthorization方法 

- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [x] .net 4.5
- [x] .net 4.6.1
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [x] Visual Studio 2015
- [ ] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

**Comment by JeffreySu** [comment]
感谢反馈！已经完成升级，下次欢迎直接把想法Pull Request给我们，成为项目的Contribute 👍
