### ISSUE TITLE
BUG提交：“企业号>>通讯录管理>>标签管理>>获取标签成员”  接口返回少了 partylist

### ISSUE THREAD

**Issue by bemguin** [JeffreySu/WeiXinMPSDK#82]
BUG提交：“企业号>>通讯录管理>>标签管理>>获取标签成员”  接口返回少了 partylist

接口位置：
Senparc.Weixin.QY.AdvancedAPIs.MailList.GetTagMember

官方文档：
http://qydev.weixin.qq.com/wiki/index.php?title=%E7%AE%A1%E7%90%86%E6%A0%87%E7%AD%BE#.E8.8E.B7.E5.8F.96.E6.A0.87.E7.AD.BE.E6.88.90.E5.91.98

**Comment by TYSZCC** [comment]
您好，最新版本的Senparc.Weixin.QY中已经添加了该字段，请您升级一下dll再试试，感谢您的反馈！
