### ISSUE TITLE
QyCustomMessageHandler  类找不到

### ISSUE THREAD

**Issue by jihaipeng** [JeffreySu/WeiXinMPSDK#822]
##### 问题描述
Senparc.Weixin.MP.Sample.WebForms项目中Qy.aspx.cs文件中没有这个类。

**Comment by JeffreySu** [comment]
之前有公告，QY已经都转移到Work，请查看WorkCustomMessageHandler。

另外Demo我们也把Qy.aspx改成了Work.aspx，可以注意同步，感谢您的支持！
