### ISSUE TITLE
CustomMessageHandler不能处理设备相关的事件

### ISSUE THREAD

**Issue by leospace** [JeffreySu/WeiXinMPSDK#832]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
SDK里没有处理设备相关的事件，例如绑定和解绑的事件的处理
因为设备绑定和解绑需要处理设备与用户的关联关系，因为设备的二维码可以携带第三方的数据，
但是目前没有这种事件类型的处理。

##### 微信官方文档 URL
http://iot.weixin.qq.com/wiki/document-2_2.html
http://iot.weixin.qq.com/wiki/document-2_5.html

##### 微信官方文档快照（直接复制关键内容到下方）
接收设备绑定解绑事件
用户通过扫描设备二维码绑定设备后，微信会推送设备绑定事件给第三方。
用户通过取消关注设备公众号解绑设备后，微信会推送设备解绑事件给第三方。
微信用户绑定设备后，设备会通过微信给第三方发送消息。

详见官方文档

##### 发现问题的模块
- [x] Senparc.Weixin.MP 版本：14.4.13.0

##### 模块对应的.net版本
- [x] .net 4.5
- [x] .net 4.6.1

##### 开发环境
- [x] Visual Studio 2015

##### 缓存环境
- [x] Redis 版本：

**Comment by JeffreySu** [comment]
IOT的接口现在MP集成了一部分，我们正在打算单独推出一个Senparc.Weixin.IoT，你觉得有必要吗？

**Comment by leospace** [comment]
我觉得是有必要的。设备这块的功能点以及相关的api还是很多的，另外我测试发现微信的扫码绑定和解绑设备事件推送过来的消息并不是官方说的xml格式，而是json格式的。如下：
"content":"","create_time":1505727735,"device_id":"gh_xxxxxxxxxxxx","device_type":"gh_xxxxxxxxxxxx","encrypt":"J0KhUFo…………………………","msg_id":267784935,"msg_type":"bind","open_id":"oI_xxxxxxxxxxxxxxxxxxxxxxxx","qrcode_suffix_data":"","session_id":0}
消息处理这块就得单独来处理了。我也再与微信官方沟通为什么设备的事件是json而不是xml，目前还没有得到回复。

**Comment by JeffreySu** [comment]
好的，我们会关注进展，后期也欢迎加入到我们的更新Contributor队伍中来 🤝

**Comment by leospace** [comment]
好的，不过要如何加入Contributor队伍呢？

**Comment by leospace** [comment]
@JeffreySu

**Comment by leospace** [comment]
已经搞清楚了，由于我这边设备管理的设置里启用了服务器配置，所以微信发来的事件就是json格式的了：

详见：http://iot.weixin.qq.com/wiki/new/index.html?page=3-4-2
注意：
如果已在公众平台－设备功能－设置中启动并设置服务器配置，设备发送的消息以及开发者需要的设备事件推送，将被微信硬件平台以Json格式转发并只转发到该URL。
在Json格式下，如果设备商需要获取设备相关数据或下达指令，可通过调用应用端OpenAPI进行操作。

**Comment by JeffreySu** [comment]
@leospace 我们的书上有详细的说明，或者看首页：https://github.com/JeffreySu/WeiXinMPSDK#%E8%B4%A1%E7%8C%AE%E4%BB%A3%E7%A0%81
当然每个步骤基本都可以可视化地在VS或者浏览器里面完成。
