### ISSUE TITLE
重要更新提示

### ISSUE THREAD

**Issue by JeffreySu** [JeffreySu/WeiXinMPSDK#839]
2017年9月20日的Release（ https://github.com/JeffreySu/WeiXinMPSDK/releases/tag/v14.7.1 ）将是最后一个单独包含.NET Framework 4.5代码的版本，此版本发布后，项目将升级到同时支持 .NET Framwork 4.5/.NET Core 1.1/.NET Core 2.0 的多版本项目（目前仅支持VS2017打开），其解决方案（.sln）或项目文件（.csproj）前可看到.vs2017字样。

升级将是完全向下兼容的，也就是说我们保留了原有的.NET Framework 4.5解决方案文件和项目文件，您仍然可以使用之前的方式（解决方案文件）打开.NET Framework 4.5项目。

同时，原有的 Developer_FullDotNet 分支将完成使命，合并入 Developer 分支并最终发布到 master 分支，完成后，Developer_FullDotNet 分支将被关闭。

升级完成后将只存在一个包含全版本的代码版本，更有利于维护和发布。

**Comment by JeffreySu** [comment]
@lishewen

**Comment by lishewen** [comment]
哦 了解

**Comment by JeffreySu** [comment]
现在master已经是FullDotNet了
