### ISSUE TITLE
企业号通过ticket获取用户详细的时候 错误消息  Role VIEWER does not exist

### ISSUE THREAD

**Issue by zariczhu** [JeffreySu/WeiXinMPSDK#848]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
我用企业号获取用户信息的时候
调用 方法 OAuth2Api.GetUserDetail(tokenResult.access_token, userInfo.user_ticket);
抛出异常
System.InvalidOperationException: Role VIEWER does not exist

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [x] .net 4.5
- [x] .net 4.6.1
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

**Comment by JeffreySu** [comment]
这个错误在不同的环境和用户下能稳定重现吗？
我们还没看到过这个错误。

**Comment by zariczhu** [comment]
同一个人有时候会出现，但是重试几次就又好了。不是所有的手机用户都会出现

**Comment by zariczhu** [comment]
不好意思，有可能是我们自己的问题，先close，如果有疑问再开。

**Comment by JeffreySu** [comment]
好的，另外建议把QY升级到Work，QY已经不更新了，Work完全兼容QY，并且会保持最新接口的更新和bug修复。
