### ISSUE TITLE
无法下载微信永久素材

### ISSUE THREAD

**Issue by serveryang** [JeffreySu/WeiXinMPSDK#85]
为什么无法下载微信素材，一直报{"errcode":40007,"errmsg":""}错误。

**Comment by serveryang** [comment]
为什么无法下载微信素材，一直报{"errcode":40007,"errmsg":""}错误。

**Comment by TYSZCC** [comment]
临时素材与永久素材的获取方式是不一样的，请问您在下载永久素材的时候是使用的获取永久素材这个接口吗？

**Comment by JeffreySu** [comment]
已经优化了SDK的写法，并且做了比较完整的单元测试，您可以试一下。不过上面这个40007的错误是id错误，应该不是SDK的问题。

**Comment by serveryang** [comment]
嗯 好的更新下nuget包。以前是下载永久素材不成功，不过我已经自己实现了该方法。

**Comment by lipengfei911** [comment]
请问下下载永久素材接口后来可以用了吗,或者还是不行,还是微信的接口问题, 我也碰到这个问题了,求指教

**Comment by serveryang** [comment]
我没有这个sdk的下载，自己实现的。sdk能用的我就用，不能用的我就自己实现。

**Comment by serveryang** [comment]
我没使用sdk下载永久素材，是自己实现的。反正sdk能用的我就用，不能用的我就自己实现。另外因为下载比较占资源，我采用的是多线程异步来实现，这样可以提高效率。

**Comment by JeffreySu** [comment]
@lipengfei911  永久素材一直是可以用的，5月份做了一些优化，目前的版本已经比较稳定了。

**Comment by thagedy** [comment]
我也遇到相同的问题，media_id是微信传过来的，但是用这个media_id去获取永久素材时就会报错40007，这是什么问题？难道是微信传过来的media_id是错误的吗
