### ISSUE TITLE
14.7.1版RedPackApi.SendNormalRedPack报错“路径中具有非法字符。”

### ISSUE THREAD

**Issue by zhw511006** [JeffreySu/WeiXinMPSDK#858]
通过nuget添加的， 调用SendNormalRedPack方法，红包发送成功！但是报错System.ArgumentException:“路径中具有非法字符。”
是xml解析出现了问题吧？期待解答！感谢！

**Comment by JeffreySu** [comment]
有跟踪数据吗？

**Comment by zhw511006** [comment]
降到14.3.142这个版本就可以了！期待解答！谢谢！

**Comment by JeffreySu** [comment]
@zhw511006 详细的抛错信息能给一下吗？
