### ISSUE TITLE
问一下，Senparc.Weixin.Open 是做什么的？

### ISSUE THREAD

**Issue by dusdong** [JeffreySu/WeiXinMPSDK#86]
RT，谢谢~

**Comment by TYSZCC** [comment]
这个模块是给第三方公众服务平台使用的，详见https://open.weixin.qq.com/

暂时还未完成

 

发件人: dusdong [mailto:notifications@github.com] 
发送时间: 2015年4月23日 13:50
收件人: JeffreySu/WeiXinMPSDK
主题: [WeiXinMPSDK] 问一下，Senparc.Weixin.Open 是做什么的？ (#86)

 

RT，谢谢~

**Comment by dusdong** [comment]
哇，这个好！
