### ISSUE TITLE
创建第三方代制模式的卡券

### ISSUE THREAD

**Issue by zhaochenghang** [JeffreySu/WeiXinMPSDK#863]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述

微信第三方代制卡券的接口中,需要sub_merchant_info数据,但Card_BaseInfoBase类中没有此属性

##### 微信官方文档 URL

https://mp.weixin.qq.com/wiki?action=doc&id=mp1451025292&t=0.17126486297633403#1.7
##### 发现问题的模块

- [√ ] Senparc.Weixin.MP 版本：v14.7.1

##### 模块对应的.net版本

- [√ ] .net 4.0（已于2017年7月暂时停止更新）
- [√ ] .net 4.5

##### 开发环境

- [ √] Visual Studio 2010
- [ √] Visual Studio 2015

**Comment by JeffreySu** [comment]
@zhaochenghang 你说的是CardApi.CreateCard()这个方法吗？

**Comment by JeffreySu** [comment]
@zhaochenghang 看一下是不是这样：https://github.com/JeffreySu/WeiXinMPSDK/commit/0a19b839abbf9e9e8ed92e56c780e5ba70d5df53#diff-537ee03a94574782c9119f56e1d211f7

**Comment by JeffreySu** [comment]
@zhaochenghang 先关闭了，如果有问题请 Reopen 这个 issue。
