### ISSUE TITLE
JSSDKHelper.GetNoncestr MD5编码方式为什么没有换成UTF-8

### ISSUE THREAD

**Issue by KevinPan** [JeffreySu/WeiXinMPSDK#878]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述

Senparc.Weixin.MP/Senparc.Weixin.MP/Helpers/JSSDK/JSSDKHelper.cs
方法GetNoncestr
        public static string GetNoncestr()
        {
            var random = new Random();
            return EncryptHelper.GetMD5(random.Next(1000).ToString(), "GBK");
        }
获取MD5的编码方式为什么没有换成**UTF-8**？

##### 发现问题的模块

- [x] Senparc.Weixin 版本：
- [x] Senparc.Weixin.MP 版本：

##### 模块对应的.net版本

- [x] .net core

##### 开发环境

- [x] Visual Studio 2017

##### 缓存环境

- [X] 服务器内存缓存（默认）

**Comment by KevinPan** [comment]
asp.net core 2.0环境使用这个方法的时候出现了 not supported encoding GBK异常
我目前换成使用Senparc.Weixin.Work.Helpers.JSSDKHelper.GetNoncestr(); Work类库里的方法了

**Comment by lishewen** [comment]
http://blog.lishewen.com/post/thenet-core-using-gb2312-encoding

编码问题好像已经改过好多遍了。用这个方法可以让netcore兼容gb2312编码，至少程序不会报错。一会我还是push一个fix上来吧

**Comment by JeffreySu** [comment]
感谢两位。
