### ISSUE TITLE
没有用户分组删除接口？

### ISSUE THREAD

**Issue by aqbjteddy** [JeffreySu/WeiXinMPSDK#88]
http://mp.weixin.qq.com/wiki/0/56d992c605a97245eb7e617854b169fc.html#.E5.88.A0.E9.99.A4.E5.88.86.E7.BB.84

这里有提供用户分组删除接口，咱们这边没有实现吗？

API
https://github.com/JeffreySu/WeiXinMPSDK/blob/master/Senparc.Weixin.MP/Senparc.Weixin.MP/AdvancedAPIs/Groups/GroupsAPI.cs

**Comment by TYSZCC** [comment]
已经添加，会在新版本中发布，感谢您的反馈

**Comment by JeffreySu** [comment]
@TYSZCC 这个修改已经上传了吗？
