### ISSUE TITLE
企业微信通讯录同步

### ISSUE THREAD

**Issue by liyuchuan86** [JeffreySu/WeiXinMPSDK#883]
##### 问题描述
急需企业微信通讯录同步功能，希望sdk能加上

##### 发现问题的模块

- [x] Senparc.Weixin.Work 版本：

##### 模块对应的.net版本

- [x] .net 4.5
- [x] .net 4.6.1
##### 开发环境

- [x] Visual Studio 2017

**Comment by lishewen** [comment]
全量覆盖成员API不是有吗？
https://github.com/JeffreySu/WeiXinMPSDK/blob/master/src/Senparc.Weixin.Work/Senparc.Weixin.Work/AdvancedAPIs/Asynchronous/AsynchronousApi.cs

**Comment by lishewen** [comment]
对应的开发文档
https://work.weixin.qq.com/api/doc#10138

**Comment by liyuchuan86** [comment]
非常感谢，已经搞定 @lishewen

**Comment by JeffreySu** [comment]
👍
