### ISSUE TITLE
发红包成功和失败 都抛的异常 信息是 路径中具有非法字符

### ISSUE THREAD

**Issue by cqwebwang** [JeffreySu/WeiXinMPSDK#886]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
发红包现在成功和失败 都抛的异常 信息是 路径中具有非法字符
Senparc.Weixin.MP.TenPayLibV3.RedPackApi  227行

源码处：    doc.Load(response);错误
使用doc.LoadXml(response);正常
 
        

##### 发现问题的模块
 
- [x] Senparc.Weixin.MP 版本： 

##### 模块对应的.net版本
 
- [x] .net 4.5 

##### 开发环境
 
- [ ] Visual Studio 2013 
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）

**Comment by JeffreySu** [comment]
有没有你那边的测试数据？

**Comment by Hieasywork** [comment]
有的

**Comment by Hieasywork** [comment]
public ActionResult SendRedPack()
        {
            string nonceStr;//随机字符串
            string paySign;//签名
            var sendNormalRedPackResult = RedPackApi.SendNormalRedPack(
               "wxf68c6218e00a7717",
               "1393118202",
               "WEIFENGSIDAO12346448060294947773",
                @"I:\Inlike.p12",     //证书物理地址
                "ozLmKv7QDaOH7AYazVRU9EdtEg0I",   //接受收红包的用户的openId
                "123",             //红包发送者名称
                Request.UserHostAddress,      //IP
                100,                          //付款金额，单位分
                "123",                 //红包祝福语
                "1231",                   //活动名称
                "备注信息",                   //备注信息
                out nonceStr,
                out paySign,
                null,                         //场景id（非必填）
                null,                         //活动信息（非必填）
                null                          //资金授权商户号，服务商替特约商户发放时使用（非必填）
                );

            SerializerHelper serializerHelper = new SerializerHelper();
            return Content(serializerHelper.GetJsonString(sendNormalRedPackResult));
        }

**Comment by Hieasywork** [comment]
@pbzyy 说的是对的，@JeffreySu  因为response出来的结果是string,  Load(string)  从指定的 URL 加载 XML 文档。而LoadXml可以直接加载string内容，

**Comment by JeffreySu** [comment]
@Hieasywork @pbzyy 谢谢各位，已经修复，问题出在.net framework和.net core对同一个Load方法支持的参数不一致，没有注意到这个问题，升级.net core的时候直接改成了.net core的方式，现在已经区别对待，请查看是否还有问题。

**Comment by pbzyy** [comment]
@JeffreySu 还有些没有改完

**Comment by JeffreySu** [comment]
@pbzyy 还有哪些？

**Comment by JeffreySu** [comment]
@pbzyy @Hieasywork 最新的版本已经发布到master分支，还有哪些没有改完的麻烦统计到这里，谢谢！

**Comment by pbzyy** [comment]
@JeffreySu 刚看了一下，改完了
