### ISSUE TITLE
work sdk升级最新版本有些对象缺少一些字段

### ISSUE THREAD

**Issue by ThomasTy966** [JeffreySu/WeiXinMPSDK#891]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
GetApprovalDataJsonResult_Data[] 对象集合里面的apply_time和apply_user_id不见了 是修改成别的名称了吗 如果是的话我建议升级sdk的时候尽量向下兼容 发现升级sdk后很多地方需要修改 比如有得方法参数的数据类型也变动过 顺序也变动过（可能因为新增了参数）

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [x] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [x] .net 4.5
- [x] .net 4.6.1
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [x] Visual Studio 2013
- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

**Comment by JeffreySu** [comment]
如果是特地改的，肯定是有依据的，比如根据当时的文档，你发现的问题能给一下对应的文档地址吗？

**Comment by ThomasTy966** [comment]
http://doc.weixin.senparc.com/html/Properties_T_Senparc_Weixin_Work_AdvancedAPIs_OaDataOpen_GetApprovalDataJsonResult_Data.htm 总体来说这个sdk 改动有点大 无从对照啊 文档没有过往版本的记录吧

**Comment by JeffreySu** [comment]
@ThomasTy966 Work是从QY移植的，然后再根据企业微信（不是微信企业号）的文档做了对照，进行适当的修改，所以如果有和QY不同的地方，应该是会有特殊的用意， 因此我想要的是微信官方的文档，查看一下目前是什么情况，不是SDK的文档，谢谢！

**Comment by JeffreySu** [comment]
@ThomasTy966 如果有更新的情况请回复并 Reopen 此 issue，谢谢！
