### ISSUE TITLE
企业微信接口 Senparc.Weixin.Work 所有使用部门ID的API需要将id长度加长

### ISSUE THREAD

**Issue by kistliu** [JeffreySu/WeiXinMPSDK#894]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
企业微信中：部门已经同步成功，部门id是超过int32的最大值的。
Senparc.Weixin.Work.AdvancedAPIs.MailList.DepartmentList类
id长度需要加长。
同时还有
Senparc.Weixin.Work.AdvancedAPIs.MailListApi下的所有关于部门id的方法

##### 微信官方文档 URL
https://work.weixin.qq.com/api/doc#10093

##### 微信官方文档快照（直接复制关键内容到下方）

参数 | 必须 | 说明
-- | -- | --
access_token | 是 | 调用接口凭证
id | 否 | 部门id。获取指定部门及其下的子部门。 如果不填，默认获取全量组织架构

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [x] Senparc.Weixin.Work 版本：1.1.3
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [x] .net 4.5
- [x] .net 4.6.1
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

**Comment by JeffreySu** [comment]
已经修改，请查看是否正确：https://github.com/JeffreySu/WeiXinMPSDK/commit/86a99efaca6f828cb33da88fddd118ed50395cc7

**Comment by kistliu** [comment]
CreateDepartment这个方法改漏了，父部门id改了，id还是int?

**Comment by kistliu** [comment]
还有什么时候能发布到nuget上呢？

**Comment by JeffreySu** [comment]
又做了一次更新：https://github.com/JeffreySu/WeiXinMPSDK/commit/4470597a927d66923f82807076a996397b59f886

去人没问题了就可也以发布nuget。

**Comment by kistliu** [comment]
嗯 看到了。
