### ISSUE TITLE
会员卡custom_field下面的name_type增加FIELD_NAME_TYPE_UNKNOW枚举

### ISSUE THREAD

**Issue by gwhzh21** [JeffreySu/WeiXinMPSDK#904]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
1.更新会员卡，或者是获取会员卡时，针对信息类目，有三个custom_field类型。下面都有一个叫name_type的定义，缺少FIELD_NAME_TYPE_UNKNOW枚举。
2.在向微信提交custom_field类型的时候，最好是用枚举值0,1,2.....而不是字符串，测试发现IELD_NAME_TYPE_ACHIEVEMEN太长了。提交不上去。
3.下午的测试，显示，custom_field[n]:{name_type:0} 会关闭对应的custom_field[n].所以最后必须增加FIELD_NAME_TYPE_UNKNOW枚举.

##### 微信官方文档 URL
官方文档并没有告之这些。客户也太喜欢改卡面了。

##### 微信官方文档快照（直接复制关键内容到下方）

2.创建会员卡时，需设置会员卡激活后呈现的信息类目，目前支持积分、余额、等级、优惠券、里程、印花、成就、折扣等类型，微信6.2以上版本显示会员信息类目的上限为3个，即创建时类目字段supply_bonus 、supply_balance、 custom_field1、custom_field2 、custom_field3最多选择三项填写。

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [x ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [x] .net 4.5
- [x] .net 4.6.1
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [x ] Visual Studio 2015
- [ ] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

**Comment by JeffreySu** [comment]
非常感谢！
对于已经明确问题，欢迎直接Pull Request到Developer分支，成为我们的Contributor一员 😄 
如果无法提交请告知，我们会来处理。

**Comment by JeffreySu** [comment]
@gwhzh21 关于（2），官方文档就是string类型的，应该不存在太长无法提交的问题。

**Comment by JeffreySu** [comment]
@gwhzh21 这个问题我们已经处理了，错过了一个Contributor机会 😭
