### ISSUE TITLE
项目若仅引用Senparc.Weixin.MP，不引用Senparc.Weixin，则解决方案启动即崩溃

### ISSUE THREAD

**Issue by mzji** [JeffreySu/WeiXinMPSDK#909]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
项目若仅引用Senparc.Weixin.MP，则启动崩溃

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [x] Senparc.Weixin.MP 版本： 14.8.3 （nuget依赖）
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [ ] .net 4.5
- [ ] .net 4.6.1
- [x] .net core 2.0

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 崩溃异常内容：
内容来自Visual Studio调试模式下的“输出”子窗口，显示输出来源：调试
```
“System.IO.FileLoadException”类型的未经处理的异常在 未知模块。 中发生 
Could not load file or assembly 'Senparc.Weixin, Version=4.17.2.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

##### Workaround
为项目添加Senparc.Weixin v14.7.2的nuget引用即可。

##### 问题分析
Senparc.Weixin.MP v14.8.3 已经引用了 Senparc.MP v14.7.2 ，但是nuspec文件未更新，仍然依赖 v14.7.1 ，导致解决方案启动崩溃（因为项目依赖图里不存在Senparc.MP v14.7.2，只有Senparc.MP v14.7.1）。

**Comment by JeffreySu** [comment]
不应该是这个问题，如果你nuget安装的是Senparc.Weixin.MP v14.8.3 ，那么应该引用的是Senparc.Weixin v14.7.1 ，和v14.7.2是无关的，v14.7.2是我们后来单独发布的，也是向下兼容v14.7.1的。

另外Senparc.Weixin.MP是必须依赖Senparc.Weixin的，如果你是通过nuget安装Senparc.Weixin.MP，所有依赖都是自动添加的，不会有问题。

**Comment by mzji** [comment]
@JeffreySu 我就是通过nuget，仅引用了Senparc.Weixin.MP v.14.8.3，结果编译运行就炸了。没有更新依赖前，只引用MP v14.7.1，编译运行就不会炸。
看了一下10月27日的commit eac44dfaf858dc1d684a95ad94a9bbdd4019dfc8 （nuget发布时的版本），在这个版本里将Senparc.Weixin版本号更新为v14.7.2，同时由于Senparc.Weixin.MP是通过引用csproj的方式来引用Senparc.Weixin，所以Senparc.Weixin.MP v14.8.3发布时，引用的是Senparc.Weixin v14.7.2，而非v14.7.1。
使用dotPeek查看Senparc.Weixin.MP v14.8.3的项目依赖，如图所示（打开的是.net standard 2.0的dll）：
![weixin_mp_reference](https://user-images.githubusercontent.com/23279426/32448298-860fda4e-c349-11e7-8911-b85cb9555b04.png)
由此图可见 Senparc.Weixin.MP v14.8.3 依赖于 Senparc.Weixin v14.7.2 。

**Comment by JeffreySu** [comment]
明白你的意思了，查了一下你说的问题确实存在，测试了一下可能是新版nuget打包程序的问题，如果新的包没有被索引（上传后需要一段时间），版本号就会自动降级，Senparc.Weixin v4.18.3已经上传，索引之后将会上传新的 MP v14.8.4，依赖Senparc.Weixin v4.18.3。非常感谢！

**Comment by JeffreySu** [comment]
@mzji MP v14.8.4已经发布了

**Comment by mzji** [comment]
好的，谢谢
