### ISSUE TITLE
第三方平台FuncscopeCategory枚举中，缺少类型

### ISSUE THREAD

**Issue by lisensoft** [JeffreySu/WeiXinMPSDK#918]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
获取授权信息需要 完善，微信官方已经到26了，SDK里只到19

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [x] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [x] .net 4.5
- [x] .net 4.6.1
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [x] Visual Studio 2015
- [ ] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：
或将问题地址及联系方式发送到 www.jeffrey.su@gmail.com

**Comment by JeffreySu** [comment]
非常感谢！已经安排到下周更新，如果您有时间可以直接修改之后Pull Request过来，成为我们的Contributor一员 :)

**Comment by lisensoft** [comment]
还有没解决~~！！

**Comment by JeffreySu** [comment]
这个任务一直挂起等您回复是不是能推过来。。

**Comment by JeffreySu** [comment]
已完成 https://github.com/JeffreySu/WeiXinMPSDK/commit/1ed3868dac93561a08bac91ec9aec9879ad1e999
