### ISSUE TITLE
无法忽略处理某些用户消息

### ISSUE THREAD

**Issue by owen26** [JeffreySu/WeiXinMPSDK#92]
有些用户发到公众号的消息我想不做任何处理（不回复任何内容），但是未找到如何进行配置。

在DefaultResponseMessage() 里面直接 return null; 微信公众号会提示“该公众号暂时无法提供服务，请稍后再试”；
如果用CreateResponseMessage()建立一个response实体，然后把它的Content设置为空字符串，仍然会在微信端提示“无法提供服务”；

我在这个帖子：http://www.weiweihi.com/QA/QAPost/Item/19
里面看到说直接return null 即可，但貌似不是这么回事儿。

请问有无解决方案。

**Comment by owen26** [comment]
找到解决办法了。。。 
之前是直接在DefaultResponseMessage()里面return null.

但是这样会让以下代码报错：
```
messageHandler.ResponseDocument.ToString()
```

从而导致asp.net返回500错误，而不是200 + 空Http Body

做了如下处理，已经可以正常忽略用户消息：

```
messageHandler.ResponseDocument = null ? "" : messageHandler.ResponseDocument.ToString();
```

建议对ResponseDocument的ToString方法做重写，或者提供专门的方法，当ResponseMessage为null的时候，返回空字符串。

**Comment by JeffreySu** [comment]
感谢反馈！这个问题之前应该已经处理掉了吧？
