### ISSUE TITLE
GetWxaCodeUnlimit这个方法参数错误

### ISSUE THREAD

**Issue by pbzyy** [JeffreySu/WeiXinMPSDK#920]
Senparc.Weixin.WxOpen.AdvancedAPIs.WxApp.WxAppApi类下的GetWxaCodeUnlimit这个方法参数错误。参数为page,不是path,请修正。而且还少了个参数。

文档地址：https://mp.weixin.qq.com/debug/wxadoc/dev/api/qrcode.html

![Uploading 微信图片_20171103113645.jpg…]()

**Comment by pbzyy** [comment]
Senparc.Weixin.WxOpen.AdvancedAPIs.WxApp.WxAppApi类下的GetWxaCodeUnlimit这个方法参数错误。参数为page,不是path,请修正。

**Comment by JeffreySu** [comment]
已发布到 v1.7.1，感谢！
