### ISSUE TITLE
Senparc.Weixin.Work.AdvancedAPIs.MediaApi.Upload上传图片报错

### ISSUE THREAD

**Issue by tangyangming** [JeffreySu/WeiXinMPSDK#921]
Senparc.Weixin.Work.AdvancedAPIs.MediaApi.Upload上传图片报错

错误提示:
找不到方法:“!!0 Senparc.Weixin.HttpUtility.Post.PostFileGetJson(System.String, System.Net.CookieContainer, System.Collections.Generic.Dictionary`2<System.String,System.String>, System.Collections.Generic.Dictionary`2<System.String,System.String>, System.Text.Encoding, System.Security.Cryptography.X509Certificates.X509Certificate2, Int32)”。

##### 发现问题的模块

- [x] Senparc.Weixin.Work 版本：

##### 模块对应的.net版本

- [x] .net 4.5

##### 开发环境
- [x] Visual Studio 2015

##### 缓存环境

- [X] 服务器内存缓存（默认）

##### 联系方式
Email：
或将问题地址及联系方式发送到 tangyangming@qq.com

**Comment by tangyangming** [comment]
单独建个控制台程序也是同样的错误,通过nuget引用Senparc.Weixin和Senparc.Weixin.Work两个引用直接报错

**Comment by JeffreySu** [comment]
@tangyangming Senparc.Weixin.Work 版本是多少？没有填。

**Comment by tangyangming** [comment]
目前引用了3个包,Senparc.Weixin(v4.18.3),Senparc.Weixin.MP(v14.8.5),Senparc.Weixin.Work(v1.2.1),单独创建控制台的时候,只引用Senparc.Weixin(v4.18.3)和Senparc.Weixin.Work(v1.2.1),报一样的错.麻烦看下,谢谢!

**Comment by JeffreySu** [comment]
重新发布了一个Work v1.2.2的版本，你再看一下，如果还有问题的话，比较有可能的是你服务器上版本配套的问题了。

**Comment by tangyangming** [comment]
更新版本后,已经OK,谢谢1
