### ISSUE TITLE
CardApi.CreateCard Card_MemberCardData 会员卡开卡接口定义错误

### ISSUE THREAD

**Issue by ulswww** [JeffreySu/WeiXinMPSDK#926]
关于 CardApi.CreateCard Card_MemberCardData 中wx_activate_after_submit_url 的类型应该是string的
但是 CardApi.CreateCard Card_MemberCardData写成 bool?了
这应该是微信文档的问题
文档如下：

wx_activate_after_submit_url | 否 | bool | 跳转型一键激活跳转的地址链接，请填写http://或者https://开头的链接

微信给的例子是：
"wx_activate_after_submit_url" : "https://qq.com"      //用户提交信息后跳转的网页

**Comment by JeffreySu** [comment]
麻烦提供一下文档详细地址，方便我们跟踪问题。

**Comment by JeffreySu** [comment]
已经确认修复，感谢！
