### ISSUE TITLE
Senparc.Weixin.MP.AdvancedAPIs.MediaApi.Get

### ISSUE THREAD

**Issue by tangyangming** [JeffreySu/WeiXinMPSDK#928]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述

Senparc.Weixin.MP.AdvancedAPIs.MediaApi.Get和Senparc.Weixin.Work.AdvancedAPIs.MediaApi.Get两个接口获取微信临时文件,没有文件后缀名,以前是有的,

##### 发现问题的模块
- [x] Senparc.Weixin.MP 版本：
- [x] Senparc.Weixin.Work 版本：
- [ ] 其他模块：

##### 模块对应的.net版本
- [x] .net 4.5
##### 开发环境

- [x] Visual Studio 2015

##### 缓存环境

- [X] 服务器内存缓存（默认）

##### 联系方式
Email：tangyangming@qq.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
你dir参数设置的是什么，能不能给一个示例？dir设置对了应该是可以保存成自定义的文件名的。

**Comment by tangyangming** [comment]
dir只是设置成了一个目录,没有到具体的文件名,我这具体调用,如下
   var filePath = Senparc.Weixin.Work.AdvancedAPIs.MediaApi.Get(QYWeixinHelper.GetContactToken(), mediaId, HttpContext.Current.Server.MapPath(dir));
   以前是我设置dir="~/Upload/Dorm/",返回filePah会变成"~/Upload/Dorm/文件名.jpg"或者"~/Upload/Dorm/文件名.amr"等
  但是现在调用,filePath="~/Upload/Dorm/文件名",没有后缀了.导致我保存的文件读不出来.

**Comment by tangyangming** [comment]
如果这样的话,就很不方便了,因为我也不知道根据mediaId下载下来的文件格式

**Comment by JeffreySu** [comment]
@tangyangming 测试了一下确实有问题，我们会继续跟进。

**Comment by tangyangming** [comment]
12月1日更新的版本,问题依旧,没有解决!

**Comment by JeffreySu** [comment]
基础库  v4.18.7 调整HttpUtility.Get.Download(string url, string filePathName)，改为输入完整文件路径+文件名。感谢 @tangyangming #928 #954
