### ISSUE TITLE
CardAPI.UpdateUser

### ISSUE THREAD

**Issue by gwhzh21** [JeffreySu/WeiXinMPSDK#929]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
已经连续被坑了两回了，参数addBonus和addBalance最后没有传到接口里面。
结果，以为是微信的接口有问题。最后看了代码，才发现，这两个参数被注释掉了。
public static UpdateUserResult UpdateUser(string accessTokenOrAppId, string code, string cardId, int addBonus, int addBalance, 
最好是改成
public static UpdateUserResult UpdateUser(string accessTokenOrAppId, string code, string cardId, int? addBonus=null, int? addBalance=null, 

1209 行的代码:

var data = new
                {
                    code = code,
                    card_id = cardId,
                    background_pic_url = backgroundPicUrl,
                    // add_bonus = addBonus,
                    bonus = bonus,
                    record_bonus = recordBonus,
                    // add_balance = addBalance,
                    balance = balance,
                    record_balance = recordBalance,
                    custom_field_value1 = customFieldValue1,
                    custom_field_value2 = customFieldValue2,
                    custom_field_value3 = customFieldValue3,
                };

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ x] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [x] .net 4.5
- [x] .net 4.6.1
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ x] Visual Studio 2015
- [ ] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
当初注释掉肯定是有原因的，能不能发一下对应的文档地址？我们查看一下。

**Comment by gwhzh21** [comment]
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1451025283

add_bonus | 否 | int | 100 | 本次积分变动值，传负数代表减少

add_balance | 否 | int | 100 | 本次余额变动值，传负数代表减少

**Comment by JeffreySu** [comment]
已更新，谢谢！ https://github.com/JeffreySu/WeiXinMPSDK/pull/1037/commits/ea5c2a9a8cbc895fcc714b0fb0bd7d70145b4821
