### ISSUE TITLE
群发clientmsgid exist错误

### ISSUE THREAD

**Issue by kuangyanit** [JeffreySu/WeiXinMPSDK#932]
##### 问题描述

群发接口中未追加clientmsgid参数，在短时间连续多次群发时会出现clientmsgid exist错误

##### 微信官方文档 URL

https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1481187827_i0l21

##### 微信官方文档快照（直接复制关键内容到下方）

一、群发接口新增 clientmsgid 参数，开发者调用群发接口时可以主动设置 clientmsgid 参数，避免重复推送。

群发时，微信后台将对 24 小时内的群发记录进行检查，如果该 clientmsgid 已经存在一条群发记录，则会拒绝本次群发请求，返回已存在的群发msgid，开发者可以调用“查询群发消息发送状态”接口查看该条群发的状态。

返回码 | 结果
-- | --
45065 | 相同 clientmsgid 已存在群发记录，返回数据中带有已存在的群发任务的 msgid
45066 | 相同 clientmsgid 重试速度过快，请间隔1分钟重试
45067 | clientmsgid 长度超过限制

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [X] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [x] .net 4.5
- [ ] .net 4.6.1
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [x] Visual Studio 2013
- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

**Comment by JeffreySu** [comment]
非常感谢！本周的版本已经发布，如果您有时间可以修改之后Pull Request到Developer分支，成为我们的
 Contributors 之一，我们会在下周继续发布新版本。
