### ISSUE TITLE
可以企业付款到银行卡么？

### ISSUE THREAD

**Issue by bangq** [JeffreySu/WeiXinMPSDK#936]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
可以企业付款到银行卡么？
https://pay.weixin.qq.com/wiki/doc/api/tools/mch_pay.php?chapter=24_2

**Comment by JeffreySu** [comment]
还没有，我们已经列入计划中，也欢迎大家贡献代码！

**Comment by JeffreySu** [comment]
已经在 https://github.com/JeffreySu/WeiXinMPSDK/tree/Developer_BankPay 分支中安排，有一些工作量，可能需要一些时间才能上线，欢迎大家贡献大妈！

**Comment by JeffreySu** [comment]
已完成，感谢！
