### ISSUE TITLE
Senparc.Weixin.Open.Containers.ComponentBag不可被ProtoBuf序列化

### ISSUE THREAD

**Issue by zixinw** [JeffreySu/WeiXinMPSDK#940]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
![image](https://user-images.githubusercontent.com/19518165/33195118-86c609d2-d09a-11e7-9f82-68f7c5a0acf2.png)

##### 发现问题的模块

- [-] Senparc.Weixin.Open 版本：2.7.5
- [-] Senparc.Weixin.Cache.Redis 版本：1.3.0

##### 模块对应的.net版本
- [-] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [-] 其他：

##### 缓存环境
- [-] Redis 版本：

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
您用的是.net core什么版本？1.1吗？

**Comment by wangzixin1113** [comment]
您好，版本是 2.0.2

**Comment by JeffreySu** [comment]
2.0.2应该用的是.net core 2.0自带的BinaryFormatter才对哇？
（PS：当然.net core 2.0 的BinaryFormatter也有其他问题，不过和这个无关）

**Comment by wangzixin1113** [comment]
是的，查看源码后我也发现代码没走对，所以就很奇怪咯。要不我先关闭这个issue吧，我同事跑Core的Sample也报错，他报的也是序列化错误（具体没截图，应该是BinaryFormatter相关的问题）。

**Comment by JeffreySu** [comment]
.net core 1.1是不支持二进制序列化，2.0以后是支持了，但是仍然没有支持带委托的对象的序列化。有截图的话可以发上来看一下是否是这个问题。

**Comment by wangzixin1113** [comment]
是不支持序列化委托的问题，找到截图了（附件）

**Comment by JeffreySu** [comment]
@wangzixin1113 没看到附件

**Comment by wangzixin1113** [comment]
![39794d3f-248a-4f18-84c1-b134890b1270-6054-0000064b9f1c1037_tmp](https://user-images.githubusercontent.com/19518165/33428279-24ae34e0-d603-11e7-9be3-c528091d05ee.png)
@JeffreySu 不好意思，用Spark直接回复以为会带上 - -

**Comment by lishewen** [comment]
Mark，3.0是否还存在此问题？要测下

**Comment by JeffreySu** [comment]
@lishewen 这个只是当时进行二进制序列化的补充，现在推荐的都是 JSON。

**Comment by lishewen** [comment]
https://docs.microsoft.com/zh-cn/aspnet/core/performance/caching/distributed?view=aspnetcore-3.0
最近主要是要在项目中加入这个，所以要用到BinaryFormatter
看了一下修改记录，当时主要是原生的BinaryFormatter不支持委托对象的序列化
但在
https://github.com/JeffreySu/WeiXinMPSDK/blob/1650d1406d9264945edf09d2da37ce5e78a498ac/src/Senparc.Weixin.Open/Senparc.Weixin.Open/Containers/ComponentContainer.cs#L71
修改中已经去掉了相关的委托
我在评估的是
1、3.0是否能用回原生的BinaryFormatter，以保证项目库的一致性
2、第三方BinaryFormatter包能否与IDistributedCache兼容，但这样可能Senparc.Weixin.Cache.Redis对第三方BinaryFormatter的引用也应该对应提到3.0.0，以保证一致，目前是依赖2.1.4

**Comment by lishewen** [comment]
https://docs.microsoft.com/en-us/dotnet/standard/serialization/binary-serialization#binary-serialization-in-net-core
官方的可序列化类型还是有局限性，我们的项目中也改用第三方的了

**Comment by JeffreySu** [comment]
目前.NET Core已经不存在这个问题了，谢谢大家的讨论！
