### ISSUE TITLE
企业微信，DepartmentList类order属性类型的问题

### ISSUE THREAD

**Issue by ajiebp1977** [JeffreySu/WeiXinMPSDK#941]
##### 问题描述

企业微信，获取部门信息时，Order的类型是Int32类型，在获取的时候，会返回 2147484646 ，超出int 32的最大值，之后报错。
 
涉及的类：Senparc.Weixin.QY.AdvancedAPIs.MailList.DepartmentList 下的Order

不清楚其它有无类似的问题，但是我这边调用企业号的部门数据，其中一条的order超出了Int32的大小。

建议把类型改为Int64或者string。不知以后ID是否有此问题。

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
已经改为long类型，谢谢！
