### ISSUE TITLE
.net core HttpClient 使用方法有误，请改正，不能每次都 new HttpClient()，经过在linux系统下压力测试，正确方法应该使用一个全局静态对象

### ISSUE THREAD

**Issue by 2881099** [JeffreySu/WeiXinMPSDK#942]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述

https://news.cnblogs.com/n/553217/
.NET HttpClient的缺陷和文档错误让开发人员倍感沮丧

现在的库每次 new HttpClient()，在 linux 系统下压测必报错

参考资料：http://blog.csdn.net/sd7o95o/article/details/78352139

##### 发现问题的模块

- [x] Senparc.Weixin 版本：

##### 模块对应的.net版本

- [x] .net core

##### 开发环境

- [x] Visual Studio 2017

##### 缓存环境

- [x] Redis 版本：

##### 联系方式
Email：2881099@qq.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by 2881099** [comment]
请更新，谢谢作者

**Comment by JeffreySu** [comment]
收到，我们会关注此问题，尽快修改。

**Comment by JeffreySu** [comment]
@2881099  正在尝试解决这个问题（见 https://github.com/JeffreySu/WeiXinMPSDK/tree/Developer_HttpClient 分支）

做到后面发现很多问题，比如：
```
HttpClient client = new HttpClient(handler);
```
这个client里面的handler是需要定义证书或者其他信息的，如：
```
            HttpClientHandler handler = new HttpClientHandler();
            handler.ClientCertificates.Add(cer);
```
不是所有请求的参数都是一样的，如果全局用一个静态变量，使用起来会有很多问题哇。

**Comment by 2881099** [comment]
是的，我目前是把源代码拉进项目里面改的，定义了一个专门负责普通http请求，一个专门负责普通https请求，另外支付那里根据商户号定义了字典httpclient

**Comment by lishewen** [comment]
我说几句吧，楼主提出的httpclient问题在早期的netcore的确存在，2.0版本之后已经好很多了，日常使用不会有太大问题，我现在一个iot微信项目跑在阿里云1核1G CentOS 7.4上的netcore版本2.0.3，1小时处理4.4W Request吧，平均响应24毫秒，基本满足客户需求了

另外，根据.Net Core建议的操作，即便是不喜欢每次new，也应该是通过DI注入的方式注入Httpclient对象，配置信息在DI注入前自行填入，SDK只是留出接口接收，进行以后的操作。而不应该由SDK去定义全局静态变量

根据我项目中的测试，全局静态变量也不是最佳实践，一个httpclient对象在50个以内并发时候是最好的，多了性能就会下降，甚至不如每次new，如果是追求极限性能的话应该是自己去实现一个client池管理

.net是自带有GC管理的，所以也不必过分担忧每次new浪费资源

**Comment by 2881099** [comment]
每次new，您可以压力测试一下，我的环境cetos7 2.0.3sdk，早期到现在都没有解决

和gc回收没关系，netcore释放了，还要等系统释放套字节，而系统默认释放时间过长导致并发稍大无法再次申请套字节资源

**Comment by lishewen** [comment]
这个坑我们团队在做项目中也是踩过的，相关的测试也做过。到了最后发现只要不用using等显式回收，就不会出错，没有你说的那么夸张
```C#
using (HttpClient client = new HttpClient())
```
我们不会刻意去追求极限性能

![_20171203235723](https://user-images.githubusercontent.com/837067/33527099-c2acd726-d885-11e7-9e6d-ba071fa29650.png)

这个是我生产环境在跑的一个每次new httpclient的方法，1秒从socket过来60~300个包，用一个死循环处理每次都是new一个httpclient转发出去，不显式释放，完全靠系统GC，程序正常跑了3个多月了，没报过一次异常

这个还是跑在一个树莓派3上，资源比传统主机还要少多了，按照你上面 “系统默认释放时间过长导致并发稍大无法再次申请套字节资源”的说法，早就没资源可用了

**Comment by 2881099** [comment]
好吧，您不相信我，我睡在床上特意起来给您看我的测试结果。

![image](https://user-images.githubusercontent.com/16286519/33527373-88de4534-d88a-11e7-835d-2bca75e959ad.png)

测试代码如下：（https://github.com/2881099/httpclientpool）

```c#
	class Program {
		static string HttpGet (string url) {
			// using (var bag = HttpClientPool.Instance.GetHttpClient()) {
			// 	var t = bag.HttpClient.GetStringAsync(url);
			// 	return t.Result;
			// }
			var httpclient = new HttpClient();
			var t = httpclient.GetStringAsync(url);
			return t.Result;
		}

		static void Main (string[] args) {
			DateTime dt = DateTime.Now;
			long counter_success = 0;
			long counter_error = 0;
			var running = true;
			for (var a = 0; a < 100; a++) {
				new Thread((obja) => {
					while (running) {
						var dt2 = DateTime.Now;
						try {
							var value = HttpGet("http://www.duoyi.com/dycommerce/ch/");
							Console.WriteLine($"{obja}: {value.Substring(0, 20)} {DateTime.Now.Subtract(dt2).TotalMilliseconds}ms {Interlocked.Increment(ref counter_success)}次成功");
						} catch (Exception ex) {
							Console.WriteLine($"{obja}: {ex.Message} {DateTime.Now.Subtract(dt2).TotalMilliseconds}ms {Interlocked.Increment(ref counter_error)}次错误");
						}
					}
				}).Start(a);
			}
			Console.WriteLine("1111");
			while (Console.ReadKey().Key != ConsoleKey.Escape) {
				var dt3 = DateTime.Now;
				var value2 = HttpGet("http://www.duoyi.com/dycommerce/ch/");
				Console.WriteLine($"{value2.Substring(0, 20)} {DateTime.Now.Subtract(dt3).TotalMilliseconds}ms");
			}
			running = false;

			var ts = DateTime.Now.Subtract(dt).TotalSeconds;
			Console.WriteLine($"总耗时：{ts}秒");
			Console.WriteLine($"共成功读取{counter_success}次，平均{counter_success / ts}/秒错误");
			Console.WriteLine($"共错误{counter_error}次，平均{counter_error / ts}/秒错误");
		}
	}
```

**Comment by 2881099** [comment]
按您的要求，我没有包 using，直接使用 newHttpClient() 的测试结果
在请求800次成功后，后面几乎全部失败

**Comment by 2881099** [comment]
和您说的建一个池来管理，也不会报一次错

此段测试代码，使用单个静态 HttpClient 重复请求，不会报一次错，后来我才知道建池管理多此一举，但是写的代码不能浪费了，所以传到github上了

另外版本使用如下：

[root@bogon test001]# dotnet --version
2.0.2

**Comment by 2881099** [comment]
作者您好：

除了 RedPackApi.cs 这个类复杂一点外，其他的可通用两个 new HttpClient() (http、https)

我处理 RedpackApi.cs 的HttpClient是定义了静态字典，代码如下：
```c#
public class MyHttpClient {
	public HttpClientHandler HttpClientHandler { get; set; }
	public HttpClient HttpClient { get; set; }
}
public static System.Collections.Concurrent.ConcurrentDictionary<string, MyHttpClient> HttpClients { get; set; }
public static MyHttpClient GetHttpClient (string cert, string password) {
	return HttpClients.GetOrAdd($"{cert}{password}", pwd => {
		X509Certificate2 cer = new X509Certificate2(cert, password, X509KeyStorageFlags.PersistKeySet | X509KeyStorageFlags.MachineKeySet);
		var newitem = new MyHttpClient();
		newitem.HttpClientHandler = new HttpClientHandler();
		newitem.HttpClientHandler.ClientCertificates.Add(cer);
		newitem.HttpClient = new HttpClient(newitem.HttpClientHandler);
		return newitem;
	});
}
```

使用的地方大概改成这样：

```c#
//发红包接口地址
string url = "https://api.mch.weixin.qq.com/mmpaymkttransfers/sendredpack";
//本地或者服务器的证书位置（证书在微信支付申请成功发来的通知邮件中）
string cert = tenPayCertPath;
//私钥（在安装证书时设置）
string password = mchId;

HttpClient client = GetHttpClient(cert, password).HttpClient;

HttpContent hc = new StringContent(data);
var request = client.PostAsync(url, hc).Result;
var response = request.Content.ReadAsStreamAsync().Result;

XmlDocument doc = new XmlDocument();
//doc.LoadXml(responseContent);
doc.Load(response);
```

**Comment by lishewen** [comment]
![_20171204083412](https://user-images.githubusercontent.com/837067/33531839-f1f0430e-d8cd-11e7-8cc2-deb5d86f322c.png)

你提供的测试方法 一行代码未改，虚拟机跑了5000多次了

**Comment by lishewen** [comment]
我并不是反对使用全局静态的 HttpClient，只是在最新的netcore下，这样的优化不会有质的提升，对于以前的老版本还是有意义的。怎么改还是看苏总吧，这个毕竟不是我的项目，你有现成的修改也可以PR过来，作者也是欢迎的。

**Comment by 2881099** [comment]
按正常开发习惯应该是每次new HttpClient，而不是静态定义

这个问题不是我一个人发现的，好多朋友和同事反应，之前一个游戏业务开新服被这个问题坑了停服2小时

我把代码扔给好几个人测试都会报错，debian8，centos7环境
网上也有其他相关的文章，说明至今为止官方仍然没解决 new HttpClient 的使用问题

**Comment by lishewen** [comment]
我这里用你的代码测、无论是ubuntu、centos、还是树莓派，均没有出现你那个异常问题，我在考虑是不是你们Linux环境配置有问题。最近项目在赶进度，等我稍微有点时间的话，我去翻下netcore的源码找下原因

**Comment by lishewen** [comment]
这个问题在1.0RC的时候确实存在，网上的文章也大多是那个时代的评测，我们团队也遇到过这个坑，但随着版本更新已经没这个问题了，每次new的实现和单例实现 性能的差距不到一秒。所以我们团队在2.0的时候已经全部换回每次new的写法了，这样对于新进来的同事也方便理解书写代码

**Comment by 2881099** [comment]
您看看 http://www.cnblogs.com/modestmt/p/7724821.html，这是1.0RC时写的文章嘛？
您不是要说服我一个人就够了的

**Comment by 2881099** [comment]
事实胜于雄辩，那么多人都遇到的问题，就你没遇上那么神奇

**Comment by lishewen** [comment]
我只是路过，就这个问题评论几句，并不是要说服谁。
没遇上过问题的人肯定不会去关注这个问题，所以我相信没遇上问题的肯定比遇上的多

**Comment by 2881099** [comment]
新技术到目前为止，应用.netcore开发项目的少，用.netcore做微信业务的少，用来做大并发重要业务的更少，用于部署linux环境下运行少之又少

按您的逻辑，会有多少人在此提这等问题呢？

**Comment by lishewen** [comment]
从netcore的ctp至今我大概有二十几个项目在用netcore，用这个SDK实现的也有十来个，只有两三个项目是跑在Win2016上的，其他都是在Linux上。其中也不乏 实时公交 这种 对并发和实时响应速度 要求高的项目。正因为如此才选择了Linux+netcore的组合，节省成本、而且综合用下来比Win+传统.net的组合性能上的确高了不少。对于这个问题这么严重，如果在我的项目中存在，我早就被客户喷死了

**Comment by 2881099** [comment]
您的并发量多大？

实例：我们做游戏业务的，之前新游戏上线注册在同一时间点注册，挂了两个多小时

原系统是php的运转了多年都未出问题，出于管理改成.netcore就出这种下等问题

系统没有其他功能，仅仅做一个http中转服务

**Comment by 2881099** [comment]
后来改成单静态变量，至今没有再出过这类错误

**Comment by lishewen** [comment]
1秒内最多有300台车同时上报GPS数据，接收到数据经过解码处理后，马上要通过httpclient转发到web api上，每个数据包 （接收数据 - 解码 - 转发完成）这个过程要压在30毫秒内完成，因为还有其他操作。现在平均24毫秒，还有空间浪

**Comment by 2881099** [comment]
再讨论已经没有意义了
我、朋友同事、其他网友测试都失败
就你测试成功，说我们环境有问题

**Comment by JeffreySu** [comment]
先抛开是不是new HttpClient的问题，全局一个统一的静态变量做这件事情确实弊端非常多，比如有A和B两个并发，他们Request的Headers参数是不一样的，是不是有可能造成A设置完，刚要请求，B修改了设置，结果A按照B的设置请求出去了？

**Comment by 2881099** [comment]
不会吧，msdn文档 https://msdn.microsoft.com/en-us/library/system.net.http.httpclient(v=vs.118).aspx

**Thread Safety**
Any public static (Shared in Visual Basic) members of this type are thread safe. Any instance members are not guaranteed to be thread safe.

**Comment by 2881099** [comment]
除了 HttpClientHandler 貌似没有其他成员设置，所以用了 HttpClientHandler 的应该会有冲突

**Comment by JeffreySu** [comment]
https://github.com/JeffreySu/WeiXinMPSDK/issues/960

**Comment by kchanlee** [comment]
@JeffreySu @2881099 @lishewen 请求头可以放在`HttpRequestMessage`里面设置，然后调用`HttpClient.SendAsync()`，像这样：
```
            using (var request = new HttpRequestMessage())
            {
                request.Headers.Add(...);
                ...
                using (var response = await _httpClient.SendAsync(request))
                {
                    ...
                }
            }
```

**Comment by JeffreySu** [comment]
@kchanlee  那比如之前需要使用HttpClientHandler来临时启用cookie，需要怎么操作呢？

**Comment by kchanlee** [comment]
@JeffreySu 参照这里http://m.blog.csdn.net/kmguo/article/details/31778711 ，cookie的设置也可以挪到`HttpRequestMessage`

**Comment by 2881099** [comment]
@kchanlee

谢谢

**Comment by JeffreySu** [comment]
@kchanlee 那CookieContainer呢？目前的做法是这样的：
```
            var handler = new HttpClientHandler
            {
                CookieContainer = cookieContainer ?? new CookieContainer(),
                UseCookies = true,
            };

            if (cer != null)
            {
                handler.ClientCertificates.Add(cer);
            }

            HttpClient httpClient = new HttpClient(handler);
```

**Comment by 2881099** [comment]
cookiecontainer 有方法，可以根据域名获取cookie字符串，再按照他提供的方法发送

**Comment by JeffreySu** [comment]
@2881099 那样的话可能会有比较多问题，CookieContainer除了发送Cookie，还有接收Cookie等都是自动处理的，这等于要重新封装一个CookieContainer了。

还有另外一个问题就是证书似乎只能通过HttpClientHandler来传递？

**Comment by 2881099** [comment]
请求完后，获取header里set-cookie的值 ，用cookiecontainer 的setcookie方法可以管理进去

**Comment by 2881099** [comment]
证书的话不知道有没其他办法

**Comment by JeffreySu** [comment]
#CookieContainer讨论# 
因为CookieContainer是引用类型很多时候会缓存起来，所以这种更新方式带来的副作用可能会很大，我先试着封装一下看看。

**Comment by mzji** [comment]
asp.net core 2.1 即将引入的[`HttpClientFactory`](https://www.stevejgordon.co.uk/introduction-to-httpclientfactory-aspnetcore)可能有助于解决问题

**Comment by JeffreySu** [comment]
@mzji 很期待

**Comment by lishewen** [comment]
@mzji @JeffreySu #1104 初步修改了一下

**Comment by JeffreySu** [comment]
@lishewen .net core 2.1-p1 之后的版本是否有解决httpcontext实例低效的问题？如果已经解决了或许这里面不需要弄的这么复杂了，直接依赖注入 HttpContextAccessor 就行了。

**Comment by JeffreySu** [comment]
@lishewen  你说的是这个PR吗：https://github.com/JeffreySu/WeiXinMPSDK/commit/ef7fc31fdeb518d79eb29af91d57d61c06b5ff53

**Comment by zhaojunxxx** [comment]
@2881099 
之前httpclient的坑也踩了很多，同样是请求时间超长，今天正好看到这个讨论，用你的代码做了个简单的测试,和你的结果一样，基本都是执行超时，单次执行需要100+秒

然后，我到ie的连接设置里面，局域网设置，去掉了勾选的【自动检测设置】。然后速度就飞起来。 
原因也是在其他文章看到的，关于httpclient使用系统默认proxy设置导致的。
比如 
httpclienthandler.UserProxy=false之类

自己写的代码还能控制，但是对于使用别人的框架，这点就很烦了

**Comment by mzji** [comment]
@zhaojunxxx 要搞定这问题，就只能不用winhttp了……

**Comment by JeffreySu** [comment]
@mzji  那你有具体的建议吗？

**Comment by mzji** [comment]
@JeffreySu 没有什么特别好的思路，靠反射注入？WinHttp的坑还不止这一处，但是因为这个用libcurl又太刚了

**Comment by PurpleForever** [comment]
建议改用IHttpClientFactory

**Comment by John0King** [comment]
@JeffreySu  @PurpleForever https://github.com/dotnet/corefx/issues/32758

**Comment by JeffreySu** [comment]
@John0King 所以你的意思是目前还没有完美的解决方案，但是优先考虑 IHttpClientFactory？

**Comment by PurpleForever** [comment]
微软在2.1加入这个，目前看来就是httpclient的最优解




| |
于驰
邮箱：024hi@163.com
|

签名由 网易邮箱大师 定制

在2018年10月22日 23:30，Jeffrey Su 写道：

@John0King 所以你的意思是目前还没有完美的解决方案，但是优先考虑 IHttpClientFactory？

**Comment by JHinW** [comment]
hi guys:
    good explanations about httpclient from: https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/

**Comment by PurpleForever** [comment]
@John0King 静态HttpClient会有dns不更新的问题。为什么用到DI就是对类库不友好呢？

**Comment by 2881099** [comment]
条件允许就自己写http客户端协议吧，基于TcpClient纯真绿色代码：
https://github.com/2881099/TcpClientHttpRequest

**Comment by John0King** [comment]
@PurpleForever  用到了 DI 就会有 注册， 而注册一般都是特定的 DI框架（`autofac`, `unity` `asp.netcore-core`）. 你是针对特定的DI框架那没问题， 如果你想编写一个 类库，到处跑， 那你怎么用注册 DI ?

**Comment by anhuisunfei** [comment]
@mzji 请教下 Flurl 使用下来如何 还会有大量的 CLOSE_WAIT 的连接吗？

**Comment by mzji** [comment]
> 
> 
> @mzji 请教下 Flurl 使用下来如何 还会有大量的 CLOSE_WAIT 的连接吗？

又转回 HttpClient 了 😂
Flurl 会有反复超时后 CPU 使用率爆炸的问题

**Comment by anhuisunfei** [comment]
> > @mzji 请教下 Flurl 使用下来如何 还会有大量的 CLOSE_WAIT 的连接吗？
> 
> 又转回 HttpClient 了 😂
> Flurl 会有反复超时后 CPU 使用率爆炸的问题

是用 HttpClientFactory 吗

**Comment by mzji** [comment]
> 
> 
> > > @mzji 请教下 Flurl 使用下来如何 还会有大量的 CLOSE_WAIT 的连接吗？
> > 
> > 
> > 又转回 HttpClient 了 😂
> > Flurl 会有反复超时后 CPU 使用率爆炸的问题
> 
> 是用 HttpClientFactory 吗

不是，是原始粗暴的 new 方式，指定 CloseConnection 选项，然后 dispose

**Comment by anhuisunfei** [comment]
> > > > @mzji 请教下 Flurl 使用下来如何 还会有大量的 CLOSE_WAIT 的连接吗？
> > > 
> > > 
> > > 又转回 HttpClient 了 😂
> > > Flurl 会有反复超时后 CPU 使用率爆炸的问题
> > 
> > 
> > 是用 HttpClientFactory 吗
> 
> 不是，是原始粗暴的 new 方式，指定 CloseConnection 选项，然后 dispose
#
这样性能很差的吧

**Comment by mzji** [comment]
> 
> 
> > > > > @mzji 请教下 Flurl 使用下来如何 还会有大量的 CLOSE_WAIT 的连接吗？
> > > > 
> > > > 
> > > > 又转回 HttpClient 了 😂
> > > > Flurl 会有反复超时后 CPU 使用率爆炸的问题
> > > 
> > > 
> > > 是用 HttpClientFactory 吗
> > 
> > 
> > 不是，是原始粗暴的 new 方式，指定 CloseConnection 选项，然后 dispose
> 
> 这样性能很差的吧

因为我们的使用场合不允许我们复用 HTTP 连接和 DNS 请求；每一次请求都必须单开新连接，用完再关闭，所以这个开销是不得不接受的

**Comment by JeffreySu** [comment]
@mzji  @anhuisunfei  @2881099 最近的稳定版中已经采用了新的 HttpClientFactory 的方式，不会再造成此类问题，并且支持CookieContainer、支持证书，可以更新试一下。谢谢大家的讨论！
