### ISSUE TITLE
经测试，StackExchange.Redis 1.2.6 版本在 linux 并发稍高依然还会报 Timeout 错误，作者有空可改为其他 redis 库

### ISSUE THREAD

**Issue by 2881099** [JeffreySu/WeiXinMPSDK#943]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 发现问题的模块

- [ ] Senparc.Weixin.Cache.Redis 版本：

##### 模块对应的.net版本

- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2017

##### 缓存环境

- [ ] Redis 版本：

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
有其他库推荐的吗？

**Comment by JeffreySu** [comment]
超时的错误是因为SDK的HttpClient引发的，还是StackExchange.Redis引发的？

**Comment by 2881099** [comment]
我的项目运行平台都是 linux
拿.net csredis 改造着在使用，开发了1年多用于多个产品中很稳定

https://github.com/2881099/csredis
刚刚花了点时间升至netstandard2.0，并且也发布到 nuget 中，搜索名：csredis

安装 CSRedisCore 2.0.0 版本

**Comment by 2881099** [comment]
StackExchange.Redis Timeout 和 HttpClient 是两个问题

1、HttpClient 在 linux 平台运行的话，不能每次都 new HttpClient() 来使用，这样写在 win 平台不会有问题，但是 linux 下会经常报错。。HttpClient 的正确使用方法：只定义一个静态全局变量，整个项目使用

2、StackExchage.Redis Timeout 问题从1年多以前就有问题，前几天测 1.2.6 依然有问题，具体原因我也答不上来

**Comment by 2881099** [comment]
最开始也是使用 StackExchange.Redis 作为 redis 驱动，但是第一个产品上线发现经常 Timeout，尝试很多方法改造都没用

1、网上说单例模式，我改成单例，还是Timeout
2、我按自己的思想定义一个Pool保存 ConnectionMultiplexer，还是Timeout

一度陷入坑中，这时还好找到了 csredis，改造成 .net core 不算复杂，就这样度过了一劫

话说回来，csredis 的源码写得很绿色干净，改起来读起来都容易很多。。压测性能也很高

**Comment by 2881099** [comment]
Senparc 核心代码请求上游链接，在 .netcore 平台每次都 new HttpClient()，在 linux 运行有隐患
这个问题在之前公司的一个很重要的项目中被坑得很惨

**Comment by JeffreySu** [comment]
明白了，非常感谢反馈，我们会跟进处理。

领：是不是csredis可以完全取代目前的SE.redis？

**Comment by 2881099** [comment]
是的，性能有过之而无不及，稳定性更加可靠
您可以对比两个驱动的源码，csredis 更加简洁易懂

stackexchange.redis 看着头晕，一点都改不动

另外：HttpClient 的问题希望您尽快改正发布版本，谢谢

**Comment by JeffreySu** [comment]
明白了 👬

**Comment by JeffreySu** [comment]
@2881099 因为还要考虑到.net core以外项目的调用，是否有兼容.net和.net core的csredis？

**Comment by 2881099** [comment]
@JeffreySu 

兼容 .net 4.6+，.net core 1.0+。

如果想兼容最好，建议不直接使用 redis，采用 IDistributedCache 注入现实的方式。
即 Senparc.Weixin 不再直接使用 redis 库，IDistributedCache 的现实方式可以是 redis、mongodb、sqlserver、mysql、甚至内存。

**Comment by JeffreySu** [comment]
但是 IDistributedCache 同样不支持低版本吧

**Comment by 2881099** [comment]
这样等于把问题留给外部了呀，锅不在 Senparc.Weixin，用户自己承担后果

**Comment by JeffreySu** [comment]
@2881099  哈哈，我主要是在考虑兼容性的问题，如果用两套机制会有很多麻烦事情。
.net core的我会考虑下怎么处理，这个issue我会继续跟进，如果你有更好的想法欢迎继续交流！

**Comment by JeffreySu** [comment]
@2881099  StackExchange.Redis 之前已经升级到最新的版本，目前应该不会有病的问题了

**Comment by CharlesZHENG** [comment]
苏老师，现在StackExchange.Redis还有timeout的问题吗？

**Comment by JeffreySu** [comment]
@CharlesZHENG  我们暂时没有碰到这样的问题，你有详细的日志记录吗？

**Comment by CharlesZHENG** [comment]
1）今天有朋友遇到这个问题，测试时流量激增，确实存在。
2）异常：
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: SET chaunce:0f7a5209-7346-4eda-a189-52a6974d943c; It was not possible to connect to the redis server(s). To create a disconnected multiplexer, disable AbortOnConnectFail. ConnectTimeout; IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=25,Free=32742,Min=4,Max=32767), Local-CPU: n/a ---> StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s). To create a disconnected multiplexer, disable AbortOnConnectFail. ConnectTimeout
3）问题讨论：https://github.com/StackExchange/StackExchange.Redis/issues/1120
4）解决参考：https://docs.microsoft.com/zh-cn/azure/azure-cache-for-redis/cache-how-to-troubleshoot

**Comment by JeffreySu** [comment]
上面给的解决参考里面，没看出来最后这个方法有一个处理的定论吗？
我觉得是时候考虑换一个第三方插件了

**Comment by JeffreySu** [comment]
@CharlesZHENG 还有一个问题，我记得新版本的SE已经提供了比较好的异步处理能力了，你确认一下使用的版本是什么？

**Comment by CharlesZHENG** [comment]
1）遇到的问题是“流量激增”引发的问题，测试时把ThreadPool的min值由原来的4设置为较大的数比如1000（只是为了测试），就好了。
2）是最新的版本。SE有异步处理。推测：流量激增时，假设激增之前线程池中只有4个线程，流量突然大量涌入，线程池中线程不够用，产生新线程进入线程池，500ms产生一个，但产生速度还是太慢，就处理不过来报timeout了。

**Comment by CharlesZHENG** [comment]
官方文档这样说的：
Note that StackExchange.Redis can hit timeouts if either the IOCP threadss or the worker threads (.NET global thread-pool, or the dedicated thread-pool) become saturated without the ability to grow.
文档地址：https://github.com/StackExchange/StackExchange.Redis/blob/master/docs/Timeouts.md

**Comment by 2881099** [comment]
@CharlesZHENG 你这样测试是理想情况，还有一种被动情况。
我们都知道redis是单线程的，容易阻塞，即便非常短暂的阻塞也会导致超时。
因为se时单连接多路复用的，服务器随便阻塞都很容易群体超市。

**Comment by 2881099** [comment]
感觉苏总项目没必要强依赖redis组件，可以抽象出来简单点让用户自己实现

**Comment by JeffreySu** [comment]
@2881099 有没有支持 .netstandard 2.1 和 .net core 3.0 的打算？我们已经计划这个月要上了。

**Comment by 2881099** [comment]
@JeffreySu 
苏总，netstandard 2.1 不能引用 2.0 的包吗？应该可以啊
.net core 3.0 应该也能引用 netstandard 2.0 的包。

netstandard 2.0 可以能引用在 .net framework 4.6.1+ 或 .net core 2.0+ 的运行环境

![image](https://user-images.githubusercontent.com/16286519/65115015-fb7fb900-da19-11e9-86ed-4b2a1049af90.png)

![image](https://user-images.githubusercontent.com/16286519/65115035-ffabd680-da19-11e9-81a3-5445ea69cf01.png)

![image](https://user-images.githubusercontent.com/16286519/65115063-06d2e480-da1a-11e9-860e-a16f778dd9c6.png)

编译能通过

**Comment by JeffreySu** [comment]
@2881099 是可以的，我只是问一下你们有没有上的打算，因为 3.0 的新接口还是挺多的

**Comment by 2881099** [comment]
@JeffreySu 哦哦，目前失业状态，没有项目可上，哈哈

**Comment by JeffreySu** [comment]
@2881099 如果有什么想法可以一起探讨一下 😄

**Comment by 2881099** [comment]
@JeffreySu 可以可以，向苏总学习

**Comment by JeffreySu** [comment]
已发布 Senparc.Weixin.Cache.CsRedis 已，感谢 @2881099 !
