### ISSUE TITLE
更新部门成员和上传图片报错-路径中具有非法字符。

### ISSUE THREAD

**Issue by tangyangming** [JeffreySu/WeiXinMPSDK#948]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述

MailListApi.UpdateMember(GetContactToken(), userId, null, mobile);
MediaApi.Upload(GetContactToken(), UploadMediaFileType.image, imagePath);
都是同样的错误"路径中具有非法字符。",在上一版本没问题

都是通过nuget安装最新版版本

##### 发现问题的模块
- [x] Senparc.Weixin.Work 版本：

##### 模块对应的.net版本
- [x] .net 4.5

##### 开发环境
- [x] Visual Studio 2015

##### 缓存环境
- [X] 服务器内存缓存（默认）

##### 联系方式
Email：tangyangming@qq.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
imagePath是怎么写的？

**Comment by tangyangming** [comment]
与imagePath没关系,更新成员也是报这个错.而且上一版本是可以的,通过nuget引用的

**Comment by JeffreySu** [comment]
有一点关系的，你发给我。

**Comment by tangyangming** [comment]
这种地址,头像地址,服务器可以正常访问这个目录的,
\\172.20.22.87\DCS_Upload\emp_photo\C040516.jpg

**Comment by tangyangming** [comment]
\\\172.20.22.87\DCS_Upload\emp_photo\" + empCode + ".jpg

**Comment by JeffreySu** [comment]
试一下用完整的物理路径。

**Comment by tangyangming** [comment]
获取今天更新的版本已可以用了.

**Comment by JeffreySu** [comment]
谢谢反馈！
