### ISSUE TITLE
如何判断下载的媒体文件的格式

### ISSUE THREAD

**Issue by KevinPan** [JeffreySu/WeiXinMPSDK#95]
通过MediaApi.Get接口下砸的媒体是只能得到一个Stream，能否判断文件的格式？
微信官方的接口返回的Http头信息会有Content的相关信息：
Content-Type: image/jpeg 
Content-disposition: attachment; filename="MEDIA_ID.jpg"

**Comment by JeffreySu** [comment]
你的mediaId当初是传什么类型上去的，下载下来就是对应的。对于Head的处理我们会在新版本中跟进。
如果您已经有最新的代码，欢迎pull request过来。
非常感谢！
@TYSZCC

**Comment by JeffreySu** [comment]
此功能后来已经改进，刚才也已在最新版本中更新到稳定版，MP v14.8.13，https://github.com/JeffreySu/WeiXinMPSDK/commit/c5cb2017b30cb41ebe1d43bcd2c54b0a8175e712
谢谢！
