### ISSUE TITLE
Could not find a part of the path "/cgi-bin/gettoken?corpid=xxxxx&corpsecret=xxxx 异常

### ISSUE THREAD

**Issue by pigwing** [JeffreySu/WeiXinMPSDK#951]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述

Senparc.Weixin.WxOpen 1.2.2的时候,在mono下是没问题的.但是更新了到1.2.4的时候.后台就报出Could not find a part of the path "/cgi-bin/gettoken?corpid=xxxxx&corpsecret=xxxx
这个异常信息导致无法推送消息

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [x] Senparc.Weixin.WxOpen 版本：1.2.4
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [x] mono 5.4.1.6

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [x] Visual Studio 2015
- [ ] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
已经修复，请下载最新的源代码或者直接从Nuget更新。

**Comment by JeffreySu** [comment]
您说的是Senparc.Weixin.Work吗？WxOpen没有这个接口。
如果是Work的话已经修复了，发布了新的版本，请看一下。

**Comment by JeffreySu** [comment]
可以直接更新源文件编译或者直接从Nuget更新。

**Comment by pigwing** [comment]
是的.是work下的.

**Comment by JeffreySu** [comment]
已经发布新版本了，麻烦给我们一下反馈，方便我们跟进，谢谢！

**Comment by JeffreySu** [comment]
@pigwing

**Comment by JeffreySu** [comment]
@pigwing  很长时间没有答复，我先关闭了，如果有任何问题可以Reopen，谢谢！
