### ISSUE TITLE
Senparc.Weixin.MP.AdvancedAPIs.MediaApi.Get #928

### ISSUE THREAD

**Issue by tangyangming** [JeffreySu/WeiXinMPSDK#954]
Senparc.Weixin.MP.AdvancedAPIs.MediaApi.Get #928

**Comment by tangyangming** [comment]
12月1日更新的版本依旧没有解决这个问题,麻烦看下

https://github.com/JeffreySu/WeiXinMPSDK/issues/928

**Comment by JeffreySu** [comment]
已经列入计划了，预计会在下个版本发布，如果你那边有已经修改好的可以Pull Request过来

**Comment by JeffreySu** [comment]
基础库  v4.18.7 调整HttpUtility.Get.Download(string url, string filePathName)，改为输入完整文件路径+文件名。感谢 @tangyangming #928 #954
