### ISSUE TITLE
是否可以支持Xamarin跨平台开发

### ISSUE THREAD

**Issue by ghd258** [JeffreySu/WeiXinMPSDK#958]
支持Xamarin跨平台开发就必须能有netstandard2.0库

**Comment by lishewen** [comment]
netcore版本系支持netstandard2.0标准的

**Comment by ghd258** [comment]
理论上是支持的，但是实际是不行了，dll根本就无法引用，你建立一个跨平台就知道了

**Comment by ghd258** [comment]
只能引用netstandard2.0版本的dll

**Comment by lishewen** [comment]
https://www.nuget.org/packages/Senparc.Weixin/

引用nuget包是支持netstandard2.0，你单独下编译好的DLL的话那个DLL好像是.net 4.5的

**Comment by lishewen** [comment]
不想使用nuget的话，或者你可以自己下源码编译你需要版本的dll，又或者从nuget的压缩包里面独立拆DLL出来

**Comment by John0King** [comment]
@ghd258   Xamarin 是优先选择 .net 45 还是 .net standard 2.0  ?

**Comment by ghd258** [comment]
.net standard 2.0
