### ISSUE TITLE
`HttpClient`的使用方式不太恰当，应尽可能地重用

### ISSUE THREAD

**Issue by kchanlee** [JeffreySu/WeiXinMPSDK#960]
##### 问题描述
在当前代码里（比如[这里](https://github.com/JeffreySu/WeiXinMPSDK/blob/0679fd1172badf78823c6b77cda41616b0aecd3b/src/Senparc.Weixin/Senparc.Weixin/Utilities/HttpUtility/RequestUtility.Post.cs)），`HttpClient`被用来发送请求。然而，其使用方式却似乎不太恰当。

1. `HttpClient`是可重用的。当前代码对每一个request都`new`一个`HttpClient`来处理，这会对性能产生影响。可参考以下两个链接：
https://stackoverflow.com/questions/22560971/what-is-the-overhead-of-creating-a-new-httpclient-per-call-in-a-webapi-client
https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/

2. `HttpClient`实现了`IDisposable`。一般来说，一个`IDisposable`实例用完之后应该`Dispose()`。

##### 发现问题的模块

- [x] Senparc.Weixin 版本：commit 0679fd1172badf78823c6b77cda41616b0aecd3b
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [x] .net 4.5
- [x] .net 4.6.1
- [x] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [ ] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
谢谢反馈！这里已经在讨论了：https://github.com/JeffreySu/WeiXinMPSDK/issues/942，欢迎先看完之前讨论得内容加入讨论。

**Comment by 2881099** [comment]
对了，今天微信返回一个错误，我觉得是 HttpClientHeader 这个函数引起的，所以我直接 return; 了

分析原因大概如下：

由于改成了单例模式，sdk 对 DefaultRequestHeaders 设置了默认请求头会影响全局。
微信每次请求几乎独立，不需要承载上一次请求头，承载了反而可能有问题

**Comment by lishewen** [comment]
请求头是有讲究的，曾经有几次修改就是改请求头才正常的。
比如 上传文件时需要 multipart/form-data 的头，微信那边才能正常识别文件，而不会导致上传文件为空
还有些场景必须要保证有 text/xml 的头，才不会导致 Request.Body 的返回为空
承载上一次请求头可以用于一些上下文的场景

**Comment by kchanlee** [comment]
@2881099 @lishewen 请求头可以放在`HttpRequestMessage`里面设置，然后调用`HttpClient.SendAsync()`，像这样：
```
            using (var request = new HttpRequestMessage())
            {
                request.Headers.Add(...);
                ...
                using (var response = await _httpClient.SendAsync(request))
                {
                    ...
                }
            }
```

**Comment by JeffreySu** [comment]
@2881099 @lishewen  现在的问题是Header里面的内容，不是每次都相同的，所以直接设置的话并发的时候应该会有很多坑。
