### ISSUE TITLE
错误代码：48004，说明：api forbidden for irregularities, view detail on mp.weixin.qq.com hint: [3Iicga0054vr43!]

### ISSUE THREAD

**Issue by zariczhu** [JeffreySu/WeiXinMPSDK#961]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述
生成二维码的时候
Senparc.Weixin.Exceptions.ErrorJsonResultException: 微信Post请求发生错误！错误代码：48004，说明：api forbidden for irregularities, view detail on mp.weixin.qq.com hint: [.IS_da0192vr47!]
   at Senparc.Weixin.HttpUtility.Post.GetResult[T](String returnText)
   at Senparc.Weixin.CommonAPIs.CommonJsonSend.Send[T](String accessToken, String urlFormat, Object data, CommonJsonSendType sendType, Int32 timeOut, Boolean checkValidationResult, JsonSetting jsonSetting)
   at Senparc.Weixin.MP.AdvancedAPIs.QrCodeApi.<>c__DisplayClass0_0.<Create>b__0(String accessToken)
   at Senparc.Weixin.MP.ApiHandlerWapper.TryCommonApi[T](Func`2 fun, String accessTokenOrAppId, Boolean retryIfFaild)

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：4.5.20.25374
- [ ] Senparc.Weixin.MP 版本：13.8.4.26917
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：1.6.5.36610
- [ ] Senparc.Weixin.QY 版本：
- [ ] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [] .net 4.5
- [x] .net 4.6.1
- [ ] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [x ] Visual Studio 2015
- [x ] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：78171485@qq.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
测试没有发现这个问题，把你的参数发上来一下

**Comment by JeffreySu** [comment]
是不是你的1000217501超出int范围了

**Comment by zariczhu** [comment]
没有超出范围，我自己也测了　这个数字是可以转换的。然后我发现个现象　是因为这个公众号里的生成带参数的二维码 是 0/0，但是正常的一般是 0/100000
![image](https://user-images.githubusercontent.com/8265166/33885954-48900486-df88-11e7-8607-838dffc73ecb.png)

**Comment by JeffreySu** [comment]
我是说你的参数“1000217501”超出官方要求的int(32)的范围了，减少一些位数看看。

你给的截图是调用次数，和int限制没关系。

**Comment by zariczhu** [comment]
没有超出int32呢,我debug了，那里没有报错

**Comment by JeffreySu** [comment]
仔细看了下，是没超，那应该就是0/0没有权限的问题了。
