### ISSUE TITLE
关注后扫描二维码，Scan事件无法触发

### ISSUE THREAD

**Issue by ihugang** [JeffreySu/WeiXinMPSDK#963]
微信后台的二维码，无参数，在首次扫描关注正常，在后面再扫描时，**无法进入ScanRequest事件**，打印原始的xml数据也没有，奇怪啊，以前老的版本没有发生过这种情况。

windows 2016, IIS

**Comment by JeffreySu** [comment]
已经关注的是进subscribe事件，请参考官方文档。

**Comment by ihugang** [comment]
我写了日志，再次扫描也没有进入subscribe事件。

**Comment by JeffreySu** [comment]
把你测试的行的和后面不行的日志发上来一下，如果还需要后续交流，请Reopen。
