### ISSUE TITLE
SendNews通过传递AccessToken来调用时失败

### ISSUE THREAD

**Issue by lei467** [JeffreySu/WeiXinMPSDK#964]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述

1. 已在Global.asax文件的 Application_Start中用Senparc.Weixin.Work.Containers.AccessTokenContainer.Register(CorpId,CorpSecret);进行全局注册。
2. 通过AccessTokenContainer.TryGetToken(CorpId, CorpSecret); 成功获取了accessToken。
3. 在需要调用 SendNews文法的地方，用Senparc.Weixin.Work.AdvancedAPIs.MassApi.SendNews(CorpId,agentId, listArticle)方式调用成功。

4.问题在于用上述获得到的accessToken来调用 
Senparc.Weixin.Work.AdvancedAPIs.MassApi.SendNews(accessToken,agentId, listArticle)时报错如下

此appId（mwZk0rgQ0ZlbWXi_38Hg2eviyPYSSYmjnrMIAVEMx2Y4hWJGvQYx1vXIrpSGioRyB5YGvV1e0HwS2_LTJAufgzTjWbh0DG1ZCkzJmTKQ）尚未注册，请先使用AccessTokenContainer.Register完成注册（全局执行一次即可）！模块：Work

##### 发现问题的模块

- [ ] Senparc.Weixin.Work 版本：1.2.5

##### 模块对应的.net版本

- [x] .net 4.5

##### 开发环境

- [ ] Visual Studio 2015

##### 缓存环境
IIS

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
麻烦您测试一下，是只有SendNews出现这个情况还是其他高级接口也会有这个问题。
这个应该是AccessToken长度的判断问题。

**Comment by lei467** [comment]
1. 我上面报错中的accessToken太长了没有贴完（长度应该是214）；
2. 我上午测试了SendNews，GetMember，GetKFList三个高级接口，报一样的错（下面是完整的报错示例）

测试高级接口-SendNews报错：此appId（fM5CruClicaXYpz9vai-nl2lB2V-S25Yed_BDmd8sl6P1vBvExBnfoYbOrYAMEawhZc5bhX1mu0nVJilrBxXyeAs-7y70gkwJIEXVrk4JvfFaDJP6GdWBDYq5l6tqfL8megghLqDHLXPsdokIJ6UmXrb8buPEUgdKPNWXNJKVeq32uqB54OaAnxNkQVK-MtbI_QgNT4grhUhuIbYak_7Gg）尚未注册，请先使用AccessTokenContainer.Register完成注册（全局执行一次即可）！模块：Work  
 在 Senparc.Weixin.CommonAPIs.ApiHandlerWapper.ApiHandlerWapperBase.TryCommonApiBase[T](PlatformType platformType, Func`1 accessTokenContainer_GetFirstOrDefaultAppIdFunc, Func`2 accessTokenContainer_CheckRegisteredFunc, Func`3 accessTokenContainer_GetAccessTokenResultFunc, Int32 invalidCredentialValue, Func`2 fun, String accessTokenOrAppId, Boolean retryIfFaild)
   在 Senparc.Weixin.Work.ApiHandlerWapper.TryCommonApi[T](Func`2 fun, String accessTokenOrAppKey, Boolean retryIfFaild)
   在 Senparc.Weixin.Work.AdvancedAPIs.MassApi.SendNews(String accessTokenOrAppKey, String agentId, List`1 articles, String toUser, String toParty, String toTag, Int32 safe, Int32 timeOut)
   在 Program_Qyh_BusinessWorks.gvBusinessWorkList_RowCommand(Object sender, GridViewCommandEventArgs e)Senparc.Weixin

**Comment by JeffreySu** [comment]
看了一下逻辑，代码应该不会进入到这个逻辑里面，你确定用的Senparc.Weixin.dll是最新的吗？

**Comment by JeffreySu** [comment]
已经添加了单元测试，没有发现问题。

**Comment by lei467** [comment]
@JeffreySu   今天更新最新的NuGet包后问题已解决！非常感谢！
