### ISSUE TITLE
GetMenuResultFull结构错误，导致Json反序列化失败

### ISSUE THREAD

**Issue by AxisRay** [JeffreySu/WeiXinMPSDK#969]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述

通过CommonApi.GetMenu()方法获取菜单结构
始终返回Null
原因是GetMenuResultFull结构错误，多了一级结构menu
将
```csharp
    public class GetMenuResultFull : WorkJsonResult
    {
        public MenuFull_ButtonGroup menu { get; set; }
    }
```
修改为
```csharp
    public class GetMenuResultFull : WorkJsonResult
    {
        public List<MenuFull_RootButton> button { get; set; }
    }
```
问题解决

##### 微信官方文档 URL
https://work.weixin.qq.com/api/doc#10786

##### 微信官方文档快照（直接复制关键内容到下方）
没有menu这一级
{
   "button":[
       {    
           "type":"click",
           "name":"今日歌曲",
           "key":"V1001_TODAY_MUSIC"
       },
       {
           "name":"菜单",
           "sub_button":[
               {

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [x] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [ ] .net 4.5
- [ ] .net 4.6.1
- [x] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：rayleesky@outlook.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
#973
