### ISSUE TITLE
AccessToken获取API接口地址错误，导致AccessToken获取失败

### ISSUE THREAD

**Issue by AxisRay** [JeffreySu/WeiXinMPSDK#981]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述

![image](https://user-images.githubusercontent.com/6546326/34112214-dd3aec46-e446-11e7-897e-4c31becc5172.png)

[2017/12/18 22:47:46] MessageHandler Error:Senparc.Weixin.Exceptions.MessageHandlerException: MessageHandler中Execute()过 程发生错误：Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
         at Senparc.Weixin.Work.Containers.AccessTokenContainer.GetTokenResult(String appKey, Boolean getNewToken)

##### 微信官方文档 URL

https://work.weixin.qq.com/api/doc#10013/%E7%AC%AC%E4%B8%89%E6%AD%A5%EF%BC%9A%E8%8E%B7%E5%8F%96access_token
##### 微信官方文档快照（直接复制关键内容到下方）

第三步：获取access_token
请求方式：GET（HTTPS）
请求URL：https://qyapi.weixin.qq.com**/cgi-bin/**gettoken?corpid=ID&corpsecret=SECRECT
注：此处标注大写的单词ID和SECRET，为需要替换的变量，根据实际获取值更新。其它接口也采用相同的标注，不再说明。

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [x] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [ ] .net 4.5
- [ ] .net 4.6.1
- [x] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：rayleesky@outlook.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by AxisRay** [comment]
很糟心
：（

**Comment by JeffreySu** [comment]
已解决
