### ISSUE TITLE
既然允许自定义API接口，建议增加相关的异常处理吧

### ISSUE THREAD

**Issue by AxisRay** [JeffreySu/WeiXinMPSDK#983]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

##### 问题描述

#946 允许自定义API域名
我不太理解这个改动的价值，但是既然允许自定义，我建议增加相关的异常处理吧
#981 直接报NullReference，给排查带来比较大的困难，微信那边也没报404
![image](https://user-images.githubusercontent.com/6546326/34113619-4441f69c-e44b-11e7-97db-8fa64b7f1f97.png)

##### 发现问题的模块

- [ ] Senparc.Weixin 版本：
- [ ] Senparc.Weixin.MP 版本：
- [ ] Senparc.Weixin.MP.MVC 版本：
- [ ] Senparc.Weixin.Open 版本：
- [ ] Senparc.Weixin.QY 版本：
- [x] Senparc.Weixin.Work 版本：
- [ ] Senparc.Weixin.WxOpen 版本：
- [ ] Senparc.Weixin.Cache.Redis 版本：
- [ ] Senparc.Weixin.Cache.Memcached 版本：
- [ ] 其他模块：

##### 模块对应的.net版本

- [ ] .net 3.5（已经停止更新）
- [ ] .net 4.0（已于2017年7月暂时停止更新）
- [ ] .net 4.5
- [ ] .net 4.6.1
- [x] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [x] Visual Studio 2017
- [ ] 其他：

##### 缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

##### 联系方式
Email：

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
按理说不会引发这个问题，是有默认值的。

这个接口一方面为了兼容用户自定义的平台（按照微信标准），另外可以支持国际版API

**Comment by JeffreySu** [comment]
有一种可能是你的corpXX传入Null了，是否可能存在这个问题？

**Comment by szw2003** [comment]
@AxisRay 有存在上面说的问题吗？

**Comment by JeffreySu** [comment]
@AxisRay 如果还有问题请回复并 Reopen 这个 issue，谢谢！
