### ISSUE TITLE
企业号 缺了“获取应用概况列表”接口

### ISSUE THREAD

**Issue by bemguin** [JeffreySu/WeiXinMPSDK#99]
官方文档在这里：
http://qydev.weixin.qq.com/wiki/index.php?title=%E8%8E%B7%E5%8F%96%E5%BA%94%E7%94%A8%E6%A6%82%E5%86%B5%E5%88%97%E8%A1%A8

**Comment by TYSZCC** [comment]
此方法在AdvancedAPIs/App/AppApi.cs文件下，请查看
