### ISSUE TITLE
企业付款到银行卡接口没有开发

### ISSUE THREAD

**Issue by chinanhb** [JeffreySu/WeiXinMPSDK#995]
(*** 此版块专为反馈bug及提交需求服务，不负责解答开发问题，请勿发表开发问题，
如果您需要这方面的帮助，请移步`问答社区`：https://weixin.senparc.com/QA ***)

 问题描述
微信支付后台开通企业付款到银行卡功能，现有的sdk只有企业付款到用户（openid）的功能。

微信官方文档 URL
https://pay.weixin.qq.com/wiki/doc/api/tools/mch_pay.php?chapter=24_1&index=1

微信官方文档快照（直接复制关键内容到下方）

企业付款到银行卡介绍
微信支付已上线企业付款至银行卡功能。商户可以将商户号余额付款至指定的收款银行账户。通过指定收款银行账户户名、卡号，以及收款银行信息即可实现付款。功能目前为灰度开放，已灰度新资金流直连普通商户及普通受理模式子商户，其他商户类型将在后续开放。
以下为功能说明，请仔细阅读：
1.企业付款至银行卡只支持新资金流类型账户
2.目前企业付款到银行卡支持17家银行，更多银行逐步开放中
3.付款到账实效为1-3日，最快次日到账
4.每笔按付款金额收取手续费，按金额0.1%收取，最低1元，最高25元, 
如果商户开通了运营账户，手续费和付款的金额都从运营账户出。如果没有开通，则都从基本户出。
5.每个商户号每天可以出款100万，单商户给同一银行卡付款每天限额5万
6.发票：在账户中心-发票信息页面申请开票的商户会按月收到发票（已申请的无需重复申请）。
企业付款到银行卡发票与交易手续费发票为拆分单独开具。

发现问题的模块

- [√ ] Senparc.Weixin.MP 版本：
- [ √] Senparc.Weixin.MP.MVC 版本：

模块对应的.net版本

- [ √] .net 3.5（已经停止更新）
- [ √] .net 4.0（已于2017年7月暂时停止更新）
- [√] .net 4.5
- [√] .net 4.6.1
- [ √] .net core

##### 开发环境

- [ ] Visual Studio 2010
- [ ] Visual Studio 2010 (SP1)
- [ ] Visual Studio 2012
- [√ ] Visual Studio 2013
- [ ] Visual Studio 2015
- [ ] Visual Studio 2017
- [ ] 其他：

缓存环境

- [X] 服务器内存缓存（默认）
- [ ] Redis 版本：
- [ ] Memcached 版本：
- [ ] 其他

联系方式
Email：13137218818@qq.com

（也可将问题地址及联系方式发送到 www.jeffrey.su@gmail.com）

**Comment by JeffreySu** [comment]
正在进行中，分支：https://github.com/JeffreySu/WeiXinMPSDK/tree/Developer_BankPay
也欢迎推送您的代码到此分支，成为项目的Contributor 🤝

**Comment by JeffreySu** [comment]
已完成，感谢！
