### ISSUE TITLE
Senparc.Weixin.Open.ComponentAPIs.AuthorizerInfo 缺少公众号主体名称属性

### ISSUE THREAD

**Issue by xy109** [JeffreySu/WeiXinMPSDK#998]
##### 问题描述
Senparc.Weixin.Open.ComponentAPIs.AuthorizerInfo 
缺少公众号主体名称属性

##### 微信官方文档 URL
https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1453779503&token=&lang=zh_CN

6、获取授权方的帐号基本信息

##### 发现问题的模块
- [ ] Senparc.Weixin.Open 版本：

##### 联系方式
Email：xy109@qq.com

**Comment by JeffreySu** [comment]
已经更新，感谢！
